tinymce/tinymce

js/tinymce/classes/jquery.tinymce.js, tests/index.html, tests/plugins/jquery_initialization.js
If you initialize multiple instances of tinymce separately with jQuery each one is causing various methods in jQuery to be wrapped, which causes re-wrapping of already-wrapped functions. Repeated enough this can have a severe performance hit.
With this change the jQuery patch will only be applied once.
=> Only apply the jQuery patch once

js/tinymce/classes/html/Schema.js, tests/tinymce/Formatter_apply.js, tests/tinymce/html/Schema.js
- [#7412](http://www.tinymce.com/develop/bugtracker_view.php?id=7412): valid_styles affects the Bold and Italic buttons, although it shouldn't
- [#7413](http://www.tinymce.com/develop/bugtracker_view.php?id=7413): valid_styles breaks the Strike-through button in IE
This fix should be better from the performance point of view than #486.
I'm submitting both options for the project team to decide.
=> alternative fix for bugs 7412 and 7413 related to valid_styles

js/tinymce/plugins/image/plugin.js
Do not merge yet - 2 tests are failing.
Previously, adding an image would always prepend the document_base_url,
which by default includes protocol and hostname, regardless of the
relative_urls setting. However, when relative_urls is set to true, this
is not desired.
WIP: I assume that convertURL does the right thing, and confirmed so
with manual testing, but I can't get the test setup changed so that it
works correctly. 2 tests are failing now:
```
tinymce.plugins.Image - Image recognizes relative src url and prepends relative document_base_url setting....ERROR
tinymce.plugins.Image - Image recognizes relative src url and prepends absolute document_base_url setting....ERROR
```
=> Use editor.convertURL instead of manually converting the URL

js/tinymce/plugins/noneditable/plugin.js, tests/plugins/noneditable.js
Fix bug #6628
* When inserting a noneditable block, first typing car just after insertion was never shown (because moveSelection was called on keyup event, and it has to be called before handlekey to act properly
* When typing some car after inserting a noneditable block, then pressing BACKSPACE, the wrong block was removed (not le last caracter)
See : http://www.tinymce.com/develop/bugtracker_view.php?id=6628 and associate fiddle
=> Fixing bug #6628 and tests

js/tinymce/plugins/table/classes/Dialogs.js
New setting for the table plugin to prevent displaying appearance options that could also be configured by using classes
=> added setting table_appearance_options 

js/tinymce/plugins/paste/classes/WordFilter.js
While I agree that comment references, comment text and pre-marked "to be deleted" elements shouldn't be pasted into the editor, captions are visible elements in the document that are usually titles of figures or tables and should be able to be pasted.
=> Removed "MsoCaption" Node Class Filter

js/tinymce/plugins/noneditable/plugin.js
These bugs occured for complex, block-level nonEditables (meaning they have child nodes which are not non-editable themselves):
1. Before it was not possible to move over/through nonEditables using up and down.
2. It was possible to remove parts (child nodes) of nonEditables, rather than the complete nonEditable, as it would be expected.
3. If one nonEditable was followed by another, there was no way to navigate between them.
There is still a bug when dropping/pasting on nonEditables, which can be fixed using the paste-plugin preprocess function (select the whole nonEditable and replace it with the drop/paste content)
=> Fix up/down movement and delete/backspace handling for complex nonEditables

js/tinymce/classes/ui/ColorButton.js, js/tinymce/plugins/textcolor/plugin.js
There's somewhat confusing behavior if you select "no color", because the preview element keeps the previously selected color.
I don't know whether this was done by design but the fix is trivial (if one is needed at all).
Maybe the default style for the preview element's background color will have to be updated to 'transparent' as well.
=> Textcolor: Treat removal like color selection

js/tinymce/plugins/paste/classes/WordFilter.js
One of the unicode characters in the list ('\u00d8') was the Norwegian and Danish letter 'Ø'.
This caused sentences starting with an Ø to become unordered lists when pasted from Word.
=> Fixed bug in paste filter for Word list detection

js/tinymce/classes/ui/ListBox.js
I think the test on settings.value is useless.
It broke my own code, because I'm providing a full list of items, one having the 'selected' flag to true, but I don't provide a settings.value
=> Fix selected item when no settings.value provided

js/tinymce/plugins/charmap/plugin.js
The charmap plugin actually lists 251 items, only a matrix of 25x10 was shown.
I changed the code to calculate the height of the matrix, preventing the last cells that are needed as a filler from being clicked.
Below the big character you get as a preview on the right I added the label of the character because there are a large number of "invisible" characters like half-space, non-breaking.space etc.
Hoping you can merge this back.
Regards,
Jelle
=> Fixed charmap plugin to show all configured characters

js/tinymce/plugins/link/plugin.js
Set only to default_link_target if creating new link
If editing an existing link without target it is misleading to have the default_link_target selected as target
=> Link target fix

js/tinymce/classes/ui/MessageBox.js
You can see the broken docs online by looking at http://www.tinymce.com/wiki.php/api4:namespace.tinymce.ui and seeing the fact that tinymce.ui.Window shows up where MessageBox ought to be, and it is a broken link.
=> Fixing typo which breaks auto-generated docs

js/tinymce/classes/EditorManager.js
For the domain
dev.minesplus.netanswer.fr
the 
src.indexOf('.min') != -1
does not work because the domain contains ".min".
With this commit, only the filename is tested, not the whole path
=> Fix bug for domains containing ".min"

js/tinymce/plugins/link/plugin.js
The `link` plugin shows a message when the user forget to put the 'http://' before the link. 
But when the user put something like "www2.walmart.com.br" the plugin don't shows the message.
=> improving validation of external links to accept a number after 'www'

js/tinymce/plugins/imagetools/classes/Plugin.js
In the Imagetools plugin, the remote image loading part seems to be broken. It always attempt to request `?url=` instead of `<imagetools_proxy>?url=<img.src>`. This pull request fixes the issue by correcting the proxied image url.
=> Fixed issue with loading remote image with proxy in Imagetools plugin

jscripts/tiny_mce/classes/Editor.js
This makes the code a little clearer in `nodeChanged` by removing an
unnecessary level of indentation.
=> return immediately from nodeChanged when editor is not initialized

js/tinymce/classes/util/Quirks.js
Mac OS X Chrome: non printable control characters are sent as keypress events
https://jsfiddle.net/19foy6oz/
Try typing in Ctrl+C, Ctrl+Q, Ctrl+R
This makes the webkit quirk handler of customDelete trigger deleting the selection.
=> fix control characters deleting selection

js/tinymce/classes/html/Entities.js
```diff
- endoded
+ encoded
```
=> Fix typo in Entities.encodeRaw documentation

js/tinymce/classes/util/XHR.js
There are times where the data sent in the XHR request needs to be modified.
An example of where this is needed can be seen in pull request, #498.  In this example, the plugin does't currently allow the URL to be defined at the time an XHR request is made.  Having a global hook, is a way to access the request even if the plugin hasn't provided for it.
This commit adds a hook before the XHR object is initialised, allowing for the settings to be modified at the time of the request.
```
tinymce.util.XHR.on('beforeInitialize', function(settings) {
if (settings.data) settings.data = settings.data + '&';
settings.data = settings.data + 'foo=bar';
});
```
=> Add global hook into XRH setup of each request

js/tinymce/classes/html/DomParser.js, js/tinymce/plugins/autolink/plugin.js
The autolink plugin works well but does not enable customization of the URL detection pattern to adjust which protocols or URL formats are allowed for automatic link conversion.
This change enables the pattern (as a Javascript Regex object) to be overridden as an editor setting.
=> Enable customization of the autolink URL regex pattern

js/tinymce/classes/html/DomParser.js, js/tinymce/plugins/autolink/plugin.js
In TinyMCE 3.x and 4.x, the matched nodes/attributes of the parser are scoped to the parser and not the parse call which causes the matchedNodes value to be corrupted by plugins that must use the editor's parser within a node filter to modify a node (and still cause the modifications to be run through the parser and other editor-parser-registered node filters).
=> Updated parser to scope match nodes/attributes to the parsing function

js/tinymce/classes/dom/DomQuery.js, js/tinymce/classes/dom/EventUtils.js, js/tinymce/classes/ui/FloatPanel.js
Some changes that break nothing and can be easily accepted, while help maturing Shadow DOM support in future (first 3 commits from #561).
Detailed description to suggested changed:
* Allow appending/prepending elements not only to regular elements (`element.nodeType == 1`), but also to Shadow Root (`element.host` is present and `element.host.nodeType == 1`)
* expect `event.path` to be present and picking first element from there instead of blindly picking `event.target` always; this helps with correct events targeting when target element is within Shadow Tree
* Modal block selection normalized like in other placed, also helps to find proper element when using Shadow DOM (previously it didn't really matter, because everything was withing main DOM Tree, but since it doesn't break anything, …
=> Some non-breaking changes (preparation for Shadow DOM support)

js/tinymce/plugins/paste/classes/Plugin.js
paste plugin doesn't use paste_block_drop setting. Fixing small typo to allow for the use of the paste_block_drop setting.
=> Issue #2278

js/tinymce/plugins/textcolor/plugin.js
If you want to set custom colors, rows or columns for the forecolor and other custom colors, rows or columns for the backcolor now you can :wink:
- ```forecolor_rows```: number of rows for the forecolor. If not setted, it takes the ```textcolor_rows``` instead.
- ```forecolor_cols```: number of columns for the forecolor. If not setted, it takes the ```textcolor_cols``` instead.
- ```backcolor_rows```: number of rows for the backcolor. If not setted, it takes the ```textcolor_rows``` instead.
- ```backcolor_cols```: number of columns for the backcolor. If not setted, it takes the ```textcolor_cols``` instead.
- ```forecolor_map```: map of colors for the forecolor. If not setted, it takes the ```textcolor_map``` instead.
- ```backcolor_map```: map of colors for the backcolor. If not setted, …
=> Added possibility to set different custom colors/rows/columns for forecolor and backcolor

js/tinymce/plugins/paste/classes/WordFilter.js
To reproduce the bug that this change should fix:
1. Create a Word document and add a bulleted list. 
2. For one of the items in the list start the line with a decimal with a leading zero like: 0.5
3. Copy that list and paste it into TinyMCE
Notice that the leading zero and decimal point are removed. 
I've updated the regular expression to look for whitespace after the decimal before trimming.
=> fix bug with pasting leading zeros from word

js/tinymce/classes/EnterKey.js
Fixes Bug #7559
If an inline editor is wrapped in spans, the styles of those spans were
cloned when a new paragraph was created.
This commit fixes this problem.
=> prevents copying styles outside the editor

js/tinymce/classes/SelectionOverrides.js
When selecting a non-editable block containing a table with styles specifying "width: 100%; table-layout:fixed;", the table extends into the visible area on Internet Explorer 11. (Firefox and Chrome appear to limit the width of elements to 1 million pixels, which remains off-screen)
Correcting the height and width specification of the mce-offscreen-selection block ensures that the non-editable table remains offscreen.
The fiddle at https://jsfiddle.net/f6be4b5r/1/ makes the current problem visible.
=> Ensure that the offscreen selection remains offscreen.

js/tinymce/classes/util/Quirks.js
This patch prevents a situation in which for example selecting all and cutting in a WebKit browser will remove typing focus. Whenever a caret node is sought, it should be a pre-requisite that the node in question is still part of the editor's DOM. In some circumstances where the start or end block for a deletion is completely removed, it is still considered as a viable block for restoring caret.
I was not able to come up with a unit test to cover this change because I think the "unfocused" state reached in a side-effect of setting the selection to a DOM node that has been removed from the tree, but the selection "fixes itself up" at least as far as the DOM is concerned. So although from a practical point of view the editor has lost focus, testing the selection with getRng() shows that it …
=> Select all and cut removes focus from editor in WebKit browsers

js/tinymce/plugins/table/classes/Dialogs.js
Fix for issue #2889.
Listbox seems to have an issue when the text attribute is set to a text which is not included in the values. It seems to recognize "Header" as the first entry and doesn't update the text accordingly (because the actual row type is "Header" which is the first item in values). This pull request sets the text to "Header" which seems to solve the issue with the non updating text.
=> Fix table row type select text attribute

js/tinymce/classes/fmt/Hooks.js
Fixed an issue where Array properties would conflict with hook names and cause unexpected results.  Since it is only used as an object, postProcessHooks does not need to be an Array.
=> Changed postProcessHooks from array to object.

js/tinymce/classes/dom/Selection.js, tests/tinymce/dom/Selection.js
Hello,
I fixed a bug that thrown an error if self.win.document was undefined or null in some cases.
=> Security added in getRng method

js/tinymce/classes/ui/SelectBox.js
The SelectBox documentation stated that in order to provide
values to serve as options when the HTML component would be rendered,
a `values` array should be passed, and its items would be used
as option values.
In the code, in `SelectBox.js:55` the property being checked is
`self.options` and there is no occurrence of `self.values` which
probably means that the documentation part was an unfortunate
copy+paste.
Signed-off-by: Adrian Oprea <adrian@codesi.nz>
=> docs: Fix misleading info in SelectBox documentation

js/tinymce/plugins/table/classes/ResizeBars.js
This bug appears when you simply click on the drag-handles in the table plugin which are used to resize the columns or rows of a table. The problem there is that when clicking there is no real resize is happening, the drag-delta is practically 0, but the Table plugin adds lots of with and height css properties to table columns/rows. This should not happen: just producing some garbage css.
The fix is to ignore "drags"/clicks with less than 1 px distance.
=> Fixes: Table plugin: simple clicking on drag-handles in table will add width or height css to cells

js/tinymce/classes/UndoManager.js
Not sure if this is a bug or just a coding style issue, since I'm not familiar with the class-defining framework you're using in this codebase.  But nowhere else do you use `this`, not even in `hasUndo()`, so it would seem that in line 319 it should be `self` also.
=> Being consistent with self vs. this

js/tinymce/classes/html/SaxParser.js, tests/tinymce/html/SaxParser.js
This prevents XSS like https://html5sec.org/#115
=> Conditional comments in IE are case-insensitive

js/tinymce/classes/dom/DOMUtils.js, js/tinymce/classes/ui/DragHelper.js
I opened an issue some months ago but nobody answered to my example (#511).
The first link produces a DOMException, the second doesn't.
Both files are identical.
https://charlesbourasseau.com/invalid-markup-tinymce.xhtml
https://charlesbourasseau.com/invalid-markup-tinymce.html
Please consider to merge this pull request.
=> Prevent invalid markup error

js/tinymce/classes/ui/Path.js
According to https://www.w3.org/TR/wai-aria/states_and_properties#aria-level, aria-level should start at 1, not 0.
=> fix aria-level in element path

js/tinymce/classes/SelectionOverrides.js, tests/tinymce/SelectionOverrides.js
When selecting a `cE=false` block containing a table with style `"width: 100%; table-layout: fixed"`, IE sizes the offscreen selection to the full width of the editor, making it visible and difficult to deal with. Limiting the width of the offscreen selection keeps it hidden, as intended.
=> IE: hide offscreen selection

js/tinymce/classes/Formatter.js, tests/tinymce/Formatter_apply.js
**What are you trying to accomplish with this PR?**
Words with non ascii characters as "Noël" can't be formatted without selecting the full word if the caret is before or after the non ascii character as ë
**How is this accomplished?** 
Use a custom regex that extends the built in \w word character match
Added support for words with unicode characters from À to ſ
http://unicode-table.com/en/#latin-1-supplement
=> Allow word formating of international words

js/tinymce/classes/ui/FormatControls.js
From the official documentation: https://www.tinymce.com/docs/advanced/keyboard-shortcuts/
The functionality already exists, this is just tidiness.
=> Underline on the menu was missing its associated keyboard shortcut label

js/tinymce/classes/fmt/Preview.js
I found an error in "js/tinymce/classes/fmt/Preview.js" whereby the editor instance is not passed to the "parsedSelectorToHtml" function.
This prevented me from adding my own custom element as a "style_formats" option.
=> Bug fix for Preview.js

js/tinymce/classes/file/ImageScanner.js
Basically, the image scanner assumes that any image with `src="blob:..."` has been already processed by tinymce, but that's not have to be the case. That will lead to unfulfilled promises and stalled execution, as mentioned on issue #3357 
This fix seems sensible to me, but I'm not familiarized with the project, so better review it.
=> Fix for images inserted with blob uri

src/plugins/visualblocks/src/main/css/visualblocks.css
We include an own CSS file via `content_css`, wich contains elements with red background and white text color and we have visualblocks enabled by default.
Now the background color gets overwritten to transparent, which results in invisible text (white on transparent).
With this fix, the color is no longer overwritten.
=> Don't overwrite the background color

src/core/src/main/js/html/Entities.js, src/core/src/test/js/browser/html/EntitiesTest.js
Fixing issue #3213 where multibyte characters were not encoded correctly in Named+Numeric.
This also adds unit tests and fixes the messages for the numeric getEncodeFunc tests; they referred to named encoding tests rather than numeric encoding tests.
=> Fixing #3213: Multibyte Characters Not Encoded Correctly in Named+Numeric

src/core/src/main/js/dom/RangeUtils.js
**Bug**
While we have PRE tag at the end of body and when we try to select all the content by pressing Ctrl + A
then some how PRE will not select.
Check on fiddle http://fiddle.tinymce.com/5Tfaab/2
**Environment :**
version : tinymce 4.6.4
Browser : Chrome , Firefox , IE and Safari
=> PRE tag not selected while selecting all the content by pressing Ctrl + A

src/plugins/fullscreen/src/main/js/ui/Buttons.js
Buttons don't have the `shortcut` setting.
=> plugin fullscreen: remove invalid button setting

src/plugins/table/main/ts/ui/Buttons.ts, src/plugins/table/main/ts/ui/MenuItems.ts
The Table plugin uses a direct call to an internal function to open the Table dialog for inserting a table and editing table properties, instead of via the mceInsertTable or mceTableProps commands, preventing these methods from being overridden, which is required for creating a custom Table dialog.
This PR replaces those function calls with a call to the appropriate command.
The PR has passed `grunt test` and `grunt lint`
=> Replace internal table function with mceTableProps command for button and menu item

src/core/main/ts/api/EditorCommands.ts, src/core/test/ts/browser/content/InsertContentCommandTest.ts
Relates to issue #4401
This takes the fix @mwilliamson created in https://github.com/tinymce/tinymce/pull/4402 and adds some basic tests for the insert raw HTML editor command.
Note: Not sure if where I placed the tests is the best location, but it seemed relevant as it's related to inserting content.
=> Fixed the mceInsertRawHTML editor command

src/ui/main/ts/ListBox.ts, src/ui/test/ts/browser/ListBoxTest.ts
Fixed issue #4606 that was causing nested listbox menu items to be shown as not selected.
I believe this was caused by a change in b579b201037e57815a4263064a725d1ef928539e whereby a check was added to ensure the value set is in the list of allowed values in the settings. However that change only looked at the top level items and didn't compare the nested menu items.
=> Fix ListBox menu items not showing as selected

src/plugins/searchreplace/main/ts/core/Actions.ts, src/plugins/searchreplace/test/ts/browser/SearchReplacePluginTest.ts
Fixes #4602 
If a line contained new chars (eg &lt;br /&gt;), then if a search was done with one or more space chars, the find and replace would incorrectly match to those new line chars. This was because find was replacing any whitespace chars in the entered text and replacing them with the '\s' regex matcher (which included matching new lines). That would then cause the find logic to remove the chars after the new lines from view when doing a find and then add additional chars when replacing.
So the fix I've made preserves the logic of replacing whitespace chars, but instead it now only match against whitespaces chars without matching on new line chars.
Note: Not 100% sure it should be replacing whitespace input text with '\s', but I've played it safe and left that alone with the …
=> Fix find and replace not working properly with spaces

src/plugins/paste/main/ts/core/Utils.ts, src/plugins/paste/test/ts/browser/PasteTest.ts
Fixes #4559 
Fixed an issue where "wbr" elements were being transformed into a space when pasting as text, when it should have just been ignored (or at least that's the behaviour Opera, Firefox and Chrome for innerText).
=> Fix wbr elements when paste_as_text is enabled

src/core/main/ts/fmt/RemoveFormat.ts, src/core/test/ts/browser/fmt/RemoveFormatTest.ts
Fixes #4636 
Fixed an issue where trying to remove formatting with a collapsed selection range would throw an exception. This was caused because when a selection isn't made, it determines the range based on the caret position, which internally creates a persistent bookmark. However the remove format logic also uses it's own set of bookmarks and when trying to unwrap those bookmarks it checks to make sure it's not picking up it's own bookmark, but this logic was checking against all bookmark nodes and would therefore try to get a non existent child node.
=> Fixes an exception being thrown when attempting to remove formatting

src/plugins/image/main/ts/core/ImageSelection.ts, src/plugins/image/test/ts/browser/core/ImageSelectionTest.ts
Fixes #4563 
Fixed an issue in the image plugin that caused updating figures to split contenteditable elements. The cause was that DOMUtils constrains `getParents` to all elements below and including the editor root element, which meant that because the editor root element looked like a text node it was trying to split it. So this just constrains the `getParents` call to elements inside the editor root element, but not to include the root element.
=> Fixes an issue inserting images when using inline editors

src/core/main/ts/dom/Position.ts
I have a scenario (angular 7) where the TinyMCE toolbar needs to be attached to the inline editing area if user scrolls up/down while the toolbar is only shown if the editor is focused.
This scenario requires placing a toolbar placeholder div (with position: absolute) just before tinymce div, both present in the angular component. When clicking on an image already present in the HTML editor, image resize handles are shown far below the edited image.
The reason for this is getPos function is skipping offsetParent div element for TinyMCE as it is a second child in a parent component which is not a part of DOM (angular element).
Since performance of this function is not critical (getPos is executed only when selecting an object), scanning for children when traversing parents won't affect the …
=> Image resize handles are shown far below the edited image if fixed_toolbar_container is used

src/plugins/paste/main/ts/core/Clipboard.ts
Resolves #4974
The previous implementation required the editor paste event to be processed within 1 second of the keyboard event. In IE11, the time for the paste event to be processed seemed to differ based on the content in the clipboard and was often > 1 second.
The new implementation only requires that the paste event is on the stack, to eventually be processed, within 100ms of the keyboard event. This approach might not be ideal but looks to be more reliable then the previous implementation.
=> Keyboard paste detection

src/core/main/ts/api/dom/Selection.ts, src/core/main/ts/api/util/Tools.ts, src/core/main/ts/selection/SelectionBookmark.ts
Please refer to TINY-2194 for more information. The issue still persists in 4.x branch, I was not able to check 5.x.
Firefox and edge are only browsers affected, issue is related to tinymce subscribing to whole document events while tinymce editors are removed from DOM by angular framework (invisible).
There is no workaround.
=> TINY-2194 Exception in Firefox if a file input element has focus when tinymce is initialized (4.9.4)

src/core/main/ts/api/dom/Selection.ts, src/core/main/ts/api/util/Tools.ts, src/core/main/ts/selection/SelectionBookmark.ts
The previous PR fix migrated to 5.x and checked in the angular 7 application.
Please refer to pull requests https://github.com/tinymce/tinymce/pull/4732 and https://github.com/tinymce/tinymce/pull/4908 for more information.
=> Exception in Firefox if a file input element has focus when tinymce is initialized (5.0.4)

changelog.txt, src/plugins/link/main/ts/api/Settings.ts, src/plugins/link/main/ts/api/Types.ts, src/plugins/link/main/ts/core/Utils.ts, src/plugins/link/main/ts/ui/Dialog.ts, src/plugins/link/main/ts/ui/DialogConfirms.ts, src/plugins/link/test/ts/browser/AssumeExternalTargetsTest.ts
Instead of overloading `link_assume_external_targets`, as suggested in the issue, a new configuration option is added in order to benefit from TypeScript validation.
Fixes #4335
---
Corresponding documentation PR: https://github.com/tinymce/tinymce-docs/pull/1053.
---
**I am not able to run `grunt test` successfully locally.**
```
$ node_modules/.bin/grunt test
Running "bedrock-auto:phantomjs" (bedrock-auto) task
Verifying property bedrock-auto.phantomjs exists in config...ERROR
>> Unable to process task.
Warning: Required config property "bedrock-auto.phantomjs" missing. Use --force to continue.
Aborted due to warnings.
```
=> Link: Add options 'http' and 'https' to link_assume_external_targets

modules/tinymce/src/themes/silver/main/ts/ui/statusbar/Statusbar.ts
The resize handle on the editor is just a &lt;div>, so it's read to a screen-reader, but the user can't take any action on it. It's possible to use a combination of ARIA attributes and dynamic live-text to allow the user to drag-and-drop the resize handle. But, this is not very useful since a screen-reader user wouldn't have much of a reason to resize the editor in the first place.
This adds aria-hidden to the resize handler so it isn't read aloud and doesn't confuse the user since they cannot interact with it.
=> Add aria-hidden to editor resize handle

.travis.yml, Gruntfile.js
While testings for all browsers currently requires the Tiny private CI infrastructure, we are able to run style checks and the TinyMCE bedrock test suite against Chrome Headless & PhantomJS.
This should provide useful feedback for community PRs ahead of any internal testing at Tiny.
=> Public Travis CI build

Jenkinsfile, modules/tinymce/changelog.txt, modules/tinymce/src/themes/silver/main/ts/ui/dialog/ColorInput.ts
This was causing the colorinput popup to show in the wrong direction, since the button got moved from the right side to the left side in 5.2.0. This also meant that since it only had one direction, the popup would appear offscreen on small screens (eg mobile).
=> TINY-4711: Fixed the `colorinput` popup appearing offscreen on mobile devices

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/image/main/ts/core/Utils.ts, modules/tinymce/src/plugins/image/main/ts/ui/Dialog.ts, modules/tinymce/src/plugins/image/main/ts/ui/DialogInfo.ts, modules/tinymce/src/plugins/link/main/ts/ui/Dialog.ts, modules/tinymce/src/plugins/link/main/ts/ui/DialogConfirms.ts, modules/tinymce/src/plugins/link/main/ts/ui/DialogInfo.ts, modules/tinymce/src/plugins/link/main/ts/ui/sections/LinkListOptions.ts, modules/tinymce/src/plugins/link/test/ts/browser/ListOptionsTest.ts, modules/tinymce/src/plugins/paste/main/ts/core/Clipboard.ts
Just something I threw together while in transit, but this should reduce the minified size of the 3 affected plugins by ~7kb each.
=> TINY-4710: Reduced bundle size of a few plugins by switching to Promises instead of Futures

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/newline/InsertBlock.ts, modules/tinymce/src/core/test/ts/browser/newline/ForcedRootBlockTest.ts
These changes improve the behaviour of applying forced root block attributes to a new block when the previous block has modified or missing attributes.
=> TINY-4564: Fixed `forced_root_block_attrs` setting not applying to new blocks consistently

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/quickbars/main/ts/insert/Picker.ts
Just a quick issue that was very easy to fix, as we were just missing the `accept` attribute on the file input. Fixes #5415 
Note: No tests, as this relies on the native file input so we can't check what it's showing.
=> TINY-4715: Fixed quickimage not restricting the file types to images

modules/tinymce/changelog.txt, modules/tinymce/src/themes/silver/main/ts/modes/Inline.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/InlineToolbarDrawerFloatingPositionTest.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/ToolbarDrawerFloatingPositionTest.ts, modules/tinymce/src/themes/silver/test/ts/module/ToolbarUtils.ts
The cause of this was that we only repositioned when the initial anchor point changed, however we also need to reposition anything in the sink when the height of the inline editor changes.
=> TINY-4725: Fixed the floating toolbar disconnecting from the toolbar when adding content in inline mode

modules/tinymce/Gruntfile.js, modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/init/Init.ts, modules/tinymce/src/core/main/ts/init/Render.ts, modules/tinymce/tools/tasks/bundle.js
This is something we've been discussing for a while now, so I decided to do it while in transit. This will reduce the initial `tinymce.js` load time and allow the icons to be loaded in parallel with everything else which should provide very marginal editor load time improvements.
=> TINY-4729: Changed the default icons to be lazy loaded

yarn.lock
This will fix the IE tests now running in some cases
=> TINY-4713: Upgrade to bedrock 9.5.1

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/table/main/ts/selection/CellSelection.ts
Edge apparently has a bug they introduced in version 44+ whereby the `buttons` property on `mouseover` events is incorrect and always returns `0`. As such there's no reliable way for us to determine if the left mouse key is pressed down anymore on Edge, so we just assume it is for most cases.
Fixes #5056 
Note: I also cleaned up some duplicate code, as the `wrapEvent` code was the same as `DomEvents.fromRawEvent`
=> TINY-3862: Fixed table selection not functioning correctly in Edge 44 or higher

modules/oxide/src/less/theme/components/insert-table-picker/insert-table-picker.less, modules/tinymce/changelog.txt
Quick fix, this makes the table picker use grid layout whenever possible.
Fixes #5430
=> TINY-4728: Fix table picker breaking in Firefox on low zoom levels

modules/katamari/src/main/ts/ephox/katamari/api/Type.ts, modules/tinymce/src/plugins/textpattern/main/ts/api/Pattern.ts
In `Type`, all functions call the `typeOf` function, which is 13 lines long, and handles some strange special cases around Arrays, Strings, null and object. However, for some of the Type.isX functions, this isn't required. If a plugin only requires Type.isFunction, for instance, it's pulling in code it doesn't need to.
This change addresses this issue.
It also makes use of `Array.isArray`, which is available on all supported browsers.
This reduces the size of `dist/tinymce_5.3.0` from 656176 to 654748 bytes - a reduction of 1428 bytes.
=> TINY-4736: Optimize Type module for tree-shaking

modules/tinymce/src/plugins/help/main/ts/ui/Dialog.ts, modules/tinymce/src/plugins/help/main/ts/ui/PluginsTab.ts
This reduces the size of the "help" plugin, by avoiding dependencies on:
- Arr.indexOf
- Fun.curry
- Strings.supplant
This reduces the overall size of `dist/tinymce_5.3.0.zip` from 656176 bytes to 656000 - a reduction of 176 bytes.
=> TINY-4735: Reduce size of "help" plugin

modules/tinymce/src/plugins/autosave/demo/html/demo.html, modules/tinymce/src/plugins/autosave/main/ts/Plugin.ts, modules/tinymce/src/plugins/autosave/main/ts/api/Api.ts, modules/tinymce/src/plugins/autosave/main/ts/api/Settings.ts, modules/tinymce/src/plugins/autosave/main/ts/core/Storage.ts, modules/tinymce/src/plugins/autosave/main/ts/ui/Buttons.ts
In the TypeScript conversion, `Fun.curry` had its type and implementation improved. However, this increased its output size. For small plugins, it's more overhead than the benefit it brings. This PR removes the `Fun.curry` calls, allowing it to be tree-shaken out. 
As well as reducing size, removing the curry also makes the `Api` method types a bit more correct. The optional nature of the parameters on `removeDraft` and `isEmpty` were not surviving the currying. 
This change also removes the `Cell` value passed through. This `Cell` was created, passed through, mutated, then out-of-scope. This didn't have any net effect.
Paths in the demo page were corrected.
Size reductions when running `yarn build`:
- `dist/tinymce-5.3.0.zip`: 653363 - 653218 = 145 bytes
- …
=> TINY-4748: Reduce size of autosave plugin

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/dom/ControlSelection.ts, modules/tinymce/src/themes/silver/main/ts/modes/Inline.ts, modules/tinymce/src/themes/silver/main/ts/ui/header/InlineHeader.ts
This is just something I'd noticed a while back that had been bugging me. Basically the cause is that we don't listen to the load event, which means only the initial size is used but that can change after the image has loaded. So this makes `ControlSelection` also listen to the `ResizeContent` event, which is currently only fired in iframe mode so I've also hooked that up in a similar way for inline mode.
I've also taken the chance to move out the inline positioning, etc... logic to a separate module as it was getting a bit cluttered (see `InlineHeader.ts`).
Note: No tests, as loading a remote image and getting the load timing right is quite fickle and likely to lead to tests that either do nothing or flake.
=> TINY-4732: Fixed resize handlers displaying in the wrong location sometimes for remote images

modules/oxide/src/less/theme/content/contenteditable/contenteditable.less, modules/tinymce/changelog.txt
This one was very strange... but ultimately it seems to be a bit of a browser quirk due to the massive negative left value that was being used.
Other solutions I found for this were:
- adding the offscreen selection to the body instead
- using fixed positioning instead of absolute for the offscreen selection
- using the HTML 5 drag/drop APIs instead of mouse events (browser behaviour was pretty different so it would have required a mixed approach of both mouse and drag events)
however using a lower negative left value seemed like the simplest and safest solution.
@metricjs also found the following, which asserts that our negative left value was likely far too high anyways for most browsers.
> There is no official range of valid values. Opera supports values up to 2^15-1, IE up to 2^20-1 …
=> TINY-4195: Fixed an issue where dragging images could cause them to be duplicated

modules/alloy/src/main/ts/ephox/alloy/alien/Boxes.ts, modules/alloy/src/main/ts/ephox/alloy/alien/Descend.ts, modules/alloy/src/main/ts/ephox/alloy/events/EventRegistry.ts, modules/alloy/src/main/ts/ephox/alloy/positioning/layout/Anchor.ts, modules/alloy/src/main/ts/ephox/alloy/positioning/mode/SelectionAnchor.ts, modules/alloy/src/main/ts/ephox/alloy/positioning/view/PositionCss.ts, modules/alloy/src/main/ts/ephox/alloy/positioning/view/SpotInfo.ts, modules/alloy/src/main/ts/ephox/alloy/toolbar/Overflows.ts, modules/darwin/src/main/ts/ephox/darwin/selection/Response.ts, modules/phoenix/src/main/ts/ephox/phoenix/api/data/Spot.ts, modules/phoenix/src/main/ts/ephox/phoenix/api/data/Types.ts, modules/phoenix/src/main/ts/ephox/phoenix/gather/Walker.ts, modules/robin/src/main/ts/ephox/robin/clumps/Clumps.ts, modules/robin/src/main/ts/ephox/robin/parent/Breaker.ts, modules/robin/src/main/ts/ephox/robin/textdata/TextSearch.ts, modules/snooker/src/main/ts/ephox/snooker/api/CopySelected.ts, modules/snooker/src/main/ts/ephox/snooker/api/Structs.ts, modules/snooker/src/main/ts/ephox/snooker/api/TableOperations.ts, modules/snooker/src/main/ts/ephox/snooker/resize/BarPositions.ts, modules/sugar/src/main/ts/ephox/sugar/api/search/ElementAddress.ts, modules/sugar/src/main/ts/ephox/sugar/api/search/Traverse.ts, modules/sugar/src/main/ts/ephox/sugar/api/selection/SimRange.ts, modules/tinymce/src/core/main/ts/EditorSettings.ts, modules/tinymce/src/core/main/ts/selection/SimpleTableModel.ts, modules/tinymce/src/plugins/table/main/ts/queries/TableTargets.ts
`Struct.immutable` was an attempt to create objects with known fields in JavaScript and enforce some kind of run-time-typing. In TypeScript, we prefer to use interfaces and objects.  
This change removes all usages that end up in the TinyMCE output code, except for a weird one  in Porkbun. 
A lot of these could be unthunked, but that's a job for another day.
Size deltas:
```
File                                                Before   After Delta
tinymce/js/tinymce/plugins/table/plugin.min.js      117401  117574   173
tinymce/js/tinymce/themes/silver/theme.min.js       407721  407650   -71
tinymce/js/tinymce/plugins/lists/plugin.min.js       26991   26901   -90
tinymce/js/tinymce/plugins/fullscreen/plugin.min.js  15065   14973   -92
tinymce/js/tinymce/tinymce.min.js …
```
=> TINY-4737: Remove usages of Struct.immutable

modules/alloy/changelog.md, modules/alloy/src/main/ts/ephox/alloy/positioning/layout/Layout.ts, modules/alloy/src/main/ts/ephox/alloy/positioning/layout/LayoutBounds.ts, modules/alloy/src/main/ts/ephox/alloy/positioning/layout/LayoutInside.ts, modules/alloy/src/main/ts/ephox/alloy/positioning/layout/LayoutTypes.ts, modules/alloy/src/main/ts/ephox/alloy/positioning/layout/LinkedLayout.ts, modules/alloy/src/main/ts/ephox/alloy/positioning/view/Bounder.ts, modules/alloy/src/main/ts/ephox/alloy/positioning/view/SpotInfo.ts, modules/alloy/src/test/ts/atomic/position/view/BounderCalcRepositionTest.ts, modules/alloy/src/test/ts/atomic/position/view/BounderCursorTest.ts, modules/alloy/src/test/ts/atomic/position/view/BounderToolbuttonTest.ts, modules/katamari/src/main/ts/ephox/katamari/api/Arr.ts, modules/tinymce/changelog.txt, modules/tinymce/src/themes/silver/main/ts/backstage/Anchors.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/NoticationManagerImplTest.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/contexttoolbar/ContextToolbarIframePositionTest.ts, modules/tinymce/src/themes/silver/test/ts/browser/window/SilverInlineDialogPositionTest.ts
This fixes the context toolbar overlapping with the header when using toolbar bottom, as our `Bounder` logic wasn't taking into account the width/height.
Fixing the bottom/right bounds constraints however highlighted another issue, in that we also allowed the component to overlap with the anchor if the X/Y was limited by the bounds. As such I've also added logic to adjust the bounds based on the anchor layout, so that the new bounds will be the anchor point out to the specified bounds.
Lastly, this also fixes an issue I found whereby the inline dialog anchor was incorrect for iframe mode (the logic was only originally setup for fixed toolbar, which is inline only). That also then highlighted that there was a bug in the `LayoutInside` logic for anything where the point was in the corners, …
=> TINY-4586: Fixed bottom/right bounds not being constrained

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/html/DomParser.ts, modules/tinymce/src/core/main/ts/api/html/SaxParser.ts, modules/tinymce/src/core/main/ts/dom/DomSerializer.ts, modules/tinymce/src/core/main/ts/file/Conversions.ts, modules/tinymce/src/core/main/ts/file/ImageScanner.ts, modules/tinymce/src/core/main/ts/html/Base64Uris.ts, modules/tinymce/src/core/main/ts/html/LegacyFilter.ts, modules/tinymce/src/core/main/ts/html/ParserFilters.ts, modules/tinymce/src/core/main/ts/html/ParserUtils.ts, modules/tinymce/src/core/main/ts/init/InitContentBody.ts, modules/tinymce/src/core/test/ts/atomic/html/Base64UrisTest.ts, modules/tinymce/src/core/test/ts/browser/EditorPaddEmptyWithBrTest.ts, modules/tinymce/src/core/test/ts/browser/EditorTest.ts, modules/tinymce/src/core/test/ts/browser/FormatterRemoveForcedRootBlockFalseTest.ts, modules/tinymce/src/core/test/ts/browser/FormatterRemoveTest.ts, modules/tinymce/src/core/test/ts/browser/content/EditorContentForcedRootBlockTest.ts, modules/tinymce/src/core/test/ts/browser/content/EditorContentTest.ts, modules/tinymce/src/core/test/ts/browser/delete/OutdentForcedRootBlockFalseTest.ts, modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts, modules/tinymce/src/core/test/ts/browser/html/SaxParserTest.ts, modules/tinymce/src/plugins/lists/test/ts/browser/RemoveForcedRootBlockAttrsTest.ts, modules/tinymce/src/plugins/lists/test/ts/browser/RemoveForcedRootBlockFalseTest.ts, modules/tinymce/src/plugins/lists/test/ts/browser/RemoveTest.ts, modules/tinymce/src/plugins/paste/main/ts/core/Clipboard.ts, modules/tinymce/src/plugins/paste/test/ts/browser/ImagePasteTest.ts, modules/tinymce/src/plugins/textpattern/test/ts/browser/TextPatternPluginForcedRootBlockFalseTest.ts, modules/tinymce/src/plugins/textpattern/test/ts/browser/TextPatternPluginTest.ts
This fixes a github community bug but it's also something we need for RTC basically we want to avoid having base64 encoded attributes in the editor and let the scanner convert them to blobs. Instead this will convert everything upfront to blobs when content is inserted into the editor.
I also changed the DomParser and DomSerializer setups so they don't get the editor settings but instead a copy of the settings specific to those things this is something I have wanted to change for a long time but I had to separate out a bunch of mutating tests since mutating editor.settings will now no longer mutate DomParser or DomSerializer settings they are immutable copies.
Fixes #5425
=> TINY-4727: Inserting large base64 encoded images in Safari creates an empty `<img>` tag

changelog.txt, src/skins/lightgray/main/less/desktop/Content.Objects.less
This just backports @jhaines fix for the table resize handler issue on Edge: https://github.com/tinymce/tinymce/pull/5422 and https://github.com/tinymce/tinymce/pull/5432
=> TINY-4160: Backport table resize handles not functioning correctly in Edge

changelog.txt, src/plugins/table/main/ts/selection/CellSelection.ts
This just backports the PR from 5.x: https://github.com/tinymce/tinymce/pull/5437
Note: `Env.browser` and `DomEvent.fromRaw` don't exist for 4.x, so I had to use the older variants.
=> TINY-3862: Backport table selection not functioning correctly in Edge 44 or higher

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/init/InitContentBody.ts, modules/tinymce/src/core/test/ts/browser/init/InitContentBodyFiltersTest.ts, modules/tinymce/src/core/test/ts/browser/init/InitContentBodyParserTest.ts
It is possible that the result from `node.attr` may be undefined which will cause an exception when calling `value.indexOf`. The fix ensures that the `value` variable is a string of some kind.
=> TINY-4742: Fixed possible uncaught exception when creating a parser

modules/tinymce/src/core/main/ts/init/Render.ts
Note: The custom icon packs are specifically configured not to load a minified version, as our tooling and docs don't include a minified version in the custom icon pack builder.
=> TINY-4729: Load the minified default icon pack if needed

modules/tinymce/changelog.txt, modules/tinymce/src/core/test/ts/browser/ReadOnlyModeTest.ts, modules/tinymce/src/themes/silver/main/ts/ContextToolbar.ts, modules/tinymce/src/themes/silver/main/ts/ui/context/ContextToolbarLookup.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/contexttoolbar/ContextToolbarTest.ts
This fixes a regression (sort of) introduced in 5.2.0 whereby the context toolbars will show without the editor having focus. The cause of this, is that we now set the selection to an initial position on init, which meant a predicate matched.
Fixes #5456
=> TINY-4754: Fixed context toolbars activating without the editor having focus

modules/agar/src/main/ts/ephox/agar/api/Cursors.ts, modules/agar/src/main/ts/ephox/agar/api/RealKeys.ts, modules/alloy/src/main/ts/ephox/alloy/api/behaviour/Dragging.ts, modules/alloy/src/main/ts/ephox/alloy/dragging/snap/Snappables.ts, modules/alloy/src/main/ts/ephox/alloy/keying/MatrixType.ts, modules/alloy/src/main/ts/ephox/alloy/navigation/MatrixNavigation.ts, modules/alloy/src/main/ts/ephox/alloy/positioning/layout/Origins.ts, modules/alloy/src/main/ts/ephox/alloy/positioning/layout/SimpleLayout.ts, modules/alloy/src/main/ts/ephox/alloy/positioning/view/Bounder.ts, modules/alloy/src/main/ts/ephox/alloy/positioning/view/Callouts.ts, modules/alloy/src/main/ts/ephox/alloy/positioning/view/Reposition.ts, modules/alloy/src/test/ts/atomic/navigation/MatrixNavigationTest.ts, modules/alloy/src/test/ts/atomic/position/view/BounderCursorTest.ts, modules/alloy/src/test/ts/atomic/position/view/BounderMenuTest.ts, modules/alloy/src/test/ts/atomic/position/view/BounderToolbuttonTest.ts, modules/darwin/src/main/ts/ephox/darwin/api/InputHandlers.ts, modules/darwin/src/main/ts/ephox/darwin/keyboard/Carets.ts, modules/darwin/src/main/ts/ephox/darwin/keyboard/KeySelection.ts, modules/darwin/src/main/ts/ephox/darwin/keyboard/Rectangles.ts, modules/darwin/src/main/ts/ephox/darwin/keyboard/Retries.ts, modules/darwin/src/main/ts/ephox/darwin/keyboard/TableKeys.ts, modules/darwin/src/main/ts/ephox/darwin/mouse/MouseSelection.ts, modules/darwin/src/main/ts/ephox/darwin/selection/CellSelection.ts, modules/darwin/src/main/ts/ephox/darwin/selection/Identified.ts, modules/katamari/src/main/ts/ephox/katamari/api/Option.ts, modules/mcagar/src/main/ts/ephox/mcagar/api/TinyDom.ts, modules/tinymce/src/plugins/table/main/ts/selection/CellSelection.ts
`immutableBag` is a remnant of an old coding style. It was an attempt to make a "constructor" which validated arguments and provided getters. 
This change removes all references except for a tricky one in `IosMode` - we need more types in there to make it safe to change.
=> TINY-4759: Remove usages of immutableBag

modules/tinymce/src/themes/silver/main/ts/ui/context/ContextToolbarLookup.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/contexttoolbar/ContextToolbarLookupTest.ts
This fixes the issue @ltrouton found and adds some tests, which in doing so found another bug.
=> TINY-4751: Fixed the context toolbar lookup starting outside the root node

modules/tinymce/changelog.txt, modules/tinymce/src/themes/silver/main/ts/ui/toolbar/CommonToolbar.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/InlineToolbarDrawerFloatingPositionTest.ts
This fixes an edge case @ltrouton found whereby the toolbar would get positioned incorrectly when using inline mode with toolbar bottom. The cause was our bounds weren't accurate for when the toolbar was positioned at the bottom.
=> TINY-4765: Fixed an edge case where the inline more drawer would get offset from the toolbar

changelog.txt, src/core/main/ts/api/EditorManager.ts, src/core/test/ts/browser/EditorManagerSetupTest.ts
This backports a fix we did a while back (5.0.16). I wasn't 100% sure whether we should backport this, and no one seemed to know when I asked on Slack, however given this causes the editor to completely fail to load I thought it had a high enough priority even if it was an edge case issue.
Fixes #5475
=> TINY-4087: Backported fix for TinyMCE failing to initialize if a script tag was used inside an SVG

modules/tinymce/Gruntfile.js
No changelog as this doesn't impact TinyMCE itself and instead only a few select bundles. This was just a very quick win and I wasn't too sure if we should throw this in 5.2.1 or 5.3.0, however it has very little risk so I thought it made sense to include it in 5.2.1. If anyone thinks otherwise let me know and I'll change it to 5.3.0.
Fixes #5489
=> TINY-4771: Fixed a couple production bundles not stripping off the sourcemap includes

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/searchreplace/test/ts/browser/SearchReplaceKeyboardNavigationTest.ts, modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialog.ts, modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialogEvents.ts, modules/tinymce/src/themes/silver/main/ts/ui/window/SilverInlineDialog.ts
The core change here, is that we were only checking if something inside the dialog component had focus and if not then it'd return the focus to the dialog. However with this change, it'll only return the focus to the dialog if the focused element is outside the sink. I also improved the disabled check, to handle things that aren't allowed the disabled attribute, meaning they'd be using the `aria-disabled` attribute instead.
Note: I've pulled this in as it's a regression introduced in 5.0.14 and is closely related to https://github.com/tinymce/tinymce/pull/5497 since the dialog loses focus so you can't use a keyboard to close the alert dialog.
=> TINY-4014: Fixed dialogs stealing focus when opening an alert/confirm via an onAction callback

modules/alloy/changelog.md, modules/alloy/src/main/ts/ephox/alloy/api/ui/FloatingToolbarButton.ts, modules/alloy/src/main/ts/ephox/alloy/api/ui/InlineView.ts, modules/alloy/src/main/ts/ephox/alloy/dropdown/DropdownUtils.ts, modules/alloy/src/main/ts/ephox/alloy/sandbox/Reposition.ts, modules/alloy/src/main/ts/ephox/alloy/ui/types/InlineViewTypes.ts, modules/tinymce/changelog.txt, modules/tinymce/src/themes/silver/main/ts/ui/dialog/WindowManager.ts, modules/tinymce/src/themes/silver/test/ts/browser/window/SilverInlineDialogTest.ts, modules/tinymce/src/themes/silver/test/ts/module/DialogUtils.ts
Note: I removed the `isExtraPart` from the repositioning spec, as it wasn't ever being used anyways, so it was just bloating the code.
Fixes #5405
=> TINY-4012: Fixed inline dialogs incorrectly closing when clicking on an opened alert or confirm dialog

modules/tinymce/src/plugins/charmap/demo/ts/demo/Demo.ts, modules/tinymce/src/plugins/charmap/main/ts/core/Scan.ts, modules/tinymce/src/plugins/charmap/test/ts/atomic/ScanTest.ts
Supplementary characters (Unicode characters greater than U+FFFF) are truncated
when adding them to the charmap.
Thus a character like 𝅘𝅥𝅮 (0x1d160 "Musical Symbol Eighth Note"), is displayed and entered into text as 텠 (0xd160 a Hangul syllables).
The underlying cause is in Scan.ts which uses String.fromCharCode(), where per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode "Numbers greater than 0xFFFF are truncated".
The fix is to use String.fromCodePoint() which supports supplementary characters - BUT:
that's ES2015. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCodePoint has a polyfile, which I've adapted as a local function.
=> Character Map Plugin: Support supplementary characters

modules/tinymce/src/core/test/ts/browser/caret/LineReaderTest.ts
It looks like Safari fixed the bug that required the branching in these tests in 13.1, so I've updated the test  to use the same logic as all other browsers for 13.1 or above.
=> TINY-4807: Fixed failing LineReaderTest on Safari 13.1

.eslintrc.json, modules/alloy/src/main/ts/ephox/alloy/api/component/GuiFactory.ts, modules/tinymce/src/core/main/ts/api/EditorManager.ts, modules/tinymce/src/core/main/ts/api/EditorObservable.ts, modules/tinymce/src/core/main/ts/api/dom/ControlSelection.ts, modules/tinymce/src/core/main/ts/api/dom/EventUtils.ts, modules/tinymce/src/core/main/ts/api/dom/Sizzle.ts, modules/tinymce/src/core/main/ts/api/html/Node.ts, modules/tinymce/src/core/main/ts/api/html/Schema.ts, modules/tinymce/src/core/main/ts/api/html/Styles.ts, modules/tinymce/src/core/main/ts/api/util/Class.ts, modules/tinymce/src/core/main/ts/api/util/EventDispatcher.ts, modules/tinymce/src/core/test/ts/browser/AddOnManagerTest.ts, modules/tinymce/src/plugins/media/main/ts/core/UpdateHtml.ts, modules/tinymce/src/plugins/visualchars/main/ts/core/Data.ts
Also enabled lint @typescript-eslint/type-annotation-spacing which I missed in the previous spacing lints PR. It only changes one file.
=> TINY-4780: Enabled lint guard-for-in and manually fixed errors

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/dom/DOMUtils.ts, modules/tinymce/src/core/main/ts/api/html/DomParser.ts, modules/tinymce/src/core/main/ts/api/html/Node.ts, modules/tinymce/src/plugins/anchor/demo/ts/demo/Demo.ts, modules/tinymce/src/plugins/anchor/main/ts/Plugin.ts, modules/tinymce/src/plugins/anchor/main/ts/api/Commands.ts, modules/tinymce/src/plugins/anchor/main/ts/core/Anchor.ts, modules/tinymce/src/plugins/anchor/main/ts/core/FilterContent.ts, modules/tinymce/src/plugins/anchor/main/ts/ui/Buttons.ts, modules/tinymce/src/plugins/anchor/main/ts/ui/Dialog.ts, modules/tinymce/src/plugins/anchor/test/ts/browser/AnchorAlertTest.ts, modules/tinymce/src/plugins/anchor/test/ts/browser/AnchorContentEditableTest.ts, modules/tinymce/src/plugins/anchor/test/ts/browser/AnchorEditTest.ts, modules/tinymce/src/plugins/anchor/test/ts/browser/AnchorInlineTest.ts, modules/tinymce/src/plugins/anchor/test/ts/browser/AnchorSanityTest.ts
The main changes to allow anchors on new lines are in DomUtils.ts and Node.ts. Also cleaned up the Anchor plugin a bit.
=> TINY-2788: Allow anchors to be inserted on empty lines

yarn.lock
This upgrades the dependencies to fix the minimist security alert. Most had already been resolved in my previous deps upgrade PR, however `handlebars` still relied on `optimist`, which relied on a vulnerable `minimist` version. That's been fixed now, so I've upgraded that and the other deps.
=> TINY-4775: Upgraded dependencies

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/image/test/ts/browser/core/ImageAlignTest.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/complex/AlignSelect.ts
The align buttons on the toolbar call a command that removes existing alignments before applying a new alignment. 
This change forces the align menu items to use the commands as well.
=> TINY-4057: Fixed format menu align buttons inconsistently applying to images

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/content/Placeholder.ts, modules/tinymce/src/core/test/ts/webdriver/content/PlaceholderTest.ts
This issue has highlighted a larger issue that pasted content when not using the paste/powerpaste plugin doesn't run through the filtering/content parsing logic so I'll be logging an issue to investigate/address that. However that's a much larger issue so this is an interim solution to make sure the placeholder is cleared when pasting content.
Fixes #5561
=> TINY-4828: Fixed the placeholder not hiding when pasting content into the editor

CONTRIBUTING.md
There is a small typo in CONTRIBUTING.md.
Should read `unwieldy` rather than `unweildy`.
=> docs: Fix simple typo, unweildy -> unwieldy

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/fmt/ApplyFormat.ts, modules/tinymce/src/core/main/ts/fmt/MergeFormats.ts, modules/tinymce/src/core/test/ts/browser/fmt/TextDecorationColorTest.ts
This change makes it so that a text decoration should always inherit the text colour irrespective of order of operations or selection ranges.
There are still a couple of issues that will need to be resolved in the future.
- Occasionally, there are additional redundant text decoration spans. Although, this was the case before my change and trying to fix this could easily cause breakages. 
- There is still an issue when applying multiple text decorations i.e. forecolor -> underline -> strikethrough. The strikethrough doesn't get the correct text colour. Fixing this will likely require a bit of work so will create a separate ticket for that.
=> TINY-4757: Improved merging of text decoration styles with colour styles

modules/tinymce/src/core/main/ts/Rtc.ts, modules/tinymce/src/core/main/ts/api/Formatter.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/color/TextColorFormattingTest.ts
The `similar` argument was accidentally dropped with the RTC PR, so this just adds it back as it broke the ability to remove color based formatting.
=> TINY-4838: Fixed a regression caused by accidentally dropping an argument when removing formatting

modules/alloy/src/main/ts/ephox/alloy/api/ui/SplitFloatingToolbar.ts, modules/mcagar/src/main/ts/ephox/mcagar/api/Editor.ts, modules/mcagar/src/main/ts/ephox/mcagar/api/RemoteTinyLoader.ts, modules/mcagar/src/main/ts/ephox/mcagar/api/TinyLoader.ts, modules/mcagar/src/main/ts/ephox/mcagar/loader/Loader.ts, modules/tinymce/changelog.txt, modules/tinymce/src/themes/silver/main/ts/ui/toolbar/CommonToolbar.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/ToolbarDrawerFloatingPositionTest.ts, modules/tinymce/src/themes/silver/test/ts/module/ToolbarUtils.ts
This fixes an issue where the bounds was being calculated incorrectly and also fixes an issue where the toolbar would render in a vertical line since we didn't have a fallback for the layouts when everything in the toolbar was collapsed.
I've specifically still used the document bounds instead of the window (though I'm also using scrollHeight which will account for floating elements), as we don't want to restrict the height if the editor is just scrolled near the bottom of the page. In that case it should overflow outside the window, so when the user scrolls the window all the toolbar buttons are visible.
Note: To be able to test this, I needed a way to render the editor in a specific location with a wrapper. To do that I've added a new `mcagar` function to be able to pass in the element …
=> TINY-4837: Fixed floating toolbar drawer issues

.travis.yml
There's a GitHub issue linked against chromedriver already, but since this is causing all PR's to show as having errors I wanted to get this working and we can move back to latest when it's supported.
=> Pin Travis CI build to use NodeJS 13, as chromedriver currently doesnt work on NodeJS 14

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/Rtc.ts, modules/tinymce/src/core/main/ts/api/dom/Selection.ts, modules/tinymce/src/core/main/ts/bookmark/GetBookmark.ts, modules/tinymce/src/core/main/ts/selection/GetSelectionContent.ts, modules/tinymce/src/core/main/ts/selection/GetSelectionContentImpl.ts, modules/tinymce/src/core/main/ts/selection/SetSelectionContent.ts, modules/tinymce/src/core/test/ts/browser/content/EditorGetContentTreeTest.ts, modules/tinymce/src/core/test/ts/browser/dom/SelectionTest.ts
This also fixes a number of `any` types within the `Selection` interface.
Fixes #5095
=> TINY-4002: Fixed the `selection.setContent()` API not running parser filters

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/util/LocalStorage.ts, modules/tinymce/src/themes/silver/main/ts/backstage/UrlInputHistory.ts
Note: No tests for this, as we'd have to pollute the globals to override the default window properties to test (ie monkeypatch) which isn't a good idea and will lead to flaky tests. I should add this is largely just lifted from TBIO.
Fixes #5468
=> TINY-5935: Fixed an issue where the editor would fail to load if local storage was disabled

modules/tinymce/src/core/main/ts/fmt/RemoveFormat.ts, modules/tinymce/src/plugins/legacyoutput/demo/ts/demo/Demo.ts, modules/tinymce/src/plugins/legacyoutput/main/ts/core/Formats.ts, modules/tinymce/src/plugins/legacyoutput/test/ts/browser/LegacyOutputPluginTest.ts
In a previous PR for this ticket, I missed updating the formats registered in the `legacyoutput` plugin. This PR updates the relevant formats in `legacyoutput`.
=> TINY-4741: Update relevant legacyoutput formats to use preserve_attributes parameter

.github/CODEOWNERS
This just updates the codeowners to match the team changes.
=> Updated the CODEOWNERS

modules/tinymce/tools/tasks/bundle.js
This will pull in any additional JS files needed by a plugin, inside a plugins `js` directory (currently emoticons is the only one that uses this).
Fixes #4847
=> TINY-4027: Include additional plugin js files when bundling

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/annotate/Wrapping.ts, modules/tinymce/src/core/main/ts/fmt/ApplyFormat.ts, modules/tinymce/src/core/main/ts/fmt/RemoveFormat.ts, modules/tinymce/src/core/main/ts/selection/RangeWalk.ts, modules/tinymce/src/core/main/ts/selection/SelectionUtils.ts, modules/tinymce/src/core/main/ts/selection/TableCellSelection.ts, modules/tinymce/src/core/test/ts/browser/FormatterApplyTest.ts, modules/tinymce/src/core/test/ts/browser/FormatterRemoveTest.ts, modules/tinymce/src/core/test/ts/browser/annotate/AnnotateTest.ts, modules/tinymce/src/core/test/ts/module/test/AnnotationAsserts.ts
Having the fake selection walking logic in `RangeWalk` wasn't really the right place, as it needed to be when getting the ranges from the selection as that's what the fake selection is actually emulating (eg multi range selection). So this fixes a few things: it fixes the original issue and also removing formats from a fake table selection, as that didn't work (found this out when writing tests).
Fixes #5408
=> TINY-4709: Fixed formats incorrectly applied or removed when table cells were selected

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/dom/ControlSelection.ts, modules/tinymce/src/core/test/ts/browser/dom/ControlSelectionTest.ts
This was causing the `ObjectResized` handler to fire in the table plugin and because a resize hadn't actually occurred the width/height reported was `0` which would collapse the table.
This also fixes another issue I've wanted to fix for a long time, whereby the "ghost" resize object width is incorrect initially for relative width elements. The fix was just to ensure we set the initial size based on the computed target element width/heights, which is what happened when you started resizing.
=> TINY-4161: Fixed `ObjectResized` event incorrectly firing when an object wasn't resized

modules/boulder/src/main/ts/ephox/boulder/core/ValueProcessor.ts, modules/tinymce/src/core/main/ts/caret/FakeCaret.ts
While doing some performance profiling on the spellchecker, I found these couple of small performance improvements.
The boulder change is fairly minimal at ~1ms or less depending on the browser. However, the `FakeCaret` change is much more so, as it saves ~4-5ms and that is on `setRng` calls (not every call, but most of them), so it ends up saving quite a bit of time. As an example, with spellchecker it saves ~400-500ms per scan (eg NodeChange) of the document that I'm currently profiling.
Pictures for reference:
**Before:**
**After:**
=> TINY-5954: Made a few minor performance improvements

modules/tinymce/src/core/main/ts/keyboard/BoundarySelection.ts
Just one more place where we were using `Sizzle` in something that triggers quite often (on NodeChange). I did try to replace the whole `DOMUtils.select` API with `SelectorFilter` instead, however it allows non-standard selectors which broke things (eg: `a:last`).
=> TINY-5954: One more minor performance improvement

modules/tinymce/src/themes/silver/main/ts/ui/header/InlineHeader.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/InlineToolbarPositionTest.ts
This fixes the regression introduced in 5.3 whereby the fixed toolbar container was getting a max-width to match the content area.
=> TINY-5955: Fixed fixed toolbar container getting a max-width assigned

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/searchreplace/main/ts/core/TextCollect.ts, modules/tinymce/src/plugins/searchreplace/test/ts/browser/SearchReplacePluginTest.ts
This just fixes an issue I knew about with the current search and replace plugin and since I've rewritten a fair bit to do the find in selection feature, I thought I should probably fix it as well.
Fixes #4650
=> TINY-5967: Fixed search and replace skipping nested contenteditable nodes

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/fmt/CaretFormat.ts, modules/tinymce/src/core/test/ts/browser/fmt/CaretFormatTest.ts
The logic that was trying to restore the selection offsets here was happening after the range had already been mutated and then unwrapped the node, which caused the range to change again. So this just stores the offsets before mutating the dom and restores it how it was previously attempting to after doing the dom mutation.
Fixes #4875
=> TINY-3438: Fixed the editor selection incorrectly changing when removing caret format containers

modules/acid/src/main/ts/ephox/acid/gui/ColourEvents.ts, modules/acid/src/main/ts/ephox/acid/gui/ColourPicker.ts
This was introduced in f40614b, as alloy will map all data passed into fired events such that they become functions so this shouldn't have been unthunked: https://github.com/tinymce/tinymce/blob/2e042bb4f71a349f6eb58a4dab28248221cfdac8/modules/alloy/src/main/ts/ephox/alloy/api/events/AlloyTriggers.ts#L29
=> TINY-5970: Fixed colour picker regression

modules/tinymce/src/themes/silver/main/ts/modes/Inline.ts, modules/tinymce/src/themes/silver/main/ts/ui/header/InlineHeader.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/InlineToolbarPositionTest.ts
I realised when writing up the QA notes and reading the original issue again that my previous PR missed the edge case of where there's no room at the bottom or top. As such this will function in the same way as the previous PR in most cases, except when the page is scrolled to the bottom and there's no room to render the toolbar below. In that case, it'll switch back to rendering at the top until you start to scroll up again.
=> TINY-3161: Fix edge case where there's no room to render the toolbar bove or below the target element

modules/sugar/src/main/ts/ephox/sugar/api/node/Body.ts, modules/tinymce/changelog.txt
This PR provides a fix for the problem outlined in #5274.
In short, menus, toolbars and dialogs currently stop working if the `body` element is replaced, which happens during a page visit in [Turbolinks](https://github.com/turbolinks/turbolinks/) (potentially in other circumstances too). See the demo at https://jsfiddle.net/hbjpmqgv/1/ for a simulation.
When I originally created the issue, I was unsure of the potential performance implications of this fix. However I have spent some time looking into this further and I don't believe there should be any negative impacts for the following reasons:
1) The call to `Body.body()` is not done very often during the life cycle of a TinyMCE instance, and certainly not in any loops that I could find. From some basic `console.log` debugging, it …
=> Remove caching from Body.body()

modules/tinymce/src/themes/silver/main/ts/modes/Inline.ts, modules/tinymce/src/themes/silver/main/ts/ui/header/InlineHeader.ts
I used the wrong height here again :facepalm: as I needed to use the document scroll height, not the offset height. As such sometimes it thought there wasn't any room to render below the content area. Also missed a case whereby if you deleted content then it wouldn't adjust back to being below the editor content.
Hopefully this is the last PR for this issue sorry all!
=> TINY-3161: Fixed more missed edge cases

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/table/main/ts/api/Commands.ts, modules/tinymce/src/plugins/table/test/ts/browser/InsertRowTableResizeTest.ts, modules/tinymce/src/plugins/table/test/ts/module/test/TableTestUtils.ts
These events were being fired when adding or removing table rows and columns, or generally any table width/change. This however was incorrect and inconsistent, as these events only normally fire when a user resizes using a resize handle everywhere else. As an example, when you change the dimension of an image these wouldn't fire.
=> TINY-4829: Fixed `ObjectResized` and `ObjectResizeStart` events incorrectly fired

modules/bridge/src/main/ts/ephox/bridge/components/menu/ToggleMenuItem.ts, modules/oxide/src/less/theme/components/collection/collection.less, modules/tinymce/changelog.txt, modules/tinymce/src/plugins/fullscreen/main/ts/ui/Buttons.ts, modules/tinymce/src/plugins/importcss/test/ts/browser/ImportCssPluginTest.ts, modules/tinymce/src/plugins/paste/main/ts/ui/Buttons.ts, modules/tinymce/src/plugins/spellchecker/main/ts/ui/Buttons.ts, modules/tinymce/src/plugins/visualblocks/main/ts/ui/Buttons.ts, modules/tinymce/src/plugins/visualchars/main/ts/ui/Buttons.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/complex/BespokeSelect.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/complex/SelectDatasets.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/complex/StyleFormat.ts, modules/tinymce/src/themes/silver/main/ts/ui/menus/item/build/ChoiceItem.ts, modules/tinymce/src/themes/silver/main/ts/ui/menus/item/build/ToggleMenuItem.ts, modules/tinymce/src/themes/silver/main/ts/ui/menus/item/structure/ItemSlices.ts, modules/tinymce/src/themes/silver/main/ts/ui/menus/item/structure/ItemStructure.ts, modules/tinymce/src/themes/silver/main/ts/ui/menus/menu/MenuChoice.ts, modules/tinymce/src/themes/silver/main/ts/ui/menus/menu/MenuUtils.ts, modules/tinymce/src/themes/silver/main/ts/ui/menus/menu/SingleMenu.ts, modules/tinymce/src/themes/silver/test/ts/browser/skin/OxideFontFormatMenuTest.ts, modules/tinymce/src/themes/silver/test/ts/browser/skin/OxideListCollectionMenuTest.ts, modules/tinymce/src/themes/silver/test/ts/phantom/sketchers/SilverMenubarTest.ts
This PR allows menu items, specifically toggle and choice items to display a dedicated icon on the left side of the item with a checkmark on the far right side of the item. If a shortcut is present and the checkmark is toggled off, the shortcut will shift over to the edge of the menu item.
=> TINY-3345: Implement new checkmark menu design

modules/oxide/src/less/skins/content/dark/content.less, modules/oxide/src/less/skins/content/default/content.less, modules/oxide/src/less/skins/content/document/content.less, modules/oxide/src/less/skins/content/writer/content.less, modules/tinymce/changelog.txt, modules/tinymce/src/plugins/autoresize/main/ts/core/Resize.ts
This is needed, as anything that uses relative heights won't render as expected within the editor otherwise (or on the users site).
Note: The calcs on the body are required due to the margins currently defined.
=> TINY-5978: Added html and body height styles to the default oxide content css

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/file/BlobCache.ts, modules/tinymce/src/core/main/ts/file/ImageScanner.ts, modules/tinymce/src/core/main/ts/html/ParserFilters.ts, modules/tinymce/src/core/test/ts/browser/file/BlobCacheTest.ts, modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts, modules/tinymce/src/plugins/paste/main/ts/core/Clipboard.ts
This fixes the regression we introduced in an earlier 5.3 PR whereby duplicate images would be added to the blob cache twice with different ids.
It also fixes a customer reported issue where images with the same data, but different mime types were using the same cached blob info. This meant that images often were being uploaded to the server with the wrong file extension and therefore may not have rendered when downloaded (eg say someone accidentally uploaded an image with a `.gif` extension, but then corrected the extension and uploaded it again as a `.png`).
=> TINY-5987/TINY-5988: Fix image upload regression and different image types being treated as the same

modules/katamari/src/main/ts/ephox/katamari/api/Unicode.ts, modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/text/Zwsp.ts, modules/tinymce/src/plugins/wordcount/main/ts/core/GetText.ts, modules/tinymce/src/plugins/wordcount/test/ts/browser/core/GetTextTest.ts
This strips zero-width spaces when fetching the text-based content from the editor, as they aren't visible and will normally be a fake caret, so they shouldn't be included in the character count.
Fixes #5659
=> TINY-5991: Fixed zero-width spaces incorrectly included in the `wordcount` plugin character count

modules/katamari/src/main/ts/ephox/katamari/api/Arr.ts, modules/tinymce/changelog.txt, modules/tinymce/src/core/demo/ts/demo/FullDemo.ts, modules/tinymce/src/plugins/lists/main/ts/Plugin.ts, modules/tinymce/src/plugins/lists/main/ts/api/Commands.ts, modules/tinymce/src/plugins/lists/main/ts/core/NodeType.ts, modules/tinymce/src/plugins/lists/main/ts/core/Selection.ts, modules/tinymce/src/plugins/lists/main/ts/core/Util.ts, modules/tinymce/src/plugins/lists/main/ts/listModel/Entry.ts, modules/tinymce/src/plugins/lists/main/ts/listModel/Indentation.ts, modules/tinymce/src/plugins/lists/main/ts/listModel/ListsIndendation.ts, modules/tinymce/src/plugins/lists/main/ts/listModel/NormalizeEntries.ts, modules/tinymce/src/plugins/lists/main/ts/listModel/Util.ts, modules/tinymce/src/plugins/lists/main/ts/ui/Buttons.ts, modules/tinymce/src/plugins/lists/main/ts/ui/Dialog.ts, modules/tinymce/src/plugins/lists/main/ts/ui/MenuItems.ts, modules/tinymce/src/plugins/lists/test/ts/browser/IndentTest.ts, modules/tinymce/src/plugins/lists/test/ts/browser/ListPropertiesTest.ts, modules/tinymce/src/plugins/lists/test/ts/browser/OutdentTest.ts
This adds the new feature to be able to configure the start number for ordered lists.
Fixes #5387
Note: This hasn't been added to the default context menu list intentionally, as we wanted to make this opt-in at this stage. That's why I've added it to the full demo instead.
=> TINY-3915: Added the ability to set the list start position for ordered lists

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/EditorSettings.ts, modules/tinymce/src/core/test/ts/browser/EditorSettingsTest.ts
This was introduced in cac78fe9810e5271d854ec296b47e8c29dfcf79c as the incorrect settings object was being passed when looking up the mobile defaults for the `toolbar_mode`/`toolbar_drawer`. So this just makes sure it's the mobile settings being passed in, instead of the top level settings.
=> TINY-5998: Fixed a regression introduced in 5.2.0 with mobile defaults

modules/tinymce/src/plugins/searchreplace/main/ts/core/TextCollect.ts, modules/tinymce/src/plugins/searchreplace/test/ts/browser/SearchReplacePluginTest.ts
This fixes the 2 issues identified during QA with the searching within content editable fix. The cause of TINY-5999 was it was walking back inside the contenteditable false elements and using that as an offset.
=> TINY-5995/TINY-5999: Fixed issues with collecting text nodes from nested contenteditable elements

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/caret/CaretFinder.ts, modules/tinymce/src/core/main/ts/content/InsertContentImpl.ts, modules/tinymce/src/core/main/ts/delete/TableDelete.ts, modules/tinymce/src/core/main/ts/delete/TableDeleteAction.ts, modules/tinymce/src/core/test/ts/browser/content/InsertContentTest.ts, modules/tinymce/src/core/test/ts/browser/delete/TableDeleteActionTest.ts, modules/tinymce/src/core/test/ts/browser/delete/TableDeleteTest.ts
This fixes two issues with single cell tables:
- Pressing delete/backspace with all cell content selected would delete the table
- Inserting content with all cell content selected would replace the table
This works by adding an override to the native browser delete behaviour, so that if all the contents of a cell is selected, then it'll manually delete the contents of the table while preserving the last block element. This was done so that it's consistent with regular deletion behaviour when selecting all content within a multicell table.
=> TINY-1044: Fixed issues with single cell tables getting deleted when all content is selected

modules/katamari/src/main/ts/ephox/katamari/api/Obj.ts, modules/tinymce/changelog.txt, modules/tinymce/src/core/demo/ts/demo/FullDemo.ts, modules/tinymce/src/core/main/ts/fmt/CaretFormat.ts, modules/tinymce/src/core/main/ts/fmt/FormatRegistry.ts, modules/tinymce/src/core/main/ts/fmt/FormatUtils.ts, modules/tinymce/src/core/main/ts/fmt/MatchFormat.ts, modules/tinymce/src/core/test/ts/browser/fmt/CaretFormatTest.ts
This fixes an issue where if multiple formats were in a single span, they would both be removed when removing a single format at the end of lines or on empty lines.
=> TINY-1170: Fix format removal on empty lines and end of lines

modules/tinymce/src/themes/silver/main/ts/ui/context/ContextToolbarLookup.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/contexttoolbar/ContextToolbarLookupPositionPriorityTest.ts
Realised we weren't running the "filter by position" logic when running lookup on ancestor nodes. Also realised that on the initial node it probably makes sense to combine `selection` and `node` toolbars (QA found weirdness). So, overall, changed the logic so that:
- if running on the initial node, will combine `selection` and `node` toolbars, and if it finds none _then_ go looking for `line` toolbars
- if running on an ancestor node, will look for `selection` then `node` then `line` toolbars
A little worried about performance from all the array iterations? Tried a couple things, this was the best I could think of.
=> TINY-4495 Fix and improve context toolbar prioritisation

modules/tinymce/src/core/main/ts/delete/TableDelete.ts, modules/tinymce/src/core/main/ts/delete/TableDeleteAction.ts, modules/tinymce/src/core/test/ts/browser/delete/TableDeleteTest.ts
This fixes the edge case @ltrouton found and also changes the table delete override logic to only run on single cell tables, to reduce the risk of breaking under any other potential edge cases.
=> TINY-1044: Fixed table cell delete edge case

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/image/main/ts/ui/Dialog.ts, modules/tinymce/src/plugins/image/test/ts/browser/UploadTabTest.ts
We introduced a regression in 5.0.0 whereby closing the error alert dialog for a failed image upload would then also close the image dialog. This didn't happen in v4 and doesn't make sense, as the user is likely to want to retry or pick another image.
Fixes #5684
=> TINY-6020: Fixed the image dialog incorrectly closing when closing the upload error dialog

modules/oxide/src/less/skins/content/dark/content.less, modules/oxide/src/less/skins/content/default/content.less, modules/oxide/src/less/skins/content/document/content.less, modules/oxide/src/less/skins/content/writer/content.less, modules/tinymce/changelog.txt
This reverts the heights added for TINY-5978, as it causes scrolling issues on Firefox since the body is smaller than the content. This does unfortunately mean we still don't have a solution to relative heights for tables, since the CSS spec doesn't treat min-height as an explicit height.
=> TINY-6019: Revert part of default content css changes done in 47b2b8a

modules/oxide/src/less/skins/content/dark/content.less, modules/oxide/src/less/skins/content/default/content.less, modules/oxide/src/less/skins/content/writer/content.less
Note: The `document` content CSS will still be broken as it was in 5.2.2 and lower.
=> TINY-6019: Fully revert the min-height CSS as fullpage breaks autoresize since it removes all body styles

modules/katamari/src/main/ts/ephox/katamari/api/Type.ts, modules/tinymce/changelog.txt, modules/tinymce/package.json, modules/tinymce/src/plugins/table/main/ts/Plugin.ts, modules/tinymce/src/plugins/table/main/ts/actions/InsertTable.ts, modules/tinymce/src/plugins/table/main/ts/api/Api.ts, modules/tinymce/src/plugins/table/main/ts/api/Commands.ts, modules/tinymce/src/plugins/table/main/ts/selection/CellSelection.ts, modules/tinymce/src/plugins/table/main/ts/ui/CellDialog.ts, modules/tinymce/src/plugins/table/main/ts/ui/CellDialogGeneralTab.ts, modules/tinymce/src/plugins/table/main/ts/ui/Helpers.ts, modules/tinymce/src/plugins/table/main/ts/ui/MenuItems.ts, modules/tinymce/src/plugins/table/main/ts/ui/RowDialog.ts, modules/tinymce/src/plugins/table/main/ts/ui/RowDialogGeneralTab.ts, modules/tinymce/src/plugins/table/main/ts/ui/TableDialog.ts, modules/tinymce/src/plugins/table/main/ts/ui/TableDialogGeneralTab.ts, modules/tinymce/src/plugins/table/test/ts/browser/InsertTableCommandTest.ts
The actual feature I implemented is in Commands.ts and InsertTable.ts. The rest came from me trying to add some types and then finding a heap of weird code. Resisted doing any major refactoring and mostly stuck to the ui folder. Deleted a few pieces of code that are left over from T4 features we haven't implemented in T5 (nested class lists) or that might even be left over from T3. 
If people want I can make another branch for the fixes and cherrypick stuff across.
=> TINY-6012 Extend mceInsertTable to allow for headerRows and headerColumns to be specified

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/undo/Setup.ts, modules/tinymce/src/core/test/ts/browser/UndoManagerTest.ts
This is a formatted version of a community patch (#3586) that makes the undo stack filtering code case insensitive. 
Fixes #3586
Note: This is a duplicate of #5708 (which can be closed) as when opening that PR I mistakenly forked the repo.
=> TINY-5946: Made undo command filtering code case insensitive.

yarn.lock
I have no idea how the hash for this ended up being incorrect, but it's different to what we have in v5 and yarn complains with the following error:
> error https://registry.yarnpkg.com/@ephox/wrap-promise-polyfill/-/wrap-promise-polyfill-2.2.0.tgz: Integrity check failed for "@ephox/wrap-promise-polyfill" (computed integrity doesn't match our records, got "sha512-bTvZa0VEBPtCbcl05lYDjMre1WruTRXReCo8Yp2JrOnkf2PK8jgzBrOYPplbjgXvh6ToPqK2wiaeeBApYYgUSQ== sha1-6hHgqIMgtQlt/tYknhaWIcmFP30=")
As such this just updates the lock file to use the same hash as v5.
=> Fixed incorrect wrap-promise-polyfill hash in yarn.lock file

modules/bridge/src/main/ts/ephox/bridge/api/Registry.ts, modules/tinymce/changelog.txt, modules/tinymce/src/themes/silver/main/ts/ui/icons/Icons.ts, modules/tinymce/src/themes/silver/test/ts/atomic/icons/IconsTest.ts, modules/tinymce/src/themes/silver/test/ts/phantom/components/alertbanner/AlertBannerTest.ts
This PR fixes an issue with mixed-case icon names. Currently, icon names are downcased before entry into the registry. However, the `icon` key of a UI element (e.g. a button ) specification is not. This means that consistent capitalisation on the part of the user can lead to missing icons in the interface. Take this excerpt from [http://fiddle.tinymce.com/ILgaab/1](http://fiddle.tinymce.com/ILgaab/1) as an example:
tinymce.IconManager.add('custom', {
icons: {
myCustomIcon: '<svg width="24" height="24"><circle cx="12" cy="12" r="10" stroke="green" stroke-width="4" fill="yellow" /></svg>'
}
});
tinymce.PluginManager.add('adbplugins', function(editor, url) {
editor.ui.registry.addButton('customButton', {
tooltip: 'A sample custom button',
icon: 'myCustomIcon',
onAction: function(buttonApi) { …
=> TINY-3854: Fixed handling of mixed-case icon names by having the silver theme downcase them before icon retrieval

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/fmt/RemoveFormat.ts, modules/tinymce/src/core/test/ts/browser/FormatterRemoveTest.ts
We were moving the start container if between a table cell/row, however we weren't doing that for the end container when removing formats. This caused the `td` to be wrapped in a span, which in turn caused IE 11 to scroll to the bottom of the table. As such, this just adds the same normalization behaviour to the endContainer.
For reference, here's the HTML it was creating that caused IE 11 to scroll:
```
<tr style="height: 21px;" data-mce-style="height: 21px;">
<td style="width: 50%; height: 21px;" data-mce-style="width: 50%; height: 21px;">this is test</td>
<span id="_end" data-mce-type="bookmark">
<td style="width: 50%; height: 21px;" data-mce-style="width: 50%; height: 21px;">
this is <span id="mce_2_start" style="line-height: 0px; overflow: hidden;" data-mce-type="bookmark" …
```
=> TINY-6049: Fixed an issue where removing formatting in a table cell would cause IE 11 to scroll to the end of the table

modules/tinymce/src/core/main/ts/api/dom/ControlSelection.ts
Related Ticket: https://github.com/tinymce/tinymce-docs/issues/1397
* Marking the empty `tinymce.dom.controlselection` API Docs page as private: https://www.tiny.cloud/docs/api/tinymce.dom/tinymce.dom.controlselection/
Pre-checks:
Review:
GitHub issues (if applicable): https://github.com/tinymce/tinymce-docs/issues/1397
=> hiding empty dom.controlselection pg

modules/oxide/src/less/theme/components/button/button-secondary.less, modules/oxide/src/less/theme/components/button/button.less, modules/tinymce/changelog.txt
* Added variables and related css declarations for font related styles of the secondary button
* Added font-style declaration for primary button (it was missing)
No complex css changed. 
Pre-checks:
Review:
_None_
=> Adding additional font related variables for secondary button #TINY-6061

modules/snooker/src/main/ts/ephox/snooker/api/Structs.ts, modules/snooker/src/main/ts/ephox/snooker/operate/Redraw.ts, modules/snooker/src/test/ts/browser/RedrawSectionOrderTest.ts
Related Ticket: TINY-6064
* I was looking into thead/tfoot operations using Snooker and realised Redraw.ts didn't enforce correct section order (caption, colgroups, thead, tbody/trs, tfoot) because I was getting output with tbody then thead, etc. This fixes that.
Pre-checks:
Review:
=> TINY-6064 Enforce table section order in Snooker's Redraw.ts

modules/sugar/src/main/ts/ephox/sugar/api/search/Selectors.ts, modules/sugar/src/test/ts/browser/ShadowDomTest.ts
Related Ticket: TINY-6067
* The bypassSelector function was not considering that shadow roots support querySelector.
Pre-checks:
Review:
n/a
=> Support shadow roots in SelectorFind.descendant.

modules/tinymce/src/core/main/ts/api/ui/Registry.ts
Related Ticket: https://github.com/tinymce/tinymce-docs/issues/1451
* update `tinymce.editor.ui.registry` API docs to include links to the relevant documentation pages (excluding methods updated in https://github.com/tinymce/tinymce/pull/5730)
* updated `tinymce.editor.ui.registry` API docs to less than 120 chars per line.
Pre-checks:
Review:
GitHub issues (if applicable): https://github.com/tinymce/tinymce-docs/issues/1451
=> add links to ui component docs

modules/tinymce/src/core/main/ts/api/ui/Registry.ts
Related Ticket: https://github.com/tinymce/tinymce-docs/issues/1461
* Updating API docs for `addContextForm`, `addContextMenu`, and `addContextToolbar` to include a link to the relevant docs pages.
Pre-checks:
Review:
GitHub issues (if applicable): https://github.com/tinymce/tinymce-docs/issues/1461
=> Add links to docs for context toolbars/forms/menus

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/selection/GetSelectionContentImpl.ts, modules/tinymce/src/core/test/ts/browser/selection/GetSelectionContentTest.ts
This fixes the `editor.selection.getContent({ format: 'text' })` API so that leading/trailing spaces are retained when used in an inline context, whereby the spaces aren't collapsible whitespace.
This wasn't the easiest to solve, since we need to pull the selection out to get the content, which means that we then need to compare it to the original location and see if the rendered version of the parent block element contained the leading/trailing spaces. Added to that, some browsers render trailing spaces differently in specific edge cases, so we discussed this on slack and decided we should try and follow what's rendered in the different browsers since that's what users would see and expect the output to be.
Pre-checks:
Review:
=> TINY-5986: Fixed leading and trailing spaces lost when using `editor.selection.getContent({ format: 'text' })`

modules/snooker/src/main/ts/ephox/snooker/api/CopyCols.ts, modules/snooker/src/main/ts/ephox/snooker/api/CopyRows.ts, modules/snooker/src/main/ts/ephox/snooker/api/Main.ts, modules/snooker/src/main/ts/ephox/snooker/api/TableOperations.ts, modules/snooker/src/main/ts/ephox/snooker/model/Fitment.ts, modules/snooker/src/main/ts/ephox/snooker/model/RunOperation.ts, modules/snooker/src/main/ts/ephox/snooker/model/TableMerge.ts, modules/snooker/src/main/ts/ephox/snooker/operate/MergingOperations.ts, modules/snooker/src/main/ts/ephox/snooker/operate/Redraw.ts, modules/snooker/src/test/ts/browser/CopyColumnsTest.ts, modules/snooker/src/test/ts/browser/CopyRowsTest.ts, modules/snooker/src/test/ts/browser/PasteColumnOperationsTest.ts, modules/snooker/src/test/ts/browser/PasteRowOperationsTest.ts, modules/snooker/src/test/ts/module/ephox/snooker/test/Assertions.ts, modules/tinymce/changelog.txt, modules/tinymce/src/plugins/table/main/ts/Plugin.ts, modules/tinymce/src/plugins/table/main/ts/actions/TableActions.ts, modules/tinymce/src/plugins/table/main/ts/api/Api.ts, modules/tinymce/src/plugins/table/main/ts/api/Commands.ts, modules/tinymce/src/plugins/table/main/ts/core/Clipboard.ts, modules/tinymce/src/plugins/table/main/ts/selection/SelectionTargets.ts, modules/tinymce/src/plugins/table/main/ts/ui/Buttons.ts, modules/tinymce/src/plugins/table/main/ts/ui/MenuItems.ts, versions.txt
* This adds the ability to cut, copy and paste columns in the same manner as the existing row functionality.
**Note:** No icons are available for this yet.
Pre-checks:
Review:
=> TINY-6006: Added API and menu items to allow cut/copy/paste operations on columns

modules/sugar/src/main/ts/ephox/sugar/api/Main.ts, modules/sugar/src/main/ts/ephox/sugar/api/node/Document.ts, modules/sugar/src/main/ts/ephox/sugar/api/node/Head.ts, modules/sugar/src/main/ts/ephox/sugar/api/node/Node.ts, modules/sugar/src/main/ts/ephox/sugar/api/node/ShadowDom.ts, modules/sugar/src/main/ts/ephox/sugar/api/search/Traverse.ts, modules/sugar/src/test/ts/browser/HeadTest.ts, modules/sugar/src/test/ts/browser/ShadowDomTest.ts, modules/sugar/src/test/ts/module/ephox/sugar/test/Arbitrary.ts, modules/sugar/src/test/ts/module/ephox/sugar/test/Doc.ts, modules/sugar/src/test/ts/module/ephox/sugar/test/WithHelpers.ts
Related Ticket: TINY-6075
* Add functions for interacting with Shadow DOM
* Add Head and Document functions in sugar (equivalents of Body)
* Add Node.isDocumentFragment
Pre-checks:
Review:
=> Add functions for interacting with Shadow DOM

modules/tinymce/changelog.txt, modules/tinymce/package.json, modules/tinymce/src/core/main/ts/api/html/DomParser.ts, modules/tinymce/src/core/main/ts/html/ParserFilters.ts, modules/tinymce/src/core/main/ts/init/InitContentBody.ts, modules/tinymce/src/core/test/ts/browser/EditorUploadTest.ts, modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts
This adds a fix to the new parser filter introduced in 5.3.0 that converts base64 images to blobs while parsing. With this change, if the `images_dataimg_filter` is configured an image element will be constructed and then passed to the callback to see if the image should be converted to a blob. If it returns false, then it'll leave it as base64 content.
This also fixes the `EditorUploadTest`, as it was very broken and wasn't failing when assertions failed previously.
**Note:** This is only a temporary fix to unblock the 5.3 enterprise release. We'll need to come back to this in a later release, as moving forward for RTC we need to avoid having base64 images in the editor (which is why this the new filter was introduced).
Pre-checks:
Review:
GitHub issues (if …
=> TINY-6086: Fixed a regression introduced in 5.3.0 whereby the `images_dataimg_filter` wouldn't ever be called

.github/CODEOWNERS
This adds Neil to the codeowners and also ensures Fredrik gets included for oxide related changes.
Also yes, GitHub is annoying in that a more specific rule excludes the global owners list :disappointed:
=> Updated codeowners to reflect team changes

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/advlist/main/ts/ui/Buttons.ts, modules/tinymce/src/plugins/advlist/test/ts/browser/ToolbarButtonStructureTest.ts
Recreating pull request with the right issue.
Fixes #4776
=> TINY-3194: Changed advlist to only show split button if there's more than one options.

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/Tinymce.ts, modules/tinymce/src/core/main/ts/api/dom/DOMUtils.ts, modules/tinymce/src/core/main/ts/api/dom/StyleSheetLoader.ts
* Move StyleSheetLoader into public api folder. It was already part of DOMUtils. This change will allow StyleSheetLoaders to be created by the silver theme, which may be useful for Shadow DOM support. 
Pre-checks:
Review:
=> Move StyleSheetLoader into public api folder.

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/autolink/main/ts/api/Settings.ts, modules/tinymce/src/plugins/autolink/test/ts/browser/AutoLinkPluginTest.ts
Also added tests to display some of the unexpected and invalid inputs we use.
Fixes #5495
=> TINY-4773: Restricted regexs to only accept one @.

Gruntfile.js
* Bumps the total test timeout from 17mins to 20mins, as with the addition of new tests we're now running over 17mins on IE 11.
Pre-checks:
Review:
=> Bumped total test timeout as it was failing on IE 11 due to additional tests

modules/katamari/src/main/ts/ephox/katamari/api/Results.ts, modules/katamari/src/test/ts/atomic/api/data/ResultsTest.ts, modules/tinymce/src/core/main/ts/api/dom/StyleSheetLoader.ts
* `Result<T, T> -> T`. Similar function exists on the `\/` (Either) type in Scalaz (they call it "merge"). Replaces `unbox` function in `StyleSheetLoader`. 
Pre-checks:
Review:
=> Results.unite

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/SettingsTypes.ts, modules/tinymce/src/core/main/ts/api/html/DomParser.ts, modules/tinymce/src/core/main/ts/init/InitContentBody.ts, modules/tinymce/src/core/test/ts/browser/content/HTMLDataURLsTest.ts
Pre-checks:
Review:
Fixes #4669
=> TINY-5951: Pass editor.allow_html_data_urls through to SaxParser

modules/katamari/src/main/ts/ephox/katamari/api/LazyValue.ts, modules/katamari/src/test/ts/atomic/api/async/LazyValueTest.ts
Related Ticket: TINY-6106
* A Katamari LazyValue wraps an asynchronous function, similar to a Future. The async function has to call a callback to complete. If the callback is called multiple times, then the LazyValue's value is set to the last of these. Basically, the LazyValue becomes mutable, which isn't what's intended. Instead, LazyValue should only consider the value from the first callback, and should ignore subsequent values.
Pre-checks:
Review:
=> LazyValue should only use the value from the first callback

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/SelectionOverrides.ts, modules/tinymce/src/core/main/ts/caret/LineUtils.ts, modules/tinymce/src/core/main/ts/dom/Dimensions.ts, modules/tinymce/src/core/test/ts/browser/caret/LineUtilsTest.ts
Related Ticket: TINY-6057
This fixes a performance issue on IE and Edge (Firefox was also partially impacted, but it's much faster so wasn't noticeable). The cause was that when clicking, TinyMCE would attempt to find a suitable fake caret position to place the cursor at. The problem however, was that it would attempt to find all client rects on the same "line", but since a table is a single "line" it would get the client rects of every cell and the nodes inside each cell.
This was slow on IE and Edge, as they are somewhat slow at computing the client rect. This really wasn't needed, as for a table the fake caret will never be inside the table. So this just updates the logic to skip checking the children of a table when computing the line rects for the potential …
=> TINY-6057: Fixed a selection performance issue when using large tables on IE and Edge

modules/tinymce/changelog.txt, modules/tinymce/src/core/test/ts/browser/init/ShadowDomEditorTest.ts, modules/tinymce/src/themes/silver/main/ts/modes/Iframe.ts
Related Ticket: TINY-6093
* TinyMCE's Silver theme uses a div as a container for menus. This div is known as the "aux" or "sink" div. This change moves its location to within the ShadowRoot if the editor is within a ShadowRoot. Without this, menus do not display correctly.
Pre-checks:
Review:
=> Ensure aux div is in ShadowRoot if editor is in ShadowRoot

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/EditorManager.ts, modules/tinymce/src/core/main/ts/api/SettingsTypes.ts, modules/tinymce/src/core/main/ts/content/Placeholder.ts, modules/tinymce/src/core/main/ts/init/InitContentBody.ts, modules/tinymce/src/core/main/ts/init/Render.ts, modules/tinymce/src/core/test/ts/browser/EditorCleanupTest.ts, modules/tinymce/src/core/test/ts/browser/init/EditorInitializationTest.ts, modules/tinymce/src/plugins/visualblocks/main/ts/core/Bindings.ts
Cleans up attributes on the target element when the editor is removed. Takes a snapshot of the attribute state when creating the editor, and restores it later. Also centralises a bit of code that was scattered around the codebase aiming to do the same thing for individual attributes / classes.
Pre-checks:
Review:
Fixes #5117
=> TINY-4001: Cleanup attributes created on target element

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/link/main/ts/ui/DialogConfirms.ts, modules/tinymce/src/plugins/link/test/ts/browser/UrlProtocolTest.ts
Related Ticket: TINY-5941
The link plugin currently suggests a `mailto:` protocol if it detects an at-sign '@' without the URL protocol distinguisher ('//'). However, with the rise of using '@' in filenames to indicate DPI, this has become a nuisance for relative paths. This commit has the plugin suggest `mailto:` when it detects the '@' without one or more URL separators ('/'). I've done some checking based on a friend's huge database of real e-mails and none use the (legally acceptable) slash whereas a quick googling reveals that over 5% of image URLs now use the '@', so this seems like a better heuristic. 
Pre-checks:
Review:
GitHub issues (if applicable): 
Fixes https://github.com/tinymce/tinymce/issues/3128
=> TINY-5941 Changed the `link` plugin to suggest `mailto:` based on the absence of URL separators (slashes)

modules/tinymce/src/core/main/ts/api/Editor.ts
Related Ticket: DOC-581
* Adds back some documentation that accidentally got deleted in 5.0.4, as moxiedoc doesn't handle the `@deprecated` marker.
Pre-checks:
Review:
=> DOC-581: Add back deprecated setMode API documentation

modules/tinymce/src/core/test/ts/browser/init/ShadowDomEditorTest.ts
Related Ticket: TINY-6143
* This test was testing that there are no skin stylesheets in the body. However, previous tests may have added a skin stylesheet. For now, we're just removing this test condition. In future, we probably need a `StyleSheetLoader.removeAll()` method.
Pre-checks:
Review:
=> Remove failing condition in ShadowDomEditorTest

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/table/main/ts/alien/Util.ts, modules/tinymce/src/plugins/table/main/ts/api/Settings.ts, modules/tinymce/src/plugins/table/main/ts/core/TableRowSectionTypes.ts, modules/tinymce/src/plugins/table/main/ts/core/TableSections.ts, modules/tinymce/src/plugins/table/main/ts/ui/CellDialog.ts, modules/tinymce/src/plugins/table/main/ts/ui/Helpers.ts, modules/tinymce/src/plugins/table/main/ts/ui/RowDialog.ts, modules/tinymce/src/plugins/table/test/ts/browser/DetectHeaderRowTest.ts, modules/tinymce/src/plugins/table/test/ts/browser/SwitchTableSectionTest.ts
Related Ticket: TINY-6007
* Correctly detect the 3 kinds of table header row structures
* Add new `table_header_type` setting to control which structure is used for table plugin's output
* Make the row dialog switch row/section types based on the setting/determine the type of a header row by detection
* Unit test for header row type detection
* Unit test for row/section switching
There will be more parts:
- API methods for switching table row/section types
- Updating the table creation API I did the other week to respect this setting, etc.
At some point would like to move this into Snooker too, but that requires fixing Snooker's problem with losing `tr` attributes first, so shelving that for now.
Pre-checks:
Review:
Fixes #3941
=> Feature/TINY-6007 (part of) Table header detection and section switching + new setting

modules/tinymce/src/core/main/ts/api/Shortcuts.ts
Related Ticket: https://github.com/tinymce/tinymce-docs/issues/1539
* Fixing minor typo in shortcut API docs
Pre-checks:
Review:
GitHub issues (if applicable): https://github.com/tinymce/tinymce-docs/issues/1539
=> GH_DOCS_1539: API docs typo

modules/katamari/src/main/ts/ephox/katamari/api/Type.ts, modules/katamari/src/test/ts/atomic/api/type/TypeTest.ts, modules/sugar/src/main/ts/ephox/sugar/api/node/ShadowDom.ts, modules/sugar/src/main/ts/ephox/sugar/impl/FilteredEvent.ts, modules/sugar/src/test/ts/browser/ShadowDomTest.ts, modules/sugar/src/test/ts/module/ephox/sugar/test/WithHelpers.ts, modules/tinymce/changelog.txt
Related Ticket: TINY-6091
* Set event targets to the "original" target, by inspecting composedPath. See the comments in the code for more details.
* This fixes clicking on menus when the editor is in a shadow root.
Pre-checks:
Review:
=> Set event targets to the "original" target, by inspecting composedPath

modules/sugar/src/main/ts/ephox/sugar/api/dom/Focus.ts, modules/sugar/src/test/ts/browser/ElementInstancesTest.ts, modules/sugar/src/test/ts/browser/FocusTest.ts, modules/sugar/src/test/ts/module/ephox/sugar/test/WithHelpers.ts, modules/tinymce/changelog.txt
* Add keyboard navigation to editors in shadow roots, by adding shadow dom support to focus code
* Minor refactors
Pre-checks:
Review:
=> Add keyboard navigation to editors in shadow roots, by adding shadow dom support to focus code

modules/tinymce/src/core/main/ts/api/Editor.ts, modules/tinymce/src/core/main/ts/api/Shortcuts.ts
Related Ticket: DOC-464
* Add useful examples to `editor.shortcuts.add` and `editor.addshortcut`API docs
Pre-checks:
Review:
=> DOC-464: add examples to shortcut api docs

modules/tinymce/src/core/main/ts/api/dom/StyleSheetLoader.ts, modules/tinymce/tools/docs/tinymce.editor.ui.Ui.js
Related Ticket: DOC-600
* Set Stylesheetloader API docs to public
Pre-checks:
Review:
=> DOC-600: Set stylesheetloader docs to public, add loadall docs

modules/tinymce/src/core/main/ts/api/Tinymce.ts, modules/tinymce/src/plugins/table/main/ts/actions/ResizeHandler.ts
Related Ticket: TINY-6051
* This fixes an issue I noticed overnight whereby if you didn't have a fixed sizing mode on and then resized a table without widths it'd resize incorrectly. This also moves the responsive -> relative conversion until after the initial resize, which makes it behave more like it previously did.
Pre-checks:
Review:
=> TINY-6051: Fixed an issue where responsive tables weren't converted to relative tables when resizing

modules/tinymce/src/plugins/help/main/ts/data/PluginUrls.ts
Related Ticket: TINY-6189
* Fix broken plugin URLs in the help plugin
Pre-checks:
Review:
=> TINY-6189: Fix broken help urls

modules/snooker/src/main/ts/ephox/snooker/api/TableConversions.ts
Related Ticket: TINY-6000
* Fixes an issue @trevorjay found that prevented swapping back to responsive sizing mode since we don't clean up the legacy width attributes.
Pre-checks:
Review:
=> TINY-6000: Fixed legacy width attribute not being removed when switching sizing modes

modules/acid/package.json, modules/agar/package.json, modules/alloy/package.json, modules/boss/package.json, modules/boulder/package.json, modules/bridge/package.json, modules/darwin/package.json, modules/dragster/package.json, modules/imagetools/package.json, modules/jax/package.json, modules/katamari-assertions/package.json, modules/katamari/package.json, modules/mcagar/package.json, modules/oxide-icons-default/package.json, modules/oxide/package.json, modules/phoenix/package.json, modules/polaris/package.json, modules/porkbun/package.json, modules/robin/package.json, modules/sand/package.json, modules/snooker/package.json, modules/sugar/package.json, modules/tinymce/changelog.txt
Related Ticket: TINY-6190
```
Changes:
- @ephox/acid: 1.0.76 => 1.0.77
- @ephox/agar: 4.15.5 => 4.16.0
- @ephox/alloy: 7.0.2 => 7.0.3
- @ephox/boss: 3.1.5 => 3.1.6
- @ephox/boulder: 4.0.5 => 4.0.6
- @ephox/bridge: 1.2.1 => 1.2.2
- @ephox/darwin: 4.0.16 => 4.0.17
- @ephox/dragster: 4.0.48 => 4.0.49
- @ephox/imagetools: 3.3.1 => 3.3.2
- @ephox/jax: 4.1.33 => 4.1.34
- @ephox/katamari-assertions: 1.0.6 => 1.0.7
- @ephox/katamari: 6.0.1 => 6.1.0
- @ephox/mcagar: 4.1.6 => 4.2.0
- @tinymce/oxide-icons-default: 1.3.3 => 1.4.0
- @tinymce/oxide: 1.3.3 => 1.4.0
- @ephox/phoenix: 5.1.6 => 5.1.7
- @ephox/polaris: 3.0.50 => 3.0.51
- @ephox/porkbun: 4.0.35 => 4.0.36
- @ephox/robin: 7.0.53 => 7.0.54
- @ephox/sand: 3.1.8 => 3.1.9
- @ephox/snooker: 5.1.14 => 6.0.0
- @ephox/sugar: …
```
=> TINY-6190: Added changelog and bump versions for 5.4.0 release

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/media/main/ts/core/UpdateHtml.ts, modules/tinymce/src/plugins/media/test/ts/atomic/UpdateHtmlTest.ts
Related Ticket: TINY-4113
Pre-checks:
Review:
=> TINY-4113: Now saves both sources if only one previously existed.

modules/acid/package.json, modules/agar/package.json, modules/alloy/package.json, modules/boss/package.json, modules/bridge/package.json, modules/darwin/package.json, modules/dragster/package.json, modules/imagetools/package.json, modules/imagetools/src/main/ts/ephox/imagetools/util/Conversions.ts, modules/jax/package.json, modules/katamari-assertions/package.json, modules/katamari/package.json, modules/mcagar/package.json, modules/phoenix/package.json, modules/polaris/package.json, modules/robin/package.json, modules/sand/package.json, modules/snooker/package.json, modules/tinymce/package.json, modules/tinymce/src/core/main/ts/api/dom/EventUtils.ts, package.json, yarn.lock
Related Ticket: TINY-6127
* Upgrade TypeScript to 3.9.5 and upgraded other dependencies as well
Pre-checks:
Review:
=> TINY-6127: Upgrade to TypeScript 3.9.5 and upgrade other deps

modules/tinymce/src/plugins/help/main/ts/data/PluginUrls.ts, modules/tinymce/src/plugins/help/main/ts/ui/PluginsTab.ts
Related Ticket: TINY-6189
* Fixes the help plugin that was broken in 5.4.0 while attempting to fix the broken URLs for comments and drive.
Pre-checks:
Review:
=> TINY-6189: Fixed broken help detection for Tiny Drive and Tiny Comments

modules/tinymce/src/core/main/ts/api/Editor.ts, modules/tinymce/src/core/main/ts/api/EditorCommands.ts
Related Ticket: DOC-571
* Remove the incorrect `queryCommandState` return type in the API docs.
Pre-checks:
Review:
=> DOC-571: API docs - fix queryCommandState return

changelog.txt, js/tinymce/classes/html/SaxParser.js, js/tinymce/plugins/visualchars/plugin.js, package.json, tests/plugins/visualchars.js, tests/tinymce/html/SaxParser.js
Related Ticket: TINY-6073
* This backports the following parsing/serialization fixes for 4.5.x:
* xlink:href fix done in 4.7.12 (see https://github.com/tinymce/tinymce/commit/15ff5b81c2a1e44efbc7fdba92b65d2bdcbc4c38)
* comments fix done in 4.9.7 (see https://github.com/tinymce/tinymce/commit/cb6bbf495356a6fbd333ab8c0ce17a32fca81cc5)
* cdata fix done in 4.9.10 (see https://github.com/tinymce/tinymce/commit/aa516c52d4f2104c36af3d640b2adb22e379f9a4)
* visual chars plugin fix done in 4.9.7 (see https://github.com/tinymce/tinymce/commit/84156be76c0ed398b1a3f806cd353ae0eb3f1473)
Pre-checks:
Review:
=> TINY-6073: Backported parsing fix to 4.5.x

changelog.txt, js/tinymce/classes/dom/Selection.js, js/tinymce/classes/html/Schema.js, tests/tinymce/dom/Selection.js, tests/tinymce/html/DomParser.js, tests/tinymce/html/SaxParser.js
Related Ticket: TINY-6073
* This backports the additional security fixes to 4.5.x:
* `selection.setContent()` API not running parser filters (see https://github.com/tinymce/tinymce/pull/5845/commits/b3d0f6352aeb5b65eb7633c91477930dfbbfeda7)
* iframe content not being parsed correctly (see https://github.com/tinymce/tinymce/pull/5844/commits/2b71c922214d388838d930806207a66c14e80f63)
Note: I also found 4.5.x was missing a number of additional special elements, which caused similar issues to the iframe. So I've included all of them as special elements.
Pre-checks:
Review:
=> TINY-6073: Backported additional security fixes to 4.5.x

modules/tinymce/changelog.txt, modules/tinymce/package.json, modules/tinymce/src/plugins/searchreplace/main/ts/core/Actions.ts, modules/tinymce/src/plugins/searchreplace/test/ts/browser/SearchReplacePluginTest.ts
Related Ticket: TINY-4599
* This fixes zwsp caret characters being included in the search results.
Pre-checks:
Review:
=> TINY-4599: Fixed zero-width characters included in the Search and Replace results

changelog.txt, package.json, src/core/main/ts/api/html/Schema.ts, src/core/main/ts/html/ParserFilters.ts, src/core/test/ts/browser/html/DomParserTest.ts, src/core/test/ts/browser/html/SaxParserTest.ts, src/core/test/ts/browser/html/SchemaTest.ts
Related Ticket: TINY-5943
Backports the fix done for 5.4.1 to the 4.x release stream. See https://github.com/tinymce/tinymce/pull/5843
Pre-checks:
Review:
=> TINY-5943: Backported iframe with content not getting parsed correctly

changelog.txt, src/core/main/ts/content/GetContent.ts, src/core/main/ts/selection/GetSelectionContent.ts, src/core/main/ts/selection/SetSelectionContent.ts, src/core/test/ts/browser/dom/SelectionTest.ts
Related Ticket: TINY-5992 & TINY-4002
* Backports the fix for the `editor.selection.setContent()` API not running parser filters, etc... to the 4.9.x release stream. See: https://github.com/tinymce/tinymce/pull/5598
Pre-checks:
Review:
=> TINY-5992: Backported `selection.setContent()` API not running parser filters

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/html/Schema.ts, modules/tinymce/src/core/main/ts/html/ParserFilters.ts, modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts, modules/tinymce/src/core/test/ts/browser/html/SaxParserTest.ts, modules/tinymce/src/core/test/ts/browser/html/SchemaTest.ts
Related Ticket: TINY-5943
As per the HTML parsing spec [1], content within an `<iframe>` element should be parsed as general text, so this just adds iframe to the special elements list. This also fixes an issue I noticed where a parser filter was using the wrong data from the schema (though it was very similar data).
[1] https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inbody
Pre-checks:
Review:
=> TINY-5943: Fixed an issue where iframes with content aren't getting parsed correctly

modules/agar/src/main/ts/ephox/agar/api/Mouse.ts, modules/agar/src/main/ts/ephox/agar/mouse/Clicks.ts, modules/darwin/src/main/ts/ephox/darwin/api/InputHandlers.ts, modules/darwin/src/main/ts/ephox/darwin/mouse/MouseSelection.ts, modules/katamari/src/main/ts/ephox/katamari/api/Singleton.ts, modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/DragDropOverrides.ts, modules/tinymce/src/core/main/ts/dom/MousePosition.ts, modules/tinymce/src/plugins/image/test/ts/browser/UploadTabTest.ts, modules/tinymce/src/plugins/table/main/ts/selection/CellSelection.ts, modules/tinymce/src/plugins/table/test/ts/browser/DragSelectionTest.ts, versions.txt
Related Ticket: TINY-5950
* Deprecated a lot of the methods in agar's Mouse module, replacing them with more customisable alternatives
* Added more types to DragDropOverrides.ts in core
* Fixed the issue where dragging and dropping inside a table could lead to selections in the table
Pre-checks:
Review:
Fixes a bug brought up during #3075
=> Tiny 5950: Prevent dragging and dropping inside a table from creating selections

modules/oxide/src/less/theme/content/checklist/checklist.less, modules/tinymce/changelog.txt
Related Ticket: TINY-5139 & TINY-5135
* This changes the checklist icons to be content, rather than background images. This ensures they will show when printing (as background images are ignored) and solves the issue where IE 11 wouldn't render the checklist for the first item.
* Note: URLs can be used for content on all supported browsers, see: https://developer.mozilla.org/en-US/docs/Web/CSS/content#Browser_compatibility I've also manually tested to make sure this works.
Pre-checks:
Review:
=> TINY-5139: Fixed checklist icons not showing when printing

modules/agar/src/main/ts/ephox/agar/api/DragnDrop.ts, modules/agar/src/test/ts/browser/api/DragnDropTest.ts, modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/DragDropOverrides.ts, modules/tinymce/src/core/main/ts/api/Settings.ts, modules/tinymce/src/core/main/ts/api/SettingsTypes.ts, modules/tinymce/src/core/main/ts/undo/Setup.ts, modules/tinymce/src/core/test/ts/browser/DragDropOverridesTest.ts
Related Ticket: TINY-6027
* Adds overrides to prevent dropping files within the editor or onto the editor UI. This is using `DOMUtils` as we can't use the `editor.on` API, since we want this to run after all the editor event handlers have run.
**Note:** I'll create a follow-up PR once this is merged to port it to `develop` and add the notification for TinyMCE 5.5
Pre-checks:
Review:
=> TINY-6027: Fixed dragging and dropping unsupported files navigating the browser away from the editor

modules/agar/src/main/ts/ephox/agar/api/DragnDrop.ts, modules/agar/src/test/ts/browser/api/DragnDropTest.ts, modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/DragDropOverrides.ts, modules/tinymce/src/core/main/ts/api/Settings.ts, modules/tinymce/src/core/main/ts/api/SettingsTypes.ts, modules/tinymce/src/core/main/ts/undo/Setup.ts, modules/tinymce/src/core/test/ts/browser/DragDropOverridesTest.ts
Related Ticket: TINY-6027
* This adds the notification banner and merges the changes from master to develop. See 26d6976e8eab52e8891b7281ae6349e148504ea7 for the additional changes.
Pre-checks:
Review:
=> TINY-6027: Added notification banner when blocking an unsupported file drop

yarn.lock
Related Ticket: TINY-6024
* Upgrade to bedrock 9.6.2 to fix retry issues and upgrade to TS 3.9.6
Pre-checks:
Review:
=> TINY-6204: Upgraded to bedrock 9.6.2 and TS 3.9.6

changelog.txt, src/core/main/ts/geom/ClientRect.ts, src/core/main/ts/keyboard/CefNavigation.ts, src/core/main/ts/keyboard/CefUtils.ts, src/core/main/ts/keyboard/TableNavigation.ts, src/core/test/ts/browser/geom/ClientRectTest.ts, src/core/test/ts/browser/keyboard/ArrowKeysCefTest.ts
Related Ticket: TINY-6226
* Backports the fix done for TinyMCE 5.5.0 (Note: Some changes are different due to the differences in v4 and v5).
Pre-checks:
Review:
=> TINY-6226: Backported up and down keyboard navigation not working for inline contenteditable false elements

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/delete/DeleteCommands.ts, modules/tinymce/src/core/main/ts/geom/ClientRect.ts, modules/tinymce/src/core/main/ts/keyboard/CefNavigation.ts, modules/tinymce/src/core/main/ts/keyboard/CefUtils.ts, modules/tinymce/src/core/main/ts/keyboard/DeleteBackspaceKeys.ts, modules/tinymce/src/core/main/ts/keyboard/TableNavigation.ts, modules/tinymce/src/core/test/ts/browser/geom/ClientRectTest.ts, modules/tinymce/src/core/test/ts/browser/keyboard/ArrowKeysCefTest.ts
Related Ticket: TINY-6226
* Ports contenteditable=false fixes from https://github.com/tinymce/tinymce/pull/5859, as we're not going ahead with the node filters in that now.
> This fixes some various navigation issues I encountered when manually testing this, such as pressing up not working when near a media element or it not scrolling the cursor into view after pressing up/down. The former was actually a bug I tried to fix when I first started (but no one got back to me) and was a regression caused by the fix for TINY-981 (see 73c077b6be41d355ed9ee346710c05fce2e13ec9). I don't believe we even need the bottom adjustments (based on manual testing), however since I couldn't find out for sure why it was added I've instead opted to limit how much it can be adjusted to. …
=> TINY-6226: Fixed up and down keyboard navigation not working for inline contenteditable false elements

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/link/main/ts/core/Utils.ts, modules/tinymce/src/plugins/link/main/ts/ui/Controls.ts, modules/tinymce/src/plugins/link/main/ts/ui/DialogInfo.ts, modules/tinymce/src/plugins/link/test/ts/browser/SelectedTextLinkTest.ts
Related Ticket: TINY-5205
* The way the "Text to display" field was being determined was rather hacky, as it just used a regex on the selected content. This caused problems when coupled with Comments for example, as Comments would add a HTML comment that would cause this to no longer match. This updates it to actually walk the dom and determine when it shouldn't be shown based on the elements found.
* This also fixes an inconsistency with how it handled "inline text elements" inside an anchor, as if you used a collapsed selection for something like `<a href="URL"><strong>word</strong> more</a>`, then the "Text to display" would be shown. However, if you did a range selection then the field would disappear.
Pre-checks:
Review:
=> TINY-5205: Fixed the `link` dialog not showing the "Text to display" field in some valid cases

modules/tinymce/changelog.txt, modules/tinymce/src/themes/silver/main/ts/Render.ts, modules/tinymce/src/themes/silver/main/ts/ui/general/OuterContainer.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/ToolbarFocusTest.ts
Related Ticket: TINY-6230
* Fixes pressing the escape key when a multiple toolbar was focused not returning focus to the editor. This appears to have been something that was missed when multiple toolbars was originally implemented.
Pre-checks:
Review:
Fixes #5876
=> TINY-6230: Fixed pressing escape not focusing the editor when using multiple toolbars

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/preview/main/ts/api/Settings.ts, modules/tinymce/src/plugins/preview/main/ts/core/IframeContent.ts, modules/tinymce/src/plugins/template/main/ts/api/Settings.ts, modules/tinymce/src/plugins/template/main/ts/ui/Dialog.ts, modules/tinymce/src/plugins/template/test/ts/browser/DialogGetPreviewContentTest.ts
Allowed template to also apply CORS and content style, similar to preview.
Pre-checks:
Review:
=> TINY-6115: Fixed template previews missing styles and other content

modules/tinymce/changelog.txt, modules/tinymce/package.json, modules/tinymce/src/core/main/ts/api/SettingsTypes.ts, modules/tinymce/src/plugins/link/test/ts/browser/AnchorFalseTest.ts, modules/tinymce/src/themes/silver/main/ts/api/Settings.ts, modules/tinymce/src/themes/silver/main/ts/backstage/UrlInputBackstage.ts
Related Ticket: TINY-6256
This fixes a regression introduced in 5.4.0 via 5ceb2d15cc20a42b3224392759efa05a17443666, as it was changed so that the setting would only allow string values, which is incorrect as it should be `false | string`.
Pre-checks:
Review:
Fixes #5904
=> TINY-6256: Fixed a regression where the `anchor_top` and `anchor_bottom` settings weren't working when set to `false`

.eslintrc.json, modules/agar/src/main/ts/ephox/agar/arbitrary/PropertySteps.ts, modules/agar/src/main/ts/ephox/agar/pipe/Pipe.ts, modules/alloy/src/test/ts/browser/api/CustomComponentTest.ts, modules/jax/src/main/ts/ephox/jax/core/Http.ts, modules/katamari/src/test/ts/atomic/api/async/FutureResultTest.ts, modules/katamari/src/test/ts/atomic/api/async/FutureTest.ts, modules/katamari/src/test/ts/atomic/api/async/LazyValueTest.ts, modules/katamari/src/test/ts/module/ephox/katamari/test/AsyncProps.ts, modules/tinymce/src/core/main/ts/api/dom/Sizzle.ts, modules/tinymce/src/themes/silver/test/ts/phantom/window/TabbedDialogTest.ts, yarn.lock
* This upgrades the linter to 1.3 and re-enables the rules that were disabled because of bugs. It also removes the overrides that are now part of the defaults.
Pre-checks:
Review:
=> Upgraded the eslint-plugin and fixed issues

modules/tinymce/changelog.txt, modules/tinymce/src/themes/silver/main/ts/ContextToolbar.ts
Related Ticket: TINY-6271
* This fixes an exception that was being thrown on IE 11 due to the previous element no longer being in the dom, since it'd been overwritten when pasting in content.
Pre-checks:
Review:
=> TINY-6271: Fixed IE 11 throwing an exception when the previous context toolbar element is no longer attached to the dom

package.json, yarn.lock
Related Ticket: TINY-3785
* This upgrades to version 1.4 of the eslint plugin, which has the new `no-implicit-dom-globals` rule.
Pre-checks:
Review:
=> TINY-3785: Upgrade to use the new eslint-plugin version, to prevent implicit dom globals being used

modules/tinymce/src/themes/silver/main/ts/ui/dialog/CustomEditor.ts
Related Ticket: TINY-6274
* We removed most "foo" references a while back, but looks like we missed one (thanks to @ephox-mogran for finding it). I tried to look for others, but the only others were in tests.
Pre-checks:
Review:
=> TINY-6274: Removed missed "foo" reference

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/NotificationManager.ts, modules/tinymce/src/themes/silver/main/ts/ui/general/Notification.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/NotificationManagerImplTest.ts
Related Ticket: TINY-6058
This fixes an issue whereby clicking the notification would cause inline editors to hide, since the focus would move back to the body.
Pre-checks:
Review:
Fixes #5702
=> TINY-6058: Fixed clicking on notifications causing inline editors to hide

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/lists/demo/ts/demo/Demo.ts, modules/tinymce/src/plugins/lists/main/ts/core/Util.ts, modules/tinymce/src/plugins/lists/test/ts/browser/ListPropertiesTest.ts, modules/tinymce/src/plugins/lists/test/ts/browser/ToggleListWithEmptyLiTest.ts
Related Ticket: TINY-6286
* Fixes a regression introduced in 5.3.0 whereby the lists toolbar state wouldn't toggle, as the listener was only being setup on teardown of the toolbar button.
Pre-checks:
Review:
=> TINY-6286: Fixed a regression causing list toolbar items to not show the active state

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/fullscreen/demo/html/demo.html, modules/tinymce/src/plugins/fullscreen/demo/ts/demo/Demo.ts, modules/tinymce/src/plugins/fullscreen/main/ts/Plugin.ts, modules/tinymce/src/plugins/fullscreen/main/ts/api/Api.ts, modules/tinymce/src/plugins/fullscreen/main/ts/api/Commands.ts, modules/tinymce/src/plugins/fullscreen/main/ts/api/Settings.ts, modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts, modules/tinymce/src/plugins/fullscreen/main/ts/core/NativeFullscreen.ts, modules/tinymce/src/plugins/fullscreen/test/ts/webdriver/FullscreenPluginNativeModeTest.ts
Related Ticket: TINY-6284
* Allow the fullscreen plugin to actually trigger the fullscreen mode of the browser when setting `fullscreen_native` is set to `true`.
Pre-checks:
Review:
Fixes #4969
=> TINY-6284: Make fullscreen mode request browser fullscreen

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/fmt/CaretFormat.ts, modules/tinymce/src/core/test/ts/browser/fmt/CaretFormatTest.ts
Related Ticket: TINY-6216
* While fixing TINY-6288, I ran into this and realised it was a quick fix which had rather bad side effects when using format painter. The idea behind this fix is we treat any format with `removeformat` in the name, to be a "remove" only format.
Pre-checks:
Review:
=> TINY-6216: Fixed inline formats not able to be removed when more than 1 removeformat exists

modules/tinymce/src/core/main/ts/api/NotificationManager.ts, modules/tinymce/src/core/test/ts/browser/NotificationManagerTest.ts, modules/tinymce/src/themes/silver/main/ts/ui/general/Notification.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/NotificationManagerImplTest.ts
Related Ticket: TINY-6058
* This adds additional focus fixes to the notifications found during QA. The focus will now shift to the button by default, so as to allow it to be closed via the keyboard and when closing a notification it'll attempt to move to another notification or if none are shown it'll focus the editor (ie does the same as dialogs).
Pre-checks:
Review:
=> TINY-6058: Additional focus fixes for notifications

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/fmt/MergeFormats.ts, modules/tinymce/src/core/main/ts/fmt/MergeUtils.ts, modules/tinymce/src/core/main/ts/fmt/RemoveFormat.ts, modules/tinymce/src/core/test/ts/browser/FormatterRemoveTest.ts
Related Ticket: TINY-6288
* This fixes an exception that's thrown when only partially removing an inline format that contains styles or classes. This can end up in the editor when copying and pasting HTML from outside the editor. It also fixes an issue missed when the preserve attributes logic was added, where sibling nodes that had the same styles wouldn't be merged.
Pre-checks:
Review:
=> TINY-6288: Fixed an exception thrown when removing inline formats with preserve_attributes configured

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/dom/Empty.ts, modules/tinymce/src/core/main/ts/dom/TrimNode.ts, modules/tinymce/src/core/test/ts/browser/dom/DomUtilsTest.ts, modules/tinymce/src/core/test/ts/browser/dom/EmptyTest.ts, modules/tinymce/src/core/test/ts/browser/dom/TrimNodeTest.ts
Related Ticket: TINY-6294
When investigating TINY-6251 (https://github.com/tinymce/tinymce/pull/5937) we found a number of bugs with the with the `TrimNode` module. We deemed they were probably too risky to include in 5.4.2, so we're including a partial fix there and this should be a more in-depth fix. The idea behind this is to re-use an existing isEmpty check instead of trying to reimplement it.
Pre-checks:
Review:
Fixes #4995
=> TINY-6294: Fixed TrimNode.trimNode() removing nodes it shouldn't

modules/sugar/src/main/ts/ephox/sugar/api/view/VisualViewport.ts, modules/sugar/src/test/ts/browser/VisualViewportTest.ts, modules/tinymce/changelog.txt
Related Ticket: TINY-3511
* We had broken the `VisualViewport.bind` function at some stage while refactoring and as such it was never calling the callback. This then meant the fullscreen plugin wasn't adjusting the editor to match the new viewport size.
Pre-checks:
Review:
=> TINY-3511: Fixed the visual viewport bind function not working, which also caused fullscreen plugin issues

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/dom/ElementType.ts, modules/tinymce/src/core/main/ts/selection/FragmentReader.ts, modules/tinymce/src/core/main/ts/selection/TableCellSelection.ts, modules/tinymce/src/core/test/ts/browser/selection/FragmentReaderTest.ts
Related Ticket: TINY-6289
* Fixed an issue where the list type styles weren't included when getting using the selection API for a contextual cut/copy operation.
Pre-checks:
Review:
=> TINY-6289: Fixed the list type style not retained when copying list items

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/link/main/ts/ui/Dialog.ts, modules/tinymce/src/plugins/link/main/ts/ui/DialogChanges.ts, modules/tinymce/src/plugins/link/main/ts/ui/DialogTypes.ts, modules/tinymce/src/plugins/link/test/ts/atomic/DialogChangesTest.ts, modules/tinymce/src/plugins/link/test/ts/browser/SelectedImageLinkTest.ts
Related Ticket: TINY-4706 & TINY-6273
* This fixes an issue where link urls couldn't be deleted/edited in the dialog. The cause was that we were incorrectly setting the URL "text" metadata which then made the typeahead component believe it was the same as the original url and replaced it with the original url.
* This also fixes another issue reported in one of the linked GitHub issues, that I also later found a JIRA for, in that the title was being incorrectly changed when changing the url.
Pre-checks:
Review:
Fixes #4939
Fixes #5403
Fixes #5888
=> TINY-4706/TINY-6273: Fixed an issue where link urls couldn't be deleted or edited in some cases

modules/tinymce/src/plugins/paste/main/ts/core/Clipboard.ts, modules/tinymce/src/plugins/paste/main/ts/core/CutCopy.ts, modules/tinymce/src/plugins/paste/main/ts/core/Utils.ts, modules/tinymce/src/plugins/paste/test/ts/browser/InternalClipboardTest.ts
Related Ticket: TINY-6117
* Syncs a fix from PowerPaste and removes the Edge 15 checks as it's no longer needed given Edge 15 isn't supported.
Pre-checks:
Review:
=> TINY-6117: Update paste plugin to match changes in powerpaste

modules/katamari/src/main/ts/ephox/katamari/api/Strings.ts, modules/katamari/src/test/ts/atomic/api/str/RepeatTest.ts, modules/tinymce/changelog.txt, modules/tinymce/src/plugins/paste/main/ts/api/Settings.ts, modules/tinymce/src/plugins/paste/main/ts/core/Clipboard.ts, modules/tinymce/src/plugins/paste/main/ts/core/Whitespace.ts, modules/tinymce/src/plugins/paste/test/ts/atomic/WhitespaceTest.ts
Related Ticket: TINY-6237
* This fixes tabs incorrectly being replaced with a single space when pasting plain text. It also adds the new `paste_tab_spaces` setting to control how many spaces are used to represent a tab (the default is 4 spaces).
Pre-checks:
Review:
=> TINY-6237: Preserve tab characters better when pasting text by converting them to spaces

readme.md
Related Ticket: fixes #5975.
* Correct the build documentation for the 4.x branch, indicating that `yarn` should be used instead of `npm` to install the build dependencies.
Pre-checks:
Review:
Fixes #5975
=> Fix 4.x build instructions: use yarn

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/dom/DOMUtils.ts, modules/tinymce/src/core/main/ts/api/dom/StyleSheetLoader.ts, modules/tinymce/src/core/main/ts/init/InitContentBody.ts, modules/tinymce/src/core/test/ts/browser/EditorCleanupTest.ts, modules/tinymce/src/core/test/ts/browser/dom/StyleSheetLoaderTest.ts, modules/tinymce/src/themes/mobile/main/ts/Theme.ts, modules/tinymce/src/themes/silver/main/ts/ui/skin/Loader.ts
Related Ticket: TINY-3926
* Cleans up stylesheets loaded via `StyleSheetLoader` or `editor.dom.loadCss()` when all editors using the related stylesheets have been removed. This uses a counter to determine how many times the stylesheet has been loaded and then decrements the counter on unload calls. If the loader believes nothing is using it, then it'll remove the stylesheet from the DOM.
* This also cleans up the `loadCss` API to use the `StyleSheetLoader` to remove duplicate code. It should functionally be identical.
Note: Added Tyler as there's new APIs here, so need to check the API jsdoc strings.
Pre-checks:
Review:
=> TINY-3926: Fixed stylesheets not cleaned up when all editors are destroyed

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/caret/CaretPositionPredicates.ts, modules/tinymce/src/core/main/ts/content/InsertContentImpl.ts, modules/tinymce/src/core/main/ts/content/NbspTrim.ts, modules/tinymce/src/core/main/ts/delete/MergeText.ts, modules/tinymce/src/core/main/ts/keyboard/Nbsps.ts, modules/tinymce/src/core/main/ts/selection/SetSelectionContent.ts, modules/tinymce/src/core/test/ts/browser/caret/CaretPositionPredicatesTest.ts, modules/tinymce/src/core/test/ts/browser/content/InsertContentTest.ts, modules/tinymce/src/core/test/ts/browser/selection/SetSelectionContentTest.ts
Related Ticket: TINY-5966
* This fixes issues with spaces being lost due to the browser collapsing them when inserting content using either the `editor.insertContent()` or `editor.selection.setContent()` APIs. The cause here is that it'd insert the content as is, without "normalising" the spaces so they have interleaving spaces and non-breaking spaces. This will by default try to prevent changing the inserted content and instead change the existing content to use spaces or nbsps as needed.
* Note: This also fixes an issue I found while writing tests when setting the content inside a pre block. This was because the parser used to sanitize the content didn't have the context set.
Pre-checks:
Review:
=> TINY-5966: Fixed an issue where inserting content was causing spaces to disappear

modules/tinymce/src/plugins/table/main/ts/actions/ResizeHandler.ts, modules/tinymce/src/plugins/table/test/ts/browser/ResizeTableTest.ts, modules/tinymce/src/plugins/table/test/ts/module/test/TableTestUtils.ts
Related Ticket: TINY-6242
* Fixed an issue I originally missed that got picked up during QA. The issue was that we were syncing the cell sizes before doing the column resize, which meant the column resize calculations were incorrect.
Pre-checks:
Review:
=> TINY-6242: Fixed an issue when resizing used fixed table sizing mode

modules/tinymce/src/themes/silver/test/ts/module/ToolbarUtils.ts
* This fixes the `InlineToolbarDrawerFloatingPositionTest` intermittently failing, as sometimes it'd failed as the NodeChange/ResizeContent event wasn't firing until after the assertion. I could have added a wait for that, but it seemed this would be more foolproof.
Pre-checks:
Review:
=> Fixed the `InlineToolbarDrawerFloatingPositionTest.ts` intermittently failing

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/EditorView.ts, modules/tinymce/src/core/test/ts/browser/EditorViewIframeTest.ts, modules/tinymce/src/core/test/ts/browser/NotificationManagerTest.ts
Related Ticket: TINY-6354
* Fixes an issue reported by @tiny-james whereby notifications weren't working when the editor was within a ShadowRoot.
Pre-checks:
Review:
=> TINY-6354: Fixed notifications not appearing when the editor is within a ShadowRoot

modules/snooker/src/main/ts/ephox/snooker/api/CopyCols.ts, modules/snooker/src/main/ts/ephox/snooker/api/CopyRows.ts, modules/snooker/src/main/ts/ephox/snooker/api/CopySelected.ts, modules/snooker/src/main/ts/ephox/snooker/api/Main.ts, modules/snooker/src/main/ts/ephox/snooker/api/OtherCells.ts, modules/snooker/src/main/ts/ephox/snooker/api/Sizes.ts, modules/snooker/src/main/ts/ephox/snooker/api/TableGridSize.ts, modules/snooker/src/main/ts/ephox/snooker/api/TableOperations.ts, modules/snooker/src/main/ts/ephox/snooker/api/TablePositions.ts, modules/snooker/src/main/ts/ephox/snooker/api/TableSize.ts, modules/snooker/src/main/ts/ephox/snooker/api/Warehouse.ts, modules/snooker/src/main/ts/ephox/snooker/lookup/Blocks.ts, modules/snooker/src/main/ts/ephox/snooker/model/RunOperation.ts, modules/snooker/src/main/ts/ephox/snooker/model/Transitions.ts, modules/snooker/src/main/ts/ephox/snooker/resize/Adjustments.ts, modules/snooker/src/main/ts/ephox/snooker/resize/Bars.ts, modules/snooker/src/main/ts/ephox/snooker/resize/ColumnSizes.ts, modules/snooker/src/main/ts/ephox/snooker/resize/Recalculations.ts, modules/snooker/src/main/ts/ephox/snooker/selection/CellBounds.ts, modules/snooker/src/main/ts/ephox/snooker/selection/CellFinder.ts, modules/snooker/src/main/ts/ephox/snooker/selection/CellGroup.ts, modules/snooker/src/test/ts/atomic/lookup/BlocksTest.ts, modules/snooker/src/test/ts/atomic/model/WarehouseTest.ts, modules/snooker/src/test/ts/atomic/resize/RecalculationsTest.ts, modules/snooker/src/test/ts/atomic/selection/CellBoundsTest.ts, modules/snooker/src/test/ts/browser/RedrawSectionOrderTest.ts, modules/snooker/src/test/ts/browser/ResizeTest.ts, modules/snooker/src/test/ts/browser/TableSizeTest.ts
Exposed Warehouse in snooker for use in the Table plugin. Internal change.
Pre-checks:
Review:
=> TINY-6050: Exposed warehouse to the world.

modules/tinymce/changelog.txt, modules/tinymce/src/themes/silver/main/ts/ui/menus/contextmenu/Settings.ts, modules/tinymce/src/themes/silver/main/ts/ui/menus/contextmenu/SilverContextMenu.ts, modules/tinymce/src/themes/silver/main/ts/ui/menus/contextmenu/platform/DesktopContextMenu.ts, modules/tinymce/src/themes/silver/main/ts/ui/menus/contextmenu/platform/MobileContextMenu.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/contextmenu/ContextMenuPositionTest.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/contextmenu/SilverContextMenuTest.ts, modules/tinymce/src/themes/silver/test/ts/module/ContextMenuUtils.ts
Related Ticket: TINY-6036
* Adds a new `contextmenu_avoid_overlap` setting that will force the context menu to use "node" anchoring, instead of "point" anchoring for anything that matches the specified selector. This will cause the context menu to appear below the selected node, instead of the exact location of the click (this already happened when activated via the keyboard).
Note: We ideally should add more tests for positioning, however, I was short on time so I've just done the bare minimum for this.
Pre-checks:
Review:
=> TINY-6036: Added the ability to show context menus below specified nodes

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/html/Schema.ts, modules/tinymce/src/core/main/ts/selection/SelectionUtils.ts, modules/tinymce/src/core/test/ts/browser/selection/SelectBeforeBlockTest.ts
Related Ticket: TINY-4058
There were bugs (exceptions being thrown and some content loss) being caused by pressing enter while the cursor was immediately before a `pre` element. I found two ways that the cursor ended up at this invalid location, and prevented them from occurring.
* Pressing enter with the cursor (`|`) like this: `<pre>|Hello</pre>` while `br_in_pre` is set to false in the editor settings
* Calling `editor.selection.setCursorLocation()`
Pre-checks:
Review:
Other issues:
=> TINY-4058: Fix cursors being placed next to pre elements

modules/tinymce/src/core/main/ts/dom/Empty.ts, modules/tinymce/src/core/main/ts/dom/TrimNode.ts, modules/tinymce/src/core/test/ts/browser/dom/DomUtilsTest.ts, modules/tinymce/src/core/test/ts/browser/dom/TrimNodeTest.ts
Related Ticket: TINY-6268
Fixes an issue whereby the `TrimNode` functionality was removing text nodes with content at the start/end of the fragment block.
**Note:** This doesn't solve the actual issue for TINY-6268, only an issue @HAFRMO found when trying to fix the actual issue and this needed to be solved first.
Pre-checks:
Review:
=> TINY-6268: Fixed `TrimNode` removing text nodes in some cases it shouldn't

modules/agar/src/main/ts/ephox/agar/api/FocusTools.ts, modules/agar/src/test/ts/browser/FocusToolsTest.ts, modules/agar/src/test/ts/module/ephox/agar/test/DomContainers.ts, modules/alloy/changelog.md, modules/alloy/src/main/ts/ephox/alloy/aria/AriaFocus.ts, modules/alloy/src/main/ts/ephox/alloy/aria/AriaOwner.ts, modules/tinymce/changelog.txt, modules/tinymce/src/core/demo/ts/demo/ShadowDomDemo.ts, modules/tinymce/src/plugins/searchreplace/test/ts/browser/SearchReplaceDialogTest.ts, modules/tinymce/src/themes/silver/main/ts/backstage/Anchors.ts, modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialogEvents.ts
Related Ticket: TINY-6360
Fixed the search and replace dialog closing and having focus issues when rendered within a ShadowRoot. The primary cause was there were a few places trying to look up the `activeElement` on the root document, not the shadow root.
Note: I also fixed the Agar FocusTools not working when the passed element was in a ShadowRoot.
Pre-checks:
Review:
=> TINY-6360: Fixed focus issues with inline dialogs when the editor is within a ShadowRoot

modules/tinymce/src/core/main/ts/Rtc.ts
* This fixes an issue with the RTC insertContent code always producing a full fragment so there was no way to distinct between `text` and `<p>text</p>` since without a context it would always assume body as the context and wrap the text in a paragraph. Didn't add a changelog entry since this isn't really something that would be used by the public.
Pre-checks:
Review:
=> TINY-6346: added parser context to rtc insertContent

Jenkinsfile, build.properties
* I'm developing tooling that automates some of the release process. Part of the manual process is to update the "primaryBranch" value, used in two places in the Jenkinsfile. To make this easier to automate, I've split it out into a build.properties file.
Pre-checks:
Review:
=> Split primaryBranch out to a properties file.

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/Editor.ts, modules/tinymce/src/core/main/ts/api/SettingsTypes.ts, modules/tinymce/src/core/main/ts/api/ThemeManager.ts, modules/tinymce/src/core/main/ts/api/ui/Ui.ts, modules/tinymce/src/core/main/ts/init/Init.ts, modules/tinymce/src/themes/silver/main/ts/Render.ts, modules/tinymce/src/themes/silver/main/ts/Theme.ts, modules/tinymce/src/themes/silver/main/ts/api/Settings.ts, modules/tinymce/src/themes/silver/main/ts/modes/Inline.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/ToolbarPersistTest.ts, modules/tinymce/tools/docs/tinymce.editor.ui.Ui.js
Added new boolean `toolbar_persist` setting. Used to permanently display/hide the inline editor.
Added new APIs for programmatically controlling the visibility of the inline editor:
```
tinyMCE.activeEditor.theme.inline.ui.show()
tinyMCE.activeEditor.theme.inline.ui.hide()
```
Pre-checks:
Review:
=> TINY-4847: Add new toolbar_persist setting

modules/alloy/changelog.md, modules/alloy/src/main/ts/ephox/alloy/api/ui/FloatingToolbarButton.ts, modules/alloy/src/main/ts/ephox/alloy/api/ui/SplitFloatingToolbar.ts, modules/alloy/src/main/ts/ephox/alloy/api/ui/SplitSlidingToolbar.ts, modules/alloy/src/main/ts/ephox/alloy/ui/types/FloatingToolbarButtonTypes.ts, modules/alloy/src/main/ts/ephox/alloy/ui/types/SplitToolbarBaseTypes.ts, modules/alloy/src/test/ts/browser/ui/button/FloatingToolbarButtonTest.ts, modules/alloy/src/test/ts/browser/ui/toolbar/SplitFloatingToolbarTest.ts, modules/alloy/src/test/ts/browser/ui/toolbar/SplitSlidingToolbarTest.ts, modules/tinymce/changelog.txt, modules/tinymce/src/themes/silver/main/ts/Render.ts, modules/tinymce/src/themes/silver/main/ts/ui/general/OuterContainer.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/ToolbarDrawerToggleTest.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/ToolbarToggleTest.ts
* Expose new command to be able to toggle the toolbar and check toolbar toggle state
```
tinyMCE.activeEditor.execCommand('ToggleToolbarDrawer')
tinyMCE.activeEditor.queryCommandState('ToggleToolbarDrawer')
```
* Works for `sliding` and `floating` toolbar modes. Is a noop for the other toolbar modes.
One thing I noticed during some manual testing was that a `max call stack` error was sometimes thrown when executing the command on init for `inline` mode. I haven't had a chance to investigate this.
Pre-checks:
Review:
Fixes #5616 
Fixes #5041
=> TINY-6032: Add 'ToggleToolbarDrawer' command and query command

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/table/main/ts/ui/MenuItems.ts
Related Ticket: TINY-6374 & TINY-6006
* Adds the cut, copy and paste column menu items to the table column menu by default.
Pre-checks:
Review:
=> TINY-6374: Changed the `table` plugin `Column` menu to include the cut, copy and paste column menu items

modules/tinymce/src/plugins/table/main/ts/core/Util.ts
Remove `data-mce-style` from cols while removing them from the cells.
Pre-checks:
Review:
=> TINY-6050: Now removing data-mce-style on cols and cells.

modules/tinymce/src/core/test/ts/browser/selection/SetSelectionContentTest.ts
Related Ticket: TINY-5966
* Adding a couple of extra test cases for setting content within a pre block. We have some via the `insertContent` tests, but this will ensure the `selection.setContent` works directly.
Pre-checks:
Review:
=> TINY-5966: Added missing test case for inserting content into a pre element

package.json, yarn.lock
* Discovered that CI tests haven't been running on IE for about a week. Turns out the cause was we upgraded to the latest fast-check version which isn't IE compatible, so this reverts back to using 1.x instead of 2.x.
Pre-checks:
Review:
=> Downgraded fast-check as 2.x isn't IE compatible

modules/imagetools/src/main/ts/ephox/imagetools/proxy/Errors.ts, modules/imagetools/src/test/ts/atomic/proxy/ErrorsTest.ts, modules/tinymce/src/core/test/json/routes.json, modules/tinymce/src/plugins/imagetools/test/ts/browser/ImageToolsErrorTest.ts
Related Ticket: TINY-5882
* The image proxy service returns a `not_found` key when an image returns a 404, so this improves the handling as previously it'd instead report `ImageProxy HTTP error: Could not find Image Proxy`.
Pre-checks:
Review:
=> TINY-5882: Improve image proxy error for images that can't be found

modules/acid/package.json, modules/agar/package.json, modules/alloy/changelog.md, modules/alloy/package.json, modules/boss/package.json, modules/boulder/package.json, modules/bridge/package.json, modules/darwin/package.json, modules/dragster/package.json, modules/imagetools/package.json, modules/jax/package.json, modules/katamari-assertions/package.json, modules/katamari/package.json, modules/mcagar/package.json, modules/oxide-icons-default/package.json, modules/oxide/package.json, modules/phoenix/package.json, modules/polaris/package.json, modules/porkbun/package.json, modules/robin/package.json, modules/sand/package.json, modules/snooker/package.json, modules/sugar/package.json, modules/tinymce/changelog.txt, versions.txt
Related Ticket: TINY-6428
* Bumped the package versions and adds the release date to the relevant changelogs. Here's the version bumps:
```
Changes:
- @ephox/acid: 1.0.81 => 2.0.0
- @ephox/agar: 4.17.2 => 5.0.0
- @ephox/alloy: 7.0.7 => 8.0.0
- @ephox/boss: 3.1.9 => 4.0.0
- @ephox/boulder: 4.0.8 => 5.0.0
- @ephox/bridge: 1.2.4 => 2.0.0
- @ephox/darwin: 4.0.20 => 5.0.0
- @ephox/dragster: 4.0.52 => 5.0.0
- @ephox/imagetools: 3.3.3 => 4.0.0
- @ephox/jax: 4.1.36 => 5.0.0
- @ephox/katamari-assertions: 1.0.9 => 2.0.0
- @ephox/katamari: 6.1.2 => 7.0.0
- @ephox/mcagar: 4.2.4 => 5.0.0
- @tinymce/oxide-icons-default: 1.4.1 => 1.5.0
- @tinymce/oxide: 1.4.2 => 1.5.0
- @ephox/phoenix: 5.1.10 => 6.0.0
- @ephox/polaris: 3.0.53 => 4.0.0
- @ephox/porkbun: 4.0.38 => 5.0.0
- …
```
=> TINY-6428: TinyMCE 5.5 release

modules/tinymce/changelog.txt, modules/tinymce/package.json, modules/tinymce/src/core/main/ts/keyboard/NavigationUtils.ts, modules/tinymce/src/core/test/ts/browser/keyboard/ArrowKeysCefTest.ts
Related Ticket: TINY-6471
* This fixes a regression introduced in 5.5 due to missing a case where `null` was returned instead of `Optional.none()`. This ideally would be picked up by TS, but we'd need to turn on strict null checks which causes many TS errors.
Pre-checks:
Review:
=> TINY-6471: Fixed an exception incorrectly thrown when pressing the down key near the end of a document

modules/tinymce/src/themes/silver/main/ts/ui/menus/menubar/Integration.ts
Related Ticket: TINY-6474
* Add `export` to the default items for the File menu in the menubar.
Pre-checks:
Review:
=> TINY-6474: Add new default to File menu

modules/tinymce/changelog.txt, modules/tinymce/src/core/test/ts/browser/FontSelectTest.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/complex/FontsizeSelect.ts
Related Ticket: TINY-6291
Font keywords such as `medium` and `small` are valid `font-size`s. These are appearing correctly in the editor content but the font size menus were displaying their values incorrectly. These keyword sizes are now mapped to `pt` values from our default font sizes.
Pre-checks:
Review:
=> TINY-6291: Map font keywords to pt values in font size menus

modules/bridge/src/main/ts/ephox/bridge/components/dialog/BodyComponent.ts, modules/bridge/src/main/ts/ephox/bridge/components/dialog/CustomEditor.ts, modules/mcagar/src/main/ts/ephox/mcagar/alien/EditorTypes.ts, modules/mcagar/src/main/ts/ephox/mcagar/api/ApiChains.ts, modules/mcagar/src/main/ts/ephox/mcagar/api/TinyActions.ts, modules/mcagar/src/main/ts/ephox/mcagar/api/TinyApis.ts, modules/tinymce/src/core/main/ts/api/EditorManager.ts
Related Ticket: TINY-6413
* Fixed the McAgar "Fake Editor" types I missed last time and fixed other issues found when trying to upgrade other plugins.
Pre-checks:
Review:
=> TINY-6413: More incorrect type fixes and fixes for McAgar not working in a shadow root

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/fullpage/main/ts/core/FilterContent.ts, modules/tinymce/src/plugins/fullpage/test/ts/browser/FullPagePluginTest.ts
Related Ticket: TINY-6541
The result from `editor.getContent({ format: 'text' })` was being incorrectly modified by the fullpage plugin.
Pre-checks:
Review:
Fixes #4556
=> TINY-6541: Ensure fullpage plugin does not modify text content

modules/acid/tsconfig.json, modules/agar/src/main/ts/ephox/agar/api/DragnDrop.ts, modules/agar/src/main/ts/ephox/agar/file/PatchInputFiles.ts, modules/agar/tsconfig.json, modules/alloy/src/main/ts/ephox/alloy/parts/PartType.ts, modules/alloy/tsconfig.json, modules/boulder/package.json, modules/boulder/tsconfig.json, modules/bridge/tsconfig.json, modules/darwin/tsconfig.json, modules/dragster/tsconfig.json, modules/imagetools/tsconfig.json, modules/jax/tsconfig.json, modules/katamari-assertions/tsconfig.json, modules/katamari/tsconfig.json, modules/mcagar/tsconfig.json, modules/phoenix/package.json, modules/phoenix/tsconfig.json, modules/porkbun/tsconfig.json, modules/robin/package.json, modules/sand/tsconfig.json, modules/snooker/tsconfig.json, modules/sugar/src/main/ts/ephox/sugar/api/dom/Truncate.ts, modules/sugar/src/main/ts/ephox/sugar/api/selection/WindowSelection.ts, tsconfig.json
Was attempting to upgrade `ts-loader` in bedrock so we could have it actually do the compilation and found a number of incorrect configs (it's less lenient than `tsc` it seems). Also found a few places where alias imports were being used where they shouldn't be (we maybe should look at creating a linter rule for that if possible).
Pre-checks:
Review:
=> Fixed a number of incorrect config or import issues

modules/tinymce/src/core/main/ts/api/Editor.ts, modules/tinymce/src/core/main/ts/api/dom/StyleSheetLoader.ts
Related Ticket: DOC-636
* Fixing 5.5 version release notes (API Docs)
Pre-checks:
Review:
=> DOC-636: Version required note on 5.5 API docs

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/Rtc.ts, modules/tinymce/src/core/main/ts/api/Editor.ts, modules/tinymce/src/core/main/ts/api/Formatter.ts, modules/tinymce/src/core/main/ts/api/Settings.ts, modules/tinymce/src/core/main/ts/fmt/FormatChanged.ts, modules/tinymce/src/core/main/ts/fmt/MatchFormat.ts, modules/tinymce/src/core/main/ts/view/VisualAids.ts, modules/tinymce/src/core/main/ts/view/VisualAidsImpl.ts, modules/tinymce/src/core/test/ts/browser/FormatterClosestTest.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/complex/FormatSelect.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/complex/StyleSelect.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/complex/utils/FormatDetection.ts
* Adds a new public closest api to formatter that isn't dom specific and redirects that to rtc.
* Redirects formatter.match to rtc.
* Redirects formatter.formatChanged to rtc.
* Contains rtc ignore for addVisual since it updates the dom view did some minor cleanup on that as well.
Pre-checks:
Review:
=> TINY-6479: Bold/Italic buttons not enabled when toggling caret format in rtc mode

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/selection/GetSelectionContentImpl.ts, modules/tinymce/src/core/test/ts/browser/selection/GetSelectionContentTest.ts
We no longer discard spaces that exists in pre-blocks when getting the content through get selection content.
Pre-checks:
Review:
=> TINY-6448: We now handle Pre-blocks as we should.

modules/oxide/src/less/skins/ui/dark/skin.shadowdom.less, modules/oxide/src/less/skins/ui/default/skin.shadowdom.less, modules/oxide/src/less/theme/components/dialog/blocker.less, modules/oxide/src/less/theme/components/dialog/dialog.less, modules/oxide/src/less/theme/shadowdom.less, modules/oxide/src/less/theme/theme.less, modules/tinymce/changelog.txt, modules/tinymce/src/core/demo/ts/demo/ShadowDomDemo.ts, modules/tinymce/src/core/test/ts/browser/init/ShadowDomEditorTest.ts, modules/tinymce/src/themes/silver/main/ts/ui/skin/Loader.ts
Related Ticket: TINY-6363
* This adds a new `skin.shadowdom.min.css` file to the bundle that has the specific styles that needs to be added to the root document when the editor is rendered within a shadow root.
Pre-checks:
Review:
=> TINY-6363: Fixed the root document able to be scrolled when a dialog is open and rendered inside a shadow root

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/fmt/ExpandRange.ts, modules/tinymce/src/core/main/ts/fmt/FormatUtils.ts, modules/tinymce/src/core/main/ts/fmt/RemoveFormat.ts, modules/tinymce/src/core/test/ts/browser/FormatterRemoveTest.ts, modules/tinymce/src/core/test/ts/browser/fmt/ExpandRangeTest.ts
Related Ticket: TINY-6268 & TINY-6444
This finishes up the work @HAFRMO started in #6022. It was on the right track, however, it needed to handle a couple more edge cases which is largely what I've added (eg multiple spaces, or a space at the start/end of a block will be collapsed). I will say I find the name `findParentContainer` a little weird when it also includes a check to see if there is a valid sibling before moving to the parent, but I didn't want to refactor too much, so I added to the existing comment to clarify that.
P.S. Sorry @HAFRMO it took me so long to get around to looking at this.
Pre-checks:
Review:
=> TINY-6268: Fixed incorrectly removing formatting on adjacent spaces when removing formatting on a ranged selection

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/dom/EventUtils.ts, modules/tinymce/src/core/main/ts/api/dom/ScriptLoader.ts, modules/tinymce/src/core/test/ts/browser/dom/ScriptLoaderTest.ts, modules/tinymce/src/plugins/autosave/main/ts/core/Storage.ts, modules/tinymce/src/themes/silver/main/ts/modes/Iframe.ts
Related Ticket: TINY-6570
* Fixed some memory leaks specific to IE that was found when doing some investigation into informant test failures.
* Fixed some other more generic leaks that applied to all browsers.
P.S. Big thanks to @ephox-mogran for the help in diagnosing the Iframe leak.
Pre-checks:
Review:
=> TINY-6570: Fixed some memory leaks that prevented editor instances being garbage collected

modules/tinymce/src/themes/silver/main/ts/Autocompleter.ts
* We need to block the autocompleter from running since it's mutating the view directly
Pre-checks:
Review:
=> TINY-6563: prevent autocompleter from running in rtc mode

modules/tinymce/src/core/main/ts/EditorSettings.ts, modules/tinymce/src/core/main/ts/init/Render.ts
* Since the RTC plugin doesn't support IE 11 the script has modern JS concepts that IE 11 won't even parse. So we need to detect if the RTC plugin is being loaded on IE 11 before it's being loaded to present a better error message than a JS parse error.
Pre-checks:
Review:
=> TINY-6530: disabled loading of the rtc plugin on IE 11 since that plugin.js file will not even be parsable

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/fmt/StyleFormat.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/complex/StyleFormat.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/complex/utils/FormatRegister.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/bespoke/NamedStyleSelectFormatsTest.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/bespoke/StyleSelectFormatNamesTest.ts
* This enables you to specify what the name of the format should be when using style_select it's very important for rtc that these names are the same since and not be based on the title that might change by i18n or similar things.
Pre-checks:
Review:
=> TINY-4239: added optional name field to style_formats setting enabling a custom name to be registered

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/paste/main/ts/api/Settings.ts, modules/tinymce/src/plugins/paste/main/ts/core/Clipboard.ts, modules/tinymce/src/plugins/paste/main/ts/core/SmartPaste.ts, modules/tinymce/src/plugins/paste/test/ts/browser/SmartPasteTest.ts
Related Ticket: TINY-6306
- new `image_file_types` setting, registered in `paste`
- default image formats: `'jpeg, jpg, jpe, jfi, jfif, png, gif, bmp, webp'`
- smart paste will now insert these file formats into `img` tags on paste
Pre-checks:
Review:
=> TINY-6306: Support common web formats with image smart paste

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/EditorObservable.ts, modules/tinymce/src/core/main/ts/mode/Readonly.ts, modules/tinymce/src/core/test/ts/browser/ReadOnlyModeTest.ts
Related Ticket: TINY-6248
Links clicked in `readonly` mode will now open in a new tab (or scroll to bookmark if appropriate).
Pre-checks:
Review:
=> TINY-6248: Readonly links should open in a new window or tab

Jenkinsfile, modules/agar/src/main/ts/ephox/agar/api/Monitor.ts, modules/alloy/src/main/ts/ephox/alloy/alien/Descend.ts, modules/alloy/src/main/ts/ephox/alloy/api/behaviour/Keying.ts, modules/alloy/src/main/ts/ephox/alloy/debugging/FunctionAnnotator.ts, modules/alloy/src/main/ts/ephox/alloy/keying/KeyingModeTypes.ts, modules/alloy/src/main/ts/ephox/alloy/positioning/mode/SelectionAnchor.ts, modules/alloy/src/test/ts/atomic/api/DomDefinitionTest.ts, modules/boulder/src/main/ts/ephox/boulder/alien/SimpleResult.ts, modules/boulder/src/main/ts/ephox/boulder/api/Objects.ts, modules/boulder/src/main/ts/ephox/boulder/core/ObjWriter.ts, modules/imagetools/src/main/ts/ephox/imagetools/util/Promise.ts, modules/jax/src/test/ts/atomic/core/UrlBuilderTest.ts, modules/katamari-assertions/src/test/ts/atomic/api/KAssertTest.ts, modules/katamari/src/main/ts/ephox/katamari/api/FutureResult.ts, modules/katamari/src/main/ts/ephox/katamari/api/Singleton.ts, modules/katamari/src/test/ts/module/ephox/katamari/test/arb/ArbDataTypes.ts, modules/robin/src/test/ts/module/ephox/robin/test/ZoneObjects.ts, modules/sugar/src/test/ts/browser/ElementTest.ts, modules/tinymce/src/core/main/ts/fmt/FormatChanged.ts, modules/tinymce/src/core/main/ts/util/ArrUtils.ts, modules/tinymce/src/plugins/charmap/test/ts/browser/CharmapSearchTest.ts, modules/tinymce/src/themes/silver/main/ts/ui/alien/RepresentingConfigs.ts, modules/tinymce/src/themes/silver/main/ts/ui/menus/item/build/CommonMenuItem.ts, modules/tinymce/src/themes/silver/main/ts/ui/menus/item/structure/ItemStructure.ts, modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialogEvents.ts, modules/tinymce/src/themes/silver/main/ts/ui/window/SilverUrlDialogInstanceApi.ts, package.json, yarn.lock
Related Ticket: TINY-6598
* The most important part of this is the upgrade to bedrock 9.7.1 to make sure we can continue to test Edge.
* Other upgrades that's good to note is the upgrade to TS 4.0.x and the new eslint plugin (which is what identified a number of issues).
* Note: I'm specifically not touching the Fun.curry types, but we should do that at some stage.
Pre-checks:
Review:
=> TINY-6598: Upgrade dependencies

modules/tinymce/src/plugins/charmap/test/ts/browser/CharmapSearchTest.ts, yarn.lock
Related Ticket: TINY-6598
* Backports the bedrock 9.7.1 upgrade to fix Chromium Edge test failures
Pre-checks:
Review:
=> TINY-6598: Upgraded to the latest bedrock version to fix Chromium Edge failures

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/dom/DOMUtils.ts, modules/tinymce/src/core/test/ts/browser/dom/DomUtilsTest.ts, modules/tinymce/src/core/test/ts/browser/focus/FocusControllerTest.ts
Related Ticket: TINY-6540
Don't call `.parentNode` when `node` is a `DocumentFragment`
Pre-checks:
Review:
GitHub issues (if applicable): #6093, #2697, #6133
=> TINY-6540: Ensure DOMUtils.getParents does not call parentNode on DocumentFragments

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/SelectionOverrides.ts, modules/tinymce/src/core/test/ts/browser/SelectionOverridesTest.ts
Related Ticket: TINY-6555
* This fixes an issue introduced in TinyMCE 5.5 whereby if the root element was a cef element, then it'd incorrectly show the fake offscreen selection element.
Pre-checks:
Review:
=> TINY-6555: Fixed an offscreen selection element incorrectly created for the editor root

modules/tinymce/changelog.txt, modules/tinymce/src/themes/silver/main/ts/Render.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/sizing/ResizeTest.ts
Attempting to resize the sink to match changes to the window, to make sure menus stops contorting when fullscreening or resizing things.
Pre-checks:
Review:
=> TINY-3321: Resize the sink when possible.

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/paste/main/ts/core/CutCopy.ts, modules/tinymce/src/plugins/paste/test/ts/webdriver/CutTest.ts
Related Ticket: TINY-6615
* Fixed an issue with the cut menu item not working in the latest versions of Firefox. Note: I've updated the test to match what's used in PowerPaste, as that was causing failures.
Pre-checks:
Review:
=> TINY-6615: Fixed the `Cut` menu item not working in the latest version of Firefox

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/file/BlobCache.ts, modules/tinymce/src/plugins/image/test/ts/browser/UploadTabTest.ts, modules/tinymce/src/themes/silver/demo/ts/components/DemoHelpers.ts, modules/tinymce/src/themes/silver/main/ts/backstage/Backstage.ts, modules/tinymce/src/themes/silver/main/ts/ui/dialog/Dropzone.ts, modules/tinymce/src/themes/silver/test/ts/module/TestProviders.ts, modules/tinymce/src/themes/silver/test/ts/phantom/components/alertbanner/AlertBannerTest.ts, modules/tinymce/src/themes/silver/test/ts/phantom/components/checkbox/BasicCheckboxTest.ts, modules/tinymce/src/themes/silver/test/ts/phantom/components/dropzone/DropzoneTest.ts, modules/tinymce/src/themes/silver/test/ts/phantom/window/SilverDialogEventTest.ts
Related Ticket: TINY-6224
NOTE: Future UX improvements detailed in TINY-6620_
Use `backstage` to provide `editor.getParam` as `editor.getSetting` through to `Dropzone.ts`.
Process files based on the setting, with the default setting the same as in `paste`.
**Pre-checks:**
**Review:**
**GitHub issues (if applicable):**
Fixes #6034
=> TINY-6224: Use `image_file_types` setting to allow additional image file types in image file uploads

modules/snooker/src/main/ts/ephox/snooker/api/TableLookup.ts, modules/snooker/src/test/ts/browser/TableLookupTest.ts, modules/tinymce/changelog.txt
Related Ticket: TINY-6623
* This fixes the `col` and `colgroup` table lookups, that was causing the wrong columns to be resized, etc...
Pre-checks:
Review:
=> TINY-6623: Fixed resizing not working correctly with colgroups and nested tables

modules/oxide/src/less/theme/components/fullscreen/fullscreen.less, modules/tinymce/changelog.txt, modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts, modules/tinymce/src/plugins/fullscreen/test/ts/browser/FullScreenPluginTest.ts
Related Ticket: TINY-6280
* Refactor `fullscreen.less` so that the selectors are compatible with both Body and ShadowDom
* Make sure `tox-fullscreen` is added to the shadow host and that it has the correct z-index
* Update test to run in Body and ShadowDom
Pre-checks:
Review:
=> TINY-6280: Fix fullscreen plugin not working with multiple editors and shadowdom

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/table/main/ts/actions/ResizeHandler.ts, modules/tinymce/src/plugins/table/test/ts/browser/ResizeTableTest.ts
Related Ticket: TINY-6601
* When using the resize bars on a `responsive` table, because they work using Snooker's logic, the table needs to be converted to a `relative` table when the resize starts. Without this, it calculates all the table widths as 0 and as such doesn't make any changes during the initial resize.
Pre-checks:
Review:
=> TINY-6601: Fixed resizing a `responsive` table not working when using the column resize handles

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/html/Schema.ts, modules/tinymce/src/core/test/ts/browser/html/SchemaTest.ts, modules/tinymce/src/plugins/table/test/ts/browser/EmptyRowTableTest.ts
**Related Ticket:** TINY-4679
Empty `tr` elements are considered valid and should not be removed.
Explicit test added with use case (`rowspan="2"`) to prevent regression.
**Pre-checks:**
**Review:**
=>  TINY-4679: Empty tr elements should not be removed by the Schema

modules/oxide/src/less/theme/content/selection/selection.less, modules/tinymce/changelog.txt
Related Ticket: TINY-6495
* This fixes a regression introduced in TinyMCE 5.5 that made the selection be unable to be seen when a table had a background.
This is what it looks like after this change:
Pre-checks:
Review:
=> TINY-6495: Fixed a regression that caused the selection to be hidden in tables with backgrounds

modules/agar/src/main/ts/ephox/agar/api/Main.ts, versions.txt
Related Ticket: TINY-6659
* Fixed the clipboard module not exposed in agar, which prevented us from using it elsewhere.
Pre-checks:
Review:
=> TINY-6659: Fixed Clipboard not exposed in agar

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/table/main/ts/actions/InsertTable.ts, modules/tinymce/src/plugins/table/main/ts/api/Api.ts, modules/tinymce/src/plugins/table/main/ts/ui/MenuItems.ts, modules/tinymce/src/plugins/table/test/ts/browser/command/InsertTableCommandTest.ts
Related Ticket: TINY-6656
This fixes calling the `mceInsertTable` command incorrectly creating 2 undo levels. This was caused by calling `editor.insertContent()` which creates a undo level and then further manipulating the dom after to ensure the table sizing is correct. This wasn't an issue with the menu item, as it was wrapped in an undo transaction (I've also made the menu item use the command to keep things consistent). This also fixes another issue I noticed where the plugin API wasn't creating an undo level.
Pre-checks:
Review:
=> TINY-6656: Fixed inserting a table via the mceInsertTable command incorrectly creating 2 undo levels

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/SettingsTypes.ts, modules/tinymce/src/core/main/ts/api/html/Writer.ts
Related Ticket: TINY-6648
* The entity_encoding setting type was incorrect, and overly restrictive. While it would be nice to fix this properly with TypeScript's new template types, for now I've just widened it to accept any string.
Pre-checks:
Review:
=> TINY-6648: Expand types for entity encoding

modules/snooker/src/main/ts/ephox/snooker/api/Sizes.ts, modules/snooker/src/main/ts/ephox/snooker/api/TableSize.ts, modules/snooker/src/main/ts/ephox/snooker/resize/Adjustments.ts, modules/snooker/src/main/ts/ephox/snooker/resize/ColumnSizes.ts, modules/snooker/src/test/ts/browser/resize/ColumnSizesTest.ts, modules/tinymce/changelog.txt, modules/tinymce/src/plugins/table/test/ts/browser/ResizeTableTest.ts
Related Ticket: TINY-6646
This fixes the widths being calculated incorrectly for `col` elements without raw widths. The problem was most browsers will return 0px for the width, as such if there's no raw width we need to fallback to getting the width from the table cells. It also fixes an issue I found with the fallback logic, as it would never calculate the last column width correctly.
Pre-checks:
Review:
=> TINY-6646: Fixed incorrectly calculating col widths when resizing tables

modules/tinymce/src/core/main/ts/api/Tinymce.ts, modules/tinymce/src/core/main/ts/api/dom/DOMUtils.ts, modules/tinymce/src/core/main/ts/api/file/BlobCache.ts
Related Ticket: TINY-6413
This just fixes a few issues I found from typing the Premium plugins that I've been meaning to fix for a while.
Note: I'm not entirely happy about how we're doing the namespace declarations in `Tinymce.ts`, however we're a bit stuck here because of the fact those implementations really should be using classes to get the proper types. Atm it's using declaration merging to merge the namespace and function, however that has issues with the constructor function since it's supposed to be called with `new`.
Pre-checks:
Review:
=> TINY-6413: Fixed more incorrect public types

modules/tinymce/src/core/main/ts/api/file/BlobCache.ts, modules/tinymce/src/plugins/paste/main/ts/api/Settings.ts, modules/tinymce/src/plugins/paste/main/ts/core/Clipboard.ts, modules/tinymce/src/plugins/paste/main/ts/core/SmartPaste.ts, modules/tinymce/src/plugins/paste/main/ts/core/Utils.ts, modules/tinymce/src/plugins/paste/test/ts/browser/ImagePasteTest.ts, modules/tinymce/src/themes/silver/main/ts/ui/dialog/Dropzone.ts
Related Ticket: TINY-6306
* Fixes the Clipboard image file type logic to respect the new `image_file_types` setting.
* Fixes missing `avif` image file type mapping in `BlobCache`.
* Adds the missing `jif` file extension.
Pre-checks:
Review:
=> TINY-6668: Fixed image_file_types not respected for pasting images

modules/tinymce/src/plugins/table/main/ts/actions/ResizeHandler.ts, modules/tinymce/src/plugins/table/main/ts/api/Commands.ts, modules/tinymce/src/plugins/table/test/ts/browser/ResizeTableTest.ts, modules/tinymce/src/plugins/table/test/ts/module/test/TableSizingModeCommandUtil.ts
TINY-6629
Add missing events for changing resize mode and resizing table.
Pre-checks:
Review:
=> TINY-6629: Fix missing events for table sizing mode change and resize

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/image/test/ts/browser/UploadTabTest.ts, modules/tinymce/src/plugins/paste/main/ts/api/Settings.ts, modules/tinymce/src/plugins/paste/test/ts/browser/ImagePasteTest.ts, modules/tinymce/src/plugins/paste/test/ts/browser/SmartPasteTest.ts, modules/tinymce/src/themes/silver/main/ts/ui/dialog/Dropzone.ts
Related Ticket: TINY-6672
* Renamed `image_file_types` to `images_file_types` for consistency
Pre-checks:
Review:
=> TINY-6672: Renamed image_file_types to images_file_types

modules/acid/package.json, modules/agar/package.json, modules/alloy/changelog.md, modules/alloy/package.json, modules/boss/package.json, modules/boulder/package.json, modules/bridge/package.json, modules/darwin/package.json, modules/dragster/package.json, modules/imagetools/package.json, modules/jax/package.json, modules/katamari-assertions/package.json, modules/katamari/package.json, modules/mcagar/package.json, modules/oxide/package.json, modules/phoenix/package.json, modules/polaris/package.json, modules/porkbun/package.json, modules/robin/package.json, modules/sand/package.json, modules/snooker/package.json, modules/sugar/package.json, modules/tinymce/changelog.txt, versions.txt
Related Ticket: TINY-6658
Description of changes:
- Bumped TinyMCE and Alloy changelog dates
- Bumped versions as per versions.txt, see:
```
Changes:
- @ephox/acid: 2.0.1 => 2.0.2
- @ephox/agar: 5.0.1 => 5.1.0
- @ephox/alloy: 8.0.1 => 8.1.0
- @ephox/boss: 4.0.1 => 4.0.2
- @ephox/boulder: 5.0.1 => 5.0.2
- @ephox/bridge: 2.0.1 => 2.1.0
- @ephox/darwin: 5.0.2 => 5.0.3
- @ephox/dragster: 5.0.1 => 5.0.2
- @ephox/imagetools: 4.0.1 => 4.0.2
- @ephox/jax: 5.0.1 => 5.0.2
- @ephox/katamari-assertions: 2.0.1 => 2.0.2
- @ephox/katamari: 7.0.1 => 7.1.0
- @ephox/mcagar: 5.0.1 => 5.1.0
- @tinymce/oxide: 1.5.1 => 1.6.0
- @ephox/phoenix: 6.0.1 => 6.0.2
- @ephox/polaris: 4.0.1 => 4.0.2
- @ephox/porkbun: 5.0.1 => 5.0.2
- @ephox/robin: 8.0.2 => 8.0.3
- @ephox/sand: 4.0.1 => 4.0.2
- @ephox/snooker: 7.0.2 => …
```
=> TINY-6658: Bump versions and added changelog dates for 5.6 release

modules/snooker/src/main/ts/ephox/snooker/api/TableLookup.ts, modules/snooker/src/test/ts/browser/TableLookupTest.ts, modules/tinymce/changelog.txt, modules/tinymce/src/plugins/table/test/ts/browser/ClipboardTest.ts
Related Ticket: TINY-6684
Fixed a regression that caused invalid HTML to be created when copying and pasting within a table that used colgroups. This was because the `col` lookup was failing when a detached colgroup was passed.
Note: Ideally we need to look at supporting copying/pasting between tables that either use colgroups or don't, however that's a much larger scope and not something that worked in TinyMCE 5.5.
Pre-checks:
Review:
=> TINY-6684: Fixed copying and pasting table columns with a colgroup resulted in invalid HTML

modules/tinymce/changelog.txt, modules/tinymce/src/themes/silver/main/ts/Render.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/sizing/ResizeNotInRootTest.ts
Regression where the sink would resize in poor ways when not wanted. Added check to avoid this case.
Pre-checks:
Review:
=> TINY-6683: Sink now only resizes if contained in the body or shadowroot.

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/table/main/ts/actions/TableActions.ts, modules/tinymce/src/plugins/table/main/ts/core/TableSections.ts, modules/tinymce/src/plugins/table/main/ts/ui/CellDialog.ts, modules/tinymce/src/plugins/table/main/ts/ui/Helpers.ts, modules/tinymce/src/plugins/table/test/ts/browser/TableSectionApiTest.ts, modules/tinymce/src/plugins/table/test/ts/browser/ui/TableCellDialogTest.ts
TINY-6692
`mceTableCellType` and `mceTableRowType` commands now fire `newCell` event whenever cells are modified
Pre-checks:
Review:
=> TINY-6692: Ensure mceTableCellType and mceTableRowType fire newCell events

modules/oxide/src/less/theme/globals/global-variables.less, modules/tinymce/changelog.txt
Related Ticket: TINY-6686
This is a partial implementation of the ticket to help with the RTC demo. The rest of the implementation (dismissing active popups) can be done later to resolve the potential UI weirdness that edge cases will now produce.
Pre-checks:
Review:
=> TINY-6686: Lower z-index of throbber

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/lists/main/ts/actions/ToggleList.ts, modules/tinymce/src/plugins/lists/test/ts/browser/ApplyTest.ts
TINY-3755
Allows toggling list type on selections including mixes of text blocks and existing lists
**Pre-checks:**
**Review:**
=> TINY-3755: Apply list style to text blocks inside a selection containing at least one other list

modules/snooker/src/main/ts/ephox/snooker/api/Generators.ts, modules/snooker/src/main/ts/ephox/snooker/api/TableOperations.ts, modules/snooker/src/test/ts/browser/MergeOperationsTest.ts, modules/snooker/src/test/ts/browser/UnmergeOperationsTest.ts, modules/snooker/src/test/ts/module/ephox/snooker/test/Assertions.ts, modules/tinymce/changelog.txt
Previously scope attributes would not be correctly changed ( colgroup to col, for example ) when merging or unmerging.
Pre-checks:
Review:
=> TINY-6484: We now switch scope to/from group as expected

modules/tinymce/src/core/main/ts/Rtc.ts
Related Ticket: #TINY-6727
* Filters are not executed on invalid fragments by default if a context is provided to the parser. So this makes sure that the fragment produced for RTC has filters executed as well processing image blobs etc.
Pre-checks:
Review:
=> TINY-6727: fixed issue with content filters not being executed on invalid fragments

modules/tinymce/src/core/main/ts/Rtc.ts
Related Ticket: TINY-6745
The RTC HTML serializer wasn't using the relevant writer editor settings, which meant indent, entities, etc... weren't working when serialising the content.
Note: I tested this works locally by pulling in the RTC plugin from cloud as an external plugin.
Pre-checks:
Review:
=> TINY-6745: Fixed an issue where the writer settings weren't being used for RTC

modules/tinymce/src/core/main/ts/api/dom/ControlSelection.ts, modules/tinymce/src/core/test/ts/browser/dom/ControlSelectionTest.ts
Related Ticket: TINY-6229
* This fixes video elements unable to be played, as it needs to have `data-mce-selected="2"`, however the current resize logic removes the `data-mce-attribute` even if it's the same element. So this makes it only cleanup the resize handles, if the selected node is a different element.
Pre-checks:
Review:
=> TINY-6229: Fixed unable to play media elements

modules/oxide/src/less/theme/globals/reset.less, modules/tinymce/changelog.txt
Related Ticket: TINY-6735
* Added box-shadow to the reset styles to prevent styles similar to the below to bleed into TinyMCE
```
:focus {
box-shadow: 0 0 1px 2px rgba(0,0,0,.75);
font-weight: bolder;
}
```
Pre-checks:
Review:
=> TINY-6735 Fixed an issue with external styles bleeding into TinyMCE

modules/tinymce/changelog.txt, modules/tinymce/package.json, modules/tinymce/src/themes/silver/main/ts/Render.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/sizing/GridSinkSizingTest.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/sizing/ResizeTest.ts
Related Ticket: TINY-6783
* Fixes a regression when the document body is using flexbox. This just makes it so the fix done for TINY-3321 only works when the body is using `display: grid`
Pre-checks:
Review:
=> TINY-6783: Fixed a regression when the document body used flexbox

modules/tinymce/src/core/main/ts/Rtc.ts, modules/tinymce/src/core/main/ts/init/InitContentBody.ts
* This moves the display of rtc setup errors to tinymce core and it uses a no-op adaptor since it would otherwise continue to throw errors while initializing since on preInit it calls various apis we override.
Pre-checks:
Review:
=> TINY-6769: added error handling for rtc setup

modules/oxide/src/less/theme/content/resize-handles/resize-handle.less, modules/tinymce/src/core/main/ts/api/dom/ControlSelection.ts, modules/tinymce/src/core/test/ts/browser/dom/ControlSelectionTest.ts
Related Ticket: TINY-6229
* An additional fix where audio elements couldn't be played due to `ControlSelection` changing the `data-mce-selected` attribute from `2` to `1` after selecting it.
* Fixes the cursor showing as a text cursor while dragging/resizing.
Pre-checks:
Review:
=> TINY-6229: Fixed an issue where audio elements weren't playable

modules/tinymce/src/core/main/ts/Rtc.ts
* This redirects more of the undo manager to rtc when enabled.
Pre-checks:
Review:
=> TINY-6770: redirect more of the undo manager to rtc

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/DragDropOverrides.ts, modules/tinymce/src/core/main/ts/api/dom/EventUtils.ts, modules/tinymce/src/core/test/ts/browser/dom/EventUtilsTest.ts
Related Ticket: TINY-6834
* Fixed the `EventUtils` fix function not setting the initial state correctly for `isDefaultPrevented` or `isPropagationStopped`.
* Fixed calling `preventDefault()` not updating the `defaultPrevented` state of the cloned event.
Note: This is the root cause of the `Dropped file type not supported` notification showing, since `defaultPrevented` was false since the original event was updated in the same callbacks handler.
Pre-checks:
Review:
=> TINY-6834: Fixed an issue where event states weren't updated correctly

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/dom/Selection.ts, modules/tinymce/src/plugins/lists/main/ts/core/Delete.ts
Related Ticket: TINY-6843
* editor.selection.getRng can no longer return null
* you can no longer pass a node to editor.selection.setCursorLocation without also passing an offset 
Pre-checks:
Review:
=> TINY-6843: Fix some type signatures in editor.selection

modules/mcagar/src/main/ts/ephox/mcagar/api/Editor.ts, modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/init/InitContentBody.ts, modules/tinymce/src/core/test/ts/browser/EditorRemoveTest.ts
This issue was originally discovered in the react integration. It probably doesn't come up in "normal" use of TinyMCE otherwise.
https://github.com/tinymce/tinymce-react/issues/191
It is probably possible to work around the issue in the react integration but I felt it would be better to fix it at the source in this case.
Currently TinyMCE will attempt to continue loading after the stylesheet has loaded even when the editor has been destroyed. This then fails when TinyMCE attempts to get the selection object on the editor which has been set to null by the destroy function.
The goal of this PR is to prevent TinyMCE from continuing to load in those circumstances.
Pre-checks:
Review:
=> INT-2282: Avoid continuing to initialize destroyed editor

modules/tinymce/src/core/main/ts/api/dom/DOMUtils.ts
Related Ticket: TINY-6283
See ticket description and comments
Pre-checks:
Review:
=> TINY-6283: Make DOMUtils Constructor documentation private

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/html/SaxParser.ts, modules/tinymce/src/core/test/ts/browser/html/SaxParserTest.ts
Related Ticket: TINY-6864
* As reported in #6015 the regex being used here wasn't a global or sticky regex, meaning that `endCommentRegexp.lastIndex = startIndex;` wasn't working. We couldn't use the sticky flag, as it's not supported on IE 11. As such this splits the string so the regex only operates from the starting index.
Pre-checks:
Review:
=> TINY-6864: Fixed parsing a malformed comment causing an infinite loop

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/dom/Sizzle.ts
Related Ticket: TINY-6859
* Backports the Sizzle memory leak fixes mentioned in #6390. I do want to look at removing our forked version if possible and use a dependency instead, but I'll look at that separately (likely for 5.8 due to the risks involved).
Pre-checks:
Review:
Fixes #6390
=> TINY-6859: Backported upstream Sizzle memory leak fix

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/html/SaxParser.ts, modules/tinymce/src/core/main/ts/html/Base64Uris.ts, modules/tinymce/src/core/test/ts/atomic/html/Base64UrisTest.ts, modules/tinymce/src/core/test/ts/browser/html/SaxParserTest.ts
Related Ticket: TINY-6828
This fixes a regression introduced in 5.3.0, as we now extract the base64 URLs before parsing as HTML and then restore them later. However, the replacement logic only looked for exact matches in the attribute value which meant if a base64 URL was used in say a style, then it wouldn't get replaced and would end up being corrupt.
Note: I've also made one minor performance improvement, as the base64 replacement logic used to compile the regex each time it was called (ie for every text or comment node and now attribute values as well). It will now instead only be compiled once and then is reused when restoring the base64 data.
Pre-checks:
Review:
=> TINY-6828: Fixed base64 URLs not getting restored in style attributes during parsing

modules/agar/src/main/ts/ephox/agar/api/FocusTools.ts, modules/agar/src/main/ts/ephox/agar/api/UiFinder.ts, modules/tinymce/src/plugins/charmap/main/ts/api/Api.ts, modules/tinymce/src/plugins/charmap/main/ts/api/Events.ts, modules/tinymce/src/plugins/charmap/main/ts/core/Actions.ts, modules/tinymce/src/plugins/charmap/test/ts/atomic/ScanTest.ts, modules/tinymce/src/plugins/charmap/test/ts/browser/CharmapAutocompletionTest.ts, modules/tinymce/src/plugins/charmap/test/ts/browser/CharmapDialogHeightTest.ts, modules/tinymce/src/plugins/charmap/test/ts/browser/CharmapPluginTest.ts, modules/tinymce/src/plugins/charmap/test/ts/browser/CharmapSearchTest.ts, modules/tinymce/src/plugins/charmap/test/ts/browser/CharmapUserDefinedTest.ts, modules/tinymce/src/plugins/charmap/test/ts/browser/InsertQuotationMarkTest.ts, modules/tinymce/src/plugins/charmap/test/ts/module/Helpers.ts
* Converts the `charmap` plugin to use BDD style tests
* Adds some additional agar helpers needed to convert the `charmap` tests.
* Sprinkled some editor types (needed to find the `InsertCustomChar` event type)
Pre-checks:
Review:
=> TINY-6870: Switch charmap plugin to use BDD style tests

modules/mcagar/src/main/ts/ephox/mcagar/api/TinyUiActions.ts, modules/tinymce/src/plugins/code/test/ts/browser/CodeSanityTest.ts, modules/tinymce/src/plugins/code/test/ts/browser/CodeTextareaTest.ts
* Converts the `code` plugin to use BDD style tests
* Added new `closeDialog` helper to `TinyUiActions`
Pre-checks:
Review:
=> TINY-6870: Switch code plugin to use BDD style tests

modules/tinymce/src/plugins/bbcode/test/ts/browser/BbcodeSanityTest.ts
* Converts the `bbcode` plugin to use BDD style tests
Pre-checks:
Review:
=> TINY-6870: Switch bbcode plugin to use BDD style tests

modules/agar/src/main/ts/ephox/agar/api/FocusTools.ts, modules/tinymce/src/plugins/fullpage/test/ts/atomic/ProtectTest.ts, modules/tinymce/src/plugins/fullpage/test/ts/browser/FullPageDialogPluginTest.ts, modules/tinymce/src/plugins/fullpage/test/ts/browser/FullPagePluginTest.ts
* Converts the `fullpage` plugin to use BDD style tests
* Adds some additional agar helpers needed to convert the `fullpage` tests (this is a duplicate of the charmap changes).
* Changes the `FocusTools.isOn` and `FocusTools.isOnSelector` to die if not found, as all the places it was used we needed to do that anyways (it's generally used as an assertion).
Pre-checks:
Review:
=> TINY-6870: Switch fullpage plugin to use BDD style tests

modules/tinymce/src/plugins/anchor/test/ts/browser/AnchorAlertTest.ts, modules/tinymce/src/plugins/anchor/test/ts/browser/AnchorAllowHtmlTest.ts, modules/tinymce/src/plugins/anchor/test/ts/browser/AnchorEditTest.ts, modules/tinymce/src/plugins/anchor/test/ts/browser/AnchorFormatsTest.ts, modules/tinymce/src/plugins/anchor/test/ts/browser/AnchorInlineTest.ts, modules/tinymce/src/plugins/anchor/test/ts/browser/AnchorSanityTest.ts, modules/tinymce/src/plugins/anchor/test/ts/module/Helpers.ts
* Converts the `anchor` plugin to use BDD style tests
Pre-checks:
Review:
=> TINY-6870: Switch anchor plugin to use BDD style tests

modules/mcagar/src/main/ts/ephox/mcagar/api/TinyHooks.ts
Related Ticket: TINY-6732
* Was doing some profiling and noticed that editor instances were being retained due to the new `TinyHooks` implementation. So this makes sure we clean up the references when the test is done.
Pre-checks:
Review:
=> TINY-6732: Fixed a memory leak in the new TinyHooks module

package.json, yarn.lock
Related Ticket: TINY-6732
* Downgrades the `eslint-plugin-mocha` package to 7.x due to extremely severe performance issues in 8.x.
Before:
```
tinymce: Rule                                   | Time (ms) | Relative
tinymce: :--------------------------------------|----------:|--------:
tinymce: mocha/no-identical-title               | 27366.935 |    36.1%
```
After:
```
tinymce: Rule                                   | Time (ms) | Relative
tinymce: :--------------------------------------|----------:|--------:
tinymce: mocha/no-identical-title               |   740.547 |     2.6%
```
Pre-checks:
Review:
=> TINY-6732: Downgrade mocha eslint plugin to 7.x due to performance issues in 8.x

modules/tinymce/src/plugins/autosave/test/ts/browser/ShouldRestoreWhenEmptyTest.ts
* Was looking at this while talking to someone and noticed I got a couple things wrong in the conversion
Pre-checks:
Review:
=> TINY-6870: Fixed incorrect test function name from conversion and missed assertion

modules/tinymce/src/plugins/advlist/test/ts/browser/AdvlistPluginTest.ts, modules/tinymce/src/plugins/advlist/test/ts/browser/ChangeListStyleTest.ts, modules/tinymce/src/plugins/advlist/test/ts/browser/SplitButtonTest.ts, modules/tinymce/src/plugins/advlist/test/ts/browser/ToolbarButtonStructureTest.ts
* Converts the `advlist` plugin to use BDD style tests
Pre-checks:
Review:
=> TINY-6870: Switch advlist plugin to use BDD style tests

modules/tinymce/src/plugins/autolink/test/ts/browser/AutoLinkPluginTest.ts, modules/tinymce/src/plugins/autolink/test/ts/browser/ConsecutiveLinkTest.ts, modules/tinymce/src/plugins/autolink/test/ts/browser/EnterKeyTest.ts, modules/tinymce/src/plugins/autolink/test/ts/module/test/KeyUtils.ts
* Converts the `autolink` plugin to use BDD style tests
Pre-checks:
Review:
=> TINY-6870: Switch autolink plugin to use BDD style tests

modules/tinymce/src/plugins/autoresize/test/ts/browser/AutoresizePluginTest.ts
* Converts the `autoresize` plugin to use BDD style tests
Pre-checks:
Review:
=> TINY-6870: Switch autoresize plugin to use BDD style tests

modules/tinymce/src/plugins/codesample/test/ts/browser/ChangeCodeSampleTest.ts, modules/tinymce/src/plugins/codesample/test/ts/browser/CodeSampleSanityTest.ts, modules/tinymce/src/plugins/codesample/test/ts/browser/CodeSampleSelectionTest.ts, modules/tinymce/src/plugins/codesample/test/ts/module/CodeSampleTestUtils.ts
* Converts the `codesample` plugin to use BDD style tests
Pre-checks:
Review:
=> TINY-6870: Switch codesample plugin to use BDD style tests

modules/agar/src/main/ts/ephox/agar/api/RealMouse.ts, modules/tinymce/src/plugins/fullscreen/test/ts/browser/FullScreenPluginTest.ts, modules/tinymce/src/plugins/fullscreen/test/ts/browser/FullscreenPluginInlineEditorTest.ts, modules/tinymce/src/plugins/fullscreen/test/ts/webdriver/FullscreenPluginNativeModeTest.ts
* Converts the `fullscreen` plugin to use BDD style tests
* Added new `RealMouse` helpers
Pre-checks:
Review:
=> TINY-6870: Switch fullscreen plugin to use BDD style tests

modules/tinymce/src/plugins/hr/test/ts/browser/HrSanityTest.ts
* Converts the `hr` plugin to use BDD style tests
Pre-checks:
Review:
=> TINY-6870: Switch hr plugin to use BDD style tests

modules/tinymce/src/plugins/directionality/test/ts/browser/DirectionalitySanityTest.ts
* Converts the `directionality` plugin to use BDD style tests
Pre-checks:
Review:
=> TINY-6870: Switch directionality plugin to use BDD style tests

modules/tinymce/src/plugins/emoticons/test/ts/browser/DifferentEmojiDatabaseTest.ts, modules/tinymce/src/plugins/emoticons/test/ts/browser/EmoticonAppendTest.ts, modules/tinymce/src/plugins/emoticons/test/ts/browser/EmoticonAutocompletionTest.ts, modules/tinymce/src/plugins/emoticons/test/ts/browser/EmoticonSearchTest.ts, modules/tinymce/src/plugins/emoticons/test/ts/browser/ImageEmoticonTest.ts, modules/tinymce/src/plugins/emoticons/test/ts/module/test/Utils.ts
* Converts the `emoticons` plugin to use BDD style tests
Pre-checks:
Review:
=> TINY-6870: Switch emoticons plugin to use BDD style tests

modules/agar/src/main/ts/ephox/agar/api/FileInput.ts, modules/agar/src/main/ts/ephox/agar/file/PatchInputFiles.ts, modules/mcagar/src/main/ts/ephox/mcagar/api/TinyUiActions.ts, modules/sugar/src/main/ts/ephox/sugar/api/properties/Checked.ts, modules/sugar/src/test/ts/browser/CheckedTest.ts, modules/tinymce/src/plugins/image/test/ts/browser/A11yImageTest.ts, modules/tinymce/src/plugins/image/test/ts/browser/ContextMenuTest.ts, modules/tinymce/src/plugins/image/test/ts/browser/DecorativeImageDialogTest.ts, modules/tinymce/src/plugins/image/test/ts/browser/DialogTest.ts, modules/tinymce/src/plugins/image/test/ts/browser/DialogUpdateTest.ts, modules/tinymce/src/plugins/image/test/ts/browser/FigureDeleteTest.ts, modules/tinymce/src/plugins/image/test/ts/browser/FigureResizeTest.ts, modules/tinymce/src/plugins/image/test/ts/browser/ImageListTest.ts, modules/tinymce/src/plugins/image/test/ts/browser/ImagePluginTest.ts, modules/tinymce/src/plugins/image/test/ts/browser/ImageResizeTest.ts, modules/tinymce/src/plugins/image/test/ts/browser/UploadTabTest.ts, modules/tinymce/src/plugins/image/test/ts/browser/api/CommandsTest.ts, modules/tinymce/src/plugins/image/test/ts/browser/core/ImageAlignTest.ts, modules/tinymce/src/plugins/image/test/ts/browser/core/ImageDataTest.ts, modules/tinymce/src/plugins/image/test/ts/browser/core/ImageSelectionTest.ts, modules/tinymce/src/plugins/image/test/ts/browser/plugin/DefaultEmptyTest.ts, modules/tinymce/src/plugins/image/test/ts/browser/plugin/DimensionsFalseTest.ts, modules/tinymce/src/plugins/image/test/ts/browser/plugin/MainTabTest.ts, modules/tinymce/src/plugins/image/test/ts/browser/plugin/PrependAbsoluteTest.ts, modules/tinymce/src/plugins/image/test/ts/browser/plugin/PrependRelativeTest.ts, modules/tinymce/src/plugins/image/test/ts/module/Helpers.ts, versions.txt
* Converts the `image` plugin to use BDD style tests
* Added more helper functions
Pre-checks:
Review:
=> TINY-6870: Switch image plugin to use BDD style tests

modules/tinymce/src/plugins/help/test/ts/browser/CustomTabsTest.ts, modules/tinymce/src/plugins/help/test/ts/browser/DialogKeyboardNavTest.ts, modules/tinymce/src/plugins/help/test/ts/browser/IgnoreForcedPluginsTest.ts, modules/tinymce/src/plugins/help/test/ts/browser/MetadataTest.ts, modules/tinymce/src/plugins/help/test/ts/browser/PluginTest.ts, modules/tinymce/src/plugins/help/test/ts/module/PluginAssert.ts, modules/tinymce/src/plugins/help/test/ts/module/test/FakePlugin.ts
* Converts the `help` plugin to use BDD style tests
Pre-checks:
Review:
=> TINY-6870: Switch help plugin to use BDD style tests

modules/tinymce/src/core/main/ts/Rtc.ts
* This moves the content api overrides for rtc into the rtc plugin it also namespaces the rtc api since it getting hard to know what is what and name clashes might start occuring.
Pre-checks:
Review:
=> TINY-6728: Redirect content apis to rtc plugin

modules/agar/package.json, modules/katamari-assertions/package.json, modules/tinymce/src/plugins/lists/test/ts/browser/BackspaceDeleteInlineTest.ts, package.json, yarn.lock
Related Ticket: TINY-6897
* This upgrades bedrock to the latest version and pulls in a fix that was causing some tests to not run.
Pre-checks:
Review:
=> TINY-6897: Upgraded to the latest version of bedrock

modules/oxide/src/less/theme/components/fullscreen/fullscreen.less, modules/tinymce/changelog.txt
Related Ticket: TINY-6903
* Added Oxide variable to define the container background color in fullscreen mode
Pre-checks:
Review:
=> Added Oxide variable to define the container background color in fullscreen mode

modules/darwin/src/main/ts/ephox/darwin/mouse/MouseSelection.ts, modules/tinymce/changelog.txt, modules/tinymce/src/plugins/table/test/ts/browser/TwoCellsSelectionTest.ts, versions.txt
Related Ticket: TINY-3897 & TINY-6667
Fixes an issue with Firefox whereby the selection would be incorrect when selecting only 2 cells and then trying to do operations.
Note: I had tried preventing the mouseover, etc... events to try and stop Firefox changing the selection, but unfortunately nothing worked. Either way, it still makes sense to ensure the fake selection is correct on `mouseup` since we know that's the end point in the selection.
Pre-checks:
Review:
Fixes #4914
Fixes #5078
=> TINY-3897 & TINY-6667: Fixed issues with fake table selection on Firefox

modules/alloy/src/main/ts/ephox/alloy/api/ui/TouchMenu.ts, modules/tinymce/changelog.txt, modules/tinymce/src/core/demo/html/shadow_dom_open_demo.html, modules/tinymce/src/core/demo/ts/demo/ShadowDomDemo.ts, modules/tinymce/src/core/main/ts/focus/EditorFocus.ts, modules/tinymce/src/plugins/charmap/test/ts/browser/CharmapDialogHeightTest.ts, modules/tinymce/src/themes/silver/main/ts/ui/alien/DialogTabHeight.ts, modules/tinymce/src/themes/silver/main/ts/ui/context/ContextUi.ts
Related Ticket: TINY-6904
* Fixed incorrectly getting focus from the root document when attempting to preserve the focus while adjusting the dialog height for collections.
* Fixed a few other minor places where we were getting the focus incorrectly as well (worth noting `TouchMenu` is never used and we possibly should delete it one day).
Pre-checks:
Review:
=> TINY-6904: Fixed focus lost in the charmap and emoticons dialog when typing within a shadow root

modules/agar/src/main/ts/ephox/agar/api/Mouse.ts, modules/tinymce/src/plugins/imagetools/test/ts/browser/ContextToolbarTest.ts, modules/tinymce/src/plugins/imagetools/test/ts/browser/ImageToolsCustomFetchTest.ts, modules/tinymce/src/plugins/imagetools/test/ts/browser/ImageToolsErrorTest.ts, modules/tinymce/src/plugins/imagetools/test/ts/browser/ImageToolsPluginTest.ts, modules/tinymce/src/plugins/imagetools/test/ts/browser/SequenceTest.ts, modules/tinymce/src/plugins/imagetools/test/ts/module/test/ImageOps.ts, modules/tinymce/src/plugins/imagetools/test/ts/module/test/ImageUtils.ts
* Converts the `imagetools` plugin to use BDD style tests
* Adds additional `Mouse` helper to match chain API
Pre-checks:
Review:
=> TINY-6870: Switch imagetools plugin to use BDD style tests

modules/tinymce/src/plugins/table/main/ts/ui/Helpers.ts, modules/tinymce/src/plugins/table/main/ts/ui/RowDialog.ts, modules/tinymce/src/plugins/table/test/ts/browser/HelpersTest.ts
Related Ticket: TINY-6738
* Unsupported attribute removed
* Pass test
Pre-checks:
Review:
=> TINY-6738  Remove 'scope' parameter from Table RowDialog

modules/snooker/src/main/ts/ephox/snooker/api/ResizeBehaviour.ts, modules/snooker/src/main/ts/ephox/snooker/api/TableOperations.ts, modules/snooker/src/main/ts/ephox/snooker/model/RunOperation.ts, modules/snooker/src/main/ts/ephox/snooker/resize/Adjustments.ts, modules/tinymce/changelog.txt, modules/tinymce/src/plugins/table/main/ts/actions/TableActions.ts, modules/tinymce/src/plugins/table/test/ts/browser/InsertColumnTableResizeTest.ts, modules/tinymce/src/plugins/table/test/ts/browser/InsertColumnTableSizeTest.ts, modules/tinymce/src/plugins/table/test/ts/browser/ModifyColumnsTableResizeTest.ts, versions.txt
Related Ticket: TINY-6711
Improved table resizing behaviour (when adding/removing columns) when using the `table_column_resizing` option.
| `table_column_resizing` | `table_sizing_mode` | `table_use_colgroups` | 
|--|--|--|
| `resizetable` | `fixed` | `true` | 
| `resizetable` | `fixed` | `false` | 
| `resizetable` | `relative` | `true` | 
| `resizetable` | `relative` | `false` |
| `resizetable` | `responsive` | `true` |  
| `resizetable` | `responsive` | `false` |  
| `preservetable` | `fixed` | `true` | 
| `preservetable` | `fixed` | `false` | 
| `preservetable` | `relative` | `true` | 
| `preservetable` | `relative` | `false` |
| `preservetable` | `responsive` | `true` |  
| `preservetable` | `responsive` | `false` |  
Pre-checks:
Review:
GitHub issues (if …
=> TINY-6711: Improved table resizing on column insertion and deletion

modules/agar/src/main/ts/ephox/agar/api/Touch.ts, modules/agar/src/main/ts/ephox/agar/find/UiSearcher.ts, modules/alloy/src/main/ts/ephox/alloy/api/testhelpers/GuiSetup.ts, modules/alloy/src/test/ts/browser/behaviour/BlockingTest.ts, modules/mcagar/src/main/ts/ephox/mcagar/api/ThemeSelectors.ts, modules/mcagar/src/main/ts/ephox/mcagar/api/bdd/TinyUiActions.ts, modules/sugar/src/main/ts/ephox/sugar/api/dom/Truncate.ts, modules/sugar/src/main/ts/ephox/sugar/api/node/SugarShadowDom.ts, modules/tinymce/src/plugins/code/test/ts/browser/CodeSanityTest.ts, modules/tinymce/src/plugins/code/test/ts/browser/CodeTextareaTest.ts, modules/tinymce/src/plugins/codesample/test/ts/module/CodeSampleTestUtils.ts, modules/tinymce/src/plugins/image/test/ts/browser/UploadTabTest.ts, modules/tinymce/src/plugins/imagetools/test/ts/browser/ContextToolbarTest.ts, modules/tinymce/src/plugins/lists/test/ts/browser/TableInListTest.ts
Related Ticket: TINY-6918
* Renamed `TinyUiActions.closeDialog` to `TinyUiActions.cancelDialog` as it was clicking the cancel button.
* Added `TinyUiActions.closeDialog` which will actually press the close button (needed for dialogs that don't have a cancel, etc...)
* Fixed `UiSearcher.findIn` logging a function string, rather than the actual error message.
* Fixed `Truncate.getHtml` not working for shadow root elements
* Added BDD helper functions to the Agar `Touch` module
* Added BDD helper functions to the Alloy `TestHelpers.GuiSetup` module
* Improved some types in the `SugarShadowDom` returns
Note: I've done this as a separate PR to make it easier to review. Actual silver theme test conversions are still a WIP.
Pre-checks:
Review:
GitHub issues (if …
=> TINY-6918: Additional helpers/fixes needed to convert silver theme tests

modules/snooker/src/main/ts/ephox/snooker/api/CopySelected.ts, modules/snooker/src/test/ts/browser/CopySelectedTest.ts
Related Ticket: TINY-6944
* Updates snooker so that series column attribute is not included on copied table when Ctrl+C
Pre-checks:
* ~~[ ] Branch prefixed with `feature/` for new features (if applicable)~~
* ~~[ ] License headers added on new files (if applicable)~~
Review:
=> TINY-6944: Update snooker to remove series column table attribute on copy

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/EventTypes.ts, modules/tinymce/src/core/main/ts/api/NotificationManager.ts, modules/tinymce/src/themes/silver/main/ts/Events.ts, modules/tinymce/src/themes/silver/main/ts/ui/menus/item/ItemEvents.ts, modules/tinymce/src/themes/silver/main/ts/ui/throbber/Throbber.ts, modules/tinymce/src/themes/silver/test/ts/browser/throbber/ThrobberPopupTest.ts
Related Ticket: TINY-6686
* Closed popups when the throbber is opened
* This required adding a new event to distinguish between "the throbber is going to open at {time}" and "the throbber is opening right now"
Pre-checks:
Review:
=> TINY-6686: Close popups when the throbber is opened

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/dom/DOMUtils.ts, modules/tinymce/src/core/main/ts/newline/InsertBr.ts, modules/tinymce/src/core/test/ts/browser/newline/InsertBrTest.ts
Related Ticket: TINY-6964
Previously when hitting `Shift+Enter` repeatedly, the editor would not scroll to the inserted `br` elements as they were pushed down out of the current view.
Pre-checks:
Review:
=> TINY-6964: Ensure br elements are scrolled into view when they are inserted

modules/tinymce/changelog.txt, modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialog.ts, modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialogCommon.ts, modules/tinymce/src/themes/silver/main/ts/ui/window/SilverInlineDialog.ts, modules/tinymce/src/themes/silver/main/ts/ui/window/SilverUrlDialog.ts, modules/tinymce/src/themes/silver/test/ts/browser/window/SilverDialogBlockTest.ts
Related Ticket: TINY-6971
* Fixes dialog API block messages not getting passed through for translation
Pre-checks:
Review:
=> TINY-6971: Fixed dialog block messages not getting translated

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/paste/main/ts/core/SmartPaste.ts, modules/tinymce/src/plugins/paste/main/ts/core/Utils.ts, modules/tinymce/src/plugins/paste/test/ts/browser/SmartPasteTest.ts, modules/tinymce/src/themes/silver/main/ts/ui/dialog/Dropzone.ts, modules/tinymce/src/themes/silver/test/ts/phantom/components/dropzone/DropzoneTest.ts
TINY-6940
Fixed an issue introduced by TINY-6306 where capitalised file extensions were treated as invalid.
Pre-checks:
Review:
Fixes #6459
=> TINY-6940: Support mixed case files extensions when handling images

modules/tinymce/src/themes/silver/main/ts/ContextToolbar.ts, modules/tinymce/src/themes/silver/test/ts/browser/throbber/ThrobberPopupTest.ts
Related Ticket: TINY-6686
* Same as the last 6686 PR, it's closing popups when the editor is blocked
* This time I made it work for context toolbars
Pre-checks:
Review:
=> TINY-6686: Ensure context toolbars also close when the throbber opens

modules/snooker/src/main/ts/ephox/snooker/api/CellMutations.ts, modules/snooker/src/main/ts/ephox/snooker/api/TableFill.ts, modules/snooker/src/main/ts/ephox/snooker/api/TableOperations.ts, modules/snooker/src/main/ts/ephox/snooker/lookup/Blocks.ts, modules/snooker/src/main/ts/ephox/snooker/resize/ColumnSizes.ts, modules/snooker/src/test/ts/browser/resize/ColumnSizesTest.ts, modules/tinymce/src/plugins/table/test/ts/browser/ModifyColumnsTableResizeTest.ts
Related Ticket: TINY-6711
* Fixes the width being removed on the source cell, not the cloned cell when a colspan existed.
* Fixes widths incorrectly being cloned for a colspan (it used the width of multiple cols when it should only use the cloned column width).
* Fixed getting column widths not working when a cell in the first row didn't have a width (it'd always use the computed width in that case, not the raw width specified on other cells in the column).
**Note:** I would like to redo how the cell halving is done, as this would still fail in some cases (eg every cell has a colspan) and it's not great we're relying on other code to set the cell width. However, to do that is going to require much larger changes and not something we should be including in 5.7. …
=> TINY-6711: Fixed an issue with widths being incorrectly cloned when inserting a new column that had a colspan previously

modules/tinymce/src/core/test/ts/browser/EditorManagerTest.ts
* The `EditorManager` test wasn't setting a base URL, so it was relying on that being set in previous tests to work. So this copies the logic from the `EditorInitializationTest` and removes the unnecessary `skin_url` and `content_css` settings.
Pre-checks:
Review:
=> Fixed a test failure on IE 11 due to the base URL not being set correctly

modules/tinymce/src/plugins/lists/main/ts/Plugin.ts, modules/tinymce/src/plugins/lists/main/ts/actions/Attributes.ts, modules/tinymce/src/plugins/lists/main/ts/actions/ToggleList.ts, modules/tinymce/src/plugins/lists/main/ts/actions/Update.ts, modules/tinymce/src/plugins/lists/main/ts/api/Commands.ts, modules/tinymce/src/plugins/lists/main/ts/core/Delete.ts, modules/tinymce/src/plugins/lists/main/ts/core/NodeType.ts, modules/tinymce/src/plugins/lists/main/ts/core/Selection.ts, modules/tinymce/src/plugins/lists/main/ts/ui/Dialog.ts, modules/tinymce/src/plugins/lists/main/ts/ui/MenuItems.ts, modules/tinymce/src/plugins/lists/test/ts/browser/ListPropertiesTest.ts
Related Ticket: TINY-6907
The list properties dialog now uses a new `SetListAttributes` command to set the list start attribute. I've also ensured the `mceListProps` command is registered in RTC mode and made use of it in the menu item instead of opening the dialog directly.
I didn't add a changelog for this because the list properties dialog doesn't seem to be documented yet; it's also an internal change that should have no impact on the feature.
Pre-checks:
Review:
=> TINY-6907: Added new mceListUpdate command

modules/tinymce/src/plugins/importcss/test/ts/browser/ImportCssGroupsPluginTest.ts, modules/tinymce/src/plugins/importcss/test/ts/browser/ImportCssPluginTest.ts, modules/tinymce/src/plugins/importcss/test/ts/module/MenuNavigationTestUtils.ts
* Switched the `importcss` plugin to use BDD style tests
Pre-checks:
Review:
=> TINY-6870: Switch importcss plugin to use BDD style tests

modules/bridge/src/main/ts/ephox/bridge/components/menu/ContextMenu.ts, modules/tinymce/changelog.txt, modules/tinymce/src/themes/silver/main/ts/ui/menus/contextmenu/SilverContextMenu.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/contextmenu/CustomContextMenuTest.ts, versions.txt
TINY-7073
Uses `CommonMenuItemSpec` for `ContextMenuItem` and `ContextSubMenu` in order to enable the following properties:
- `disabled`
- `shortcut`
Pre-checks:
Review:
=> TINY-7073: Support disabled and shortcut parameters for context menu items

modules/tinymce/CHANGELOG.md, modules/tinymce/src/themes/silver/main/ts/backstage/ColorInputBackstage.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/color/ColorSwatch.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/color/ColorPickerSanityTest.ts
TINY-2814
Shows an alert dialog when the color picker is submitted with an invalid hex color code.
Pre-checks:
Review:
=> TINY-2814: Show alert when submitting color picker dialog if hex color code is invalid

modules/tinymce/src/plugins/link/test/ts/atomic/DialogChangesTest.ts, modules/tinymce/src/plugins/link/test/ts/browser/AllowUnsafeLinkTargetTest.ts, modules/tinymce/src/plugins/link/test/ts/browser/AnchorFalseTest.ts, modules/tinymce/src/plugins/link/test/ts/browser/AssumeExternalTargetsTest.ts, modules/tinymce/src/plugins/link/test/ts/browser/ContextToolbarTest.ts, modules/tinymce/src/plugins/link/test/ts/browser/DefaultLinkProtocolTest.ts, modules/tinymce/src/plugins/link/test/ts/browser/DefaultLinkTargetTest.ts, modules/tinymce/src/plugins/link/test/ts/browser/DialogFlowTest.ts, modules/tinymce/src/plugins/link/test/ts/browser/DialogSectionsTest.ts, modules/tinymce/src/plugins/link/test/ts/browser/ImageFigureLinkTest.ts, modules/tinymce/src/plugins/link/test/ts/browser/LinkJustFirstFieldTest.ts, modules/tinymce/src/plugins/link/test/ts/browser/ListOptionsTest.ts, modules/tinymce/src/plugins/link/test/ts/browser/QuickLinkTest.ts, modules/tinymce/src/plugins/link/test/ts/browser/RemoveLinkTest.ts, modules/tinymce/src/plugins/link/test/ts/browser/SelectedImageLinkTest.ts, modules/tinymce/src/plugins/link/test/ts/browser/SelectedLinkTest.ts, modules/tinymce/src/plugins/link/test/ts/browser/SelectedTextLinkTest.ts, modules/tinymce/src/plugins/link/test/ts/browser/UpdateLinkTest.ts, modules/tinymce/src/plugins/link/test/ts/browser/UrlInputTest.ts, modules/tinymce/src/plugins/link/test/ts/browser/UrlProtocolTest.ts, modules/tinymce/src/plugins/link/test/ts/module/TestLinkUi.ts
TINY-7053
* Converts the `link` plugin to use BDD style tests
Pre-checks:
Review:
=> TINY-7053: Convert link plugin tests to use BDD style

modules/tinymce/changelog.txt, modules/tinymce/src/core/main/ts/api/dom/ControlSelection.ts, modules/tinymce/src/core/test/ts/browser/dom/ControlSelectionTest.ts, modules/tinymce/src/plugins/media/main/ts/core/Nodes.ts, modules/tinymce/src/plugins/media/test/ts/browser/LiveEmbedNodeTest.ts
Related Ticket: TINY-7074
* Fixes the width/height not being copied to the "wrapper" span used in the media plugin.
* Ensure when resizing the width/height are set on both the wrapper span and original media element.
Note: This will convert `%` to `px` when resizing but that's outside the scope of this, as TinyMCE's resizing logic has never supported that outside tables.
Pre-checks:
Review:
=> TINY-7074: Fixed a regression with widths/heights not being included on the media wrapper span

package.json, yarn.lock
* The IE 11 regression has now been fixed in chai, so this upgrades to the latest version.
Review:
=> Upgrade chai to fix 4.3.1 IE 11 regression

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/image/main/ts/ui/Dialog.ts, modules/tinymce/src/plugins/image/test/ts/browser/UploadTabTest.ts
Related Ticket: TINY-7099
* Fix a regression where the error message stopped being displayed correctly in the image upload dialog (was just `[object Object]`)
Pre-checks:
Review:
Fixes #6579
=> TINY-7099: Ensure that error message is displayed in image upload dialog

modules/tinymce/src/themes/silver/test/ts/browser/editor/SilverInlineEditorTest.ts, modules/tinymce/src/themes/silver/test/ts/browser/throbber/ThrobberPopupTest.ts
* Fixed the `SilverInlineEditorTest` flaking due to not having focus if the first test isn't run.
* Backported the flake fix from https://github.com/tinymce/tinymce/pull/6578
Pre-checks:
Review:
=> Fixed a test flake in the inline editor test

modules/agar/src/main/ts/ephox/agar/server/SeleniumAction.ts
Related Ticket: TINY-7039
* IE 11 tests are failing with the following error sometimes in CI. Due to this bug we're not able to find out why it's failing, so this just makes sure the failure is readable.
```
Test failed: webdriver.tinymce.core.content.PlaceholderTest - TINY-3917: Check placeholder hides when typing content and returns once content is deleted (modules/tinymce/src/core/test/ts/webdriver/content/PlaceholderTest.ts)
[object Object]
```
Review:
=> TINY-7039: Fix failure messages for agar selenium actions

modules/tinymce/src/core/main/ts/Rtc.ts
* When rtc is not enabled for a specific api key a sub plugin gets loaded instead of the real plugin. That plugin doesn't have any setup function so the Rtc integration would try to call a setup function on a plugin that doesn't have that function exported. This fix just check if the setup function exists if it doesn't it falls back to the normal editor setup but since the stub plugin will present a notification of that rtc is not enabled the user would be presented with a nice error message.
Pre-checks:
Review:
=> TINY-7098: fixed issue with setup function not always being available

package.json, yarn.lock
Related Ticket: TINY-7039
* Upgrade to the latest bedrock version to fix edge flakes caused by the mouse position on build nodes.
* Upgrade `elliptic` to pull in upstream security fixes
Review:
=> TINY-7039: Upgrade to bedrock 11.2.0 and upgrade elliptic

modules/katamari/CHANGELOG.md, modules/katamari/src/main/ts/ephox/katamari/api/Arr.ts, modules/katamari/src/test/ts/atomic/api/arr/ArrFindTest.ts, modules/mcagar/src/main/ts/ephox/mcagar/api/pipeline/TinyUi.ts, modules/polaris/src/main/ts/ephox/polaris/parray/Query.ts, versions.txt
TINY-7138
Adds type guard predicates to `Arr.find` and `Arr.findUntil`.
Pre-checks:
Review:
=> TINY-7138: Add type guards to array find methods in Katamari

modules/tinymce/changelog.txt, modules/tinymce/src/plugins/help/main/ts/ui/VersionTab.ts
Related Ticket: TINY-7031
* Change the URL from tinymce.com to tiny.cloud — tinymce.com does redirect to tiny.cloud, but it goes to the 4x docs instead of the modern ones.
Pre-checks:
Review:
=> TINY-7031: Change changelog URL in help plugin

package.json, yarn.lock
Pre-checks:
~* [ ] Branch prefixed with `feature/` for new features (if applicable)~
~* [ ] License headers added on new files (if applicable)~
Review:
=> Upgrade oxide-icons-tools to fix xmldom warnings

modules/tinymce/src/core/main/ts/SelectionOverrides.ts, modules/tinymce/src/core/main/ts/util/Quirks.ts
* Disables SelectionOverrides for content editable false elements since those are now handled by the RTC model.
* Disables some of the mutating quirks when running with RTC.
Pre-checks:
Review:
=> TINY-6706: disabled SelectionOverrides and dom/selection mutating quirks

modules/tinymce/src/core/main/ts/init/InitContentBody.ts
* This moved the initial content setup to the RTC plugin for both standalone mode and rtc mode. I'm keeping rtcMode as a return value for now maybe we need it for other things later.
Pre-checks:
Review:
=> TINY-7201: always let rtc plugin load the content from target element

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/SettingsTypes.ts
Related Ticket: #6607 
Adds missing settings type for `images_file_types`.
Pre-checks:
Review:
GitHub issues (if applicable): #6607
=> GH-6607: Add missing type for images_file_types setting

modules/oxide/src/less/theme/components/statusbar/statusbar.less, modules/tinymce/CHANGELOG.md, modules/tinymce/src/themes/silver/main/ts/Render.ts, modules/tinymce/src/themes/silver/main/ts/ui/statusbar/ResizeHandle.ts, modules/tinymce/src/themes/silver/main/ts/ui/statusbar/Statusbar.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/sizing/ResizeTest.ts, modules/tinymce/src/themes/silver/test/ts/browser/statusbar/StatusbarTest.ts
Related Ticket: TINY-4823
* Add keyboard control to the editor resize handle
Pre-checks:
Other checks:
Review:
=> TINY-4823: Add keyboard control to the editor resize handle

modules/oxide/src/less/theme/components/button/button.less, modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/searchreplace/main/ts/ui/Dialog.ts, modules/tinymce/src/plugins/searchreplace/test/ts/browser/SearchReplaceKeyboardNavigationTest.ts, modules/tinymce/src/themes/silver/demo/ts/components/searchreplace/SearchReplace.ts
Related Ticket: TINY-6816
* Make sure dialog buttons use sentence case for their text.
Pre-checks:
Review:
=> TINY-6816: Fix title-case dialog buttons

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/fmt/DefaultFormats.ts, modules/tinymce/src/core/test/ts/browser/FormattingCommandsTest.ts, modules/tinymce/src/core/test/ts/browser/fmt/MediaAlignTest.ts
Related Ticket: TINY-6633
* Allow the `small` element to be removed when clearing text formatting
* Add `video` and `audio` to align formats. Worth noting that if the media plugin is enabled, the alignments won't work on them which needs to be looked into in a separate ticket.
Pre-checks:
* ~~[ ] Branch prefixed with `feature/` for new features (if applicable)~~
* ~~[ ] License headers added on new files (if applicable)~~
Review:
=> TINY-6633: Add HTML5 elements to default formats

modules/tinymce/src/core/main/ts/selection/WordSelection.ts, modules/tinymce/src/core/test/ts/browser/keyboard/ArrowKeysInlineBoundariesTest.ts
Related Ticket: TINY-7334
* Branches the assertion logic for the "moveByWord" test due to the change of behaviour on Windows Edge/Chrome v90. It will now move to the start of the next word instead of the end of the next word.
* Updates some assertions to use the newer `assertCursor` helper instead of the `assertSelection` helper.
* Added return types to `WordSelection`
Pre-checks:
Review:
=> TINY-7334: Fixed ArrowKeys test failure on Windows Chrome/Edge v90

modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/image/main/ts/ui/MainTab.ts, modules/tinymce/src/plugins/image/test/ts/browser/plugin/MainTabTest.ts
Related Ticket: [TINY-6400](https://ephocks.atlassian.net/secure/RapidBoard.jspa?rapidView=116&modal=detail&selectedIssue=TINY-6400)
* Update tap config to forcing it into a 2 column grid if both a class list and caption are enabled
Pre-checks:
Review:
=> feature/TINY-6400: Image dialog incorrectly renders class/caption in grid

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/html/StyleUtils.ts, modules/tinymce/src/core/main/ts/content/InsertContentImpl.ts, modules/tinymce/src/core/main/ts/dom/NodeStyleUtils.ts, modules/tinymce/src/core/test/ts/browser/content/InsertContentTest.ts
Related Ticket: TINY-6263
* Fix an issue where `editor.insertContent` merged matching style spans without checking if another in-between node had the same style, but a different value
Pre-checks:
Review:
=> TINY-6263: Fix `editor.insertContent` incorrectly handling nested style spans

modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/table/main/ts/Plugin.ts, modules/tinymce/src/plugins/table/main/ts/queries/TabContext.ts, modules/tinymce/src/plugins/table/test/ts/browser/TabKeyNavigationTest.ts
Related Ticket: TINY-6638
Allow table tab navigation with ranged selections
Pre-checks:
Review:
=> TINY-6638: Allow table tab navigation with ranged selections

modules/tinymce/src/themes/silver/test/ts/phantom/components/urlinput/UrlInputTest.ts
* Fixed the UrlInputTest flaking because it was relying on previous test state (it was relying on the previous test opening the menu)
* Fixed typo in test file name `UrlinputTest` -> `UrlInputTest`.
Pre-checks:
Review:
=> Fixed the UrlInputTest flaking because it was relying on previous test state

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/util/Tools.ts, modules/tinymce/src/core/test/ts/browser/util/ToolsTest.ts
This regression caused all the create calls to use the same constructor, as it was reusing the `Fun.noop` function.
Related Ticket: TINY-7358
* Fixed a regression causing issues with the `tinymce.create` API.
Pre-checks:
Review:
=> TINY-7358: Fixed a regression in the Tools.create() API

modules/tinymce/src/plugins/table/main/ts/queries/TabContext.ts, modules/tinymce/src/plugins/table/test/ts/browser/TabKeyNavigationTest.ts
Related Ticket: TINY-6638
Fixes several bugs found in QA regarding where the selection is collapsed to
Pre-checks:
Review:
=> TINY-6638_2: Fix location of collapsed selection before operating on table

modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/table/main/ts/api/Commands.ts, modules/tinymce/src/plugins/table/main/ts/selection/SelectionTargets.ts, modules/tinymce/src/plugins/table/main/ts/selection/TableSelection.ts, modules/tinymce/src/plugins/table/main/ts/ui/TableDialog.ts, modules/tinymce/src/plugins/table/test/ts/browser/InlineEditorInsideTableTest.ts
Related Ticket: TINY-6625
Pre-checks:
Review:
=> TINY-6625: Table plugin tries to perform operations on tables that contain the (inline) editor

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/fmt/MatchFormat.ts, modules/tinymce/src/core/test/ts/browser/FormatterApplyTest.ts, modules/tinymce/src/core/test/ts/browser/FormatterCheckTest.ts, modules/tinymce/src/core/test/ts/browser/FormatterRemoveTest.ts
Related Ticket: [7227](https://ephocks.atlassian.net/secure/RapidBoard.jspa?rapidView=116&modal=detail&selectedIssue=TINY-7227)
* Match multiple classes on the same element
Pre-checks:
Review:
=> TINY-7227: Support formatting multiple classes on same element

modules/tinymce/src/themes/silver/test/ts/module/StickyHeaderStep.ts, modules/tinymce/src/themes/silver/test/ts/module/StickyHeaderUtils.ts
* Fix another test flake causing nightly builds to fail. This was another case of incorrectly relying on previous test state (in this case the scroll position).
Pre-checks:
Review:
=> Fixed more test flakes

modules/imagetools/src/main/ts/ephox/imagetools/transformations/ImageTools.ts, modules/imagetools/src/test/ts/browser/RotateTest.ts
Related Ticket: TINY-7371
* The image rotation logic had an issue in that it wouldn't set the right dimensions if the degrees passed wasn't 90/180/270/360.
Pre-checks:
Review:
=> TINY-7371: Fixed imagetools rotation logic not working with anything other than 90 degree increments

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/commands/LineHeight.ts, modules/tinymce/src/core/test/ts/browser/commands/LineHeightTest.ts
Related Ticket: TINY-7048
* Fixes the `LineHeight` command incorrectly being wrapped in an UndoManager transaction (commands are already wrapped via the command manager). This then caused an UndoLevel to be created too early, which in turn caused the `change` event to fire inconsistently.
Pre-checks:
Review:
Fixes #6549
=> TINY-7048: Fixed the `LineHeight` command causing the `change` event to be fired inconsistently

modules/bridge/src/main/ts/ephox/bridge/components/toolbar/ToolbarSplitButton.ts, modules/tinymce/CHANGELOG.md, modules/tinymce/src/themes/silver/main/ts/ui/core/color/ColorSwatch.ts, modules/tinymce/src/themes/silver/main/ts/ui/toolbar/button/ToolbarButtons.ts
Related Ticket: TINY-3551
* Fixed the `forecolor`/`backcolor` color indicator ending up blurry due to incorrectly setting the `stroke` attribute when changing the color.
* Deprecated the undocumented `setIconStroke` Split Toolbar button API.
Before:
After:
Pre-checks:
Review:
=> TINY-3551: Fixed the forecolor/backcolor color indicator being blurry

modules/tinymce/src/plugins/paste/main/ts/core/WordFilter.ts, modules/tinymce/src/plugins/paste/test/ts/browser/PasteTest.ts
This pull request replaces #6621 as agreed with @JamesToohey.
Fixes #6620
Previously roman numerals with more than two characters
caused the list to split into two. E.g. the list below would split
to ol & ul at third item:
```
i. First
ii. Second
iii. Third
```
The included test case covers numerals from I to X.
Pre-checks:
Review:
- #6620 
- #2933
=> Fixed roman numeral detection with copy-paste from Word.

.github/ISSUE_TEMPLATE/feature_request.md
GitHub allows setting default labels when issues are created via templates, so this is just a small change to have the `feature` label set by default.
=> Added default label to feature requests

modules/tinymce/src/plugins/help/main/ts/ui/KeyboardNavTab.ts
Related Ticket: TINY-7387
* Update the help dialog to mention that the editor resize handle is in the list of things selectable via keyboard navigation now
Pre-checks:
Review:
=> TINY-7387: Update the help dialog to mention keyboard resizing of the editor

modules/tinymce/CHANGELOG.md, modules/tinymce/package.json, modules/tinymce/src/core/test/ts/browser/ReadOnlyModeTest.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/complex/AlignSelect.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/complex/BespokeSelect.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/complex/FontSelect.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/complex/FontsizeSelect.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/complex/FormatSelect.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/complex/StyleSelect.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/ReadonlyToolbarResizeTest.ts
Related Ticket: TINY-6383
* Fixed an exception thrown when switching to readonly mode and resizing the editor
* Cleaned up the bespoke logic, as it was overly complicated
Note: This is the low-risk version of this fix, however I'm going to create a more versatile fix for 5.9 that will follow this.
Pre-checks:
Review:
=> TINY-6383: Fixed an exception thrown when switching to readonly mode and resizing the editor

modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/pagebreak/main/ts/api/Commands.ts, modules/tinymce/src/plugins/pagebreak/main/ts/core/FilterContent.ts, modules/tinymce/src/plugins/pagebreak/main/ts/core/ResolveName.ts, modules/tinymce/src/plugins/pagebreak/test/ts/browser/PageBreakSanityTest.ts, modules/tinymce/src/plugins/pagebreak/test/ts/browser/PageBreakSplitBlockTest.ts
Related Ticket: TINY-3388
Fixed the bug by ensuring all code paths add the wrapping `p` element around the pagebreak
Pre-checks:
Review:
GitHub issues (if applicable): https://github.com/tinymce/tinymce/issues/4844
=> TINY-3388: Fix block elements containing pagebreaks being removed when `pagebreak_split_block=true`

modules/mcagar/CHANGELOG.md, modules/mcagar/src/main/ts/ephox/mcagar/alien/EditorTypes.ts, modules/mcagar/src/main/ts/ephox/mcagar/api/bdd/TinyAssertions.ts, modules/tinymce/src/plugins/fullpage/test/ts/browser/FullPagePluginTest.ts, versions.txt
Related Ticket: TINY-3388
Note: This couldn't go through with #6792 because it's a `minor` bump to mcagar.
Pre-checks:
Review:
=> TINY-3388_2: Allow optional getContent args in TinyAssertions.assertContent

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/fmt/RemoveFormat.ts, modules/tinymce/src/core/test/ts/browser/fmt/RemoveFormatTest.ts
Related Ticket: TINY-6264
Ensure that nested list items do not have their `list-style-type: none;` style removed when clearing formatting. This resulted in a bug where the markers for each li would be revealed.
Pre-checks:
Review:
=> TINY-6264: Ensure list-style-type: none is not removed from nested lists when clearing formatting

modules/tinymce/src/plugins/noneditable/test/ts/browser/NonEditablePluginTest.ts
BDD style test for `noneditable` plugin
Pre-checks:
Review:
=> TINY-6870: Switch Noneditable plugin to use BDD style tests 

modules/tinymce/src/plugins/nonbreaking/test/ts/browser/NonbreakingForceTabTest.ts, modules/tinymce/src/plugins/nonbreaking/test/ts/browser/NonbreakingSanityTest.ts, modules/tinymce/src/plugins/nonbreaking/test/ts/browser/NonbreakingSettingsTest.ts, modules/tinymce/src/plugins/nonbreaking/test/ts/browser/NonbreakingVisualCharsTest.ts, modules/tinymce/src/plugins/nonbreaking/test/ts/webdriver/NonbreakingTypingTest.ts, modules/tinymce/src/plugins/nonbreaking/test/ts/webdriver/NonbreakingVisualCharsTypingTest.ts, modules/tinymce/src/plugins/nonbreaking/test/ts/webdriver/NonbreakingWrapTypingTest.ts
Switch `nonbreaking` plugin to use BDD style tests
Pre-checks:
Review:
=> TINY-6870: Switch Nonbreaking plugin to use BDD style tests

modules/tinymce/src/plugins/preview/test/ts/browser/PreviewContentCssTest.ts, modules/tinymce/src/plugins/preview/test/ts/browser/PreviewContentStyleTest.ts, modules/tinymce/src/plugins/preview/test/ts/browser/PreviewSanityTest.ts
Switch `preview` plugin to use BDD style tests
Pre-checks:
Review:
=> TINY-6870: Switch Preview plugin to use BDD style tests

modules/tinymce/src/plugins/save/test/ts/browser/SaveSanityTest.ts
Switch `save` plugin to use BDD style tests
Pre-checks:
Review:
=> TINY-6870: Switch save plugin to use BDD style tests

modules/tinymce/src/plugins/tabfocus/test/ts/browser/TabfocusSanityTest.ts
Switch `tabfocus` plugin to use BDD style tests
Pre-checks:
Review:
=> TINY-6870: Switch tabfocus plugin to use BDD style tests

modules/tinymce/src/plugins/print/test/ts/browser/PrintSanityTest.ts
Switch `print` plugin to use BDD style tests
Pre-checks:
Review:
=> TINY-6870: Switch print plugin to use BDD style tests

modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/paste/main/ts/core/Clipboard.ts
Related Ticket: TINY-6493
* Fixes to paste plugin (see title)
Pre-checks:
Review:
Before merge:
GitHub issues (if applicable): Fixes #6493
=>   TINY-6997: Paste plugin with smart_paste not pasting url over highlighted text

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/NotificationManager.ts, modules/tinymce/src/core/test/ts/browser/NotificationManagerTest.ts
Related Ticket: TINY-7486
* Restructure the OpenNotification event fields
Pre-checks:
Review:
=> TINY-7486: Restructure the OpenNotification event fields

modules/agar/CHANGELOG.md, modules/agar/src/main/ts/ephox/agar/api/Clipboard.ts, modules/agar/src/main/ts/ephox/agar/datatransfer/DataTransfer.ts, modules/agar/src/main/ts/ephox/agar/dragndrop/DndEvents.ts, modules/agar/src/main/ts/ephox/agar/keyboard/FakeKeys.ts, modules/agar/src/test/ts/browser/KeyboardTest.ts, modules/agar/src/test/ts/browser/api/ClipboardTest.ts
* Added new BDD clipboard helpers
* Fixed issues found in the mocked DataTransfer and FakeKeys implementations.
Note: This was split out from the other conversions to make it easier to review.
Pre-checks:
Review:
=> TINY-6870: Added APIs and fixed issues found in Agar while converting tests to BDD

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/Rtc.ts, modules/tinymce/src/core/main/ts/init/InitContentBody.ts, modules/tinymce/src/core/test/ts/browser/EditorRemoveTest.ts, modules/tinymce/src/themes/mobile/test/ts/module/test/theme/TestTheme.ts
* This changes the load order of things so that the content css gets loaded before the editor is filled with contents. This is to prevent a FOUC happening while loading the editor. It's extra visible with RTC but I think this happens on the non RTC version of tinymce as well. Not sure how to make a unit test for this though since just waiting for the events to fire is not enough to ensure that a flash doesn't occur.
Pre-checks:
Review:
=> TINY-7249: changed loading order so content css gets loaded before loading contents

modules/tinymce/src/plugins/searchreplace/test/ts/browser/SearchReplaceDialogCyclingTest.ts, modules/tinymce/src/plugins/searchreplace/test/ts/browser/SearchReplaceDialogTest.ts, modules/tinymce/src/plugins/searchreplace/test/ts/browser/SearchReplaceInSelectionTest.ts, modules/tinymce/src/plugins/searchreplace/test/ts/browser/SearchReplaceKeyboardNavigationTest.ts, modules/tinymce/src/plugins/searchreplace/test/ts/browser/SearchReplacePluginTest.ts, modules/tinymce/src/plugins/searchreplace/test/ts/browser/SearchReplacePrevNextTest.ts, modules/tinymce/src/plugins/searchreplace/test/ts/browser/UndoReplaceSpanTest.ts, modules/tinymce/src/plugins/searchreplace/test/ts/module/test/Utils.ts
Convert the `searchreplace` plugin to use BDD style tests
Pre-checks:
Review:
=> TINY-6870: Convert the searchreplace plugin to use BDD style tests

modules/tinymce/Gruntfile.js
modules/tinymce/copyright-header.js needs to be included in
tinymce_5.*_dev.zip for it to build cleanly.
* Adding inclusion of modules/tinymce/copyright-header.js in the Gruntfile, so it will be added to the archive.
Pre-checks:
Review:
* ~[ ] Milestone set~
Fixes #6867
=> Add copyright-header.js to dev archive

modules/acid/CHANGELOG.md, modules/acid/src/main/ts/ephox/acid/api/colour/HexColour.ts, modules/acid/src/main/ts/ephox/acid/api/colour/Transformations.ts, modules/acid/src/test/ts/atomic/HexColourTest.ts, modules/acid/src/test/ts/browser/TransformationsTest.ts, modules/tinymce/CHANGELOG.md, modules/tinymce/src/themes/silver/main/ts/ui/core/color/Settings.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/color/ColorSettingsTest.ts, versions.txt
Related Ticket: TINY-7480/TINY-7163
This splits out the color parsing/transformation logic from Silver to Acid that @HAFRMO and I came up with for https://github.com/tinymce/tinymce/pull/6761/, as it's going to be needed in multiple places and not just in TinyMCE. This also adds the acid changelog/tests.
Pre-checks:
Review:
=> TINY-7480: Split out colour transformation logic to acid

modules/tinymce/src/themes/silver/test/ts/phantom/toolbar/ToolbarButtonsTest.ts
* If the very first test in `ToolbarButtonsTest` didn't run, then all subsequent tests would fail. As such, this moves the clear store call before each other test.
Pre-checks:
Review:
=> Fixed the ToolbarButtonsTest flaking when not run in a specific order

modules/tinymce/src/themes/silver/main/ts/ui/dialog/imagetools/ImagePanel.ts, modules/tinymce/src/themes/silver/main/ts/ui/dialog/imagetools/ImageTools.ts
This should fix a long-standing Firefox test flake. I haven't been able to verify it, as it's quite random, however what I believe was happening was that the `loadImage` promise would resolve, however the alloy components had been removed in the very short time that the image was attempting to load. Given the timing required to trigger this, it's possible a user could run into it, but the chances would be extremely unlikely and if it did nothing is going to fail.
Note: This also does some minor cleanup as we never used the `Optional` passed all the way up from `updateSrc` and it didn't make sense to be returning the temporary image.
For reference, here's what we'd see as the test failure:
```
12:42:36  Current test: …
```
=> Fixed a test flake on Firefox

modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/fullpage/main/ts/core/FilterContent.ts, modules/tinymce/src/plugins/fullpage/main/ts/core/Parser.ts
Related Ticket: TINY-6504
- Rather than building a new schema, this just uses the existing editor schema. Shaves ~4-5ms off the script load time.
Pre-checks:
Review:
=> TINY-6504: Use pre-existing editor schema in fullpage plugin when parsing editor contents

modules/tinymce/src/core/main/ts/util/Quirks.ts
* It seems that the IME fix is a more generic issue now days on Chromium based browsers. So I renamed the function and added some comment details about that. But this doesn't change any behavior except for RTC so I didn't add a change log item.
Pre-checks:
Review:
=> TINY-7544: enabled the document element focus fix for the RTC branch

package.json, yarn.lock
Related Ticket: TINY-7531
* Upgrade bedrock to pull in recent fixes and improvements
* Upgraded the eslint-plugin from 1.8.1 to 1.8.2
Pre-checks:
Review:
=> TINY-7531: Upgrade to the latest bedrock version

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/dom/EventUtils.ts, modules/tinymce/src/core/main/ts/api/util/EventDispatcher.ts, modules/tinymce/src/core/main/ts/content/GetContentImpl.ts, modules/tinymce/src/core/main/ts/content/SetContentImpl.ts, modules/tinymce/src/core/main/ts/events/EventUtils.ts, modules/tinymce/src/core/main/ts/selection/GetSelectionContentImpl.ts, modules/tinymce/src/core/main/ts/selection/SetSelectionContent.ts, modules/tinymce/src/core/test/ts/browser/selection/SetSelectionContentTest.ts, modules/tinymce/src/core/test/ts/browser/util/EventDispatcherTest.ts
Related Ticket: TINY-3254
* Fixed `EventDispatcher` mutating the data provided
* Reworked the logic to share the clone/normalize functionality between `EventUtils` and `EventDispatcher`
* Fixed a small bug in `SetSelectionContent` I found when cleaning up the incorrect reliance on mutation when getting and setting content.
Pre-checks:
Review:
=> TINY-3254: Fixed EventDispatcher mutating the original event data

modules/tinymce/CHANGELOG.md, modules/tinymce/src/themes/silver/main/ts/modes/Inline.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/ShowHideTest.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/SilverFixedToolbarContainerTest.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/SilverInlineEditorTest.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/contexttoolbar/ContextToolbarBoundsTest.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/ToolbarDrawerToggleTest.ts, modules/tinymce/src/themes/silver/test/ts/module/TestUtils.ts, modules/tinymce/src/themes/silver/test/ts/module/UiUtils.ts, modules/tinymce/src/themes/silver/test/ts/webdriver/editor/SimpleControlsInlineTest.ts, modules/tinymce/src/themes/silver/test/ts/webdriver/throbber/ThrobberTabbingTest.ts
Related Ticket: TINY-6297
This fixes certain operations performing on a selection that may not be valid yet (e.g. the selection could be in another editor on the same page).
The bug reported was when two inline editors are on the same page, the toolbar state does not update correctly when you move your selection to another editor.
Pre-checks:
Review:
GitHub issues (if applicable): Fixes #5947
=> TINY-6297: Push editor rendering on focus into another event loop

modules/alloy/CHANGELOG.md, modules/alloy/src/main/ts/ephox/alloy/positioning/layout/Layout.ts, modules/alloy/src/main/ts/ephox/alloy/positioning/layout/LayoutInside.ts, modules/alloy/src/main/ts/ephox/alloy/positioning/layout/LayoutTypes.ts, modules/alloy/src/main/ts/ephox/alloy/positioning/layout/LinkedLayout.ts, modules/alloy/src/main/ts/ephox/alloy/positioning/layout/Placement.ts, modules/alloy/src/main/ts/ephox/alloy/positioning/layout/SimpleLayout.ts, modules/alloy/src/main/ts/ephox/alloy/positioning/view/Bounder.ts, modules/alloy/src/main/ts/ephox/alloy/positioning/view/Callouts.ts, modules/alloy/src/main/ts/ephox/alloy/positioning/view/Reposition.ts, modules/alloy/src/main/ts/ephox/alloy/positioning/view/SpotInfo.ts, modules/alloy/src/test/ts/browser/position/layout/LayoutInsidePreserveTest.ts, modules/alloy/src/test/ts/browser/position/view/BounderCursorTest.ts, modules/alloy/src/test/ts/browser/position/view/BounderMenuTest.ts, modules/alloy/src/test/ts/browser/position/view/BounderOverlappingTest.ts, modules/alloy/src/test/ts/browser/position/view/BounderToolbuttonTest.ts, modules/tinymce/CHANGELOG.md, modules/tinymce/src/themes/silver/demo/ts/demo/PlayDemo.ts, modules/tinymce/src/themes/silver/main/ts/ContextToolbar.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/contexttoolbar/ContextToolbarIframePositionTest.ts
Related Ticket: TINY-7545
This is part 3 of 3 PRs to get this working. This finally adds in the new `preserve` functionality to `LayoutInside` which will attempt to preserve the previous layout that was used for the component. This is done by storing the placement of the layout as chosen by `Bounder` via the `data-alloy-placement` attribute and then looking this up when repositioning.
This also cleans up the `ContextToolbar` logic a little, mainly just removing the duplicate `debounce` implementation we had going on.
**Note:** This builds on and does some reworking of the work done by @HAFRMO in https://github.com/tinymce/tinymce/pull/6725
Pre-checks:
Review:
=> TINY-7545: Attempt to preserve the previous position of context toolbars when rendering over top of the element

modules/tinymce/src/themes/silver/main/ts/ContextToolbar.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/contexttoolbar/ContextToolbarIframePositionTest.ts
Related Ticket: TINY-7545
* Fixed a bug @ltrouton found when doing team QA. The problem was the last anchor element was being updated before the element rendered, which caused it to always think it was rendering on the same anchor point.
Pre-checks:
Review:
=> TINY-7545: Fixed a bug with the context toolbar placement when switching anchors

modules/alloy/CHANGELOG.md, modules/alloy/src/main/ts/ephox/alloy/behaviour/common/Behaviour.ts, modules/alloy/src/main/ts/ephox/alloy/construct/CustomDefinition.ts, modules/alloy/src/main/ts/ephox/alloy/construct/EventHandler.ts, modules/alloy/src/main/ts/ephox/alloy/dom/DomModification.ts, modules/alloy/src/main/ts/ephox/alloy/toolbar/SplitToolbarUtils.ts, modules/boulder/CHANGELOG.md, modules/boulder/src/main/ts/ephox/boulder/core/StructureProcessor.ts, modules/tinymce/CHANGELOG.md, modules/tinymce/src/themes/silver/main/ts/Render.ts, modules/tinymce/src/themes/silver/main/ts/ui/menus/item/build/CommonMenuItem.ts
Related Ticket: TINY-7572
* Improves the boulder validation so that a lot less objects are created. This saves in construction time and also reduces the amount of garbage collection needed. It also reduces the amount of looping going on, as it was previously was looping at least twice for every field being validated.
* Removes the boulder validation from alloy event handler construction, as it's not needed with TypeScript and only slows things down setting up the event processing.
* Stores a constant copy of the component schema, which saves having to construct it for every Alloy component generated.
* A couple of other very minor cleanup tasks.
Pre-checks:
Review:
=> TINY-7572: Various little UI performance improvements

modules/tinymce/src/themes/silver/main/ts/ui/core/AlignmentButtons.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/ControlUtils.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/IndentOutdent.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/SimpleControls.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/UndoRedo.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/VisualAid.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/complex/AlignSelect.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/complex/BespokeSelect.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/complex/FontSelect.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/complex/FontsizeSelect.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/complex/FormatSelect.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/complex/StyleSelect.ts
Related Ticket: TINY-7572
The bespoke toolbar buttons where running a number of times before init and this didn't do anything meaningful as they need the initial location set during init. Additionally, these aren't the fastest lookups so this just makes the bespoke and other core buttons only start listening to events once the editor is initialized. I also did some code cleanup to remove duplicate code which made this easier to implement. Doing all this ends up saving another ~20-25ms during init time for the full feature demo.
Pre-checks:
Review:
=> TINY-7572: Minor toolbar button setup performance improvement and cleanup

modules/tinymce/src/core/main/ts/Rtc.ts
* This just redirects api calls that are unimplemented or noop to the RTC plugin so it can better log error messages and we can more easily log specific things on the RTC side without having to alter the tinymce core.
This is a two part PR rockfest has a PR as well.
Pre-checks:
Review:
=> TINY-7258: redirected unsupported api calls to rtc plugin

modules/oxide/src/less/theme/components/notification/notification.less, modules/tinymce/CHANGELOG.md
Related Ticket: TINY-7661
* Added a `cursor: pointer` style entry to `a` tags inside notifications. Without this they default to the text cursor.
Pre-checks:
Review:
=> TINY-7661: Add cursor: pointer to 'a' tags in notifications

package.json, yarn.lock
Related Ticket: TINY-7656
* Upgrade swag to 4.4.0
* Upgrade other deps (@types/chai, eslint & typescript)
Pre-checks:
Review:
=> TINY-7656: Upgrade swag and other dependencies

modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/code/main/ts/ui/Buttons.ts, modules/tinymce/src/plugins/codesample/main/ts/ui/Buttons.ts, modules/tinymce/src/plugins/emoticons/main/ts/Plugin.ts, modules/tinymce/src/plugins/emoticons/main/ts/api/Commands.ts, modules/tinymce/src/plugins/emoticons/main/ts/ui/Buttons.ts, modules/tinymce/src/plugins/template/main/ts/api/Commands.ts, modules/tinymce/src/plugins/template/main/ts/ui/Buttons.ts, modules/tinymce/src/plugins/wordcount/main/ts/Plugin.ts, modules/tinymce/src/plugins/wordcount/main/ts/api/Commands.ts, modules/tinymce/src/plugins/wordcount/main/ts/ui/Buttons.ts
* Changed emoticons, wordcount, code, and codesample plugins to open dialogs using commands
Pre-checks:
Review:
=> TINY-7619: Ensure all dialogs have the ability to be opened by a command

modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/directionality/demo/ts/demo/Demo.ts, modules/tinymce/src/plugins/directionality/main/ts/api/Commands.ts, modules/tinymce/src/plugins/directionality/main/ts/core/Direction.ts, modules/tinymce/src/plugins/directionality/test/ts/browser/DirectionalitySanityTest.ts
* when `rtl` or `ltr` is clicked on a list item (li) it applies `dir` to parent (`ul` or `ol`).
Pre-checks:
Review:
=> TINY-4589: Rtl/ltl attributes sometimes gets applied to list items

modules/boss/CHANGELOG.md, modules/boss/src/main/ts/ephox/boss/api/DomUniverse.ts, modules/boss/src/main/ts/ephox/boss/api/TestUniverse.ts, modules/boss/src/main/ts/ephox/boss/api/Universe.ts, modules/boss/src/main/ts/ephox/boss/mutant/Properties.ts, modules/robin/CHANGELOG.md, modules/robin/src/main/ts/ephox/robin/zone/LanguageZones.ts, modules/robin/src/main/ts/ephox/robin/zone/ZoneWalker.ts, modules/robin/src/test/ts/atomic/zone/LanguageGetTest.ts, modules/robin/src/test/ts/browser/LanguageOverrideTest.ts, versions.txt
Related Ticket: TINY-7570
* Add a new `getLanguage` function to boss' Universe
* Use that function everywhere we were previously looking at `.attr('lang')`
I'm targeting master here, so that we can get the changes released before 5.9 so that we can start using them elsewhere.
* This is a minor version bump of boss and robin, but that's okay because they've both received major version bumps on the develop branch
Pre-checks:
Review:
=> TINY-7570: Allow overrides to language extraction in robin's Zones APIs

modules/tinymce/src/core/main/ts/annotate/Wrapping.ts, modules/tinymce/src/core/main/ts/fmt/ApplyFormat.ts, modules/tinymce/src/core/main/ts/fmt/ExpandRange.ts, modules/tinymce/src/core/main/ts/fmt/FormatRegistry.ts, modules/tinymce/src/core/main/ts/fmt/FormatTypes.ts, modules/tinymce/src/core/main/ts/fmt/FormatUtils.ts, modules/tinymce/src/core/main/ts/fmt/MatchFormat.ts, modules/tinymce/src/core/main/ts/fmt/MergeFormats.ts, modules/tinymce/src/core/main/ts/fmt/MergeUtils.ts, modules/tinymce/src/core/main/ts/fmt/RemoveFormat.ts, modules/tinymce/src/core/test/ts/browser/fmt/RemoveFormatTest.ts
Related Ticket: TINY-7393
This is just an initial step towards fixing the root cause of this, as I kept struggling with the types and getting things incorrect. So this fixes the internal formatter types that I've known were incorrect for quite a while and also does a little clean up here and there to try and make things a little more manageable.
Note: This definitely doesn't fix all the various issues with formatter, it's just a partial step towards making it easier to maintain.
Pre-checks:
Review:
=> TINY-7393: Clean up formatter types and logic

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/bookmark/BookmarkTypes.ts, modules/tinymce/src/core/main/ts/bookmark/GetBookmark.ts, modules/tinymce/src/core/main/ts/content/ContentTypes.ts, modules/tinymce/src/core/main/ts/content/SetContentImpl.ts, modules/tinymce/src/core/main/ts/undo/Levels.ts, modules/tinymce/src/core/test/ts/browser/UndoManagerTest.ts
TINY-7663
When setting a bookmark, we now check to see if the selection is within a fake caret. If it _isn't_, we need to ensure that when we call `setContent` when restoring the content that a fake caret is not created (this will happen if the first element in the content is `contenteditable="false"`) by `moveSelection` in `SetContentImpl.ts`. 
If a fake caret is created - as it was previously - as this will mean when the selection is restored in `Levels.ts` that the path will be off by one.
**Pre-checks:**
**Review:**
=> TINY-7663: Fix selection location when undoing or redoing in a document with CEF elements

modules/darwin/CHANGELOG.md, modules/darwin/src/main/ts/ephox/darwin/keyboard/KeySelection.ts, modules/darwin/src/main/ts/ephox/darwin/mouse/MouseSelection.ts, modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/table/test/ts/browser/FakeSelectionTest.ts, modules/tinymce/src/plugins/table/test/ts/browser/NestedFakeSelectionTest.ts, modules/tinymce/src/plugins/table/test/ts/module/test/TableTestUtils.ts
Related Ticket: TINY-6298
* Update Darwin `MouseSelection` and `KeySelection` logic to only make a fake selection when more than one cell of the same table has been selected
Pre-checks:
Review:
=> TINY-6298: Fix table cell selection issue with nested tables

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/Rtc.ts, modules/tinymce/src/core/main/ts/api/Formatter.ts, modules/tinymce/src/core/main/ts/api/dom/DOMUtils.ts, modules/tinymce/src/core/main/ts/caret/CaretPosition.ts, modules/tinymce/src/core/main/ts/dom/NodeType.ts, modules/tinymce/src/core/main/ts/fmt/ApplyFormat.ts, modules/tinymce/src/core/main/ts/fmt/ExpandRange.ts, modules/tinymce/src/core/main/ts/fmt/FormatUtils.ts, modules/tinymce/src/core/main/ts/fmt/MatchFormat.ts, modules/tinymce/src/core/main/ts/fmt/RemoveFormat.ts, modules/tinymce/src/core/main/ts/selection/RangeNodes.ts, modules/tinymce/src/core/main/ts/selection/RangeWalk.ts, modules/tinymce/src/core/test/ts/browser/FormatterApplyTest.ts, modules/tinymce/src/core/test/ts/browser/dom/DomUtilsTest.ts, modules/tinymce/src/core/test/ts/browser/fmt/RemoveFormatTest.ts, modules/tinymce/src/core/test/ts/browser/selection/RangeWalkTest.ts
**Related Ticket:** TINY-7393
* Fixes an issue where selector formats (eg center alignment) wouldn't work due to how the ranges are walked (only nodes that are fully selected are returned). This expands on the original fix done in: https://github.com/tinymce/tinymce/pull/6666
* As part of this, I tried a number of solutions, one of which was making range walker return all the leaf nodes (which did work but ran into other edge case issues). As part of that I did a fair amount of clean up and wrote some additional tests, as `RangeWalk` has no tests currently, so this includes all of those clean ups/improvements as well (as discussed at standup).
Note: There's 2 commits to help with reviewing the different parts above.
**Additional information:**
So for those not …
=> TINY-7393: Fixed formats not applied correctly to nested list items

modules/alloy/CHANGELOG.md, modules/alloy/src/demo/html/layout-inset-demo.html, modules/alloy/src/demo/ts/ephox/alloy/demo/Demos.ts, modules/alloy/src/demo/ts/ephox/alloy/demo/LayoutInsetDemo.ts, modules/alloy/src/main/ts/ephox/alloy/api/Main.ts, modules/alloy/src/main/ts/ephox/alloy/positioning/layout/Bubble.ts, modules/alloy/src/main/ts/ephox/alloy/positioning/layout/LayoutInset.ts, modules/alloy/src/test/ts/browser/position/layout/LayoutInsetTest.ts, modules/alloy/src/test/ts/browser/position/view/BounderOverlappingTest.ts, modules/alloy/src/test/ts/browser/position/view/BounderToolbuttonTest.ts, modules/oxide/src/less/theme/components/pop/pop.less, modules/tinymce/CHANGELOG.md, modules/tinymce/src/themes/silver/main/ts/alien/NotificationManagerImpl.ts, modules/tinymce/src/themes/silver/main/ts/backstage/Anchors.ts, modules/tinymce/src/themes/silver/main/ts/ui/context/ContextToolbarAnchor.ts, modules/tinymce/src/themes/silver/main/ts/ui/menus/contextmenu/platform/MobileContextMenu.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/contexttoolbar/ContextToolbarDistractionFreePositionTest.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/contexttoolbar/ContextToolbarIframePositionTest.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/contexttoolbar/ContextToolbarInlinePositionTest.ts
Related Ticket: TINY-7665
* Renamed `LayoutInside` to `LayoutInset` since that's the relevant CSS term and what we've been calling it more lately.
* Make `Bubble` include a new inset class when generating a bubble to be used for an inset layout.
* Changed context toolbars to use the new `tox-pop--inset` class when using an inset layout. This class will hide the bubble arrow. Additionally to match the gif provided I've halved the bubble for insets.
* Note: I've intentionally used `opacity` here instead of `display: none` as there was some talk about making it transition as it disappears.
* Updated the tests to properly check if the toolbar is positioned so that it's overlapping (this couldn't be done previously since we didn't have a selector that was different). …
=> TINY-7665: Update the context toolbar to hide the bubble arrow when using an inset layout

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/Settings.ts, modules/tinymce/src/core/main/ts/api/SettingsTypes.ts, modules/tinymce/src/core/main/ts/init/InitIframe.ts, modules/tinymce/src/core/test/ts/browser/init/InitIframeAriaTextTest.ts, modules/tinymce/src/core/test/ts/browser/init/InitIframeContentAriaLabelTest.ts
Related Ticket: TINY-1264
* Create new setting `iframe_aria_text` to set the iframe title attribute
Pre-checks:
`modules/tinymce/src/core/test/ts/browser/init/InitIframeAriaTextTest.ts`
Review:
[Labeling editor field for accessibility doesn't work #177](https://github.com/tinymce/tinymce-react/issues/177)
=> TINY-1264: Make iframe title configurable

modules/tinymce/CHANGELOG.md, modules/tinymce/src/themes/silver/main/ts/ui/context/ContextToolbar.ts, modules/tinymce/src/themes/silver/main/ts/ui/context/ContextToolbarBounds.ts, modules/tinymce/src/themes/silver/main/ts/ui/menus/contextmenu/platform/MobileContextMenu.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/contexttoolbar/ContextToolbarBoundsTest.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/contexttoolbar/ContextToolbarIframePositionTest.ts
Related Ticket: TINY-7666
Changed the context toolbar bounds so that it can no longer overlap the statusbar for node/selection context toolbars (north/south). Line based (east/west) context toolbar will still overlap as discussed. The relevant positions should have moved by 18px (the height of the statusbar).
Pre-checks:
Review:
=> TINY-7666: Changed context toolbars to not overlap the statusbar

modules/tinymce/Gruntfile.js, yarn.lock
Related Ticket: TINY-7720
* Upgrade to the latest UglifyJS version
* Disable the `merge_vars` setting as it causes a behaviour change on IE 11 that results in things always being `undefined`
Pre-checks:
Review:
=> TINY-7720: Disable the UglifyJS `merge_vars` functionality due to issues with IE 11

modules/agar/CHANGELOG.md, modules/agar/src/main/ts/ephox/agar/api/UiControls.ts, modules/mcagar/src/main/ts/ephox/mcagar/api/ThemeSelectors.ts
Related Ticket: TINY-7065
- Fire event when changing field values
- Fix dialog close selector for v4
Pre-checks:
Review:
Before merge:
=> TINY-7065: Test library fixes and improvements

modules/agar/CHANGELOG.md, modules/agar/src/main/ts/ephox/agar/api/UiControls.ts
Related Ticket: TINY-7065
* Add optional eventName to UiControls.setValue
Pre-checks:
Review:
Upon merge:
=> TINY-7065: Add optional eventName to UiControls.setValue

modules/tinymce/src/plugins/link/main/ts/core/Utils.ts, modules/tinymce/src/plugins/link/main/ts/ui/Controls.ts
Use `Utils.link()` to both create and edit links from the quicklink bar.
Related Ticket: TINY-7729
* No user-visible changes, so no changelog, just redirecting quicklink code into existing code for create/edit link that knows about RTC.
Pre-checks:
Review:
=> TINY-7729: Use Utils.link() to both create and edit links from the quicklink bar

modules/tinymce/src/plugins/table/demo/ts/demo/Demo.ts, modules/tinymce/src/plugins/table/main/ts/ui/UiUtils.ts, modules/tinymce/src/plugins/table/test/ts/module/test/TableModifiersTestUtils.ts
For table lists with a None-entry, it now selects that entry if no other entry could be selected.
Pre-checks:
Review:
=> TINY-7690: None-entries are now selected if none other is.

modules/tinymce/src/core/main/ts/api/EditorUpload.ts
Related Ticket: TINY-6533
* No user-visible changes, so no changelog, just turning off code that mutates the DOM when RTC is active.
* RTC already handles image upload updates; we just had special code in our mutation blocker to allow these modifications to the view. They had no effect on the model.
* Turning off the unnecessary modifications allows us to remove those checks from our mutation blocker and prevent a class of mutations that could be performed without an error.
From what I can tell the image scanner should _never_ need to convert base64 to blob anymore - Spocke updated the parser to do it - but I'm not prepared to verify that right now.
Pre-checks:
Review:
=> TINY-6533: Turn off parts of image upload that RTC handles itself

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/EditorObservable.ts, modules/tinymce/src/core/test/ts/browser/EditorRemoveTest.ts
Related Ticket: TINY-7730
* Block `toggleNativeEvent` from doing anything if the editor has been removed
This condition has lurked for a _very_ long time, but we never hit it before RTC because most of the editor doesn't clean up event listeners (there's usually no need to). RTC disables most native event listeners but one was added a week ago (#7015).
The newly added listener is the only `mousedown` listener in RTC mode and it unbinds itself in the `remove` event.
The problem flow is:
* `editor.off()` triggers `toggleNativeEvent` for native event names
* However if this is done inside the `remove` event the delegates have already been unbound and `self.delegates` is undefined
* The result is an exception that blocks editor removal
Pre-checks:
Review:
GitHub issues …
=> TINY-7730: Fix problem where 'editor.off()' could cause 'editor.remove()' to fail

modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/bbcode/main/ts/Plugin.ts, modules/tinymce/src/plugins/fullpage/main/ts/Plugin.ts, modules/tinymce/src/plugins/legacyoutput/main/ts/Plugin.ts, modules/tinymce/src/plugins/spellchecker/main/ts/Plugin.ts
Related Ticket: TINY-7260
- Add removal notices to plugins scheduled to be removed in 6.0
Pre-checks:
Review:
=> TINY-7260: Add removal notices to plugins scheduled to be removed in 6.0

modules/tinymce/src/themes/silver/main/ts/ui/core/ChoiceControls.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/core/ChoiceControlsTest.ts
Related Ticket: TINY-7707
* Added new callbacks to `ChoiceControls` to define a custom setup function for the toolbar button/menu (they need to be different as they have different APIs and it's not something we can standardise).
* Updated the `language` toolbar button to mark itself as active when a `lang` format is active (i.e the selection is inside a lang span). This is done by using the format changed listener.
Pre-checks:
Review:
=> TINY-7707: Fixed the new language toolbar not showing as active when inside a language span

modules/sand/src/main/ts/ephox/sand/api/SandHTMLElement.ts, modules/sand/src/test/ts/browser/HtmlElementTest.ts, modules/snooker/src/test/ts/browser/resize/ColumnSizesTest.ts
Related Ticket: TINY-7374
* Fix the `SandHTMLElement.isPrototypeOf` function not working when an element is constructed in another window.
**Note:** Tests were failing because of the `ColumnSizesTest` issue on Chrome 92, so I've also cherry-picked that commit as well.
Pre-checks:
Review:
=> TINY-7374: Fixed SandHTMLElement not working across different windows

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/html/DomParser.ts, modules/tinymce/src/core/main/ts/api/html/SaxParser.ts, modules/tinymce/src/core/main/ts/init/InitContentBody.ts, modules/tinymce/src/core/test/ts/browser/dom/SerializerTest.ts, modules/tinymce/src/core/test/ts/browser/html/SaxParserTest.ts
Related Ticket: TINY-7756
This updates the parser to mark attributes as unsafe if they would clobber a document/form property. For those that aren't aware, using an id/name can cause the browser to store a reference to that element on the owner `document` or `form`. As such, using certain names/ids will cause the browser to overwrite the existing properties/functions.
Note: This is only part 1 of the issues for this Jira and I'm just creating the PR now to keep the PR size smaller as discussed earlier in the week.
Pre-checks:
Review:
=> TINY-7756: Fixed attributes clobbering native document properties causing the editor to crash

modules/tinymce/src/plugins/table/main/ts/Plugin.ts, modules/tinymce/src/plugins/table/main/ts/api/Commands.ts, modules/tinymce/src/plugins/table/main/ts/api/QueryCommands.ts, modules/tinymce/src/plugins/table/main/ts/core/Util.ts, modules/tinymce/src/plugins/table/main/ts/selection/SelectionTargets.ts, modules/tinymce/src/plugins/table/main/ts/selection/TableSelection.ts, modules/tinymce/src/plugins/table/test/ts/browser/settings/TableToolbarTest.ts, modules/tinymce/src/plugins/table/test/ts/browser/settings/ToolbarButtonDisplayTest.ts
Now check that the start and end are both within the same table.
Pre-checks:
Review:
=> TINY-7737: Table buttons enable only when whole selection is within the same table

modules/tinymce/src/plugins/table/main/ts/Plugin.ts, modules/tinymce/src/plugins/table/main/ts/api/Commands.ts, modules/tinymce/src/plugins/table/main/ts/core/TableFormats.ts, modules/tinymce/src/plugins/table/main/ts/ui/Buttons.ts, modules/tinymce/src/plugins/table/main/ts/ui/MenuItems.ts, modules/tinymce/src/plugins/table/main/ts/ui/UiUtils.ts, modules/tinymce/src/plugins/table/test/ts/browser/command/ModifyClassesCommandsTest.ts
Classes are now toggled as a group. Buttons also now consider the whole selection, not just the first.
No changelog since it's a bug-fix for unreleased feature.
Pre-checks:
Review:
=> TINY-7691: Table cell class changing now as a group, not individually

modules/snooker/CHANGELOG.md, modules/snooker/src/main/ts/ephox/snooker/api/Generators.ts, modules/snooker/src/main/ts/ephox/snooker/api/TableOperations.ts, modules/snooker/src/main/ts/ephox/snooker/operate/TransformOperations.ts, modules/snooker/src/test/ts/atomic/operate/TransformOperationsTest.ts, modules/snooker/src/test/ts/browser/HeaderOperationsTest.ts, modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/table/main/ts/Plugin.ts, modules/tinymce/src/plugins/table/main/ts/actions/TableActions.ts, modules/tinymce/src/plugins/table/main/ts/api/Commands.ts, modules/tinymce/src/plugins/table/main/ts/api/QueryCommands.ts, modules/tinymce/src/plugins/table/main/ts/ui/CellDialog.ts, modules/tinymce/src/plugins/table/test/ts/browser/TableSectionApiTest.ts
Related Ticket: TINY-6666
* Move the `mceTableCellType` logic to snooker.
* Clean up the existing query command logic and made `getCellsType` consistent with `getColsType` in snooker.
* Update the dialog to use the cell type command instead of using the able update cell type logic.
Pre-checks:
Review:
=> TINY-6666: Moved table cell type operations to snooker

modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/imagetools/main/ts/ui/Buttons.ts, modules/tinymce/src/plugins/imagetools/test/ts/browser/ImageToolsDisabledButtonsTest.ts
* Disable buttons - Edit, Flip h, Flip v, Rotate counterclockwise, Rotate clockwise - when setting `imagetools_proxy` is not provided and image is remote
Pre-checks:
Review:
=> TINY-7772: When no imagetools_proxy is provided buttons should be disabled for remote images

modules/snooker/CHANGELOG.md, modules/snooker/src/main/ts/ephox/snooker/api/TableOperations.ts, modules/snooker/src/test/ts/browser/EraseOperationsTest.ts, modules/tinymce/CHANGELOG.md
Related Ticket: TINY-7695
* Ensure that when erasing columns/rows we try to ensure the cursor position used is within the grid. This means that when deleting the last row/column it'll move to the previous row/column instead of the first cell in the table.
* Update snooker to attempt to find a different cursor position that's editable if the one provided by the operation isn't valid/editable.
Pre-checks:
Review:
=> TINY-7695: Fixed table operations placing the cursor in an invalid position

modules/tinymce/src/themes/silver/main/ts/ui/context/ContextToolbar.ts, modules/tinymce/src/themes/silver/main/ts/ui/context/ContextToolbarAnchor.ts, modules/tinymce/src/themes/silver/main/ts/ui/context/ContextToolbarBounds.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/contexttoolbar/ContextToolbarIframePositionTest.ts
Related Ticket: TINY-7739
So there were 3 parts to this in the end:
1. There was an issue with using the wrong anchor position lookup when trying to see if the toolbar should hide. This was because it was using the element position (e.g. the `p` element) for selection toolbars which isn't the same as the selection and in most cases was off by 1px. That off by 1 is what caused the "north" layout to say it didn't fit as part of it was deemed to be offscreen.
2. The was an issue with the overlap detection logic as if it was the same value (e.g. the anchor was `y` 400 and the `bottom` bounds was 400) than nothing was visible so it should have been hidden. It also had an issue when one of the bounds had a height of zero.
3. I've also improved the context toolbar layout …
=> TINY-7739: Fix inset layouts incorrectly used for selection context toolbars

modules/snooker/src/main/ts/ephox/snooker/api/TableOperations.ts, modules/tinymce/src/plugins/table/test/ts/browser/TableSectionApiTest.ts
Related Ticket: TINY-6666
Fixed the cell type operations in snooker only working on the first cell in a column due to incorrectly using `uniqueColumns` to filter out other cells in the same column (was a copy/paste fail on my part in the earlier PRs).
Pre-checks:
Review:
=> TINY-6666: Fixed `mceTableCellType` not updating multiple cells in the same column

modules/darwin/CHANGELOG.md, modules/darwin/src/main/ts/ephox/darwin/queries/CellOpSelection.ts, modules/darwin/src/main/ts/ephox/darwin/selection/SelectionTypes.ts, modules/darwin/src/main/ts/ephox/darwin/selection/Selections.ts, modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/table/main/ts/Plugin.ts, modules/tinymce/src/plugins/table/main/ts/actions/Clipboard.ts, modules/tinymce/src/plugins/table/main/ts/api/Commands.ts, modules/tinymce/src/plugins/table/main/ts/selection/TableSelection.ts, modules/tinymce/src/plugins/table/main/ts/ui/CellDialog.ts, modules/tinymce/src/plugins/table/main/ts/ui/UiUtils.ts, modules/tinymce/src/plugins/table/test/ts/browser/ClipboardTest.ts
Related Ticket: TINY-7485
The paste logic incorrectly looked up the cell selection as it only ever considered the native selection, not the fake selection. So this swaps it over to use the proper way to lookup the selection in for the tables plugin. I also cleaned up a little by using the `SugarNode.isTag` function.
Additionally, I discovered that `CellOpSelection` was returning a `caption` element in some cases which was incorrect, so I've corrected the types in Darwin and feed that through. This hadn't caused an issue previously thankfully because the only place it's used is for `TableSelection` and `RunOperation`. The former had an additional guard to workaround this bug and the latter does `TableLookup.cell` on the single element passed, which in turn returns …
=> TINY-7485: Fixed pasting into the wrong cell when multiple cells were selected

modules/tinymce/src/plugins/template/main/ts/ui/Dialog.ts
Related Ticket: TINY-7781
* Ensure the dialog uses the `mceInsertTemplate` command rather than inserting directly using internal modules.
Pre-checks:
Review:
=> TINY-7781: Ensure the template dialog inserts content via the `mceInsertTemplate` command

modules/tinymce/src/plugins/table/main/ts/queries/TabContext.ts, modules/tinymce/src/plugins/table/test/ts/browser/KeyboardCellNavigationTest.ts
Related Ticket: TINY-7705
This fixes an edge case I'd missed in local testing and only became obvious when using Advanced Tables. When the new row is inserted, the cells maybe changed to non-editable so we can't just find the first position and need to walk again. So this updates that logic to walk forward from the last cell to the next viable position.
Pre-checks:
Review:
=> TINY-7705: Fixed edge case for table tab navigation

modules/oxide/src/less/theme/components/collection/collection.less, modules/oxide/src/less/theme/components/toolbar/toolbar.less, modules/oxide/src/less/theme/globals/global.less, modules/tinymce/CHANGELOG.md, modules/tinymce/src/themes/silver/main/ts/ui/button/ButtonSlices.ts, modules/tinymce/src/themes/silver/main/ts/ui/dialog/SelectBox.ts, modules/tinymce/src/themes/silver/main/ts/ui/dialog/SizeInput.ts, modules/tinymce/src/themes/silver/main/ts/ui/dialog/UrlInput.ts, modules/tinymce/src/themes/silver/main/ts/ui/dropdown/CommonDropdown.ts, modules/tinymce/src/themes/silver/main/ts/ui/general/Checkbox.ts, modules/tinymce/src/themes/silver/main/ts/ui/general/Notification.ts, modules/tinymce/src/themes/silver/main/ts/ui/icons/Icons.ts, modules/tinymce/src/themes/silver/main/ts/ui/menus/item/ItemClasses.ts, modules/tinymce/src/themes/silver/main/ts/ui/menus/item/build/CardMenuItem.ts, modules/tinymce/src/themes/silver/main/ts/ui/menus/item/structure/ItemSlices.ts, modules/tinymce/src/themes/silver/main/ts/ui/menus/item/structure/ItemStructure.ts, modules/tinymce/src/themes/silver/main/ts/ui/statusbar/ResizeHandle.ts, modules/tinymce/src/themes/silver/main/ts/ui/toolbar/button/ButtonClasses.ts, modules/tinymce/src/themes/silver/main/ts/ui/toolbar/button/ToolbarButtons.ts, modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialogHeader.ts, modules/tinymce/src/themes/silver/test/ts/browser/icons/IconsTest.ts
Related Ticket: TINY-7782
This reworks how icons are rendered in Silver, so that they all go via the same path (`Icons.render` in most cases). This also ensures that the RTL logic applies to all icons being rendered, as previously a number we not being transformed, etc... correctly. The changes are as follows:
- Changed how the `Icons.render` function works so that it accepts the icon name, not the icon HTML, etc... and also added an equivalent `renderFirst` function.
- Changed the class being used to transform/rotate select icons in RTL mode. It will now add a generic `tox-icon--flip` class instead.
- Improved the icon lookup logic to automatically use an icon with the same name that includes a `-rtl` suffix (e.g. `checklist-rtl`)
- Updated all places that …
=> TINY-7782: Rework how icons are rendered

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/html/Base64Uris.ts, modules/tinymce/src/core/test/ts/atomic/html/Base64UrisTest.ts
Allow spaces and line breaks inside base64 encoded data of images.
#7093
* Change regular expressions to alloow spaces and line breaks in data Uri
Pre-checks:
Review:
Fixes #7093
=> Fix #7093: base64 encoded images are not displayed if data value contains line breaks or spaces

modules/tinymce/Gruntfile.js
* Removed the `ie8` compatibility configuration of UglifyJS as we haven't supported IE 8 since 4.5.x.
* Enable a second compression pass to further reduce the bundle size. This does add a bit of time to the build stage. Locally, it was ~13s as it went from 157s -> 170s.
Both of the above changes helps reduce the size of the bundle by about 8kb for the minified `tinymce.js` file.
Pre-checks:
Review:
=> Remove UglifyJS ie8 compatibility configuration and enable 2 compression passes

modules/jax/CHANGELOG.md, modules/jax/src/main/ts/ephox/jax/core/Http.ts, modules/jax/src/main/ts/ephox/jax/core/HttpData.ts, modules/jax/src/main/ts/ephox/jax/core/HttpError.ts, modules/jax/src/main/ts/ephox/jax/core/HttpJwt.ts, modules/jax/src/main/ts/ephox/jax/core/HttpTypes.ts, modules/jax/src/main/ts/ephox/jax/core/ResponseError.ts, modules/jax/src/main/ts/ephox/jax/core/ResponseSuccess.ts, modules/jax/src/test/ts/browser/AjaxTest.ts, modules/jax/src/test/ts/browser/HttpJwtTest.ts
* Change HttpError responseText type from `string` to `ResponseTypeMap[T]` - `HttpError<T extends keyof ResponseTypeMap>`
Pre-checks:
Review:
=> TINY-7721: Fix broken typescript types in Jax

package.json, yarn.lock
Upgraded the following dev dependencies:
* `@ephox/bedrock-server` 11.3.0 -> 11.3.3
* `@ephox/bedrock-client` 11.3.0 -> 11.3.2
* `@tinymce/eslint-plugin` 1.9.1 -> 1.9.2
* `@tinymce/dispute` 1.0.9 -> 1.0.10
* `tslib` 2.3.0 -> 2.3.1
Note: I only changed the minimum version of bedrock, since it's the only thing that actually needs the minimum version bumped.
Pre-checks:
Review:
=> Updated dev dependencies to pull in bedrock fix

modules/tinymce/CHANGELOG.md, modules/tinymce/src/themes/silver/main/ts/ui/icons/Icons.ts
Related Ticket: TINY-7851
* Added the `paste-column-after` and `paste-column-before` icons to the list that needs to be flipped in RTL mode. This was missed when they were added in 5.4.
Pre-checks:
Review:
=> TINY-7851: Fixed the table paste column before/after icons not flipped in RTL mode

modules/sand/CHANGELOG.md, modules/sand/src/main/ts/ephox/sand/api/PlatformDetection.ts, modules/sand/src/main/ts/ephox/sand/core/Browser.ts, modules/sand/src/main/ts/ephox/sand/core/OperatingSystem.ts, modules/sand/src/main/ts/ephox/sand/core/PlatformDetection.ts, modules/sand/src/main/ts/ephox/sand/detect/UaData.ts, modules/sand/src/main/ts/ephox/sand/detect/UaString.ts, modules/sand/src/main/ts/ephox/sand/detect/Version.ts, modules/sand/src/main/ts/ephox/sand/info/PlatformInfo.ts, modules/sand/src/main/ts/ephox/sand/info/UaInfo.ts, modules/sand/src/test/ts/atomic/core/BrowserTest.ts, modules/sand/src/test/ts/atomic/core/DeviceTypeTest.ts, modules/tinymce/CHANGELOG.md
Related Ticket: TINY-7785
* Use new userAgentData API to detect browser type and major version in Sand
Pre-checks:
Review:
=> TINY-7785: Use `navigator.userAgentData` for browser detection when supported

modules/darwin/CHANGELOG.md, modules/darwin/src/main/ts/ephox/darwin/api/WindowBridge.ts, modules/darwin/src/main/ts/ephox/darwin/mouse/MouseSelection.ts, modules/sugar/src/main/ts/ephox/sugar/api/selection/WindowSelection.ts, modules/sugar/src/main/ts/ephox/sugar/selection/core/NativeRange.ts, modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/table/test/ts/browser/FakeSelectionTest.ts, modules/tinymce/src/plugins/table/test/ts/module/test/TableTestUtils.ts
Related Ticket: TINY-7724
* Update MouseSelection logic in Darwin to add the selected attributes when a single CEF cell is clicked
Pre-checks:
Review:
=> TINY-7724: Clicking on a noneditable table cell did not show a visual selection

modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/autolink/main/ts/api/Settings.ts, modules/tinymce/src/plugins/autolink/main/ts/core/Keys.ts, modules/tinymce/src/plugins/autolink/test/ts/browser/AutoLinkPluginTest.ts
Related Ticket: TINY-7714
This builds on the initial version @HAFRMO did in https://github.com/tinymce/tinymce/pull/7107, however it makes it use the Polaris link regex directly. Note that we can't use the `autolink` regex, as the autolink plugin does the punctuation detection itself before even using the regex (which it needs to due to adjusting the range). On that note, I've also updated the punctuation detection a little to handle additional common cases as it previously only handled a full stop (I didn't want to go too far on this since it's somewhat out of scope, but it was something that was obviously broken/different so I did something minimal).
Pre-checks:
Review:
=> TINY-7714: Updated the autolink plugin to use the Polaris link regex

modules/tinymce/src/plugins/table/main/ts/api/Settings.ts, modules/tinymce/src/plugins/table/main/ts/ui/Buttons.ts, modules/tinymce/src/plugins/table/main/ts/ui/CellDialogGeneralTab.ts, modules/tinymce/src/plugins/table/main/ts/ui/DialogAdvancedTab.ts, modules/tinymce/src/plugins/table/main/ts/ui/Helpers.ts, modules/tinymce/src/plugins/table/main/ts/ui/MenuItems.ts, modules/tinymce/src/plugins/table/main/ts/ui/RowDialogGeneralTab.ts, modules/tinymce/src/plugins/table/main/ts/ui/TableDialog.ts, modules/tinymce/src/plugins/table/main/ts/ui/UiUtils.ts, modules/tinymce/src/plugins/table/test/ts/browser/ui/TableBorderStyleTest.ts, modules/tinymce/src/plugins/table/test/ts/browser/ui/TableClassListButtonsTest.ts
Related Ticket: TINY-7853
* Fixed a typo in the `tablecellclass` menu item name.
* Fixed the toolbar buttons not working with nested class lists.
* Fixed the border cell style toolbar/dialog not working and throwing errors when using `title` in the `table_border_styles` setting.
* **Note:** Remember that `title` is the documented way to use this and the documented way for all other settings, so it shouldn't have been requiring `text` previously. 
* Moved setting -> dialog list conversion logic to `UiUtils`.
* Moved color menu item rendering from `Settings` -> `UiUtils`
* General cleanup given changes above.
Pre-checks:
Review:
=> TINY-7853: Fixed the new table buttons/settings not using the right properties or not working with nested menus

modules/tinymce/src/core/test/ts/browser/delete/MediaDeleteTest.ts, modules/tinymce/src/core/test/ts/browser/keyboard/MediaNavigationTest.ts
Related Ticket: TINY-7871
Okay, after investigating more it seems we've stumbled upon a Safari bug on newer versions. It's causing things to lockup when providing an invalid object, so just disable the relevant test on Safari for now until we can investigate the root cause.
Pre-checks:
Review:
=> TINY-7871: Disable the media object tests on Safari

modules/tinymce/src/core/test/ts/browser/keyboard/ArrowKeysCefTest.ts, modules/tinymce/src/themes/silver/test/ts/module/StickyHeaderStep.ts
Related Ticket: TINY-7873
* Changed the text offset for `ArrowKeysCefTest` to account for Apple M1 devices rendering text differently. This in turn caused the cef navigation logic to not run due to the content above no longer being a CEF element.
* Disabled the Sticky Header tests on Firefox 91, as there is a legitimate bug there that's causing the header to not show in this specific case. We have the mentioned Jira to investigate and fix it for 5.9.1.
Review:
=> TINY-7873: Adjust tests to account for changes in ARM Firefox 91

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/delete/CefDelete.ts, modules/tinymce/src/core/main/ts/delete/TableDelete.ts, modules/tinymce/src/core/test/ts/browser/delete/TableDeleteTest.ts
Related Ticket: TINY-7891
Fixed how noneditable cells are deleted, as removing the `td` element leads to a corrupted table. So instead, we clear all the content and reset the editable state to make it as close to what happens with other cef elements as possible.
Pre-checks:
Review:
=> TINY-7891: Fixed table corruption when deleting cef cells

modules/tinymce/src/core/test/ts/browser/commands/LineHeightTest.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/ChoiceControls.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/core/ChoiceControlsTest.ts
Related Ticket: TINY-7713
* Don't let two submenus be active at once
Pre-checks:
Review:
=> TINY-7713: Fix computed line height bug

modules/darwin/src/main/ts/ephox/darwin/mouse/MouseSelection.ts, modules/sugar/src/main/ts/ephox/sugar/api/properties/ContentEditable.ts, modules/tinymce/src/plugins/table/test/ts/browser/FakeSelectionTest.ts
Related Ticket: TINY-7724
* Try and improve the issue where the cursor would be visible despite a noneditable cell being selected
* Fix issue where noneditable cell would be selected if a noneditable child was selected
Pre-checks:
Review:
=> TINY-7724: Temporarily improve lingering cursor issue

modules/tinymce/CHANGELOG.md
Related Ticket: DOC-852
* Fixed some changelogs being in the incorrect groups
* Reordered changelogs to keep similar items together
* Applied feedback from Tyler and Millie on changelog wording
Review:
=> DOC-865: Rework and reorder changelog entries to group similar items

modules/tinymce/src/core/demo/ts/demo/FullDemo.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/ChoiceControls.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/core/ChoiceControlsTest.ts
Related Ticket: TINY-7713 (again)
* Nested menus weren't able to cope with being opened twice without the parent menu being closed in-between
Pre-checks:
Review:
=> TINY-7713: Fix a bug found in QA

package.json, yarn.lock
Related Ticket: TINY-7918
* Upgrade to Bedrock 11.5.0 to get Chrome/Edge performance improvements
Pre-checks:
Review:
=> TINY-7918: Upgrade to Bedrock 11.5.0 to get Chrome/Edge performance improvements

modules/tinymce/src/core/test/ts/browser/WindowManagerTest.ts, modules/tinymce/src/plugins/link/test/ts/browser/LinkDialogOverrideTest.ts
Related Ticket: TINY-7738
* Add regression test for support dialog validation workaround
Pre-checks:
Review:
=> TINY-7738: Add regression test for support dialog validation workaround

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/content/GetContentImpl.ts, modules/tinymce/src/core/main/ts/content/SetContentImpl.ts, modules/tinymce/src/core/main/ts/selection/GetSelectionContentImpl.ts, modules/tinymce/src/core/main/ts/selection/SetSelectionContent.ts, modules/tinymce/src/core/test/ts/browser/content/EditorContentTest.ts
Related Ticket: TINY-7956
Fixes an issue where the default args weren't set if `no_events: true` was passed in the get/set content APIs. This in turn also caused an exception since when setting the content the `content` variable ended up being `undefined`.
Pre-checks:
Review:
Fixes https://github.com/tinymce/tinymce-react/issues/283
=> TINY-7956: Fixed an exception getting thrown when disabling events and setting content

modules/mcagar/CHANGELOG.md, modules/mcagar/src/main/ts/ephox/mcagar/api/bdd/TinyHooks.ts, modules/tinymce/src/plugins/table/main/ts/Plugin.ts, modules/tinymce/src/plugins/table/main/ts/actions/Clipboard.ts
Related Ticket: TINY-7957
* Fixes the module setup logic running before TinyMCE was available.
* Fixes an unused argument that was missed in https://github.com/tinymce/tinymce/pull/7162 and ESLint was printing warnings about.
Pre-checks:
Review:
=> TINY-7957: Fixed McAgar setting up modules before TinyMCE was available in TinyHooks

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/dom/ControlSelection.ts
Related Ticket: TINY-7854
* Super minor fix, not critical at all.
* All of the image resize temporary elements include `data-mce-bogus=all`, except the backdrop. As a result the RTC mutation observer needs to include a special case for the backdrop element. This adds a small overhead to every document mutation.
* Adding this attribute is also more consistent with other elements used for resize.
Pre-checks:
Review:
=> TINY-7854: Add bogus attribute to image resize backdrop

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/delete/TableDelete.ts, modules/tinymce/src/core/test/ts/browser/delete/TableDeleteTest.ts
**Related Ticket:** TINY-7596
When performing delete operations on selections that contain tables, we now perform a custom delete operation on the cells in the selection that _might_ have only part of their contents selected:
1. If the start of the selection is outside a table and the end of the selection is in a table, then the last cell in the selection
2. If the start of the selection is inside a table and the end is outside a table, then the first cell in that selection
3. If the start of the selection is in a table and the end of the selection is in another table, then the first cell of the selection in the first table and the last cell of the selection in the last table
This means we create a new `Range` inside the cell, delete that, and if the cell still …
=> TINY-7596: Fix all contents of cell being deleted when only part of the contents were selected

modules/snooker/CHANGELOG.md, modules/snooker/src/main/ts/ephox/snooker/api/Sizes.ts, modules/snooker/src/main/ts/ephox/snooker/api/TableConversions.ts, modules/snooker/src/main/ts/ephox/snooker/api/TableSize.ts, modules/snooker/src/main/ts/ephox/snooker/resize/ColumnSizes.ts, modules/snooker/src/main/ts/ephox/snooker/resize/Sizes.ts, modules/snooker/src/main/ts/ephox/snooker/util/CellUtils.ts, modules/snooker/src/test/ts/browser/ResizeTest.ts, modules/snooker/src/test/ts/browser/TableAdjustmentsTest.ts, modules/snooker/src/test/ts/browser/TableConversionsTest.ts, modules/snooker/src/test/ts/browser/TableSizeTest.ts, modules/snooker/src/test/ts/browser/TableSizesTest.ts, modules/snooker/src/test/ts/browser/resize/ColumnSizesTest.ts, modules/sugar/CHANGELOG.md, modules/sugar/src/main/ts/ephox/sugar/api/search/Traverse.ts, modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/table/main/ts/actions/EnforceUnit.ts, modules/tinymce/src/plugins/table/main/ts/actions/InsertTable.ts, modules/tinymce/src/plugins/table/main/ts/actions/ResizeHandler.ts, modules/tinymce/src/plugins/table/main/ts/api/Commands.ts, modules/tinymce/src/plugins/table/main/ts/queries/TableSize.ts, modules/tinymce/src/plugins/table/test/ts/browser/ModifyColumnsTableResizeTest.ts, modules/tinymce/src/plugins/table/test/ts/browser/command/MergeCellCommandTest.ts, versions.txt
Related Ticket: TINY-7731
* Update snooker width lookups to always use the actual width instead of the specified width where possible (table and cell widths/heights).
* This is the core of the fix, as the root issue is that we always used the raw widths which may not have been accurate if the content caused the cell to grow.
* Use the `col` element offset width where safe to do so.
* Converted a number of tests to use BDD style tests.
Pre-checks:
Review:
=> TINY-7731: Fixed table resizing when the contents of a cell has caused it's size to change

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/SelectionOverrides.ts, modules/tinymce/src/core/test/ts/browser/SelectionOverridesTest.ts
Related Ticket: TINY-7062
* Focus body after setting range. Chrome would scroll the editor when calling focus before setting the range when clicking from inside an editable element to beside a non-editable element
Pre-checks:
Review:
Fixes #6456
=> TINY-7062: Fix editor sometimes scrolling when clicking beside non-editable element

modules/oxide/src/less/theme/components/fullscreen/fullscreen.less, modules/sugar/CHANGELOG.md, modules/sugar/src/main/ts/ephox/sugar/api/view/WindowVisualViewport.ts, modules/tinymce/CHANGELOG.md, modules/tinymce/src/themes/silver/test/ts/module/StickyHeaderStep.ts
Related Ticket: TINY-7873
* Also rearranges some CSS after a discussion with @lnewson 
Pre-checks:
Review:
=> TINY-7873: Disable window.visualViewport in Firefox to fix sticky toolbar bug in fullscreen mode

modules/tinymce/src/core/main/ts/delete/TableDelete.ts, modules/tinymce/src/core/test/ts/browser/delete/TableDeleteTest.ts
Related Ticket: TINY-7596 (Part 2)
Ensures we don't clean out nodes that aren't empty
Pre-checks:
Review:
=> TINY-7596: Fix entire nodes within cells being cleaned when they still contain content

modules/snooker/CHANGELOG.md, modules/snooker/src/main/ts/ephox/snooker/api/Generators.ts, modules/snooker/src/main/ts/ephox/snooker/api/TableOperations.ts, modules/snooker/src/main/ts/ephox/snooker/api/TableSection.ts, modules/snooker/src/main/ts/ephox/snooker/lookup/Type.ts, modules/snooker/src/main/ts/ephox/snooker/operate/TransformOperations.ts, modules/snooker/src/test/ts/browser/HeaderOperationsTest.ts, modules/snooker/src/test/ts/browser/MergeOperationsTest.ts, modules/snooker/src/test/ts/browser/operate/TransformOperationsTest.ts, modules/sugar/CHANGELOG.md, modules/sugar/src/main/ts/ephox/sugar/api/properties/Attribute.ts, modules/sugar/src/test/ts/browser/AttributeTest.ts, modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/table/test/ts/browser/SwitchTableSectionTest.ts, modules/tinymce/src/plugins/table/test/ts/browser/TableSectionApiTest.ts, modules/tinymce/src/plugins/table/test/ts/browser/TwoCellsSelectionTest.ts, modules/tinymce/src/plugins/table/test/ts/browser/ui/TableRowDialogTest.ts, modules/tinymce/src/plugins/table/test/ts/browser/ui/TableRowHeaderUiTest.ts
Related Ticket: TINY-7709
* Added new `setOptions` function to `Attribute` to mirror the `Css.setOptions` function.
* Updated the `TransformOperations` logic to fix issues where the cell may still have been a header when making a column/row a normal column/row.
* Reworked how scopes are created, as they needed more complex logic than what could be done via a generator. It also needed updating when not generating a new cell with these changes.
* Ensure `scope` is never set on `td` elements as it's deprecated/no longer recommended.
Pre-checks:
Review:
=> TINY-7709: Fixed row/column header operations incorrectly converting `th` to `td`

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/content/InsertContentImpl.ts, modules/tinymce/src/core/test/ts/browser/content/InsertContentTest.ts
Related Ticket: TINY-7842
* Check for content editable true root elements when inserting content. Previously we would only look for `ce=false` parents up the tree without taking into account any `ce=true` that were found along the way
Pre-checks:
Review:
=> TINY-7842: Check for content editable true root elements when inserting content

modules/alloy/CHANGELOG.md, modules/alloy/src/main/ts/ephox/alloy/api/component/CompBehaviours.ts, modules/alloy/src/main/ts/ephox/alloy/api/component/SketchBehaviours.ts, modules/alloy/src/main/ts/ephox/alloy/behaviour/common/Behaviour.ts, modules/alloy/src/main/ts/ephox/alloy/behaviour/common/BehaviourTypes.ts, modules/alloy/src/test/ts/browser/ui/dropdown/SplitDropdownTest.ts, modules/tinymce/CHANGELOG.md
Related Ticket: TINY-7879
* Fixed an issue whereby the sketcher behaviours were merged in the incorrect order (this was introduced in 1dff21202ff097180445084a8fccdf831828ae7f when converting from `Merger.merge`). This caused nested focusable/`tabindex="-1"` elements in split toolbar buttons.
* Fixed some incorrect types and did some simplification.
Pre-checks:
Review:
=> TINY-7879: Fixed sketcher behaviours augmenting in the wrong order

modules/tinymce/src/plugins/help/main/ts/data/PluginUrls.ts, modules/tinymce/src/plugins/help/main/ts/ui/PluginsTab.ts
Related Ticket: TINY-7986
* Fixed missing RTC and Quickbars metadata causing plain text to be shown.
* Cleaned up the Premium Plugins list as it was duplicated and easy to miss updating both.
Pre-checks:
Review:
=> TINY-7986: Fixed missing quickbars and rtc help url/name mapping

modules/tinymce/src/plugins/wordcount/test/ts/browser/PluginTest.ts, modules/tinymce/src/plugins/wordcount/test/ts/browser/api/ApiTest.ts, modules/tinymce/src/plugins/wordcount/test/ts/browser/core/GetTextTest.ts
Related Ticket: TINY-6970
* Converts the `wordcount` plugin to use BDD style tests
Pre-checks:
Review:
=> TINY-6870: Switch wordcount plugin to use BDD style tests

modules/oxide/src/less/theme/content/resize-handles/resize-handle.less, modules/oxide/src/less/theme/globals/global-variables.less, modules/tinymce/CHANGELOG.md
Related Ticket: TINY-3263
* Fixes the resize handle z-index as it was much higher than the sink z-index which meant it rendered above anything in the sink  (e.g. dialogs and menus) in inline mode
Pre-checks:
Review:
=> TINY-3263: Fixed resize handles rendering above dialogs/menus in inline mode

build.properties, modules/acid/CHANGELOG.md, modules/agar/CHANGELOG.md, modules/alloy/CHANGELOG.md, modules/boss/CHANGELOG.md, modules/boulder/CHANGELOG.md, modules/bridge/CHANGELOG.md, modules/darwin/CHANGELOG.md, modules/dragster/CHANGELOG.md, modules/imagetools/CHANGELOG.md, modules/jax/CHANGELOG.md, modules/katamari-assertions/CHANGELOG.md, modules/katamari/CHANGELOG.md, modules/mcagar/CHANGELOG.md, modules/phoenix/CHANGELOG.md, modules/polaris/CHANGELOG.md, modules/porkbun/CHANGELOG.md, modules/robin/CHANGELOG.md, modules/sand/CHANGELOG.md, modules/snooker/CHANGELOG.md, modules/sugar/CHANGELOG.md, modules/tinymce/CHANGELOG.md, modules/tinymce/package.json
Related Ticket: Get a branch ready for us to have somewhere to put our 6.0 work
* Added a placeholder release to each changelog, so we can tell 5.x work apart from 6.0 work and avoid git conflicts
* Update `build.properties` so that Jenkins knows which branch to look at when doing merges and tests
* Updated `modules/tinymce/package.json` to the new version
Pre-checks:
Review:
=> Prepare branch for 6.0 work

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/fmt/ExpandRange.ts, modules/tinymce/src/core/test/ts/browser/FormatterApplyTest.ts, modules/tinymce/src/core/test/ts/browser/FormatterRemoveTest.ts
Related Ticket: TINY-8036
Fixes a regression introduced in https://github.com/tinymce/tinymce/pull/7002 whereby block wrapper formats didn't expand out to the parent block correctly. This in turn caused blockquotes to fail to apply/remove correctly when there were multiple words.
Pre-checks:
Review:
=> TINY-8036: Fixed a regression in the format expand range logic when using block formats with a wrapper

modules/alloy/CHANGELOG.md, modules/alloy/src/main/ts/ephox/alloy/behaviour/docking/DockingApis.ts
Related Ticket: TINY-7894
This was a bug found when trying to get docking working with notifications. I'm still not sure exactly what triggers this case, but it makes sense that the docking state can end up in a bad state as there are 3 possible morph modes, but only 2 possible states. So if we happen to end up morphing to between the 2 modes that are undocked, then the state could have ended up in a bad state. So this resolves that by explicitly setting the state based on how we're morphing.
Pre-checks:
Review:
=> TINY-7894: Fixed docking state being set incorrectly in some edge cases

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/NotificationManager.ts, modules/tinymce/src/themes/silver/main/ts/alien/NotificationManagerImpl.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/NotificationManagerImplTest.ts
Related Ticket: TINY-7894
* Fixes an issue where the notifications could be incorrectly positioned on initial render.
* Fixes an issue where notifications were rendered when the editor was not visible in the window.
* Did a little bit of cleanup in the notification manager logic, as it was doing some unnecessary things (stuff that looks to have been required in 4.x, but not in 5.x).
Pre-checks:
Review:
=> TINY-7894: Fixed a number of notification positioning issues

modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/image/main/ts/core/ImageSelection.ts, modules/tinymce/src/plugins/image/main/ts/ui/Buttons.ts, modules/tinymce/src/plugins/image/test/ts/browser/ImagePluginTest.ts, modules/tinymce/src/plugins/media/main/ts/core/Selection.ts, modules/tinymce/src/plugins/media/main/ts/ui/Buttons.ts, modules/tinymce/src/plugins/media/main/ts/ui/Dialog.ts, modules/tinymce/src/plugins/media/test/ts/browser/MediaPluginSanityTest.ts
Related Ticket: TINY-3463
This ensures the initial active state is set for the `image` and `media` toolbar buttons, as since this wasn't done the button didn't show as active when in a toolbar drawer or context toolbar.
Note: The associated Jira is about auditing and fixing all cases, but for now this just fixes the immediate case identified in TINY-3463.
Pre-checks:
Review:
=> TINY-3463: Fixed the `image` and `media` toolbar buttons showing the incorrect active state in some cases

modules/polaris/CHANGELOG.md, modules/polaris/src/main/ts/ephox/polaris/pattern/Chars.ts, modules/polaris/src/test/ts/atomic/pattern/CharsTest.ts, modules/robin/CHANGELOG.md, modules/robin/src/main/ts/ephox/robin/api/general/TextSearch.ts, modules/robin/src/test/ts/browser/zone/EntityTest.ts, modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/wordcount/test/ts/browser/PluginTest.ts
Related Ticket: TINY-7908 (take 2)
* Add soft-hyphens to the list of accepted word characters in Polaris
* This affects Robin's zone-walker related APIs
* This also affects the word count plugin
Pre-checks:
Review:
=> TINY-7908: SHY entities should not be treated as word-breaks

modules/tinymce/CHANGELOG.md
Related Ticket: TINY-7908
* Oops, turns out this wasn't fixed in this release, it already worked
Pre-checks:
Review:
=> TINY-7908: Revert incorrect changelog entry

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/dom/SelectorChanged.ts, modules/tinymce/src/core/test/ts/browser/dom/SelectionTest.ts
Related Ticket: TINY-3463
This is a followup for an issue @ltrouton found when QAing that turned out to be an existing core bug whereby the `selectorChanged` API doesn't setup the state correctly if the selector already matches the current selection.
Pre-checks:
Review:
=> TINY-3463: Fixed the `selection.selectorChanged` API not firing correctly if the selector matched the current selection when registered

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/Editor.ts, modules/tinymce/src/core/main/ts/api/EditorManager.ts, modules/tinymce/src/core/main/ts/api/Env.ts, modules/tinymce/src/core/main/ts/api/dom/DOMUtils.ts, modules/tinymce/src/core/main/ts/api/dom/Sizzle.ts
Related Ticket: TINY-8063
Mark `fileApi`, `Sizzle` and `$` (`DomQuery` alias) as deprecated
Pre-checks:
Review:
=> TINY-8063: Mark several more APIs as deprecated

modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/media/main/ts/core/Nodes.ts, modules/tinymce/src/plugins/media/test/ts/browser/LiveEmbedNodeTest.ts
Related Ticket: TINY-7674
* Fixes an issue where media live embeds wouldn't play correctly when they had child `<source>` nodes. This was caused by not unescaping the attribute value that stores the real HTML when trying to process it.
Pre-checks:
Review:
Fixes #6673
=> TINY-7674: Fixed media live embed video and audio elements were unable to be played in some cases

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/Deprecations.ts, modules/tinymce/src/core/main/ts/EditorSettings.ts, modules/tinymce/src/core/main/ts/api/SettingsTypes.ts, modules/tinymce/src/plugins/bbcode/main/ts/Plugin.ts, modules/tinymce/src/plugins/colorpicker/main/ts/Plugin.ts, modules/tinymce/src/plugins/contextmenu/main/ts/Plugin.ts, modules/tinymce/src/plugins/fullpage/main/ts/Plugin.ts, modules/tinymce/src/plugins/legacyoutput/main/ts/Plugin.ts, modules/tinymce/src/plugins/spellchecker/main/ts/Plugin.ts, modules/tinymce/src/plugins/textcolor/main/ts/Plugin.ts
Related Ticket:  TINY-8049
This reworks the deprecation messaging to be a little less intrusive by logging a single console warning with the various plugins/settings being used that have been deprecated and that will be removed.
Note: The "placeholder" plugins don't use `Fun.noop` as it needs to be a separate function since it's used as a class constructor.
Pre-checks:
Review:
=> TINY-8049: Rework deprecation messaging to use a single console warning and to include settings

modules/tinymce/src/plugins/insertdatetime/main/ts/api/Commands.ts, modules/tinymce/src/plugins/insertdatetime/main/ts/ui/Buttons.ts
Related Ticket: TINY-8058
* Ensure insertdatetime buttons and menus use the editor commands
Pre-checks:
Review:
=> TINY-8058: Ensure insertdatetime buttons and menus use the editor commands

modules/katamari/CHANGELOG.md, modules/katamari/src/main/ts/ephox/katamari/api/Strings.ts, modules/katamari/src/test/ts/atomic/api/str/ToFloatTest.ts, modules/katamari/src/test/ts/atomic/api/str/ToIntTest.ts, modules/snooker/CHANGELOG.md, modules/snooker/src/main/ts/ephox/snooker/resize/ColumnSizes.ts, modules/snooker/src/main/ts/ephox/snooker/resize/RuntimeSize.ts, modules/snooker/src/main/ts/ephox/snooker/resize/Sizes.ts, modules/snooker/src/test/ts/browser/resize/ColumnSizesTest.ts, modules/sugar/CHANGELOG.md, modules/sugar/src/main/ts/ephox/sugar/api/view/Height.ts, modules/sugar/src/main/ts/ephox/sugar/api/view/Width.ts, modules/sugar/src/main/ts/ephox/sugar/impl/RuntimeSize.ts, modules/sugar/src/test/ts/browser/DimensionTest.ts, modules/sugar/src/test/ts/browser/impl/RuntimeSizeTest.ts, modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/table/main/ts/api/Settings.ts, modules/tinymce/src/plugins/table/test/ts/browser/InsertTableWidthsTest.ts, versions.txt
Related Ticket: TINY-7991
Katamari:
* Added new helper functions to convert a string to an integer or float.
Sugar:
* Moved `RuntimeSize` logic from Snooker to Sugar (this was done as I needed the "inner" size to fix the fixed width table size).
* Added new `getInner()` and `getRuntime()` functions to `Width` and `Height` (this just exposes the `RuntimeSize` logic).
Snooker:
* Updated the sizing logic in `Sizes` to use the inner/content width for the parent element when calculating the percentage widths.
* Changed the is `col` safe logic to use an allow list and removed Safari as it can return 0px for the col element in some cases.
Note: The snooker fix to `Sizes.ts` it the core of this fix, the rest were largely side-effects to be able to get the inner/content …
=> TINY-7991: Fixed issues with table sizing when the parent element had padding

modules/darwin/CHANGELOG.md, modules/darwin/src/main/ts/ephox/darwin/api/InputHandlers.ts, modules/darwin/src/main/ts/ephox/darwin/api/SelectionAnnotation.ts, modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/table/test/ts/browser/FakeSelectionTest.ts
Related Ticket: TINY-8053
* Update darwin logic to clear firstSelectedAttr and lastSelectedAttr even if the selectedAttr is not present on the table cells. This can occur from SelectionOverrides removing the selectedAttr on the noneditable cell before the darwin annotation clearing logic runs
Pre-checks:
Review:
=> TINY-8053: Fix 'data-mce-selected' attrs not removed from noneditable cell

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/EditorUpload.ts, modules/tinymce/src/core/test/ts/browser/EditorUploadTest.ts
Related Ticket: TINY-7735
* Add `removed` boolean flag to UploadResult. If some image failed to upload this flag signals to the RTC plugin to remove it from alt-model.
Pre-checks:
Review:
=> TINY-7735: Add 'removed' flag to UploadResult

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/Settings.ts, modules/tinymce/src/core/main/ts/init/InitIframe.ts, modules/tinymce/src/core/test/ts/browser/init/InitIframeAriaTextTest.ts
Related Ticket: TINY-8171
As discussed at stand up, this moves the iframe aria text to the body since a number of screen readers don't read the iframe title anymore. However, the iframe itself still must have a title, so we're leaving that as `Rich Text Area`. This means `Rich Text Area` won't have translations, but it's the lesser of two bad situations so we're pushing ahead.
Pre-checks:
Review:
=> TINY-8171: Moved the iframe title to the body as VoiceOver and Chrome Vox wouldn't read it when on the iframe directly

modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/wordcount/main/ts/core/Count.ts, modules/tinymce/src/plugins/wordcount/test/ts/browser/PluginTest.ts
Related Ticket: TINY-7484
Removes the `&#8203;`/`\u200B` character before counting words
Pre-checks:
Review:
=> TINY-7484: Remove zero width space before counting words

Jenkinsfile, modules/tinymce/CHANGELOG.md
Related Ticket: TINY-8194
- Remove IE11 from browser test suite
Pre-checks:
Review:
=> TINY-8194: Remove IE11 from tests

modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/importcss/demo/css/rules.css, modules/tinymce/src/plugins/importcss/main/ts/core/ImportCss.ts, modules/tinymce/src/plugins/importcss/test/css/internal.css, modules/tinymce/src/plugins/importcss/test/ts/browser/ImportCssPluginTest.ts
Related Ticket:TINY-8238
* Switch from a simple `.mce-` check to a regex that covers all the ways we phrase our content CSS selectors
Pre-checks:
Review:
=> TINY-8238: Exclude more internal selectors from the imported CSS list

modules/tinymce/src/plugins/importcss/demo/css/rules.css, modules/tinymce/src/plugins/importcss/main/ts/core/ImportCss.ts, modules/tinymce/src/plugins/importcss/test/css/internal.css
Related Ticket: TINY-8238
* Fixes another case that was missed whereby internal selectors/classes could still be picked up by the import css plugin
Pre-checks:
Review:
=> TINY-8238: Fixed another case for internal selectors

modules/tinymce/src/core/main/ts/api/EditorOptions.ts, modules/tinymce/src/core/test/ts/browser/EditorOptionsTest.ts
Related Ticket: TINY-8206/TINY-8235
* Adds an `isSet` API to see if a custom value has been set for an option
Pre-checks:
Review:
=> TINY-8206: Added the isSet function to the editor options API

Jenkinsfile
Related Ticket: TINY-8278
This just attempts to fix an issue we found where tests seemed to be locking up when running multiple headless browsers in parallel.
Pre-checks:
Review:
=> TINY-8278: Added a lock for headless tests to prevent them running simultaneously

modules/katamari/CHANGELOG.md, modules/katamari/src/main/ts/ephox/katamari/api/Type.ts, modules/katamari/src/test/ts/atomic/api/type/TypeTest.ts, modules/katamari/src/test/ts/browser/TypeBrowserTest.ts, modules/tinymce/src/core/main/ts/api/EditorOptions.ts, modules/tinymce/src/core/test/ts/browser/EditorOptionsTest.ts, modules/tinymce/src/plugins/advlist/main/ts/api/Options.ts, modules/tinymce/src/plugins/autolink/main/ts/api/Options.ts, modules/tinymce/src/plugins/codesample/main/ts/api/Options.ts, modules/tinymce/src/plugins/help/main/ts/api/Options.ts, modules/tinymce/src/plugins/image/main/ts/api/Options.ts, modules/tinymce/src/plugins/importcss/main/ts/api/Options.ts, modules/tinymce/src/plugins/link/main/ts/api/Options.ts, modules/tinymce/src/plugins/media/main/ts/api/Options.ts, modules/tinymce/src/plugins/noneditable/main/ts/api/Options.ts, modules/tinymce/src/plugins/table/main/ts/api/Options.ts, modules/tinymce/src/themes/silver/main/ts/api/Options.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/color/Options.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/complex/FontSelect.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/complex/FontsizeSelect.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/complex/FormatSelect.ts, modules/tinymce/src/themes/silver/main/ts/ui/core/complex/SelectDatasets.ts
Related Ticket: TINY-8235
* Adds a `Type.is` function to Katamari to check if an object is a specific class/constructor type
* Swap to using `Array.isArray` instead of the custom proto check
* Adds the `regexp` and `object[]` built-in processors for options
* Changed the `string[]` built-in processor to allow a string array or a comma/space separated string (as discussed at stand up)
* Updated the registered options to make use of them
Pre-checks:
Review:
=> TINY-8235: Added additional built-in processors and made use of them

Gruntfile.js, Jenkinsfile
Related Ticket: TINY-8284
@TheSpyder noticed today that the `--chunk` argument wasn't working and this turned out to be the cause (since it uses the bedrock API directly). That means that for quite a while now the tests have been running pretty much all of them without reloading which might explain some of the IE flakes we've had.
Pre-checks:
Review:
=> TINY-8284: Fixed not parsing the grunt options to numbers and updated chunking value

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/AddOnManager.ts, modules/tinymce/src/core/main/ts/api/PluginManager.ts, modules/tinymce/src/core/main/ts/init/Init.ts
Related Ticket: TINY-8256
Updated how plugins and themes are initialised so that they don't use the `new` operator. This means that plugins/themes can be defined using arrow functions, etc...
Pre-checks:
Review:
=> TINY-8256: Don't use the new operator when constructing addons

modules/tinymce/src/core/main/ts/api/EditorOptions.ts, modules/tinymce/src/core/main/ts/api/Options.ts
Related Ticket: TINY-8234
* Added the missing `api_key` option which is used with cloud
* Don't report `mobile` as an unregistered option as it'll be flatten when normalised
Pre-checks:
Review:
=> TINY-8234: Added missing api_key option and ignore mobile when reporting unregistered options

modules/tinymce/src/core/main/ts/api/Tinymce.ts
Related Ticket: TINY-8162
This is something I missed in https://github.com/tinymce/tinymce/pull/7314. Unfortunately because of the way `Tools.extend` work TypeScript couldn't tell these weren't implemented.
Pre-checks:
Review:
=> TINY-8162: Fixed types that weren't cleaned up when the deprecated Env properties were removed

modules/tinymce/src/core/main/ts/api/Editor.ts
Related Ticket: TINY-8162
* Just cleans up some more deprecated APIs that we'd missed
Pre-checks:
Review:
=> TINY-8162: Removed old v4 deprecated toolbar button/menu APIs

modules/mcagar/src/main/ts/ephox/mcagar/alien/EditorTypes.ts, modules/mcagar/src/main/ts/ephox/mcagar/alien/Options.ts, modules/mcagar/src/test/ts/browser/api/TinySetAndDeleteSettingTest.ts
Related Ticket: TINY-8235
When doing some upgrades I noticed the shared Editor types don't work as `options` is mandatory. So this fixes them so that they work with TinyMCE 5/6 types.
Pre-checks:
Review:
=> TINY-8235: Fixed incorrect partial/shared editor types in McAgar

modules/tinymce/src/core/main/ts/Rtc.ts, modules/tinymce/src/core/main/ts/init/InitContentBody.ts
* This is part of a change on both the RTC side and the tinymce core side.
Pre-checks:
Review:
=> TINY-8282: bind default events last so they can be prevented by themes/plugins

modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/autolink/main/ts/api/Options.ts, modules/tinymce/src/plugins/autolink/test/ts/browser/AutoLinkPluginTest.ts, modules/tinymce/src/plugins/link/main/ts/api/Options.ts, modules/tinymce/src/plugins/link/test/ts/browser/AllowUnsafeLinkTargetTest.ts, modules/tinymce/src/plugins/link/test/ts/browser/DefaultLinkTargetTest.ts, modules/tinymce/src/plugins/link/test/ts/browser/DialogSectionsTest.ts, modules/tinymce/src/plugins/link/test/ts/browser/ListOptionsTest.ts
Renamed variables to be consistent with other option names.
Pre-checks:
Review:
=> TINY-4603: Renaming link options to be more consistent

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/html/DomParser.ts, modules/tinymce/src/core/main/ts/api/html/Node.ts, modules/tinymce/src/core/main/ts/api/html/Serializer.ts, modules/tinymce/src/core/main/ts/content/InsertContentImpl.ts, modules/tinymce/src/core/main/ts/html/InvalidNodes.ts, modules/tinymce/src/core/main/ts/html/ParserUtils.ts, modules/tinymce/src/core/main/ts/init/InitContentBody.ts, modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts, modules/tinymce/src/plugins/media/main/ts/core/Nodes.ts, modules/tinymce/src/plugins/media/test/ts/browser/ContentFormatsTest.ts, modules/tinymce/src/plugins/media/test/ts/browser/SubmitTest.ts, modules/tinymce/src/plugins/paste/main/ts/core/Utils.ts
Related Ticket: TINY-8205
* This one you could probably review commit by commit if you wanted to (and I'm thinking of rebasing it, instead of squashing, so it would be a good idea to look at the commits separately)
* Fixed a weird test thunking case we'd missed before
* Removed .shortEnded from AstNode
* Removed .fixed from AstNode
* Changed the way we handle inserting invalid content — previously we just parsed and serialised the whole tree it as a way of tidying up the structure, and now we perform tree operations manually (and refactored to take some of that logic out of DomParser)
Pre-checks:
Review:
=> TINY-8205: Fixes to add some forward compatibility with the new parser

modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/autolink/main/ts/api/Options.ts, modules/tinymce/src/plugins/autolink/test/ts/browser/AutoLinkPluginTest.ts, modules/tinymce/src/plugins/autolink/test/ts/browser/ConsecutiveLinkTest.ts, modules/tinymce/src/plugins/link/main/ts/api/Options.ts, modules/tinymce/src/plugins/link/test/ts/browser/AssumeExternalTargetsTest.ts, modules/tinymce/src/plugins/link/test/ts/browser/UrlProtocolTest.ts
Related Ticket: TINY-7824
* Changed the default value from `http` to `https` for the `link_default_protocol` option
Pre-checks:
Review:
=> TINY-7824: Changed the default value for the link_default_protocol option

modules/tinymce/src/core/main/ts/api/Options.ts, modules/tinymce/src/core/test/ts/browser/init/InitEditorThemeFunctionInlineTest.ts, modules/tinymce/src/themes/silver/main/ts/api/Options.ts
Related Ticket: TINY-8348
* Fixed 2 separate minor issues found with the options conversion that caused incorrect defaults in inline mode and on touch devices.
Pre-checks:
Review:
Fixes #7458
=> TINY-8348: Fixed bugs from options conversion

modules/tinymce/src/core/main/ts/Rtc.ts, modules/tinymce/src/core/main/ts/keyboard/Autocompleter.ts, modules/tinymce/src/core/main/ts/keyboard/KeyboardOverrides.ts
* Adds support for the rtc autocompleter
Pre-checks:
Review:
=> TINY-8280: added alt model decorations for autocompleter

modules/tinymce/CHANGELOG.md, modules/tinymce/src/themes/silver/main/ts/ui/dialog/ColorPicker.ts, modules/tinymce/src/themes/silver/main/ts/ui/general/UiFactory.ts, modules/tinymce/src/themes/silver/test/ts/headless/components/colorpicker/ColorPickerTest.ts
Related Ticket: TINY-8381
* Fixed color picker aria label strings not getting passed for translation
* Removed unused key to english strings
Pre-checks:
Review:
=> TINY-8381: Fixed color picker not getting translated

modules/tinymce/src/plugins/help/main/ts/data/PluginUrls.ts, modules/tinymce/src/themes/silver/main/ts/ui/menus/contextmenu/Options.ts, modules/tinymce/src/themes/silver/main/ts/ui/menus/menubar/Integration.ts
Related Ticket: TINY-8365
* Updated the help plugin names/id for Image Tools and Table of Contents
* Updated the default contextmenu/menu configuration to use the new names
Pre-checks:
Review:
=> TINY-8365: Updated imagetools and toc names

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/json/globals.json, modules/tinymce/src/core/main/ts/api/FakeClipboard.ts, modules/tinymce/src/core/main/ts/api/PublicApi.ts, modules/tinymce/src/core/main/ts/api/Tinymce.ts, modules/tinymce/src/core/test/ts/browser/FakeClipboardTest.ts
Related Ticket: TINY-8353
* Add a fake clipboard to the tinymce global that can be used by the table copy row/column logic as well by the paste plugin
Note: I didn't have an exact spec to work with so have just done a basic read, write, clear API as a starting point.
Pre-checks:
Review:
=> TINY-8353: Add FakeClipboard to tinymce global

modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/emoticons/main/ts/Plugin.ts, modules/tinymce/src/plugins/emoticons/main/ts/api/Options.ts, modules/tinymce/src/plugins/emoticons/main/ts/core/EmojiDatabase.ts, modules/tinymce/src/plugins/emoticons/main/ts/ui/Buttons.ts, modules/tinymce/src/plugins/emoticons/main/ts/ui/Dialog.ts, modules/tinymce/src/plugins/emoticons/test/ts/browser/EmojiAppendTest.ts, modules/tinymce/src/plugins/emoticons/test/ts/browser/EmojiSearchTest.ts, modules/tinymce/src/plugins/emoticons/test/ts/browser/EmoticonAutocompletionTest.ts, modules/tinymce/src/plugins/emoticons/test/ts/browser/ImageEmojiTest.ts
Related Ticket: TINY-7631
* Updated the UI text and internal code to use the correct `Emojis` term instead of `Emoticons`
Note: As per the Jira the plugin name and options are not changing.
Pre-checks:
Review:
=> TINY-7631: Updated the emoticon plugin UI to use "Emojis" instead of "Emoticons"

modules/oxide/src/less/theme/content/comments/comments.less, modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/demo/html/annotations_demo.html, modules/tinymce/src/core/demo/ts/demo/AnnotationsDemo.ts, modules/tinymce/src/core/main/ts/annotate/AnnotationChanges.ts, modules/tinymce/src/core/main/ts/annotate/AnnotationFilter.ts, modules/tinymce/src/core/main/ts/annotate/AnnotationsRegistry.ts, modules/tinymce/src/core/main/ts/annotate/Identification.ts, modules/tinymce/src/core/main/ts/annotate/Markings.ts, modules/tinymce/src/core/main/ts/api/Annotator.ts, modules/tinymce/src/core/test/ts/browser/annotate/AnnotationChangedTest.ts, modules/tinymce/src/core/test/ts/browser/annotate/AnnotationRemovedTest.ts
* This does some changes to the annotation part of the core to avoid direct dom mutation by the remark plugin. Check the JIRA ticket for details.
Pre-checks:
Review:
=> TINY-8195: Change the annotation api to avoid dom mutation in plugins using it

modules/tinymce/src/plugins/paste/main/ts/core/Quirks.ts, modules/tinymce/src/plugins/paste/test/ts/browser/PasteStylesTest.ts
Related Ticket: TINY-8163
* fix paste regression due to incorrect variable being used.
Pre-checks:
Review:
=> TINY-8163: test for paste not changing RGB color

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/EditorManager.ts, modules/tinymce/src/core/test/ts/browser/EditorManagerCommandsTest.ts
Related Ticket: TINY-8138
* Update the `mceAddEditor` command to either take an id string as its value or an object that contains the id and editor options to be used for the new editor
Pre-checks:
Review:
=> TINY-8138: Change `mceAddEditor` command to allow editor options

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/Editor.ts, modules/tinymce/src/core/main/ts/api/EditorOptions.ts, modules/tinymce/src/core/main/ts/api/Options.ts, modules/tinymce/src/core/main/ts/options/NormalizeOptions.ts, modules/tinymce/src/core/test/ts/browser/EditorManagerTest.ts, modules/tinymce/src/core/test/ts/browser/EditorTest.ts, modules/tinymce/src/core/test/ts/browser/options/NormalizeOptionsTest.ts
Related Ticket: TINY-8236
* Removed the `editor.settings` property
* Updated the `editor.getParam` API to delegate to the Options API for better backwards compatibility and marked it as deprecated.
* Cleaned up any old `getParam` specific logic
Pre-checks:
Review:
=> TINY-8236: Removed the editor.settings property and updated the getParam API to use the Options API

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/Options.ts, modules/tinymce/src/core/main/ts/api/html/Schema.ts, modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts, modules/tinymce/src/core/test/ts/browser/keyboard/EnterKeyTest.ts
Related Ticket: TINY-8261
* Updated the `schema` option to default to `html5` instead of `undefined` (they were fairly similar but it did have slight differences)
* Cleaned up the schema code (removed code duplication, added types and cleaned up variables)
Pre-checks:
Review:
=> TINY-8261: Update the schema option to default to `html5`

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/EditorManager.ts, modules/tinymce/src/core/test/ts/browser/EditorManagerCommandsTest.ts
Related Ticket: TINY-8138
* Rework the `mceAddEditor`  command so that editor options have to specified in addition to the id
Pre-checks:
Review:
=> TINY-8138: Rework `mceAddEditor` command to use an object value

modules/acid/src/main/ts/ephox/acid/gui/components/RgbForm.ts, modules/tinymce/CHANGELOG.md, modules/tinymce/src/themes/silver/main/ts/ui/alien/FieldLabeller.ts, modules/tinymce/src/themes/silver/main/ts/ui/button/ButtonSlices.ts, modules/tinymce/src/themes/silver/main/ts/ui/dialog/Dropzone.ts, modules/tinymce/src/themes/silver/main/ts/ui/dialog/Label.ts, modules/tinymce/src/themes/silver/main/ts/ui/dialog/SizeInput.ts, modules/tinymce/src/themes/silver/main/ts/ui/dialog/Slider.ts, modules/tinymce/src/themes/silver/main/ts/ui/dialog/TabPanel.ts, modules/tinymce/src/themes/silver/main/ts/ui/general/Checkbox.ts, modules/tinymce/src/themes/silver/main/ts/ui/general/Tooltips.ts, modules/tinymce/src/themes/silver/main/ts/ui/menus/item/alien/ConvertShortcut.ts, modules/tinymce/src/themes/silver/main/ts/ui/menus/item/build/SeparatorItem.ts, modules/tinymce/src/themes/silver/main/ts/ui/menus/item/structure/ItemSlices.ts, modules/tinymce/src/themes/silver/main/ts/ui/menus/menu/MenuStructures.ts, modules/tinymce/src/themes/silver/main/ts/ui/statusbar/ElementPath.ts, modules/tinymce/src/themes/silver/test/ts/headless/components/input/InputTest.ts, modules/tinymce/src/themes/silver/test/ts/headless/components/label/LabelTest.ts
Related Ticket: TINY-7524/TINY-8340
* Fixed a number of dialog labels and other text-based UI fields to ensure they are always rendered as text content only.
Note: I haven't touched `AlertBanner.ts` or `Notification.ts` as I know those do actually need to allow HTML at this stage.
Pre-checks:
Review:
=> TINY-7524: Ensure dialog labels and other text based fields only render as text

modules/tinymce/src/core/main/ts/api/html/DomParser.ts, modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts, modules/tinymce/src/core/test/ts/browser/html/SerializerTest.ts, modules/tinymce/src/plugins/autolink/test/ts/browser/AutoLinkPluginTest.ts
Related Ticket: TINY-8202
* Got the `xhtml` parser side of things working again.
* Removed the parser `xml` format and replaced references in tests with `xhtml` instead as we've never actually parsed XML and the native DOM parser won't parse XML only XHTML.
* Fixed a few issues with the dom purify configuration I found while fixing tests
* Updated the various invalid tests to reflect how the native parser actually parser per the spec.
Pre-checks:
Review:
=> TINY-8202: More changes to get the parser working and passing tests

modules/tinymce/src/core/test/ts/browser/FormatterApplyTest.ts
Related Ticket: TINY-8260
* Make sure editor is focused when running test
* Change `block: 'del'` tests as `del` is an inline element
Pre-checks:
Review:
=> TINY-8260: Fix formatter test that was failing in isolation

modules/tinymce/src/themes/silver/main/ts/ui/general/Button.ts, modules/tinymce/src/themes/silver/test/ts/headless/components/dialogbutton/DialogButtonTest.ts
Related Ticket: TINY-7524
* Found one more case while writing the QA notes where a `text` or `label` property was being rendered as HTML.
Pre-checks:
Review:
=> TINY-7524: Fixed another case where text was being interpreted as HTML

modules/tinymce/src/core/main/ts/api/html/DomParser.ts, modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts, modules/tinymce/src/core/test/ts/browser/html/SerializerTest.ts
Related Ticket: TINY-8383
* Make `validate: false` work again by ignoring the configured schema rules and added some basic tests since we largely had none
* Split out the parsing and sanitizing logic so DOMPurify only handles sanitization
* Made some minor performance improvements
* Did some minor code clean up (largely for legacy code)
Pre-checks:
Review:
=> TINY-8383: Added back `validate: false` support for the parser

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/SelectionOverrides.ts, modules/tinymce/src/core/main/ts/api/html/SaxParser.ts, modules/tinymce/src/core/main/ts/api/html/Schema.ts, modules/tinymce/src/core/main/ts/content/InsertContentImpl.ts, modules/tinymce/src/core/main/ts/dom/TrimHtml.ts, modules/tinymce/src/core/main/ts/paste/PasteUtils.ts, modules/tinymce/src/core/test/ts/browser/html/SchemaTest.ts, modules/tinymce/src/plugins/searchreplace/main/ts/core/TextCollect.ts, modules/tinymce/src/plugins/wordcount/main/ts/core/GetText.ts
Related Ticket: TINY-8344
* Rename the `getShortEndedElements` API to `getVoidElements` to match the actual name used in the HTML spec
* Seal the void elements list since it's not something that should be changed at runtime
Note: I didn't seal the special elements in this PR, as that's instead been done in https://github.com/tinymce/tinymce/pull/7535 since the media plugin needs to be updated first.
Pre-checks:
Review:
=> TINY-8344: Rename getShortEndedElements to getVoidElements and seal the list of void elements

modules/agar/package.json, modules/agar/src/main/ts/ephox/agar/assertions/ApproxStructures.ts, modules/agar/src/test/ts/atomic/api/LoggerTest.ts, modules/agar/src/test/ts/atomic/api/StepTest.ts, modules/agar/src/test/ts/browser/AssertionsTest.ts, modules/agar/src/test/ts/browser/api/CleanerTest.ts, modules/agar/src/test/ts/browser/api/DragnDropTest.ts, modules/agar/src/test/ts/browser/datatransfer/DataTransferItemListTest.ts, modules/sand/CHANGELOG.md, modules/sand/src/main/ts/ephox/sand/api/SandHTMLElement.ts, modules/sand/src/test/ts/browser/HtmlElementTest.ts, yarn.lock
Related Ticket: TINY-8411/TINY-8414
* Upgrade Agar to remove uses of the legacy `assert` API that was removed in Bedrock 13
* Upgrade Agar deps to allow using version 11, 12 or 13 of bedrock
* Fix `SandHTMLElement.isPrototypeOf` throwing an `Illegal invocation` error for `HTMLAnchorElement` on Chromium based browsers (it doesn't like calling `toString` on the prototype)
Pre-checks:
Review:
=> TINY-8411: Various fixes to be able to upgrade to the latest bedrock/monorepo libraries

modules/tinymce/src/core/main/ts/api/EditorOptions.ts, modules/tinymce/src/core/main/ts/api/dom/ScriptLoader.ts
Related Ticket: TINY-8296
* Remove the unregistered options warning
* Sneak in a typo @RobinJoe found in the `ScriptLoader` API docs
Pre-checks:
Review:
=> TINY-8296: Removed the unregistered options console warning

package.json, patches/dompurify+2.3.4.patch, yarn.lock
Related Ticket: TINY-4627
This patch is only meant to be short-lived as we should contribute this back upstream if all works well, but this just makes some fairly minor performance improvements I was able to find for DOMPurify.
Pre-checks:
Review:
=> TINY-4627: Patch dompurify to apply some minor performance improvements

modules/tinymce/src/core/main/ts/api/Editor.ts
* Corrected typo in execCommand documentation
Pre-checks:
Review:
=> fix typo in execCommand docstring

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/ErrorReporter.ts, modules/tinymce/src/core/main/ts/api/AddOnManager.ts, modules/tinymce/src/core/main/ts/api/Editor.ts, modules/tinymce/src/core/main/ts/api/EditorUpload.ts, modules/tinymce/src/core/main/ts/api/EventTypes.ts, modules/tinymce/src/core/main/ts/api/Resource.ts, modules/tinymce/src/core/main/ts/api/dom/DOMUtils.ts, modules/tinymce/src/core/main/ts/api/dom/ScriptLoader.ts, modules/tinymce/src/core/main/ts/api/dom/StyleSheetLoader.ts, modules/tinymce/src/core/main/ts/file/Uploader.ts, modules/tinymce/src/core/main/ts/init/InitContentBody.ts, modules/tinymce/src/core/main/ts/init/Render.ts, modules/tinymce/src/core/test/ts/browser/AddOnManagerTest.ts, modules/tinymce/src/core/test/ts/browser/EditorRemoveTest.ts, modules/tinymce/src/core/test/ts/browser/EditorRemovedApiTest.ts, modules/tinymce/src/core/test/ts/browser/EditorUploadTest.ts, modules/tinymce/src/core/test/ts/browser/dom/ReferrerPolicyTest.ts, modules/tinymce/src/core/test/ts/browser/dom/ScriptLoaderTest.ts, modules/tinymce/src/core/test/ts/browser/dom/StyleSheetLoaderTest.ts, modules/tinymce/src/core/test/ts/browser/util/ImageUploaderTest.ts, modules/tinymce/src/plugins/image/test/ts/browser/UploadTabTest.ts, modules/tinymce/src/themes/silver/main/ts/ui/skin/Loader.ts
Related Ticket: TINY-8325
* Update the `ScriptLoader`, `StyleSheetLoader`, `AddOnManager`, `PluginManager` and `ThemeManager` APIs to return Promises instead of having to pass in a callback
* Made the theme load logic fire a new `ThemeLoadError` event if the theme fails to load. This is for consistency with the rest of the error handling and I needed to do something in the `catch`, otherwise we'd get unhandled promise rejection errors.
* Remove the callbacks on the `EditorUpload` APIs
* Changed the `images_upload_handler` to require a Promise be returned instead of passing `success` and `failure` callbacks. This also means if passing the `remove` option for a failure it now requires an object containing the message and remove flag (since we can only return a single …
=> TINY-8325: Convert a number of APIs to use Promises instead of callbacks

modules/tinymce/src/core/main/ts/api/html/DomParser.ts, modules/tinymce/src/core/main/ts/api/util/URI.ts, modules/tinymce/src/core/main/ts/html/ParserUtils.ts, modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts, modules/tinymce/src/core/test/ts/browser/html/SerializerTest.ts, patches/dompurify+2.3.4.patch
Related Ticket: TINY-4627
This is just some more fixes both to our logic and to DOMPurify to help with the parsing speed. This like the previous PR doesn't make a huge difference (largely a number of micro optimizations), but in my testing between this and the previous PR it's shaven off between 10-20% in general (really depends on the content and how much the GC runs).
Pre-checks:
Review:
=> TINY-4627: More minor parser optimizations

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/demo/html/content_editable_false_demo.html, modules/tinymce/src/core/demo/ts/demo/ContentEditableFalseDemo.ts, modules/tinymce/src/core/main/ts/SelectionOverrides.ts, modules/tinymce/src/core/main/ts/caret/CaretContainerInput.ts, modules/tinymce/src/core/main/ts/caret/ClosestCaretCandidate.ts, modules/tinymce/src/core/main/ts/caret/LineUtils.ts, modules/tinymce/src/core/main/ts/geom/ClientRect.ts, modules/tinymce/src/core/test/ts/browser/ClickContentEditableFalseTest.ts, modules/tinymce/src/core/test/ts/browser/caret/ClosestCaretCandidateTest.ts, modules/tinymce/src/core/test/ts/browser/caret/FakeCaretTypeTest.ts, modules/tinymce/src/core/test/ts/browser/caret/LineUtilsTest.ts, modules/tinymce/src/core/test/ts/browser/geom/ClientRectTest.ts, modules/tinymce/src/plugins/table/test/ts/browser/FakeSelectionTest.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/core/SimpleControlsTest.ts, modules/tinymce/src/themes/silver/test/ts/headless/components/checkbox/BasicCheckboxTest.ts
* Adds a new approach to figuring out where to render fake carets.
* Also fixed two unrelated tests that where failing while the 100 test chunk pivot point was moving around. They are depending on state from the previous test.
Pre-checks:
Review:
=> TINY-8169: added new approach for adding noneditable fake carets

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/html/Schema.ts
Related Ticket: TINY-8214/TINY-4627
This just brings back the `elements` property on the schema and updates the `setValidElements` function to clear all properties instead of create a new object. It's not great for performance having to manually delete each property, but this isn't something that's called often, if at all so it should be okay.
Pre-checks:
Review:
=> TINY-8214: Revert removing the Schema elements property

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/Resource.ts, modules/tinymce/src/core/test/ts/browser/EditorManagerTest.ts, modules/tinymce/src/core/test/ts/browser/EditorRemoveTest.ts, modules/tinymce/src/core/test/ts/browser/FakeClipboardTest.ts, modules/tinymce/src/core/test/ts/browser/ForceBlocksTest.ts, modules/tinymce/src/core/test/ts/browser/ResourceTest.ts, modules/tinymce/src/core/test/ts/browser/dom/SelectionTest.ts, modules/tinymce/src/core/test/ts/browser/init/ContentCssTest.ts, modules/tinymce/src/plugins/emoticons/test/ts/browser/ImageEmojiTest.ts, modules/tinymce/src/plugins/template/test/ts/browser/DialogGetPreviewContentTest.ts
* Fixed an annoying test that has been failing for me for a long time when running the tests locally. The ImageEmoji tests fails since a previous test has already setup a resource id for the database so it will load the data from the previous test not the current one. I added a tinymce.Resource.unload that lets you remove a previously loaded resource this is probably only useful for tests so not sure we need to document it.
* Fixed a few issues with the test for the Resource it was not returning promises correctly and it was not properly isolated tests they depended on each other.
* Fixed various other tests that either depend on state from a previous test or break if a state exists from a previous test. These will flake on/off if the 100 tests …
=> TINY-8431: Fix emoticons image database test

modules/tinymce/src/core/main/ts/api/html/DomParser.ts, modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts
Related Ticket: TINY-8414
* Fixed `aria-*` attributes being incorrectly stripped (this was something Neil and I had missed porting from SaxParser). This was found when upgrading TinyMCE in premium plugins.
Pre-checks:
Review:
=> TINY-8414: Fixed aria attributes incorrectly being stripped

modules/tinymce/CHANGELOG.md, modules/tinymce/package.json, modules/tinymce/src/core/main/ts/fmt/RemoveFormat.ts, modules/tinymce/src/core/test/ts/browser/fmt/RemoveFormatTest.ts
A backport of the TINY-8308 fix.
Pre-checks:
Review:
=> TINY-8442: Backport prevent removing formats if matching selected element

modules/tinymce/src/core/main/ts/textpatterns/core/InlinePattern.ts, modules/tinymce/src/core/test/ts/browser/textpatterns/TextPatternsTest.ts
Related Ticket: TINY-8414
This is something that came up with the spellchecker tests when upgrading. The inline textpattern detection code expects that when it's triggered via space the offset will be 1 at minimum, but when using APIs it's possible for that to not be the case. While it's a pretty unlikely case to occur and can't happen naturally, as discussed via slack it was thought it was still worthwhile adding a guard for this case, so that's that guard.
Pre-checks:
Review:
=> TINY-8414: Added a guard for an edge case issue with inline textpattern detection

modules/oxide/src/less/theme/content/anchor/anchor.less, modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/util/Quirks.ts
Related Ticket: TINY-3799
This just makes some improvements and fixes the visual rendering issues with using `allow_html_in_named_anchor: true`. The screenshot below shows the two different versions should render the same now, with the top being an anchor with HTML content (`<a id="dfdfd">dfdfd</a>`) and the second being empty (`<a id="dfdfd"></a>dfdfd`).
**Note:** This in no way attempts to solve all the issues with enabling this option and only attempts to fix the poor rendering.
Pre-checks:
Review:
=> TINY-3799: Added a workaround to improve anchor rendering when using allow_html_in_named_anchor: true

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/NotificationManager.ts, modules/tinymce/src/core/main/ts/ui/NotificationManagerImpl.ts, modules/tinymce/src/themes/silver/main/ts/alien/NotificationManagerImpl.ts
Related Ticket: TINY-6679
* `closeButton` no longer depends on `timeout`
* Removed undocumented notification APIs (`moveTo` and `moveRel`) that restricted future work. Despite being undocumented this is a breaking change, requiring a major version boundary to release.
The functionality in `moveRel` is unfortunately still required for `notificationManager.reposition()` to operate correctly, so I've added a hack to replicate what reposition was doing. We have already planned TINY-8128 to resolve this issue but ran out of time to do it in the 6.0 release.
Pre-checks:
Review:
=> TINY-6679: Separate notification closeButton and timeout settings

modules/tinymce/src/core/main/ts/api/html/DomParser.ts, modules/tinymce/src/core/main/ts/api/util/URI.ts, modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts, modules/tinymce/src/plugins/media/main/ts/core/Nodes.ts, modules/tinymce/src/plugins/media/main/ts/core/Parser.ts, modules/tinymce/src/plugins/media/main/ts/core/Sanitize.ts, modules/tinymce/src/plugins/media/main/ts/core/UpdateHtml.ts, modules/tinymce/src/plugins/media/test/ts/browser/ContentFormatsTest.ts
Related Ticket: TINY-8410
* Ports a number of useful tests from `SaxParserTest` to `DomParserTest`
* Fixed an issue where bogus elements weren't removed correctly if the element wasn't in the schema
* Fixed `allow_conditional_comments` not being used
* Fixed attribute values not being URL decoded which means some older unsafe values weren't stripped
* Added some logic to preserve certain internal element attributes (this is different to 5.x, but this is a safe option for now given the changes and TINY-8452 has been logged to investigate this further)
* Cleaned up the media code a little
Pre-checks:
Review:
=> TINY-8410: Ported relevant SaxParser tests and fixed issues found

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/Editor.ts, modules/tinymce/src/core/main/ts/api/EditorOptions.ts, modules/tinymce/src/core/main/ts/api/OptionTypes.ts, modules/tinymce/src/core/main/ts/api/Options.ts, modules/tinymce/src/core/main/ts/init/Init.ts, modules/tinymce/src/core/main/ts/init/Render.ts, modules/tinymce/src/core/main/ts/options/NormalizeOptions.ts, modules/tinymce/src/core/test/ts/browser/EditorTest.ts, modules/tinymce/src/core/test/ts/browser/options/NormalizeOptionsTest.ts
Related Ticket: TINY-8455
* Changes the return type for the `plugins` option to be a `string[]` since that's how it's always used
* Fixed an issue with the `Options.set` types, that meant type checking wasn't really working in some cases since it'd fall-through to the more generic override.
Pre-checks:
Review:
=> TINY-8455: Make the plugins option return type be a string array

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/demo/ts/demo/CommandsDemo.ts, modules/tinymce/src/core/demo/ts/demo/ContentSecurityPolicyDemo.ts, modules/tinymce/src/core/demo/ts/demo/FullDemo.ts, modules/tinymce/src/core/demo/ts/demo/IframeDemo.ts, modules/tinymce/src/core/demo/ts/demo/InlineDemo.ts, modules/tinymce/src/core/demo/ts/demo/ResponsiveDemo.ts, modules/tinymce/src/core/demo/ts/demo/SourceDumpDemo.ts, modules/tinymce/src/core/demo/ts/demo/StickyToolbarDemo.ts, modules/tinymce/src/core/main/ts/options/NormalizeOptions.ts, modules/tinymce/src/core/test/ts/browser/options/NormalizeOptionsTest.ts
Related Ticket: TINY-8399
This changes the `plugins` option so it now only accepts a string array or a space separated string, instead of a mixture of the two. For example these are valid:
```js
plugins: 'advlist list image help wordcount'
```
```js
plugins: 'advlist,list,image,help,wordcount'
```
```js
plugins: [ 'advlist', 'list', 'image', 'help', 'wordcount' ]
```
however, this is no longer valid:
```js
plugins: [
'advlist list image',
'help wordcount'
]
```
Note: The [documentation](https://www.tiny.cloud/docs/configure/integration-and-setup/#plugins) actually only states we allow the first option, however removing the rest could be too risky and would end up being inconsistent with the built-in `string[]` option processor.
Pre-checks:
Review:
GitHub issues (if …
=> TINY-8399: Removed support for plugins allowing a mixture of a string array and of space separated strings

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/init/Render.ts
Related Ticket: TINY-8453
Changes how the scripts are loaded so that the theme is now loaded in parallel with the other resources (e.g. the plugins, icons and language pack). Previously it'd load the theme first and then load the rest of the resources.
Pre-checks:
Review:
=> TINY-8453: Load the editor theme in parallel with other resources

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/Editor.ts, modules/tinymce/src/core/main/ts/api/EventTypes.ts, modules/tinymce/src/core/main/ts/api/Events.ts
Related Ticket: TINY-8457
* The `content` property is problematic on the SetContent event for rtc and it also doesn't make much sense to have it.
* add @deprecated tag for `SetContentEvent.content` property
* update changelog
Pre-checks:
Review:
=> TINY-8457: Deprecate the content property for setContent event

modules/tinymce/src/core/main/ts/api/html/DomParser.ts, modules/tinymce/src/core/main/ts/content/InsertContentImpl.ts, modules/tinymce/src/core/main/ts/html/FilterNode.ts, modules/tinymce/src/core/test/ts/browser/content/InsertContentTest.ts, modules/tinymce/src/plugins/media/main/ts/core/Nodes.ts, modules/tinymce/src/plugins/media/test/ts/browser/SubmitTest.ts
Related Ticket: TINY-8444
This is something that regressed in https://github.com/tinymce/tinymce/pull/7448, as since `parser.parse()` no longer runs and instead we manually patch in the AST nodes then that in turn meant the node filters didn't run in this specific case. As such, I found we actually had 2 sets of filtering code paths, so I've merged them into 1 and updated the insert content logic to ensure the filters are run after we've adjusted the tree.
Note: I've also manually built this and linked it to the premium plugins that were failing and have verified the tests now pass there.
Pre-checks:
Review:
=> TINY-8444: Fixed node filters not running when inserting certain content

modules/tinymce/src/themes/silver/main/ts/ui/statusbar/ElementPath.ts, modules/tinymce/src/themes/silver/main/ts/ui/statusbar/WordCount.ts, modules/tinymce/src/themes/silver/test/ts/browser/statusbar/StatusbarTest.ts
Related Ticket: TINY-8459
This fixes the element path only correctly rendering the last delimiter. The cause of this was that we were using a constant delimiter spec and sharing it for each delimiter. However since `GuiFactory.text()` is a premade text node, it could only be used once in the DOM which is why it broke. I've also cleaned up the element path code a reasonable bit and added various types. I also threw some types in on `WordCount.ts` while I was looking for other cases where we may have misused `GuiFactory.text()` (I didn't find any others though).
Pre-checks:
Review:
=> TINY-8459: Fixed the statusbar element path not rendering correctly

modules/alloy/src/main/ts/ephox/alloy/behaviour/replacing/ReplaceApis.ts, modules/alloy/src/main/ts/ephox/alloy/behaviour/replacing/ReplacingAll.ts, modules/alloy/src/main/ts/ephox/alloy/dom/Patching.ts, modules/alloy/src/test/ts/browser/behaviour/ReplacingTest.ts
Related Ticket: TINY-8440
* Fixed an issue with the `Replacing.replaceBy` and `Replacing.replaceAt` APIs when passing in a premade component when `reuseDom` is enabled
* Did some minor reworking as well to allow the `buildOrPatch` function to be passed directly to the `Patching` functions
Pre-checks:
Review:
=> TINY-8440: Fixed the replaceBy and replaceAt apis not working correctly with premade components

modules/tinymce/CHANGELOG.md, modules/tinymce/src/plugins/image/main/ts/ui/AdvTab.ts, modules/tinymce/src/plugins/image/main/ts/ui/Dialog.ts, modules/tinymce/src/plugins/image/test/ts/browser/DialogTest.ts, modules/tinymce/src/plugins/image/test/ts/browser/ImagePluginTest.ts, modules/tinymce/src/plugins/image/test/ts/module/Helpers.ts
Related Ticket: TINY-3422
* Removed style field from the advanced tab of image dialog
* Adjusted dialog logic to calculate the style value on submit instead of on change
This was much harder than it first appeared, because every other field on the advanced tab did not store information independently. When updated they simply patched the style field, and the style field is what was serialised when the dialog was submitted.
Dialogs cannot store information in the API data other than fields that exist in the dialog, so I had to refactor the style generation logic into the submit handler. That itself required some additional work because it was very specifically structured to not have access to the other helper functions.
Technically this also means invalid values in …
=> TINY-3422: Removed style field from image dialog

modules/mcagar/CHANGELOG.md, modules/mcagar/src/main/ts/ephox/mcagar/alien/EditorTypes.ts, modules/mcagar/src/main/ts/ephox/mcagar/api/bdd/TinySelections.ts, modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/selection/SelectionRestore.ts, modules/tinymce/src/core/test/ts/browser/selection/SelectionBookmarkInlineEditorTest.ts
Related Ticket: TINY-8450
* Add `AfterSetSelectionRange` to the list of events that trigger storing the selection bookmark
* Update the test that verifies a 'bookmark doesn't change' scenario to use native selection
Perhaps other tests should be updated too, since the `setRng` call is now the one updating the bookmark as well as the other conditions in the test. I'm not sure.
Pre-checks:
Review:
=> TINY-8450: Update selection bookmark when the 'AfterSetSelectionRange' event is fired

modules/tinymce/src/core/main/ts/api/dom/ScriptLoader.ts, modules/tinymce/src/core/main/ts/init/Render.ts, modules/tinymce/src/core/test/assets/js/nested.js, modules/tinymce/src/core/test/assets/langs/custom.js, modules/tinymce/src/core/test/ts/browser/dom/ScriptLoaderTest.ts, modules/tinymce/src/core/test/ts/browser/init/InitEditorLanguageTest.ts
Related Ticket: TINY-8480
* Fixed an incorrect variable being used in the language url generation which caused it to generate an empty url unless `language_url` was configured.
* **Note:** The test I've added for this doesn't cover this exact case as we can't do that with our current test setup unfortunately, but we had nothing testing a custom language being loaded so this does at least assert languages can be loaded.
* Fixed an issue where the init sequence wasn't waiting for plugin language packs to be loaded before proceeding.
* **Note:** This was something I'd noticed the old `ScriptLoader` implementation did but found it poor behaviour to be loading scripts not passed in. However, since it's needed for the this case I've added it back, but we may want to look …
=> TINY-8480: Fixed language packs loading incorrectly

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/EditorUpload.ts, modules/tinymce/src/core/main/ts/api/EventTypes.ts, modules/tinymce/src/core/main/ts/api/Events.ts, modules/tinymce/src/core/main/ts/content/ContentTypes.ts, modules/tinymce/src/core/main/ts/content/PrePostProcess.ts, modules/tinymce/src/core/main/ts/content/SetContent.ts, modules/tinymce/src/core/main/ts/content/SetContentImpl.ts, modules/tinymce/src/core/main/ts/init/Render.ts, modules/tinymce/src/core/test/ts/browser/content/EditorContentTest.ts
Related Ticket: TINY-7996
* Update the `GetContent` event to ensure the `content` property is always a string.
* Update the `BeforeSetContent` event to actually serialize the tree passed to `setContent()` instead of always using an empty string. This also means `BeforeSetContent` is actually usable for tree content now.
* Cleaned up a few `isString` checks for the relevant events since they aren't needed anymore and didn't work with `tree` content (which is one reason we're changing this).
* Fixed/improved a few types for the get/set content operations
Pre-checks:
Review:
=> TINY-7996: Ensure only strings are passed to get/set content events

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/caret/CaretUtils.ts, modules/tinymce/src/core/main/ts/keyboard/NavigationUtils.ts, modules/tinymce/src/core/test/ts/browser/caret/CaretUtilsTest.ts, modules/tinymce/src/core/test/ts/browser/init/InitEditorLanguageTest.ts, modules/tinymce/src/core/test/ts/browser/keyboard/HomeEndKeysTest.ts
* Fixes an issue where home and end keys would move outside the current editable host element
* Sneaked in a fix for a test that was flaking on/off due to the 100 test pivot point moving around
* Cleaned up the tests a bit so that is uses `assertCursor` instead of `assertSelection`
Pre-checks:
Review:
=> TINY-8201: Pressing the "End" key within a CEF element causes the selection to incorrectly leave the element

modules/tinymce/src/core/test/ts/atomic/html/Base64UrisTest.ts, modules/tinymce/src/core/test/ts/browser/EditorTest.ts
Adding tests to ensure that corrupted base64 file data does not cause the editor to crash.
Pre-checks:
Review:
=> TINY-6946: Added regression tests for base64 image parsing

modules/tinymce/src/core/main/ts/api/Editor.ts, modules/tinymce/src/core/main/ts/api/dom/DOMUtils.ts, modules/tinymce/src/core/main/ts/api/dom/EventUtils.ts, modules/tinymce/src/core/main/ts/api/util/EventDispatcher.ts, modules/tinymce/src/core/main/ts/api/util/Observable.ts
Related Ticket: TINY-8102
* Fixed invalid HTML tags used in the deprecated comments
Pre-checks:
Review:
=> TINY-8102: Fixed invalid HTML tags used in the deprecated comments

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/paste/DragDrop.ts, modules/tinymce/src/core/test/ts/browser/paste/DragDropImageTest.ts
Related Ticket: TINY-8486
* Fix regex to not include `data:` as that is never part of an image `file.type`
* Add a test as I couldn't find any existing ones
Pre-checks:
Review:
=> TINY-8486: Fix DataTransfer image check in DragDrop.ts

modules/tinymce/CHANGELOG.md, modules/tinymce/src/themes/silver/main/ts/ui/menus/item/ItemEvents.ts
Related Ticket: TINY-8513
This reverts part of 8ad4a1a2df1b79bc8856d99a0b7be69bcd238001, as this specific line still needs the `isConnected` check since the `onAction` within the execute handler can cause the menu to close/be removed from the DOM (unlike the other cases were the check was removed). That is what's happening with the export menu item, as it triggers the throbber which in turns closes all the open popups.
Pre-checks:
Review:
=> TINY-8513: Fixed alloy detached context console warnings when menu items are closed by the onAction

modules/acid/package.json, modules/agar/package.json, modules/alloy/package.json, modules/boss/package.json, modules/boulder/package.json, modules/bridge/package.json, modules/darwin/package.json, modules/dragster/package.json, modules/jax/package.json, modules/katamari-assertions/package.json, modules/katamari/package.json, modules/mcagar/package.json, modules/oxide-icons-default/package.json, modules/oxide/package.json, modules/phoenix/package.json, modules/polaris/package.json, modules/porkbun/package.json, modules/robin/package.json, modules/sand/package.json, modules/snooker/package.json, modules/sugar/package.json, modules/tinymce/Gruntfile.js, modules/tinymce/package.json
Related Ticket: TINY-2316
* This was missed in #7647. The company name in our license txt is different to what we've been using in the package.json files:
https://github.com/tinymce/tinymce/blob/236891ffcdf2fd1b698d020e67c31838fb110019/LICENSE.TXT#L3
This PR updates everywhere we use the company name to the proper full string.
Pre-checks:
Review:
=> TINY-2316: Corrected company name

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/OptionTypes.ts, modules/tinymce/src/core/main/ts/api/Options.ts, modules/tinymce/src/core/main/ts/paste/DragDrop.ts
Related Ticket: TINY-8511
This removes the `paste_filter_drop` option as upon further review we found the only thing it does is control whether the TinyMCE drop handling takes over or whether it should fallback to the native logic. So given we don't want native logic running for TinyMCE 6 (since it's not compatible with RTC, etc...), then this option provides no longer is useful given the other filtering logic (e.g. Word) has already been removed as well.
Note: I've already checked with QA and Product since removing this isn't in scope of our allowed freeze changes.
Pre-checks:
Review:
=> TINY-8511: Removed the no longer useful paste_filter_drop option

modules/tinymce/src/core/main/ts/api/util/Tools.ts, modules/tinymce/src/core/main/ts/paste/Quirks.ts, modules/tinymce/src/core/test/ts/browser/paste/PasteStylesTest.ts
Related Ticket: TINY-8525
Fixes a regression introduced in https://github.com/tinymce/tinymce/pull/7451/ as the string value passed to `rgbToHex` can be undefined if the styles attribute doesn't have the configured webkit styles to retain. I've largely just made it do what it did previously to solve this, so that it both cleans the value and handles the undefined value since `Tools.trim` will convert a nullable value to an empty string. I also fixed the incorrect types for `Tools.trim` to reflect it takes nullable values.
Pre-checks:
Review:
=> TINY-8525: Fixed a regression with webkit style handling while pasting content

modules/oxide/src/less/skins/ui/dark/content.less, modules/oxide/src/less/skins/ui/default/content.less, modules/oxide/src/less/skins/ui/tinymce-5-dark/content.less
Related Ticket: TINY-8528
* Fix mixed up content styles for dark & light modes
Pre-checks:
Review:
=> TINY-8528: Fix mixed up content styles for dark & light modes

README.md, SECURITY.md, modules/oxide-icons-default/README.md, modules/oxide/README.md, modules/oxide/src/less/skins/ui/dark/content.less, modules/oxide/src/less/skins/ui/default/content.less, modules/oxide/src/less/skins/ui/tinymce-5-dark/content.less, modules/tinymce/CHANGELOG.md, modules/tinymce/README.md, modules/tinymce/src/core/main/ts/Deprecations.ts, modules/tinymce/src/core/main/ts/api/EditorManager.ts, modules/tinymce/src/core/main/ts/api/NotificationManager.ts, modules/tinymce/src/core/main/ts/api/WindowManager.ts, modules/tinymce/src/core/main/ts/api/fmt/StyleFormat.ts, modules/tinymce/src/core/main/ts/api/ui/Registry.ts, modules/tinymce/src/plugins/help/main/ts/ui/PluginsTab.ts, modules/tinymce/src/plugins/help/main/ts/ui/VersionTab.ts, modules/tinymce/src/plugins/quickbars/demo/html/demo.html, yarn.lock
* Updated embedded URL links to docs from within the core source code
* Updated help dialog plugin links to the docs
* Updated docs repo to fill missing landing pages
Pre-checks:
Review:
=> TINY-8441: Updated docs links for 6.0

modules/tinymce/src/core/main/ts/dom/Dimensions.ts, modules/tinymce/src/core/test/ts/browser/dom/DimensionsTest.ts
Related Ticket: TINY-8532
This caused `undefined` to be returned since there was no return statement, which meant the array was something like `[ Object, undefined, Object ]` which threw an exception in `Arr.flatten`. Since non-visible nodes like comments should be ignored and we should always have a return case, I've just updated it to return an empty array.
Pre-checks:
Review:
=> TINY-8532: Fixed an exception getting thrown when clicking in the editor if it had html comments

modules/oxide/src/less/skins/ui/dark/skin.less, modules/oxide/src/less/theme/components/color-swatch/color-swatch.less, modules/oxide/src/less/theme/components/editor/editor.less, modules/oxide/src/less/theme/components/notification/notification.less, modules/oxide/src/less/theme/globals/global-variables.less, modules/tinymce/CHANGELOG.md
Related Ticket: TINY-8527
* Modified Notifications bg, border and text colors to support both dark and light skins
* Header, statusbar and menu dividers made more consistent in dark skin
* Replaced shadows with borders for menu dropdowns in dark skin
* Color picker icon now reacts to menu darker backgrounds in dark skin
Pre-checks:
Review:
GitHub issues:
Fixes [notifications issue #7370](https://github.com/tinymce/tinymce/issues/7370)
Fixes [color picker icon #7369](https://github.com/tinymce/tinymce/issues/7369)
=> TINY-8527: Dark skin fixes

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/api/OptionTypes.ts, modules/tinymce/src/core/main/ts/api/Options.ts, modules/tinymce/src/core/main/ts/textpatterns/TextPatterns.ts, modules/tinymce/src/core/main/ts/textpatterns/core/Pattern.ts, modules/tinymce/src/core/main/ts/textpatterns/keyboard/KeyHandler.ts, modules/tinymce/src/core/main/ts/textpatterns/keyboard/Keyboard.ts, modules/tinymce/src/core/test/ts/atomic/textpatterns/FindBlockPatternsTest.ts, modules/tinymce/src/core/test/ts/browser/textpatterns/FindInlinePatternTest.ts, modules/tinymce/src/core/test/ts/browser/textpatterns/TextPatternsTest.ts
Related Ticket: TINY-8540
Fixed a regression in functionality from 5.x whereby text patterns used to be able to be updated at runtime via the `plugins.textpattern.setPatterns()` API. While we don't want to bring that API back, as this is needed for connections our concession here was to make it so the option value can be updated at runtime and the text pattern logic will instead use the updated value. As such this moves the logic around a little so the options processor does the normalization now instead of doing it separately and we then use the normalized option value when matching the patterns.
Pre-checks:
Review:
=> TINY-8540: Fixed text patterns not able to be updated at runtime

modules/tinymce/CHANGELOG.md, modules/tinymce/src/core/main/ts/keyboard/Autocompleter.ts, modules/tinymce/src/core/test/ts/browser/keyboard/AutocompleterTest.ts, modules/tinymce/src/themes/silver/main/ts/Autocompleter.ts, modules/tinymce/src/themes/silver/main/ts/autocomplete/AutocompleteEditorEvents.ts, modules/tinymce/src/themes/silver/test/ts/browser/editor/autocomplete/AutocompleteTest.ts
Related Ticket: TINY-8552
This fixes an issue whereby the autocompleter wouldn't start correctly which in turn meant the UI state believed the autocompleter wasn't active and therefore wouldn't close the menu. This was largely only an issue when using a throttled fetch function such that the first `fetch` call never ends up resolving.
I've also fixed a very minor regression I noticed in the `esc` key handling as in 5.x it would cancel even when a fetch was running but that's no longer the case and with the 6.x changes it'd only cancel if the UI had been triggered (e.g. the fetch had completed). I'm happy to revert this if we don't think this should happen, but it made sense to me that if you press escape you don't want the menu to pop up after.
Pre-checks:
Review: …
=> TINY-8552: Fixed the autocompleter failing to start and close properly in some cases
