tinymce/tinymce

js/tinymce/plugins/media/plugin.js

Fixed Bug #7387
http://www.tinymce.com/develop/bugtracker_view.php?id=7387

Media plugin - Capital letters in file extension problem (Bug #7387)

---

js/tinymce/classes/html/DomParser.js
tests/tinymce/html/DomParser.js

As per the docs, it should allow the specified classes, not forbid.

fix valid_classes for individual elements

---

js/tinymce/classes/Env.js

Add android constant to the tinymce.Env class to detect if the current os is Android or not

Add android constant to the tinymce.Env class

---

tests/js/utils.js
tests/plugins/image.js
tests/plugins/link.js
tests/plugins/table.js

`getFontmostWindow` -> `getFrontmostWindow`

Fix typo in test helper name

---

js/tinymce/classes/ui/ResizeHandle.js

Fixes http://www.tinymce.com/develop/bugtracker_view.php?id=7563

Fix in adding resize class

---

js/tinymce/plugins/pagebreak/plugin.js

The pagebreaks were editable using the new imagetools, this pr adds the data-attribute to disable that.

Fixed bug where pagebreaks were editable to imagetools.

---

js/tinymce/plugins/charmap/plugin.js

We were in need of a way to be able to show the character map and we are
not utilizing the buttons or menus so the command is the only way to
accomplish this.

add editor command for charmap

---

js/tinymce/themes/modern/theme.js

I am a student who is studying code clones. I try to refactor the code clones in your system and propose the following changes. The proposed changes have passed all unit tests on my machine. Please let me know what you think.
In case the proposed changes do not match your coding style or contain any issues, I would appreciate it if you can let me know how I can improve them. Thank you.

Refactor duplicated callback functions for changed selector

---

js/tinymce/plugins/anchor/plugin.js

When a existing anchor is edited this won't change the anchor but inserts a new anchor. Also when a selection is made and an anchor is inserted it will no longer replace the selection but place the anchor in front of selection.

Fixed editing of an existing anchor.

---

.jshintrc

comments aren't valid in json.

remove commented-out line in .jshintrc

---

js/tinymce/plugins/template/plugin.js

Make the templates in the dialog look the way they will
be displayed in the editor.

Add settings.body_class to template choice dialog.

---

js/tinymce/plugins/media/plugin.js

The media plugin currently does not support dailymotion videos
Fixes issue #2656

add dailymotion urlPattern in media plugin

---

readme.md

some formatting for better readability

updated some formatting for better readability

---

js/tinymce/classes/html/Styles.js
tests/tinymce/html/Styles.js

and filter properties that look suspiciously like an XSS attempt

Add support for escape sequences in CSS property names

---

js/tinymce/plugins/advlist/plugin.js

Use a normal button if there are no options to choose from

---

src/core/src/main/js/keyboard/EnterKey.js

This corrects a couple of issues with hitting the enter key with the caret before and after horizontal rules.
Problem 1:
1. Type a line of text into an empty editor
2. Put the cursor at the start of the line and insert a horizontal rule
3. Hit the up arrow on the keyboard twice (the caret is effectively before the HR)
4. Hit enter, an exception is thrown and the HR is deleted
Expected: no exception and the new line is inserted before the HR
Problem 2:
1. Type a line of text into an empty editor
2. Press enter and type another line of text in
3. Place the caret at the end of line one and insert a horizontal rule
4. Hit the up arrow once (the caret effectively is after the HR)
5. Hit enter, an exception is thrown and the text on line two is deleted
Expected: no exception and the new line is …

Fixed handling for enterkey around HRs

---

changelog.txt

**Before submitting a pull request** please do the following:
1. Fork [the repository](https://github.com/tinymce/tinymce) and create your branch from `master`
2. Have you added some code that should be tested? Write some tests! (Are you unsure how to write the test you want to write, ask us for help!)
3. Ensure that the tests pass: `grunt test`
4. Ensure that your code passes the linter: `grunt lint`
5. Make sure to sign the CLA.

2 dittographies

---

src/skins/lightgray/src/main/less/mobile/app/mobile-icons.less

- Remove reference to missing icon
Fix https://github.com/tinymce/tinymce/issues/3978

Remove reference to missing icon

---

src/core/main/ts/api/Editor.ts

Cleaned up some redundant self assignment statements let over from  when the initialization logic was moved in 1392dd3ed4ba382638768c8612e6c1a49388b46b
Fixes #4557

Cleaned up some redundant self assignment statements

---

Jenkinsfile

I missed updating the 4.x branch to use the new waluigi pipeline library, so 4.x builds are failing at the moment.

Use "waliugi" pipeline library

---

modules/tinymce/changelog.txt
modules/tinymce/src/plugins/image/main/ts/ui/Dialog.ts

Not sure what version this is going in and if it needs a changelog?

FOAM-11 Fix bug with isDecorative checkbox not staying checked on certain actions

---

changelog.txt
package.json
src/core/main/ts/newline/InsertBlock.ts
src/core/test/ts/browser/newline/ForcedRootBlockTest.ts

Original PR for reference: https://github.com/tinymce/tinymce/pull/5412/files

TINY-4564-4x: Backport fix to 4.x

---

modules/alloy/src/main/ts/ephox/alloy/api/behaviour/Dragging.ts
modules/alloy/src/main/ts/ephox/alloy/behaviour/dragging/DraggingApis.ts
modules/alloy/src/main/ts/ephox/alloy/dragging/common/DragMovement.ts
modules/alloy/src/main/ts/ephox/alloy/dragging/common/DragUtils.ts
modules/alloy/src/main/ts/ephox/alloy/dragging/common/DraggingTypes.ts
modules/alloy/src/main/ts/ephox/alloy/dragging/mouse/MouseDragging.ts
modules/alloy/src/main/ts/ephox/alloy/dragging/mouse/MouseDraggingTypes.ts
modules/alloy/src/main/ts/ephox/alloy/dragging/mouseortouch/MouseOrTouchDragging.ts
modules/alloy/src/main/ts/ephox/alloy/dragging/mouseortouch/MouseOrTouchDraggingTypes.ts
modules/alloy/src/main/ts/ephox/alloy/dragging/snap/Presnaps.ts
modules/alloy/src/main/ts/ephox/alloy/dragging/snap/Snappables.ts
modules/alloy/src/main/ts/ephox/alloy/dragging/touch/TouchDragging.ts
modules/alloy/src/main/ts/ephox/alloy/dragging/touch/TouchDraggingTypes.ts
modules/tinymce/src/themes/silver/main/ts/ui/selector/TableSelectorHandles.ts

This was just something I noticed from work @tinydylan has been doing to remove `immutableBag` and it wasn't too hard to improve, so thought I'd open a PR.

Improved the types for alloy dragging, specifically for the extra property

---

modules/alloy/src/main/ts/ephox/alloy/positioning/layout/LayoutBounds.ts

This is just a quick fix for something I realized on the train, as the previous logic would have allowed the layout to place the restriction outside the initial bounds.

TINY-4586: Ensure the layout restriction doesn't escape the specified bounds

---

modules/acid/src/main/ts/ephox/acid/gui/ColourEvents.ts
modules/acid/src/main/ts/ephox/acid/gui/ColourPicker.ts
modules/acid/src/main/ts/ephox/acid/gui/components/HueSlider.ts
modules/acid/src/main/ts/ephox/acid/gui/components/RgbForm.ts
modules/acid/src/main/ts/ephox/acid/gui/components/SaturationBrightnessPalette.ts
modules/robin/src/main/ts/ephox/robin/api/general/Clumps.ts
modules/robin/src/main/ts/ephox/robin/clumps/Clumps.ts
modules/robin/src/main/ts/ephox/robin/smartselect/EndofWord.ts
modules/robin/src/main/ts/ephox/robin/words/Clustering.ts
modules/robin/src/main/ts/ephox/robin/zone/TextZone.ts
modules/robin/src/main/ts/ephox/robin/zone/TextZones.ts
modules/robin/src/test/ts/atomic/clumps/CollectTest.ts
modules/robin/src/test/ts/atomic/words/ClusteringTest.ts
modules/robin/src/test/ts/browser/clumps/ClumpsTest.ts

TINY-4753: Unthunking

---

modules/polaris/src/main/ts/ephox/polaris/pattern/Types.ts
modules/robin/src/main/ts/ephox/robin/api/general/TextSearch.ts
modules/robin/src/main/ts/ephox/robin/clumps/Fractures.ts
modules/robin/src/main/ts/ephox/robin/parent/Breaker.ts
modules/robin/src/main/ts/ephox/robin/textdata/TextSearch.ts
modules/robin/src/main/ts/ephox/robin/zone/LanguageZones.ts
modules/robin/src/main/ts/ephox/robin/zone/Zones.ts
modules/robin/src/test/ts/atomic/parent/BreakerTest.ts
modules/snooker/src/main/ts/ephox/snooker/api/CopySelected.ts
modules/snooker/src/main/ts/ephox/snooker/api/Generators.ts
modules/snooker/src/main/ts/ephox/snooker/api/ResizeDirection.ts
modules/snooker/src/main/ts/ephox/snooker/api/Sizes.ts
modules/snooker/src/main/ts/ephox/snooker/api/Structs.ts
modules/snooker/src/main/ts/ephox/snooker/api/TableGridSize.ts
modules/snooker/src/main/ts/ephox/snooker/api/TableOperations.ts
modules/snooker/src/main/ts/ephox/snooker/api/TableResize.ts
modules/snooker/src/main/ts/ephox/snooker/calc/Deltas.ts
modules/snooker/src/main/ts/ephox/snooker/lookup/Blocks.ts
modules/snooker/src/main/ts/ephox/snooker/model/RunOperation.ts
modules/snooker/src/main/ts/ephox/snooker/model/Transitions.ts
modules/snooker/src/main/ts/ephox/snooker/model/Warehouse.ts
modules/snooker/src/main/ts/ephox/snooker/operate/Redraw.ts
modules/snooker/src/main/ts/ephox/snooker/resize/Adjustments.ts
modules/snooker/src/main/ts/ephox/snooker/resize/BarPositions.ts
modules/snooker/src/main/ts/ephox/snooker/resize/Bars.ts
modules/snooker/src/main/ts/ephox/snooker/resize/Recalculations.ts
modules/snooker/src/test/ts/atomic/model/WarehouseTest.ts
modules/snooker/src/test/ts/atomic/resize/RecalculationsTest.ts
modules/sugar/src/main/ts/ephox/sugar/api/view/Position.ts

Also note the efficiency fix in RunOperation.findInWarehouse

TINY-4753-3: More unthunking

---

modules/tinymce/src/themes/silver/main/ts/modes/Iframe.ts

@jhaines found that image resize handles weren't being repositioned in iframe mode and it turns out to be because we weren't firing the `ResizeContent` event since we were only storing the size changes on `load` events.

TINY-4732: Fixed iframe resize content event not being fired when the content resizes

---

modules/tinymce/changelog.txt
modules/tinymce/src/core/main/ts/selection/RangeWalk.ts
modules/tinymce/src/core/test/ts/browser/fmt/RemoveHighlightFormatTest.ts

TINY-4770: Clamped child node selection, added tests.

---

.eslintrc.json
modules/agar/src/main/ts/ephox/agar/datatransfer/DataTransfer.ts
modules/alloy/src/main/ts/ephox/alloy/debugging/FunctionAnnotator.ts
modules/alloy/src/main/ts/ephox/alloy/foreign/ForeignCache.ts
modules/alloy/src/test/ts/browser/api/CustomComponentTest.ts
modules/alloy/src/test/ts/browser/ui/form/FieldsTest.ts
modules/imagetools/src/main/ts/ephox/imagetools/meta/BinaryReader.ts
modules/imagetools/src/main/ts/ephox/imagetools/meta/BinaryReaderUtils.ts
modules/imagetools/src/main/ts/ephox/imagetools/meta/ExifReader.ts
modules/imagetools/src/main/ts/ephox/imagetools/meta/JPEGMeta.ts
modules/katamari/src/main/ts/ephox/katamari/api/Obj.ts
modules/katamari/src/main/ts/ephox/katamari/api/Unicode.ts
modules/katamari/src/test/ts/atomic/api/str/StringMatchTest.ts
modules/tinymce/src/core/main/ts/NodeChange.ts
modules/tinymce/src/core/main/ts/api/Editor.ts
modules/tinymce/src/core/main/ts/api/EditorCommands.ts
modules/tinymce/src/core/main/ts/api/Shortcuts.ts
modules/tinymce/src/core/main/ts/api/dom/EventUtils.ts
modules/tinymce/src/core/main/ts/api/dom/ScriptLoader.ts
modules/tinymce/src/core/main/ts/api/dom/TreeWalker.ts
modules/tinymce/src/core/main/ts/api/html/Node.ts
modules/tinymce/src/core/main/ts/api/util/EventDispatcher.ts
modules/tinymce/src/core/main/ts/api/util/JSONRequest.ts
modules/tinymce/src/core/main/ts/api/util/URI.ts

@typescript-eslint/no-non-null-assertion
@typescript-eslint/no-inferrable-types
@typescript-eslint/no-for-in-array
@typescript-eslint/explicit-member-accessibility

TINY-4780: Enabled 4 lints

---

modules/tinymce/changelog.txt
modules/tinymce/src/themes/silver/main/ts/ContextToolbar.ts
modules/tinymce/src/themes/silver/main/ts/ui/context/ContextForm.ts
modules/tinymce/src/themes/silver/main/ts/ui/context/ContextToolbarLookup.ts
modules/tinymce/src/themes/silver/main/ts/ui/context/ContextToolbarScopes.ts
modules/tinymce/src/themes/silver/test/ts/browser/editor/contexttoolbar/ContextToolbarLookupPositionPriorityTest.ts
modules/tinymce/src/themes/silver/test/ts/browser/editor/contexttoolbar/ContextToolbarLookupPrioritisationTest.ts
modules/tinymce/src/themes/silver/test/ts/browser/editor/contexttoolbar/ContextToolbarLookupTest.ts

There's 2 TODOs in here that I need to check properly yet, but I also kind of wanted feedback on them so making this now.

TINY-4495: Concat context toolbars

---

modules/alloy/src/main/ts/ephox/alloy/api/Main.ts

One of the premium plugins needs this exposed.

Expose AriaVoice on Alloy.

---

modules/acid/package.json
modules/agar/package.json
modules/alloy/changelog.md
modules/alloy/package.json
modules/boss/package.json
modules/boulder/package.json
modules/bridge/package.json
modules/darwin/package.json
modules/dragster/package.json
modules/imagetools/package.json
modules/jax/package.json
modules/katamari-assertions/package.json
modules/katamari/package.json
modules/mcagar/package.json
modules/oxide-icons-default/package.json
modules/oxide/package.json
modules/phoenix/package.json
modules/polaris/package.json
modules/porkbun/package.json
modules/robin/package.json
modules/sand/package.json
modules/snooker/package.json
modules/sugar/package.json
modules/tinymce/changelog.txt

TINY-5949: Update monorepo for 5.3.0 release v2

---

SECURITY.md

This just adds a basic SECURITY.md file to make it clearer about supported versions and how to report security issues.

TINY-5945: Added SECURITY.md

---

modules/tinymce/changelog.txt

TINY-6029: Bumped changelog for 5.3.1 release

---

modules/tinymce/changelog.txt
modules/tinymce/src/plugins/table/main/ts/ui/MenuItems.ts

Registred all the ones that I could find which weren't auto-generated from some input.

TINY-4866: Registred spec-defined menuitems.

---

.github/PULL_REQUEST_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Currently, a number of common things are forgotten and this is used by other teams, so I thought it might help us as well. If anyone can think of something extra to add, let me know.

Updated PR template and moved it to where GitHub would recognise it

---

CONTRIBUTING.md
modules/tinymce/src/core/main/json/globals.json
modules/tinymce/src/core/main/ts/api/Tinymce.ts

* Move StyleSheetLoader to correct package.
Pre-checks:
Review:

Move StyleSheetLoader to correct package.

---

modules/tinymce/src/core/main/ts/api/dom/DOMUtils.ts
modules/tinymce/src/core/test/ts/browser/dom/DomUtilsTest.ts

Related Ticket: TINY-6087
This function had special handling for bogus behaviour of browsers we no longer support. This change removes the special handling and tests that the bogus behaviours don't occur.
Pre-checks:
Review:

Simplify DOMUtils.get

---

modules/tinymce/src/core/demo/html/shadow_dom_demo.html
modules/tinymce/src/core/demo/ts/demo/Demos.ts
modules/tinymce/src/core/demo/ts/demo/ShadowDomDemo.ts

Related Ticket: TINY-6111
* Just a demo page to help test some Shadow DOM work.
Pre-checks:
Review:

Add Shadow DOM demo page for experimental testing.

---

modules/katamari/src/main/ts/ephox/katamari/api/LazyValues.ts
modules/katamari/src/test/ts/atomic/api/async/LazyValueTest.ts

* New function: LazyValues.withTimeout. I found this useful when experimenting with rewriting StyleSheetLoader.
Pre-checks:
Review:

LazyValues.withTimeout

---

modules/tinymce/changelog.txt
modules/tinymce/src/plugins/autosave/main/ts/core/Storage.ts
modules/tinymce/src/plugins/autosave/test/ts/browser/AutoSavePluginTest.ts

Now reuses element detection.
Pre-checks:
Review:
Fixes https://github.com/tinymce/tinymce/issues/5328

TINY-5953: Autosave now more accurate on empty detection.

---

modules/tinymce/src/core/test/ts/atomic/text/ZwspTest.ts
modules/tinymce/src/core/test/ts/browser/FormatterRemoveTest.ts
modules/tinymce/src/core/test/ts/browser/MiscCommandsTest.ts
modules/tinymce/src/core/test/ts/browser/fmt/PreviewTest.ts

Related Ticket: TINY-6135
* Replace some usages of LegacyUnit
Pre-checks:
Review:

Replace some usages of LegacyUnit

---

modules/alloy/src/main/ts/ephox/alloy/behaviour/disabling/ActiveDisable.ts
modules/alloy/src/main/ts/ephox/alloy/spec/SpecSchema.ts
modules/alloy/src/main/ts/ephox/alloy/ui/single/TieredMenuSpec.ts
modules/alloy/src/main/ts/ephox/alloy/ui/types/ContainerTypes.ts
modules/alloy/src/main/ts/ephox/alloy/ui/types/DropdownTypes.ts
modules/alloy/src/test/ts/browser/behaviour/DisablingTest.ts

Related Ticket: TINY-6127
* While prepping for the TS 3.9 upgrade, it found a few bugs. We don't plan to do the upgrade until after 5.4 has been released, so this just backports those fixes so they can be included now.
Pre-checks:
Review:

TINY-6127: Fixed alloy bugs/issues found while attempting to upgrade to TS 3.9

---

modules/tinymce/src/core/demo/html/shadow_dom_closed_demo.html
modules/tinymce/src/core/demo/html/shadow_dom_open_demo.html
modules/tinymce/src/core/demo/ts/demo/ShadowDomDemo.ts

Related Ticket: TINY-6148
* Test pages
Pre-checks:
Review:

Split shadow dom demo page into one for open, one for closed.

---

modules/agar/src/main/ts/ephox/agar/api/TestLogs.ts
modules/agar/src/test/ts/atomic/api/TestLogsTest.ts
modules/alloy/src/main/ts/ephox/alloy/api/testhelpers/GuiSetup.ts
modules/mcagar/src/main/ts/ephox/mcagar/api/TinyLoader.ts
modules/mcagar/src/main/ts/ephox/mcagar/api/TinyUi.ts
modules/mcagar/src/test/ts/browser/api/TinyLoaderTest.ts
modules/sugar/src/test/ts/browser/ShadowDomTest.ts
modules/sugar/src/test/ts/module/ephox/sugar/test/WithHelpers.ts
modules/tinymce/src/core/test/ts/browser/init/ShadowDomEditorTest.ts
modules/tinymce/src/plugins/advlist/test/ts/browser/ChangeListStyleTest.ts
modules/tinymce/src/themes/silver/test/ts/browser/editor/color/ColorPickerSanityTest.ts
modules/tinymce/src/themes/silver/test/ts/browser/editor/color/TextColorFormattingTest.ts

Related Ticket: TINY-6130
* Helper functions in alloy and mcagar
Pre-checks:
Review:

Add helper functions for testing shadow dom scenarios

---

modules/tinymce/changelog.txt

Related Ticket: DOC-603
* Suggested changes to 5.4 changelog
Pre-checks:
Review:

DOC-603: suggested changes for TinyMCE 5.4 changelog

---

.github/ISSUE_TEMPLATE/bug_report.md

* Updated the Fiddle URL on GitHub's Bug Reports
Pre-checks:
Review:

Updated the Fiddle URL on GitHub's Bug Reports.

---

modules/tinymce/src/core/main/ts/api/ui/Registry.ts

Related Ticket: https://github.com/tinymce/tinymce-docs/issues/1583
* Add example to addIcon API
Pre-checks:
Review:
GitHub issues (if applicable): https://github.com/tinymce/tinymce-docs/issues/1583

tinymce-docs#1583: Add example to addIcon API

---

.github/CODEOWNERS

* It's time. I haven't really reviewed PRs in a while, and I don't think I need to remain on the auto-reviewer list.

Remove myself as a codeowner

---

modules/tinymce/src/core/main/ts/api/EditorCommands.ts

Related Ticket: DOC-571
* Fixing the return type documented for the `queryCommandValue` API.
* Improving wording on command API docs.
Pre-checks:
Review:

DOC-571: Minor edits to command API docs.

---

modules/tinymce/changelog.txt
modules/tinymce/src/plugins/table/main/ts/actions/TableActions.ts
modules/tinymce/src/plugins/table/main/ts/core/TableSections.ts
modules/tinymce/src/plugins/table/test/ts/browser/SwitchTableSectionTest.ts
modules/tinymce/src/plugins/table/test/ts/browser/TableSectionApiTest.ts
modules/tinymce/src/plugins/table/test/ts/browser/ui/TableRowDialogTest.ts

TINY-6206 Fix bug with header rows not using scope attribute

---

modules/tinymce/changelog.txt

* Minor change to 5.4.1 changelog
Pre-checks:
Review:

Minor suggested change to 5.4.1 changelog

---

modules/tinymce/changelog.txt

Related Ticket: TINY-6215
* Updated the changelog for TinyMCE 5.4.1 release
Pre-checks:
Review:

TINY-6215: Updated changelog for 5.4.1 release

---

modules/tinymce/changelog.txt
modules/tinymce/src/plugins/imagetools/main/ts/ui/Buttons.ts

Related Ticket: TINY-4141
Pre-checks:
Review:

TINY-4141: Changed imagetools context menu item icon.

---

changelog.txt

Related Ticket: TINY-6231
* Added the changelog date for 4.9.11
Pre-checks:
Review:

TINY-6231: Updated changelog for 4.9.11 release

---

modules/tinymce/src/core/main/ts/api/util/Tools.ts
modules/tinymce/src/core/main/ts/api/util/XHR.ts

Related Ticket: https://github.com/tinymce/tinymce-docs/issues/1619
* Updated XHR send API docs.
* Updated XHR send data type cos @lnewson said.
Pre-checks:
Review:
GitHub issues (if applicable): https://github.com/tinymce/tinymce-docs/issues/1619

ghdocs#1619: Add docs for XHR send API

---

modules/tinymce/changelog.txt
modules/tinymce/src/core/main/ts/api/dom/DOMUtils.ts
modules/tinymce/src/core/main/ts/api/html/Node.ts
modules/tinymce/src/core/main/ts/dom/Empty.ts
modules/tinymce/src/core/main/ts/dom/TrimNode.ts
modules/tinymce/src/core/main/ts/newline/InsertBlock.ts
modules/tinymce/src/core/main/ts/text/Whitespace.ts
modules/tinymce/src/core/test/ts/browser/dom/DomUtilsTest.ts
modules/tinymce/src/core/test/ts/browser/fmt/RemoveFormatTest.ts

Fixed an issue where spaces would sometimes be deleted when removing formating from nearby text.
Pre-checks:
Review:

TINY-6251: Fixed issue of spaces sometimes being deleted.

---

modules/tinymce/changelog.txt

Related Ticket: DOC-621
* Suggested changes to 5.4.2 changelog entries
Pre-checks:
Review:

DOC-621: Suggested changes to 5.4.2 changelog entries

---

modules/tinymce/changelog.txt

Related Ticket: TINY-6313
* Updating the changelog date for 5.4.2 community release. tinymce package.json version is already correct.
Review:

Update changelog date for release

---

modules/phoenix/src/demo/ts/ephox/phoenix/demo/ReuseDemo.ts
modules/sugar/src/demo/ts/ephox/sugar/demo/Demo.ts
modules/sugar/src/main/ts/ephox/sugar/api/node/SugarElement.ts
modules/sugar/src/main/ts/ephox/sugar/api/search/Traverse.ts
modules/sugar/src/main/ts/ephox/sugar/api/selection/WindowSelection.ts
modules/tinymce/src/core/main/ts/api/dom/Selection.ts

* Just noticed some types were incorrect, so this fixes them up.
Pre-checks:
Review:

Fixed some incorrect types

---

modules/tinymce/src/core/main/ts/api/dom/DOMUtils.ts

* Improve description on DOMUtils.select
Pre-checks:
Review:

Improve description on DOMUtils.select

---

modules/tinymce/tools/docs/tinymce.editor.ui.Ui.js

Related Ticket: DOC-642 & TINY-4847
* Updated API docs for the `tinymce.editor.ui.show` and `tinymce.editor.ui.hide` methods.
Pre-checks:
Review:

DOC-642: Suggested edits to ui.hide/show API docs

---

modules/tinymce/src/core/main/ts/api/EditorUpload.ts
modules/tinymce/src/core/test/ts/browser/EditorUploadTest.ts

TINY-6011: Now replacing images with a dummy one.

---

modules/tinymce/changelog.txt

* Suggested changes to 5.5.0 changelog
Pre-checks:
Review:

Suggested changes for 5.5.0 changelog

---

modules/tinymce/changelog.txt
modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialogHeader.ts

Fixed dialog using hard-coded icon.
Pre-checks:
Review:

TINY-6445: Retrieve close icon from icon provider

---

modules/tinymce/src/themes/silver/main/ts/ui/core/LineHeight.ts

Related Ticket: TINY-4843
* Removed the icon from the dropdown menu
Pre-checks:
~* [ ] Branch prefixed with `feature/` for new features (if applicable)~
~* [ ] License headers added on new files (if applicable)~
Review:

TINY-4843: Remove line-height icon

---

modules/tinymce/changelog.txt

Related Ticket: DOC-650
* minor changes to changelog
Pre-checks:
Review:

DOC-650: changelog changes

---

modules/tinymce/changelog.txt

Related Ticket: TINY-6473
* Update changelog date for 5.1.1 release
Pre-checks:
Review:

TINY-6473: Update changelog date for 5.1.1 release

---

modules/robin/src/main/ts/ephox/robin/zone/ZoneWalker.ts
modules/robin/src/test/ts/atomic/zone/InViewportTest.ts

Related Ticket: TINY-6412
* A more minimal rewrite of #6091 - the full restructure of ZoneWalker will happen, but it will happen in a separate PR, targeting develop instead of master.
Pre-checks:
Review:
* ~[ ] Milestone set~

TINY-6412: Stopped ZoneWalker from passing the end node

---

modules/snooker/src/main/ts/ephox/snooker/api/TableFill.ts
modules/snooker/src/test/ts/browser/CopyAttributesTest.ts
modules/tinymce/changelog.txt

Some attributes were not copied over when they should be.
Pre-checks:
Review:

TINY-6485: Now copy over attributes for TDs.

---

modules/tinymce/src/core/main/ts/api/Formatter.ts

Related Ticket: DOC-687
* Minor API Docs edit
Pre-checks:
Review:

DOC-687: Minor API docs edit

---

modules/darwin/package.json
modules/robin/package.json
modules/robin/src/main/ts/ephox/robin/zone/ZoneWalker.ts
modules/robin/src/test/ts/atomic/zone/InViewportTest.ts
modules/snooker/package.json
modules/tinymce/changelog.txt

Related Ticket: TINY-6412
* This is (hopefully) the final fix for TINY-6412. It ports the logic from the
quick-and-nasty fix (2e488122fb) to the nice and refactored version (commits
6307e569a4 to 75b96db74f).
Pre-checks:
* ~[ ] Changelog entry added~ _robin doesn't have a changelog_
Review:
* ~[ ] Milestone set~

Tiny 6412 3

---

modules/tinymce/changelog.txt
modules/tinymce/src/core/main/ts/api/SettingsTypes.ts
modules/tinymce/src/core/main/ts/api/html/DomParser.ts
modules/tinymce/src/core/main/ts/api/html/SaxParser.ts
modules/tinymce/src/core/main/ts/init/InitContentBody.ts
modules/tinymce/src/core/test/ts/browser/html/SaxParserTest.ts

Related Ticket: TINY-6518
* Fixes a security issue reported for certain URLs in attributes.
* Fixed a setting not being passed through correctly.
Pre-checks:
Review:

TINY-6518: Fixed a security issue where urls in attributes weren't correctly sanitized

---

modules/tinymce/src/plugins/paste/main/ts/core/Clipboard.ts

Changes handling of paste events to fix bugs in IE11 (https://github.com/tinymce/tinymce/issues/4905)
* Flag to specify that the paste event was triggered from the keyboard will now only be cleared when the paste event is fired, this is because IE sometimes shows a popup asking for permission to access the clipboard, making the delay between keydown and paste much more than 100ms
* If a paste event is fired while the Ctrl-V keys are still pressed, this will be treated as a keyboard paste, this is because it seems that when you press the Ctrl-V keys fast enough, or keep them pressed down, IE does not fire keydown, this means the second paste event fired will not be treated as a keyboard paste, which causes an infinite loop

Handling of keyboard paste events

---

modules/snooker/src/main/ts/ephox/snooker/api/TableOperations.ts
modules/snooker/src/test/ts/browser/HeaderOperationsTest.ts
modules/snooker/src/test/ts/module/ephox/snooker/test/Assertions.ts
modules/tinymce/changelog.txt
modules/tinymce/src/plugins/table/main/ts/actions/TableActions.ts
modules/tinymce/src/plugins/table/main/ts/api/Commands.ts
modules/tinymce/src/plugins/table/test/ts/browser/TableSectionApiTest.ts
versions.txt

We can now change one or more columns to headers.
Pre-checks:
Review:

TINY-6326: Now converts several columns at once.

---

modules/tinymce/changelog.txt

* Suggested edits to changelog
Pre-checks:
Review:

5.6.0 suggested edits

---

modules/tinymce/src/core/main/ts/api/EditorUpload.ts
modules/tinymce/src/core/test/ts/browser/EditorUploadTest.ts

Related Ticket: TINY-6586
* An attempt at making sure a change event is only fired on uploads, if the last undo level has actually changed.
Pre-checks:
Review:

TINY-6586: Fixed multiple change events fired in some cases

---

modules/tinymce/src/themes/silver/main/ts/Render.ts

Shadowdom is also causing trouble, so no resize for it either.
Pre-checks:
Review:

TINY-6683: No sink resize on shadowdom either.

---

modules/tinymce/changelog.txt

* 5.6.1 changelog suggestions
Pre-checks:
Review:

5.6.1 changelog suggestions

---

modules/tinymce/Gruntfile.js
modules/tinymce/changelog.txt
modules/tinymce/package.json

Related Ticket: TINY-6693
* Bumped version and changelog for release
* Updated the company name in the various dist packages, since @JamesToohey pointed out these were outdated
Review:

TINY-6693: Bumped version and changelog for release

---

modules/tinymce/src/core/main/ts/api/util/ImageUploader.ts
modules/tinymce/src/core/main/ts/file/Uploader.ts
modules/tinymce/src/core/test/ts/browser/UndoManagerTest.ts
modules/tinymce/src/themes/silver/test/ts/phantom/components/htmlpanel/HtmlPanelTest.ts

Related Ticket: TINY-6732
* Fixes a number of tests that were silently failing or were calling `success` multiple times. These were picked up by the new version of bedrock I've been working on.
Pre-checks:
Review:

Fixed silently failing tests

---

modules/agar/src/main/ts/ephox/agar/api/DragnDrop.ts
modules/agar/src/main/ts/ephox/agar/api/FocusTools.ts
modules/agar/src/main/ts/ephox/agar/api/Mouse.ts
modules/agar/src/main/ts/ephox/agar/api/UiControls.ts
modules/alloy/src/test/ts/browser/events/GuiEventsTest.ts
modules/mcagar/src/main/ts/ephox/mcagar/api/Editor.ts
modules/mcagar/src/main/ts/ephox/mcagar/loader/Loader.ts
modules/tinymce/src/core/main/ts/ErrorReporter.ts
modules/tinymce/src/core/main/ts/api/Editor.ts
modules/tinymce/src/core/main/ts/api/html/Node.ts
modules/tinymce/src/core/main/ts/api/html/Writer.ts
modules/tinymce/src/core/main/ts/bookmark/CaretBookmark.ts
modules/tinymce/src/core/main/ts/bookmark/ResolveBookmark.ts
modules/tinymce/src/core/main/ts/caret/TableCells.ts
modules/tinymce/src/core/main/ts/dom/ElementType.ts
modules/tinymce/src/core/main/ts/fmt/ExpandRange.ts
modules/tinymce/src/core/test/ts/browser/init/InitEditorPluginInitErrorTest.ts
modules/tinymce/src/plugins/image/main/ts/ui/Dialog.ts

Related Ticket: TINY-6732
* Fixes a few minor issues found (eg unhandled promise rejection or tests not running).
* Adds some types to things I needed for the test conversion.
Pre-checks:
Review:

TINY-6732: Various fixes and type improvements found while converting tests

---

README.md

Related Ticket: DOC-745
* Apply README updates based on marketing feedback
Pre-checks:
Review:

DOC-745: Apply README changes from marketing

---

modules/tinymce/changelog.txt
package.json
yarn.lock

Related Ticket: TINY-6996
* Pulls in fixes for performance issues with some syntax in certain languages.
Pre-checks:
Review:

TINY-6996: Upgrade to latest PrismJS to pull in the latest fixes

---

modules/tinymce/changelog.txt

Related Ticket: DOC-761
* Suggested edits to the 5.7 changelogs
Pre-checks:
Review:

DOC-761: Suggested edits to the 5.7 changelogs

---

modules/acid/package.json
modules/agar/package.json
modules/alloy/package.json
modules/boss/package.json
modules/boulder/package.json
modules/bridge/package.json
modules/darwin/package.json
modules/dragster/package.json
modules/imagetools/package.json
modules/jax/package.json
modules/katamari-assertions/package.json
modules/katamari/package.json
modules/mcagar/package.json
modules/oxide/package.json
modules/phoenix/package.json
modules/polaris/package.json
modules/porkbun/package.json
modules/robin/package.json
modules/sand/package.json
modules/snooker/package.json
modules/sugar/package.json
modules/tinymce/changelog.txt
versions.txt

Related Ticket: TINY-6981
* Bump module versions
* Added changelog date
Review:

TINY-6981: Prepare 5.7.0 release

---

modules/katamari/README.md

* Tidy up Katamari readme
Pre-checks:
Review:

Tidy up Katamari readme

---

modules/mcagar/README.md
modules/mcagar/docs/bdd.md
modules/mcagar/docs/pipelines.md

* This adds some initial documentation and examples on how to use the new BDD logic added to McAgar.
Pre-checks:
Review:

Adding McAgar documentation for using the BDD tests

---

modules/tinymce/changelog.txt
modules/tinymce/package.json
modules/tinymce/src/core/main/ts/api/html/SaxParser.ts
modules/tinymce/src/core/test/ts/browser/html/SaxParserTest.ts

Related Ticket: TINY-7025
* Fixed an issue where URLs were not correctly filtered in some cases
Pre-checks:
Review:

TINY-7025: Fixed an issue where URLs were not correctly filtered in some cases

---

modules/tinymce/changelog.txt

* 5.7.1 changelog suggested changes
Pre-checks:
Review:

5.7.1 changelog suggested changes

---

modules/tinymce/src/themes/silver/test/ts/browser/editor/contexttoolbar/ContextToolbarLookupTest.ts
yarn.lock

Related Ticket: TINY-7167
* There was a messy test flake, that's going to need a bit more investigation
* It needs more investigation, but for now this is a workaround
Pre-checks:
Review:

TINY-7167: Patch the flaky test, and leave a TODO for future investigations

---

modules/tinymce/changelog.txt

TINY-7149
5.7.1 Release
Review:

TINY-7149: 5.7.1 Release

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/plugins/table/main/ts/Plugin.ts
modules/tinymce/src/plugins/table/main/ts/queries/TabContext.ts
modules/tinymce/src/plugins/table/test/ts/browser/TabKeyNavigationTest.ts

Related Ticket: TINY-7006
Pre-checks:
* ~[] License headers added on new files (if applicable)~
Review:

TINY-7006: Fire TableModified event when rows are added via Tab key

---

modules/bridge/src/demo/ts/dialogs/TableCellDialog.ts
modules/tinymce/CHANGELOG.md
modules/tinymce/src/plugins/table/main/ts/ui/CellDialogGeneralTab.ts
modules/tinymce/src/plugins/table/test/ts/browser/ui/TableCellDialogTest.ts
modules/tinymce/src/themes/silver/demo/ts/dialogs/spec/TableCellDialogSpec.ts

TINY-7285 Switch V/H Align to Vertical and Horizontal align

---

modules/tinymce/src/plugins/legacyoutput/test/ts/browser/LegacyOutputPluginTest.ts

* Refactor plugins to BDD-style tests
Pre-checks:
Review:

feature/TINY-7119: BDD conversion Legacy Output

---

modules/tinymce/src/plugins/insertdatetime/test/ts/browser/InsertDatetimeSanityTest.ts

Related Ticket: [7052](https://ephocks.atlassian.net/secure/RapidBoard.jspa?rapidView=116&modal=detail&selectedIssue=TINY-7052)
* Refactor plugins to BDD-style tests
Pre-checks:
Review:

feature/TINY-7052: BDD conversion: Insert Date Time

---

modules/tinymce/src/plugins/template/test/ts/browser/DatesTest.ts
modules/tinymce/src/plugins/template/test/ts/browser/DialogGetPreviewContentTest.ts
modules/tinymce/src/plugins/template/test/ts/browser/InvalidUrlTest.ts
modules/tinymce/src/plugins/template/test/ts/browser/SelectedContentTest.ts
modules/tinymce/src/plugins/template/test/ts/browser/TemplateSanityTest.ts
modules/tinymce/src/plugins/template/test/ts/module/InsertTemplate.ts
modules/tinymce/src/plugins/template/test/ts/module/Settings.ts

Related Ticket: TINY-7319
Pre-checks:
~* [ ] License headers added on new files (if applicable)~
Review:

TINY-7319: BDD conversion: Template

---

.github/PULL_REQUEST_TEMPLATE.md
modules/tinymce/.eslintrc.json
modules/tinymce/copyright-header.js
modules/tinymce/src/core/main/ts/events/TouchEvents.ts
modules/tinymce/src/core/main/ts/keyboard/FormatShortcuts.ts
modules/tinymce/src/core/main/ts/text/CharType.ts
modules/tinymce/src/plugins/fullscreen/main/ts/core/Thor.ts
modules/tinymce/src/plugins/preview/main/ts/api/Settings.ts
modules/tinymce/src/plugins/table/main/ts/selection/SelectionTargets.ts
modules/tinymce/src/themes/silver/main/ts/backstage/Anchors.ts
modules/tinymce/src/themes/silver/main/ts/ui/dialog/Dialogs.ts
modules/tinymce/src/themes/silver/main/ts/ui/menus/contextmenu/platform/DesktopContextMenu.ts
modules/tinymce/src/themes/silver/main/ts/ui/menus/contextmenu/platform/MobileContextMenu.ts
modules/tinymce/src/themes/silver/main/ts/ui/menus/item/build/NestedMenuItem.ts
modules/tinymce/src/themes/silver/main/ts/ui/menus/menu/MenuUtils.ts
modules/tinymce/src/themes/silver/main/ts/ui/selector/TableSelectorHandles.ts
package.json
yarn.lock

* Added linting rules to check we have the relevant license headers, which means it's no longer something we need to review/include in pre-checks.
* Fixed issues found where headers were missing or were missing a new line between them and the imports.
Pre-checks:
Review:

Added copyright header linting rules and fixed issues

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/plugins/paste/main/ts/core/WordFilter.ts
modules/tinymce/src/plugins/paste/test/ts/browser/PasteTest.ts

* Follow up to #6689 to add a changelog entry
Pre-checks:
Review:
Fixes #6620

TINY-7368: Fixed roman numeral detection with copy-paste from Word

---

Jenkinsfile

Related Ticket: TINY-7396
* Upgrade the CI Jenkinsfile build to make sure the primary branch runs all tests regardless of lerna change detection.
* Upgrade to latest waluigi version
Pre-checks:
Review:

TINY-7396: Ensure the primary branch runs all tests, not just tests with changes

---

modules/tinymce/CHANGELOG.md

Related Ticket: DOC-821
* Suggested changelog edits
Pre-checks:
Review:

DOC-821: 5.8.0 changelog suggestions

---

SECURITY.md
modules/acid/package.json
modules/agar/package.json
modules/alloy/CHANGELOG.md
modules/alloy/package.json
modules/boss/package.json
modules/boulder/package.json
modules/bridge/package.json
modules/darwin/package.json
modules/dragster/package.json
modules/imagetools/package.json
modules/jax/package.json
modules/katamari-assertions/package.json
modules/katamari/CHANGELOG.md
modules/katamari/package.json
modules/mcagar/package.json
modules/oxide/package.json
modules/phoenix/package.json
modules/polaris/package.json
modules/porkbun/package.json
modules/robin/package.json
modules/sand/package.json
modules/snooker/package.json
modules/sugar/package.json
modules/tinymce/CHANGELOG.md
versions.txt

Related Ticket: TINY-7363
Pre-checks:
Review:

TINY-7363: Update files and versions for 5.8 community release

---

modules/tinymce/src/themes/silver/main/ts/ui/toolbar/button/ToolbarButtons.ts
modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/ReadonlyToolbarResizeTest.ts

Related Ticket: TINY-6383
* Fixed another case that was causing exceptions by adding a system isConnected check
Note: This is only a stop-gap solution until we can fix the root cause in 5.9.0 (see https://github.com/tinymce/tinymce/pull/6805).
Pre-checks:
Review:

TINY-6383: Fixed another case that was causing exceptions

---

modules/tinymce/CHANGELOG.md

Related Ticket: DOC-827
* suggested 5.8.1 changelog edits
Pre-checks:
Review:

suggested 5.8.1 changelog edits

---

modules/tinymce/CHANGELOG.md

Related Ticket: TINY-7300
* Update changelog in preparation for community release 5.8.1
Pre-checks:
Review:

TINY-7300: Update TinyMCE changelog

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/plugins/table/main/ts/core/TableFormats.ts
modules/tinymce/src/plugins/table/main/ts/ui/Buttons.ts
modules/tinymce/src/plugins/table/main/ts/ui/CellAlignValues.ts
modules/tinymce/src/plugins/table/main/ts/ui/CellDialogGeneralTab.ts
modules/tinymce/src/plugins/table/main/ts/ui/MenuItems.ts
modules/tinymce/src/plugins/table/main/ts/ui/UiUtils.ts
modules/tinymce/src/plugins/table/test/ts/browser/ui/TableValignButtonsTest.ts

* Added button for vertical alignment in table cells.
Pre-checks:
Review:

TINY-7477: Added valign button

---

modules/robin/CHANGELOG.md
modules/robin/src/main/ts/ephox/robin/api/general/TextZones.ts
modules/robin/src/main/ts/ephox/robin/api/general/Words.ts
versions.txt

* Export some types from Robin so that we're able to import them directly instead of using weird `ReturnType` shenanigans
Pre-checks:
Review:

Exported more types from robin

---

modules/tinymce/src/core/main/ts/api/html/DomParser.ts
modules/tinymce/src/core/main/ts/commands/FontCommands.ts
modules/tinymce/src/core/main/ts/commands/IndentOutdent.ts
modules/tinymce/src/core/main/ts/commands/LineHeight.ts
modules/tinymce/src/core/main/ts/content/ContentTypes.ts
modules/tinymce/src/core/main/ts/content/GetContentImpl.ts
modules/tinymce/src/core/main/ts/content/InsertContent.ts
modules/tinymce/src/core/main/ts/content/InsertContentImpl.ts
modules/tinymce/src/core/main/ts/content/InsertList.ts
modules/tinymce/src/core/main/ts/content/Placeholder.ts
modules/tinymce/src/core/main/ts/content/SetContent.ts
modules/tinymce/src/core/main/ts/content/SetContentImpl.ts

This is a follow on from https://github.com/tinymce/tinymce/pull/6806, so same situation as then whereby this is just trying to get more types declared in core. This isn't meant to be an exhaustive conversion and certainly somethings aren't typed still (should only be variables inside functions).
Pre-checks:
Review:

Added return types and fixed no implicit any errors for modules in the commands and content directories

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/plugins/table/main/ts/api/Settings.ts
modules/tinymce/src/plugins/table/main/ts/ui/Buttons.ts
modules/tinymce/src/plugins/table/main/ts/ui/CellDialog.ts
modules/tinymce/src/plugins/table/main/ts/ui/DialogAdvancedTab.ts
modules/tinymce/src/plugins/table/main/ts/ui/Helpers.ts
modules/tinymce/src/plugins/table/main/ts/ui/MenuItems.ts
modules/tinymce/src/plugins/table/main/ts/ui/RowDialog.ts
modules/tinymce/src/plugins/table/main/ts/ui/TableDialog.ts
modules/tinymce/src/plugins/table/main/ts/ui/UiUtils.ts
modules/tinymce/src/plugins/table/test/ts/browser/ui/TableBorderStyleTest.ts
modules/tinymce/src/plugins/table/test/ts/browser/ui/TableBorderWidthTest.ts
modules/tinymce/src/plugins/table/test/ts/browser/ui/TableClassListButtonsTest.ts
modules/tinymce/src/plugins/table/test/ts/browser/ui/TableValignButtonsTest.ts
modules/tinymce/src/plugins/table/test/ts/module/test/TableModifiersTestUtils.ts

Added cell border and style
Pre-checks:
Review:

TINY-7478: Added table cell border style and width toolbar buttons/menu items

---

modules/tinymce/src/core/test/ts/browser/EditorRemoveTest.ts
modules/tinymce/src/core/test/ts/browser/InlineEditorRemoveTest.ts
modules/tinymce/src/core/test/ts/browser/annotate/AnnotationPersistenceTest.ts
modules/tinymce/src/core/test/ts/browser/bookmark/BookmarksTest.ts
modules/tinymce/src/core/test/ts/browser/content/EditorContentNotInitializedTest.ts
modules/tinymce/src/core/test/ts/browser/content/EditorContentWsTest.ts
modules/tinymce/src/core/test/ts/browser/content/HTMLDataURLsTest.ts
modules/tinymce/src/core/test/ts/browser/dom/ReferrerPolicyTest.ts
modules/tinymce/src/core/test/ts/browser/focus/CefFocusTest.ts
modules/tinymce/src/core/test/ts/browser/focus/EditorFocusTest.ts
modules/tinymce/src/core/test/ts/browser/init/InitContentBodySelectionTest.ts
modules/tinymce/src/core/test/ts/browser/init/InitEditorOnHiddenElementTest.ts
modules/tinymce/src/core/test/ts/browser/keyboard/EnterKeyInlineTest.ts
modules/tinymce/src/core/test/ts/browser/selection/SelectBeforeBlockTest.ts

Replace shorthand hooks 
Pre-checks:
Review:

Fix shorthand hooks

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/plugins/table/main/ts/api/Commands.ts
modules/tinymce/src/plugins/table/main/ts/selection/SelectionTargets.ts
modules/tinymce/src/plugins/table/main/ts/ui/Buttons.ts
modules/tinymce/src/plugins/table/main/ts/ui/MenuItems.ts
modules/tinymce/src/plugins/table/main/ts/ui/TableDialog.ts
modules/tinymce/src/plugins/table/test/ts/browser/ui/TableBorderStyleTest.ts
modules/tinymce/src/plugins/table/test/ts/browser/ui/TableBorderWidthTest.ts
modules/tinymce/src/plugins/table/test/ts/browser/ui/TableCaptionTest.ts
modules/tinymce/src/plugins/table/test/ts/browser/ui/TableClassListButtonsTest.ts
modules/tinymce/src/plugins/table/test/ts/browser/ui/TableDialogTest.ts
modules/tinymce/src/plugins/table/test/ts/browser/ui/TableValignButtonsTest.ts
modules/tinymce/src/plugins/table/test/ts/module/test/TableModifiersTestUtils.ts

Added table's ability to toggle captions
Pre-checks:
Review:

TINY-7479: Added table caption functionality.

---

modules/snooker/CHANGELOG.md
modules/snooker/src/main/ts/ephox/snooker/model/TableMerge.ts
modules/snooker/src/test/ts/browser/PasteCellsOperationsTest.ts
modules/tinymce/CHANGELOG.md
modules/tinymce/package.json
modules/tinymce/src/themes/silver/main/ts/modes/Inline.ts
modules/tinymce/src/themes/silver/test/ts/browser/editor/ShowHideTest.ts
modules/tinymce/src/themes/silver/test/ts/browser/editor/SilverFixedToolbarContainerTest.ts
modules/tinymce/src/themes/silver/test/ts/browser/editor/SilverInlineEditorTest.ts
modules/tinymce/src/themes/silver/test/ts/browser/editor/contexttoolbar/ContextToolbarBoundsTest.ts
modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/ToolbarDrawerToggleTest.ts
modules/tinymce/src/themes/silver/test/ts/module/UiUtils.ts
modules/tinymce/src/themes/silver/test/ts/webdriver/editor/SimpleControlsInlineTest.ts
versions.txt

Related Ticket: TINY-7591
* Backports the changes that we wanted released with 5.8.2 from develop into master
Pre-checks:
Review:

TINY-7591: back port changes in preparation for 5.8.2 release

---

modules/bridge/src/main/ts/ephox/bridge/api/Menu.ts
modules/bridge/src/main/ts/ephox/bridge/api/PublicMenu.ts
modules/bridge/src/main/ts/ephox/bridge/components/menu/FancyMenuItem.ts
modules/tinymce/src/themes/silver/main/ts/ui/menus/item/build/ColorSwatchItem.ts
modules/tinymce/src/themes/silver/main/ts/ui/menus/item/build/InsertTableMenuItem.ts

Related Ticket: TINY-7480
Just an improvement to provide better validation and types for fancy menu items. This is just something that we discussed this afternoon, that I didn't want to hold the other PR up for.
Pre-checks:
Review:

TINY-7480: Improve fancy menu item validation and types

---

modules/sand/src/test/ts/atomic/core/BrowserTest.ts
modules/sand/src/test/ts/atomic/core/DeviceTypeTest.ts
modules/sand/src/test/ts/atomic/detect/VersionDetectorTest.ts
modules/sand/src/test/ts/browser/HtmlElementTest.ts

- Converts sand to use BDD-style tests
Pre-checks:
Review:

BDD conversion for Sand

---

modules/tinymce/src/core/main/ts/api/SettingsTypes.ts
modules/tinymce/src/core/main/ts/api/html/DomParser.ts
modules/tinymce/src/core/main/ts/api/html/Node.ts
modules/tinymce/src/core/main/ts/api/html/Schema.ts
modules/tinymce/src/core/main/ts/api/html/Serializer.ts
modules/tinymce/src/core/main/ts/delete/TableDelete.ts
modules/tinymce/src/core/main/ts/dom/Dimensions.ts
modules/tinymce/src/core/main/ts/dom/DomSerializerFilters.ts
modules/tinymce/src/core/main/ts/dom/DomSerializerImpl.ts
modules/tinymce/src/core/main/ts/dom/DomSerializerPreProcess.ts
modules/tinymce/src/core/main/ts/dom/ElementType.ts
modules/tinymce/src/core/main/ts/dom/Empty.ts
modules/tinymce/src/core/main/ts/dom/MousePosition.ts
modules/tinymce/src/core/main/ts/dom/NodePath.ts
modules/tinymce/src/core/main/ts/dom/NodeType.ts
modules/tinymce/src/core/main/ts/dom/PaddingBr.ts
modules/tinymce/src/core/main/ts/dom/Parents.ts
modules/tinymce/src/core/main/ts/dom/Position.ts
modules/tinymce/src/core/main/ts/dom/ScrollIntoView.ts
modules/tinymce/src/core/main/ts/dom/TrimHtml.ts
modules/tinymce/src/core/main/ts/dom/TrimNode.ts
modules/tinymce/src/core/main/ts/html/Base64Uris.ts
modules/tinymce/src/core/main/ts/html/LegacyFilter.ts
modules/tinymce/src/core/main/ts/html/ParserFilters.ts
modules/tinymce/src/core/main/ts/html/ParserUtils.ts

This is a follow on from https://github.com/tinymce/tinymce/pull/6806 and https://github.com/tinymce/tinymce/pull/6905, so same situation as then whereby this is just trying to get more types declared in core. This isn't meant to be an exhaustive conversion and certainly somethings aren't typed still (should only be variables inside functions).
Pre-checks:
Review:

Added return types and fixed no implicit any errors for modules in the dom and html directory

---

modules/tinymce/src/core/main/ts/delete/BlockMergeBoundary.ts
modules/tinymce/src/core/main/ts/delete/BlockRangeDelete.ts
modules/tinymce/src/core/main/ts/delete/CaretBoundaryDelete.ts
modules/tinymce/src/core/main/ts/delete/CefDelete.ts
modules/tinymce/src/core/main/ts/delete/CefDeleteAction.ts
modules/tinymce/src/core/main/ts/delete/DeleteCommands.ts
modules/tinymce/src/core/main/ts/delete/DeleteElement.ts
modules/tinymce/src/core/main/ts/delete/DeleteUtils.ts
modules/tinymce/src/core/main/ts/delete/InlineBoundaryDelete.ts
modules/tinymce/src/core/main/ts/delete/InlineFormatDelete.ts
modules/tinymce/src/core/main/ts/delete/MediaDelete.ts
modules/tinymce/src/core/main/ts/delete/MergeBlocks.ts
modules/tinymce/src/core/main/ts/delete/MergeText.ts
modules/tinymce/src/core/main/ts/delete/Outdent.ts
modules/tinymce/src/core/main/ts/delete/TableDelete.ts
modules/tinymce/src/core/main/ts/delete/TableDeleteAction.ts
modules/tinymce/src/core/main/ts/delete/TableDeleteUtils.ts
modules/tinymce/src/core/test/ts/browser/delete/CefDeleteActionTest.ts
modules/tinymce/src/core/test/ts/browser/delete/MergeBlocksTest.ts

This is a follow on from https://github.com/tinymce/tinymce/pull/6806 and https://github.com/tinymce/tinymce/pull/6905, so same situation as then whereby this is just trying to get more types declared in core. This isn't meant to be an exhaustive conversion and certainly somethings aren't typed still (should only be variables inside functions).
Pre-checks:
Review:

Added return types and fixed no implicit any errors for modules in the delete directory

---

modules/agar/src/main/ts/ephox/agar/datatransfer/DataTransferItem.ts
modules/snooker/src/main/ts/ephox/snooker/util/LayerSelector.ts
modules/sugar/src/main/ts/ephox/sugar/api/node/SugarComments.ts
modules/sugar/src/main/ts/ephox/sugar/api/node/SugarShadowDom.ts
modules/sugar/src/main/ts/ephox/sugar/api/search/ElementAddress.ts
modules/sugar/src/main/ts/ephox/sugar/api/search/Traverse.ts
modules/sugar/src/main/ts/ephox/sugar/api/selection/CursorPosition.ts
modules/sugar/src/main/ts/ephox/sugar/selection/query/CaretRange.ts
modules/tinymce/src/core/main/ts/api/dom/DomQuery.ts
modules/tinymce/src/core/main/ts/selection/CaretRangeFromPoint.ts
modules/tinymce/src/themes/silver/test/ts/browser/editor/SilverDialogPopupsTest.ts

TypeScript 4.4 made a number of changes to the dom lib which breaks things, so this is largely just fixing them. It does not upgrade yet, as TS 4.4 is still only in beta.
Pre-checks:
Review:

Made a number of fixes/changes to the types so they'll work when TypeScript 4.4 is released

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/plugins/table/main/ts/selection/SelectionTargets.ts
modules/tinymce/src/plugins/table/main/ts/ui/Buttons.ts
modules/tinymce/src/plugins/table/main/ts/ui/MenuItems.ts
modules/tinymce/src/plugins/table/main/ts/ui/UiUtils.ts
modules/tinymce/src/plugins/table/test/ts/browser/ui/TableColumnHeaderUiTest.ts
modules/tinymce/src/plugins/table/test/ts/module/test/TableModifiersTestUtils.ts

Added the column header ability.
Pre-checks:
Review:

TINY-7482: Added column header functionality

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/core/main/ts/Rtc.ts
modules/tinymce/src/core/main/ts/api/Formatter.ts
modules/tinymce/src/core/main/ts/fmt/MatchFormat.ts
modules/tinymce/src/core/test/ts/browser/FormatterCheckTest.ts

TINY-7712: Added optional similar parameter to formatter.match

---

modules/agar/CHANGELOG.md
modules/agar/src/main/ts/ephox/agar/api/UiControls.ts

Related Ticket: TINY-7065
Revert agar changes
Pre-checks:
Review:
Before merging: 

Revert agar portion of "TINY-7065: Test library fixes and improvements (#7018)"

---

modules/tinymce/src/themes/silver/test/ts/browser/editor/EventsTest.ts

Related Ticket: TINY-7399
* Fixed an additional flake due to the link plugin being used but not imported
Pre-checks:
Review:

TINY-7399: Additional fixes for flaky tests

---

modules/snooker/src/test/ts/browser/resize/ColumnSizesTest.ts

Change test to handle suspected bug in Chrome 92
Pre-checks:
Review:

Change test to handle suspected bug in Chrome 92

---

README.md
modules/acid/package.json
modules/agar/package.json
modules/alloy/package.json
modules/boss/package.json
modules/boulder/package.json
modules/bridge/package.json
modules/darwin/package.json
modules/dragster/package.json
modules/imagetools/package.json
modules/jax/package.json
modules/katamari-assertions/package.json
modules/katamari/package.json
modules/mcagar/package.json
modules/oxide-icons-default/package.json
modules/oxide/package.json
modules/phoenix/package.json
modules/polaris/package.json
modules/porkbun/package.json
modules/robin/package.json
modules/sand/package.json
modules/snooker/package.json
modules/sugar/package.json
modules/tinymce/Gruntfile.js
modules/tinymce/package.json

Related Ticket: TINY-7694
* Update the TinyMCE README and package.json as per marketing feedback
* Fixed other incorrect package.json metadata in other modules
**Note:** Test failures are unrelated to this PR.
Pre-checks:
Review:

TINY-7694: Updated README and package.json based on marketing feedback

---

package.json
yarn.lock

* Upgrade the following dev dependencies (was primarily just doing this for the Prism.js upgrade):
Pre-checks:
Review:

Upgraded dev dependencies

---

modules/alloy/src/main/ts/ephox/alloy/alien/PrioritySort.ts
modules/alloy/src/main/ts/ephox/alloy/ui/slider/SliderOffsets.ts
modules/alloy/src/test/ts/module/ephox/alloy/test/StepUtils.ts
modules/imagetools/src/main/ts/ephox/imagetools/meta/JPEGMeta.ts
modules/jax/src/test/ts/browser/AjaxTest.ts
modules/mcagar/src/main/ts/ephox/mcagar/loader/Loader.ts
modules/mcagar/src/test/ts/browser/api/TinyLoaderTest.ts
modules/porkbun/src/test/ts/atomic/EventsTest.ts
modules/snooker/src/test/ts/module/ephox/snooker/test/Assertions.ts
modules/sugar/src/test/ts/browser/CssReflowTest.ts
modules/sugar/src/test/ts/browser/LocationTest.ts
modules/sugar/src/test/ts/browser/ScrollTest.ts
modules/sugar/src/test/ts/browser/SelectionPointTest.ts
modules/sugar/src/test/ts/browser/SelectorTest.ts
modules/sugar/src/test/ts/browser/ShadowDomTest.ts
modules/sugar/src/test/ts/browser/SizeTest.ts
modules/tinymce/src/core/main/ts/EditorView.ts
modules/tinymce/src/core/main/ts/api/dom/Selection.ts
modules/tinymce/src/core/main/ts/api/geom/Rect.ts
modules/tinymce/src/core/main/ts/caret/CaretPosition.ts
modules/tinymce/src/core/main/ts/caret/FakeCaret.ts
modules/tinymce/src/core/main/ts/caret/LineUtils.ts
modules/tinymce/src/core/main/ts/caret/LineWalker.ts
modules/tinymce/src/core/main/ts/caret/TableCells.ts
modules/tinymce/src/core/main/ts/dom/Dimensions.ts
modules/tinymce/src/core/test/ts/browser/geom/RectTest.ts
modules/tinymce/src/plugins/table/main/ts/actions/InsertTable.ts
modules/tinymce/src/themes/mobile/main/ts/util/Rectangles.ts
modules/tinymce/src/themes/silver/main/ts/ui/selector/TableSelectorHandles.ts

* Fixes type issues in TS 4.4 due to dom.lib.d.ts changes. Some types are deprecated or changed, such as `ClientRect` -> `DOMRect`, which also showed we had the wrong type in a few places due to TinyMCE having it's own `ClientRect` type.
* Fixes or adds `any` to caught exceptions which were failing under TS 4.4.
Note: All was tested using TS 4.4.1-rc.
Pre-checks:
Review:

TypeScript 4.4 type fixes

---

modules/tinymce/CHANGELOG.md

Related Ticket: DOC-865
* 5.9.0 suggested changelog edits
Pre-checks:
Review:

DOC-865: 5.9.0 suggested changelog edits

---

package.json
yarn.lock

* TypeScript 4.4 was released earlier in the week, so this upgrades to use that.
Pre-checks:
Review:

Upgrade to TypeScript 4.4

---

modules/tinymce/CHANGELOG.md
modules/tinymce/package.json

Related Ticket: TINY-7914
* Updated the changelog and package.json for 5.9.2 release.
Pre-checks:
Review:

TINY-7914: Update changelog and package.json for 5.9.2 release

---

modules/oxide/src/less/theme/components/fullscreen/fullscreen.less

Related Ticket: TINY-7873
Fix issue with shadowroot found in QA
Pre-checks:
Review:

TINY-7873: Fix styling issues when running the editor in a shadow root

---

modules/alloy/src/main/ts/ephox/alloy/api/system/Gui.ts
modules/alloy/src/main/ts/ephox/alloy/events/EventRegistry.ts
modules/alloy/src/main/ts/ephox/alloy/events/GuiEvents.ts
modules/alloy/src/test/ts/browser/events/GuiEventsTest.ts
modules/tinymce/src/themes/silver/main/ts/Events.ts

Related Ticket: TINY-8045
* Cleaned up the `EventRegistry` logic
* Replaced some duplication in `Events`
* Removed the bouldering happening in `GuiEvents`
Pre-checks:
Review:

TINY-8045: Minor improvements identified during alloy walk through

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/core/main/ts/api/Editor.ts
modules/tinymce/src/core/main/ts/api/dom/DomQuery.ts
modules/tinymce/src/core/main/ts/api/html/Styles.ts
modules/tinymce/src/core/main/ts/api/util/Color.ts
modules/tinymce/src/core/main/ts/api/util/Delay.ts
modules/tinymce/src/core/main/ts/api/util/JSON.ts
modules/tinymce/src/core/main/ts/api/util/JSONRequest.ts
modules/tinymce/src/core/main/ts/api/util/Tools.ts
modules/tinymce/src/core/main/ts/api/util/XHR.ts

Related Ticket: TINY-8023
Add deprecation notices for several APIs
Pre-checks:
Review:

TINY-8023: Mark several APIs as deprecated

---

modules/tinymce/src/core/main/ts/api/Annotator.ts
modules/tinymce/src/core/main/ts/api/Env.ts
modules/tinymce/src/core/main/ts/api/Mode.ts
modules/tinymce/src/core/main/ts/api/dom/Sizzle.ts
modules/tinymce/src/core/main/ts/api/util/I18n.ts
modules/tinymce/src/core/main/ts/api/util/Tools.ts
modules/tinymce/tools/docs/tinymce.Env.js

Related Ticket: DOC-979
* Fix MoxieDoc warnings. During API docs builds at this time, multiple warnings are shown, this PR addresses all the warnings returned when building the API docs from the `develop` branch.
Pre-checks:
Review:

Fixing MoxieDoc warnings on develop

---

modules/tinymce/src/core/main/ts/api/dom/DomQuery.ts
modules/tinymce/src/core/main/ts/api/util/Color.ts
modules/tinymce/src/core/main/ts/api/util/JSON.ts
modules/tinymce/src/core/main/ts/api/util/JSONRequest.ts
modules/tinymce/src/core/main/ts/api/util/XHR.ts

Related Ticket: TINY-8023
Fix bad formatting
Pre-checks:
Review:

TINY-8023: Fix bad formatting

---

modules/tinymce/CHANGELOG.md

* 5.10 suggested changelog edits
Pre-checks:
Review:

suggested changes to the 5.10 changelog

---

modules/tinymce/CHANGELOG.md
modules/tinymce/package.json

Related Ticket: TINY-8060
* Update changelog and bump package.json
Pre-checks:
Review:

TINY-8060: Update package.json and changelog for TinyMCE 5.10.1 release

---

modules/tinymce/src/themes/silver/test/ts/browser/editor/NotificationManagerImplTest.ts

* Fix chrome notifications flake
Pre-checks:
Review:

Fix chrome notifications flake

---

modules/tinymce/CHANGELOG.md
modules/tinymce/package.json

Related Ticket:  TINY-8240
* Update the changelog/package.json for the 5.10.2 release
Pre-checks:
Review:

TINY-8240: Update package.json and changelog for TinyMCE 5.10.2 release

---

modules/tinymce/src/core/main/ts/api/html/StyleUtils.ts

Related Ticket: TINY-7493
* Fix an exception that was found when QAing TINY-7493 the occurred by pasting a list from Word
Pre-checks:
Review:

TINY-7493: Fix an exception that could be thrown from potentially undefined string

---

modules/tinymce/src/core/main/ts/api/EditorManager.ts

Related Ticket: TINY-8254 
* added check for old edge and removed check for ie version.
Pre-checks:
Review:

TINY-8254: added check for old edge and removed check for ie version.

---

modules/tinymce/src/core/main/ts/file/Uploader.ts

Related Ticket: TINY-8255
* Fix progress argument in `UploadHandler` to be required
Pre-checks:
Review:

TINY-8255: Fix progress argument type in UploadHandler

---

modules/tinymce/src/core/main/ts/Deprecations.ts
modules/tinymce/src/core/main/ts/api/Editor.ts

Related Ticket: TINY-8220
* Updated the deprecations warnings to say the features have been removed
Pre-checks:
Review:

TINY-8220: Updated the deprecation message to reflect that the features have been removed

---

modules/tinymce/src/core/main/ts/api/AddOnManager.ts
modules/tinymce/src/plugins/anchor/main/ts/ui/Dialog.ts

Related Ticket: TINY-7280
Description of Changes: 
* Fix casing for example and updated dialogs
Pre-checks:
Review:

TINY-7280: Fix casing for example and updated Dialogs

---

modules/tinymce/src/core/main/ts/api/html/DomParser.ts

Related Ticket: TINY-8214
* Some things that might make the code in the TINY-8214 branch simpler, or address some concerns — but they also might be too risky as far as changes go, so I didn't want to push them directly to that branch
* Move a bunch of helper functions _outside_ of `DomParser.parse`
* Collect all of the various "walk the tree" things into a single tree walking loop, that accepts a bunch of callbacks 
Pre-checks:
Review:

TINY-8214 cleanup

---

modules/tinymce/src/core/main/ts/api/html/DomParser.ts
modules/tinymce/src/core/main/ts/api/html/Schema.ts
modules/tinymce/src/core/test/ts/browser/EditorTest.ts
modules/tinymce/src/core/test/ts/browser/dom/SerializerTest.ts
modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts
modules/tinymce/src/core/test/ts/browser/html/SchemaTest.ts

Related Ticket: TINY-8204
* Ensure that special elements are parsed with the appropriate context
Pre-checks:
Review:

TINY-8204: Ensure elements are parsed with the appropriate context

---

modules/tinymce/src/core/main/ts/api/Editor.ts
modules/tinymce/src/core/main/ts/api/EditorCommands.ts

Related Ticket: TINY-8088
* Started to clean up other files
* 
Pre-checks:
Review:

TINY-8088: removed !! from editor files

---

modules/tinymce/src/core/main/ts/api/dom/ScriptLoader.ts
modules/tinymce/src/core/test/ts/browser/dom/ScriptLoaderTest.ts

Related Ticket: TINY-8325
This largely just rolls back some things that were removed in https://github.com/tinymce/tinymce/pull/7549 that shouldn't have been. Have also reworked it though to work better with promises.
Pre-checks:
Review:

TINY-8325: Fixed a race condition with scripts loading

---

modules/tinymce/src/themes/silver/test/ts/browser/editor/color/ColorPickerSanityTest.ts

Related Ticket: TINY-8391
* Fix test error that was exposed from chunking shift
Pre-checks:
Review:

TINY-8391: Fix test relying on previous state

---

modules/tinymce/src/core/main/ts/ErrorReporter.ts
modules/tinymce/src/core/main/ts/api/EventTypes.ts
modules/tinymce/src/core/main/ts/init/Render.ts
modules/tinymce/src/models/dom/demo/html/demo/basic-demo.html
modules/tinymce/src/plugins/table/main/ts/ui/Buttons.ts
modules/tinymce/src/plugins/table/main/ts/ui/MenuItems.ts
modules/tinymce/tools/tasks/bundle.js

Related Ticket: TINY-8391
* Update comments in the table Buttons.ts and MenuItems.ts files. The best solution will be determined in TINY-8172
* Swap from `hasCommandCommand` to `queryCommandSupported`
* Other small cleanup and fixes
Pre-checks:
Review:

TINY-8391: Small fixes and changes for alt-table work

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts
modules/tinymce/src/plugins/fullscreen/test/ts/browser/FullscreenRestoreScrollTest.ts

Backport of TINY-8418.
Pre-checks:
Review:

TINY-8418: Fixed fullscreen not restoring the scroll position

---

modules/tinymce/CHANGELOG.md

Related Ticket: TINY-8324
* Update changelog for 5.10.3 release
Pre-checks:
Review:

TINY-8324: Update changelog for 5.10.3 release

---

modules/tinymce/Gruntfile.js
modules/tinymce/src/core/main/json/globals.json
modules/tinymce/src/core/main/ts/ErrorReporter.ts
modules/tinymce/src/core/main/ts/api/AddOnManager.ts
modules/tinymce/src/core/main/ts/api/Editor.ts
modules/tinymce/src/core/main/ts/api/EventTypes.ts
modules/tinymce/src/core/main/ts/api/ModelManager.ts
modules/tinymce/src/core/main/ts/api/OptionTypes.ts
modules/tinymce/src/core/main/ts/api/Options.ts
modules/tinymce/src/core/main/ts/api/PluginManager.ts
modules/tinymce/src/core/main/ts/api/PublicApi.ts
modules/tinymce/src/core/main/ts/api/ThemeManager.ts
modules/tinymce/src/core/main/ts/api/Tinymce.ts
modules/tinymce/src/core/main/ts/init/Init.ts
modules/tinymce/src/core/main/ts/init/Render.ts
modules/tinymce/src/core/test/ts/module/McAgar.ts
modules/tinymce/src/models/dom/demo/html/demo/basic-demo.html
modules/tinymce/src/models/dom/demo/ts/demo/Demo.ts
modules/tinymce/src/models/dom/main/ts/Main.ts
modules/tinymce/src/models/dom/main/ts/Model.ts
modules/tinymce/tools/modules/grunt-webpack.js
modules/tinymce/tools/tasks/bundle.js
modules/tinymce/tsconfig.json
modules/tinymce/tsconfig.model.json
tsconfig.json

Related Ticket: TINY-8152, TINY-8391
* Implement skeleton for model and modelManager concept for the editor
Pre-checks:
Review:

TINY-8152: Implement DOM model init and loading for the editor

---

SECURITY.md
modules/acid/package.json
modules/agar/package.json
modules/alloy/package.json
modules/boss/package.json
modules/boulder/package.json
modules/bridge/package.json
modules/darwin/package.json
modules/dragster/package.json
modules/jax/package.json
modules/katamari-assertions/package.json
modules/katamari/package.json
modules/mcagar/package.json
modules/oxide-icons-default/package.json
modules/oxide/package.json
modules/phoenix/package.json
modules/polaris/package.json
modules/porkbun/package.json
modules/robin/package.json
modules/sand/package.json
modules/snooker/package.json
modules/sugar/package.json
modules/tinymce/CHANGELOG.md
versions.txt

Related Ticket: TINY-8395
* Updated the changelog date
* Publish monorepo packages (all should be a major update)
Pre-checks:
Review:

TINY-8395: Prepare for 6.0 release

---

modules/oxide/src/less/skins/ui/tinymce-5/skin.less
modules/oxide/src/less/theme/components/button/button-naked.less
modules/oxide/src/less/theme/components/notification/notification.less
modules/oxide/src/less/theme/globals/utils.less
modules/oxide/src/less/theme/theme.less
modules/tinymce/CHANGELOG.md

Related Ticket: TINY-8533
* Adjusted contrast for Naked Button component on darker backgrounds
* Adjusted contrast in Notifications component
Pre-checks:
Review:

TINY-8533: Adjust naked button and notifications contrast

---

.github/CODEOWNERS

This just updates the codeowners to match recent staffing changes.
Pre-checks:
Review:

Updated the codeowners

---

README.md
SECURITY.md
modules/oxide-icons-default/README.md
modules/oxide/README.md
modules/tinymce/CHANGELOG.md
modules/tinymce/src/core/main/ts/Deprecations.ts
modules/tinymce/src/core/main/ts/api/EditorManager.ts
modules/tinymce/src/core/main/ts/api/NotificationManager.ts
modules/tinymce/src/core/main/ts/api/WindowManager.ts
modules/tinymce/src/core/main/ts/api/fmt/StyleFormat.ts
modules/tinymce/src/core/main/ts/api/ui/Registry.ts
modules/tinymce/src/core/main/ts/api/util/Observable.ts
modules/tinymce/src/plugins/help/main/ts/ui/PluginsTab.ts
modules/tinymce/src/plugins/help/main/ts/ui/VersionTab.ts

Related Ticket: TINY-8584
* Updated the docs URL links as the format for the site unexpectedly got changed all of a sudden
Pre-checks:
Review:

TINY-8584: Updated the docs urls to meet the change in URL format

---

modules/tinymce/src/core/main/ts/api/Editor.ts
modules/tinymce/src/core/main/ts/api/Formatter.ts
modules/tinymce/src/core/main/ts/api/dom/StyleSheetLoader.ts
modules/tinymce/src/core/main/ts/api/dom/TextSeeker.ts
modules/tinymce/src/core/main/ts/api/ui/Registry.ts
modules/tinymce/src/core/main/ts/api/util/ImageUploader.ts
modules/tinymce/tools/docs/tinymce.Env.js
modules/tinymce/tools/docs/tinymce.Event.js
modules/tinymce/tools/docs/tinymce.editor.ui.Ui.js

Related Ticket: TINY-8585
* Removed instances of "Added in TinyMCE 5.x"
* Updated renamed enabled API documentation
* Only comment blocks have been altered
Pre-checks:
Review:

TINY-8585: Removed "Added in TinyMCE" version comments, updated "setEnabled" and "isEnabled" API comments

---

modules/oxide/src/less/theme/components/form/autocomplete.less
modules/tinymce/CHANGELOG.md

Related Ticket: TINY-8573
* Fix autcomplete border
Pre-checks:
Review:

TINY-8573: Fix autcomplete border

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/core/main/ts/fmt/DefaultFormats.ts
modules/tinymce/src/core/test/ts/browser/FormattingCommandsTest.ts

TINY-7715: Alignment could not be applied to pre-blocks

---

modules/tinymce/src/core/test/ts/browser/UndoManagerTest.ts
modules/tinymce/src/plugins/autoresize/test/ts/browser/AutoresizePluginTest.ts
modules/tinymce/src/plugins/image/test/ts/browser/UploadTabTest.ts
modules/tinymce/src/plugins/link/test/ts/browser/DefaultLinkTargetTest.ts
modules/tinymce/src/plugins/wordcount/test/ts/browser/PluginTest.ts
modules/tinymce/src/themes/silver/test/ts/browser/editor/core/UndoRedoTest.ts
modules/tinymce/src/themes/silver/test/ts/headless/components/listbox/ListBoxTest.ts
modules/tinymce/src/themes/silver/test/ts/headless/components/sizeinput/SizeInputTest.ts
modules/tinymce/src/themes/silver/test/ts/headless/sketchers/SilverMenubarTest.ts

Related Ticket: TINY-8663
* Fixed various tests that failed to run in isolation. This for example then caused flakes when used with bedrock's chunking.
Pre-checks:
Review:

TINY-8663: Fixed some tests that failed to run in isolation

---

modules/tinymce/CHANGELOG.md

Related Ticket: TINY-8638
* Add date to changelog for 6.0.2 release
Pre-checks:
Review:

TINY-8638: Update changelog for TinyMCE 6.0.2 release

---

modules/tinymce/CHANGELOG.md

Related Ticket: TINY-8519
* Add date to changelog for 5.10.4 release
Pre-checks:
Review:

TINY-8519: Update changelog for TinyMCE 5.10.4 release

---

modules/tinymce/src/core/main/ts/api/Editor.ts
modules/tinymce/src/core/main/ts/api/EditorOptions.ts
modules/tinymce/src/core/main/ts/api/dom/DOMUtils.ts
modules/tinymce/src/core/main/ts/api/dom/StyleSheetLoader.ts
modules/tinymce/src/core/main/ts/api/html/DomParser.ts
modules/tinymce/src/core/main/ts/api/html/Entities.ts
modules/tinymce/src/core/main/ts/api/html/Serializer.ts
modules/tinymce/src/core/main/ts/api/html/Styles.ts
modules/tinymce/src/core/main/ts/api/html/Writer.ts
modules/tinymce/src/core/main/ts/api/util/Delay.ts
modules/tinymce/src/core/main/ts/api/util/Tools.ts

Related Ticket: DOC-1613
* Various fixes for the API docs as found by QA (and a couple more I found clicking around).
* Improved the Editor Options API docs to include details about the built-in processors.
Pre-checks:
Review:

DOC-1613: Various fixes to API documentation

---

modules/tinymce/src/core/main/ts/html/Base64Uris.ts
modules/tinymce/src/core/test/ts/atomic/html/Base64UrisTest.ts

Related Ticket: TINY-8646
Pre-checks:
Review:

TINY-8646: Removed unused extractBase64DataUris logic

---

modules/tinymce/src/plugins/table/main/ts/actions/Styles.ts
modules/tinymce/src/plugins/table/main/ts/ui/CellDialog.ts
modules/tinymce/src/plugins/table/main/ts/ui/RowDialog.ts
modules/tinymce/src/plugins/table/main/ts/ui/TableDialog.ts
modules/tinymce/src/plugins/table/test/ts/browser/ui/TableCellDialogTest.ts
modules/tinymce/src/plugins/table/test/ts/browser/ui/TableRowDialogTest.ts
modules/tinymce/src/plugins/table/test/ts/module/test/TableTestUtils.ts

Related Ticket: TINY-8625
Fixed additional cases missed in https://github.com/tinymce/tinymce/pull/7803 whereby changing a value wasn't updating the cells.
Pre-checks:
Review:

TINY-8625: Fix table alignment fields not updated correctly in some cases

---

modules/tinymce/CHANGELOG.md

Related Ticket: TINY-8643
* Updated changelog
Pre-checks:
Review:

TINY-8643: Updated changelog 6.0.3 release

---

modules/tinymce/CHANGELOG.md

Related Ticket: TINY-8622
* Updated changelog
Pre-checks:
Review:

TINY-8622: Updated changelog for 5.10.5 release

---

modules/oxide/src/less/theme/components/comments/comment.less
modules/oxide/src/less/theme/components/comments/user.less

Related Ticket: TINY-8695
* Added styles for improved user/comment avatars
Pre-checks:
Review:

TINY-8695: Added styles for improved user/comment avatars

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/plugins/media/main/ts/api/Options.ts
modules/tinymce/src/plugins/media/main/ts/core/DataToHtml.ts

* Adds the `iframeTemplateCallback` parameter to the `getIframeHtml` function
Pre-checks:
Review:

Added iframeTemplateCallback

---

modules/tinymce/src/themes/silver/main/ts/ui/sidebar/Sidebar.ts
modules/tinymce/src/themes/silver/test/ts/browser/sidebar/SidebarShowOptionTest.ts

Related Ticket: TINY-8710
Pre-checks:
Review:

TINY-8710: sidebar_show option should be case insensitive

---

README.md

Related Ticket: TINY-8767
* Updated the README image link
Pre-checks:
* ~[] Changelog entry added~
* ~[] Tests have been added (if applicable)~
Review:

TINY-8767: Update screenshot in Readme

---

modules/tinymce/CHANGELOG.md

Related Ticket: TINY-8099
Pre-checks:
Review:

TINY-8099: Reviewing changelog for release

---

modules/tinymce/src/core/main/ts/fmt/ApplyFormat.ts
modules/tinymce/src/core/main/ts/fmt/FormatUtils.ts
package.json

Related Ticket: TINY-8905
* Fix CI commands
* Fix strict type failures
Pre-checks:
Review:

TINY-8905: Fix CI strict type checking and associated failures

---

.github/PULL_REQUEST_TEMPLATE.md

* Adding `Docs ticket created` to github template
Pre-checks:
* ~[x] Changelog entry added~
* ~[x] Tests have been added (if applicable)~
* ~[x] Branch prefixed with `feature/`, `hotfix/` or `spike/`~
Review:
* ~[x] Milestone set~

Add docs ticket created to template

---

modules/tinymce/src/plugins/codesample/test/ts/webdriver/CodeSampleCopyAndPasteTest.ts

Related Ticket: TINY-8861
* Add some selection assertions that were missed in a codesample test
* Replacement PR for #8018 
Pre-checks:
Review:

TINY-8861: Add selection assertions to test

---

modules/tinymce/src/core/main/ts/textpatterns/core/BlockPattern.ts
modules/tinymce/src/core/main/ts/textpatterns/core/Pattern.ts
modules/tinymce/src/core/main/ts/textpatterns/utils/Utils.ts
modules/tinymce/src/core/test/ts/atomic/textpatterns/FindBlockPatternsTest.ts
modules/tinymce/src/core/test/ts/browser/textpatterns/FindBlockPatternsTest.ts

Related Ticket: TINY-8778
Pre-checks:
Review:

TINY-8778: Fixed the lookup patterns taking priority over default patterns even though the latter has a better match

---

modules/tinymce/src/core/main/ts/dom/NodeType.ts
modules/tinymce/src/core/main/ts/fmt/ApplyFormat.ts

Related Ticket: TINY-8961
* Some minor cleanups of issues that Luke found.
Pre-checks:
Review:

TINY-8961: minor cleanup

---

modules/tinymce/src/themes/silver/main/ts/ui/promotion/Promotion.ts

Add the final text and link ( Link not yet set up on the site ). No changelog needed, no tests needed.
Pre-checks:
Review:

TINY-8954: Adding the final link and text

---

modules/tinymce/src/themes/silver/main/ts/ui/menus/menubar/Integration.ts

Related Ticket: TINY-8995
* adding more default menu items
Pre-checks:
* [N/A] Changelog entry added (?)
* [N/A] Tests have been added (if applicable)
Review:

TINY-8995: new defaults for menu items

---

modules/tinymce/CHANGELOG.md

Related Ticket: DOC-1790
* TinyMCE 6.2 ChangeLog edits and copy edits
Pre-checks:
Review:

DOC-1790: Copy edits for the 6.2 changelog

---

modules/snooker/src/test/ts/browser/ResizeTest.ts
modules/snooker/src/test/ts/browser/TableSizeTest.ts
modules/sugar/src/test/ts/browser/LocationTest.ts
modules/sugar/src/test/ts/browser/ScrollTest.ts
modules/tinymce/src/plugins/table/test/ts/module/test/TableTestUtils.ts

Related Ticket: TINY-9219
* Backport fix to failing tests on Firefox (TINY-9200)
Pre-checks:
Review:

TINY-9219: Fix broken tests on Firefox (#8155)

---

modules/tinymce/src/themes/silver/test/ts/browser/editor/backstage/BackstageSinkTest.ts

Related Ticket: TINY-9223
* Fixing test
Pre-checks:
* [N/A] Changelog entry added
* [N/A] Tests have been added (if applicable)
Review:

TINY-9223: Fixing test failure caused by bridge changes in TINY-9184

---

modules/tinymce/CHANGELOG.md

Related Ticket: TINY-8885
* Update changelog for the 5.10.6 release
Pre-checks:
Review:

TINY-8885: Update changelog for 5.10.6 release

---

modules/bridge/CHANGELOG.md
modules/tinymce/CHANGELOG.md

Changelog correction was forgotten on previous PR and not added before merge.
Pre-checks:
Review:

TINY-9184: Missed  changelog correction

---

modules/oxide/src/less/theme/components/view/view.less
modules/tinymce/src/core/demo/ts/demo/FullDemo.ts

Related Ticket: TINY-8964 there is also a related PR for the `advcode` plugin
* Added background color required for dark skins
* Added a new class that can be used to add border around anything inside the view needs to be skinnable
Pre-checks:
Review:

TINY-8964: Apply new design options around advcode

---

Jenkinsfile

Related Ticket: TINY-9258
* Update to Waluigi 7
* Update the builds to run using the `windows` label instead which will allow them to run on Windows 11
* Modernize the Jenkinsfile a little to match changes done in newer Waluigi versions. This means tests will now show as "unstable" (orange) instead of "failed" (red) when a test doesn't pass
Pre-checks:
Review:

TINY-9258: Update to waluigi 7 and run tests on Windows 11

---

modules/tinymce/src/plugins/help/main/ts/data/PluginUrls.ts

Related Ticket: TINY-9328
Pre-checks:
Review:

TINY-9328: Added Inline CSS to the premium plugin list

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/plugins/help/main/ts/data/PluginUrls.ts

Related Ticket: TINY-9298
* Added typography premium plugin to the premium plugin list
Pre-checks:
Review:

TINY-9298: Add typography premium plugin to the premium plugin list

---

modules/tinymce/src/themes/silver/main/ts/ui/core/color/ColorCache.ts
modules/tinymce/src/themes/silver/test/ts/browser/editor/color/ColorCacheTest.ts

Checkmark icon not included
Pre-checks:
Review:

TINY-9392: Forgot to add icon to custom colors.

---

modules/tinymce/tools/docs/tinymce.Env.js

Related Ticket: DOC-1006
* Update doc comment
* I haven't published this to `tinymce-docs` yet, but it needs to be merged before the 6.3 release unless we want to wait for 6.4
Pre-checks:
Review:

DOC-1006: Update isEdge docs to note it detects Legacy Edge

---

modules/tinymce/CHANGELOG.md

Related Ticket: DOC-1777, TINY-8984
* Changelog edits courtesy of @brian-forte 
Pre-checks:
Review:

DOC-1777: Changelog edits for 6.3

---

modules/tinymce/src/themes/silver/main/ts/ui/core/color/ColorSwatch.ts
modules/tinymce/src/themes/silver/test/ts/browser/skin/OxideColorSwatchMenuTest.ts

More accurate background color detection.
Pre-checks:
Review:

TINY-9342: More accurate background color detection.

---

modules/tinymce/CHANGELOG.md
modules/tinymce/package.json

Related Ticket: TINY-9404
* Updated package.json and changelog
Pre-checks:
Review:

TINY-9404: Prepare for TinyMCE 6.3.1 release

---

modules/tinymce/src/core/main/ts/api/Editor.ts
modules/tinymce/src/core/main/ts/api/EditorUpload.ts

Related Ticket: DOC-1487
* Adds documentation for each property and method in the EditorUpload API
Pre-checks:
Review:

DOC-1487: Add EditorUpload API documentation

---

SECURITY.md

Related Ticket: [TINY-9487](https://ephocks.atlassian.net/browse/TINY-9487)
* Updated `security.md` as per the edited file, new-security.md, attached to TINY-9487.
Pre-checks:
Review:
[TINY-9487]: https://ephocks.atlassian.net/browse/TINY-9487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TINY-9487: Updated `security.md` as per the edited file in the ticket, `new-security.md`.

---

modules/agar/CHANGELOG.md
modules/agar/src/main/ts/ephox/agar/api/ApproxStructure.ts
modules/agar/src/main/ts/ephox/agar/assertions/ApproxComparisons.ts
modules/agar/src/test/ts/browser/assertions/ApproxComparisonsTest.ts
modules/alloy/src/demo/ts/ephox/alloy/demo/DockableDemo.ts
modules/alloy/src/main/ts/ephox/alloy/api/Main.ts
modules/alloy/src/main/ts/ephox/alloy/api/events/SystemEvents.ts
modules/alloy/src/main/ts/ephox/alloy/behaviour/docking/ActiveDocking.ts
modules/alloy/src/main/ts/ephox/alloy/behaviour/docking/Dockables.ts
modules/alloy/src/main/ts/ephox/alloy/behaviour/docking/DockingApis.ts
modules/alloy/src/main/ts/ephox/alloy/behaviour/docking/DockingSchema.ts
modules/alloy/src/main/ts/ephox/alloy/behaviour/docking/DockingTypes.ts
modules/alloy/src/test/ts/browser/behaviour/docking/DockingInScrollingContainerTest.ts
modules/alloy/src/test/ts/browser/behaviour/docking/DockingTest.ts
modules/tinymce/src/themes/silver/demo/html/demo/demo-with-scrolling.html
modules/tinymce/src/themes/silver/demo/ts/demo/PlayDemo.ts
modules/tinymce/src/themes/silver/main/ts/Events.ts
modules/tinymce/src/themes/silver/main/ts/Theme.ts
modules/tinymce/src/themes/silver/main/ts/modes/ScrollingContext.ts
modules/tinymce/src/themes/silver/main/ts/ui/dialog/WindowManager.ts
modules/tinymce/src/themes/silver/main/ts/ui/header/StickyHeader.ts
modules/tinymce/src/themes/silver/test/ts/browser/editor/scrolling/EditorInScrollingContainerTest.ts
modules/tinymce/src/themes/silver/test/ts/browser/editor/scrolling/InlineDialogInScrollingContainerTest.ts
versions.txt

Related Ticket: TINY-9242
* TBA
Pre-checks:
* [N/A] Changelog entry added  - deferring for main merge
Review:
* [N/A] Docs ticket created (if applicable) - deferring

TINY-9242: Phase V => Adding scrolling support to Docking and Classic Mode Sticky Toolbars

---

.github/workflows/codeql.yml
Gruntfile.js
modules/acid/src/main/ts/ephox/acid/api/colour/Transformations.ts
modules/alloy/Gruntfile.js
modules/tinymce/src/core/main/ts/api/EditorObservable.ts
modules/tinymce/src/core/main/ts/selection/ElementSelection.ts

Related Ticket: TINY-9428
* Setting up CodeQL to replace the soon-to-be-decommissioned LGTM
Pre-checks:
* [N/A] Tests have been added (if applicable)
Review:

TINY-9428: Code Scanning

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/plugins/image/test/ts/browser/ContextMenuTest.ts
modules/tinymce/src/plugins/link/main/ts/ui/Controls.ts
modules/tinymce/src/plugins/link/test/ts/browser/ContextMenuTest.ts

Link plugin opened the context menu on table of content, added a check to make it stop doing that.
Pre-checks:
Review:

TINY-9491: Added some restrictions to link plugin.

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/core/main/ts/api/ThemeManager.ts
modules/tinymce/src/core/main/ts/init/Init.ts
modules/tinymce/src/core/test/ts/browser/init/EditorCustomThemeTest.ts
modules/tinymce/src/themes/silver/main/ts/Render.ts
modules/tinymce/src/themes/silver/main/ts/modes/Iframe.ts
modules/tinymce/src/themes/silver/main/ts/modes/Inline.ts
modules/tinymce/src/themes/silver/main/ts/ui/skin/Loader.ts

Related Ticket: TINY-9556
* Fix for flaky test ToolbarDrawerToggleTest.ts
Pre-checks:
Review:

TINY-9556: fix flaky test ToolbarDrawerToggleTest.ts

---

modules/tinymce/CHANGELOG.md

Related Ticket: TINY-9589
* Fixing errors found in the TinyMCE Changelog file from 6.3.
* Added missing changelog items for `6.4` release
* TINY-9398
Pre-checks:
Review:

TINY-9589: Fixed errors in the changelog.md for 6.4 release

---

modules/oxide/src/less/theme/components/advtemplate/advtemplate.less
modules/oxide/src/less/theme/theme.less

Related Ticket: TINY-9533
* Added styles for InsertTemplate Dialog (preview iframe border styles)
Pre-checks:
Review:

TINY-9533: Advtemplate styles

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/themes/silver/main/ts/modes/Inline.ts
modules/tinymce/src/themes/silver/main/ts/ui/header/InlineHeader.ts
modules/tinymce/src/themes/silver/test/ts/browser/editor/header/InlineHeaderTest.ts

Minimum width changes
Pre-checks:
Review:

TINY-8977: Inline header fixup.

---

modules/sugar/src/test/ts/browser/PredicateTest.ts
modules/tinymce/src/core/test/ts/browser/DragDropOverridesTest.ts
modules/tinymce/src/plugins/visualchars/test/ts/browser/PluginTest.ts
modules/tinymce/src/themes/silver/test/ts/browser/editor/color/TextColorSanityTest.ts

Fixed some flakey tests, some minor formatting
Pre-checks:
* ~~[x] Changelog entry added~~
Review:

TINY-9561: Fixed flakey tests.

---

modules/acid/CHANGELOG.md
modules/bridge/CHANGELOG.md
modules/mcagar/CHANGELOG.md
versions.txt

Related Ticket: TINY-9358
Pre-checks:
Review:

TINY-9358: Fix versions.txt and changelog files

---

modules/tinymce/src/core/main/ts/Deprecations.ts

Added deprecation texts.
Pre-checks:
* ~~[x] Changelog entry added~~
* ~~[x] Tests have been added (if applicable)~~
Review:

TINY-9642: Added template to deprecated list.

---

modules/oxide/src/less/theme/components/advtemplate/advtemplate.less

Related Ticket: TINY-9693
* added styles for Advanced Template dialog
Pre-checks:
Review:

TINY-9693: Handle tree component content overflow

---

modules/tinymce/CHANGELOG.md

Related Ticket: Tiny-9358
* Copy edits to entries in Added, Improved, Changed, and Fixed sub-sections of what will be, upon release, the new ‘6.4 - 2023-03-15’ section.
Pre-checks:
Review:

TINY-9358: changelog.md

---

modules/tinymce/src/themes/silver/test/ts/browser/window/SilverDialogApiAccessTest.ts

Related Ticket: TINY-9686
* Not super important for the release but made a typo in the label number for the test so setting milestone 6.5.0
Pre-checks:
Review:

TINY-9686: updated test label

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/themes/silver/main/ts/ui/header/InlineHeader.ts
modules/tinymce/src/themes/silver/test/ts/browser/editor/header/InlineHeaderTest.ts

Fix for 6.4.1 for the toolbar overflow issue that was not properly solved.
Pre-checks:
Review:

TINY-9646: Toolbar overflow issue that was not properly solved previously.

---

modules/oxide/src/less/skins/ui/tinymce-5-dark/skin.less
modules/oxide/src/less/skins/ui/tinymce-5/skin.less
modules/oxide/src/less/theme/components/collection/collection.less
modules/oxide/src/less/theme/components/menubar/menubar-button.less
modules/oxide/src/less/theme/components/toolbar-button/toolbar-button.less
modules/oxide/src/less/theme/components/toolbar-button/toolbar-select-button.less
modules/oxide/src/less/theme/components/toolbar-button/toolbar-split-button.less
modules/oxide/src/less/theme/components/tree/tree-button.less
modules/oxide/src/less/theme/globals/global-variables.less
modules/oxide/src/less/theme/globals/global.less
modules/tinymce/CHANGELOG.md

Related Ticket: TINY-9176
* Reverting the two TINY-9176 PR commits
* Adjusting tree-button variables to work
Pre-checks:
Review:

TINY-9176: Revert Focus Styles

---

modules/tinymce/CHANGELOG.md

TINY-9623: TinyMCE 6.4.1-specific changes added to changelog.md
* Added TinyMCE 6.4.1-specific changes added to changelog.md
Pre-checks:
Review:

TINY-9623: TinyMCE 6.4.1-specific changes added to changelog.md

---

modules/tinymce/package.json

Related Ticket: TINY-9623
* Bump tinymce package.json version number to 6.4.1
Pre-checks:
Review:

TINY-9623: Prepare for 6.4.1 community release

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/plugins/codesample/main/ts/ui/Dialog.ts
modules/tinymce/src/plugins/codesample/test/ts/module/CodeSampleTestUtils.ts
modules/tinymce/src/plugins/template/main/ts/ui/Dialog.ts

https://ephocks.atlassian.net/browse/TINY-9630
- Update the dropdown style of the code sample and template to tinymce custom style
Pre-checks:
Review:

TINY-9630: Update CodeSample Template dropdown to custom style

---

modules/alloy/CHANGELOG.md
modules/alloy/src/main/ts/ephox/alloy/api/ui/HtmlSelect.ts
modules/alloy/src/test/ts/browser/ui/form/HtmlSelectTest.ts
modules/tinymce/CHANGELOG.md
modules/tinymce/src/themes/silver/test/ts/headless/window/SilverDialogReuseTest.ts

Changed select element to default to first option in list if none is selected.
Pre-checks:
Review:

TINY-9679: Changed select element to default to first option in list if none is selected.

---

modules/tinymce/CHANGELOG.md

TINY-9645: changelog.md correction and copy-edit
* Correction and copy-edit made to entry in the 6.4.1 section of the TinyMCE changelog.
Pre-checks:
Review:

TINY-9645: changelog.md correction and copy-edit

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/core/main/ts/util/Quirks.ts
modules/tinymce/src/core/test/ts/browser/util/QuirksFirefoxTest.ts

Dragend event not firing sometimes.
Pre-checks:
Review:

TINY-9694: Fire event when appropriate.

---

versions.txt

Related Ticket: TINY-9654
* Put the new versions for robin and polaris in versions.txt, missed this in previous PRs
Pre-checks:
Review:

TINY-9654: Add updated robin and polaris versions to versions.txt

---

modules/tinymce/src/core/main/ts/Deprecations.ts

Add deprication message for rtc as it is to be removed.
Pre-checks:
* ~~[ ] Changelog entry added~~
Review:
* ~~[ ] Docs ticket created (if applicable)~~

TINY-9688: Add depreciation message for rtc

---

modules/oxide/package.json
modules/tinymce/CHANGELOG.md
modules/tinymce/src/plugins/quickbars/main/ts/insert/Picker.ts

* Merge latest master changes into develop (incl. TINY-9769). Created a PR as there were a couple of conflicts and needed to update a test file to work with develop changes. Wanted to make sure CI passes without issues
Pre-checks:
Review:

Merge latest master changes into develop

---

modules/polaris/CHANGELOG.md
modules/tinymce/CHANGELOG.md

https://ephocks.atlassian.net/browse/TINY-8122
* Update `tinymce` and `polaris` changlog
Pre-checks:
Review:

TINY-8122: Update Changelog Entries from 6.4.x to Unreleased and add missing entry to Polaris

---

modules/tinymce/CHANGELOG.md
modules/tinymce/package.json

Related Ticket: TINY-9734
* Added release details for 6.4.2
Pre-checks:
Review:

TINY-9734: Updated package and changelog

---

modules/tinymce/CHANGELOG.md

TINY-9804: bring `/tinymce/CHANGELOG.md` into sync with `/tinymce-docs/modules/ROOT/pages/changelog.adoc`
* 6.4.2-specific changelog.md entries and equivalent changelog.adoc entries now in sync.
Pre-checks:
Review:
~* [ ] Milestone set~
~* [ ] Docs ticket created (if applicable)~

TINY-9804: bring `/tinymce/CHANGELOG.md` into sync with `/tinymce-docs/modules/ROOT/pages/changelog.adoc`

---

modules/tinymce/src/themes/silver/main/ts/ui/menus/menubar/Integration.ts

Related Ticket: TINY-9790
* Added accordion to the default menu bar.
Pre-checks:
Review:

TINY-9790: Add accordion to the default menu bar

---

modules/tinymce/Gruntfile.js
modules/tinymce/src/plugins/ai/demo/html/demo.html
modules/tinymce/src/plugins/ai/demo/ts/demo/Demo.ts
modules/tinymce/src/plugins/ai/main/ts/Main.ts
modules/tinymce/src/plugins/ai/main/ts/Plugin.ts
modules/tinymce/src/plugins/ai/main/ts/api/Commands.ts
modules/tinymce/src/plugins/ai/main/ts/core/Ai.ts
modules/tinymce/src/plugins/ai/main/ts/ui/Buttons.ts
modules/tinymce/src/plugins/ai/test/ts/browser/SampleTest.ts
modules/tinymce/tsconfig.json
tsconfig.demo.json
tsconfig.json

Related Ticket: TINY-9850
* Create basic directory structure for AI plugin
* Update build files to ensure plugin can be built and demo can be used as expected
Pre-checks:
Review:

TINY-9850: Create basic template for ai plugin

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/core/main/ts/newline/InsertBlock.ts
modules/tinymce/src/core/test/ts/browser/keyboard/EnterKeyHrTest.ts
modules/tinymce/src/core/test/ts/browser/newline/InsertNewLineTest.ts

TINY-9822: Improved cursor placement on newline.

---

modules/tinymce/src/plugins/quickbars/test/ts/browser/ToolbarPositionTest.ts

Related Ticket: TINY-8297
* Fixes for failing test cases of ticket 8297, when the quickbar is shown furtherest at the right
Pre-checks:
Review:

TINY-8297: Fixed failing test cases when quickbar is shown furthest at the right

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/core/main/ts/selection/DetailsElement.ts
modules/tinymce/src/plugins/accordion/main/ts/core/Keyboard.ts
modules/tinymce/src/plugins/accordion/main/ts/core/Utils.ts
modules/tinymce/src/plugins/accordion/test/ts/browser/AccordionPluginTest.ts

Related Ticket: TINY-9884
* Fixed pressing BACKSPACE in details body and summary.
Pre-checks:
Review:

TINY-9884: Fix pressing BACKSPACE in details body and summary

---

modules/tinymce/CHANGELOG.md

Related Ticket: TINY-9913
* Changelog copy-edits made to changelog.adoc before publication added back to changelog.md.
Pre-checks:
Review:
~* [ ] Docs ticket created (if applicable)~

TINY-9913: Bring TinyMCE’s changelog.md into sync with TinyMCE Doc’s changelog.adoc.

---

modules/alloy/src/main/ts/ephox/alloy/api/ui/FloatingToolbarButton.ts
modules/oxide/src/less/theme/components/toolbar/toolbar.less
modules/tinymce/CHANGELOG.md

Related Ticket: TINY-9847
* Revert due to regression
Pre-checks:
Review:

TINY-9847: Revert regression

---

modules/tinymce/src/core/main/ts/selection/DetailsElement.ts
modules/tinymce/src/plugins/accordion/test/ts/webdriver/AccordionBackspaceDeleteTest.ts

Related Ticket: TINY-9950
* Fix issues / add tests for each cases noted in TINY-9950
Pre-checks:
Review:

TINY-9950: Fix backspace/delete issues with Accordion component

---

SECURITY.md
modules/acid/package.json
modules/agar/package.json
modules/alloy/CHANGELOG.md
modules/alloy/package.json
modules/bridge/package.json
modules/darwin/package.json
modules/dragster/CHANGELOG.md
modules/dragster/package.json
modules/mcagar/CHANGELOG.md
modules/mcagar/package.json
modules/oxide-icons-default/package.json
modules/oxide/package.json
modules/phoenix/package.json
modules/polaris/CHANGELOG.md
modules/polaris/package.json
modules/robin/CHANGELOG.md
modules/robin/package.json
modules/snooker/package.json
modules/tinymce/CHANGELOG.md
versions.txt

Related Ticket: TINY-9621
* Follow release preparation steps in https://internal-docs.tiny.work/internal-docs/1.1/engineering/releases/release-preparation.html
Pre-checks:
Review:

TINY-9621: 6.5 community release preparation

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/core/main/ts/paste/Clipboard.ts
modules/tinymce/src/core/main/ts/paste/Commands.ts
modules/tinymce/src/core/main/ts/paste/DragDrop.ts
modules/tinymce/src/core/test/ts/browser/paste/ImagePasteTest.ts
modules/tinymce/src/core/test/ts/browser/paste/InternalClipboardTest.ts
modules/tinymce/src/core/test/ts/browser/paste/PasteTest.ts
modules/tinymce/src/core/test/ts/module/test/PasteEventUtils.ts
modules/tinymce/src/core/test/ts/webdriver/paste/CopyAndPasteTest.ts

Related Ticket: TINY-9997
* Merge TINY-9997 changes into develop for testing purposes
Pre-checks:
Review:

TINY-9997: Merge master into develop for testing

---

modules/tinymce/CHANGELOG.md
modules/tinymce/package.json

Related Ticket: TINY-10002
* Add 6.5.1 changelog heading and bump package.json version
Pre-checks:
Review:

TINY-10002: Add 6.5.1 changelog heading and bump package.json version

---

modules/oxide/src/less/theme/components/dialog/dialog.less
modules/tinymce/CHANGELOG.md
modules/tinymce/src/themes/silver/main/ts/ui/window/SilverInlineDialog.ts
modules/tinymce/src/themes/silver/test/ts/browser/window/SilverInlineDialogTest.ts

https://ephocks.atlassian.net/browse/TINY-10015 
implement size option for inline dialog
Pre-checks:
Review:

TINY-10015: implement size option for inline dialog

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/themes/silver/main/ts/ui/menus/menubar/Integration.ts
modules/tinymce/src/themes/silver/main/ts/ui/toolbar/Integration.ts

https://ephocks.atlassian.net/browse/TINY-9939
add ai to default toolbar and menubar
Pre-checks:
Review:

TINY-9939: add ai to default toolbar and menubar

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/plugins/lists/main/ts/actions/ToggleList.ts
modules/tinymce/src/plugins/lists/test/ts/browser/ApplyToDivTest.ts

It would previous detect what will be the list item as the stopper, preventing the list from being longer than one.
Pre-checks:
Review:

TINY-9872: List now better detect a suitable parent.

---

modules/tinymce/src/plugins/help/main/ts/data/PluginUrls.ts

Related Ticket: TINY-9868
* Add ai plugin to help dialog plugin list
Pre-checks:
* ~~[X] Changelog entry added~~
* ~~[X] Tests have been added (if applicable)~~
Review:
* ~~[X] Docs ticket created (if applicable)~~

TINY-9868: Add ai plugin to help dialog plugin list

---

Gruntfile.js
Jenkinsfile
package.json
yarn.lock

Related Ticket: DEVOPS-807
* Added selenium container to run headless tests using selenium standalone chrome
Pre-checks:
Review:

DEVOPS-807: Use selenium for headless tests

---

modules/alloy/CHANGELOG.md
modules/alloy/src/main/ts/ephox/alloy/ui/types/DropdownTypes.ts
modules/tinymce/CHANGELOG.md
modules/tinymce/src/themes/silver/main/ts/ui/dropdown/CommonDropdown.ts

Related Ticket: https://ephocks.atlassian.net/browse/TINY-9978
May need manual testing instead of automated.
Pre-checks:
Review:

TINY-9978: Added margin around the menu to separate it from the frame.

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/core/main/ts/api/OptionTypes.ts
modules/tinymce/src/core/main/ts/api/Options.ts
modules/tinymce/src/core/main/ts/api/html/DomParser.ts
modules/tinymce/src/core/main/ts/dom/DomSerializerFilters.ts
modules/tinymce/src/core/main/ts/dom/DomSerializerImpl.ts
modules/tinymce/src/core/main/ts/dom/RemoveTrailingBr.ts
modules/tinymce/src/core/main/ts/html/ParserFilters.ts
modules/tinymce/src/core/main/ts/html/ParserUtils.ts
modules/tinymce/src/core/main/ts/init/InitContentBody.ts
modules/tinymce/src/core/test/ts/browser/PadEmptyWithBrTest.ts
modules/tinymce/src/core/test/ts/browser/dom/SerializerTest.ts
modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts
modules/tinymce/src/plugins/image/main/ts/ui/Buttons.ts
modules/tinymce/src/plugins/image/test/ts/browser/ContextMenuTest.ts
modules/tinymce/src/plugins/lists/main/ts/actions/ToggleList.ts
modules/tinymce/src/plugins/lists/test/ts/browser/ContentEditableFalseActionsTest.ts

Related Ticket: TINY-10117
* Cherry-pick #8894
* Cherry-pick #8879
* Cherry-pick #8783
Pre-checks:
* ~~[X] Changelog entry added~~
* ~~[X] Tests have been added (if applicable)~~
Review:

TINY-10117: Cherry-pick commits from develop to master for 6.6.1 release

---

modules/tinymce/src/themes/silver/test/ts/webdriver/dialogs/IFrameDialogTest.ts

Related Ticket: TINY-10101
* Updated tests when merging from master -> develop
Pre-checks:
Review:

TINY-10101: Fix Safari/Firefox not showing border when focus on iframe - updated IFrameDialogTest.ts

---

modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialogEvents.ts

https://ephocks.atlassian.net/browse/TINY-10070
revert a change that caused fix to not work
Pre-checks:
Review:

TINY-10070: revert function change

---

modules/tinymce/CHANGELOG.md
modules/tinymce/package.json

Related Ticket: TINY-10020
* Preparation for 6.6.1 TinyMCE release
Pre-checks:
Review:

TINY-10020: Preparation for 6.6.1 TinyMCE release

---

modules/tinymce/CHANGELOG.md
modules/tinymce/package.json

Related Ticket: TINY-10135
* Preparation for TinyMCE 6.6.2 release
Pre-checks:
Review:

TINY-10135: Preparation for TinyMCE 6.6.2 release

---

modules/tinymce/src/themes/silver/main/ts/ui/statusbar/Statusbar.ts

Related Ticket: TINY-9379, TINY-9898
* Updated text to accommodate for translations. Will convert the text to a shortcut based on OS
Pre-checks:
Review:

TINY-9379: Update help text to accommodate for translations

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/themes/silver/main/ts/ui/core/complex/BespokeNumberInput.ts
modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/NumberInputTest.ts

We just needed to listen to the right events
Pre-checks:
Review:

TINY-10129: Disable now toggles for numberinput as expected.

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/plugins/media/main/ts/core/DataToHtml.ts
modules/tinymce/src/plugins/media/main/ts/core/FilterContent.ts
modules/tinymce/src/plugins/media/main/ts/core/HtmlToData.ts
modules/tinymce/src/plugins/media/main/ts/core/Selection.ts
modules/tinymce/src/plugins/media/main/ts/core/Types.ts
modules/tinymce/src/plugins/media/test/ts/browser/ScriptContentTest.ts

Removed all the script stuff, added a test.
Pre-checks:
Review:

TINY-10007: Removed script recognition in media plugin

---

modules/oxide/src/less/theme/content/table-of-contents/table-of-contents.less

No changelog included as this is a fix for an as-of-now unrelased feature.
Pre-checks:
* ~~[ ] Changelog entry added~~
Review:

TINY-10171: Restrict hiding the counter to ol-lists only.

---

modules/tinymce/CHANGELOG.md

Related Ticket: DOC-2169: edits, copy-edits, and markup changes to changelog.md
* Edits, copy-edits, and markup changes.
Pre-checks:
~* [] Changelog entry added~
Review:
~* [ ] Milestone set~

DOC-2169: edits, copy-edits, and markup changes to changelog.md

---

modules/sugar/CHANGELOG.md
modules/sugar/package.json
modules/sugar/src/main/ts/ephox/sugar/api/dom/Focus.ts
modules/tinymce/CHANGELOG.md
modules/tinymce/src/themes/silver/main/ts/ui/throbber/Throbber.ts
modules/tinymce/src/themes/silver/test/ts/browser/throbber/ThrobberFocusTest.ts
versions.txt

Related Ticket: TINY-10172
* Prevent scroll when showing the Throbber
Pre-checks:
Review:

TINY-10172: Prevent scroll when showing the Throbber

---

modules/tinymce/CHANGELOG.md
modules/tinymce/package.json

Related Ticket: TINY-10164
* Update changelog heading and package.json version for 6.7.1 release
Pre-checks:
Review:

TINY-10164: Update changelog heading and package.json version for 6.7.1 release

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/themes/silver/main/ts/Render.ts
modules/tinymce/src/themes/silver/main/ts/Theme.ts
modules/tinymce/src/themes/silver/main/ts/modes/Iframe.ts
modules/tinymce/src/themes/silver/main/ts/modes/Inline.ts

Related Ticket: TINY-10249
I `cherry-pick`ed [this develop PR](https://github.com/tinymce/tinymce/pull/9064)
Pre-checks:
Review:

TINY-10249: avoid flickering when remove and put the editor back (#9064)

---

modules/mcagar/CHANGELOG.md
modules/mcagar/src/main/ts/ephox/mcagar/alien/EditorTypes.ts
modules/mcagar/src/main/ts/ephox/mcagar/api/bdd/TinyState.ts
modules/tinymce/src/plugins/advlist/test/ts/browser/NoneditableRootTest.ts

Related Ticket: TINY-10304
* Backporting fixes to tests causing issues as we merge things in.
Pre-checks:
Review:

TINY-10304: Fixed broken non-editable root advlist test (#9091)

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/plugins/lists/main/ts/listmodel/ComposeList.ts
modules/tinymce/src/plugins/lists/main/ts/listmodel/Entry.ts
modules/tinymce/src/plugins/lists/main/ts/listmodel/ListsIndendation.ts
modules/tinymce/src/plugins/lists/main/ts/listmodel/NormalizeEntries.ts
modules/tinymce/src/plugins/lists/main/ts/listmodel/ParseLists.ts
modules/tinymce/src/plugins/lists/test/ts/browser/IndentTest.ts
modules/tinymce/src/plugins/lists/test/ts/browser/ListModelTest.ts

Related Ticket: TINY-10213
Description of Changes: cherry-pick of: https://github.com/tinymce/tinymce/pull/9035
Pre-checks:
Review:

TINY-10213: manage li with a list and then other elements

---

modules/tinymce/CHANGELOG.md
modules/tinymce/package.json

Related Ticket: TINY-10226
* Updated changelog and package version to 6.7.2
Pre-checks:
Review:

TINY-10226: Preparation for 6.7.2 TinyMCE release

---

modules/tinymce/CHANGELOG.md
modules/tinymce/package.json
modules/tinymce/src/core/main/ts/content/ContentTypes.ts
modules/tinymce/src/core/main/ts/content/InsertContentImpl.ts
modules/tinymce/src/core/main/ts/content/SetContentImpl.ts
modules/tinymce/src/core/main/ts/dom/TrimBody.ts
modules/tinymce/src/core/main/ts/text/Zwsp.ts
modules/tinymce/src/core/test/ts/browser/UndoManagerTest.ts
modules/tinymce/src/core/test/ts/browser/content/EditorContentTest.ts
modules/tinymce/src/core/test/ts/browser/content/EditorGetContentRawTest.ts
modules/tinymce/src/core/test/ts/browser/content/EditorGetContentTreeTest.ts
modules/tinymce/src/core/test/ts/browser/content/EditorResetContentTest.ts
modules/tinymce/src/core/test/ts/browser/content/InsertContentTest.ts
modules/tinymce/src/core/test/ts/browser/content/PlaceholderVisuallyEmptyTest.ts
modules/tinymce/src/core/test/ts/browser/dom/TrimBodyTest.ts
modules/tinymce/src/core/test/ts/browser/fmt/ExpandRangeTest.ts
modules/tinymce/src/core/test/ts/browser/init/EditorInitializationTest.ts
modules/tinymce/src/core/test/ts/browser/keyboard/EnterKeyAnchorTest.ts
modules/tinymce/src/core/test/ts/browser/undo/LevelsTest.ts
modules/tinymce/src/plugins/autosave/test/ts/browser/AutoSavePluginTest.ts
modules/tinymce/src/plugins/searchreplace/test/ts/browser/SearchReplacePluginTest.ts
modules/tinymce/src/plugins/textpattern/main/ts/keyboard/KeyHandler.ts

Related Ticket: TINY-10333, TINY-10337
* Bring in changes from TINY-10337
* Update changelog and package.json
Pre-checks:
Review:

TINY-10333: Prepare for 5.10.9 Community Release

---

modules/tinymce/CHANGELOG.md
modules/tinymce/package.json
modules/tinymce/src/core/main/ts/content/ContentTypes.ts
modules/tinymce/src/core/main/ts/content/InsertContentImpl.ts
modules/tinymce/src/core/main/ts/content/SetContentImpl.ts
modules/tinymce/src/core/main/ts/dom/TrimBody.ts
modules/tinymce/src/core/main/ts/text/Zwsp.ts
modules/tinymce/src/core/main/ts/textpatterns/keyboard/KeyHandler.ts
modules/tinymce/src/core/test/ts/browser/FormatterRemoveTest.ts
modules/tinymce/src/core/test/ts/browser/UndoManagerTest.ts
modules/tinymce/src/core/test/ts/browser/content/EditorContentTest.ts
modules/tinymce/src/core/test/ts/browser/content/EditorGetContentRawTest.ts
modules/tinymce/src/core/test/ts/browser/content/EditorGetContentTreeTest.ts
modules/tinymce/src/core/test/ts/browser/content/EditorResetContentTest.ts
modules/tinymce/src/core/test/ts/browser/content/InsertContentTest.ts
modules/tinymce/src/core/test/ts/browser/delete/InlineFormatPostShortcutDeleteTest.ts
modules/tinymce/src/core/test/ts/browser/dom/TrimBodyTest.ts
modules/tinymce/src/core/test/ts/browser/fmt/ExpandRangeTest.ts
modules/tinymce/src/core/test/ts/browser/init/EditorInitializationTest.ts
modules/tinymce/src/core/test/ts/browser/keyboard/EnterKeyAnchorTest.ts
modules/tinymce/src/core/test/ts/browser/text/ZwspInsertTest.ts
modules/tinymce/src/core/test/ts/browser/undo/LevelsTest.ts
modules/tinymce/src/plugins/autosave/test/ts/browser/AutoSavePluginTest.ts
modules/tinymce/src/plugins/searchreplace/test/ts/browser/SearchReplacePluginTest.ts

Related Ticket: TINY-10319, TINY-10305
* Bring in changes from TINY-10305
* Update changelog and package.json
Pre-checks:
Review:

TINY-10319: Prepare for 6.7.3 Community Release

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/core/main/ts/api/dom/StyleSheetLoader.ts

Related Ticket: TINY-10372
* Removed changelog items for the Resource API since that API is not documented in the API docs. Will do that post 6.8
* Updated `unloadRawCss` API docs so that it has the right method name.
* Added docs for `loadRawCss` API since that is a module that has API docs.
Pre-checks:
Review:

TINY-10372: Updated changelog and StylesheetLoader APIs

---

modules/tinymce/CHANGELOG.md

Related Ticket: Didn't bother to create a ticket.
* Remove blank line between the Added and Improved sections.
* Removed the extra changelog item about hex colors. @kemister85 told me to remove that.
Pre-checks:
Review:

Some changelog cleanup

---

modules/tinymce/CHANGELOG.md
modules/tinymce/src/core/main/ts/api/html/Schema.ts
modules/tinymce/src/core/test/ts/browser/html/SchemaTest.ts
modules/tinymce/src/core/test/ts/webdriver/paste/CutTest.ts

Related Ticket: TINY-10385
backport for: https://github.com/tinymce/tinymce/pull/9195
Pre-checks:
Review:

TINY-10385: fix schema.isWrapper function

---

modules/acid/src/demo/ts/ephox/acid/demo/Demo.ts
modules/acid/src/main/ts/ephox/acid/alien/I18n.ts
modules/acid/src/main/ts/ephox/acid/gui/ColourPicker.ts
modules/acid/src/main/ts/ephox/acid/gui/components/HueSlider.ts
modules/acid/src/main/ts/ephox/acid/gui/components/SaturationBrightnessPalette.ts
modules/alloy/CHANGELOG.md
modules/alloy/src/main/ts/ephox/alloy/ui/slider/HorizontalModel.ts
modules/alloy/src/main/ts/ephox/alloy/ui/slider/SliderParts.ts
modules/alloy/src/main/ts/ephox/alloy/ui/slider/SliderSchema.ts
modules/alloy/src/main/ts/ephox/alloy/ui/slider/SliderUi.ts
modules/alloy/src/main/ts/ephox/alloy/ui/slider/SliderValues.ts
modules/alloy/src/main/ts/ephox/alloy/ui/slider/TwoDModel.ts
modules/alloy/src/main/ts/ephox/alloy/ui/slider/VerticalModel.ts
modules/alloy/src/main/ts/ephox/alloy/ui/types/SliderTypes.ts
modules/oxide/src/less/theme/components/color-picker/color-picker.less
modules/tinymce/CHANGELOG.md
modules/tinymce/src/themes/silver/main/ts/ui/dialog/ColorPicker.ts
modules/tinymce/src/themes/silver/test/ts/browser/editor/color/ColorPickerSanityTest.ts

No changes aside from backporting
Pre-checks:
* ~~[ ] Changelog entry added~~
Review:
* ~~[ ] Docs ticket created (if applicable)~~

TINY-10383: Backporting accessability which was removed from 6.8.0 for 6.8.1

---

modules/tinymce/CHANGELOG.md
modules/tinymce/package.json

Related Ticket: TINY-10388
* Prepare 6.8.1 Community release
Pre-checks:
Review:

TINY-10388: Prepare 6.8.1 Community release

---

modules/alloy/CHANGELOG.md
modules/tinymce/CHANGELOG.md
modules/tinymce/package.json

https://ephocks.atlassian.net/browse/TINY-10419
- Bump tinymce version
- Bump alloy changelog version
Pre-checks:
Review:

TINY-10419: Prepare for 6.8.2 release

---

modules/oxide/src/less/theme/components/revisionhistory/revisionhistory.less

Related Ticket: TINY-10541
Pre-checks:
* ~[ ] Branch prefixed with `feature/`, `hotfix/` or `spike/`~
Review:
* ~[ ] Docs ticket created (if applicable)~

TINY-10541: Fix typo of revision history style

---

modules/tinymce/src/core/test/ts/webdriver/keyboard/IframeTabfocusTest.ts
modules/tinymce/src/plugins/charmap/test/ts/browser/CharmapDialogHeightTest.ts
modules/tinymce/src/themes/silver/test/ts/browser/editor/bespoke/SilverBespokeButtonsTest.ts
modules/tinymce/src/themes/silver/test/ts/headless/components/iframe/IframeTest.ts

Related Ticket: TINY-10579
* Just a backport of the fixes that was added to `develop` to fix some test flakes
Pre-checks:
Review:

TINY-10579: Fixed flakes

---

modules/oxide/src/less/theme/components/advcode/advcode.less

Related Ticket: TINY-10561
This should be the last one for this ticket, sorry :sweat_smile: 
Pre-checks:
Review:

TINY-10561: fix for inline mode

---

.changes/unreleased/tinymce-TINY-10433-2024-02-05.yaml
modules/tinymce/src/core/main/ts/api/Options.ts

Related Ticket: TINY-10433
* Resolves #9218 
Pre-checks:
Review:
#9218

TINY-10433: Fixed incorect object processor for `event_root` option

---

modules/tinymce/src/plugins/help/main/ts/data/PluginUrls.ts

Related Ticket: TINY-10600
Added revisionhistory to the plugin list in the help dialog.
Pre-checks:
~~* [ ] Changelog entry added~~
~~* [ ] Tests have been added (if applicable)~~
Review:
~~* [ ] Docs ticket created (if applicable)~~

TINY-10600: Add revisionhistory plugin to help dialog

---

modules/oxide/src/less/theme/components/revisionhistory/revisionhistory.less

Related Ticket: TINY-10598
Pre-checks:
* ~[x] Changelog entry added~
* ~[x] Tests have been added (if applicable)~
Review:

TINY-10598: Add style for no revision message of revision history

---

Jenkinsfile
package.json
yarn.lock

Related Ticket: TINY-10622
* Update bedrock to better implement remote testing
Pre-checks:
Review:

TINY-10622: Update bedrock for remote testing

---

.changes/unreleased/tinymce-TINY-9638-2024-02-20.yaml

Related Ticket: TINY-9638
* Add changelog entry for TINY-9638
Pre-checks:
Review:

TINY-9638: Add changelog entry for TINY-9638

---

modules/oxide/src/less/theme/components/revisionhistory/revisionhistory.less

Related Ticket: TINY-10543
Pre-checks:
Review:

TINY-10543: Add outline style for revision cards being focused

---

.changes/unreleased/tinymce-TINY-10675-2024-02-25.yaml
modules/oxide/src/less/theme/components/advcode/advcode.less

Related Ticket: TINY-10675
fix some styles for `advcode`
Pre-checks:
Review:

TINY-10675: fix `advcode` styles

---

.changes/unreleased/tinymce-TINY-10694-2024-02-28.yaml
modules/tinymce/src/core/main/ts/Deprecations.ts

Related Ticket: TINY-10694
* Update deprecation/removed console message for 7.0
Pre-checks:
Review:

TINY-10694: Update deprecation/removed console message for 7.0

---

Jenkinsfile

Related Ticket: TINY-10706
* Update requested resources
Pre-checks:
* [-] Branch prefixed with `feature/`, `hotfix/` or `spike/`
Review:
* [-] Milestone set

TINY-10706: Update pod resources

---

modules/oxide/src/less/theme/components/revisionhistory/revisionhistory.less

Related Ticket: TINY-10544
* Update styles there are some structure changes introduced, visually there should be no difference, before and after screenshots visible in premium repo.
Pre-checks:
Review:

TINY-10544: Update revision history styles

---

.changes/unreleased/acid-TINY-10578-2024-02-29.yaml
.changes/unreleased/agar-TINY-10578-2024-02-29.yaml
.changes/unreleased/alloy-TINY-10578-2024-02-29.yaml
.changes/unreleased/boss-TINY-10578-2024-02-29.yaml
.changes/unreleased/boulder-TINY-10578-2024-02-29.yaml
.changes/unreleased/bridge-TINY-10578-2024-02-29.yaml
.changes/unreleased/darwin-TINY-10578-2024-02-29.yaml
.changes/unreleased/dragster-TINY-10578-2024-02-29.yaml
.changes/unreleased/jax-TINY-10578-2024-02-29.yaml
.changes/unreleased/katamari-TINY-10578-2024-02-29.yaml
.changes/unreleased/katamari-assertions-TINY-10578-2024-02-29.yaml
.changes/unreleased/mcagar-TINY-10578-2024-02-29.yaml
.changes/unreleased/phoenix-TINY-10578-2024-02-29.yaml
.changes/unreleased/polaris-TINY-10578-2024-02-29.yaml
.changes/unreleased/porkbun-TINY-10578-2024-02-29.yaml
.changes/unreleased/robin-TINY-10578-2024-02-29.yaml
.changes/unreleased/sand-TINY-10578-2024-02-29.yaml
.changes/unreleased/snooker-TINY-10578-2024-02-29.yaml
.changes/unreleased/sugar-TINY-10578-2024-02-29.yaml

Related Ticket: TINY-10578
* Adds changelog details to the libraries on the license change.
Pre-checks:
Review:

TINY-10578: Added changelogs for libraries

---

Jenkinsfile

Related Ticket: TINY-10691
* Update name of test runs to have better telemetry in LT dashboard/metrics
Pre-checks:
Review:
* [-] Milestone set

TINY-10691: Test name changes for LT metrics

---

modules/tinymce/src/core/main/ts/init/LicenseKeyValidation.ts
modules/tinymce/src/core/test/ts/browser/init/LicenseKeyValidationTest.ts

Related Ticket: TINY-10754
* Updated message for invalid/missing license key
Pre-checks:
Review:

TINY-10754: Updated the license message

---

modules/tinymce/package.json

Related Ticket: TINY-10838
* Bumped tinymce version to 7.0.1
Pre-checks:
Review:

TINY-10838: Bumped version

---

.changes/unreleased/tinymce-TINY-10715-2024-03-14.yaml

Related Ticket: TINY-10845
* Removed a changelog item that was added as a hotfix.
Pre-checks:
Review:

TINY-10845: Removed hotfix changelog items

---

.changes/unreleased/tinymce-TINY-10780-2024-04-08.yaml
modules/tinymce/src/core/demo/ts/demo/ViewDemo.ts
modules/tinymce/src/themes/silver/main/ts/ui/view/View.ts
modules/tinymce/src/themes/silver/test/ts/browser/view/ViewTest.ts

Related Ticket: TINY-10780
- Add tab behavior to the factory
- Add `Focusing` and `Tabstopping` to the view pane
Pre-checks:
Review:

TINY-10780: Fix views tab navigation

---

modules/tinymce/package.json

* Updated TinyMCE version to 7.2
Pre-checks:
Review:

Bump TinyMCE version for next release

---

.changes/unreleased/tinymce-TINY-10718-2024-04-19.yaml
.changes/unreleased/tinymce-TINY-10741-2024-04-12-1.yaml
.changes/unreleased/tinymce-TINY-10741-2024-04-12.yaml
.changes/unreleased/tinymce-TINY-10781-2024-04-22.yaml
.changes/unreleased/tinymce-TINY-9811-2024-04-19.yaml
.changes/unreleased/tinymce-TINY-9932-2024-03-06.yaml

Related Ticket: TINY-10629
* Added missing full stops and styling markups
* Grammar correction
Pre-checks:
Review:

TINY-10629: Minor fixes to changelog entries

---

SECURITY.md

Related Ticket: TINY-10628
Pre-checks:

TINY-10628: Bump version in SECURITY.md

---

build.properties
modules/tinymce/package.json

TINY-10628: Bump version to the next patch

---

.changes/unreleased/tinymce-TINY-10942-2024-05-15.yaml
modules/tinymce/src/core/main/ts/keyboard/Autocompleter.ts

Duplicate PR of #9645 but targeting release/7 branch.

TINY-10942: Show autocompleter regardless of match length (base release/7)

---

.changes/unreleased/tinymce-TINY-10885-2024-04-30.yaml
.changes/unreleased/tinymce-TINY-10942-2024-05-15.yaml

Related Ticket: TINY-10897
* Removes changelog items that was merged into main but also hotfixed on `release/7`
Pre-checks:
Review:

TINY-10897: Removed some duplicate changelog items

---

modules/tinymce/src/themes/silver/test/ts/webdriver/dialogs/IFrameDialogTest.ts

Related Ticket: TINY-10974
backport of https://github.com/tinymce/tinymce/pull/9666 for release branch
Pre-checks:
Review:

TINY-10974: fix tests for new Firefox version (126)

---

.changes/unreleased/tinymce-TINY-10938-2024-05-15.yaml
modules/tinymce/src/core/main/ts/paste/Paste.ts
modules/tinymce/src/core/test/ts/browser/paste/PasteTest.ts

Related Ticket: https://ephocks.atlassian.net/browse/TINY-10938
Added querycommand
Pre-checks:
Review:

TINY-10938: Added query command for paste as plaintext status.

---

.changes/unreleased/tinymce-TINY-6887-2024-05-29.yaml
modules/tinymce/src/plugins/table/test/ts/browser/TableContextMenuInsertTest.ts
modules/tinymce/src/plugins/table/test/ts/module/test/TableTestUtils.ts
modules/tinymce/src/themes/silver/main/ts/ui/menus/item/build/InsertTableMenuItem.ts

TINY-6887
- Changed the order actions, sandbox is closed before action is triggered
Pre-checks:
Review:

TINY-6887: Change the action order

---

.changes/unreleased/katamari-TINY-10946-2024-06-05.yaml
.eslintrc.json
modules/boss/src/main/ts/ephox/boss/mutant/Creator.ts
modules/katamari/src/main/ts/ephox/katamari/api/Id.ts
modules/katamari/src/main/ts/ephox/katamari/api/Num.ts
modules/snooker/src/test/ts/atomic/model/FitmentIVTest.ts
modules/sugar/src/test/ts/browser/impl/RuntimeSizeTest.ts
modules/tinymce/src/core/main/ts/util/Uuid.ts
modules/tinymce/src/core/test/ts/browser/EditorUploadTest.ts
modules/tinymce/src/core/test/ts/browser/init/InitIframeEditorCookiesTest.ts
modules/tinymce/src/plugins/autosave/test/ts/browser/AutoSavePluginTest.ts
modules/tinymce/src/plugins/autosave/test/ts/browser/ShouldRestoreWhenEmptyTest.ts
package.json
yarn.lock

Related Ticket: TINY-10946
replaced `Math.random` with `crypto.getRandomValues`
Pre-checks:
Review:

TINY-10946: replace `Math.random` with `crypto.getRandomValues`

---

Jenkinsfile

* I don't recommend doing this but here is the jenkinsfile without mac and edge tests
Pre-checks:
Review:
* [-] Milestone set

Disable tests for downed infrastrcuture

---

.eslintrc.json

Related Ticket: TINY-10946
follow up of: https://github.com/tinymce/tinymce/pull/9687
Pre-checks:
Review:

TINY-10946: update global eslint rules

---

modules/oxide-icons-default/src/svg/format-code.svg

Related Ticket: TINY-11018
Added format code icon
Pre-checks:
Review:

TINY-11018: add format code icon

---

modules/tinymce/package.json

Related Ticket: TINY-11023
* Bump versions for next patch
Pre-checks:
Review:

TINY-11023: Bump release version

---

.changes/unreleased/agar-TINY-11025-2024-07-09.yaml
modules/agar/src/main/ts/ephox/agar/api/Mouse.ts
modules/agar/src/main/ts/ephox/agar/mouse/Clicks.ts

Related Ticket: TINY-11025
Added dblclick functions to agar/Mouse
Pre-checks:
Review:

TINY-11025: add dblclick function to agar Mouse

---

modules/tinymce/src/themes/silver/main/ts/ui/dialog/TextField.ts

Related Ticket: TINY-11008
Added data-mce-name as an attribute to be used in tests as css selector
Pre-checks:
Review:

TINY-11008: add data-mce attribute for input

---

modules/oxide/src/less/theme/components/revisionhistory/revisionhistory.less

Related Ticket: TINY-11014
* Added styles for author in the revision card
Pre-checks:
Review:

TINY-11014: Add styles for revision author

---

modules/oxide/src/less/theme/components/revisionhistory/revisionhistory.less

TINY-11073
- Add revision card label css
Pre-checks:
Review:

TINY-11073: Add CSS improvement for revision history

---

.changes/unreleased/tinymce-TINY-10116-2024-07-22.yaml
.changes/unreleased/tinymce-TINY-10636-2024-07-22.yaml

TINY-10636, TINY-10116
- Remove change logs
Pre-checks:
Review:

TINY-10636: Remove 10636 and 10116 changelog

---

modules/oxide/src/less/theme/components/collection/collection.less

TINY-10636
- Removed single quote, it cased invalid CSS after compile
Pre-checks:
Review:

TINY-10636: Update keyboard-focus-outline-mixin in collection.less

---

modules/tinymce/src/plugins/emoticons/test/ts/browser/EmojiStyleTest.ts

TINY-10636
- Added test to check incorrect css syntax
Pre-checks:
Review:

TINY-10636: Added test to check incorrect css syntax

---

yarn.lock

Related Ticket: TINY-11149
* Update lambdatest node-tunnel dependency
Pre-checks:
Review:
* [-] Milestone set

TINY-11149: Update lambda node-tunnel dependency

---

modules/oxide/src/less/theme/components/comments/comment.less

Related Ticket: TINY-11278
* Update focus style of a single comment inside a conversation card
Pre-checks:
Review:

TINY-11278: Update focus style of a single comment inside a conversation card

---

modules/oxide/src/less/theme/components/comments/comment.less

Related Ticket: TINY-11278
* Fix focus border color
Pre-checks:
Review:

TINY-11278: Fix focus border color

---

.changes/unreleased/tinymce-TINY-11332-2024-10-08.yaml
modules/tinymce/package.json
modules/tinymce/src/core/main/ts/html/Sanitization.ts
modules/tinymce/src/core/test/ts/browser/content/insert/NamespaceElementsTest.ts
modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts
modules/tinymce/src/core/test/ts/browser/html/SanitizationTest.ts
modules/tinymce/src/core/test/ts/browser/html/SerializerTest.ts
package.json
patches/dompurify+3.1.7.patch
yarn.lock

Related Ticket: TINY-11332
* Update dompurify and relevant tests for security patch
Pre-checks:
Review:

TINY-11332: Update dependencies

---

SECURITY.md

TINY-11024
- Post release security version bump
Pre-checks:
Review:

TINY-11024: Bump Tinymce security version

---

.changes/unreleased/tinymce-TINY-11095-2024-10-10.yaml
modules/bridge/src/main/ts/ephox/bridge/api/InlineContent.ts
modules/bridge/src/main/ts/ephox/bridge/components/content/ContextToolbar.ts
modules/oxide/src/less/skins/ui/tinymce-5/skin.less
modules/oxide/src/less/theme/components/toolbar-button/toolbar-label.less
modules/oxide/src/less/theme/theme.less
modules/tinymce/src/core/demo/html/context_toolbar_demo.html
modules/tinymce/src/core/demo/ts/demo/ContextToolbarDemo.ts
modules/tinymce/src/core/demo/ts/demo/Demos.ts
modules/tinymce/src/core/demo/ts/demo/FullDemo.ts
modules/tinymce/src/core/main/ts/api/OptionTypes.ts
modules/tinymce/src/themes/silver/main/ts/ui/context/ContextForm.ts
modules/tinymce/src/themes/silver/main/ts/ui/context/ContextToolbar.ts
modules/tinymce/src/themes/silver/main/ts/ui/toolbar/CommonToolbar.ts
modules/tinymce/src/themes/silver/main/ts/ui/toolbar/Integration.ts
modules/tinymce/src/themes/silver/test/ts/headless/toolbar/ToolbarTest.ts

Related Ticket: TINY-11095
example:
Pre-checks:
Review:

TINY-11095: add inline label for toolbars' groups

---

modules/oxide/src/less/theme/components/statusbar/statusbar.less

Related Ticket: TINY-11381
* Fix hidden statusbar focus outline
Pre-checks:
Review:

TINY-11381: Fix hidden statusbar focus outline

---

modules/oxide/src/less/theme/components/comments/comment.less
modules/oxide/src/less/theme/content-ui.less
modules/oxide/src/less/theme/content/uploadcare/loader.less
modules/oxide/src/less/theme/content/uploadcare/uploadcare.less
modules/oxide/src/less/theme/globals/animations.less

Related Ticket: TINY-11338
Loader and overlay styles.
Pre-checks:
Review:

TINY-11338: add uploadcare loader styles to oxide

---

modules/oxide/src/less/theme/components/comments/comment.less

TINY-11174: update styles to match new design

---

.changes/unreleased/tinymce-TINY-11395-2024-10-17.yaml
modules/tinymce/src/core/main/ts/api/NotificationManager.ts

TINY-11395
- Update changelog and comment
Pre-checks:
Review:

TINY-11395: Update changelog and comment

---

modules/oxide/src/less/skins/content/dark/content.less
modules/oxide/src/less/skins/ui/dark/content.less
modules/oxide/src/less/theme/content/comments/comments.less
modules/oxide/src/less/theme/globals/global-variables.less

Related Ticket: TINY-11405
Removing variables from `modules/oxide/src/less/skins/content/dark/content.less`
Pre-checks:
Review:

TINY-11405: remove variables from content css

---

modules/oxide/src/less/skins/content/dark/content.less
modules/oxide/src/less/skins/content/default/content.less
modules/oxide/src/less/skins/content/document/content.less
modules/oxide/src/less/theme/content-ui.less
modules/oxide/src/less/theme/content/list/list.less
modules/tinymce/src/core/test/ts/browser/fmt/ListIndentationFormatTest.ts

TINY-11217
Move list item style change to content folder
Pre-checks:
Review:

TINY-11217: Move list item style change to content folder

---

modules/oxide/src/less/theme/content/uploadcare/uploadcare.less

Related Ticket: TINY-11458
Separate class for semitransparent background. 
Pre-checks:
Review:

TINY-11458: uploadcare loader css classes

---

.changes/unreleased/tinymce-TINY-11459-2024-11-08.yaml
modules/bridge/src/main/ts/ephox/bridge/components/content/ContextForm.ts
modules/tinymce/src/themes/silver/main/ts/ui/context/ContextFormTextInput.ts
modules/tinymce/src/themes/silver/test/ts/browser/editor/contextform/ContextFormTest.ts
modules/tinymce/src/themes/silver/test/ts/browser/editor/contexttoolbar/ContextToolbarLookupPrioritisationTest.ts

Related Ticket: TINY-11459
Add placeholder for context form input
Pre-checks:
Review:

TINY-11459: add placeholder for context form input

---

modules/oxide/src/less/theme/components/comments/comment.less

Related Ticket: TINY-11447
Comments dark mode fixes: 
- Comment card color border
Pre-checks:
Review:

TINY-11447: comments dark mode fixes

---

modules/oxide/src/less/theme/components/accessibility-checker/accessibility-checker.less

TINY-11523
Pre-checks:
Review:

TINY-11523: Add announcement area for accessbility dialog

---

modules/oxide/src/less/theme/theme.less

Related Ticket: TINY-11625
Import animations to fix a bug with comments saving button
Pre-checks:
Review:

TINY-11625: import animations in theme

---

modules/tinymce/src/themes/silver/main/ts/ui/context/ContextFormSlider.ts
modules/tinymce/src/themes/silver/main/ts/ui/context/ContextFormTextInput.ts

Related Ticket: TINY-11594
* The the labels didn't call the translate function
Pre-checks:
Review:

TINY-11594: Added missing translate calls

---

Jenkinsfile

Related Ticket: TINY-11749
* Use PTC image to avoid rate limiting
Pre-checks:
Review:

TINY-11749: Use PTC images

---

Jenkinsfile

Related Ticket: TINY-11962
* Skip safari testing due to MacOS Sequoia CI issues
Pre-checks:
Review:

TINY-11962: Skip safari

---

modules/tinymce/src/core/main/ts/SelectionOverrides.ts

Related Ticket: TINY-11997
fix a bug in plugin introduced by `TINY-11997`
Pre-checks:
Review:

TINY-11997: fix bug in plugins

---

NOTICES.txt
modules/oxide/Gruntfile.js
modules/oxide/src/text/build-header.js
modules/tinymce/Gruntfile.js
modules/tinymce/src/core/text/tinymce-license-headers.js

Related Ticket: TINY-12091
* Add Notices and license headers
Pre-checks:
Review:

TINY-12091: [cherry-pick] Add Notices to TinyMCE component

---

Jenkinsfile
NOTICES.txt
modules/oxide-icons-default/package.json
modules/oxide/gulpfile.js
modules/oxide/src/text/build-header.js
modules/sugar/src/test/ts/browser/VisibilityTest.ts
modules/tinymce/Gruntfile.js
modules/tinymce/src/core/test/ts/browser/delete/InlineFormatDeleteTest.ts
modules/tinymce/src/core/test/ts/webdriver/delete/InlineFormatRetentionTest.ts
modules/tinymce/src/core/test/ts/webdriver/delete/ShortcutDeleteTest.ts
modules/tinymce/src/core/text/tinymce-license-headers.js

Related Ticket: TINY-12098
* Add license and notices
Pre-checks:
Review:

TINY-12098: Add license and notices

---

modules/tinymce/src/core/test/ts/browser/delete/SelectedHTMLElementDeleteTest.ts

Related Ticket: TINY-12092
* Update tests for colgroup and col to match implementation
Pre-checks:
Review:

TINY-12092: Fix failing test to reflect correct behaviour

---

modules/tinymce/Gruntfile.js
modules/tinymce/src/core/text/prism-header.js

Related Ticket: TINY-12177
* License headers added where missing
Pre-checks:
Review:
* ~[ ] Docs ticket created (if applicable)~

TINY-12177: Add license headers after terser instead. Add prismjs license

---

modules/oxide/src/less/theme/components/toolbar-button/toolbar-split-button.less

TINY-12497
- Update split button main button width to auto
Pre-checks:
Review:

TINY-12497: Update split button main button width to auto

---

.changes/unreleased/tinymce-TINY-12013-2025-05-04.yaml
.changes/unreleased/tinymce-TINY-12462-2025-07-07.yaml
modules/tinymce/src/plugins/pagebreak/main/ts/api/Options.ts
modules/tinymce/src/plugins/pagebreak/test/ts/browser/PageBreakSplitBlockTest.ts

Related Ticket: TINY-12537
* Revert changes from EPIC-233
Pre-checks:
Review:

TINY-12537: Revert changes from EPIC-233

---

README.md

Related Ticket: TINY-12559
* Update README to reflect TinyMCE 8 version and related documentation links for TinyMCE 8.0.0 release.
Pre-checks:
Review:

TINY-12559: Update README to reflect TinyMCE 8 version and related documentation links.

---

SECURITY.md
modules/oxide-icons-default/README.md
modules/oxide/README.md
modules/tinymce/README.md
modules/tinymce/src/core/main/ts/Deprecations.ts
modules/tinymce/src/core/main/ts/api/EditorManager.ts
modules/tinymce/src/core/main/ts/api/NotificationManager.ts
modules/tinymce/src/core/main/ts/api/WindowManager.ts
modules/tinymce/src/core/main/ts/api/fmt/StyleFormat.ts
modules/tinymce/src/core/main/ts/api/ui/Registry.ts
modules/tinymce/src/core/main/ts/api/util/Observable.ts
modules/tinymce/src/plugins/help/main/ts/ui/VersionTab.ts

Related Ticket: TINY-12585
* Update links in comments, messages and readmes pointing to new major
Pre-checks:
Review:

TINY-12585: Update links

---

modules/tinymce/src/core/test/ts/browser/SelectionEnabledModeTest.ts
modules/tinymce/src/core/test/ts/browser/util/QuirksFirefoxTest.ts
modules/tinymce/src/core/test/ts/module/Assets.ts
modules/tinymce/src/core/test/ts/webdriver/content/SelectionEnabledModeTest.ts
modules/tinymce/src/plugins/image/test/ts/browser/DialogUpdateTest.ts
modules/tinymce/src/plugins/image/test/ts/module/Helpers.ts
modules/tinymce/src/plugins/link/test/ts/browser/SelectedImageFigureLinkTest.ts
modules/tinymce/src/themes/silver/test/ts/browser/editor/menubar/EditorMenuItemContextTest.ts
modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/ToolbarButtonContextTest.ts
modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/ToolbarOverflowContextTest.ts

Related Ticket:TINY-12247
* Fix flaky tests, remove use of remote resources in tests and replace with base64 img
Pre-checks:
Review:

TINY-12247: Fix flaky tests

---

modules/oxide/src/less/theme/components/suggestededits/suggestededits.less

Related Ticket: TINY-12847
* Reordering classes of suggested edits content iframe
* Improving height and width calculations
Pre-checks:
Review:

TINY-12847: Accompanying style changes to content iframe

---

modules/tinymce/src/core/main/ts/api/dom/ControlSelection.ts

Related Ticket: TINY-12184
add a specific way to resize `uc-video`'s ghost
Pre-checks:
Review:

TINY-12184: add resize to `uc-video`
