tinymce/tinymce

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/SelectionOverrides.ts
- modules/tinymce/src/core/test/ts/browser/paste/InternalClipboardTest.ts
Related Ticket: TINY-8563
This removes the `copy` logic for CEF elements in the `SelectionOverrides` code because this is no longer needed now that we have the paste plugin in core. Additionally, having this here meant it ran first and didn't add the internal HTML comment mark to the clipboard content, which in turn caused issues when pasting it within the editor. Now the reason this isn't needed, is the paste logic uses `editor.selection.getRng()` to get the range and clone the contents, so `SelectionOverrides` already adjusts the range back to the real element instead of the offscreen clone.
Pre-checks:
Review:
> TINY-8563: Fixed internal marks not added to clipboard content when cef elements were selected

- modules/tinymce/src/core/test/ts/browser/NotificationManagerTest.ts
Related Ticket: TINY-8575
This test includes a service message that means it opens the notification during init. That in turn causes issues if the first test in the suite doesn't run first, so this adjusts the tests to make sure it always works when the tests are run in isolation.
Pre-checks:
Review:
> TINY-8575: Fixed the notification manager tests failing in isolation

- modules/tinymce/src/core/main/ts/Deprecations.ts
- modules/tinymce/src/core/test/ts/browser/paste/PasteTest.ts
Related Ticket: TINY-8580
* Added the 3 options that were missing in the deprecations warnings that were removed in 6.0
* Cleaned up the `PasteTest.ts` file as it still had a couple references to options that were removed
Pre-checks:
Review:
> TINY-8580: Added missing removed options and cleaned up test

- modules/snooker/CHANGELOG.md
- modules/snooker/src/main/ts/ephox/snooker/api/CopySelected.ts
- modules/snooker/src/test/ts/browser/CopySelectedTest.ts
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/table/test/ts/browser/ClipboardTest.ts
Related Ticket: TINY-8568
* Make sure only `td` cells are passed to the `fillInGaps` function. Handling of cols is done further down in the `clean` function already
Pre-checks:
Review:
> TINY-8568: Fix incorrect copying of colgroup table with colspans/rowspans

- modules/oxide/src/less/skins/ui/tinymce-5/skin.less
- modules/tinymce/CHANGELOG.md
Related Ticket: TINY-8564
* Fix double border with `toolbar_location: bottom`
Pre-checks:
Review:
> TINY-8564: Fix double border with toolbar_location: bottom

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/caret/ClosestCaretCandidate.ts
- modules/tinymce/src/core/test/ts/browser/caret/ClosestCaretCandidateTest.ts
Related Ticket: TINY-8567
* Fixes and issue where it wasn't possible to select text after an inline noneditable element.
* It now treats horizontal elements that intersect the x coordinate the same as vertical elements. That means they now have a 0 distance.
* It also favors the text node if there are two candidates that are very close to each other. This is to make it easier to select text after a noneditable if the space between the noneditable and the text node is very small like 2 pixels or less.
* It also fixes a bug where the root children would not be handled correctly if you didn't find a caret candidate in the target element under the specified x, y position.
Pre-checks:
Review:
> TINY-8567: fixed issue where it was not possible to select text after a inline noneditable

- modules/tinymce/CHANGELOG.md
updated the jquery changelog from TINY-4518 to TINY-4519
* the original change log entry was incorrect, but now it has been updated
Pre-checks:
Review:
> TINY-4519:  Fixed incorrect Jira number used in the changelog

- modules/bridge/CHANGELOG.md
- modules/bridge/src/main/ts/ephox/bridge/components/dialog/DialogFooterButton.ts
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/AlertDialog.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/ConfirmDialog.ts
- modules/tinymce/src/themes/silver/main/ts/ui/general/Button.ts
- modules/tinymce/src/themes/silver/test/ts/headless/components/dialogbutton/DialogFooterButtonTest.ts
- modules/tinymce/src/themes/silver/test/ts/headless/window/SilverDialogEventTest.ts
Related Ticket: TINY-8582
* Deprecated `primary` property of dialog footer buttons
* Fixed the buttonType property not working for dialog footer
* Removed `buttonType: Optional.none()` in `Button.ts`
Pre-checks:
Review:
> TINY-8582: Fixed the buttonType property not working for dialog footer

- modules/oxide/src/less/theme/components/notification/notification.less
- modules/tinymce/CHANGELOG.md
Related Ticket: TINY-8586
* Fix incorrectly assigned link color in error messages
Pre-checks:
Review:
> TINY-8586: Fix contrast ratio for error messages

- modules/tinymce/CHANGELOG.md
- modules/tinymce/package.json
- modules/tinymce/src/themes/silver/main/ts/modes/Inline.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/MultipleInlineToolbarVisibilityTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/MultipleToolbarVisibilityTest.ts
Related Ticket: TINY-8594
* Reverted changes that were made in #6916
* Bumped package.json version to 5.10.4
The issue occurring in a single frame makes it difficult to write a reliable test
Pre-checks:
Review:
> TINY-8594: Backport - Fixed inline toolbars flickering when switching between editors

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/dom/TreeWalker.ts
- modules/tinymce/src/core/test/ts/browser/dom/TreeWalkerTest.ts
- modules/tinymce/src/plugins/lists/main/ts/core/Delete.ts
- modules/tinymce/src/plugins/lists/test/ts/browser/BackspaceDeleteFromBlockIntoLiTest.ts
List plugin should no longer step into tables if the last cell of the table contains a list at the end. Also added typing to reflect TreeWalker's ability return undefined in addition to a Node ( such as when reaching the end of a walk ).
Pre-checks:
Review:
> TINY-8592: List backspace function no longer steps into tables

- modules/oxide/src/less/skins/ui/tinymce-5/skin.less
- modules/oxide/src/less/theme/components/toolbar-button/toolbar-select-button.less
- modules/tinymce/CHANGELOG.md
Related Ticket: TINY-8617
* Added background and additional spacing for the text labeled buttons in the toolbar to improve visual clarity
Pre-checks:
Review:
> TINY-8617: Improve visual clarity for text based toolbar selects

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/demo/ts/demo/CommandsDemo.ts
- modules/tinymce/src/core/main/ts/api/commands/NewlineCommands.ts
- modules/tinymce/src/core/main/ts/keyboard/EnterKey.ts
- modules/tinymce/src/core/main/ts/newline/InsertNewLine.ts
- modules/tinymce/src/core/main/ts/newline/NewLineAction.ts
- modules/tinymce/src/core/test/ts/browser/api/commands/NewlineCommandsTest.ts
Related Ticket: TINY-8606
Pre-checks:
Review:
> TINY-8606: Fixed the selection not deleted on `InsertParagraph` execution

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/media/main/ts/core/UpdateHtml.ts
- modules/tinymce/src/plugins/media/test/ts/browser/MediaPluginSanityTest.ts
Related Ticket: TINY-8660
When reworking the media plugin in 6.0 to use the DomParser the wrong media data property was used which caused the source URL to be unable to be updated for iframe based media.
Pre-checks:
Review:
Fixes #7772
> TINY-8660: Fixed media elements not updating when changing the source URL

- modules/tinymce/src/core/main/ts/file/Conversions.ts
Related Ticket: TINY-8349
* Convert native uses of xhr to fetch
There is still one use of xhr in the repo but since it requires progress state and fetch does not provide a simple way to do this, it is better to leave that as is for now
Pre-checks:
Review:
> TINY-8349: Convert xhr to fetch where possible

- modules/oxide/src/less/theme/content/selection/selection.less
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/SelectionOverrides.ts
- modules/tinymce/src/core/main/ts/api/dom/ControlSelection.ts
- modules/tinymce/src/core/test/ts/browser/dom/ControlSelectionTest.ts
Related Ticket: TINY-5947
This fixes an issue where the browser selection would never show for images when more than just the image was selected. The main cause is the CSS we used, however to make that work without flickering it required a change to how we do the selection as we need to ensure the `data-mce-selected` attribute is set immediately, not in the next event loop. This does mean a little bit of the logic runs more often on node change or similar events, but I've tried to keep it minimised so as to not cause performance problems.
Note: I also did some very minor cleanup while I was messing with the code.
Pre-checks:
Review:
Fixes #5450
> TINY-5947: Fixed images not showing as selected when selecting all content

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/dom/Selection.ts
Selection caused errors on test node 4
Pre-checks:
* N/A Tests have been added (if applicable)
Review:
> TINY-8686: Invalid selections would cause errors on newer versions of safari

- modules/tinymce/CHANGELOG.md
- modules/tinymce/package.json
- modules/tinymce/src/plugins/table/main/ts/ui/CellDialog.ts
- modules/tinymce/src/plugins/table/main/ts/ui/DomModifier.ts
- modules/tinymce/src/plugins/table/main/ts/ui/RowDialog.ts
- modules/tinymce/src/plugins/table/test/ts/browser/ui/TableCellDialogTest.ts
- modules/tinymce/src/plugins/table/test/ts/browser/ui/TableRowDialogTest.ts
Removing values from the dialogs would not remove them when multiple cells/rows were selected.
Pre-checks:
Review:
Fixes #7731
> TINY-8625: Can now reset multiple cells' height, or other values

- modules/tinymce/CHANGELOG.md
- modules/tinymce/package.json
- modules/tinymce/src/core/main/ts/html/Base64Uris.ts
- modules/tinymce/src/core/test/ts/atomic/html/Base64UrisTest.ts
Related Ticket: TINY-8646
Description:
- Updated the regex in `Base64Uris()` function as suggested in the ticket
**Note:** The bug seems to be fixed without updating `parseDataUri()` as suggested in the fix. I just leave it as is
Pre-checks:
Review:
Fixes #7737
> TINY-8646: Fix base64 encoded image not displayed following `data:` text

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/link/main/ts/core/Actions.ts
- modules/tinymce/src/plugins/link/test/ts/browser/PreventDefaultTest.ts
Related Ticket: TINY-8661
Stop links from opening using alt+enter (option+enter on Mac) when preventDefault is called
Pre-checks:
Review:
> TINY-8661: Stop links from opening when preventDefault is called

- modules/polaris/CHANGELOG.md
- modules/polaris/src/main/ts/ephox/polaris/api/Regexes.ts
- modules/polaris/src/test/ts/atomic/api/RegexesTest.ts
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/paste/SmartPaste.ts
- modules/tinymce/src/core/test/ts/browser/paste/SmartPasteTest.ts
- versions.txt
Related Ticket: TINY-8069
Updated the URL detection logic used by autolink and paste to ensure that path segments parse correctly when some uncommon characters are used, such as `!` and `:`. These are valid as per the URL parsing spec here: https://url.spec.whatwg.org/#url-path-segment-string
Pre-checks:
Review:
> TINY-8069: Fixed incorrect URL detection for path segments

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/dom/ControlSelection.ts
- modules/tinymce/src/plugins/fullscreen/main/ts/api/Events.ts
- modules/tinymce/src/plugins/fullscreen/test/ts/browser/FullScreenPluginTest.ts
This issue was detected as one where notifications are not appropriately moved when toggling fullscreen. I thought it might be better for the fullscreen plugin to fire the `resizeeditor`-event instead of making the notifications listen to the `fullscreenstatechanged` as it seemed more generic, since fullscreen does change the size of the editor.
Pre-checks:
Review:
> TINY-8701: Ensure fullscreen fires a ResizeEditor event

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/lists/main/ts/actions/ToggleList.ts
- modules/tinymce/src/plugins/lists/main/ts/core/Delete.ts
- modules/tinymce/src/plugins/lists/main/ts/core/Selection.ts
- modules/tinymce/src/plugins/lists/test/ts/browser/ApplyTest.ts
- modules/tinymce/src/plugins/lists/test/ts/browser/IndentTest.ts
- modules/tinymce/src/plugins/lists/test/ts/browser/OutdentTest.ts
- modules/tinymce/src/plugins/lists/test/ts/browser/RemoveTest.ts
This makes any element that can hold UL/LI/DL elements except for list elements the scope for list operations. Added more details in the ticket.
Pre-checks:
Review:
> TINY-8068: changed scope of list operations to closest list host element

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/html/Schema.ts
- modules/tinymce/src/core/test/ts/browser/content/InsertContentTest.ts
- modules/tinymce/src/core/test/ts/browser/dom/SerializerTest.ts
- modules/tinymce/src/core/test/ts/browser/html/SchemaTest.ts
Related Ticket: TINY-4784
As discussed on slack, we cannot be certain of the intention for custom elements so this updates the schema to treat them as "non-empty" so that the `isEmpty` checks will return false for custom elements. It's also quite common for custom elements/webcomponents to be empty, so this change reflects that.
Pre-checks:
Review:
> TINY-4784: Treat custom elements as always being non-empty by default

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/html/DomParser.ts
- modules/tinymce/src/core/main/ts/api/html/Schema.ts
- modules/tinymce/src/core/main/ts/fmt/ApplyFormat.ts
- modules/tinymce/src/core/main/ts/init/InitContentBody.ts
- modules/tinymce/src/core/test/ts/browser/fmt/FormatEmptyLineTest.ts
- modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts
- modules/tinymce/src/core/test/ts/browser/html/SchemaTest.ts
Related Ticket: TINY-8639
* Update the schema and DomParser so that text inline elements can be padded if they are a child of an empty block. As to whether text inline elements are padded by default is controlled by the `format_empty_lines` option
Coming up with setting and property names for the schema was tricky so am open to suggestions if we are not happy with what I have got currently
Pre-checks:
Review:
> TINY-8639: Retain formatted blank lines when `format_empty_lines` is true

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/SettingsTypes.ts
- modules/tinymce/src/core/main/ts/api/html/DomParser.ts
- modules/tinymce/src/core/main/ts/api/html/Schema.ts
- modules/tinymce/src/core/main/ts/fmt/ApplyFormat.ts
- modules/tinymce/src/core/main/ts/init/InitContentBody.ts
- modules/tinymce/src/core/test/ts/browser/fmt/FormatEmptyLineTest.ts
- modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts
- modules/tinymce/src/core/test/ts/browser/html/SchemaTest.ts
Related Ticket: TINY-8639
* Update the schema and DomParser so that text inline elements can be padded if they are a child of an empty block. As to whether text inline elements are padded by default is controlled by the `format_empty_lines` option
All of the files are largely the same except for InitContentBody.ts and DomParser.ts
Original PR: #7835
Pre-checks:
Review:
> TINY-8639: Retain formatted blank lines when `format_empty_lines` is true (backport)

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/template/main/ts/core/FilterContent.ts
- modules/tinymce/src/plugins/template/main/ts/core/Templates.ts
- modules/tinymce/src/plugins/template/main/ts/core/Utils.ts
- modules/tinymce/src/plugins/template/test/ts/browser/DatesTest.ts
- modules/tinymce/src/plugins/template/test/ts/browser/TemplateSanityTest.ts
Related Ticket: TINY-7433
Fixes some cases where values provided via options were used (that weren't escaped) when constructing a regular expression leading to them being interpreted as regex syntax. In the end I removed using regex entirely for one case as it wasn't a good use case for regex.
Pre-checks:
Review:
> TINY-7433: Fixed values not escaped in generated regular expressions for the template plugin

- modules/sugar/src/test/ts/browser/CssTest.ts
Related Ticket: TINY-8750
Chrome 102 added further MathML support so that those elements can be styled via the browser APIs. And that fails a test in `modules/sugar/src/test/ts/browser/CssTest.ts`. 
* Update the check to clobber to the expected CSS for Chrome 102
Pre-checks:
Review:
> TINY-8750: Fixed a failing test in CssTest on Chrome 102

- modules/snooker/CHANGELOG.md
- modules/snooker/src/main/ts/ephox/snooker/api/CopyCols.ts
- modules/snooker/src/main/ts/ephox/snooker/operate/MergingOperations.ts
- modules/snooker/src/test/ts/browser/CopyColumnsTest.ts
- modules/snooker/src/test/ts/browser/PasteColumnOperationsTest.ts
- modules/tinymce/CHANGELOG.md
This issue is only concerned with preventing the editor from creating illegal tables.
Pre-checks:
Review:
> TINY-8040: Copying and pasting columns will no longer generate illegal tables when interacting with colspan

- modules/alloy/CHANGELOG.md
- modules/alloy/src/main/ts/ephox/alloy/api/Main.ts
- modules/alloy/src/main/ts/ephox/alloy/api/ui/InlineView.ts
- modules/oxide/src/less/theme/components/form/autocomplete.less
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/Autocompleter.ts
- modules/tinymce/src/themes/silver/main/ts/autocomplete/AutocompleteEditorEvents.ts
- modules/tinymce/src/themes/silver/main/ts/ui/menus/menu/SingleMenu.ts
- modules/tinymce/src/themes/silver/test/ts/module/AutocompleterUtils.ts
* Fixes the `tox-autocompleter` sandbox being positioned instead of the menu (which in turn caused some issues with styling). The core issue is that we were using the wrong `InlineView` API as the one being used is meant to position the sandbox so that content can be swapped in and out (such as in context forms). 
* Reverted the CSS workaround done in https://github.com/tinymce/tinymce/pull/7704 due to this bug.
Pre-checks:
Review:
> TINY-6476: Fixed the autocompleter positioning the menu incorrectly

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/OptionTypes.ts
- modules/tinymce/src/core/main/ts/api/Options.ts
- modules/tinymce/src/core/main/ts/newline/InsertNewLine.ts
- modules/tinymce/src/core/test/ts/browser/newline/InsertNewLineTest.ts
Related Ticket: TINY-8458
* New option that can be used to adjust when to use block breaks vs line breaks.
Pre-checks:
Review:
discussion #7342
> TINY-8458: Add new `newline_behavior` option

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/autocomplete/AutocompleteLookup.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/autocomplete/AutocompleteTest.ts
Autocompleter would step out of block elements to check for previous text, causing it to not trigger in situations where a block element was nested in another, such as a nested list.
Pre-checks:
Review:
> TINY-8759: Autocompleter checks for block elements and not just for root

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/dom/Serializer.ts
- modules/tinymce/src/core/main/ts/api/html/DomParser.ts
- modules/tinymce/src/core/main/ts/dom/DomSerializerImpl.ts
- modules/tinymce/src/core/main/ts/html/FilterRegistry.ts
- modules/tinymce/src/core/test/ts/browser/dom/SerializerTest.ts
- modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts
Related Ticket: TINY-7847
* Added the new `removeNodeFilter` and `removeAttributeFilter` functions to the parser/serializer APIs.
* Abstracted the filter registry logic out into a separate module to avoid duplication between nodes/attributes.
* Fixed a couple of minor issues with the existing parser/serializer doc strings/examples.
Pre-checks:
Review:
> TINY-7847: Added new parser/serializer remove filter APIs

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/media/main/ts/api/Options.ts
- modules/tinymce/src/plugins/media/main/ts/core/DataToHtml.ts
- modules/tinymce/src/plugins/media/test/ts/browser/DataToHtmlTest.ts
- modules/tinymce/src/plugins/media/test/ts/browser/SubmitTest.ts
Related Ticket: TINY-8684
* Added iframeTemplateCallback and iframe_template_callback option
* Added tests for all template callback options in media plugin
Pre-checks:
Review:
Before merging:
> TINY-8684: Added iframe_template_callback option

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/commands/NewlineCommands.ts
- modules/tinymce/src/core/main/ts/newline/InsertBlock.ts
- modules/tinymce/src/core/main/ts/newline/InsertBr.ts
- modules/tinymce/src/core/main/ts/newline/InsertNewLine.ts
- modules/tinymce/src/core/test/ts/browser/api/commands/NewlineCommandsTest.ts
- modules/tinymce/src/core/test/ts/browser/newline/InsertBrTest.ts
Related Ticket: TINY-8458
- Corrected behaviour of InsertParagraph with `newline_behavior` set.
- Fix `InsertLineBreak` bug where it did not delete selection.
- This adds a little bit to our bundle size (the `InsertBreak` and `InsertBr` modules now generate an export object in the bundle where previously the functions were used directly) but it seems worth it.
Pre-checks:
Review:
> TINY-8458: Fix newline commands 

- modules/alloy/CHANGELOG.md
- modules/alloy/src/main/ts/ephox/alloy/dom/Reconcile.ts
- modules/alloy/src/test/ts/atomic/dom/ReconcileTest.ts
Related Ticket: TINY-8763
Pre-checks:
Review:
> TINY-8763: The value of togglable elements was not reset if not defined in the definition

- modules/agar/CHANGELOG.md
- modules/agar/src/main/ts/ephox/agar/api/RealMouse.ts
- modules/agar/src/test/ts/webdriver/RealMouseTest.ts
Related Ticket: TINY-8731
Add pClick helper to RealMouse in agar
Pre-checks:
Review:
> TINY-8731: Add pClick helper to RealMouse in agar

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/delete/CefDelete.ts
- modules/tinymce/src/core/main/ts/delete/DeleteUtils.ts
- modules/tinymce/src/core/main/ts/delete/TableDelete.ts
- modules/tinymce/src/core/test/ts/browser/delete/CefDeleteTest.ts
Related Ticket: TINY-8729
* Overrides default deletion when the selection contains cef at the start or the end of the document and explicitly removes selected content
Pre-checks:
Review:
> TINY-8729: Delete is broken when the selection contains CEF at the edge of the content

- modules/alloy/CHANGELOG.md
- modules/alloy/src/main/ts/ephox/alloy/behaviour/toggling/ToggleApis.ts
- modules/alloy/src/main/ts/ephox/alloy/behaviour/toggling/ToggleModes.ts
- modules/alloy/src/main/ts/ephox/alloy/behaviour/toggling/ToggleSchema.ts
- modules/alloy/src/main/ts/ephox/alloy/behaviour/toggling/TogglingTypes.ts
- modules/alloy/src/main/ts/ephox/alloy/menu/build/ItemType.ts
- modules/alloy/src/main/ts/ephox/alloy/menu/util/ItemEvents.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/single/MenuSpec.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/types/ItemTypes.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/types/MenuTypes.ts
- modules/alloy/src/test/ts/browser/behaviour/ToggleModesTest.ts
- modules/alloy/src/test/ts/browser/behaviour/TogglingAriaTest.ts
- modules/alloy/src/test/ts/browser/behaviour/TogglingClassTest.ts
- modules/alloy/src/test/ts/browser/ui/dropdown/DropdownListTest.ts
- modules/alloy/src/test/ts/browser/ui/dropdown/MenuRadioTest.ts
- modules/alloy/src/test/ts/browser/ui/dropdown/SplitDropdownTest.ts
- modules/alloy/src/test/ts/browser/ui/inline/InlineViewTest.ts
- modules/alloy/src/test/ts/browser/ui/typeahead/TypeaheadEscEnterBubbleTest.ts
- modules/alloy/src/test/ts/browser/ui/typeahead/TypeaheadNoBlurTest.ts
- modules/alloy/src/test/ts/browser/ui/typeahead/TypeaheadNoReopeningTest.ts
- modules/alloy/src/test/ts/browser/ui/typeahead/TypeaheadSelectsOverTest.ts
- modules/alloy/src/test/ts/browser/ui/typeahead/TypeaheadTest.ts
- modules/alloy/src/test/ts/module/ephox/alloy/test/dropdown/TestDropdownMenu.ts
- modules/alloy/src/test/ts/webdriver/spec/TypeaheadTriggerTest.ts
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/advlist/test/ts/browser/SplitButtonTest.ts
- modules/tinymce/src/plugins/insertdatetime/test/ts/browser/InsertDatetimeSanityTest.ts
- modules/tinymce/src/themes/silver/main/ts/ui/menus/item/build/ChoiceItem.ts
- modules/tinymce/src/themes/silver/main/ts/ui/menus/menu/MenuChoice.ts
- modules/tinymce/src/themes/silver/main/ts/ui/menus/menu/MenuUtils.ts
Related Ticket: TINY-8602
This fixes an accessibility issue whereby our choice menu items were using the `menuitemcheckbox` role when the options were exclusive. As part of this, to be able to tell when different menu items are toggled I've also added a `onToggled` callback to the Toggling configuration spec.
Pre-checks:
Review:
> TINY-8602: Ensure choice menu items use the "menuitemradio" aria role

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/EditorUpload.ts
- modules/tinymce/src/core/main/ts/api/UndoManager.ts
- modules/tinymce/src/core/main/ts/undo/Setup.ts
- modules/tinymce/src/core/main/ts/undo/UndoManagerTypes.ts
- modules/tinymce/src/core/test/ts/browser/EditorUploadTest.ts
- modules/tinymce/src/core/test/ts/browser/UndoManagerTest.ts
Related Ticket: TINY-8641
Add the `dispatchChange` function that triggers a change event with current editor status as level and current `undoManager` layer as `lastLevel` in the `undoManager` and the current content of the editor
Pre-checks:
Review:
> TINY-8641: Add the `dispatchChange` function to the `undoManager`

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/SelectionOverrides.ts
- modules/tinymce/src/core/main/ts/bookmark/GetBookmark.ts
- modules/tinymce/src/core/main/ts/selection/NormalizeRange.ts
- modules/tinymce/src/core/test/ts/browser/bookmark/BookmarksTest.ts
- modules/tinymce/src/core/test/ts/browser/selection/NormalizeRangeTest.ts
Related Ticket: TINY-7817
At the moment there is a [mechanism](https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/core/main/ts/selection/NormalizeRange.ts#L216) that normalizes caret and moves it left from the text node into the previous inline element text node if this previous inline node is a comment the caret is positioned over it and this can cause problems like trying to insert a tag into a comment
Pre-checks:
Review:
> TINY-7817: avoid moving the selection to a comment with the normalization

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/help/main/ts/ui/PluginsTab.ts
- modules/tinymce/src/plugins/help/main/ts/ui/VersionTab.ts
- modules/tinymce/src/plugins/link/main/ts/core/OpenUrl.ts
Related Ticket: TINY-8834
* Add `rel="noopener"` to a couple of `https://www.tiny.cloud` where it was missing
Pre-checks:
Review:
GitHub issues (if applicable): #7898
> TINY-8834: add rel="noopener" to changelog and pricing links

- modules/tinymce/CHANGELOG.md
…-stops throughout.
1081 full-stops added. 138 (or thereabouts) double-full stops removed.
Pre-checks:
Review:
> DOC-1742: copy-edit changelog.md so it has a consistent use of full-stops throughout

- .yarnrc
- yarn.lock
Related Ticket: TINY-8864
* Doesn't seem like major version changes so I think it can be a hotfix.
* This doesn't need to involve publishing a new version since it only impacts building from source.
* I removed the experimental flag in `.yarnrc` while trying to track this down, and it doesn't seem to make a difference anymore, so I decided to leave it out.
Pre-checks:
Review:
GitHub issues (if applicable): #7941
> TINY-8864: Upgrade transitive dependencies to avoid yarn workspace warning

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/link/main/ts/core/Actions.ts
- modules/tinymce/src/plugins/link/main/ts/core/Utils.ts
- modules/tinymce/src/plugins/link/main/ts/ui/Controls.ts
- modules/tinymce/src/plugins/link/main/ts/ui/Dialog.ts
- modules/tinymce/src/plugins/link/main/ts/ui/DialogInfo.ts
- modules/tinymce/src/plugins/link/test/ts/browser/SelectedImageFigureLinkTest.ts
Fix a bug where the link button would get highlighted when selecting a figure even though it doesn't contain a link
Pre-checks:
Review:
> TINY-8832: Figure class="image" incorrectly highlights link on the toolbar

- modules/tinymce/CHANGELOG.md
- modules/tinymce/package.json
- modules/tinymce/src/themes/silver/main/ts/modes/Iframe.ts
- modules/tinymce/src/themes/silver/main/ts/ui/sidebar/Sidebar.ts
- modules/tinymce/src/themes/silver/test/ts/browser/sidebar/SidebarShowOptionTest.ts
Related Ticket: TINY-8873
* Make sure the associated toolbar toggle button is highlighted if the sidebar is opened using the `sidebar_show` option
* The associated toolbar toggle button listens to the `ToggleSidebar` event [here ](https://github.com/tinymce/tinymce/blob/c3b6572e2d5a42f6b4a17bfe4d565bea3f5c85a0/modules/tinymce/src/themes/silver/main/ts/ui/sidebar/Sidebar.ts#L34) so utilising this for the change
Pre-checks:
Review:
> TINY-8873: Fix sidebar toggle button active state when using `sidebar_show` option

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/ForceBlocks.ts
- modules/tinymce/src/core/main/ts/caret/CaretContainer.ts
- modules/tinymce/src/core/main/ts/delete/DeleteUtils.ts
- modules/tinymce/src/core/main/ts/dom/PaddingBr.ts
- modules/tinymce/src/core/main/ts/keyboard/ContentEndpointNavigation.ts
- modules/tinymce/src/core/main/ts/keyboard/TableNavigation.ts
- modules/tinymce/src/core/test/ts/browser/delete/CefDeleteTest.ts
Related Ticket: TINY-8873
* Fixed a regression caused by https://github.com/tinymce/tinymce/pull/7892. The problem is that in `DeleteUtils.ts` the `getParent` call can return `null` and will if the node passed in is the root/body node. So this corrects that logic and also makes the delete logic properly handle padding an empty editor by inserting the root block.
* Note: This exception actually isn't thrown in `develop` because the strict types made me do a similar fix (though it didn't handle padding the root/body properly). So +1 for strict types I guess?
* I also cleaned up some duplication for other cases where I found we were inserting the root block in the delete/navigation logic, so we now hopefully only have the one bit of code for generating that. …
> TINY-8877: Fixed a regression that caused an exception to be thrown when deleting all content

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/OptionTypes.ts
- modules/tinymce/src/core/main/ts/api/Options.ts
- modules/tinymce/src/core/main/ts/textpatterns/core/BlockPattern.ts
- modules/tinymce/src/core/main/ts/textpatterns/core/InlinePattern.ts
- modules/tinymce/src/core/main/ts/textpatterns/core/Pattern.ts
- modules/tinymce/src/core/main/ts/textpatterns/core/PatternTypes.ts
- modules/tinymce/src/core/main/ts/textpatterns/keyboard/KeyHandler.ts
- modules/tinymce/src/core/main/ts/textpatterns/keyboard/Keyboard.ts
- modules/tinymce/src/core/test/ts/atomic/textpatterns/FindBlockPatternsTest.ts
- modules/tinymce/src/core/test/ts/browser/textpatterns/FindBlockPatternTest.ts
- modules/tinymce/src/core/test/ts/browser/textpatterns/FindBlockPatternsTest.ts
- modules/tinymce/src/core/test/ts/browser/textpatterns/FindInlinePatternTest.ts
- modules/tinymce/src/core/test/ts/browser/textpatterns/ReplacementTest.ts
- modules/tinymce/src/core/test/ts/module/test/TextPatternsUtils.ts
Related Ticket: TINY-8778: 
* Added new option `text_patterns_lookup` which allows prepending additional patterns on the fly. The patterns take precedence over `text_patterns` during the matching process
Pre-checks:
Review:
> TINY-8778: New `text_patterns_lookup` option

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/autolink/main/ts/core/Keys.ts
- modules/tinymce/src/plugins/autolink/test/ts/browser/AutoLinkPluginTest.ts
- modules/tinymce/src/plugins/autolink/test/ts/module/test/KeyUtils.ts
Related Ticket: TINY-8896
* Fixes the `createlink` `ExecCommand` event no longer firing that was being relied on elsewhere.
* Fixes that an undo level was no longer created because we weren't calling `editor.execCommand` anymore.
* Fixes issues with the undo level restoring the selection in an unexpected place or the undo stack having an unexpected order (this was an issue in 5.x as well). This involved reworking the bracket logic to use `keyup` and overriding the enter logic (similar to how textpattern works) to make sure the events happened in the correct order.
* Note: As discussed with @TheSpyder, hopefully after 6.2 we could even look at making this build on top of the text pattern logic instead.
* Fixed the fake test typing logic to ensure it fired with the …
> TINY-8896: Fixed a regression in the autolink conversion logic

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/html/DomParser.ts
- modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts
Related Ticket: TINY-8780
Fixes a regression introduced in TinyMCE 6.0 where part of the old SaxParser logic wasn't converted over meaning special elements weren't quite sanitized/cleaned up correctly. The part that was missed was here: https://github.com/tinymce/tinymce/blob/release/5.10/modules/tinymce/src/core/main/ts/api/html/SaxParser.ts#L568-L574. In this you can see it used to drop/not emit the child content for special elements when it wasn't valid, however the new DomParser implementation only ever unwrapped them.
Pre-checks:
Review:
> TINY-8780: Fixed a regression in how special elements were sanitized while parsing

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/OptionTypes.ts
- modules/tinymce/src/core/main/ts/api/Options.ts
- modules/tinymce/src/core/main/ts/fmt/ApplyFormat.ts
- modules/tinymce/src/core/main/ts/fmt/FormatUtils.ts
- modules/tinymce/src/core/main/ts/fmt/MergeFormats.ts
- modules/tinymce/src/core/main/ts/fmt/MergeUtils.ts
- modules/tinymce/src/core/main/ts/fmt/RemoveFormat.ts
- modules/tinymce/src/core/test/ts/browser/fmt/FormatNoneditableTest.ts
- modules/tinymce/src/plugins/image/test/ts/browser/core/ImageAlignTest.ts
Related Ticket: TINY-8905
* Allow a non-editable element to be wrapped if it is specifically marked as wrappable and also does not have any editable descendants
* Currently the marker is a `data-mce-cef-wrappable` data attribute. I am open to suggestions if there is a better way to indicate wrappable elements whether that be an option or something else
* Refactor some of the `if` blocks in ApplyFormat.ts to hopefully make them easier to reason about
* Make sure styling on a non-editable element or on a child of a non-editable element is not eagerly removed so that the non-editable behaviour is respected	 
Pre-checks:
Review:
> TINY-8905: Allow formatter to be able to wrap noneditable elements

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/init/InitContentBody.ts
- modules/tinymce/src/core/test/ts/browser/init/InitIframeEditorCookiesTest.ts
Related Ticket: TINY-8916
This changes how the initial iframe content is loaded only on Firefox to fallback to the older browser APIs we used in TinyMCE 5 due to https://bugzilla.mozilla.org/show_bug.cgi?id=1741489.
Pre-checks:
Review:
Fixes #7746
> TINY-8916: Worked around a Firefox bug whereby cookies weren't available inside the editor content

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/content/InsertContentImpl.ts
- modules/tinymce/src/core/test/ts/browser/content/InsertContentTest.ts
Related Ticket: TINY-8860
* Fixed pasting codesample onto any `pre` content removing class attribute
* Fixed pasting any `pre` content into styled `pre` content not merging correctly
Pre-checks:
Review:
> TINY-8860: Correctly merge pre content from paste

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/codesample/main/ts/core/FilterContent.ts
- modules/tinymce/src/plugins/codesample/test/ts/browser/CodeSampleSanityTest.ts
- modules/tinymce/src/plugins/codesample/test/ts/webdriver/CodeSampleCopyAndPasteTest.ts
Related Ticket: TINY-8861
* Ensure contenteditable state is set before inserting pasted `codesample` snippets
* Make better use of the `data-mce-highlighted` attribute flag rather than simply `contenteditable=false`
* See further discussion in #7996
Pre-checks:
Review:
> TINY-8861: fix cursor position after pasting a `codesample` snippet

- modules/tinymce/CHANGELOG.md
*Unreleased* section is now *6.1.1 - 2022-07-27* section.
5 change notes copy-edited (TINY-8780, TINY-8877, TINY-8873, TINY-8896, TINY-8916) in this section.
2. change notes added (TINY-8860, TINY-8861) to this section.
Pre-checks:
Review:
> DOC-1769: copy edits and additions to 6.1.1 section of CHANGELOG.md

- modules/tinymce/src/core/main/ts/textpatterns/core/BlockPattern.ts
- modules/tinymce/src/core/main/ts/textpatterns/core/InlinePattern.ts
- modules/tinymce/src/core/main/ts/textpatterns/core/PatternTypes.ts
- modules/tinymce/src/core/main/ts/textpatterns/keyboard/KeyHandler.ts
- modules/tinymce/src/core/main/ts/textpatterns/keyboard/Keyboard.ts
- modules/tinymce/src/core/main/ts/textpatterns/utils/Utils.ts
- modules/tinymce/src/core/test/ts/browser/textpatterns/FindBlockPatternsTest.ts
- modules/tinymce/src/core/test/ts/browser/textpatterns/FindInlinePatternTest.ts
- modules/tinymce/src/core/test/ts/browser/textpatterns/ReplacementTest.ts
- modules/tinymce/src/core/test/ts/browser/textpatterns/TextPatternsLookupTest.ts
- modules/tinymce/src/core/test/ts/module/test/TextPatternsUtils.ts
Related Ticket: TINY-8778
* This PR address the issue,  which was found in the QA of TINY-8778,  that `text_patterns_lookup` was called more than expected (> 1 time) when matching a pattern on pressing enter or space key.
* Also reduced the number of sorting patterns
@TheSpyder, this might also address TINY-8904
Pre-checks:
Review:
> TINY-8778: Fixed `text_patterns_lookup` being called more than expected when matching patterns

- modules/tinymce/CHANGELOG.md
- modules/tinymce/package.json
- modules/tinymce/src/plugins/autolink/main/ts/core/Keys.ts
- modules/tinymce/src/plugins/autolink/test/ts/browser/AutoLinkPluginTest.ts
Related Ticket: TINY-8936
Reverts the undo level fixes so this works the same as it did in 5.x and we'll re-evaluate and provide a better fix for 6.2.
Pre-checks:
Review:
> TINY-8936: Reverted the undo level part of the fixes done for f5c2ce9

- modules/tinymce/CHANGELOG.md
- modules/tinymce/package.json
- modules/tinymce/src/core/main/ts/api/html/SaxParser.ts
- modules/tinymce/src/core/test/ts/browser/html/SaxParserTest.ts
Related Ticket: TINY-8773
* Regression introduced in clobbering check #TINY-7756
* Filter through new document for each attribute, rather than same document
* SaxParser method now works same as in 6.
Pre-checks:
Review:
> TINY-8773: Prevent stripping of "name" and "id" attributes on iframe and img elements

- modules/sugar/src/test/ts/browser/CssTest.ts
Related Ticket: TINY-8750
* Backports https://github.com/tinymce/tinymce/pull/7857 due to a failing test in CssTest on Chrome 102
Pre-checks:
Review:
> TINY-8750: Backport fix to a failing test in CssTest on Chrome 102

- modules/agar/src/test/ts/webdriver/RealEffectsTest.ts
- modules/tinymce/src/core/test/ts/webdriver/paste/CopyAndPasteTest.ts
- modules/tinymce/src/plugins/nonbreaking/test/ts/webdriver/NonbreakingVisualCharsTypingTest.ts
- package.json
- yarn.lock
Related Ticket: TINY-8944
- Upgrades to the latest bedrock version, plus a couple other dev deps
- Re-enables the skipped tests due to the Safari RealKeys issue
- Fixes some issues in the VisualChars test where the selector was invalid
Pre-checks:
Review:
> TINY-8944: Upgrade bedrock plus other dev deps and re-enable skipped tests

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/link/main/ts/core/Actions.ts
- modules/tinymce/src/plugins/link/main/ts/core/Utils.ts
- modules/tinymce/src/plugins/link/main/ts/ui/Controls.ts
- modules/tinymce/src/plugins/link/test/ts/browser/ContextToolbarTest.ts
Related Ticket: TINY-8940
* Fix a regression introduced in TINY-8832 where clicking in the editor would always show the link context toolbar when the option `link_context_toolbar` is set to true
Pre-checks:
Review:
> TINY-8940: Investigate and fix getAnchorElement changes

- modules/snooker/CHANGELOG.md
- modules/snooker/src/main/ts/ephox/snooker/api/TableFill.ts
- modules/tinymce/.eslintrc.json
- modules/tinymce/src/models/dom/demo/ts/demo/Demo.ts
- modules/tinymce/src/models/dom/main/ts/Model.ts
- modules/tinymce/src/models/dom/main/ts/table/actions/Clipboard.ts
- modules/tinymce/src/models/dom/main/ts/table/actions/InsertTable.ts
- modules/tinymce/src/models/dom/main/ts/table/actions/TableActions.ts
- modules/tinymce/src/models/dom/main/ts/table/api/Events.ts
- modules/tinymce/src/models/dom/main/ts/table/api/Options.ts
- modules/tinymce/src/models/dom/main/ts/table/api/TableCellSelectionHandler.ts
- modules/tinymce/src/models/dom/main/ts/table/api/TableResizeHandler.ts
- modules/tinymce/src/models/dom/test/ts/browser/table/DragResizeTest.ts
- modules/tinymce/src/models/dom/test/ts/browser/table/InsertRowTableResizeTest.ts
- modules/tinymce/src/models/dom/test/ts/browser/table/ResizeTableTest.ts
- modules/tinymce/src/models/dom/test/ts/browser/table/TableSectionApiTest.ts
- modules/tinymce/src/models/dom/test/ts/browser/table/TwoCellsSelectionTest.ts
- modules/tinymce/src/models/dom/test/ts/browser/table/command/MergeCellCommandTest.ts
- modules/tinymce/src/models/dom/test/ts/module/table/TableSizingModeCommandUtil.ts
- modules/tinymce/src/models/dom/test/ts/module/table/TableTestUtils.ts
- modules/tinymce/tsconfig.strict.json
Related Ticket: TINY-8921
This PR is a lot smaller than that last thankfully and aims at fixing all the strict type errors in the DOM model. Note that I've not included the `tests` directory in the `tsconfig.strict.json` file because they include silver and some plugins which won't compile yet.
Pre-checks:
Review:
> TINY-8921: Fixed strict type errors in the model

- modules/bridge/src/demo/ts/dialogs/DemoDialogHelpers.ts
- modules/bridge/src/demo/ts/menus/ContextMenuDemo.ts
- modules/bridge/src/demo/ts/plugins/AnchorItems.ts
- modules/bridge/src/demo/ts/plugins/AutosaveItems.ts
- modules/bridge/src/demo/ts/plugins/DirectionalityItems.ts
- modules/bridge/src/demo/ts/plugins/FullscreenItems.ts
- modules/bridge/src/demo/ts/plugins/ImageItems.ts
- modules/bridge/src/demo/ts/plugins/MediaItems.ts
- modules/bridge/src/demo/ts/plugins/PasteItems.ts
- modules/bridge/src/demo/ts/plugins/SaveItems.ts
- modules/bridge/src/demo/ts/plugins/TODO_AdvListItems.ts
- modules/bridge/src/demo/ts/plugins/TocItems.ts
- modules/bridge/src/demo/ts/plugins/VisualBlocksItems.ts
- modules/bridge/src/demo/ts/plugins/VisualCharsItems.ts
- modules/bridge/src/main/ts/ephox/bridge/api/DialogManager.ts
- modules/bridge/src/main/ts/ephox/bridge/api/Registry.ts
- modules/bridge/src/main/ts/ephox/bridge/core/DataProcessors.ts
- modules/bridge/tsconfig.json
- modules/sand/src/demo/ts/ephox/sand/demo/Demo.ts
- modules/sand/src/main/ts/ephox/sand/api/SandHTMLElement.ts
- modules/sand/src/main/ts/ephox/sand/detect/DeviceType.ts
- modules/sand/src/test/ts/browser/HtmlElementTest.ts
- modules/sand/tsconfig.json
Related Ticket: TINY-8808
One more strict types PR sorry all, though it is small... I realised that this should also be done since it's part of the TinyMCE public API and also used heavily in Silver so it'd defeat the purpose a little by not having it compile under strict mode.
Pre-checks:
Review:
> TINY-8808: Fixed strict type errors in Sand and Bridge

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/html/FilterNode.ts
- modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts
Related Ticket: TINY-8888
* The logic that calls filters did not expect that filters could remove things that a later filter was matched on.
* The logged issue happened when a node filter removed the `src` attribute from an `iframe`, our internal `src` attribute filter [received an unexpected `undefined` and triggered an exception](https://github.com/tinymce/tinymce/blob/ece3bf774b9ae20910d073af5351f162c4fb52d5/modules/tinymce/src/core/main/ts/dom/DomSerializerFilters.ts#L40).
* The fix is to check the filter still matches the node array before _every_ filter callback is executed.
* To keep the performance impact to a minimum, this uses careful mutation of the node array rather than copying the contents. Our expectation is that the case where a filter no longer …
> TINY-8888: Check parser filter matching in between calling each filter

- modules/tinymce/src/core/main/ts/api/EditorManager.ts
- modules/tinymce/tools/docs/tinymce.EditorManager.js
- modules/tinymce/tools/docs/tinymce.js
Related Ticket: TINY-8591
* Uncommented the `@class` reference to generate a page for `EditorManager`
* Did this with a new page, instead of in `EditorManager.ts`, otherwise all of the references it adds are deleted from the `tinymce` root page.
Take a look at the branch on staging and see what we think:
http://docs-feature-62-tiny-8591.staging.tiny.cloud/docs/tinymce/6/apis/tinymce.editormanager/
The generated code isn’t great, this text is also used for the description so it ends up with `&#x60;` literals in the description. I've made a branch with the files checked in:
https://github.com/tinymce/tinymce-docs/compare/feature/6.2/TINY-8591
But I couldn’t figure out another way to do it with the way our moxiedoc/asciidoc code generation works.
Pre-checks:
Review: …
> TINY-8591: Add EditorManager page to documentation

- modules/alloy/CHANGELOG.md
- modules/alloy/src/main/ts/ephox/alloy/api/testhelpers/GuiSetup.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/types/TypeaheadTypes.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/UrlInput.ts
- modules/tinymce/src/themes/silver/test/ts/headless/components/urlinput/UrlInputTest.ts
- versions.txt
Related Ticket: TINY-8997
This fixes a regression I accidentally introduced when doing the strict types due to the alloy types being incorrect for the `TypeaheadSpec`. As part of this, I also had to add a way to specify a custom gui for the alloy `TestHelpers` because the URL input was never working properly because the `input` element and menu were in different GUI motherships. This then meant that all the logic in https://github.com/tinymce/tinymce/blob/16676bc48409eb440ad1e2bb3021d62c24d975fa/modules/alloy/src/main/ts/ephox/alloy/ui/schema/TypeaheadSchema.ts was never running since the `getByUid` would always return a `Result.error`.
Pre-checks:
Review:
> TINY-8997: Fixed urlinput components updating the value when highlighting dropdown values

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/UrlInput.ts
- modules/tinymce/src/themes/silver/test/ts/webdriver/components/urlinput/UrlInputTest.ts
UrlInput would not remove spaces on its own, and it would need to be triggered from the outside. This makes the spaces always be removed.
Pre-checks:
Review:
> TINY-8775: Reduce spaces in urlinput when they should not be there

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/dom/NodeType.ts
- modules/tinymce/src/core/main/ts/fmt/ApplyFormat.ts
- modules/tinymce/src/core/main/ts/fmt/ListItemFormat.ts
- modules/tinymce/src/core/main/ts/fmt/RemoveFormat.ts
- modules/tinymce/src/core/test/ts/browser/fmt/FormatEmptyLineTest.ts
- modules/tinymce/src/core/test/ts/browser/fmt/ListItemFormatTest.ts
* Formats that have style properties that are possible to apply to list bullets/numbers are now expanded to that list number.
Pre-checks:
Review:
> TINY-8961: added expand formats to li behaviour

- modules/oxide/src/less/skins/ui/tinymce-5/skin.less
- modules/oxide/src/less/theme/components/toolbar/toolbar.less
- modules/tinymce/CHANGELOG.md
Related Ticket: TINY-8980
* Removed extra padding for floating Toolbar in tinymce-5 skin
Pre-checks:
Review:
> TINY-8980: fix toolbar padding in tinymce-5 skin

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/help/main/ts/data/PluginUrls.ts
- modules/tinymce/src/plugins/help/main/ts/ui/PluginsTab.ts
- modules/tinymce/src/plugins/help/test/ts/browser/MetadataTest.ts
- modules/tinymce/src/plugins/help/test/ts/browser/PluginTabsOrderTest.ts
- modules/tinymce/src/plugins/help/test/ts/module/Selectors.ts
Related Ticket: TINY-8988 and TINY-9019
* added mergetags and footnotes to the available plugin lists
* sorted the available and installed plugin lists that are displayed
Pre-checks:
Review:
> TINY-8988: Adding Merge Tags and Footnotes to the Plugin Lists

- modules/oxide/src/less/theme/content-ui.less
- modules/oxide/src/less/theme/content/footnotes/footnotes.less
- modules/tinymce/CHANGELOG.md
Related Ticket: TINY-8966
* Added CSS to affect visuals of `mce-footnote` and `mce-footnotes` elements.
Pre-checks:
Review:
> TINY-8966: Include CSS for Footnotes plugin

- modules/tinymce/src/core/main/ts/api/textpatterns/TextPatterns.ts
- modules/tinymce/src/core/main/ts/textpatterns/core/PatternTypes.ts
- modules/tinymce/src/core/test/ts/browser/textpatterns/TextPatternsPublicApiTest.ts
Related Ticket: TINY-9053
* exposed more types through TextPatterns in PublicApi
* created a test that uses just PublicApi to check that managing text pattern lookups are more managable
Questions
- does this need documentation changes? 
- is there a precedent for how verbose our changelog entry is for this? Does it need to list every type exposed? 
Pre-checks:
Review:
> TINY-9053: Exposing more types of TextPatterns 

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/fmt/DefaultFormats.ts
- modules/tinymce/src/core/test/ts/browser/fmt/FormatNoneditableTest.ts
- modules/tinymce/src/plugins/media/test/ts/browser/MediaAlignmentTest.ts
Related Ticket: TINY-8687
* Adds two new alignment formats for media plugin wrapping elements and for ephox embeded elements (enhanced media plugin)
* Tested a few variants of this one was using classes instead like the figure element another one was trying to have the display be `block` in import/exporting but `table` internally both became messy. So this is the simplest solution and the customer can override this alignment if they want to in one spot with the `formats` config option.
* The case where you select an inline editable element seems to work with other changes we made recently to cef so I just added an extra test for that
Pre-checks:
Review:
> TINY-8687: added support for aligning media plugin and ephox embed elements

- modules/tinymce/src/core/main/ts/fmt/ListItemFormat.ts
- modules/tinymce/src/core/test/ts/browser/fmt/ListItemFormatTest.ts
* Fixes a case that happens on Firefox found by QA
Pre-checks:
Review:
> TINY-9089: added fix for trailing br element

- modules/oxide/src/less/theme/content-ui.less
- modules/oxide/src/less/theme/content/mergetags/mergetag.less
Related Ticket: TINY-9023
* Added new mergetags ui css to visualize the merge tags while editing
Pre-checks:
Review:
> TINY-9023: added oxide content ui css for mergetags

- modules/tinymce/src/themes/silver/main/ts/ui/menus/menu/searchable/SearchableMenuField.ts
- modules/tinymce/src/themes/silver/test/ts/headless/toolbar/SearchableMenuButtonPlaceholderTest.ts
- modules/tinymce/src/themes/silver/test/ts/headless/toolbar/SearchableMenuButtonTest.ts
- modules/tinymce/src/themes/silver/test/ts/module/CommonMenuTestStructures.ts
- modules/tinymce/src/themes/silver/test/ts/webdriver/toolbar/SearchableMenuTypingTest.ts
Related Ticket: TINY-8952 (follow-up that was missed initially)
* placeholder text for search menu field is now translated.
Pre-checks:
* [N/A] Changelog entry added
Review:
> TINY-8952: Translating the placeholder text for SearchMenuField

- modules/tinymce/src/core/main/ts/newline/InsertBlock.ts
- modules/tinymce/src/core/main/ts/newline/NewLineAction.ts
- modules/tinymce/src/core/main/ts/newline/NewLineUtils.ts
- modules/tinymce/src/core/test/ts/browser/keyboard/EnterKeyCeFalseTest.ts
- modules/tinymce/src/core/test/ts/browser/newline/InsertNewLineTest.ts
- modules/tinymce/src/plugins/table/test/ts/browser/settings/TableGridFalseTest.ts
Related Ticket: TINY-9098
Fixes a regression introduced in 6.2 development when I was doing the strict types as the new line logic relies on `getEditableRoot` returning a nullable value. So this swaps that back and adds other checks/fallbacks where required to handle that.
Pre-checks:
Review:
> TINY-9098: Fixed a regression that caused enter to work within noneditable elements

- modules/tinymce/src/core/main/ts/fmt/ApplyFormat.ts
- modules/tinymce/src/core/main/ts/fmt/FormatUtils.ts
- modules/tinymce/src/core/main/ts/fmt/RemoveFormat.ts
- modules/tinymce/src/core/test/ts/browser/fmt/FormatChangeSelectionTest.ts
- modules/tinymce/src/core/test/ts/browser/fmt/FormatNoneditableTest.ts
Related Ticket: TINY-8935
* Fixes a regression that was caused when adding support for wrapping noneditable elements. After either applying or removing a format, the selection is kept on the noneditable element if it was already selected. Additionally, there is some extra checks to prevent placing the cursor inside a noneditable element.
Pre-checks:
Review:
> TINY-8935: Fix formatter placing cursor inside a noneditable node

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/delete/DeleteCommands.ts
- modules/tinymce/src/core/main/ts/delete/DeleteUtils.ts
- modules/tinymce/src/core/main/ts/delete/InlineBoundaryDelete.ts
- modules/tinymce/src/core/main/ts/newline/InsertNewLine.ts
- modules/tinymce/src/core/main/ts/newline/NewLineAction.ts
- modules/tinymce/src/core/test/ts/browser/keyboard/EnterKeyCeFalseTest.ts
- modules/tinymce/src/plugins/codesample/test/ts/webdriver/CodeSampleCopyAndPasteTest.ts
Related Ticket: TINY-9101
* spilt execDeleteCommand into two: native and editor. Only editor will consider deletion overrides, and only newlines uses the editor variant.
* rewrote CodeSample test for pasting pre tags
Pre-checks:
Review:
> TINY-9101: Allowing inserting newline based deletions to use deletion overrides

- modules/oxide/src/less/theme/components/menubar/promotion.less
Related Ticket: TINY-9106
* Fix promotion button height and center it’s content regardless of content’s height
* Moved `cursor: pointer` property from promotion wrapper to button itself
Pre-checks:
Review:
> TINY-9106: Fix promotion button height difference between hidpi and regular screens

- modules/oxide/src/less/theme/content/mergetags/mergetag.less
Related Ticket: TINY-9141
* Change merge tag background colors based on `content-ui-darkmode` less variable
Pre-checks:
Review:
> TINY-9141: Decrease background opacity for merge tags in dark UI

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/content/ContentTypes.ts
- modules/tinymce/src/core/main/ts/content/InsertContent.ts
- modules/tinymce/src/core/test/ts/browser/content/EditorContentTest.ts
Related Ticket: TINY-9140
* Fix `editor.insertContent` not respecting `no_events` . All other set/get content calls look to respect the event so this just makes them consistent.
Pre-checks:
Review:
> TINY-9140: Fix `editor.insertContent` API not respecting the `no_events` arg

- modules/tinymce/src/core/main/ts/fmt/ApplyFormat.ts
- modules/tinymce/src/core/main/ts/fmt/FormatUtils.ts
- modules/tinymce/src/core/test/ts/browser/fmt/FormatNoneditableTest.ts
Related Ticket: TINY-9111
* It was found during QA that when a noneditable element was directly selected and had editable children, applying a format would format the editable children. Whilst this may have been fine, there was then no way to toggle the format off again when the nonediatble element was directly selected. Because of this, part of the code deleted from #7968 has been put back so that the 6-stable behaviour is maintained.
It might be better if the editable children of the noneditable element could be formatted even if the noneditable element was selected so that it is consistent with how a ranged selection works. Although, this would require various changes to MatchFormat and RemoveFormat so is best left for another ticket if we wanted to do it. …
> TINY-9111: Revert changes for how selected nested noneditable element is formatted

- SECURITY.md
- modules/acid/package.json
- modules/agar/CHANGELOG.md
- modules/agar/package.json
- modules/alloy/CHANGELOG.md
- modules/alloy/package.json
- modules/boss/package.json
- modules/boulder/CHANGELOG.md
- modules/boulder/package.json
- modules/bridge/CHANGELOG.md
- modules/bridge/package.json
- modules/darwin/package.json
- modules/dragster/package.json
- modules/jax/package.json
- modules/katamari-assertions/package.json
- modules/katamari/CHANGELOG.md
- modules/katamari/package.json
- modules/mcagar/CHANGELOG.md
- modules/mcagar/package.json
- modules/oxide-icons-default/package.json
- modules/oxide/package.json
- modules/phoenix/package.json
- modules/polaris/package.json
- modules/porkbun/package.json
- modules/robin/package.json
- modules/sand/package.json
- modules/snooker/package.json
- modules/sugar/CHANGELOG.md
- modules/sugar/package.json
- versions.txt
Related Ticket: TINY-8787
* Added changelog dates for monorepo libraries being released per `versions.txt`
* Bump monorepo libraries to their respective versions and cleaned `versions.txt`.
* Update SECURITY.md
Note: The TinyMCE changelog/package.json was already up to date due to previous PRs.
Monorepo version changes:
```
Changes:
- @ephox/acid: 5.0.3 => 5.0.4
- @ephox/agar: 7.1.1 => 7.2.0
- @ephox/alloy: 10.1.1 => 11.0.0
- @ephox/boss: 6.0.3 => 6.0.4
- @ephox/boulder: 7.0.3 => 7.1.0
- @ephox/bridge: 4.0.4 => 4.1.0
- @ephox/darwin: 8.0.4 => 8.0.5
- @ephox/dragster: 7.0.3 => 7.0.4
- @ephox/jax: 7.0.3 => 7.0.4
- @ephox/katamari-assertions: 4.0.3 => 4.0.4
- @ephox/katamari: 9.0.3 => 9.1.0
- @ephox/mcagar: 8.0.3 => 8.1.0
- @tinymce/oxide-icons-default: 2.0.3 => 2.1.0 …
```
> TINY-8787: Prepare for TinyMCE 6.2.0 release

- modules/oxide/src/less/theme/components/toolbar/toolbar.less
- modules/tinymce/CHANGELOG.md
Related Ticket: TINY-8948
* Specified `background-attachment: local` for toolbar so that separator lines would scroll with it’s contents
Pre-checks:
Review:
> TINY-8948: fix scrolling of separator lines in multiline toolbars

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/dom/ControlSelection.ts
- modules/tinymce/src/plugins/fullscreen/main/ts/api/Events.ts
- modules/tinymce/src/plugins/fullscreen/test/ts/browser/FullScreenPluginTest.ts
- modules/tinymce/src/plugins/table/test/ts/browser/settings/TableGridFalseTest.ts
Related Ticket: TINY-8978
* Backport fix for notifications in fullscreen
* New `ResizeEditor` Event
* Backport fix for `TableGridFalseTest`
Pre-checks:
Review:
> TINY-8978: Backport fix for notifications in fullscreen

- modules/oxide/src/less/skins/ui/tinymce-5/skin.less
- modules/tinymce/CHANGELOG.md
Related Ticket: TINY-9108
* Reverted overflow value for inline mode editor in `tinymce-5` skin
Pre-checks:
Review:
> TINY-9108: Fix double bottom border on inline mode editor in `tinymce-5` skin

- modules/polaris/CHANGELOG.md
- modules/polaris/src/main/ts/ephox/polaris/api/Regexes.ts
- modules/polaris/src/test/ts/atomic/api/RegexesTest.ts
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/paste/main/ts/core/SmartPaste.ts
- modules/tinymce/src/plugins/paste/test/ts/browser/SmartPasteTest.ts
- versions.txt
Related Ticket: TINY-8979
- Backport URL link detection fix
- Note: Replacement PR for https://github.com/tinymce/tinymce/pull/8122 (wrong email 😢 )
Pre-checks:
Review:
> TINY-8979: Backport URL link detection fix

- modules/snooker/src/test/ts/browser/ResizeTest.ts
- modules/snooker/src/test/ts/browser/TableSizeTest.ts
- modules/sugar/src/test/ts/browser/LocationTest.ts
- modules/sugar/src/test/ts/browser/ScrollTest.ts
- modules/tinymce/src/core/test/ts/browser/annotate/AnnotationStylingTest.ts
- modules/tinymce/src/models/dom/test/ts/module/table/TableTestUtils.ts
Related Ticket: TINY-9200
Tests started to fail since Firefox was updated to a newer version
* Changed the `ResizeTest.ts` and `TableSizeTest.ts` for snooker to have an inline block with exact pixels to expand the TD rather than just text that could cause issues with kerning, oses etc the intent of the test is still the same.
* Added a fix for Firefox scrollbars. By default Firefox 100+ on Linux has no scrollbars visible. Makes local testing a bit easier.
* Removed `source` from the children elements for the `AnnotationStylingTest.ts` test since it now return an empty string instead of a proper rgb value. It is a hidden element so it kind of makes sense to return nothing.
* Increased the fuzzy asserts from 2 to 4 to compensate for rendering changes in latest …
> TINY-9200: Fix broken tests on Firefox

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/DragDropOverrides.ts
- modules/tinymce/src/core/test/ts/browser/DragDropOverridesTest.ts
Related Ticket: TINY-9025
*  Dragging CEF element toward the bottom edge no longer causes the page to scroll up
Pre-checks:
Review:
> TINY-9025: Dragging CEF element toward the bottom edge no longer causes the page to scroll up

- modules/agar/CHANGELOG.md
- modules/agar/src/main/ts/ephox/agar/api/ApproxStructure.ts
- modules/agar/src/main/ts/ephox/agar/assertions/ApproxStructures.ts
- modules/agar/src/test/ts/browser/ApproxStructureTest.ts
Related Ticket: TINY-9102
* Added `elementWithSpecifics` to `structApi` (`ApproxStructure`) for strict comparison of styles, attributes and classes
Pre-checks:
Review:
> TINY-9102: Added exactAttrs, exactClasses and exactStyles to ApproxStructures.element

- package.json
- yarn.lock
Related Ticket: TINY-8886
* Small version bump to include security patches
* We don't actually use the vulnerable code, but there's no harm in upgrading (primjs is [in maintenance mode](https://github.com/PrismJS/prism/blob/59e5a3471377057de1f401ba38337aca27b80e03/README.md?plain=1#L18-L20) until v2 is released)
Pre-checks:
Review:
> TINY-8886: Update prismjs

- modules/oxide/src/less/theme/components/toolbar/toolbar.less
Related Ticket: TINY-9237
* Limited overscroll for floating toolbar
Pre-checks:
Review:
> TINY-9237: Limit overscroll for floating toolbar

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/textpatterns/core/InlinePattern.ts
- modules/tinymce/src/core/test/ts/browser/textpatterns/FindInlinePatternTest.ts
- modules/tinymce/src/core/test/ts/browser/textpatterns/TextPatternsTest.ts
Related Ticket: TINY-8947
- update the check for a complete match in `findPatternStartFromSpot` that ATM works only if the string starts with the pattern
- add backtracking for the matching of the patterns, it is needed because otherwise in: `*a**` instead of matching `[*a*]*` it matches `*a[**]`
adding the backtracking makes fail this case:
```
patterns = [ { start: '*', end: '*' }, { start: '**', end: '**' } ]
**a**
```
before the first pattern (`*`) gets `**a[**]` and the second one (`**`) gets `[**a**]
with the backtracking, the first pattern (`*`) is matched.
to solve this I added a system that sort the pattern based on the length of the end (since is where we start to check, but it could be improved).
the order that take the prioritization is the one that has …
> TINY-8947: prevent inline text pattern to trigger when end match and start don't

- modules/oxide/src/less/theme/components/accessibility-checker/accessibility-checker.less
Related Ticket: TINY-9180
* Setting icon alignment to be middle 
* Decrease font size of 'issue' and 'warning/error'
* Remove borders around descriptions
* Set warning and success title colours to meet the contrast ratio
* Setting the background colour of the 'question mark' button
Pre-checks:
Review:
Screenshot of UI changes: 
- The `info` state is to demo
**Light Mode:**
**Dark Mode:**
> TINY-9180: Improve discoverability of the question mark read more link

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/html/DomParser.ts
Related Ticket: TINY-9186
* Fix memory leak caused in getContent method
Pre-checks:
Review:
> TINY-9186: Fix reported memory leak when parsing content

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/selection/SelectionBookmark.ts
- modules/tinymce/src/core/test/ts/browser/bookmark/BookmarksTest.ts
- modules/tinymce/src/core/test/ts/browser/dom/SelectionTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/view/ViewTest.ts
Related Ticket: TINY-9259
* Getting more selection apis working for hidden editors on Firefox
Pre-checks:
Review:
> TINY-9259: get more selection apis working on hidden editors

- modules/sugar/src/test/ts/browser/LocationTest.ts
- modules/sugar/src/test/ts/browser/ScrollTest.ts
TINY-9203
Since:
* Win11 FF defaults to hidden scrollbars while Win10 FF does not
* Win11 appears as Win10 to sand,
* sand cannot currently be updated to use User-Agent Client Hints API to support Win11 detection as sand needs to be synchronous for now
* FF has not implemented User-Agent Client Hints API for now
the following change has been made:
* Loosen scrollbar width assertions in LocationTest and ScrollTest in the sugar module to allow the scrollbar to be either hidden (zero-width) or visible when on Win10/11 FF
Pre-checks:
Review:
> TINY-9203: Allow scrollbar to be either hidden or visible when on Win10/11 Firefox

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/undo/Levels.ts
- modules/tinymce/src/core/test/ts/browser/UndoManagerTest.ts
Related Ticket: TINY-9222
* Fixed scrolling to the new cursor position after undo or redo action. This is fixed in `undo/Levels.ts:applyToEditor` since this function is called both from `undo` and `redo` actions. However it is also called in `undoManager.extra` function which I do not fully comprehend.
Pre-checks:
Review:
> TINY-9222: Fix scrolling to the cursor after undo or redo actions

- modules/tinymce/src/plugins/visualchars/test/ts/browser/PluginTest.ts
TINY-9308
* Add `editor.focus()` before an `editor.setRng` that reverses current selection to address browser quirk in Firefox where editor loses focus when toolbar button is clicked
Pre-checks:
Review:
> TINY-9308: Focus editor before reversing selection in visualchars PluginTest

- modules/tinymce/src/core/main/ts/content/TransparentElements.ts
- modules/tinymce/src/core/main/ts/delete/BlockMergeBoundary.ts
- modules/tinymce/src/core/test/ts/browser/content/TransparentElementsTest.ts
- modules/tinymce/src/core/test/ts/browser/delete/BlockBoundaryDeleteTest.ts
Related Ticket: TINY-9230
* Fixes issues with deleting elements where chrome in particular is doing very strange things.
Pre-checks:
Review:
> TINY-9230: Backspace/delete at transparent elements

- modules/tinymce/src/core/main/ts/content/TransparentElements.ts
- modules/tinymce/src/core/test/ts/browser/ForceBlocksTest.ts
- modules/tinymce/src/core/test/ts/browser/content/TransparentElementsTest.ts
Related Ticket: TINY-9290
* The node name matches was incorrect since they didn't match H1 so they are changed to look for things that are not uppercase instead.
* Changed all duplicates of the function in tests by exposing the function also makes it testable.
* Improved tests so that all text blocks elements are tested would be more difficult to test all block elements since UL etc require a child element to be valid.
Pre-checks:
Review:
> TINY-9290: fixed bug where names with numbers was not working correctly

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/core/color/ColorSwatch.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/color/ColorPickerSanityTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/color/GetCurrentColorTest.ts
Color picker dialog uses cursor position for color.
Pre-checks:
Review:
> TINY-9213: Color picker dialog now defaults to approriate color 

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/content/ContentTypes.ts
- modules/tinymce/src/core/test/ts/browser/content/EditorContentEventsTest.ts
- modules/tinymce/src/core/test/ts/browser/content/EditorContentTest.ts
Related Ticket: TINY-9143
* Added tests to check if content manipulation in `BeforeSetContent` callback is possible;
* Added tests to check if custom data object can be passed to all get content and set content events.
Pre-checks:
Review:
> TINY-9143: Add tests for insert content and get content events

- modules/tinymce/src/core/main/ts/api/EditorManager.ts
Related Ticket: DOC-1757
Previous PR: https://github.com/tinymce/tinymce-docs/pull/2554
* Update EditorManager API docs to improve description of `overrideDefaults` method, with example
* Document the `defaultOptions` property
* Credit to @kemister85 and @lnewson for the new documentation
Pre-checks:
Review:
> DOC-1757: Improve documentation of overrideDefaults editor method

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/Editor.ts
- modules/tinymce/src/core/main/ts/api/dom/StyleSheetLoader.ts
- modules/tinymce/src/core/test/ts/browser/dom/ContentCssCorsTest.ts
Related Ticket: TINY-6037
* Setting the `content_css_cors` option will now update the global `tinymce.dom.styleSheetLoader` with the given setting
* This allows the `crossOrigin="anonymous"` attribute to be added to stylesheets loaded in inline mode
* This was not possible before as inline editors share the global `styleSheetLoader`, rather than separate ones for each editor, which never has this setting updated.
Pre-checks:
Review:
> TINY-6037: Add `content_css_cors` setting to global `tinymce.dom.styleSheetLoader`

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/content/InsertContentImpl.ts
- modules/tinymce/src/core/test/ts/browser/content/InsertContentTest.ts
- modules/tinymce/src/core/test/ts/browser/textpatterns/TextPatternsTest.ts
Related Ticket: TINY-9193
Pre-checks:
Review:
> TINY-9193: The caret is moved to the previous line after Enter key pressed

- modules/tinymce/src/plugins/link/main/ts/core/Utils.ts
- modules/tinymce/src/plugins/link/test/ts/browser/SelectedTextLinkTest.ts
Related Ticket: TINY-9335
* Text to display will now be hidden if the selection is expanded within a block anchor
Pre-checks:
Review:
> TINY-9335: Block Links - Selection allows 'Text to Display' in Link Dialog

- modules/tinymce/src/core/main/ts/content/TransparentElements.ts
- modules/tinymce/src/core/test/ts/browser/content/InsertContentTest.ts
- modules/tinymce/src/core/test/ts/browser/content/TransparentElementsTest.ts
- modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts
Related Ticket: TINY-9232
* Splits out invalid elements that gets contained in nested structures in transparent elements like `p -> a -> p` for example
Pre-checks:
Review:
> TINY-9232: Parser needs to handle nested anchor cases better

- modules/alloy/CHANGELOG.md
- modules/alloy/src/main/ts/ephox/alloy/ui/schema/MenuSchema.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/types/MenuTypes.ts
- modules/alloy/src/test/ts/browser/ui/dropdown/MatrixMenuTest.ts
- modules/oxide/src/less/theme/components/color-swatch/color-swatch.less
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/core/color/Options.ts
- modules/tinymce/src/themes/silver/main/ts/ui/menus/item/structure/ItemStructure.ts
- modules/tinymce/src/themes/silver/main/ts/ui/menus/menu/MenuMovement.ts
- modules/tinymce/src/themes/silver/test/ts/browser/skin/OxideColorSwatchMenuTest.ts
Colorswatch now displays the selected color ( if applicable ) with a checkmark, navigation starts at the current color ( if applicable )
Pre-checks:
Review:
> TINY-9283: Improved colorswatch ui functionality.

- modules/mcagar/CHANGELOG.md
- modules/mcagar/src/main/ts/ephox/mcagar/api/bdd/TinyUiActions.ts
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/OptionTypes.ts
- modules/tinymce/src/core/test/ts/browser/init/ShadowDomEditorTest.ts
- modules/tinymce/src/themes/silver/main/ts/Render.ts
- modules/tinymce/src/themes/silver/main/ts/api/Options.ts
- modules/tinymce/src/themes/silver/main/ts/modes/Iframe.ts
- modules/tinymce/src/themes/silver/main/ts/modes/Inline.ts
- modules/tinymce/src/themes/silver/main/ts/modes/UiReferences.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/SilverUiOfTomorrowTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/window/SilverInlineDialogPositionTest.ts
- modules/tinymce/src/themes/silver/test/ts/headless/modes/UiReferencesTest.ts
Related Ticket: TINY-9226
* creates a new setting (placeholder name: ui_of_tomorrow) that enables the "two sink / adjacent sink" mode
* updates some tests to work with both modes
Pre-checks:
* [N/A] Changelog entry added - deferring for merge into develop
Review:
* [N/A] Docs ticket created (if applicable) - we don't know the name of the setting yet
> TINY-9226: Phase II => Introducing new UI setting

- SECURITY.md
- modules/acid/package.json
- modules/agar/CHANGELOG.md
- modules/agar/package.json
- modules/alloy/CHANGELOG.md
- modules/alloy/package.json
- modules/boss/package.json
- modules/boulder/package.json
- modules/bridge/CHANGELOG.md
- modules/bridge/package.json
- modules/darwin/package.json
- modules/dragster/package.json
- modules/jax/package.json
- modules/katamari-assertions/package.json
- modules/katamari/package.json
- modules/mcagar/CHANGELOG.md
- modules/mcagar/package.json
- modules/oxide-icons-default/package.json
- modules/oxide/package.json
- modules/phoenix/package.json
- modules/polaris/package.json
- modules/porkbun/package.json
- modules/robin/package.json
- modules/sand/package.json
- modules/snooker/package.json
- modules/sugar/package.json
- modules/tinymce/CHANGELOG.md
- versions.txt
Related ticket: TINY-8984
* Added changelog dates for monorepo libraries being released per `versions.txt`
* Bump monorepo libraries to their respective versions and cleaned `versions.txt`.
* Update SECURITY.md and CHANGELOG.md
Note: The TinyMCE changelog/package.json was already up to date due to previous PRs.
Monorepo version changes:
```
- @ephox/acid: 5.0.5 => 5.0.6
- @ephox/agar: 7.2.1 => 7.3.0
- @ephox/alloy: 11.0.1 => 12.0.0
- @ephox/boss: 6.0.5 => 6.0.6
- @ephox/boulder: 7.1.1 => 7.1.2
- @ephox/bridge: 4.1.1 => 4.2.0
- @ephox/darwin: 8.0.6 => 8.0.7
- @ephox/dragster: 7.0.5 => 7.0.6
- @ephox/jax: 7.0.5 => 7.0.6
- @ephox/katamari-assertions: 4.0.5 => 4.0.6
- @ephox/katamari: 9.1.1 => 9.1.2
- @ephox/mcagar: 8.1.1 => 8.2.0
- @tinymce/oxide-icons-default: 2.1.1 …
```
> TINY-8984: Preparation for 6.3 community release

- modules/alloy/src/main/ts/ephox/alloy/alien/Boxes.ts
- modules/alloy/src/test/ts/atomic/alien/BoxesTest.ts
- modules/tinymce/src/themes/silver/main/ts/Render.ts
- modules/tinymce/src/themes/silver/main/ts/Theme.ts
- modules/tinymce/src/themes/silver/main/ts/modes/ScrollingContext.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/SilverPopupSinkBoundsTest.ts
- modules/tinymce/src/themes/silver/test/ts/headless/modes/ScrollingContextTest.ts
Related Ticket: TINY-9226
* restrict the popup sink to show within visible areas of the (possibly nested) scrollable viewports
Pre-checks:
* [N/A] Changelog entry added - deferring
Review:
* [N/A] Docs ticket created (if applicable) - no documentation required.
> TINY-9226: Phase III => Constraining the popup sink bounds

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/lists/main/ts/Plugin.ts
- modules/tinymce/src/plugins/lists/main/ts/core/FilterContent.ts
- modules/tinymce/src/plugins/lists/test/ts/browser/FilterContentTest.ts
Related Ticket: TINY-4818
*  added content filter for lists to wrap invalid child nodes in `li` elements
Pre-checks:
Review:
> TINY-4818: Wrap invalid list child nodes within list items

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/advlist/main/ts/core/ListUtils.ts
- modules/tinymce/src/plugins/advlist/main/ts/ui/Buttons.ts
- modules/tinymce/src/plugins/advlist/test/ts/atomic/ListUtilsTest.ts
- modules/tinymce/src/plugins/advlist/test/ts/browser/AdvlistOptionsAndToolbarTest.ts
- modules/tinymce/src/plugins/advlist/test/ts/browser/ListUtilsTest.ts
Related Ticket: TINY-5167
* Toolbar split buttons in advlist plugin to show the correct state when the cursor is in a checklist
Pre-checks:
Review:
> TINY-5167: Toolbar split buttons in advlist plugin to show the correct state when the cursor is in a checklist

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/autoresize/main/ts/core/Resize.ts
- modules/tinymce/src/plugins/autoresize/test/ts/browser/AutoresizePluginTest.ts
Related Ticket: TINY-8872
the problem was that `document` skin has a CSS that aligns the bottom of the content to the bottom of the editor, but not setting `autoresize_bottom_margin` the editor takes the default of `50`, so each time the resize function calculated the size it also adds `autoresize_bottom_margin` but since the CSS sets the bottom of the content to something less than the `autoresize_bottom_margin` resize go in a loop.
The idea is to check if the resize function goes in a loop and if so, the resize function considers the `margin bottom` as always 0 instead of `autoresize_bottom_margin`, and the min-height of HTML and Body are changed
P.S. we could put in the documentation that `autoresize_bottom_margin` should not be set as a value greater than the …
> TINY-8872: fix infinite autoresize with content_css document

- modules/bridge/CHANGELOG.md
- modules/bridge/src/main/ts/ephox/bridge/components/menu/FancyMenuItem.ts
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/core/color/ColorSwatch.ts
- modules/tinymce/src/themes/silver/main/ts/ui/menus/item/build/ColorSwatchItem.ts
- modules/tinymce/src/themes/silver/test/ts/browser/skin/OxideColorSwatchMenuTest.ts
Checkmark missing from the menu colorswatch
Pre-checks:
Review:
> TINY-9395: menu colorswatch fixup

- Jenkinsfile
- modules/tinymce/CHANGELOG.md
- modules/tinymce/package.json
Related Ticket: TINY-9402
* Bumped package.json and updated changelog
Pre-checks:
Review:
> TINY-9402: Prepare for TinyMCE 5.10.7 release

- Jenkinsfile
- modules/sugar/src/test/ts/browser/LocationTest.ts
- modules/sugar/src/test/ts/browser/ScrollTest.ts
* Use win10 nodes to test Chrome, Edge and FF
* Backported fixes for ScrollTest.ts and LocationTest.ts
Pre-checks:
Review:
> TINY-9402: Prepare for TinyMCE 5.10.7 release (take 2)

- Jenkinsfile
- modules/alloy/src/test/ts/browser/position/TransitionsTest.ts
- modules/tinymce/src/plugins/table/test/ts/module/test/TableTestUtils.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/header/StickyHeaderInitialPlacementTest.ts
Related Ticket: TINY-9402
* Reverted to use win10 to run tests for Chrome and Edge
* Changed the delta value of approximate width in testing table
* Skipped a transition as it is flaky on PhantomJS
Pre-checks:
Review:
> TINY-9402: Prepare for TinyMCE 5.10.7 release (take 3)

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/content/TransparentElements.ts
- modules/tinymce/src/core/main/ts/paste/DragDrop.ts
- modules/tinymce/src/core/test/ts/browser/EditorAutoFocusTest.ts
- modules/tinymce/src/core/test/ts/browser/content/InsertContentTest.ts
- modules/tinymce/src/core/test/ts/browser/content/TransparentElementsTest.ts
- modules/tinymce/src/core/test/ts/browser/paste/DragDropTransparentsTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/header/StickyHeaderInitialPlacementTest.ts
Related Ticket: TINY-9231
* Fix for drag/dropping transparents into transparents
Pre-checks:
Review:
> TINY-9231: Drag/drop on block links into other links

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/lists/main/ts/actions/ToggleList.ts
- modules/tinymce/src/plugins/lists/main/ts/core/NodeType.ts
- modules/tinymce/src/plugins/lists/test/ts/browser/ToggleListInTableCell.ts
Related Ticket: TINY-6853
* Toggling list inside a table cell with that has an anchor element in it, now includes the anchor element in the produced list
Pre-checks:
Review:
> TINY-6853: Lists applied incorrectly in table cells

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/dom/DOMUtils.ts
- modules/tinymce/src/core/main/ts/api/dom/Selection.ts
- modules/tinymce/src/core/main/ts/content/InsertContent.ts
- modules/tinymce/src/core/test/ts/browser/content/InsertContentTest.ts
- modules/tinymce/src/core/test/ts/browser/dom/DomUtilsTest.ts
- modules/tinymce/src/core/test/ts/browser/dom/SelectionTest.ts
Related Ticket: TINY-9462
* Fixes so insertContent becomes a noop if the selection range is noneditable
* Adds a new editor.selection.isEditable public api needed for this and other future PRs
* Adds a new editor.dom.isEditable public api needed for this and other future PRs
* Fixes some issues with the changelog like duplicate categories and incorrect ordering and heading level
Pre-checks:
Review:
> TINY-9462: InsertContent api is not blocking for noneditable root content

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/menus/menubar/Integration.ts
Related Ticket: TINY-9450
* Added typography plugin to the default menubar.
Pre-checks:
Review:
> TINY-9450: Added typography plugin to the default menubar

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/dom/StyleSheetLoader.ts
Related Ticket: TINY-9433
* Removes `onload` event workaround for webkit as this has been fixed
* Replaces custom event handler
Pre-checks:
Review:
> TINY-9433: Removed outdated webkit bug workaround

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/toolbar/button/ToolbarButtons.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/buttons/GroupToolbarButtonTest.ts
Related Ticket: TINY-9496
* onSetup function was not running when defining custom group toolbar button
Pre-checks:
Review:
> TINY-9496: onSetup should run when defining a custom group toolbar button

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/core/color/ColorSwatch.ts
- modules/tinymce/src/themes/silver/test/ts/browser/skin/OxideColorSwatchMenuTest.ts
Related Ticket: TINY-9439
* Color picker on toolbar is not updated when changing forecolor or backcolor from menu
Pre-checks:
Review:
[TINY-9439]: https://ephocks.atlassian.net/browse/TINY-9439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TINY-9439: Color picker on toolbar is not updated when changing forecolor or backcolor from menu

- modules/acid/src/main/ts/ephox/acid/api/colour/HexColour.ts
- modules/acid/src/main/ts/ephox/acid/gui/components/RgbForm.ts
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/ColorPicker.ts
- modules/tinymce/src/themes/silver/test/ts/headless/components/colorpicker/ColorPickerTest.ts
Related Ticket: TINY-9457 [GitHub-#8156](https://github.com/tinymce/tinymce/issues/8156)
* remove the `#` prefix before updating the hex value in the state of the color picker component
Pre-checks:
Review:
https://github.com/tinymce/tinymce/issues/8156
> TINY-9457: Color Picker doesn't handle hex color prefixed with #

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/visualchars/main/ts/core/Nodes.ts
- modules/tinymce/src/plugins/visualchars/main/ts/core/VisualChars.ts
- modules/tinymce/src/plugins/visualchars/test/ts/atomic/NodesTest.ts
- modules/tinymce/src/plugins/visualchars/test/ts/browser/PluginTest.ts
Related Ticket: TINY-9474
* Prevents visual characters spans from being rendered within a noneditable context.
Pre-checks:
Review:
[TINY-9474]: https://ephocks.atlassian.net/browse/TINY-9474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TINY-9474: Visualchars applies to noneditable content

- modules/tinymce/src/core/main/ts/paste/DragDrop.ts
- modules/tinymce/src/core/test/ts/browser/paste/DragDropTransparentsTest.ts
Related Ticket: TINY-9231
* This is a follow up PR to the previous TINY-9231 PR a Firefox specific case was found during QA
Pre-checks:
Review:
[TINY-9231]: https://ephocks.atlassian.net/browse/TINY-9231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TINY-9231]: https://ephocks.atlassian.net/browse/TINY-9231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TINY-9231: fixed firefox case with drag/drop next to block

- modules/alloy/src/main/ts/ephox/alloy/api/ui/FloatingToolbarButton.ts
- modules/alloy/src/main/ts/ephox/alloy/api/ui/SplitFloatingToolbar.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/types/FloatingToolbarButtonTypes.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/types/SplitToolbarBaseTypes.ts
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/Render.ts
- modules/tinymce/src/themes/silver/main/ts/ui/general/OuterContainer.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/ToolbarDrawerToggleTest.ts
Related Ticket: TINY-9337
* Removed focusing after toggling the toolbar in `FloatingToolbarButton`.
The focusing was added in the initial `FloatingToolbarButton` commit in 2019. I am not sure what are the consequences of removing it, but it definitely conflicts with `skip_focus` argument in `execCommend`.
Other solutions would be to refactor the `execCommand` in order to pass down `skip_focus` argument to all commands, but that feels like a major public API change.
Pre-checks:
Review:
[TINY-9337]: https://ephocks.atlassian.net/browse/TINY-9337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TINY-9337: Remove focusing after toggling the toolbar

- modules/snooker/src/main/ts/ephox/snooker/api/TableFill.ts
- modules/snooker/src/test/ts/browser/CloneFormatsTest.ts
- modules/sugar/CHANGELOG.md
- modules/sugar/src/main/ts/ephox/sugar/api/selection/Awareness.ts
- modules/sugar/src/test/ts/browser/CursorPositionTest.ts
- modules/tinymce/CHANGELOG.md
- versions.txt
Related Ticket: TINY-9449
* This issue is related to cloning the formatting during the creation of new table rows. Here we have the case when formatting of merge tag prefix unexpectedly cloned to the new cell.  The clone logic searches for the first cursor position in the original cell and collects ancestors' formatting nodes. It seems to me that the main root of the issue is that the search is continuing even within the `CEF` elements, instead of stopping before them. This [test](https://github.com/tinymce/tinymce/blob/develop/modules/snooker/src/test/ts/browser/CloneFormatsTest.ts) shows that cloning formatting nodes even if they are in the `CEF` container is the expected behavior. In this PR I am trying to revisit the approach and treat `CEF` elements the same …
> TINY-9449: Cursor position search should not descend into the CEF

- modules/tinymce/src/core/main/ts/api/dom/DOMUtils.ts
- modules/tinymce/src/core/main/ts/api/dom/Selection.ts
Related Ticket: DOC-1888
* Adds api docs for the new isEditable apis.
I'm trying to be vague of it's implementation details but still hint that they are O(n) so could be expensive to use.
Pre-checks:
Review:
> DOC-1888: added docs for selection.isEditable/dom.isEditable

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/dom/DOMUtils.ts
- modules/tinymce/src/plugins/advlist/main/ts/core/ListUtils.ts
- modules/tinymce/src/plugins/advlist/test/ts/browser/NoneditableRootTest.ts
- modules/tinymce/src/plugins/lists/demo/ts/demo/Demo.ts
- modules/tinymce/src/plugins/lists/main/ts/actions/ToggleList.ts
- modules/tinymce/src/plugins/lists/main/ts/core/Util.ts
- modules/tinymce/src/plugins/lists/test/ts/browser/ContentEditableFalseActionsTest.ts
- modules/tinymce/src/plugins/lists/test/ts/browser/NoneditableRootTest.ts
Related Ticket: TINY-9458
* Blocks list operations on lists in a noneditable root
* Blocks adding lists when any noneditable block is selected
Pre-checks:
Review:
> TINY-9458: Editable lists in noneditable root

- modules/tinymce/src/core/test/ts/browser/delete/InlineFormatDeleteTest.ts
Related Ticket: TINY-9516
* Updated structure and selection assertion to match Firefox's updated `contenteditable` behaviour on v108.0.2
Pre-checks:
Review:
> TINY-9516: InlineFormatDelete element with multiple children selection test fails on latest Firefox v108.0.2

- modules/tinymce/src/plugins/fullscreen/test/ts/browser/FullScreenPluginTest.ts
* This adds some logging to the area of where we are seeing some flakes.
* It makes us able to see if the issue with with Sizzle that is used in the query matching.
* It checks if the command did anything or if it's just the body class that doesn't have the expected `.tox-fullscreen` class
* The plan is to remove this once we figure out why this is happening.
Pre-checks:
Review:
> Temporary extra logging of fullscreen test

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/keyboard/InlineUtils.ts
- modules/tinymce/src/core/test/ts/browser/keyboard/InlineUtilsTest.ts
- modules/tinymce/src/core/test/ts/browser/selection/InlineBoundarySelectionTest.ts
Related Ticket: TINY-9471
* Added predicate check for inline boundaries rendering
* Added tests for selections of inline boundaries in general and then some special case for the noneditables
Pre-checks:
Review:
> TINY-9471: Inline boundaries styling gets applied to noneditable elements

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/toolbar/button/ToolbarButtons.ts
- modules/tinymce/src/themes/silver/test/ts/headless/toolbar/ToolbarButtonsTest.ts
Related Ticket: TINY-9504
* Clicking on a disabled split button won't call `onAction` callback anymore. Added the necessary check.
Pre-checks:
Review:
> TINY-9504: Fix clicking on a disabled split button

- modules/tinymce/src/core/main/ts/focus/FocusController.ts
- modules/tinymce/src/core/test/ts/browser/focus/HighlightOnFocusTest.ts
- modules/tinymce/src/core/test/ts/webdriver/keyboard/IframeTabfocusTest.ts
Related Ticket: TINY-9277
* Removed the editor focus highlight when not in focus
Pre-checks:
Review:
> TINY-9277: Remove the editor focus highlight when not in focus

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/newline/InsertBlock.ts
- modules/tinymce/src/core/test/ts/browser/keyboard/EnterKeyTest.ts
- modules/tinymce/src/core/test/ts/browser/newline/InsertNewLineTest.ts
Related Ticket: TINY-9461
* Prevents editing host elements like contentEditable true in a contentEditable false to be split.
* Prevents editing hosts elements inside a noneditable root to be split.
* Fixed issue with schema checking not being correct it would put P in P since it checked the wrong element parent.
Pre-checks:
Review:
> TINY-9461: Pressing enter in a block in a noneditable root causes invalid nesting

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/delete/MergeBlocks.ts
- modules/tinymce/src/core/main/ts/dom/PaddingBr.ts
- modules/tinymce/src/core/test/ts/browser/delete/BlockBoundaryDeleteTest.ts
Related Ticket: TINY-9454
* Preserve formatting when backspacing from one empty block to another. Otherwise block's formatting is cleared by inserting `br[data-mce-bogus]`.
Pre-checks:
Review:
> TINY-9454: Preserve formatting when backspacing from one empty block to another

- modules/tinymce/src/themes/silver/main/ts/ui/menus/menubar/Integration.ts
Related Ticket: TINY-9537
* added `addtemplate` `inserttemplate` menu items to default menubar
Pre-checks:
Review:
> TINY-9537: Added Advance Template plugin menu items to default menubar

- modules/oxide/src/less/theme/components/form/textarea.less
Related Ticket: TINY-9331
* Followup on a previous PR since QA found some isuses
* Added overflow hidden that seem to properly clip the scrollbars to the border-radius on all browsers.
Pre-checks:
Review:
> TINY-9331: added overflow hidden to clip the textarea scrollbars

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/sidebar/Sidebar.ts
- modules/tinymce/src/themes/silver/test/ts/browser/sidebar/SidebarRoleAttributeTest.ts
Related Ticket: TINY-9517
* Sidebar element role attribute defaults to `role="presentation"` (hidden)
* Sidebar element role attribute changes to `role="region"` (with `sidebar_show` option)
* Toggling the sidebar element would toggle attributes with `region` and `presentation`
Pre-checks:
Review:
> TINY-9517: Sidebar element accessibility fixes

- modules/tinymce/src/core/main/ts/api/OptionTypes.ts
- modules/tinymce/src/core/main/ts/focus/FocusController.ts
- modules/tinymce/src/core/test/ts/browser/focus/HighlightOnFocusTest.ts
- modules/tinymce/src/core/test/ts/module/test/DialogUtils.ts
Related Ticket:  TINY-9277
* Border should only show when content area is focused, instead of checking the editor (which includes menubar, toolbar, dialog, etc)
* Added test cases
Pre-checks:
Review:
> TINY-9277: Border should only be triggered when focused on content area and removed otherwise

- modules/oxide/src/less/theme/components/color-swatch/color-swatch.less
Different selector. No changelog or tests should be needed, as the same behavior remains, and it shouldn't really change anything aside from using the better css selector.
Pre-checks:
Review:
> TINY-9567: Changed selector for color swatch checkmark, same behavior

- modules/bridge/src/demo/ts/dialogs/DemoDialogHelpers.ts
- modules/bridge/src/main/ts/ephox/bridge/components/dialog/Dialog.ts
- modules/oxide/src/less/theme/components/dialog/dialog.less
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialog.ts
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialogInstanceApi.ts
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverInlineDialog.ts
- modules/tinymce/src/themes/silver/test/ts/browser/window/SilverDialogApiAccessTest.ts
Related Ticket: TINY-9528
This function simple remove the current size class of the dialog and put a full-screen class instead or vice versa
`toggleFullscreen` is in `SilverDialog` and not in `SilverDialogInstanceApi` the dialog sizes are managed in `SilverDialog` and not in `SilverDialogInstanceApi`
P.S. about the docs ticket I did not find doc for the single API, so I did not create a ticket, if I miss something let me know and I will create it
Pre-checks:
Review:
> TINY-9528: implementation of `toggleFullscreen` function for dialog

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/fmt/ListItemFormat.ts
- modules/tinymce/src/core/test/ts/browser/fmt/ListItemFormatTest.ts
Related Ticket: TINY-9563
* Disable list formatting if the list is in a noneditable root
Pre-checks:
Review:
> TINY-9563: Noneditable multi-line selection is formattable

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/dom/Selection.ts
- modules/tinymce/src/core/main/ts/delete/DeleteCommands.ts
- modules/tinymce/src/core/main/ts/keyboard/DeleteBackspaceKeys.ts
- modules/tinymce/src/core/main/ts/util/Quirks.ts
- modules/tinymce/src/core/test/ts/browser/delete/CefDeleteTest.ts
- modules/tinymce/src/core/test/ts/browser/delete/DeleteCommandsTest.ts
- modules/tinymce/src/core/test/ts/browser/dom/SelectionTest.ts
Related Ticket: TINY-9477
* Blocking commands and keyboard delete/backspace from being applied to noneditable content
* Rewrote editor.selection.isEditable to handle fake selections and prioritize them first.
Pre-checks:
Review:
> TINY-9477: Backspace/delete with selection across block elements in a noneditable root deletes the elements

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/paste/Clipboard.ts
- modules/tinymce/src/core/test/ts/browser/paste/InternalClipboardTest.ts
We now try to prevent to rely on safari's default paste behavior for links provided by safari, as it attempted to be helpful.
Pre-checks:
Review:
> TINY-9489: Prevent safari from modifying paste content.

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/Annotator.ts
- modules/tinymce/src/core/test/ts/browser/annotate/AnnotationRemovedTest.ts
Related Ticket: TINY-9399
* It is possible to remove an annotation immediately after creation without any selection changes.
The bug was introduced in TINY-8195 and connected to [this](https://github.com/tinymce/tinymce/pull/7485/files#diff-3882b4c135273323573f94b4f8e6a895594701e68d80588eb3749f9567e5502cL89-L92) bookmark, which adjusts the selection in the way that it is impossible to retain the selected word. 
Everything works fine by using offset bookmark `getBookmark(2)`, but I do not really understand the differences between different bookmark types (and only the default one is used in Tiny's code). Other possible solution is in this PR.
Pre-checks:
Review:
> TINY-9399: Fix removing annotation immediately after creation

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/OptionTypes.ts
- modules/tinymce/src/core/main/ts/api/Options.ts
- modules/tinymce/src/core/main/ts/api/html/DomParser.ts
- modules/tinymce/src/core/main/ts/content/PrePostProcess.ts
- modules/tinymce/src/core/main/ts/init/InitContentBody.ts
- modules/tinymce/src/core/main/ts/paste/ProcessFilters.ts
- modules/tinymce/src/core/test/ts/browser/content/EditorContentTest.ts
- modules/tinymce/src/core/test/ts/browser/content/InsertContentTest.ts
- modules/tinymce/src/core/test/ts/browser/content/InsertUnsanitizedContentTest.ts
- modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts
- modules/tinymce/src/core/test/ts/browser/init/InitUnsanitizedContentTest.ts
- modules/tinymce/src/core/test/ts/browser/paste/UnsanitizedPasteTest.ts
- modules/tinymce/src/plugins/media/main/ts/core/Sanitize.ts
- modules/tinymce/src/plugins/template/main/ts/core/Templates.ts
- modules/tinymce/src/plugins/template/main/ts/core/Utils.ts
- modules/tinymce/src/plugins/template/main/ts/ui/Dialog.ts
Related Ticket: TINY-9600
* Add `xss_sanitization: boolean` option (default: `true`) to enable/disable XSS sanitization in the parser
* Make all content-related behaviour, including `setContent`, `getContent`, initialising content, and pasting content, respect `xss_sanitization` option
Pre-checks:
Review:
> TINY-9600: Provide configuration to turn off XSS sanitization

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/link/main/ts/ui/Controls.ts
- modules/tinymce/src/plugins/link/test/ts/browser/QuickLinkTest.ts
Related Ticket: TINY-9593
* Formatting after pasting a link from quickbars is preserved now.
Pre-checks:
Review:
> TINY-9593: Fix pasting links from quickbars

- modules/oxide/src/less/theme/components/form/textarea.less
Related Ticket: TINY-9610
* Moves the CSS border reset to a wrapper specific selector making the wrapper change backwards compatible
Pre-checks:
Review:
> TINY-9610: added css workaround for unwrapped textareas

- modules/oxide/gulpfile.js
- modules/oxide/src/less/theme/components/dialog/dialog.less
- modules/oxide/src/less/theme/globals/global-variables.less
- modules/tinymce/CHANGELOG.md
Related Ticket: TINY-9587
- update `@dialog-table-border-color`, `@border-color` to increase the contrast of the border colour in dialog in dark mode.
- update oxide `gulpfile` to fix button not working after hot reload
Pre-checks:
Review:
> TINY-9587: Increase help dialog horizontal rule contrast in dark mode

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/WindowManager.ts
- modules/tinymce/src/themes/silver/test/ts/browser/window/SilverInlineDialogPositionTest.ts
- modules/tinymce/src/themes/silver/test/ts/module/TestExtras.ts
Related Ticket: TINY-9554
The problem was that for inline dialogs we use to refer to the body even if the editor was not an inline editor, this does not work if the container of the editor is in position `fixed` or `absolute`
Pre-checks:
Review:
> TINY-9554: Inline Dialog mispositioned inside fixed or absolute content

- modules/oxide/src/less/theme/components/editor/editor.less
- modules/tinymce/CHANGELOG.md
Related Ticket: TINY-9408
* Fix transition of sticky-toolbar in inline mode
* Toolbar would disappear immediately, when it is meant to fade out
Pre-checks:
Review:
> TINY-9408: Fix sticky-toolbar transition in iframe mode

- modules/bridge/src/main/ts/ephox/bridge/components/view/ViewButton.ts
- modules/tinymce/src/themes/silver/main/ts/ui/view/ViewButtons.ts
- modules/tinymce/src/themes/silver/test/ts/browser/view/ViewButtonsTest.ts
Related Ticket: TINY-9616
this add the active flag to  `togglebutton` to allow to have the correct active status when the view is open
Pre-checks:
Review:
> TINY-9616: add active flag to togglebutton

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/core/color/Options.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/color/TextColorSanityTest.ts
Related Ticket: TINY-9560
* `forecolor` and `backcolor` color swatches did not have the correct number of columns when `color_cols` option was set
* `color_cols` option is now used as a fallback before the default number of columns for the `forecolor` and `backcolor` color swatches
Pre-checks:
Review:
> TINY-9560: Fix `color_cols` option not being respected

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/DragDropOverrides.ts
- modules/tinymce/src/core/test/ts/browser/DragDropOverridesTest.ts
Related Ticket: TINY-9606
* Added padding if needed when dragging the last item out of a block.
Pre-checks:
Review:
> TINY-9606: Dragging single child CEF from block doesn't pad it

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/html/DomParser.ts
- modules/tinymce/src/core/main/ts/content/InsertContentImpl.ts
- modules/tinymce/src/core/main/ts/html/InvalidNodes.ts
- modules/tinymce/src/core/main/ts/html/ParserUtils.ts
- modules/tinymce/src/core/test/ts/browser/DragDropOverridesTest.ts
- modules/tinymce/src/core/test/ts/browser/content/InsertContentTest.ts
- modules/tinymce/src/core/test/ts/browser/html/ParserUtilsTest.ts
Related Ticket: TINY-9595
* Adds a fix for not splitting editing hosts
* Adds a way to find the closest editing host in ast nodes
* Fixed a test in drag drop that broke now that it does the correct thing
Pre-checks:
Review:
> TINY-9595: Paste paragraphs in CET p in noneditable root

- modules/oxide/src/less/skins/ui/tinymce-5/skin.less
- modules/oxide/src/less/theme/components/toolbar-button/toolbar-number-input.less
Related Ticket: TINY-9644
the problem was that in some cases we got that `skin.less` file that overwrites the styles for some elements and also that overwriting the `@toolbar-button-height` was not enough since we had also `@toolbar-number-input-button-height` with the same value
Pre-checks:
Review:
> TINY-9644: fix styles for `fontinputsize` component

- modules/tinymce/src/core/main/ts/api/html/DomParser.ts
- modules/tinymce/src/core/main/ts/api/html/Sanitization.ts
- modules/tinymce/src/core/main/ts/api/util/URI.ts
- modules/tinymce/src/core/test/ts/browser/content/EditorContentTest.ts
- modules/tinymce/src/core/test/ts/browser/content/InsertUnsanitizedContentTest.ts
- modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts
- modules/tinymce/src/core/test/ts/browser/init/InitUnsanitizedContentTest.ts
- modules/tinymce/src/core/test/ts/browser/paste/UnsanitizedPasteTest.ts
Related Ticket: TINY-9635
Previously node and attribute validation code (incl. bogus element removal, schema validation, etc.) is attached to DOMPurify hooks
* With the new option `xss_sanitization` introduced in TINY-9600, this code is no longer run when DOMPurify sanitization is disabled with `xss_sanitization: false`
This PR reintroduces the functionality by using NodeIterator to iterate through the body to validate nodes and attributes when DOMPurify is disabled (`xss_sanitization: false`)
* We reuse the same logic as what was previously defined in the DOMPurify hooks where possible (attribute validation had to be slightly adapted)
* Sanitization code is also refactored into a new `Sanitization` module separate from `DomParser`
* Address bug in `isInvalidUri` …
> TINY-9635: Use NodeIterator to perform node and attribute validation when sanitization is disabled

- modules/alloy/src/main/ts/ephox/alloy/api/ui/Button.ts
- modules/oxide/src/less/theme/components/tree/tree-button.less
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/demo/ts/demo/TreeDemo.ts
- modules/tinymce/src/themes/silver/main/ts/ui/button/MenuButton.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/Tree.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/SilverDialogTreeTest.ts
- modules/tinymce/src/themes/silver/test/ts/headless/components/tree/TreeTest.ts
Related Ticket: TINY-9614
* Enable navigation in the Tree component using Tab and shift+Tab keys
* Fix styling of focused components
* Add aria attributes to tree items
Pre-checks:
Review:
> TINY-9614: Fix navigation inside tree using keyboard 

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/textpatterns/core/BlockPattern.ts
- modules/tinymce/src/core/test/ts/browser/textpatterns/TextPatternsTest.ts
Related Ticket: TINY-9603
If there is a single space between pattern.start and text (e.g. `# 1`) then it will be left in the text content as an invisible one and then can be transformed to nbsp in certain circumstances. This is not an issue with multiple spaces because they are transformed to non-breaking ones straight away. I've decided to remove this single space whatsoever as it feels to be the expected behavior.
Other solution is to preserve this space by replacing it with `&nbsp;` so it will be visible to the user.
Pre-checks:
Review:
> TINY-9603: Fix an invisible space after applying heading text_patterns

- modules/tinymce/CHANGELOG.md
Related Ticket: TINY-9647
* Removed near-duplicate line from changlog.
* Removed entry duplicated from entry in the Advanced Typography plugin changelog.
Pre-checks:
~* [ ] Branch prefixed with `feature/`, `hotfix/` or `spike/`~
Review:
~* [ ] Milestone set~
~* [ ] Docs ticket created (if applicable)~
> TINY-9647: Two duplicated lines in the TinyMCE Changelog

- modules/tinymce/src/core/test/ts/browser/DragDropOverridesTest.ts
Related Ticket: TINY-9606
* Follow up PR to TINY-9606 noticed that I used the wrong ticket IDs in the test labels. So pretty minor. To many parallel PRs got them mixed up.
Pre-checks:
Review:
> TINY-9606: fixed test labels ticket ids

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/core/color/Options.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/color/TextColorSanityTest.ts
Related Ticket: TINY-9649
* Opening a color swatch with `color_cols`, `color_cols_foreground`, or `color_cols_background` set to `0` would cause the page to crash.
* Validated the number returned within `getColorCols` to be greater than zero
* If the number is set to zero or less in the option, the default number of columns, five, will be returned
Pre-checks:
Review:
> TINY-9649: Prevent zero color columns from crashing page

- modules/oxide/src/less/theme/components/view/view.less
- modules/tinymce/src/themes/silver/main/ts/ui/view/View.ts
Related Ticket: TINY-9663
Added class `tox-view--scrolling` similar to `tox-toolbar--scrolling` also added `tox-view--mobile` that overview the padding in mobile
Pre-checks:
Review:
> TINY-9663: now view header scrolls on mobile

- modules/acid/package.json
- modules/agar/package.json
- modules/alloy/package.json
- modules/boss/package.json
- modules/bridge/package.json
- modules/darwin/package.json
- modules/dragster/package.json
- modules/jax/package.json
- modules/katamari-assertions/package.json
- modules/katamari/package.json
- modules/mcagar/package.json
- modules/oxide/package.json
- modules/phoenix/package.json
- modules/polaris/package.json
- modules/robin/package.json
- modules/sand/package.json
- modules/snooker/package.json
Related Ticket: None
* In the end, the only major change is removing `tslib` from each package - we no longer need it as we require the latest browsers. It's still a devDependency at the top level as our `tsconfig.json` is set to import it if necessary.
Pre-checks:
Review:
> Clean up our dependency lists, make sure devDependencies are not listed as dependencies

- modules/oxide/src/less/theme/components/collection/collection.less
- modules/oxide/src/less/theme/components/toolbar-button/toolbar-button.less
- modules/oxide/src/less/theme/components/toolbar-button/toolbar-split-button.less
Related Ticket: TINY-9176
* Fixed borders on split buttons when active, hovered, enabled
* Fixed missing focus on split buttons using keyboard navigation
* Fixed missing focus on disabled buttons using keyboard navigation
* Fixed icon color in disabled menu items
* Fixed table grid background color
* Reverted variable name changes causing issues in premium skins
Pre-checks:
Review:
> TINY-9176: Focus Styles QA fixes

- modules/oxide/src/less/theme/components/advtemplate/advtemplate.less
Related Ticket: TINY-9667
* set 30% width for the left side of Templates dialog (with the tree component)
* set width to 100% when it is on mobile
Pre-checks:
Review:
> TINY-9667: Set width for Templates dialog left side bar

- modules/oxide/src/less/theme/components/dialog/dialog.less
- modules/oxide/src/less/theme/globals/global-variables.less
- modules/tinymce/CHANGELOG.md
Related Ticket: TINY-9676
Alternate PR: https://github.com/tinymce/tinymce/pull/8537
* Revert all changes to border colors
* Contrast issues in dark mode remain as they are in previous version
Pre-checks:
Review:
> TINY-9676: Revert TINY-9587

- modules/oxide/src/less/theme/components/well/well.less
- modules/tinymce/CHANGELOG.md
Related Ticket: TINY-9673
fix border for modal square custom editor content
Pre-checks:
Review:
> TINY-9673: fix border for modal square custom editor content

- modules/tinymce/src/themes/silver/main/ts/ui/view/View.ts
- modules/tinymce/src/themes/silver/test/ts/browser/view/ViewTest.ts
Related Ticket: TINY-9671
add buttons navigation via keyboard to view mode
Pre-checks:
Review:
> TINY-9671: add buttons navigation via keyboard to view mode

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/general/OuterContainer.ts
- modules/tinymce/src/themes/silver/test/ts/browser/view/ViewTest.ts
Related Ticket: TINY-9419
The problem is that the [toggleToolbarDrawer](https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/themes/silver/main/ts/ui/general/OuterContainer.ts#L200) uses [this refresh function](https://github.com/tinymce/tinymce/blob/develop/modules/alloy/src/main/ts/ephox/alloy/toolbar/SplitToolbarUtils.ts#L22), but it needs the width of the toolbar to render the buttons.
An easy fix is to show the toolbar before `toggleToolbarDrawer`, but this cause the user will see the animation again
Pre-checks:
Review:
> TINY-9419: `More...` button disapear if it is triggered and view mode is switched

- modules/alloy/src/main/ts/ephox/alloy/behaviour/docking/DockingApis.ts
- modules/tinymce/src/themes/silver/main/ts/modes/Inline.ts
- modules/tinymce/src/themes/silver/main/ts/ui/header/InlineHeader.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/scrolling/EditorInScrollingContainerTest.ts
- modules/tinymce/src/themes/silver/test/ts/module/TestExtras.ts
Related Ticket: TINY-9652
* Changed the logic of `updateVisibility` of the toolbar when `ui_mode: 'split'`
* 	In a scrollable container, for toolbar_location: top and if the toolbar is shown and the scrollable container is scrolled to the top, the toolbar should be invisible (in this case, the toolbar isn't docked, so the code updating the visibility is not triggered)
* 	In a scrollable container, for toolbar_location: bottom and if the toolbar is shown and the scrollable container is scrolled to the furthest down to the bottom, the toolbar should be invisible 
Pre-checks:
Review:
> TINY-9652: Hide toolbar when editor is out of view in a scrollable container

- modules/tinymce/src/plugins/visualchars/main/ts/core/Nodes.ts
- modules/tinymce/src/plugins/visualchars/main/ts/core/VisualChars.ts
- modules/tinymce/src/plugins/visualchars/test/ts/browser/NodesTest.ts
- modules/tinymce/src/plugins/visualchars/test/ts/browser/PluginTest.ts
Related Ticket: TINY-9685
* It should always process `mce-nbsp-wrap` elements regardless if they are editable or not.
* Moved atomic test to browser since it does dom things it's no longer atomic.
* Moved the isNbspWrapper to the Nodes module where all the other predicates are.
Pre-checks:
Review:
> TINY-9685: fixed filtering for mce-nbsp-wrap elements

- modules/tinymce/src/core/main/ts/init/Init.ts
- modules/tinymce/src/core/main/ts/init/InitContentBody.ts
- modules/tinymce/src/core/main/ts/init/InitIframe.ts
Related Ticket: TINY-9670
* While explaining the Init process to @kemister85, I realised that the iframe-specific things `InitContentBody` does no longer need to be there. The `skipWrite` parameter is never used.
* So I moved all the code to `InitIframe`, which simplifies the explanation considerably.
Pre-checks:
Review:
> TINY-9670: Move iframe init code sideways from InitContentBody to InitIframe

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/general/Checkbox.ts
- modules/tinymce/src/themes/silver/test/ts/headless/components/checkbox/BasicCheckboxTest.ts
The checkbox would not trigger disable on the label. The checkbox now calls it.
Pre-checks:
Review:
> TINY-4189: Checkbox and containing label now both disabled/enabled

- modules/mcagar/src/main/ts/ephox/mcagar/api/bdd/TinyUiActions.ts
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/core/complex/BespokeNumberInput.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/NumberInputTest.ts
Related Ticket: TINY-9725
tap on `fontinputsize`'s buttons were not managed
Pre-checks:
Review:
> TINY-9725: manage tap for `fontinputsize`'s buttons

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/searchreplace/main/ts/ui/Dialog.ts
- modules/tinymce/src/plugins/searchreplace/test/ts/browser/SearchReplaceDialogTest.ts
- modules/tinymce/src/plugins/searchreplace/test/ts/module/test/Utils.ts
Related Ticket: TINY-9704
* Fix hiding the inline alert in the "Search and Replace" dialog when the search preferences are changed.
Pre-checks:
Review:
> TINY-9704: Fix hiding the inline alert in Search and Replace dialog

- modules/bridge/src/main/ts/ephox/bridge/components/dialog/Tree.ts
- modules/oxide/src/less/theme/components/tree/tree-button.less
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/demo/ts/demo/TreeDemo.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/Tree.ts
- modules/tinymce/src/themes/silver/test/ts/headless/components/tree/TreeTest.ts
Related Ticket: TINY-9653
* Add defaultExpandedKeys and onToggleExpand options to Tree component
Pre-checks:
Review:
> TINY-9653: Add defaultExpandedIds and onToggleExpand options to Tree component

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/advlist/main/ts/core/ListUtils.ts
- modules/tinymce/src/plugins/advlist/main/ts/ui/Buttons.ts
- modules/tinymce/src/plugins/advlist/test/ts/browser/AdvlistOptionsAndToolbarTest.ts
Related Ticket: TINY-9680
the problem seems to was caused by the different way that we manage the `makeSetupHandler` in [advlist](https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/plugins/advlist/main/ts/ui/Buttons.ts) versus in the [lists](https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/plugins/lists/main/ts/ui/Buttons.ts#L7-L13), so I simply aligned the two behaviors.
About the test, at the moment there is some strange thing that is going on with the test about the open of the `context toolbar`
- I had to put it as the first `context` because somehow the other test block the opening of the `context toolbar`
- I had to put `inline: true` otherwise it does not work
- I tried to use: `editor.dispatch('contexttoolbar-show', { …
> TINY-9680: context toolbar not showing the correct status for `advlist`

- modules/oxide/src/less/theme/components/tree/tree-button.less
- modules/tinymce/CHANGELOG.md
Related Ticket: TINY-9692
* Added `cursor: default` rule to `.tox-tree__label` class
Pre-checks:
Review:
> TINY-9692: Set the pointer to default arrow instead of text cursor for the Tree component node labels

- modules/oxide/src/less/theme/components/button/button-secondary.less
- modules/oxide/src/less/theme/components/button/button.less
- modules/tinymce/CHANGELOG.md
Related Ticket: TINY-9713
**NOTE:** these changes was in this PR: https://github.com/tinymce/tinymce/pull/8585 , I had to change the name of the branch because this is an hotfix
This fix `--enabled` for `tox-button` and `tox-button--secondary`, I asked for help with CSS to @noxuhax to have a maintainable and well written CSS
Pre-checks:
Review:
> TINY-9713: fix --enabled for tox-button and tox-button--secondary

- modules/alloy/CHANGELOG.md
- modules/alloy/src/main/ts/ephox/alloy/ui/composite/TypeaheadSpec.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/schema/TypeaheadSchema.ts
- modules/alloy/src/test/ts/browser/ui/typeahead/TypeaheadTest.ts
- modules/alloy/src/test/ts/module/ephox/alloy/test/dropdown/TestDropdownMenu.ts
- modules/alloy/src/test/ts/module/ephox/alloy/test/typeahead/TestTypeaheadSteps.ts
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/menus/item/structure/ItemStructure.ts
Related Ticket: TINY-9280
**Description of Changes**:
* Added `id` attribute to menu items
* `aria-activedescendant` of `Typeahead`/`urlinput` is updated to the menu item that is highlighted
Pre-checks:
Review:
> TINY-9280: Screen readers announce the highlighted menu item in typeahead

- modules/oxide/src/less/theme/alien/unknowns.less
- modules/oxide/src/less/theme/components/dialog/dialog.less
- modules/tinymce/CHANGELOG.md
Related Ticket: TINY-9668
~to fix this I added a `max-height` as `vh` to each component of the `dialog`:~
~`tox-dialog__header` -> 15vh - its padding~
~`tox-dialog__content-js` -> 70vh~
~`tox-dialog__footer` -> 15vh - its padding~
~this seems to work, but I'm not sure that we still need this [other fix](https://github.com/tinymce/tinymce/blob/develop/modules/oxide/src/less/theme/components/dialog/dialog.less#L233) for `tox-dialog__body-content`~
to fix scroll problem, the `max-height` of `tox-dialog__body-content` as been changed into a `min` between `650px` (the current value) and `calc(100vh - 110px)`
Pre-checks:
Review:
> TINY-9668: fix dialog's components `max-height` in order to make the content scroll

- modules/bridge/src/main/ts/ephox/bridge/components/dialog/Tree.ts
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/demo/ts/demo/TreeDemo.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/Tree.ts
- modules/tinymce/src/themes/silver/test/ts/headless/components/tree/TreeTest.ts
Related Ticket: TINY-9715
* Selected item in tree component under directory now remains selected after collapsing and re-expanding the directory
Pre-checks:
Review:
> TINY-9715: Selected item in tree component under directory now remains selected after collapsing and re-expanding the directory

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/directionality/main/ts/core/Direction.ts
- modules/tinymce/src/plugins/directionality/test/ts/browser/CommandsTest.ts
Related Ticket: TINY-9662
* Prevents directionality to be applied to noneditable blocks
* Did a bit of refactoring while I was at it
Pre-checks:
Review:
> TINY-9662: Directionality applies to noneditable elements

- modules/tinymce/src/plugins/quickbars/test/ts/browser/ContentEditableTest.ts
Related Ticket: TINY-9759
* Fixefox on Windows started to flake due to a recent change this adds a fix that make sure that the toolbar is hidden before it continues the other tests for the noneditable state.
Pre-checks:
Review:
> TINY-9759: Fixed test flake

- modules/phoenix/package.json
- modules/polaris/package.json
- modules/robin/package.json
Related Ticket: TINY-9654
As a follow-up to the publishes of the rc versions of phoenix, polaris, and robin to NPM
* Keep package.json up to date and add tags that lerna can identify
* Tags added: `@ephox/phoenix@8.1.0-alpha.0`, `@ephox/polaris@6.1.0-alpha.0`, `@ephox/robin@10.1.0-alpha.0`
Pre-checks:
Review:
> TINY-9654: Update package.json of phoenix, polaris, and robin to current alpha versions

- modules/bridge/src/main/ts/ephox/bridge/components/dialog/DialogFooterButton.ts
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/code/main/ts/ui/Dialog.ts
- modules/tinymce/src/themes/silver/main/ts/ui/general/Button.ts
Related Ticket: TINY-9757
now `icon` field for `togglebutton`s is not mandatory
Pre-checks:
Review:
> TINY-9757: now `icon` field for `togglebutton`s is not mandatory

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/core/complex/BespokeNumberInput.ts
- modules/tinymce/src/themes/silver/main/ts/ui/core/complex/FontSizeBespoke.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/NumberInputTest.ts
Related Ticket: TINY-9754
possible solutions to avoid that inserting a value with an invalid unit the value will be set to `0pt` (or any other default unit)
1. a mechanism that reverses it to the previous value.
2. check what value the user is trying to insert and add the default unit
I implemented the first one because the second one has these 2 problems:
- value: `abc` -> no number so back to the previous default.
- from `16pt` to `1emm` -> probably here the intention of the user would have been to go to `1em` but we cannot know that so we would convert it to `1pt` which is far away from the user intention.
**Other Change:**
- put a `defautlValue` different from `0` to cover other possible edge cases with a default that makes "more sense"
Pre-checks:
Review: …
> TINY-9754: now fontsizeinput revert to old value instead of setting a default value

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/toolbar/CommonToolbar.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/ToolbarBottomTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/InlineToolbarDrawerFloatingPositionTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/ToolbarDrawerToggleTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/view/ViewTest.ts
- modules/tinymce/src/themes/silver/test/ts/module/MenuUtils.ts
https://ephocks.atlassian.net/browse/TINY-9629
Rename the Toolbar "More..." button to "Toggle additional toolbar buttons."
Pre-checks:
Review:
> TINY-9629: Improve 'more' menu button announcement for people using screen readers

- modules/tinymce/CHANGELOG.md
Related Ticket: TINY-9772
* Move TINY-8872 changelog entry from 6.3.0 to 6.4.0, as TINY-8872 was released as part of 6.4
Pre-checks:
Review:
> TINY-9772: Move TINY-8872 changelog entry from 6.3.0 to 6.4.0

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/keyboard/EnterKey.ts
- modules/tinymce/src/core/test/ts/browser/keyboard/CaretAfterHangulTest.ts
- modules/tinymce/src/core/test/ts/browser/keyboard/CursorAfterHangulTest.ts
Related Ticket: TINY-9746
On iOS Safari, if the cursor is after a Hangul (Korean) character when the Enter key is pressed:
* On keydown, save a bookmark and add an undo level. Do not prevent default to allow native Enter keypress to fire.
* On keyup, undo the effects of the native Enter keypress and execute our own Enter key handler
This is because iOS Safari composes Hangul characters by deleting the previous partial character and inserting the composed character.
* Without the native Enter keypress event being fired, iOS Safari will attempt to compose across our custom newline by deleting it and inserting the composed character on the previous line
Pre-checks:
Review:
> TINY-9746: Add iOS Safari workaround to prevent Hangul (Korean) characters from merging onto previous line after pressing Enter to insert newline

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/keyboard/DeleteBackspaceKeys.ts
- modules/tinymce/src/core/main/ts/undo/Setup.ts
Related Ticket: TINY-8910
* Added undo level when pressing cmd+backspace on Mac
* Restore correct caret position after pressing ctrl+backspace/delete on Windows
Pre-checks:
Automatic testing for this case is next to impossible so we need to rely on manual QA for this one.
Review:
> TINY-8910: Command+Delete and Ctrl+Delete do not trigger undo level correctly

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/commands/LinkCommands.ts
- modules/tinymce/src/core/test/ts/browser/FormattingCommandsTest.ts
Related Ticket: TINY-9739
* Prevent the `unlink` command from being executed on noneditable selections.
Pre-checks:
Review:
> TINY-9739: Unlink button/command should not work in noneditable contexts

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/dom/ScrollIntoView.ts
- modules/tinymce/src/core/test/ts/browser/dom/ScrollIntoViewTest.ts
Related Ticket: TINY-9747
now `scrollToMarker` use native `scrollIntoView` instead of calculating the new position
Pre-checks:
Review:
> TINY-9747: fix scroll when is possible to scroll horizontally

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/fmt/ApplyFormat.ts
- modules/tinymce/src/core/main/ts/fmt/MatchFormat.ts
- modules/tinymce/src/core/main/ts/fmt/RemoveFormat.ts
- modules/tinymce/src/core/test/ts/browser/FormatterApplyTest.ts
- modules/tinymce/src/core/test/ts/browser/FormatterCheckTest.ts
- modules/tinymce/src/core/test/ts/browser/fmt/RemoveFormatTest.ts
Related Ticket: TINY-9678
* Prevents formatting api calls from being executed if the selection is noneditable
* Returns `false` if the formatting `canApply` is executed on noneditable selections.
Pre-checks:
Review:
> TINY-9678: CEF <p> tag element inside CEF root, apply's formatting to CET <p> element

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/dom/ControlSelection.ts
- modules/tinymce/src/models/dom/test/ts/browser/table/ResizeTableTest.ts
- modules/tinymce/src/models/dom/test/ts/browser/table/UnmergeCellTableResizeTest.ts
The editor will now require to be in focus before it adds the resize handles
Pre-checks:
Review:
> TINY-9748: Do not add resizehandles if editor is not in focus.

- modules/oxide/package.json
https://ephocks.atlassian.net/browse/TINY-9719
Update prism packages from devDependencies to `dependencies` in oxide
Pre-checks:
Review:
> TINY-9719: Address premium skin deployment issues due to prismjs dependency being misplaced as a dev dependency

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/quickbars/main/ts/insert/Picker.ts
- modules/tinymce/src/themes/silver/main/ts/ui/toolbar/button/ToolbarButtons.ts
Related Ticket: TINY-9769
* on Chrome `focusin` event is fired before `change` fileinput event, so the `focusin` handler is scheduled 1 sec later
* requires manual testing
Pre-checks:
Review:
> TINY-9769: Regression: quickimage button no longer works

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/EditorUpload.ts
- modules/tinymce/src/core/test/ts/browser/EditorUploadTest.ts
Related Ticket: TINY-9696
Avoid leaving p-blocks empty and add padding if needed.
Pre-checks:
Review:
> TINY-9696: Add padding when removing elements if required.

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/html/DomParser.ts
- modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts
Related Ticket: TINY-9761
* Treats transparent blocks as blocks when removing white space between the elements.
Pre-checks:
Review:
> TINY-9761: Paragraph added between two block anchors

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/html/Schema.ts
- modules/tinymce/src/core/test/ts/browser/html/SchemaTest.ts
Related Ticket: TINY-9768
* updated html4 schema for the mentioned elements to have only phrasing content as child elements
Pre-checks:
Review:
> TINY-9768: HTML4 schema incorrectly allows non-inline children in <caption>, <address>, and <dt> elements

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/directionality/main/ts/core/Direction.ts
- modules/tinymce/src/plugins/directionality/test/ts/browser/DirectionStyleTest.ts
Related Ticket: TINY-9314
* Directionality plugin adds an inline `direction` style if the `dir` attribute has been taken precedence by either an inline `direction` style, or a `direction` style from the stylesheet
* Clean up `dir` attribute removal logic
Pre-checks:
Review:
> TINY-9314: Make Directionality plugin work with direction CSS property

- Jenkinsfile
Migrate TinyMCE build process to containers
Related Ticket: TINY-9251
* Use a node container for building. Keep headless-test on mac-headless (`headless-macos`)
Pre-checks:
Review:
> TINY-9251: Use K8s for TinyMCE build process

- modules/tinymce/src/plugins/directionality/test/ts/browser/DirectionStyleTest.ts
Related Ticket: TINY-9314
* Malformed CSS caused `ltr-content` class to not apply correctly in tests
Pre-checks:
Review:
> TINY-9314: Correct malformed CSS in DirectionStyleTest

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/keyboard/CefNavigation.ts
- modules/tinymce/src/core/test/ts/browser/keyboard/ArrowKeysCefTest.ts
Related Ticket: TINY-9565
* Changed so that the arrow keys are reversed if the selection is in a RTL context.
Pre-checks:
Review:
> TINY-9565: Caret cycle when moving caret with arrow keys in inline noneditable span

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/fmt/CaretFormat.ts
- modules/tinymce/src/core/test/ts/browser/fmt/CaretFormatTest.ts
- modules/tinymce/src/core/test/ts/webdriver/keyboard/SpaceKeyTest.ts
Related Ticket: TINY-9310
The problem was that `disableCaretContainer` calls `removeCaretContainerNode` with `moveCaret: false`, and this cause this case:
status: `a |<empty_formatted_tag/>`
press: `b`
result: `ab `
P.S.
FireFox seems to not remove the formatted content
Pre-checks:
Review:
> TINY-9310: fix placing of caret after `disableCaretContainer`

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/html/Schema.ts
- modules/tinymce/src/core/test/ts/browser/html/SchemaTest.ts
Related Ticket: TINY-9805
* Updated HTML4 schema now treats block elements as invalid children for links
Pre-checks:
Review:
> TINY-9805: Prohibit block links in html4 scheme

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/delete/InlineFormatDelete.ts
- modules/tinymce/src/core/test/ts/browser/delete/DeleteCommandsTest.ts
- modules/tinymce/src/core/test/ts/browser/delete/InlineFormatDeleteTest.ts
Would sometimes delete images behind the caret, this shouldn't happen anymore.
Pre-checks:
Review:
> TINY-9807: No longer delete images on the wrong side of the caret

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/accordion/main/ts/core/Actions.ts
- modules/tinymce/src/plugins/accordion/main/ts/core/Utils.ts
- modules/tinymce/src/plugins/accordion/main/ts/ui/Buttons.ts
- modules/tinymce/src/plugins/accordion/test/ts/browser/AccordionPluginTest.ts
* Disabled inserting an accordion into noneditable elements.
Pre-checks:
Review:
> TINY-9760: Disable inserting an accordion into noneditable elements

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/demo/ts/demo/FullDemo.ts
- modules/tinymce/src/core/main/ts/api/OptionTypes.ts
- modules/tinymce/src/core/main/ts/api/Options.ts
- modules/tinymce/src/core/main/ts/init/InitIframe.ts
- modules/tinymce/src/core/test/ts/browser/init/InitDocumentWriteTest.ts
Related Ticket: TINY-9818
* Adds a `init_content_sync` boolean option to use the sync document.write to fill the `iframe` instead of `srcdoc` that is async.
Pre-checks:
Review:
> TINY-9818: Add option to restore document.write behaviour

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/newline/InsertBlock.ts
- modules/tinymce/src/core/main/ts/newline/NewLineAction.ts
- modules/tinymce/src/core/test/ts/browser/newline/InsertNewLineTest.ts
Added newlines where they should be added.
Pre-checks:
Review:
> TINY-9813: Newlines should be added when pressing enter after a table.

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/general/Notification.ts
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialogHeader.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/NotificationManagerImplTest.ts
* Fixed invalid markup in Notification and Dialog close buttons.
Pre-checks:
Review:
> TINY-9849: Fix invalid markup in close buttons

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/models/dom/main/ts/table/actions/Clipboard.ts
- modules/tinymce/src/models/dom/main/ts/table/api/Options.ts
- modules/tinymce/src/models/dom/test/ts/browser/table/PasteTableTest.ts
Related Ticket: TINY-9808
* Add option that disables the table merge on paste override
Pre-checks:
Review:
> TINY-9808: Add option that disables the table merge on paste override

- modules/tinymce/CHANGELOG.md
Related Ticket: TINY-9310
In the [previous PR](https://github.com/tinymce/tinymce/commit/632782ee32cb541f8220ac5070c5740a0394c006#diff-230a1d97cb8ef9885f06853bfe2485250430fb50d576b83537e4fb71abbdf4e4R10) I created the changelog's entry in the wrong place
Pre-checks:
Review:
> TINY-9310: fix changelog's entry position

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/template/main/ts/ui/Dialog.ts
- modules/tinymce/src/plugins/template/test/ts/browser/DialogGetPreviewContentTest.ts
- modules/tinymce/src/plugins/template/test/ts/browser/TemplateSanityTest.ts
Related Ticket: TINY-9867
* Ensure that template html strings containing `<html>` are also parsed before being rendered for preview
* Refactor some tests
Pre-checks:
Review:
> TINY-9867: Parse templates containing <html> tags before rendering for preview

- modules/alloy/CHANGELOG.md
- modules/alloy/src/main/ts/ephox/alloy/positioning/mode/Anchoring.ts
- modules/alloy/src/main/ts/ephox/alloy/positioning/mode/SelectionAnchor.ts
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/quickbars/test/ts/browser/ToolbarPositionTest.ts
- modules/tinymce/src/plugins/quickbars/test/ts/module/test/Utils.ts
- modules/tinymce/src/themes/silver/main/ts/backstage/Anchors.ts
- versions.txt
Related Ticket: TINY-8297
* Quickbar toolbar positioned in the middle of table cell selection if contains more than one table cell selection
Pre-checks:
Review:
> TINY-8297: Quickbar toolbar positioned in the middle of table cell selection if contains more than one table cell

- modules/oxide/src/less/theme/content/mergetags/mergetag.less
- modules/tinymce/CHANGELOG.md
Related Ticket: TINY-9848
* Normalize merge tag highlighting across browsers on right click
Pre-checks:
Review:
> TINY-9848: Normalize merge tag highlighting across browsers on right click

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/Editor.ts
- modules/tinymce/src/core/main/ts/api/EventTypes.ts
- modules/tinymce/src/core/main/ts/api/Events.ts
- modules/tinymce/src/core/main/ts/api/OptionTypes.ts
- modules/tinymce/src/core/main/ts/api/Options.ts
- modules/tinymce/src/core/main/ts/api/commands/ContentCommands.ts
- modules/tinymce/src/core/main/ts/init/InitContentBody.ts
- modules/tinymce/src/core/main/ts/mode/EditableRoot.ts
- modules/tinymce/src/core/main/ts/mode/Readonly.ts
- modules/tinymce/src/core/test/ts/browser/EditableRootTest.ts
- modules/tinymce/src/core/test/ts/browser/api/commands/ContentCommandsTest.ts
Related Ticket: TINY-9839
* Adds the new editable root API according to spec
* Adds the new newdocument_content so that you can set default content when the root is non-editable
Pre-checks:
Review:
> TINY-9839: Adding editable root API

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/modes/Iframe.ts
- modules/tinymce/src/themes/silver/main/ts/ui/general/OuterContainer.ts
- modules/tinymce/src/themes/silver/test/ts/browser/view/ViewTest.ts
Related Ticket: TINY-9814
Having `toolbar_sticky` and `toolbar_sticky_offset` and `autoresize` (to have the editor scrolling), cause a render problem when you switch back from a view to the editor.
the cause is similar to the one in this [PR](https://github.com/tinymce/tinymce/pull/8543).
without the `toolbar_sticky_offset` when you switch back from a view the toolbar is not rendered so it works as intended, but with `toolbar_sticky_offset` the toolbar is rendered immediately so, since the action before refresh is to [show the editor](https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/themes/silver/main/ts/ui/general/OuterContainer.ts#L206-L207), trying to refresh it immediately doesn't take the correct width.
However I see that removing entirely …
> TINY-9814: fix toolbar refresh with `toolbar_sticky`

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/events/InputEvents.ts
- modules/tinymce/src/core/main/ts/paste/Clipboard.ts
- modules/tinymce/src/core/test/ts/browser/paste/ImagePasteTest.ts
- modules/tinymce/src/core/test/ts/browser/paste/InternalClipboardTest.ts
- modules/tinymce/src/core/test/ts/browser/paste/PasteTest.ts
- modules/tinymce/src/core/test/ts/module/test/PasteEventUtils.ts
Related Ticket: TINY-9829
* [Previous PR](https://github.com/tinymce/tinymce/pull/8733) dealt with dispatching "insertFromPaste" `input` event on paste
* This PR dispatches an "insertFromPaste" `beforeinput` event with a dataTransfer property (as per native behaviour on Chrome) before dispatching that `input` event
* Refactor PasteEventUtils module
Pre-checks:
Review:
> TINY-9829: Dispatch "insertFromPaste" `beforeinput` event with `dataTransfer` object on paste

- modules/tinymce/src/core/main/ts/Rtc.ts
- modules/tinymce/src/core/main/ts/fmt/ApplyFormat.ts
- modules/tinymce/src/core/main/ts/fmt/MergeFormats.ts
- modules/tinymce/src/core/main/ts/fmt/RemoveFormat.ts
- modules/tinymce/src/core/main/ts/fmt/ToggleFormat.ts
- modules/tinymce/src/core/test/ts/browser/FormatterApplyTest.ts
- modules/tinymce/src/core/test/ts/browser/FormatterRemoveTest.ts
- modules/tinymce/src/core/test/ts/browser/fmt/RemoveFormatTest.ts
Related Ticket: TINY-9887
This is a follow up to TINY-9678 added the `selection.isEditable` check to the wrong function since they were very confusingly named `applyFormat` in the `ApplyFormat` module but `remove` in the `RemoveFormat` module but the `RemoveFormat` had a function that was called `removeFormat` but was not the opposite of the `applyFormat` function. So a refactored it now so that it makes more sense and is the same internal API. But also fixed a few regressions.
* Fixed regression with remove format being a noop if custom node was specified but selection was non editable.
* Fixed regression with apply format being a noop if custom node was specified but selection was non editable.
* Fixed regression with remove format not working in the first or …
> TINY-9887: Fixed formatter API regressions

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/toolbar/CommonToolbar.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/ToolbarBottomTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/InlineToolbarDrawerFloatingPositionTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/SplitFloatingToolbarKeyboardNavigationTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/ToolbarDrawerToggleTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/view/ViewTest.ts
- modules/tinymce/src/themes/silver/test/ts/module/MenuUtils.ts
https://ephocks.atlassian.net/browse/TINY-9629
This revert the changes for https://github.com/tinymce/tinymce/commit/c6196d0f42a067152811fe89285e799eb02f0b28
Pre-checks:
Review:
> TINY-9629: revert change to `more...` button

- modules/tinymce/src/themes/silver/test/ts/browser/skin/OxideColorSwatchMenuTest.ts
Related Ticket: TINY-9904
* Added awaits
* Changed id to class
Pre-checks:
Review:
> TINY-9904: Unhandled rejection in floating promises in OxideColorSwatchMenuTest causing test flakes

- modules/tinymce/src/core/main/ts/api/Editor.ts
Related Ticket: DOC-2029
* Added API docs for the new `setEditableRoot` and `hasEditableRoot` functions
Pre-checks:
Review:
> DOC-2029: Added API docs for setEditableRoot/hasEditableRoot

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/media/main/ts/core/UrlPatterns.ts
- modules/tinymce/src/plugins/media/test/ts/atomic/UrlPatternsTest.ts
Related Ticket: TINY-9830
* Add support for `h` parameter for vimeo video url in the Media plugin
Pre-checks:
Review:
> TINY-9830: Add support for `h` parameter for vimeo video url in the Media plugin

- modules/tinymce/src/plugins/help/test/ts/browser/KeyboardNavTabI18nTest.ts
Related Ticket: TINY-9633
* Add test for fallback when invalid language code is specified
Pre-checks:
Review:
> TINY-9633: Add test for fallback when invalid language code is specified

- modules/tinymce/src/plugins/help/main/ts/ui/KeyboardNavTabI18n.ts
- modules/tinymce/src/plugins/help/test/ts/browser/KeyboardNavTabI18nTest.ts
Related Ticket: TINY-9928
* Remove fallback string literal and use loading from English file as fallback
* Add test that fallback is the same as the html loaded from English file
Pre-checks:
Review:
> TINY-9928: Remove fallback string literal and use loading from English file as fallback

- modules/tinymce/src/plugins/help/main/ts/data/PluginUrls.ts
Related Ticket: TINY-9936
* Adds the accordion plugin to the help dialog.
* Not adding a changelog for this since plugin is a new documented plugin so it would just make sense that it is in the help dialog list.
Pre-checks:
Review:
> TINY-9936: Added accordion to help

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/lists/main/ts/actions/ToggleList.ts
- modules/tinymce/src/plugins/lists/main/ts/core/Util.ts
- modules/tinymce/src/plugins/lists/test/ts/browser/ContentEditableFalseActionsTest.ts
Related Ticket: TINY-9823
* Fixes inserting lists if there are elements with `contenteditable=false` in selection. Overrides some of the features introduced in [TINY-9458](https://github.com/tinymce/tinymce/pull/8373) PR.
Pre-checks:
Review:
[TINY-9458]: https://ephocks.atlassian.net/browse/TINY-9458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TINY-9823: Fix inserting lists with noneditable selection

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/content/InsertContentImpl.ts
- modules/tinymce/src/core/main/ts/selection/DetailsElement.ts
- modules/tinymce/src/core/test/ts/browser/selection/DetailsElementTest.ts
Related Ticket: TINY-9885
* Fixed breaking summaries into 2 elements when inserting a table or a horizontal rule inside.
Pre-checks:
Review:
> TINY-9885: Fix breaking summaries into 2 elements

- modules/tinymce/src/core/main/ts/selection/DetailsElement.ts
- modules/tinymce/src/plugins/accordion/test/ts/browser/AccordionPluginTest.ts
- modules/tinymce/src/plugins/accordion/test/ts/module/AccordionUtils.ts
- modules/tinymce/src/plugins/accordion/test/ts/webdriver/AccordionBackspaceDeleteTest.ts
Related Ticket: TINY-9945
* Make sure elements immediately after accordion can be edited using BACKSPACE or DELETE keys as expected (resolve TINY-9884 QA failure/regression). Do not move caret back into accordion if:
* Backspace key + caret is at not at start
* Delete key + element is not empty
* Allow select & delete all content in summary or detail (resolve limitation)
* Refactor boolean condition in DetailsElement module
Pre-checks:
Review:
> TINY-9945: Ensure elements after accordion can be edited by Backspace/Delete as expected and allow select all & delete content in summary/body

- modules/tinymce/src/core/main/ts/selection/DetailsElement.ts
- modules/tinymce/src/plugins/accordion/test/ts/browser/AccordionPluginTest.ts
- modules/tinymce/src/plugins/accordion/test/ts/webdriver/AccordionBackspaceDeleteTest.ts
- modules/tinymce/src/plugins/accordion/test/ts/webdriver/AccordionEnterTest.ts
Related Ticket: TINY-9945, TINY-9946
* Improve non-collapsed selection logic for Backspace/Delete override in Accordions (TINY-9945). This was overlooked in previous PR https://github.com/tinymce/tinymce/pull/8791
* After the improvement above, all key-driven Accordion tests can be converted to webdriver successfully (TINY-9946)
Pre-checks:
Review:
> TINY-9945 & TINY-9946: Improve non-collapsed selection logic for Backspace/Delete override in Accordions and convert key-driven tests to webdriver

- modules/oxide/src/less/theme/components/dialog/dialog.less
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/help/main/ts/ui/Dialog.ts
Related Ticket: TINY-9947
* Reverts the help dialog width change made in TinyMCE 6.4
* Enables word wrap in tab labels
* Disables `flex-shrink` to encourage text to expand
* Sets a `max-width` that approximates the intended width of the tab column
The new design restores readability necessary for the now-translated Keyboard Navigation section, while also preserving the tab width on smaller dialogs.
And to confirm smaller dialogs did not change:
Pre-checks:
Review:
> TINY-9947: Improved help dialog readability in all languages

- modules/oxide/src/less/theme/components/dialog/dialog.less
- modules/tinymce/CHANGELOG.md
Related Ticket: TINY-9956
* #8796 introduced a small regression in tab widths using the thin (mobile) layout.
* To fix, `flex-shrink` and `max-width` had to be added to the individual tab elements, and the `max-width` on the tab column no longer applies in the thin layout.
Pre-checks:
Review:
> TINY-9956: Ensure consistent widths for dialog tabs between wide and thin views

- modules/tinymce/src/core/main/ts/delete/InlineFormatDelete.ts
- modules/tinymce/src/core/main/ts/fmt/CaretFormat.ts
- modules/tinymce/src/core/main/ts/selection/DetailsElement.ts
- modules/tinymce/src/plugins/accordion/test/ts/webdriver/AccordionBackspaceDeleteTest.ts
Related Ticket: TINY-9951
* Implement Safari backspace/delete workaround when caret is in summary to override native behavior of deleting all content in summary including the `<br>` which prevents the summary from being re-focused
* Add tests to cover more cases of backspace/delete in summary and body content, including for collapsed, ranged, and ranged-by-keyboard-shortcut deletions
Pre-checks:
Review:
> TINY-9951: Implement Safari workaround for editing content in Accordion summary using Backspace/Delete

- package.json
- yarn.lock
Related Ticket: TINY-9962
* Upgrade bedrock-server to ^13.4.1
* Deduplicated lockfile using `yarn-deduplicate`
Pre-checks:
Review:
> TINY-9962: Upgrade bedrock-server to ^13.4.1

- modules/tinymce/src/core/main/ts/api/Options.ts
- modules/tinymce/src/core/main/ts/api/html/Schema.ts
- modules/tinymce/src/core/main/ts/dom/NodeType.ts
- modules/tinymce/src/core/main/ts/newline/InsertDetailsNewLine.ts
- modules/tinymce/src/core/main/ts/selection/DetailsElement.ts
- modules/tinymce/src/plugins/accordion/test/ts/browser/AccordionPluginTest.ts
- modules/tinymce/src/plugins/accordion/test/ts/webdriver/AccordionBackspaceDeleteTest.ts
- modules/tinymce/src/plugins/accordion/test/ts/webdriver/AccordionEnterTest.ts
Related Ticket: TINY-9959
* Changed so that details elements gets newlines before/after them like other blocks
* Changed so that summary elements gets padded
* Merged in develop since I ran into out of memory issues
* Fixed enter by checking if all parents are text blocks and they are the last one so div > div > div > p should now work.
* Rewrote backspace delete so that it handles more cases and hopefully easier to understand.
* Fixed tests to that they now all pass at least locally.
* Moved predicates to the NodeType module.
* Removed the `entities: 'raw'` and `extended_valid_elements` overrides for the backspace delete tests so they test the default setup.
Left do do:
* Adding more tests for the backspace/delete cases like for example partial selections like …
> TINY-9959: Delete and enter fixes

- modules/alloy/src/main/ts/ephox/alloy/ui/schema/TypeaheadSchema.ts
Related Ticket: TINY-9897
* No code change
* edits and copy-edits to code comments in `TypeaheadSchema.ts`
Pre-checks:
Review:
~* [ ] Milestone set~
~* [ ] Docs ticket created (if applicable)~
> TINY-9897: edits and copy-edits to code comments in `TypeaheadSchema.ts`

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/Options.ts
- modules/tinymce/src/core/main/ts/api/html/Schema.ts
- modules/tinymce/src/core/main/ts/dom/NodeType.ts
- modules/tinymce/src/core/main/ts/newline/InsertDetailsNewLine.ts
- modules/tinymce/src/core/main/ts/selection/DetailsElement.ts
- modules/tinymce/src/plugins/accordion/main/ts/Plugin.ts
- modules/tinymce/src/plugins/accordion/main/ts/core/Actions.ts
- modules/tinymce/src/plugins/accordion/main/ts/core/FilterContent.ts
- modules/tinymce/src/plugins/accordion/main/ts/core/Identifiers.ts
- modules/tinymce/src/plugins/accordion/test/ts/browser/AccordionPluginTest.ts
- modules/tinymce/src/plugins/accordion/test/ts/browser/FilterContentTest.ts
- modules/tinymce/src/plugins/accordion/test/ts/module/AccordionUtils.ts
- modules/tinymce/src/plugins/accordion/test/ts/webdriver/AccordionBackspaceDeleteTest.ts
- modules/tinymce/src/plugins/accordion/test/ts/webdriver/AccordionEnterTest.ts
Related Ticket: TINY-9959:
* Wrap the accordion (details element) body in a div when editing to prevent selection issues on Chrome
* The second commit was merged from #8811. Thanks @spocke for that
* For the changed files that apply to the wrapping div work see the first commit: https://github.com/tinymce/tinymce/commit/f8f8c4e58356c59ef99785b621a09ddd270a3b59
Pre-checks:
Review:
> TINY-9959: Wrap accordion body in div to prevent selection issues

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/dom/DOMUtils.ts
- modules/tinymce/src/core/main/ts/textpatterns/utils/Utils.ts
- modules/tinymce/src/core/test/ts/browser/textpatterns/ReplacementTest.ts
- modules/tinymce/src/core/test/ts/browser/util/UtilsTest.ts
Related Ticket: TINY-9744
replace text sometime causes removal of spaces, for example in this case:
```
Hello.<strong> world</strong> &nbsp;
```
if we have a pattern that replace `world ` with `World ` after we remove the previous string and replace it we have:
```
Hello.<strong> </strong>World &nbsp;
```
so when we clean-up the `strong` tag will be removed, since it has only a space in it
this is because `applyMatches` uses [removeMarker](https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/core/main/ts/textpatterns/core/InlinePattern.ts#L318-L319) that uses [cleanEmptyNodes](https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/core/main/ts/textpatterns/utils/Utils.ts#L9).
To solve this I made `cleanEmptyNodes` replacing the node with …
> TINY-9744: pattern replacement text sometime causes removal of spaces

- modules/alloy/CHANGELOG.md
- modules/alloy/package.json
- modules/alloy/src/main/ts/ephox/alloy/keying/KeyingModeTypes.ts
- modules/alloy/src/main/ts/ephox/alloy/keying/TabbingTypes.ts
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/test/ts/webdriver/dialogs/IFrameDialogTest.ts
- versions.txt
Related Ticket: TINY-9815
* There are two fake tab stop divs wrapping the iframe element. When the focus is on the component before the iframe the Tab press successfully skips the first fake tab stop div and moves focus to the iframe. However next Tab press does not skip the second tab stop div because there is only keyup event fired on it, as such keydown Tab key rules do not work. The solution is to bind key rules to keyup event but check that focus is currently on tab stop div to avoid duplicated tab handling.
Pre-checks:
Review:
> TINY-9815: Skip fake tab stops from tab navigation flow

- package.json
- yarn.lock
Related Ticket: TINY-9843
* Bump oxide-icons-tools to fix a linting error in oxide-icons
Pre-checks:
Review:
> TINY-9843: Bump oxide-icons-tools

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/paste/Clipboard.ts
- modules/tinymce/src/core/main/ts/paste/Commands.ts
- modules/tinymce/src/core/main/ts/paste/DragDrop.ts
- modules/tinymce/src/core/test/ts/browser/paste/ImagePasteTest.ts
- modules/tinymce/src/core/test/ts/browser/paste/InternalClipboardTest.ts
- modules/tinymce/src/core/test/ts/browser/paste/PasteTest.ts
- modules/tinymce/src/core/test/ts/module/test/PasteEventUtils.ts
- modules/tinymce/src/core/test/ts/webdriver/paste/CopyAndPasteTest.ts
Related Ticket: TINY-9997
* Restore behavior that converts image url to image tag on paste while still allowing firing of simulated input events when default is prevented, as introduced in https://github.com/tinymce/tinymce/pull/8733
Pre-checks:
Review:
> TINY-9997: Restore behavior that converts image url to image tag on paste

- modules/alloy/src/test/ts/browser/behaviour/docking/DockingTest.ts
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/keyboard/InsertSpace.ts
- modules/tinymce/src/core/main/ts/keyboard/SpaceKey.ts
- modules/tinymce/src/core/test/ts/browser/keyboard/SpaceKeyTest.ts
Related Ticket: TINY-9964
* Fixed issue with space key not working inside summary elements in Firefox
Pre-checks:
Review:
> TINY-9964: Fixed issue with pressing space inside summary on firefox

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/lists/main/ts/core/Delete.ts
- modules/tinymce/src/plugins/lists/test/ts/browser/BackspaceDeleteFromBlockIntoLiTest.ts
Related Ticket: TINY-6888
The problem was that when we were in a `li` and the parent of the new caret container is the same `li` we remove the `li` and then we try to use `ToggleList.mergeWithAdjacentLists` we use it on `otherLi.parentNode`, but at that point we already removed `otherLi`.
To solve this now the `otherLi.parentNode` reference is stored in a `cost` before the remove
Pre-checks:
Review:
> TINY-6888: now delete `li` in particular situation doesn't cause error

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/OptionTypes.ts
- modules/tinymce/src/core/main/ts/api/Options.ts
- modules/tinymce/src/core/main/ts/api/html/DomParser.ts
- modules/tinymce/src/core/main/ts/dom/DomSerializerFilters.ts
- modules/tinymce/src/core/main/ts/dom/DomSerializerImpl.ts
- modules/tinymce/src/core/main/ts/dom/RemoveTrailingBr.ts
- modules/tinymce/src/core/main/ts/html/ParserFilters.ts
- modules/tinymce/src/core/main/ts/html/ParserUtils.ts
- modules/tinymce/src/core/main/ts/init/InitContentBody.ts
- modules/tinymce/src/core/test/ts/browser/PadEmptyWithBrTest.ts
- modules/tinymce/src/core/test/ts/browser/dom/SerializerTest.ts
- modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts
Related Ticket: TINY-9861
* The `pad_empty_with_br` option ported back from tinymce5
Pre-checks:
Review:
> TINY-9861: Resurrect the pad_empty_with_br option

- modules/alloy/src/test/ts/browser/behaviour/docking/DockingTest.ts
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/selection/DetailsElement.ts
- modules/tinymce/src/core/test/ts/browser/delete/DetailsDeleteTest.ts
- modules/tinymce/src/plugins/accordion/test/ts/webdriver/AccordionBackspaceDeleteTest.ts
Related Ticket: TINY-9965
* Fixed issue with deleting blocks before/after nested details elements.
* Added more low level tests for details delete code.
* Separated the Safari specific delete in summary code form the rest of the details delete code.
* Various code cleanup.
Pre-checks:
Review:
> TINY-9965: Deleting content within the <details> of a nested accordion, removes nested accordion <summary> content

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/demo/ts/demo/FullDemo.ts
- modules/tinymce/src/core/main/ts/content/InsertContentImpl.ts
- modules/tinymce/src/core/main/ts/html/InvalidNodes.ts
- modules/tinymce/src/core/main/ts/paste/DragDrop.ts
- modules/tinymce/src/core/test/ts/browser/content/InsertContentTest.ts
- modules/tinymce/src/core/test/ts/browser/paste/DragDropSummaryTest.ts
- modules/tinymce/src/core/test/ts/browser/paste/DragDropTransparentsTest.ts
- modules/tinymce/src/core/test/ts/browser/selection/DetailsElementTest.ts
- modules/tinymce/src/core/test/ts/module/test/DragDropUtils.ts
- modules/tinymce/src/core/test/ts/module/test/InputEventUtils.ts
Related Ticket: TINY-9960
* Added the accordion plugin to full featured example
* Changed the prevent splitting of summary to use the way it's done for other elements by unwrapping until it fits.
* Added fixed so drag/drop that will inject back a empty summary if it's removed by drag/drop.
* Fixed issue with drag/drop internally wouldn't remove the dragstart selection for summary and transparent elements.
Pre-checks:
Review:
> TINY-9960: Various fixes for dragging and dropping into or out of summary elements

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/dom/ScrollIntoView.ts
- modules/tinymce/src/core/test/ts/browser/dom/ScrollIntoViewTest.ts
Related Ticket: TINY-9828
To avoid the scroll of the whole content in some cases I revert the logic to the previous version and fix it to avoid the problem that we had with the horizontal scroll.
to fix it, now the left position is calculated as the negative of the left of the editor's body.
Pre-checks:
Review:
> TINY-9828: fix `scrollToMarker` logic

- modules/oxide/src/less/theme/components/anchorbar/anchorbar.less
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/WindowManager.ts
- modules/tinymce/src/themes/silver/main/ts/Render.ts
- modules/tinymce/src/themes/silver/main/ts/backstage/Anchors.ts
- modules/tinymce/src/themes/silver/main/ts/backstage/Backstage.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/WindowManager.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/SilverEditorTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/backstage/BackstageSinkTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/header/HeaderLocationTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/statusbar/StatusbarTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/window/SilverDialogPositioningTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/window/SilverInlineDialogPositionTest.ts
- modules/tinymce/src/themes/silver/test/ts/module/StickyHeaderUtils.ts
- modules/tinymce/src/themes/silver/test/ts/module/TestBackstage.ts
Related Ticket: TINY-9888
* Added new inline dialog type `bottom`, this new inline dialog option allows the inline dialog to be positioned at the bottom of the editor
* See ticket for demo video
Pre-checks:
Review:
> TINY-9888: New `bottom` inline dialog type to position inline dialog at the bottom of the editor

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/html/Styles.ts
- modules/tinymce/src/core/test/ts/browser/html/StylesTest.ts
- modules/tinymce/src/plugins/table/main/ts/ui/TableDialog.ts
- modules/tinymce/src/plugins/table/test/ts/browser/ui/TableDialogTest.ts
Related Ticket: TINY-9843
* Fix border styles in 'data-mce-style` being split into the longhand form after table updates
Pre-checks:
Review:
> TINY-9843: Fix border styles being split into longhand form after table updates

- modules/alloy/src/main/ts/ephox/alloy/api/ui/ModalDialog.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/types/ModalDialogTypes.ts
- modules/alloy/src/test/ts/browser/ui/dialog/ModalDialogTest.ts
- modules/bridge/CHANGELOG.md
- modules/bridge/src/main/ts/ephox/bridge/components/dialog/Dialog.ts
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialog.ts
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialogInstanceApi.ts
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverInlineDialog.ts
- modules/tinymce/src/themes/silver/test/ts/browser/skin/OxideBlockedDialogTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/window/SilverDialogFooterTest.ts
- modules/tinymce/src/themes/silver/test/ts/headless/window/WindowManagerTest.ts
Related Ticket: TINY-9996
* Prevent modal and inline dialog footer from rendering if buttons is undefined or empty array
* Result: https://ephocks.atlassian.net/browse/TINY-9996?focusedCommentId=129659
Pre-checks:
Review:
> TINY-9996: Prevent modal and inline dialog footer from rendering if buttons is undefined or empty array

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/WindowManager.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/WindowManager.ts
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverInlineDialog.ts
- modules/tinymce/src/themes/silver/test/ts/browser/window/SilverInlineDialogPersistenceTest.ts
Related Ticket: TINY-9991
* Fire the `doNotDismissYet` event instead of the default `dimissRequested` when the persistent mode is set to true
* This prevents inline dialog from being closed when clicking away from the dialog
Pre-checks:
Review:
> TINY-9991: Implement `persistent` mode for inline dialogs

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/content/InsertContentImpl.ts
- modules/tinymce/src/plugins/table/test/ts/browser/TableRemoveTrailingBrTest.ts
https://ephocks.atlassian.net/browse/TINY-9860
remove `data-mce-bogue`for last table cell
Pre-checks:
Review:
> TINY-9860: Use non-bogus <br> to pad last table cell

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/toolbar/CommonToolbar.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/ToolbarBottomTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/InlineToolbarDrawerFloatingPositionTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/SplitFloatingToolbarKeyboardNavigationTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/ToolbarDrawerToggleTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/view/ViewTest.ts
- modules/tinymce/src/themes/silver/test/ts/module/MenuUtils.ts
[TINY-9629](https://ephocks.atlassian.net/browse/TINY-9629)
update `More...` button tooltip on toolbar to `Reveal or hide additional toolbar items`
Pre-checks:
Review:
[TINY-9629]: https://ephocks.atlassian.net/browse/TINY-9629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TINY-9629: change the `more...` button tooltip

- modules/bridge/CHANGELOG.md
- modules/bridge/src/main/ts/ephox/bridge/components/dialog/Iframe.ts
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/IFrame.ts
- modules/tinymce/src/themes/silver/test/ts/headless/components/iframe/IframeTest.ts
- versions.txt
Related Ticket: TINY-10032
New `streamContent` property to `IframeSpec` which when set to `true`:
* Updates content using `document.write` instead of `srcdoc` to prevent flickering at short update intervals
* Automatically scrolls iframe window to the bottom on each update if the scroll position is at the bottom before the update
Pre-checks:
Review:
> TINY-10032: Allow iframes to update using document.write and autoscroll to bottom on each update

- modules/bridge/CHANGELOG.md
- modules/bridge/src/main/ts/ephox/bridge/components/dialog/Iframe.ts
- modules/oxide/src/less/theme/components/dialog/dialog.less
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/IFrame.ts
- modules/tinymce/src/themes/silver/test/ts/headless/components/iframe/IframeTest.ts
Related Ticket: TINY-10049
* Implement optional border and place behind new `border` property in `IframeSpec`
* Use border styles from https://github.com/tinymce/tinymce/pull/8777/files
* Add focus styles for border
Pre-checks:
Review:
> TINY-10049: Implement optional border to dialog iframe component

- modules/bridge/CHANGELOG.md
- modules/bridge/src/main/ts/ephox/bridge/components/dialog/Label.ts
- modules/oxide/src/less/theme/components/dialog/dialog.less
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/Label.ts
- modules/tinymce/src/themes/silver/test/ts/headless/components/label/LabelTest.ts
Related Ticket: TINY-10058
* Add align property to labels to control text alignment
Pre-checks:
Review:
> TINY-10058: Add align property to labels to control text alignment

- modules/tinymce/src/core/main/ts/api/WindowManager.ts
Related Ticket: TINY-10044
*  Update WindowManager API docs to include missing `params` argument on the `open` method
* Other small adjustments
Pre-checks:
* ~~[X] Changelog entry added~~
* ~~[X] Tests have been added (if applicable)~~
Review:
> TINY-10044: Update WindowManager API docs

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/paste/Clipboard.ts
- modules/tinymce/src/core/main/ts/paste/Commands.ts
- modules/tinymce/src/core/test/ts/browser/paste/PasteTest.ts
TINY-9776: add the possibility to paste images with `mceInsertClipboardContent`
This reverts commit d7cfa10f33a6286ca01e87d929ab7f7c507ee962.
Related Ticket: TINY-9776
Pre-checks:
Review:
> TINY-9776: Revert

- modules/alloy/CHANGELOG.md
- modules/alloy/src/main/ts/ephox/alloy/api/ui/ModalDialog.ts
- modules/alloy/src/main/ts/ephox/alloy/behaviour/blocking/BlockingApis.ts
- modules/alloy/src/main/ts/ephox/alloy/behaviour/blocking/BlockingTypes.ts
- modules/alloy/src/test/ts/browser/ui/dialog/ModalDialogTest.ts
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/Dialogs.ts
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialogCommon.ts
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverInlineDialog.ts
- modules/tinymce/src/themes/silver/test/ts/browser/window/SilverDialogBlockTest.ts
Related Ticket: TINY-10056
* Make dialog blocker only blocks the body and footer
* Clicking on the blocker/dialog header wouldn't focus on the first element in dialog (see ticket for more info)
* Added `isBlocked` API to the `Blocking`.;
Pre-checks:
Review:
> TINY-10056: Make dialog 'x' close button clickable when dialog is busy

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/lists/main/ts/actions/ToggleList.ts
- modules/tinymce/src/plugins/lists/test/ts/browser/ContentEditableFalseActionsTest.ts
Related Ticket: TINY-10000
* It is now possible to create a list in an editable part within a non-editable root
Pre-checks:
Review:
> TINY-10000: It is now possible to create a list in an editable part within a non-editable root

- modules/tinymce/src/themes/silver/main/ts/ui/dialog/IFrame.ts
Related Ticket: TINY-10032
Related Comment: [TINY-10032](https://ephocks.atlassian.net/browse/TINY-10032?focusedCommentId=129839)
Follow-up to https://github.com/tinymce/tinymce/pull/8868:
* Account for nullable documentElement and body when iframe has not finished loading
Pre-checks:
Review:
[TINY-10032]: https://ephocks.atlassian.net/browse/TINY-10032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TINY-10032: Account for nullable documentElement and body when iframe has not finished loading

- modules/oxide/src/less/theme/components/dialog/dialog.less
- modules/tinymce/CHANGELOG.md
Related Ticket: TINY-10059
* Add minimum height to iframe dialog component so it displays larger on `medium` sized inline dialogs
Pre-checks:
Review:
> TINY-10059: Add minimum height to iframe dialog component

- modules/tinymce/src/themes/silver/main/ts/ui/dialog/IFrame.ts
Related Ticket: TINY-10032
* Round scrollTop to prevent isScrollAtBottom being unexpectedly false
Pre-checks:
Review:
> TINY-10032: Round scrollTop to prevent isScrollAtBottom being unexpectedly false

- modules/tinymce/CHANGELOG.md
1. Copy-edits to 6.6-specific entries to bring changelog.md into sync with changelog.adoc and the 6.6 release notes sub-heads.
2. Sub-sections re-arranged to match presentation order of past releases.
DOC-2105: Bring `changelog.md` into sync with `changelog.adoc`
Pre-checks:
Review:
> DOC-2105: Bring `changelog.md` into sync with `changelog.adoc`

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/image/main/ts/ui/Buttons.ts
- modules/tinymce/src/plugins/image/test/ts/browser/ContextMenuTest.ts
Related Ticket: TINY-10016
* Context menu no longer shows up when right-clicking on non-editable image
Pre-checks:
Review:
> TINY-10016: Context menu no longer shows up when right-clicking on non-editable image

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/newline/InsertBlock.ts
- modules/tinymce/src/core/main/ts/newline/NewLineAction.ts
- modules/tinymce/src/core/test/ts/browser/newline/InsertNewLineTest.ts
Let the newline code merge with the previously added work. I initially thought that since the code was very eager to split the parent div, that's what we should do ( and we didn't do it on the previous issue because the body shouldn't be split ). Discussion about it made us agree that even when in divs they should not be split, so we can use the same code.
Pre-checks:
Review:
> TINY-9863: improved newline break detection in divs before a cef

- modules/alloy/CHANGELOG.md
- modules/alloy/src/main/ts/ephox/alloy/api/ui/Toolbar.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/types/ToolbarTypes.ts
Related Ticket: TINY-10003
Here the problem was that switching from a view to the editor calls [this refresh](https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/themes/silver/main/ts/ui/general/OuterContainer.ts#L132) , but in this case we were using [alloy/api/ui/Toolbar](https://github.com/tinymce/tinymce/blob/develop/modules/alloy/src/main/ts/ephox/alloy/api/ui/Toolbar.ts#L45) that didn't have the `refresh` API, and this cause the error.
Pre-checks:
Review:
> TINY-10003: add refresh for `Toolbar`

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/quickbars/main/ts/selection/Toolbars.ts
- modules/tinymce/src/plugins/quickbars/test/ts/browser/SelectionToolbarTest.ts
Broke the original isImage function up to increase readability as it was getting rather long.
Pre-checks:
Review:
> TINY-10054: Quick toolbar would be shown inappropriately

- modules/tinymce/src/themes/silver/main/ts/ui/dialog/IFrame.ts
- modules/tinymce/src/themes/silver/test/ts/headless/components/iframe/IframeTest.ts
Related Ticket: TINY-10078
* Follow-up to https://github.com/tinymce/tinymce/pull/8926
* Since we manually maintain non-end scroll positions on Firefox and Safari on each update, having rapid updates would cause freescrolling to feel stuck. Safari is already throttled to 500ms as part of TINY-10097, so here we throttle Firefox to 200ms to improve freescrolling.
Pre-checks:
Review:
> TINY-10078: Throttle Firefox update interval to 200ms to improve freescrolling

- modules/oxide/src/less/theme/components/collection/collection.less
- modules/oxide/src/less/theme/components/menu/menu.less
- modules/tinymce/CHANGELOG.md
Related Ticket: https://ephocks.atlassian.net/browse/TINY-10017
Menuitem content could before overflow outside of the menu, becoming hidden from view.
We prevent some text from wordbreaking ugly. Restricted this more, to prevent it from affecting the dialog autocompletion.
Pre-checks:
Review:
> TINY-10017: menu items will no longer overflow the menu containing them.

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialogEvents.ts
- modules/tinymce/src/themes/silver/test/ts/browser/window/SilverInlineDialogTest.ts
[TINY-10070](https://ephocks.atlassian.net/browse/TINY-10070)
- applied Luke's suggestion, check if dialog is in the dom with `focusIn` function
- added precautionary test
Pre-checks:
Review:
[TINY-10070]: https://ephocks.atlassian.net/browse/TINY-10070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TINY-10070: Warning is displayed to the console after closing dialog contain an iframe with api.close()

- modules/tinymce/src/themes/silver/main/ts/ui/dialog/IFrame.ts
- modules/tinymce/src/themes/silver/test/ts/headless/components/iframe/IframeTest.ts
Related Ticket: TINY-10078, TINY-10097
* Using `Throttler.first` is flawed as any content updates made during the waiting period is ignored, resulting in content incompleteness towards the end of the stream. This is replaced with `Throttler.adaptable` to resolve the issue.
Pre-checks:
Review:
> TINY-10078 & TINY-10097: Replace Throttler.first with Throttler.adaptable to ensure content completeness

- modules/oxide/src/less/theme/components/dialog/dialog.less
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/alien/RepresentingConfigs.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/BodyPanel.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/ColorPicker.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/CustomEditor.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/Dialogs.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/Dropzone.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/IFrame.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/ImagePreview.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/Label.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/ListBox.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/TabPanel.ts
- modules/tinymce/src/themes/silver/main/ts/ui/general/Button.ts
- modules/tinymce/src/themes/silver/main/ts/ui/general/Checkbox.ts
- modules/tinymce/src/themes/silver/main/ts/ui/general/NavigableObject.ts
- modules/tinymce/src/themes/silver/main/ts/ui/window/DialogChannels.ts
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialog.ts
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialogBody.ts
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialogCommon.ts
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialogEvents.ts
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverInlineDialog.ts
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverUrlDialog.ts
- modules/tinymce/src/themes/silver/test/ts/headless/components/iframe/IframeTest.ts
- modules/tinymce/src/themes/silver/test/ts/webdriver/dialogs/IFrameDialogTest.ts
Related Ticket: TINY-10101
* Borders around the div instead of the iframe, there are some issues on Safari and Firefox the border still shows while the focus has shifted
* Created a channel within the dialog and broadcast the new focus element on `dialogFocusShiftedChannel`, `iframe` in dialog has `Receiving.config` to compare if the iframe has focus to remove the focussed class
Pre-checks:
Review:
> TINY-10101: Fix Safari/Firefox not showing border when focus on iframe

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/core/color/Options.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/color/TextColorSanityTest.ts
Related Ticket: TINY-10098, TINY-9737
* Fixed color_cols not being respected when color_map is defined
* Rounded any color_cols option to nearest integer.
Pre-checks:
Review:
> TINY-10098: Fix color_cols not respected

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/WindowManager.ts
Copy-edits to remove run-on clauses in API comments/documentation
Related Ticket: TINY-10073
* Two run-on sentences in the API documentation no longer run-on.
Pre-checks:
> TINY-10073: copy-edits to remove run-on clauses in API comments/documentation

- modules/tinymce/CHANGELOG.md
Related Ticket: DOC-2158
* Edits to bring changelog.md into sync with changelog.adoc in the docs and with the sub-heads in the forthcoming 6.6.1 Release Notes.
Pre-checks:
Review:
> DOC-2158: edits to bring changelog.md into sync with changelog.adoc, and with the 6.6.1 Release Notes sub-heads

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/help/main/ts/ui/PluginsTab.ts
- modules/tinymce/src/plugins/help/main/ts/ui/VersionTab.ts
- modules/tinymce/src/plugins/help/test/ts/browser/DialogKeyboardNavTest.ts
Related Ticket: TINY-10071
Pre-checks:
Review:
> TINY-10071: improve help dialog keyboard navigation

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/IFrame.ts
- modules/tinymce/src/themes/silver/test/ts/headless/components/iframe/IframeTest.ts
Related Ticket: TINY-10128
* Use a numerical value for Window.scrollTo instead of body.scrollHeight (in case body is `null`)
* On all browsers, wait for `load` before attempting to scroll, as trying to scroll before iframe is loaded does not work
Pre-checks:
Review:
> TINY-10128: For streamContent: true iframes, use numerical value for scrolling and only scroll after iframe load

- modules/tinymce/src/themes/silver/main/ts/ui/dialog/IFrame.ts
- modules/tinymce/src/themes/silver/test/ts/headless/components/iframe/IframeTest.ts
Related Ticket: TINY-10128
Related Comment: https://ephocks.atlassian.net/browse/TINY-10128?focusedCommentId=130527
* Scroll directly after write on Chrome and Firefox instead of waiting for iframe load to prevent scroll jumping
* Revert Firefox throttle back to 200ms
* Reduce the fallback value to 99999999 to minimise the chance future browser changes impact scrolling functionality
Pre-checks:
Review:
> TINY-10128: Scroll directly after write on Chrome and Firefox instead of waiting for iframe load

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/commands/Commands.ts
- modules/tinymce/src/core/main/ts/api/commands/NewBlockCommands.ts
- modules/tinymce/src/core/main/ts/newline/InsertBlock.ts
- modules/tinymce/src/core/main/ts/newline/NewBlock.ts
- modules/tinymce/src/core/main/ts/newline/NewLineUtils.ts
- modules/tinymce/src/core/test/ts/browser/api/commands/NewBlockCommandsTest.ts
Related Ticket: TINY-10022
* Added two new commands for inserting new empty block before / after current position.
Pre-checks:
Review:
> TINY-10022: insert new block commands

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/util/Quirks.ts
- modules/tinymce/src/core/test/ts/browser/delete/CefDeleteTest.ts
Related Ticket: TINY-10011
* The issue is that on `Backspace` key pressing the editor prunes redundant formatting elements without text. In doing so the call `dom.isEmpty(body)` returns true even if the body has an empty CET element. The solution is to provide an additional check for such en empty preserved elements. The attempt to upgrade the `dom.isEmpty` function to treat such CET element as a `nonEmptyElement` failed. In some places we need `dom.isEmpty(cetElm)` returns true for activating padding empty blocks.
Pre-checks:
Review:
> TINY-10011: Preserve empty CET from pruning

- modules/phoenix/src/test/ts/atomic/search/MatchSplitterTest.ts
- modules/phoenix/src/test/ts/atomic/search/SearcherTest.ts
- modules/phoenix/src/test/ts/browser/DomSearchTest.ts
- modules/polaris/CHANGELOG.md
- modules/polaris/src/main/ts/ephox/polaris/search/Sleuth.ts
- modules/polaris/src/test/ts/atomic/api/SearchFindTest.ts
- modules/robin/src/test/ts/atomic/words/IdentifyTest.ts
- versions.txt
Related Ticket: TINY-10062
* Changes are mainly in `Search.findmany` to remove the overlapped indices in the result 
* Other changes are adding some tests for the code change, porting them into the new TDD style and putting assertion messages
Pre-checks:
Review:
> TINY-10062: Remove overlapped indices in `Search.findmany`

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/keyboard/ArrowKeys.ts
- modules/tinymce/src/core/main/ts/keyboard/DetailsNavigation.ts
- modules/tinymce/src/plugins/accordion/test/ts/browser/AccordionNavigationTest.ts
Related Ticket: TINY-9827
* Track the accordion edge position and execute "InsertNewBlockBefore" command on ArrowUp key pressing.
Pre-checks:
Review:
> TINY-9827: Move the cursor out of the accordion at the document edges

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/menus/item/build/InsertTableMenuItem.ts
- modules/tinymce/src/themes/silver/test/ts/browser/skin/OxideTablePickerMenuTest.ts
Related Ticket: TINY-10140
* Updated the table grid menu item cells with individual aria-labels to announce selection with "columns" and "rows".
Pre-checks:
Review:
> TINY-10140: Improve description on label of insert table grid menu item

- modules/oxide/src/less/theme/components/statusbar/statusbar.less
- modules/tinymce/src/themes/silver/main/ts/ui/statusbar/Statusbar.ts
Related Ticket: TINY-10146
* `has()` pseudo-class require a browser config to be set, the changes here to change from CSS to having different classes based on the count of the element in the container
* See ticket for screenshots
Pre-checks:
Review:
> TINY-10146: Refactor statusbar changes in TINY-9379 to use classes in JS

- modules/acid/package.json
- modules/alloy/package.json
- modules/bridge/package.json
- modules/darwin/package.json
- modules/oxide-icons-default/package.json
- modules/oxide/package.json
- modules/phoenix/package.json
- modules/polaris/package.json
- modules/robin/package.json
- modules/snooker/package.json
Related Ticket: TINY-10062
* Manually bumping the released packages to their alpha versions
* Tags added:
* @ephox/acid@5.2.0-alpha.0
* @ephox/alloy@13.1.0-alpha.0
* @ephox/bridge@4.6.0-alpha.0
* @ephox/darwin@8.1.0-alpha.0
* @tinymce/oxide-icons-default@2.6.0-alpha.0
* @tinymce/oxide@2.7.0-alpha.0
* @ephox/phoenix@8.3.0-alpha.0
* @ephox/polaris@6.3.0-alpha.0
* @ephox/robin@10.3.0-alpha.0
* @ephox/snooker@11.1.0-alpha.0
Pre-checks:
Review:
> TINY-10062: Update package.json to current alpha versions

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/delete/DetailsDelete.ts
- modules/tinymce/src/core/test/ts/browser/delete/DetailsDeleteTest.ts
Related Ticket: TINY-10123
* bogus workaround span affects the correct working of `dom.isEmpty` function
Pre-checks:
Review:
> TINY-10123: Fix deleting in `summary` on Safari

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/lists/main/ts/actions/ToggleList.ts
- modules/tinymce/src/plugins/lists/test/ts/browser/ApplyTest.ts
Related Ticket: https://ephocks.atlassian.net/browse/TINY-10136
Restrict the DOMtreeWalker to the correct parent.
Pre-checks:
Review:
> TINY-10136: Prevent list generation to go outside of expected child nodes.

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/util/I18n.ts
- modules/tinymce/src/core/test/ts/browser/util/I18nTest.ts
Related Ticket: TINY-10115
* Where there are multiple case sensitive variants of a translation key, they will now all be kept in the translation object instead of just the lowercase variant
* If there is no lowercase variant present, then we manually add one to ensure that case insensitive matching still works
Pre-checks:
Review:
> TINY-10115: Add support for case sensitive translations

- modules/oxide/src/less/skins/ui/dark/skin.less
- modules/oxide/src/less/theme/components/dialog/dialog.less
- modules/tinymce/CHANGELOG.md
Related Ticket: TINY-10124
* Improved the color contrast between normal, hover and active states
* Added a focus outline around links when using keyboard navigation
* Updated the link colors in the dark skin to be AA compliant.
Pre-checks:
Review:
> TINY-10124: Improved the keyboard focus visibility for links inside dialogs

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/lists/main/ts/actions/ToggleList.ts
- modules/tinymce/src/plugins/lists/test/ts/browser/ApplyListOnCustomList.ts
Related Ticket: TINY-9998 
* Applying bullist to a custom unordered list would turn list into paragraphs instead of a bulleted list.
Pre-checks:
Review:
> TINY-9998: Applying bullist to a custom unordered list would turn list into paragraphs instead of a bulleted list.

- SECURITY.md
- modules/acid/package.json
- modules/alloy/package.json
- modules/bridge/package.json
- modules/darwin/package.json
- modules/oxide-icons-default/package.json
- modules/oxide/package.json
- modules/phoenix/package.json
- modules/polaris/CHANGELOG.md
- modules/polaris/package.json
- modules/robin/package.json
- modules/snooker/package.json
- modules/tinymce/CHANGELOG.md
- versions.txt
Related Ticket: TINY-9879
* Follow release preparation steps in https://internal-docs.tiny.work/internal-docs/1.1/engineering/releases/release-preparation.html
Pre-checks:
Review:
> TINY-9879: Preparation for TinyMCE 6.7.0 release

- modules/tinymce/src/plugins/accordion/test/ts/browser/AccordionNavigationTest.ts
- modules/tinymce/src/plugins/accordion/test/ts/browser/AccordionPluginTest.ts
- modules/tinymce/src/plugins/accordion/test/ts/browser/FilterContentTest.ts
- modules/tinymce/src/plugins/accordion/test/ts/module/AccordionUtils.ts
- modules/tinymce/src/plugins/accordion/test/ts/webdriver/AccordionBackspaceDeleteTest.ts
Related Ticket:  TINY-10154
* Avoid using new line characters in tests
* This is a test refactoring, there is no need to add changelog entry
Pre-checks:
Review:
> TINY-10154: Refactor accordion tests use the `indent: false` option

- modules/bridge/CHANGELOG.md
- modules/bridge/src/main/ts/ephox/bridge/components/dialog/UrlInput.ts
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/image/main/ts/ui/MainTab.ts
- modules/tinymce/src/plugins/image/test/ts/browser/DialogUpdateTest.ts
- modules/tinymce/src/plugins/link/main/ts/ui/Dialog.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/UrlInput.ts
- modules/tinymce/src/themes/silver/test/ts/headless/components/urlinput/UrlInputTest.ts
- modules/tinymce/src/themes/silver/test/ts/webdriver/components/urlinput/UrlInputTest.ts
- versions.txt
Related Ticket: TINY-10155
* Added optional `picker_text` property to `UrlInputSpec` to specify tooltip text of picker button
* Improved picker button tooltips for Image and Link dialogs as per ticket DoD
Pre-checks:
Review:
> TINY-10155: Improve tooltips for urlinput picker button in Image and Link dialogs

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/media/main/ts/ui/Dialog.ts
Related Ticket: TINY-10155
* Added tooltip to Media dialog file picker button, originally not included in the ticket https://ephocks.atlassian.net/browse/TINY-10155?focusedCommentId=131258
Pre-checks:
Review:
> TINY-10155: Add 'Browse files' tooltip to Media dialog file picker button

- modules/oxide/gulpfile.js
Used for testing withing the epic. Not intended for production release at this time. Will not pass tests due to removing the css files.
Pre-checks:
Review:
> TINY-9911: Changed gulp-file to generate javascript files instead of css.

- modules/oxide/src/less/theme/components/dialog/dialog.less
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/WindowManager.ts
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialog.ts
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialogCommon.ts
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverInlineDialog.ts
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverUrlDialog.ts
- modules/tinymce/src/themes/silver/test/ts/browser/window/SilverDialogPositioningTest.ts
Related Ticket: TINY-10209
* Added large dialog class to inline dialogs when large size is specified
* Redialling dialogs with a new size now updates the size class
* Repositioning and re-docking was also necessary after the size of inline dialogs are updated.
* Modal dialogs only need the class to be updated to display correctly
* URL dialogs still do not support updating the size on redial
* Dialog sizes are retained and restored when fullscreen is toggled (api.toggleFullscreen)
* Some cleanup with reused functionality across modal, url, and inline dialogs, now that all sizes are supported and updated
* Fullscreen toggle functionality
* Retrieving and updating the size class.
Pre-checks:
Review:
> TINY-10209: Added support for large inline dialogs and updating dialog size on redial

- modules/acid/src/demo/ts/ephox/acid/demo/Demo.ts
- modules/acid/src/main/ts/ephox/acid/alien/I18n.ts
- modules/acid/src/main/ts/ephox/acid/gui/ColourPicker.ts
- modules/acid/src/main/ts/ephox/acid/gui/components/HueSlider.ts
- modules/acid/src/main/ts/ephox/acid/gui/components/SaturationBrightnessPalette.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/slider/HorizontalModel.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/slider/SliderParts.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/slider/SliderSchema.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/slider/SliderValues.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/slider/TwoDModel.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/slider/VerticalModel.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/types/SliderTypes.ts
- modules/oxide/src/less/theme/components/color-picker/color-picker.less
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/ColorPicker.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/color/ColorPickerSanityTest.ts
Related Ticket: https://ephocks.atlassian.net/browse/TINY-9287
Included the Brightness/Saturation selection area and the Hue slider in the tabbing rotation.
Also added a speed multiplier when pressing shift, as requested.
Pre-checks:
Review:
> TINY-9287: Added brightness/saturation 2D selector and hue slider to tabstop targets, added speed multiplier for pressing shift.

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/lists/main/ts/listmodel/ComposeList.ts
- modules/tinymce/src/plugins/lists/main/ts/listmodel/Entry.ts
- modules/tinymce/src/plugins/lists/main/ts/listmodel/ListsIndendation.ts
- modules/tinymce/src/plugins/lists/main/ts/listmodel/NormalizeEntries.ts
- modules/tinymce/src/plugins/lists/main/ts/listmodel/ParseLists.ts
- modules/tinymce/src/plugins/lists/test/ts/browser/IndentTest.ts
- modules/tinymce/src/plugins/lists/test/ts/browser/ListModelTest.ts
Related Ticket: TINY-10213
the problem here was that in order to merge on Indent a `li` with the successive `li` if that has a list as the first element, we parse that list but ignore the other elements inside the `li`.
to solve this issue I added the siblings in the parsing of that list.
But since our `Entry`'s structure wasn't design only to have entries that are `li` or `lists` so I added a kind of `Entry` that is neither a `li` or a `list` to manage the issue.
Pre-checks:
Review:
> TINY-10213: manage li with a list and then other elements

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/ForceBlocks.ts
- modules/tinymce/src/core/main/ts/SelectionOverrides.ts
- modules/tinymce/src/core/main/ts/api/dom/DOMUtils.ts
- modules/tinymce/src/core/main/ts/api/html/DomParser.ts
- modules/tinymce/src/core/main/ts/api/html/Sanitization.ts
- modules/tinymce/src/core/main/ts/api/html/Schema.ts
- modules/tinymce/src/core/main/ts/api/html/Serializer.ts
- modules/tinymce/src/core/main/ts/dom/NodeType.ts
- modules/tinymce/src/core/main/ts/fmt/FormatUtils.ts
- modules/tinymce/src/core/main/ts/fmt/MergeFormats.ts
- modules/tinymce/src/core/main/ts/fmt/MergeUtils.ts
- modules/tinymce/src/core/main/ts/html/Namespace.ts
- modules/tinymce/src/core/main/ts/html/Sanitization.ts
- modules/tinymce/src/core/main/ts/schema/SchemaElementSets.ts
- modules/tinymce/src/core/main/ts/schema/SchemaLookupTable.ts
- modules/tinymce/src/core/main/ts/selection/ElementSelection.ts
- modules/tinymce/src/core/test/ts/atomic/schema/SchemaElementSetsTest.ts
- modules/tinymce/src/core/test/ts/browser/ForceBlocksTest.ts
- modules/tinymce/src/core/test/ts/browser/content/EditorContentTest.ts
- modules/tinymce/src/core/test/ts/browser/content/InsertContentTest.ts
- modules/tinymce/src/core/test/ts/browser/dom/DomUtilsTest.ts
- modules/tinymce/src/core/test/ts/browser/dom/NodeTypeTest.ts
- modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts
- modules/tinymce/src/core/test/ts/browser/html/NamespaceTest.ts
- modules/tinymce/src/core/test/ts/browser/html/SanitizationTest.ts
- modules/tinymce/src/core/test/ts/browser/html/SchemaTest.ts
- modules/tinymce/src/core/test/ts/browser/html/SerializerTest.ts
Related Ticket: TINY-10237
This is a bit on the big side but you should be able to review it commit by commit.
* Adds opt-in support for SVG elements by just allowing SVG then all children of a SVG is also valid
* Adds support for XLINK in SVGs since that is how you do links in previous version of SVG
* Adds opt-out XSS filtering of SVG elements.
* SVG elements are purified as a separate step since it can have SVG, HTML mixed.
* Treats SVG elements as black boxes anything inside them is just retained as it but filtered though sanitation. 
* Changes a bunch of predicate checks to be isHTMLElement before we could cheat by treating all elements in the editor as HTMLElements after this it's no longer the case it can now contain SVGElement nodes.
* Right now it just …
> TINY-10237: Enable SVG support

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/searchreplace/main/ts/core/TextCollect.ts
- modules/tinymce/src/plugins/searchreplace/test/ts/browser/SearchReplaceInSelectionTest.ts
Related Ticket: TINY-10162
* Uses the new dom.isEditable API so that it will properly handle SVGs and non-editable root elements.
Pre-checks:
Review:
> TINY-10162: Find & replace replaced text inside a non-editable root and svgs

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/Render.ts
- modules/tinymce/src/themes/silver/main/ts/Theme.ts
- modules/tinymce/src/themes/silver/main/ts/modes/Iframe.ts
- modules/tinymce/src/themes/silver/main/ts/modes/Inline.ts
Related Ticket: TINY-10249
To avoid using `render` with `await` and with it having a slow refresh, we also need a second `setToolbar` after `SkinLoaded` event, this is because setting the toolbar and then getting the skin can let the skin to overwrite some styles
Pre-checks:
Review:
> TINY-10249: avoid flickering when remove and put the editor back

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/lists/main/ts/core/Delete.ts
- modules/tinymce/src/plugins/lists/test/ts/browser/BackspaceDeleteTest.ts
Related Ticket: TINY-10133
* Add `isUnwrappable` predicate to prevent the `details` from unwrapping when merging the `li` content on Backspace pressing.
* Noticed the same issue for CEF `li` child, so prevent unwrapping CEF as well.
Pre-checks:
Review:
> TINY-10133: Don't unwrap `details` inside `li`

- modules/tinymce/src/core/main/ts/content/TransparentElements.ts
- modules/tinymce/src/core/main/ts/html/Namespace.ts
- modules/tinymce/src/core/test/ts/browser/content/TransparentElementsTest.ts
Related Ticket: TINY-10272
* This is a pre-release bug so no changelog is needed
* It excludes SVGs by changing the selector to be `a:not(svg a)` so that it doesn't match on `a` elements inside `svg` elements.
Pre-checks:
Review:
> TINY-10272: Fixed bug with data-mce-block being added to anchors inside svg elements

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/dom/Empty.ts
- modules/tinymce/src/core/main/ts/util/Quirks.ts
- modules/tinymce/src/core/test/ts/browser/delete/CefDeleteTest.ts
- modules/tinymce/src/core/test/ts/browser/dom/EmptyTest.ts
Related Ticket: TINY-10010
* Replace in `Quirks.ts` `DomUtils.isEmpty` on `Empty.isEmtpy`
* add to `Empty.isEmpty` function the condition to treat empty CET as a non-empty content
Pre-checks:
Review:
> TINY-10010: Empty.isEmpty should respect empty CET

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/lists/main/ts/core/Selection.ts
- modules/tinymce/src/plugins/lists/test/ts/browser/IndentTest.ts
Related Ticket: TINY-10268
Since our current model for table doesn't allow us to represent this situation:
```
<li>
<something>
<list>
<something-else>
</li>
```
except managing it as a single `li` with some content ignoring the fact that there is a list in it.
to allow us to manage this case we have to change how the `selectedListRoots` is working no more returning the whole tree of lists until the end but stopping at the first list which is in that particular state
Pre-checks:
Review:
> TINY-10268: manage `list` inside an `li` surrounded by 2 not `li` elements

- modules/tinymce/src/core/main/ts/ForceBlocks.ts
- modules/tinymce/src/core/main/ts/api/html/DomParser.ts
- modules/tinymce/src/core/test/ts/browser/ForceBlocksTest.ts
- modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts
Related Ticket: TINY-10273
* Removed empty paragraphs created between SVG root elements.
* Didn't add a changelog since we didn't have official SVG support before.
Pre-checks:
Review:
> TINY-10273: Adjacent SVG block level elements adds extra paragraph

- modules/tinymce/src/core/main/ts/keyboard/KeyboardOverrides.ts
- modules/tinymce/src/core/main/ts/keyboard/PreventNoneditableInput.ts
- modules/tinymce/src/core/test/ts/browser/keyboard/PreventNoneditableInputTest.ts
- modules/tinymce/src/core/test/ts/module/test/InputEventUtils.ts
Related Ticket: TINY-10271
* Fixed delete/backspace but also type over inside SVG elements on Firefox.
* Didn't add a changelog since this is part of the overall support for SVG elements.
Pre-checks:
Review:
> TINY-10271: Backspace/delete can be performed on selected SVG elements in Firefox

- modules/agar/src/main/ts/ephox/agar/keyboard/FakeKeys.ts
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/events/EventUtils.ts
- modules/tinymce/src/core/test/ts/browser/keyboard/KeyboardEventTest.ts
Related Ticket: https://ephocks.atlassian.net/browse/TINY-10263
Backport from develop
Pre-checks:
Review:
* ~~[ ]~~ Milestone set
> TINY-10263: We now keep getModifierState properly accessible. (#9087)

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/lists/main/ts/core/Selection.ts
- modules/tinymce/src/plugins/lists/test/ts/browser/IndentTest.ts
Related Ticket: TINY-10268
cherry-pick of: https://github.com/tinymce/tinymce/pull/9086
Pre-checks:
Review:
> TINY-10268: manage list inside an li surrounded by 2 not li elements

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/NotificationManager.ts
- modules/tinymce/src/core/test/ts/browser/NotificationManagerTest.ts
Related Ticket: https://ephocks.atlassian.net/browse/TINY-10282
Notifications would always take focus to the editor even when not appropriate. We now only take focus if it's in the editor 'area' ( The intention was to move it from the ui to the content, not from anywhere to there )
Pre-checks:
Review:
> TINY-10282: Focus no longer stolen by the editor due to notification closure

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/delete/TableDeleteAction.ts
- modules/tinymce/src/core/main/ts/delete/TableDeleteUtils.ts
- modules/tinymce/src/core/test/ts/browser/delete/TableDeleteTest.ts
Related Ticket: TINY-10254
The problem was that when we have a situation like this:
```
...
<td>
<table id="table1">
<tbody>
<tr>
<td>table</td>
<td>abc</td>
</tr>
</tbody>
</table>
<p>content</p>
</td>
...
```
selecting `content` and `abc` our [getTableDetailsFromRange](https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/core/main/ts/delete/TableDeleteUtils.ts#L23) returns `isSameTable: false` and `isMultiTable: true` because both `content` and `abc` result in a table, but `content` resutls in the parent table and `abc` in `table1` so not the same table.
but doing it when we go to delete the selection we manage it with [this code](https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/core/main/ts/delete/TableDeleteAction.ts#L123-L124) …
> TINY-10254: manage the case when the selection is in multiple table inside a table

- modules/agar/src/main/ts/ephox/agar/api/RealKeys.ts
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/lists/main/ts/core/Delete.ts
- modules/tinymce/src/plugins/lists/test/ts/webdriver/DeleteTest.ts
Related Ticket: TINY-10289
when we are in a situation like this:
```
<ol>
<li>
<span>List 1</span>
</li>
<li>
<h2>Header</h2>
<ol>
<li>List 1-1</li>
</ol>
<p>Place custor at the start of this line and hit backspace.1</p>
</li>
</ol>
```
and we try to use delete or backspace to merge the `p` with the `li` we get an error since we went in a case where we are trying to merge the parent `li` inside the child `li`.
to manage this I added a check that in case of `backspace` from the `p` it moves the current selection container inside the `otherLi` which is the nested `li`
in case of `delete` from `li` we just have to return false since that case is well managed from other part of the code
Pre-checks:
Review:
> TINY-10289: manage delete/backspace involving a nested list

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/OptionTypes.ts
- modules/tinymce/src/core/main/ts/api/Options.ts
- modules/tinymce/src/core/main/ts/api/dom/DOMUtils.ts
- modules/tinymce/src/core/main/ts/api/html/Styles.ts
- modules/tinymce/src/core/main/ts/init/InitContentBody.ts
- modules/tinymce/src/core/test/ts/browser/html/StylesTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/ForceHexColorTest.ts
Related Ticket: [TINY-9819](https://ephocks.atlassian.net/browse/TINY-9819)
Added an editor option called force_hex_color. Defaults to "off".
Setting to "always" will cause applied colors on the "data-mce-style" attribute to be set as HEX values instead of the default RGB (as of a change in v6). This reflects the behavior of applying colors in v5, as every style color was forced to HEX then.
Setting to "rgb_only" will only convert RGB colors, and _not_ RGBA.
Pre-checks:
Review:
Original [pull request](https://github.com/tinymce/tinymce/pull/9076) was closed because I didn't have contributor status yet.
[TINY-9819]: https://ephocks.atlassian.net/browse/TINY-9819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ …
> TINY-9819: Added force_hex_color option

- modules/agar/CHANGELOG.md
- modules/agar/src/main/ts/ephox/agar/api/Clipboard.ts
- modules/agar/src/main/ts/ephox/agar/api/Files.ts
- modules/agar/src/main/ts/ephox/agar/api/RealClipboard.ts
- modules/agar/src/main/ts/ephox/agar/file/BlobReader.ts
- modules/agar/src/main/ts/ephox/agar/file/Files.ts
- modules/agar/src/test/resources/clipboard.html
- modules/agar/src/test/resources/clipboard.txt
- modules/agar/src/test/ts/browser/api/ClipboardTest.ts
- versions.txt
Related Ticket: TINY-10275
* Removed the `RealClipboard.sImportToClipboard` API that uses wink that is problematic for bedrock selenium grid.
* Added new `Clipboard.pPasteUrlItems` to paste URL files as clipboard data items.
Pre-checks:
Review:
> TINY-10275: Replace agar RealClipboard.sImportToClipboard with Clipboard.pPasteUrlItems

- modules/agar/package.json
- modules/alloy/CHANGELOG.md
- modules/alloy/package.json
- modules/mcagar/CHANGELOG.md
- modules/mcagar/package.json
- versions.txt
* Updated agar, mcagar and alloy to major alpha versions since the agar is updated to a major I think it makes sense to bump them all to majors even though technically mcagar and alloy are not breaking their API surface.
Pre-checks:
Review:
> TINY-10275: Updated to alpha versions of mcagar

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/OptionTypes.ts
- modules/tinymce/src/core/test/ts/browser/FontSelectTest.ts
- modules/tinymce/src/themes/silver/main/ts/api/Options.ts
- modules/tinymce/src/themes/silver/main/ts/ui/core/complex/FontFamilyBespoke.ts
Related Ticket: TINY-10290
* Adds a new option to configure the default font stack.
Pre-checks:
Review:
> TINY-10290: Added default_font_stack option

- modules/acid/CHANGELOG.md
- modules/acid/package.json
- versions.txt
Related Ticket: TINY-10275
* Apparently I forgot to commit this change didn't notice that acid is dependent on alloy
* I think we should bump acid to latest major since alloy is a major and agar is a major
Pre-checks:
Review:
> TINY-10275: Bumped alloy dependency

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/selection/NormalizeRange.ts
- modules/tinymce/src/plugins/accordion/main/ts/core/Actions.ts
- modules/tinymce/src/plugins/accordion/main/ts/core/FilterContent.ts
- modules/tinymce/src/plugins/accordion/test/ts/browser/AccordionNavigationTest.ts
- modules/tinymce/src/plugins/accordion/test/ts/browser/DirectionalityTest.ts
Related Ticket:  TINY-10291
* When applying directionality to the `accordion`, the `dir` attribute was modified in both the `summary` and auxiliary `accordion` body `div` element. However, the auxiliary `accordion` body `div` element disappeared during the editor serialization process, resulting in the loss of the applied `dir` value for the `accordion` content.
* When the TinyMCE editor is focused, a selection normalization process refines the editor selection directly to the element contents. Previously, when selecting an `accordion`, only the `summary` and `accordion` body were included in the selection instead of the entire `details` element. To address this, the `details` element has been intentionally excluded from this selection normalization process. …
> TINY-10291: Fix applying directionality on accordion

- modules/tinymce/src/core/test/ts/browser/FontSelectTest.ts
- modules/tinymce/src/themes/silver/main/ts/ui/core/complex/FontFamilyBespoke.ts
Related Ticket: TINY-10290
* The `Arr.forall` becoming `true` for the empty set bites me again. This is a follow up to make sure that we only consider non empty sets. Issue found when trying the fiddle in the QA notes.
Pre-checks:
Review:
> TINY-10290: Fixed issue with empty stacks

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/modes/Iframe.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/menubar/EditorMenubarRenderTest.ts
Related Ticket: TINY-10343
to avoid various render problems caused by a slow load of the skin, all render activities that were on `PostRender` are now on `SkinLoaded`
Pre-checks:
Review:
> TINY-10343: change `iframe.render` from `PostRender` to `SkinLoaded`

- modules/tinymce/src/plugins/lists/main/ts/core/Delete.ts
- modules/tinymce/src/plugins/lists/test/ts/webdriver/DeleteTest.ts
Related Ticket: TINY-10289
this is a fix for a problem with the solution of `TINY-10289` that in case of `backspace` doesn't put the caret in the correct position
Pre-checks:
Review:
> TINY-10289: fix caret position after merging a `p` in an `li` in nested list

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/newline/InsertBlock.ts
- modules/tinymce/src/core/main/ts/newline/InsertLi.ts
- modules/tinymce/src/core/main/ts/newline/NewLineUtils.ts
- modules/tinymce/src/plugins/lists/test/ts/browser/StyleTest.ts
Related Ticket: TINY-10316
Here the problem was that `InsertLi.insert` was creating a new `li` but ignoring the `styles` of the "source li", to solve this now the `new li` will inherit styles of the `li` inside that we pressed enter to create a new li.
NOTE:
since in the case when we are in a case where the "source li" is between to `li` we split the list and we use a new `li` with inside a new `list` this case need to be managed differently
Pre-checks:
Review:
> TINY-10316: inserting `li` via `enter` makes it inherit styles

- modules/tinymce/src/core/main/ts/api/EventTypes.ts
- modules/tinymce/src/core/main/ts/api/dom/Selection.ts
- modules/tinymce/src/core/main/ts/events/EventUtils.ts
- modules/tinymce/src/core/main/ts/keyboard/PreventNoneditableInput.ts
- modules/tinymce/src/core/main/ts/selection/EditableRange.ts
- modules/tinymce/src/core/test/ts/browser/keyboard/PreventNoneditableInputTest.ts
Related Ticket: TINY-10347
* Added fix for delete and backspace into the SVG element.
Pre-checks:
Review:
> TINY-10347: Prevent input events on targets inside svg elements

- modules/tinymce/src/plugins/accordion/main/ts/Plugin.ts
- modules/tinymce/src/plugins/accordion/main/ts/core/Quirks.ts
- modules/tinymce/src/plugins/accordion/test/ts/browser/QuirksTest.ts
Related Ticket: TINY-10177
* On Safari, clicking on the expand arrow of the `details` element sets the selection before the `summary`,
so we override the selection to the beginning of `summary` content 
Pre-checks:
Review:
> TINY-10177: Override selection when clicking Accordion expand arrow on Safari

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/Collection.ts
- modules/tinymce/src/themes/silver/test/ts/browser/skin/OxideCollectionComponentTest.ts
Related Ticket: TINY-10174
* Collection item icons are now retrieved from the icon pack before using the string as a fallback
* This will not affect charmap or emoticons dialogs, as those characters are not registered as icons
Pre-checks:
Review:
> TINY-10174: Allow dialog collection items to use icons from icon pack

- modules/tinymce/CHANGELOG.md
Related Ticket: TINY-10368
* Removing the changelog item about the SVG search & replace fix since that is part of the overall SVG support feature.
Pre-checks:
Review:
> TINY-10368: Removed changelog item about SVG search and replace

- modules/tinymce/src/core/main/ts/delete/DeleteCommands.ts
- modules/tinymce/src/core/main/ts/paste/CutCopy.ts
- modules/tinymce/src/core/test/ts/browser/delete/DeleteCommandsTest.ts
- modules/tinymce/src/core/test/ts/browser/paste/CutNoneditableTest.ts
Related Ticket: TINY-10346
* Fixed so cut doesn't delete inside SVG elements.
* Didn't add a changelog since we never really officially supported SVGs before.
Pre-checks:
Review:
> TINY-10346: Cut inside a SVG with text deletes the selected text

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/Autocompleter.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/autocomplete/AutocompleteAriaTest.ts
Related Ticket: TINY-9393
* Set `aria-owns` and `aria-activedescendant` attributes when autocompleter is shown, and when the focus is shifted, update the `aria-activedescendant` attribute
* For iframe mode, clone a "hidden" autcompleter and insert it into the `editor.getDoc().documentElement) (sibling of the editor body)
* Clean up when autocompleter is closed/no match
* Removed associated attributes
* Removed the cloned element
* See the latest comment in the ticket for video reference
Pre-checks:
Review:
> TINY-9393: Screen readers now announce the active autocompleter item

- modules/acid/src/demo/ts/ephox/acid/demo/Demo.ts
- modules/acid/src/main/ts/ephox/acid/alien/I18n.ts
- modules/acid/src/main/ts/ephox/acid/gui/ColourPicker.ts
- modules/acid/src/main/ts/ephox/acid/gui/components/HueSlider.ts
- modules/acid/src/main/ts/ephox/acid/gui/components/SaturationBrightnessPalette.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/slider/HorizontalModel.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/slider/SliderParts.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/slider/SliderSchema.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/slider/SliderUi.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/slider/SliderValues.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/slider/TwoDModel.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/slider/VerticalModel.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/types/SliderTypes.ts
- modules/oxide/src/less/theme/components/color-picker/color-picker.less
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/ColorPicker.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/color/ColorPickerSanityTest.ts
Related Ticket: TINY-9287
* Reverted the two changes made by TINY-9287 since it was causing a regression with the `editimage` plugin
Pre-checks:
Review:
> TINY-9287: Revert the changes to sliders since it caused a regression with editimage

- SECURITY.md
- modules/acid/CHANGELOG.md
- modules/acid/package.json
- modules/agar/CHANGELOG.md
- modules/agar/package.json
- modules/alloy/CHANGELOG.md
- modules/alloy/package.json
- modules/boss/package.json
- modules/bridge/CHANGELOG.md
- modules/bridge/package.json
- modules/darwin/package.json
- modules/dragster/package.json
- modules/mcagar/CHANGELOG.md
- modules/mcagar/package.json
- modules/oxide/package.json
- modules/phoenix/package.json
- modules/robin/package.json
- modules/snooker/package.json
- modules/sugar/CHANGELOG.md
- modules/sugar/package.json
- modules/tinymce/CHANGELOG.md
- versions.txt
Related Ticket: TINY-9881
* Updated versions and changelogs
* Bumped the oxide version to 2.8 even though there are no changes it still needs to be in sync with the oxide-premium-skins version that we need to release due to the new bundling feature (new .js files in the distribution)
* We bumped the versions of things that depend on sugar to a minor since the sugar version was a minor.
Pre-checks:
Review:
> TINY-9881: Prepare for 6.8.0 Community Release

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/menus/item/build/InsertTableMenuItem.ts
Related Ticket: TINY-10141, TINY-10140
* Fix incorrect translation syntax for table grid announcement text
Pre-checks:
Review:
> TINY-10141: Fix broken translation in table grid announcement

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/api/html/Schema.ts
- modules/tinymce/src/core/test/ts/browser/html/SchemaTest.ts
- modules/tinymce/src/core/test/ts/webdriver/paste/CutTest.ts
Related Ticket: TINY-10385
~`schema.isWrapper` didn't exclude elements that can't be a wrapper element like `comments` and `text`
so `valid_elements: '*[*]'` allow us to try to wrap an element inside such non-wrapper elements~
to avoid breaking change now the check is inside `schema.isInline` and it checks if the name starts with `#`
Pre-checks:
Review:
> TINY-10385: fix `schema.isWrapper` function

- modules/acid/src/demo/ts/ephox/acid/demo/Demo.ts
- modules/acid/src/main/ts/ephox/acid/alien/I18n.ts
- modules/acid/src/main/ts/ephox/acid/gui/ColourPicker.ts
- modules/acid/src/main/ts/ephox/acid/gui/components/HueSlider.ts
- modules/acid/src/main/ts/ephox/acid/gui/components/SaturationBrightnessPalette.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/slider/HorizontalModel.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/slider/SliderParts.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/slider/SliderSchema.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/slider/SliderUi.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/slider/SliderValues.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/slider/TwoDModel.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/slider/VerticalModel.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/types/SliderTypes.ts
- modules/oxide/src/less/theme/components/color-picker/color-picker.less
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/ColorPicker.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/color/ColorPickerSanityTest.ts
Related Ticket: https://ephocks.atlassian.net/browse/TINY-10383
These already-approved things were found to cause a regression with regards to slider behavior and was hurriedly removed prior to release. This re-introduces it, so that the fix can be applied in a separate PR ( as to allow it to be properly reviewd without being mixed in with all of the previous things )
No changes has been made to this code, it is only the previously removed commits.
Pre-checks:
* ~~[ ] Changelog entry added~~
Review:
* ~~[ ] Docs ticket created (if applicable)~~
> TINY-10383: Re-merging the accessibility fixes to the color-picker

- modules/alloy/CHANGELOG.md
- modules/alloy/src/main/ts/ephox/alloy/ui/slider/SliderUi.ts
Related Ticket: https://ephocks.atlassian.net/browse/TINY-10383
Sliders could not be dragged. Combined event listeners into one, and calling the functions one at a time. Dragging now works.
Pre-checks:
Review:
> TINY-10383: Sliders could not be dragged.

- modules/agar/CHANGELOG.md
- modules/agar/src/main/ts/ephox/agar/datatransfer/DataTransfer.ts
- modules/agar/src/test/ts/browser/api/ClipboardTest.ts
- modules/agar/src/test/ts/browser/datatransfer/DataTransferTest.ts
Related Ticket: TINY-10386
* Makes the custom DataTransfer instance in agar be an instance of window.DataTransfer
* Converted test to mocha style
* Added test for this change
Pre-checks:
Review:
> TINY-10386: Fixed so agar DataTransfer is an instance of window.DataTransfer

- modules/alloy/src/main/ts/ephox/alloy/dropdown/DropdownUtils.ts
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/Events.ts
Related Ticket: https://ephocks.atlassian.net/browse/TINY-10310
Blur event was triggered by focusin/focusout passing through the focuscontroller, these were not relayed to the focuscontroller from the ui.
Pre-checks:
Review:
> TINY-10310: Blur events not fired as expected.

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/plugins/lists/main/ts/listmodel/ComposeList.ts
- modules/tinymce/src/plugins/lists/main/ts/listmodel/Entry.ts
- modules/tinymce/src/plugins/lists/main/ts/listmodel/ParseLists.ts
- modules/tinymce/src/plugins/lists/main/ts/listmodel/Util.ts
- modules/tinymce/src/plugins/lists/test/ts/browser/IndentTest.ts
- modules/tinymce/src/plugins/lists/test/ts/browser/RetainContentTest.ts
- modules/tinymce/src/plugins/lists/test/ts/module/ArbList.ts
Related Ticket: TINY-10414
the problem was that `composeList` if the result contains only `EntryNoList` that were be ignored
Pre-checks:
Review:
> TINY-10414: Fix for toggle of nested list with non-list siblings

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/caret/ClosestCaretCandidate.ts
- modules/tinymce/src/core/test/ts/browser/caret/ClosestCaretCandidateTest.ts
Related Ticket: TINY-10380
* Optimized the ClosestCaretCandidate code it would check for a first and second best match even if it already had a good match. It would also re-check something that it already checked. That caused a insane amount of recursion a time complexity of O(2^n) so the checks would double on every level of depth added.
* Added a test that hangs if the code is the old code but is fine now.
Pre-checks:
Review:
> TINY-10380: Optimized the ClosestCaretCandidate

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/caret/ClosestCaretCandidate.ts
- modules/tinymce/src/core/test/ts/browser/caret/ClosestCaretCandidateTest.ts
Related Ticket: TINY-10380
* Backport of ClosestCaretCandidate fix from `develop` to `master` to be included in 6.8.2
Pre-checks:
Review:
> TINY-10380: Optimized the ClosestCaretCandidate (#9214)

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/test/ts/browser/FontSelectCustomTest.ts
- modules/tinymce/src/core/test/ts/browser/FontSelectTest.ts
- modules/tinymce/src/themes/silver/main/ts/ui/core/color/ColorSwatch.ts
- modules/tinymce/src/themes/silver/main/ts/ui/core/complex/AlignBespoke.ts
- modules/tinymce/src/themes/silver/main/ts/ui/core/complex/BespokeSelect.ts
- modules/tinymce/src/themes/silver/main/ts/ui/core/complex/BlocksBespoke.ts
- modules/tinymce/src/themes/silver/main/ts/ui/core/complex/FontFamilyBespoke.ts
- modules/tinymce/src/themes/silver/main/ts/ui/core/complex/FontSizeBespoke.ts
- modules/tinymce/src/themes/silver/main/ts/ui/core/complex/StylesBespoke.ts
- modules/tinymce/src/themes/silver/main/ts/ui/core/complex/utils/Tooltip.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/ToolbarBottomTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/bespoke/DropdownAriaLabelTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/bespoke/SilverBespokeButtonsTest.ts
- modules/tinymce/src/themes/silver/test/ts/module/StickyHeaderStep.ts
Related Ticket: TINY-10426
* Singularize labels of `fontfamily`, `fontsize`, `blocks`, and `styles` bespoke toolbar buttons
* Keep menu item text plural
* Remove string concatenation in Tooltip module
* Add translation tests for bespoke button aria labels
Pre-checks:
Review:
> TINY-10426: Singularize accessible labels of bespoke buttons that append the current value

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/core/complex/AlignBespoke.ts
- modules/tinymce/src/themes/silver/main/ts/ui/core/complex/BespokeSelect.ts
- modules/tinymce/src/themes/silver/main/ts/ui/core/complex/BlocksBespoke.ts
- modules/tinymce/src/themes/silver/main/ts/ui/core/complex/FontFamilyBespoke.ts
- modules/tinymce/src/themes/silver/main/ts/ui/core/complex/FontSizeBespoke.ts
- modules/tinymce/src/themes/silver/main/ts/ui/core/complex/StylesBespoke.ts
- modules/tinymce/src/themes/silver/main/ts/ui/core/complex/utils/Tooltip.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/bespoke/DropdownAriaLabelTest.ts
Related Ticket: TINY-10435
* Convert Align bespoke button tooltips to use concatenated literals since we don't have `Align {0}` as a translation source string but we have `Align left`, `Align right` etc. literals in translations
Pre-checks:
Review:
> TINY-10435: Convert Align bespoke button tooltips to use concatenated literal

- modules/tinymce/src/themes/silver/main/ts/ui/core/complex/AlignBespoke.ts
- modules/tinymce/src/themes/silver/main/ts/ui/core/complex/BespokeSelect.ts
- modules/tinymce/src/themes/silver/main/ts/ui/core/complex/BlocksBespoke.ts
- modules/tinymce/src/themes/silver/main/ts/ui/core/complex/FontFamilyBespoke.ts
- modules/tinymce/src/themes/silver/main/ts/ui/core/complex/FontSizeBespoke.ts
- modules/tinymce/src/themes/silver/main/ts/ui/core/complex/StylesBespoke.ts
Related Ticket: TINY-10446
* Remove unused param in generateSelectItems in BespokeSelect module
Pre-checks:
Review:
> TINY-10446: Remove unused param in generateSelectItems in BespokeSelect module

- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/core/main/ts/caret/FakeCaret.ts
- modules/tinymce/src/core/test/ts/browser/caret/FakeCaretTest.ts
Related Ticket: TINY-10314
by clicking to the left or right of a non-editable `div` in Firefox we get 2 carets.
This seems to happen when we put the selection inside of our fake caret container. When we do so the caret is showed in Firefox but not in Chrome.
To fix it I added a `caret-color: 'transparent'` to our fake care container to don't have the double caret in Firefox
NOTE: I tried to make a test for it, testing the presence of `caret-color: 'transparent'`, I don't know how it make sense, but I didn't find a better check to do :/
Pre-checks:
Review:
> TINY-10314: Fix mutiple caret display on Firefox

- modules/snooker/CHANGELOG.md
- modules/snooker/src/main/ts/ephox/snooker/api/TableOperations.ts
- modules/snooker/src/test/ts/browser/PasteColumnOperationsTest.ts
- modules/snooker/src/test/ts/browser/PasteRowOperationsTest.ts
- modules/snooker/src/test/ts/module/ephox/snooker/test/Assertions.ts
Related Ticket: TINY-6460
As in what's described in the Jira ticket. This fix is just using the new pasted `index` instead. This fix only affects the "pasting after" table operations, but I've put in tests for checking the cursor postions for pasting before _and_ after anyway.
So now all pasting operations have consistent cursor postions, as in placing the cursor in the newly pasted row/column.
Pre-checks:
Review:
GitHub issues (if applicable): https://github.com/tinymce/tinymce/issues/6059
> TINY-6460: Correctly place cursor position for the "paste after" table operations

- modules/jax/package.json
- modules/sugar/src/test/ts/browser/VisibilityTest.ts
- modules/tinymce/Gruntfile.js
- modules/tinymce/package.json
Related Ticket: TINY-10470
* Changed paths for jax so that it passes when you run the tests locally inside that project with say `yarn test`
* Changed the grunt task imports so they pass if you run tests locally inside tinymce using `yarn test`
* Disabled a test for sugar since it flaked on Chrome in manual mode and always fails in headless mode. It checks if the element is invisible by looking at offsetHeight and offsetWidth sometimes it would have that sometimes it wouldn't in firefox it never has that.
* Added `test-manual` to tinymce so that you can run the tests for tinymce only manually like all other things
Pre-checks:
Review:
> TINY-10470: Worked on isolated test runs

- Jenkinsfile
- modules/tinymce/src/core/test/ts/webdriver/keyboard/IframeTabfocusTest.ts
- modules/tinymce/src/plugins/charmap/test/ts/browser/CharmapDialogHeightTest.ts
- modules/tinymce/src/themes/silver/test/ts/headless/components/iframe/IframeTest.ts
Related Ticket: TINY-10559
* This should replace all instances of remote testing with azure and mac nodes
Pre-checks:
Review:
* [- ] Milestone set
* [- ] Docs ticket created (if applicable)
> TINY-10559: Roll back local testing

- modules/tinymce/src/core/test/ts/webdriver/paste/CopyAndPasteTest.ts
Related Ticket: TINY-10556
* Skipping a test on chrome headless did a direct check for headless mode since we don't have a way to detect headless in sand. If we are to add that then it needs to be some form of new check since we want to treat headless chrome the same way we treat chrome unless it's some very specific reason like tests failing.
Pre-checks:
Review:
> TINY-10556: Skipping paste test on chrome headless

- .changes/unreleased/tinymce-TINY-10335-2023-12-21.yaml
- modules/tinymce/src/plugins/fullscreen/main/ts/Plugin.ts
- modules/tinymce/src/plugins/fullscreen/main/ts/api/Api.ts
- modules/tinymce/src/plugins/fullscreen/main/ts/api/Commands.ts
- modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts
- modules/tinymce/src/plugins/fullscreen/main/ts/ui/Buttons.ts
- modules/tinymce/src/plugins/fullscreen/test/ts/browser/FullScreenSinkTest.ts
Related Ticket: TINY-10335
* When the TinyMCE editor operates within a scrollable container, the UI sink – the area displaying editor's interface elements – is constrained by the boundaries of this container. A notable issue arises when toggling to fullscreen mode: while the editor container adopts a 'fixed' position, its UI sink does not, leading to display inconsistencies. This PR addresses the identified issue by dynamically adjusting the UI sink's positioning. When fullscreen mode is activated, the position of the sink is set to 'fixed'.
Pre-checks:
Review:
> TINY-10335: Handle immediate sink on fullscreen toggle

- .changes/unreleased/tinymce-TINY-10439-2024-01-12.yaml
- modules/tinymce/src/plugins/link/main/ts/ui/Controls.ts
- modules/tinymce/src/plugins/link/test/ts/browser/QuickLinkTest.ts
Related Ticket: TINY-10439
`link_default_target` wasn't consider by quicklink
Pre-checks:
Review:
> TINY-10439: read `link_default_target` using quicklink

- .changes/unreleased/tinymce-TINY-10574-2024-01-15.yaml
- modules/tinymce/src/core/main/ts/api/Options.ts
- modules/tinymce/src/core/test/ts/browser/focus/HighlightOnFocusTest.ts
Related Ticket: TINY-10574
switch `highlight_on_focus` default to `true`
Pre-checks:
Review:
> TINY-10574: now `highlight_on_focus` default is `true`

- .changes/unreleased/tinymce-TINY-10475-2024-01-22.yaml
- modules/tinymce/src/themes/silver/main/ts/backstage/TooltipsBackstage.ts
Related Ticket: TINY-10475
* Change delay to show tooltip from `800ms` to `300ms`
Pre-checks:
Review:
> TINY-10475: Change delay before the tooltip to show up

- modules/tinymce/src/core/main/ts/api/Resource.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/ResourceLoadingCssTest.ts
Related Ticket: https://ephocks.atlassian.net/browse/TINY-10378
Minor confidence test. No changelog added as it's internal only.
Pre-checks:
Review:
> TINY-10378: Added confidence tests for the resource css loading functionality

- modules/oxide/src/less/theme/components/revisionhistory/revisionhistory.less
Related Ticket:  TINY-10284
* Update the styles of Revision History UI after Alloy is replaced with Preact
Snapshots of revision history UI with this change:
Pre-checks:
* ~[x] Changelog entry added~
* ~[x] Tests have been added (if applicable)~
* ~[x] Branch prefixed with `feature/`, `hotfix/` or `spike/`~
Review:
> TINY-10284: Update styles of Revision History UI

- .changes/unreleased/tinymce-TINY-10580-2024-01-18.yaml
- modules/tinymce/src/themes/silver/main/ts/ui/header/InlineHeader.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/header/InlineHeaderTest.ts
Related Ticket: TINY-10580
the problem was that if the toolbar has few space and need to be increase in height we need to apply the width before calculating the top to calculate it correctly
Pre-checks:
Review:
> TINY-10580: fix toolbar top calculation when the toolbar height is not standard

- .changes/unreleased/tinymce-TINY-10389-2024-01-23.yaml
- modules/tinymce/src/core/main/ts/util/Quirks.ts
- modules/tinymce/src/core/test/ts/browser/util/QuirksFirefoxTest.ts
Related Ticket: TINY-10389
*  Revert manually dispatching dragend event on drop event in firefox
Pre-checks:
Review:
> TINY-10389: Revert manually dispatching dragend event on drop event in firefox

- modules/tinymce/src/core/test/ts/webdriver/keyboard/IframeTabfocusTest.ts
- modules/tinymce/src/plugins/charmap/test/ts/browser/CharmapDialogHeightTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/bespoke/SilverBespokeButtonsTest.ts
- modules/tinymce/src/themes/silver/test/ts/headless/components/iframe/IframeTest.ts
Related Ticket: TINY-10579
* Fixed the flakey tests and re-enabled those tests.
* The Iframe streaming test was dependent on the `onload` event but was filled at intervals so sometimes onload would have time to trigger other times it would not.
* The `IframeTabfocusTest` test would move the foucs out in the Edge UI and then random tests would fail.
* The `DialogHeightTest` is disabled on Edge using navigator not sand since sand isEdge checks for old pre Chromium edge.
* The `SilverBespokeButtonsTest` will sometimes be off a bit since the SelectionChange event in browsers are thottled so sometimes it fires sometimes it doesn't and the events being monitored is based on that.
Pre-checks:
Review:
> TINY-10579: Re-enabled tests and fixed flakes

- .changes/unreleased/tinymce-TINY-10572-2024-01-29.yaml
- modules/tinymce/src/plugins/emoticons/main/ts/Plugin.ts
- modules/tinymce/src/plugins/emoticons/test/ts/browser/EmoticonsPluginTest.ts
Related Ticket: https://ephocks.atlassian.net/browse/TINY-10572
Another plugin needs to access data from the emoji plugin, it was this or duplicate code or options. The Husky team though this sort of method would be easier.
Pre-checks:
Review:
> TINY-10572: Added a function to the emoji plugin to get the emojis.

- modules/tinymce/src/themes/silver/main/ts/ui/menus/item/build/AutocompleteMenuItem.ts
- modules/tinymce/src/themes/silver/main/ts/ui/menus/menu/SingleMenu.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/tooltip/AutocompleterTooltipTest.ts
- modules/tinymce/src/themes/silver/test/ts/module/TooltipUtils.ts
Related Ticket: TINY-9638
* Add custom tooltip to autocompleter, this is only for `AutocompleteItem` 
* Only when `AutocompleteItem` columns is not equals to 1, then there will be tooltips. When columns equals to 1, they *usually* have text, so tooltip is omitted
* <img width="442" alt="image" src="https://github.com/tinymce/tinymce/assets/111734091/a1530bc0-7883-4961-be33-9bbef9107534">
Pre-checks:
Review:
> TINY-9638: Add custom tooltips to autocompleter

- .changes/unreleased/tinymce-TINY-10561-2024-01-29.yaml
- modules/oxide/src/less/theme/components/advcode/advcode.less
- modules/oxide/src/less/theme/components/view/view.less
Related Ticket: TINY-10561
- added correct styles for `mce-codemirror`
- changed `tox-view__pane` to `position: 'relative'` since the position was the default (`static`), this shouldn't impact other implementation of the view
Pre-checks:
Review:
> TINY-10561: fix CSS for advcode dialog and view mode

- .changes/unreleased/tinymce-TINY-10335-2023-12-21.yaml
- modules/tinymce/CHANGELOG.md
Related Ticket: TINY-10335
This is a follow up of https://github.com/tinymce/tinymce/pull/9316#issuecomment-1922950368
* Removed `.changie` folder.
* Change log updated in a regular way.
Pre-checks:
Review:
> TINY-10335: Handle immediate sink on fullscreen toggle (Remove changie )

- modules/oxide/src/less/theme/components/advcode/advcode.less
- modules/oxide/src/less/theme/theme.less
Related Ticket: TINY-10561
this is just an little fix, I forgot to import the `.less` file in `theme.less` in the previous PR: https://github.com/tinymce/tinymce/pull/9337
Pre-checks:
Review:
> TINY-10561: add import for `advcode.less`

- .changes/unreleased/tinymce-TINY-10581-2024-01-24.yaml
- modules/tinymce/src/themes/silver/main/ts/ui/header/InlineHeader.ts
- modules/tinymce/src/themes/silver/test/ts/module/StickyHeaderStep.ts
Related Ticket: TINY-10581
the problem here is that when we have a vertical scroll and we render the inline editor the second time.
When the position of the `editor-header` is `fixed` and there is a space between the top of the `<body>` and the top of the editor's content the `editor-header` is rendered outside of the  `mainUi.outerContainer.element` so when we calculate the `mainUi.outerContainer.element` width to `restoreAndGetCompleteOuterContainerWidth`, it is 0 and not the `editor-header` width.
To solve this I add a condition to check if the `mainUi.outerContainer.element` has a width lesser that the `minimumToolbarWidth`
Pre-checks:
Review:
> TINY-10581: Fix render for inline editor with vertical scroll

- .changes/unreleased/tinymce-TINY-10451-2024-01-11.yaml
- modules/tinymce/CHANGELOG.md
- modules/tinymce/src/themes/silver/main/ts/ui/skin/Loader.ts
Related Ticket: TINY-10451
* Backport ShadowDOM skin fix from develop to master
Pre-checks:
Review:
* ~~[X] Docs ticket created (if applicable)~~
> TINY-10451: ShadowDOM skin was not imported correctly when using js bundling feature

- lerna.json
- package.json
- yarn.lock
Related Ticket: TINY-10627
* Updated lerna to latest version
* Updated chai to latest 4.x version since 5.x produced some error on Safari
Pre-checks:
Review:
> TINY-10627: Update lerna and chai dev dependencies

- .changes/unreleased/tinymce-TINY-9176-2024-01-26.yaml
- modules/oxide/src/less/skins/ui/dark/skin.less
- modules/oxide/src/less/skins/ui/tinymce-5/skin.less
- modules/oxide/src/less/theme/components/collection/collection.less
- modules/oxide/src/less/theme/components/insert-table-picker/insert-table-picker.less
- modules/oxide/src/less/theme/components/menubar/menubar-button.less
- modules/oxide/src/less/theme/components/statusbar/statusbar.less
- modules/oxide/src/less/theme/components/toolbar-button/toolbar-button.less
- modules/oxide/src/less/theme/components/toolbar-button/toolbar-number-input.less
- modules/oxide/src/less/theme/components/toolbar-button/toolbar-select-button.less
- modules/oxide/src/less/theme/components/toolbar-button/toolbar-split-button.less
- modules/oxide/src/less/theme/globals/global-variables.less
- modules/oxide/src/less/theme/globals/global.less
Related Ticket: TINY-9176
* This accessibility improvement adds a clear outline around the element that has focus, and does not rely solely on color.
* The statusbar uses :focus-visible which makes the outline only show up when navigating using the keyboard. This does not work optimally on Safari, but I deem it an acceptable trade-off to not have the outline show up on click.
* Some ui elements like menu items and list menu has a different technical implementation, interlocking the focus and active states. Therefore they behave slightly differently.
Some examples
Pre-checks:
Review:
https://github.com/tinymce/tinymce/issues/5506
> TINY-9176: improved showing which ui element has focus

- modules/oxide/src/less/theme/components/advcode/advcode.less
Related Ticket: TINY-10561
I found out that in inline mode we have a class that overwrite the `position` so we need a more specific CSS to ensure that the position is `absolute`
Pre-checks:
Review:
> TINY-10561: fix for advcode inline mode

- .changes/unreleased/tinymce-TINY-10646-2024-02-14.yaml
- modules/tinymce/src/core/main/ts/api/NotificationManager.ts
- modules/tinymce/src/core/test/ts/browser/NotificationManagerTest.ts
- modules/tinymce/src/themes/silver/main/ts/alien/NotificationManagerImpl.ts
- modules/tinymce/src/themes/silver/main/ts/ui/general/Notification.ts
- modules/tinymce/src/themes/silver/test/ts/browser/throbber/ThrobberFocusTest.ts
Related Ticket: TINY-10646
* Make all notifications standardized to have a close button by default
* Remove `closeButton` property in NotificationSpec
Pre-checks:
Review:
> TINY-10646: Make all notifications have a close button by default

- .changes/unreleased/tinymce-TINY-10596-2024-02-07.yaml
- modules/bridge/src/main/ts/ephox/bridge/components/dialog/CustomEditor.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/CustomEditor.ts
- modules/tinymce/src/themes/silver/test/ts/headless/components/customeditor/BasicCustomEditorTest.ts
Related Ticket: TINY-10596
I added an `focusBehaviour` for the `customEditor` in dialog, this relay on a `focusSelector` in settings, I tried to use a callback instead of a selector but I get an error, and if I remember correctly we can pass a callback in the specs.
Pre-checks:
Review:
> TINY-10596: add `Tabstopping` to customeditor component

- .changes/unreleased/tinymce-TINY-10611-2024-02-13.yaml
- modules/tinymce/src/core/main/ts/schema/SchemaElementSets.ts
- modules/tinymce/src/core/main/ts/schema/SchemaLookupTable.ts
- modules/tinymce/src/core/test/ts/atomic/schema/SchemaElementSetsTest.ts
Related Ticket: TINY-10611
* Adds `data` and `template` to phrasing element set. This makes the schema more up to date with the current HTML5 spec.
Pre-checks:
Review:
> TINY-10611: Added missing phrasing content elements

- .changes/unreleased/tinymce-TINY-9980-2024-02-13.yaml
- modules/tinymce/src/core/main/ts/api/OptionTypes.ts
- modules/tinymce/src/core/main/ts/api/Options.ts
- modules/tinymce/src/core/main/ts/api/html/Schema.ts
- modules/tinymce/src/core/main/ts/schema/CustomElementsRuleParser.ts
- modules/tinymce/src/core/main/ts/schema/SchemaTypes.ts
- modules/tinymce/src/core/main/ts/schema/SchemaUtils.ts
- modules/tinymce/src/core/main/ts/schema/ValidChildrenRuleParser.ts
- modules/tinymce/src/core/main/ts/schema/ValidElementsRuleParser.ts
- modules/tinymce/src/core/test/ts/atomic/schema/CustomElementsRuleParserTest.ts
- modules/tinymce/src/core/test/ts/atomic/schema/ValidChildrenRuleParserTest.ts
- modules/tinymce/src/core/test/ts/browser/content/CustomElementsTest.ts
- modules/tinymce/src/core/test/ts/browser/html/SchemaTest.ts
Related Ticket: TINY-9980
* Adds a more powerful custom elements spec to the `custom_elements` option and `addCustomElements` API
* Wraps the setup of the schema into a function that gets invoked so that all the functions are defined before that is executed.
* Changes the custom_elements parser slightly so that it doesn't use the inline property instead it bases the block/inline rules based on what it extends so it if it extends a div then it's a block if it extends a span then it's an inline.
Pre-checks:
Review:
> TINY-9980: Added new custom elements spec

- .changes/unreleased/tinymce-TINY-10611-2024-02-13.yaml
- modules/tinymce/src/core/main/ts/schema/SchemaElementSets.ts
- modules/tinymce/src/core/main/ts/schema/SchemaLookupTable.ts
- modules/tinymce/src/core/test/ts/atomic/schema/SchemaElementSetsTest.ts
Related Ticket: TINY-10611
* Made a mistake of adding the `template` element in the previous PR didn't test it enough it more complex than I thought and the ticket is more about aligning more with the HTML5 spec we do already deviate some. So I will reduce the scope to only include the `data` element since `template` will require some additional work in the parser to retain it's inner contents.
Pre-checks:
Review:
> TINY-10611: Removed template from supported elements

- .changes/unreleased/tinymce-TINY-10560-2024-02-15.yaml
- modules/tinymce/src/core/main/ts/newline/InsertBlock.ts
- modules/tinymce/src/core/test/ts/browser/newline/InsertNewLineTest.ts
Related Ticket: TINY-10560
using `editor.selection.setContent('<pre><code>hello</code></pre>')` and then press enter, the problem was that we have this [newBlock](https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/core/main/ts/newline/InsertBlock.ts#L410) undefined.
even though if we are at the end of line [this check](https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/core/main/ts/newline/InsertBlock.ts#L396) returns false.
This is cuased by the fact that [this check](https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/core/main/ts/newline/InsertBlock.ts#L231) doesn't pass because the `container.parentNode` and the `parentBlock` are differend in particular `container.parentNode` is the body and the `parentBlock` is …
> TINY-10560: fix newline after using `selection.setContent` with a `<pre>`

- modules/tinymce/src/themes/silver/main/ts/ui/menus/menubar/Integration.ts
Related Ticket: TINY-10610
Added "Revision History" underneath "Source Code" in the default menu bar.
Pre-checks:
Review:
> TINY-10610: Add revision history menu to the default TinyMCE integration

- .changes/unreleased/tinymce-TINY-8929-2024-02-19.yaml
- modules/bridge/src/main/ts/ephox/bridge/components/content/Autocompleter.ts
Related Ticket: TINY-8929
* Remove the `ch` configuration property
Pre-checks:
Review:
> TINY-8929:  Remove the autocompleter `ch` configuration property.

- .changes/unreleased/tinymce-TINY-10570-2024-02-19.yaml
- modules/alloy/src/main/ts/ephox/alloy/toolbar/SplitToolbarUtils.ts
- modules/tinymce/src/themes/silver/main/ts/ui/header/InlineHeader.ts
Related Ticket: TINY-10570
* Move the setting of inline header width after the toolbar being refreshed on window resize.
* Refine the toolbar width calculation by using getBoundingClientRect when the browser is zoomed
* No unit tests, since it needs browser zooming and window resize. Also the measurement requires the subpixel accuracy - might be flaky.
Pre-checks:
Review:
> TINY-10570: Improve toolbar width recalculation on window resize

- modules/oxide/src/less/theme/components/tooltip/tooltip.less
Related Ticket: TINY-10616
* Add tooltip styles, mainly setting the max width and `overflow-wrap: break-word` to limit the width and ensure consistencies of tooltip. 
Pre-checks:
Review:
> TINY-10616: Add tooltip styles

- .changes/unreleased/tinymce-TINY-10308-2024-02-22.yaml
- modules/tinymce/src/plugins/table/main/ts/ui/TableDialog.ts
- modules/tinymce/src/plugins/table/test/ts/browser/ui/TableDialogStyleWithCssTest.ts
- modules/tinymce/src/plugins/table/test/ts/browser/ui/TableDialogWithoutCssTest.ts
Related Ticket: TINY-10308
When settting table border to '0' or '0px', `border-width` styling is no longer used and only the `border` attribute is set to 0.
Only applies to the table properties dialog and when `table_style_with_css` is set to true.
Pre-checks:
Review:
> TINY-10308: Fix table borders when using `table_style_by_css`

- .changes/unreleased/bridge-TINY-10672-2024-02-21.yaml
- .changes/unreleased/tinymce-TINY-10672-2024-02-21.yaml
- modules/bridge/src/main/ts/ephox/bridge/components/dialog/DialogFooterButton.ts
- modules/tinymce/src/themes/silver/main/ts/ui/general/Button.ts
- modules/tinymce/src/themes/silver/main/ts/ui/view/ViewButtons.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/tooltip/TooltipTest.ts
Related Ticket: TINY-10672
* Change tooltip in `DialogFooterToggleButton` from required to optional
* Revert changes to `ViewButtons.ts` in https://github.com/tinymce/tinymce/pull/9312
Pre-checks:
Review:
> TINY-10672: Change tooltip in `DialogFooterToggleButton` from required to optional

- modules/oxide/src/less/theme/components/revisionhistory/revisionhistory.less
Related Ticket: TINY-10608
* Updated revision history CSS to accommodate the dark skin
Pre-checks:
Review:
> TINY-10608: Update revision history CSS for dark mode

- README.md
- modules/oxide-icons-default/README.md
- modules/oxide/README.md
TINY-10676
Update reference of TinyMCE 6 to 7 in root, `oxide` and `oxide-icons-default`
Pre-checks:
Review:
> TINY-10676: Update reference of TinyMCE 6 to 7

- .changes/unreleased/tinymce-TINY-10658-2024-02-22.yaml
- modules/tinymce/src/core/main/ts/api/dom/ControlSelection.ts
- modules/tinymce/src/core/test/ts/browser/dom/ControlSelectionTest.ts
Related Ticket: TINY-10658
* When resizing with the corner resize handles, remove the height styles from the last row of the control selection ghost element to allow it to visually change height when dragging/resizing
Pre-checks:
Review:
> TINY-10658: Make table ghost element better reflect height changes when resizing

- .changes/unreleased/tinymce-TINY-10617-2024-02-18.yaml
- modules/tinymce/src/plugins/table/main/ts/ui/CellDialog.ts
- modules/tinymce/src/plugins/table/main/ts/ui/CellDialogGeneralTab.ts
- modules/tinymce/src/plugins/table/main/ts/ui/Helpers.ts
- modules/tinymce/src/plugins/table/main/ts/ui/RowDialog.ts
- modules/tinymce/src/plugins/table/test/ts/browser/HelpersTest.ts
- modules/tinymce/src/plugins/table/test/ts/browser/ui/TableCellDialogTest.ts
- modules/tinymce/src/plugins/table/test/ts/browser/ui/TableRowDialogTest.ts
Related Ticket: TINY-10617
* Remove `height` field from the table cell dialog
* Update table row dialog to remove height styles from td/th that are children of the row(s) that have their height changed
Pre-checks:
Review:
> TINY-10617: Update table cell and row dialogs for table row height changes

- .changes/unreleased/tinymce-TINY-10670-2024-02-26.yaml
- modules/tinymce/src/themes/silver/main/ts/ui/menus/menubar/Integration.ts
Related Ticket: TINY-10670
* Added importword, exportpdf and exportword menu items to default file menu
Pre-checks:
Review:
> TINY-10670: Add importword exportpdf and exportword to default file menu

- modules/tinymce/src/core/main/ts/init/LicenseKeyValidation.ts
- modules/tinymce/src/core/test/ts/browser/init/LicenseKeyValidationTest.ts
Related Ticket: TINY-10681
* We are changing the minimal key length to 64 characters to avoid `api_key` confustion
Pre-checks:
Review:
> TINY-10681: Changed minimal key length to 64 on license_key check

- modules/tinymce/src/core/main/ts/api/html/Schema.ts
Related Ticket: TINY-9980 (API docs follow up)
* Adds shallow API docs that references the more complete structure in the `tinymce-docs` section.
* Unsure if we should use `Object` or `Record<string, CustomElementSpec>` here since the types are pascal case for `String` but in TS that should really be `string` so we are not really TS compatible in the type information anyway?
Pre-checks:
Review:
> TINY-9980: Updated API docs for addCustomElements

- modules/tinymce/src/themes/silver/main/ts/ui/core/SimpleControls.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/tooltip/TooltipShortcutTest.ts
Related Ticket: TINY-10696
* Use `access` instead of `alt+shift`
* Tests are updated as well, in mac and windows they're different
Pre-checks:
Review:
> TINY-10696: Use `Access` instead of `Alt+Shift` for heading shortcut in tooltips

- modules/tinymce/src/themes/silver/main/ts/backstage/Backstage.ts
Related Ticket: TINY-10702
* Popup sink and dialog sink has the same z-index, even though tooltip was set to a higher z-index, it is not shown on top of a modal dialog (see ticket for more info)
* Moving tooltip to dialog sink when `ui_mode: split` to address this issue, when `ui_mode: combined` , the tooltip is still rendered in the dialog sink, so it will show on top because the modal and tooltip is within the same sink
Pre-checks:
Review:
> TINY-10702: Render tooltips in `dialog` sink to resolve stacking issue

- .changes/unreleased/tinymce-TINY-9154-2024-02-26.yaml
- modules/tinymce/src/plugins/media/main/ts/core/Service.ts
- modules/tinymce/src/plugins/media/test/ts/browser/DataAttributeTest.ts
- modules/tinymce/src/plugins/media/test/ts/browser/EphoxEmbedTest.ts
- modules/tinymce/src/plugins/media/test/ts/browser/IsCachedResponseTest.ts
- modules/tinymce/src/plugins/media/test/ts/browser/MediaEmbedTest.ts
- modules/tinymce/src/plugins/media/test/ts/browser/SubmitTest.ts
TINY-9154
Change media_url_resolver to use promises
Pre-checks:
Review:
> TINY-9154: Change media_url_resolver to use promises

- modules/oxide/src/less/skins/ui/tinymce-5/skin.less
- modules/oxide/src/less/theme/components/button/button.less
- modules/oxide/src/less/theme/components/collection/collection.less
- modules/oxide/src/less/theme/components/edit-area/edit-area.less
- modules/oxide/src/less/theme/components/form/textfield.less
- modules/oxide/src/less/theme/components/toolbar-button/toolbar-number-input.less
- modules/oxide/src/less/theme/components/toolbar-button/toolbar-select-button.less
- modules/oxide/src/less/theme/components/toolbar-button/toolbar-split-button.less
- modules/oxide/src/less/theme/globals/global-variables.less
Related Ticket: TINY-9681:
* Adressed a couple of instances where the toolbar background background didn't show up for the `tinymce-5` skin.
* The editable area focus outline is turned of for `TinyMCE-5` skins and the premium skins that inherit it.
* Fixed a better variable inheritance for the editable area focus outline color
* Made input field and button focus styles look like the new toolbar button focus outline.
Pre-checks:
Review:
N/a
[TINY-9176]: https://ephocks.atlassian.net/browse/TINY-9176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TINY-9681: Fixed some focus issues related to TinyMCE 5 skin and premium skins

- modules/tinymce/src/core/main/ts/api/Options.ts
Related Ticket: TINY-10535
* Add more popular embed websites to list of `sandbox_iframe_exclusions` to avoid unexpected behaviour
Pre-checks:
Review:
> TINY-10535: Improve list of iframe sandboxing exclusions

- modules/tinymce/src/core/main/ts/api/dom/ControlSelection.ts
- modules/tinymce/src/core/test/ts/browser/dom/ControlSelectionTest.ts
- modules/tinymce/src/models/dom/main/ts/table/api/TableResizeHandler.ts
- modules/tinymce/src/models/dom/test/ts/browser/table/ResizeTableTest.ts
Related Ticket: TINY-10707
* Follow up to TINY-10658 and TINY-10589
* Found that when `table_column_resizing: 'resizetable'` is set and when using either the top-left or bottom-left corner resize handles, only the first column is resized. So just making the behaviour consistent for row resizing as well
Pre-checks:
* ~~[X] Changelog entry added~~ Changelog entries from TINY-10658 and TINY-10589 should be sufficient
Review:
> TINY-10707: Improve table row height reizing when using top corner handles

- modules/tinymce/src/core/main/ts/api/ui/Registry.ts
- modules/tinymce/src/plugins/advlist/main/ts/Plugin.ts
- modules/tinymce/src/plugins/help/main/ts/data/PluginUrls.ts
Related Ticket: TINY-10713
* Change Advanced List plugin name to List Styles
Pre-checks:
Review:
> TINY-10713: Change Advanced List plugin name to List Styles

- modules/tinymce/src/themes/silver/main/ts/ui/general/Button.ts
Related Ticket: TINY-10732
* The `aria-label` still takes tooltip property as the priority, otherwise will fallback to the spec.text for those buttons with visible labels.
Pre-checks:
Review:
> TINY-10732:  Fallback `FooterToggleButton` in dialog to use `spec.text` to set the `aria-label` attribute

- modules/tinymce/src/core/main/ts/keyboard/Autocompleter.ts
Related Ticket: TINY-10717
* Fixed the Esc key not properly closing the autocompleter when in IME
* Fixed the arrow down key re-rendering the autocomplete list
* Fixed issue where the autocompleter would not start in a IME session on other browsers than Safari
Pre-checks:
Review:
> TINY-10717: Fixed Esc and arrow keys and IME not starting

- modules/tinymce/src/core/main/ts/api/ui/Registry.ts
Related Ticket: TINY-10650
* Add a link referencing the custom view doc page to the `addView` API doc
* Update other links which point to 6, to point to 7
Pre-checks:
Review:
> TINY-10650: Add a link referencing custom view doc page to the addView API doc

- modules/oxide/src/less/theme/components/revisionhistory/revisionhistory.less
Related Ticket: TINY-10734
* Update the layout CSS to make sure the revision history diff iframe is not clipped off.
Pre-checks:
Review:
> TINY-10734: Fix the bottom part of the revision history diff iframe hidden behind its container

- modules/oxide/src/less/theme/components/revisionhistory/revisionhistory.less
* Add an outline to indicate when the revisions list is focused which is when there is no revisions
Pre-checks:
Review:
> TINY-10710: Add focus style for the revisions list

- .changes/unreleased/tinymce-TINY-10715-2024-03-14.yaml
- modules/tinymce/src/core/main/ts/keyboard/Autocompleter.ts
Related Ticket: TINY-10715
* Ignore any composition input event if the editor is not in a composing state.
Pre-checks:
Review:
> TINY-10715: Fix for Android Firefox autocompleter bug

- modules/tinymce/src/core/test/ts/browser/content/InsertContentTest.ts
- modules/tinymce/src/core/test/ts/browser/content/insert/CaretPlaceholderTest.ts
- modules/tinymce/src/core/test/ts/browser/content/insert/InsertContentCommandTest.ts
- modules/tinymce/src/core/test/ts/browser/content/insert/InsertContentTest.ts
- modules/tinymce/src/core/test/ts/browser/content/insert/InsertContentWebKitBugs.ts
- modules/tinymce/src/core/test/ts/browser/content/insert/InsertListTest.ts
- modules/tinymce/src/core/test/ts/browser/content/insert/InsertUnsanitizedContentTest.ts
- modules/tinymce/src/core/test/ts/browser/content/insert/SvgTest.ts
Related Ticket: TINY-10370
* Cover undocumented {$caret} placeholder feature of editor.insertContent API.
Pre-checks:
Review:
> TINY-10370: Cover `{$caret}` placeholder feature of editor.insertContent API with tests.

- .changes/unreleased/tinymce-TINY-10797-2024-03-23.yaml
- modules/oxide/src/less/theme/components/tooltip/tooltip.less
Related Ticket: TINY-10797
* Introduced `width` property for tooltips as they are absolute positioned elements to prevent unintended shrinking.
Pre-checks:
Review:
> TINY-10797: Add `width` style to tooltips

- .changes/unreleased/tinymce-TINY-10684-2024-03-23.yaml
- modules/tinymce/src/themes/silver/main/ts/ui/header/InlineHeader.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/header/InlineHeaderTest.ts
Related Ticket: TINY-10684
* Fixed the `max-width` calculation to use the viewport width instead of body width and use `SugarLocation.viewport` instead of `SugarLocation.absolute`, we want to exclude scrolls and calculate the location of the `targetElement`
* Tests are written to assert at least x number of toolbar groups instead of width since it has been flakey, and that should work across different screen sizes.
* Previous behaviour
https://github.com/tinymce/tinymce/assets/111734091/54720d9e-6b84-4afb-983d-6415194ede8a
*  `width: max-content` is set because the toolbar is absolute positioned, and they will `shrink-wrap` to fit their contents unless the dimensions are specified. See: [link](https://www.w3.org/wiki/CSS_absolute_and_fixed_positioning?source=post_pa …
> TINY-10684: Fix inline header `max-width` calculations

- .changes/unreleased/tinymce-TINY-10705-2024-03-25.yaml
- modules/tinymce/src/themes/silver/main/ts/Render.ts
- modules/tinymce/src/themes/silver/main/ts/ui/general/OuterContainer.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/SilverEditorTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/header/HeaderLocationTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/statusbar/StatusbarTest.ts
- modules/tinymce/src/themes/silver/test/ts/module/StickyHeaderUtils.ts
Related Ticket: TINY-10705	
* Moved the status bar out of the editor container, which is a revert in #8164
* Added `toggleStatusBar` function to be called when toggling a view
Pre-checks:
Review:
> TINY-10705: Fix status bar disappearing when the editor's height becomes too short

- modules/tinymce/src/themes/silver/main/ts/ui/header/InlineHeader.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/header/InlineHeaderTest.ts
Related Ticket: TINY-10684
* Previously the calculation adds `bodyMargin` which is incorrect, causing the toolbar have greater `max-width` than available space hence toolbar wraps unnecessarily
* Removed body margin calculation since we are dealing with viewport and the viewport of location of the target element.
* Video reference:
https://github.com/tinymce/tinymce/assets/111734091/7c7cb4b7-7223-41e8-bbea-7b6256137da6
https://github.com/tinymce/tinymce/assets/111734091/1cb4d326-a235-4d20-99f2-dae5d066394f
Pre-checks:
Review:
> TINY-10684: Fix up incorrect `max-width` calculation 

- .changes/unreleased/tinymce-TINY-10488-2024-02-29.yaml
- modules/tinymce/src/plugins/lists/main/ts/actions/ToggleList.ts
- modules/tinymce/src/plugins/lists/main/ts/core/Selection.ts
- modules/tinymce/src/plugins/lists/test/ts/browser/TableInListWithRootDivTest.ts
Related Ticket: TINY-10488
I splitted the behavior for the last condition of [this if](https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/plugins/lists/main/ts/actions/ToggleList.ts#L176)
the previos behavior was:
`* abc` -> `* abc[plugin-bookmark]` -> `<p></p>* abc[plugin-bookmark]` -> `<p>* abc</p>[plugin-bookmark]` -`if`> END
now is:
`* abc` -> `* abc[plugin-bookmark]` -> `<p></p>* abc[plugin-bookmark]` -> `<p>* abc</p>[plugin-bookmark]` -> `<p>* abc[plugin-bookmark]</p>` -> END
P.S. cherry picked from: https://github.com/tinymce/tinymce/pull/9449
Pre-checks:
Review:
> TINY-10488: fix list pattern with `forced_root_block: 'div'`

- .changes/unreleased/tinymce-TINY-10590-2024-03-06.yaml
- modules/tinymce/src/core/main/ts/delete/BlockMergeBoundary.ts
- modules/tinymce/src/core/test/ts/browser/delete/BlockMergeBoundaryTest.ts
Related Ticket: https://ephocks.atlassian.net/browse/TINY-10590
Backport of #9474
Pre-checks:
Review:
> TINY-10590: Tree dom structure could confuse block merge boundary detection

- README.md
- SECURITY.md
- modules/tinymce/README.md
- modules/tinymce/src/core/main/ts/api/EditorManager.ts
- modules/tinymce/src/core/main/ts/api/NotificationManager.ts
- modules/tinymce/src/core/main/ts/api/WindowManager.ts
- modules/tinymce/src/core/main/ts/api/fmt/StyleFormat.ts
- modules/tinymce/src/core/main/ts/api/ui/Registry.ts
- modules/tinymce/src/core/main/ts/api/util/Observable.ts
Related Ticket: TINY-10834
* Changed all readme links
* Changed all JSDoc links since 7 might add new events etc
Pre-checks:
Review:
> TINY-10834: Bumped all docs links from 6 to 7

- modules/tinymce/src/themes/silver/main/ts/ui/header/InlineHeader.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/header/InlineHeaderTest.ts
Related Ticket: TINY-10684
* Preserving the scroll when the toolbar item is focused in the toolbar overflow drawer
https://github.com/tinymce/tinymce/assets/111734091/b7d25a89-c023-4fb5-951b-c4fe243b004d
https://github.com/tinymce/tinymce/assets/111734091/758c2406-af8a-4bd1-b446-c58ffad85c6d
Pre-checks:
Review:
> TINY-10684: The scroll position should be maintained in a horizontal scrollable container

- .changes/unreleased/tinymce-TINY-10590-2024-03-06.yaml
- modules/tinymce/src/core/main/ts/delete/BlockMergeBoundary.ts
- modules/tinymce/src/core/test/ts/browser/delete/BlockMergeBoundaryTest.ts
This reverts commit 32b71078ead06caff327095869777984c518c83d.
Related Ticket: TINY-10590
* Reverted the backspace/delete fix for nested elements.
Pre-checks:
Review:
> TINY-10590: Reverted Tree dom structure could confuse block merge boundary detection

- modules/sugar/src/test/ts/browser/LocationTest.ts
Related Ticket: TINY-10839
* Fun times some of the browsers have updated to Firefox 124 and that fixes an issue that we have a workaround for in the test so we need to change the check to for that range of affected browsers. It only fails on Mac nodes so they have been updated to 124 but the Windows nodes are still on 123.
Once this is approved I will cherrypick this into release/7 that is also affected but this issue.
Pre-checks:
Review:
> TINY-10839: Fixed failing test for Firefox 124

- .changes/unreleased/tinymce-TINY-10602-2024-04-04.yaml
- modules/tinymce/src/core/test/ts/browser/init/EditorInitializationTest.ts
- modules/tinymce/src/core/test/ts/browser/init/ShadowDomEditorTest.ts
- modules/tinymce/src/plugins/importcss/main/ts/core/ImportCss.ts
- modules/tinymce/src/themes/silver/main/ts/ui/skin/Loader.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/backstage/BackstageSinkTest.ts
Related Ticket: TINY-10602
* I swapped premium tests to load the unminified TinyMCE, but it turns out a lot of the skin files still load minified when this happens.
* Some tests had to be updated.
* I wrote a new test for using the suffix in skin URLs.
* I also applied some minor refactoring to the theme loader.
Pre-checks:
Review:
> TINY-10602: Theme loader now respects the suffix when loading skin CSS files

- .changes/unreleased/tinymce-TINY-10813-2024-04-04.yaml
- modules/tinymce/src/core/main/ts/content/TransparentElements.ts
- modules/tinymce/src/core/test/ts/browser/content/TransparentElementsTest.ts
Related Ticket: TINY-10813
* Escaping element names in the query selector so that we don't get an exception thrown if colon is used.
Pre-checks:
Review:
> TINY-10813: Fixed issue with colon characters in custom block elements

- .changes/unreleased/tinymce-TINY-10809-2024-04-08.yaml
- modules/tinymce/src/core/main/ts/html/Namespace.ts
- modules/tinymce/src/core/main/ts/html/Sanitization.ts
- modules/tinymce/src/core/test/ts/browser/ForceBlocksTest.ts
- modules/tinymce/src/core/test/ts/browser/content/insert/NamespaceElementsTest.ts
- modules/tinymce/src/core/test/ts/browser/dom/DomUtilsTest.ts
- modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts
- modules/tinymce/src/core/test/ts/browser/html/NamespaceTest.ts
- modules/tinymce/src/core/test/ts/browser/html/SanitizationTest.ts
Related Ticket: TINY-10809
* Added parsing support for mathml elements similar to SVGs.
Pre-checks:
Review:
> TINY-10809: Add MathML parsing support

- .changes/unreleased/alloy-TINY-10808-2024-04-02.yaml
- .changes/unreleased/tinymce-TINY-10800-2024-04-02.yaml
- .changes/unreleased/tinymce-TINY-10808-2024-04-02.yaml
- modules/alloy/src/main/ts/ephox/alloy/api/ui/ModalDialog.ts
- modules/alloy/src/test/ts/browser/ui/dialog/ModalDialogTest.ts
- modules/tinymce/src/plugins/fullscreen/test/ts/browser/FullScreenPluginTest.ts
- modules/tinymce/src/plugins/table/test/ts/browser/settings/TableGridFalseTest.ts
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialogHeader.ts
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverInlineDialog.ts
- modules/tinymce/src/themes/silver/test/ts/browser/window/SilverDialogAriaLabelTest.ts
- modules/tinymce/src/themes/silver/test/ts/headless/window/SilverDialogReuseTest.ts
- modules/tinymce/src/themes/silver/test/ts/headless/window/WindowManagerAlertTest.ts
- modules/tinymce/src/themes/silver/test/ts/headless/window/WindowManagerConfirmTest.ts
- modules/tinymce/src/themes/silver/test/ts/headless/window/WindowManagerTest.ts
- modules/tinymce/src/themes/silver/test/ts/webdriver/dialogs/DialogFocusTest.ts
Related Ticket: TINY-10800 & TINY-10808
* Dialog title markup changed to use an `h1` element instead of `div`
* Don't think we've used platform detection in alloy, but it requires since the `aria-labelledby` is not announced with  `role="dialog"` so that has been changed to `aria-label` only on MacOS
* Ideally we should still use `aria-labelledby` since the dialog already has a visible label, this is a workaround for dialog title to be announced on MacOS VoiceOver. (See: [Dialog Modal Pattern](https://arc.net/l/quote/pchpomfw))
* Changes only impact MacOS, other screen reader like JAWS and NVDA do support usage of `aria-labelledby` in `role="dialog"`. [Assistive Technology Support](https://arc.net/l/quote/jmovypin) …
> TINY-10808 & TINY-10800: Dialog accessibility fixes, dialog title markup changed to use an `h1` element

- .changes/unreleased/tinymce-TINY-10774-2024-04-08.yaml
- modules/tinymce/src/core/demo/html/full_demo.html
- modules/tinymce/src/plugins/media/main/ts/core/Selection.ts
- modules/tinymce/src/plugins/media/test/ts/browser/VideoMouseEventsTest.ts
Related Ticket: TINY-10774
* Safari bubbles click event out of the video element other browsers do not.
Pre-checks:
Review:
> TINY-10774: Fix for not being able to play video on Safari

- .changes/unreleased/tinymce-TINY-10726-2024-04-09.yaml
- modules/alloy/src/main/ts/ephox/alloy/api/ui/SplitSlidingToolbar.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/schema/SplitSlidingToolbarSchema.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/ToolbarDrawerToggleTest.ts
Related Ticket: TINY-10726
* Added `toggleWithoutFocusing` api to `SplitSlidingToolbar` component
Pre-checks:
Review:
> TINY-10726: Fix `ToggleToolbarDrawer` command in sliding mode

- .changes/unreleased/tinymce-TINY-9932-2024-03-06.yaml
- modules/dragster/src/test/ts/browser/datatransfer/DataTransferTest.ts
- modules/tinymce/src/core/main/ts/schema/GlobalAttributesSet.ts
- modules/tinymce/src/core/test/ts/atomic/schema/GlobalAttributesSetTest.ts
- modules/tinymce/src/core/test/ts/atomic/schema/SchemaLookupTableTest.ts
- modules/tinymce/src/core/test/ts/browser/html/SchemaTest.ts
- modules/tinymce/src/core/test/ts/webdriver/keyboard/SpaceKeyTest.ts
TINY-9932
- Add itemprop, itemscope, and itemtype to HTML5 schema
- Update test
Pre-checks:
Review:
> TINY-9932: Add itemprop, itemscope, and itemtype to HTML5 schema

- modules/tinymce/src/plugins/accordion/test/ts/browser/AccordionContextMenuTest.ts
- modules/tinymce/src/plugins/accordion/test/ts/browser/AccordionMenubarTest.ts
Related Ticket: TINY-9961
- Added _AccordionContextMenuTest.ts_
- Added _AccordionMenubarTest.ts_
Pre-checks:
Review:
> TINY-9961: Added more UI tests for the Accordion plugin

- modules/oxide/src/less/theme/content-ui.less
- modules/oxide/src/less/theme/content/math/math.less
- modules/tinymce/src/plugins/help/main/ts/data/PluginUrls.ts
- modules/tinymce/src/themes/silver/main/ts/ui/menus/menubar/Integration.ts
Related Ticket: TINY-10853
* Added the `math` plugin to the default insert menu.
* Added css to display the `tiny-math-block` element as `flex` this makes it possible to later have alignment on it using `justify-content` defaults to center since that is what a math element in a regular block would do and more of the norm.
* Had to disable a csslint rule since it doesn't seem to like custom elements. Might investigate that further in some other ticket.
* Added the math plugin to the help dialog.
Pre-checks:
Review:
> TINY-10853: Added math plugin to default menu, help and content css

- .changes/unreleased/alloy-TINY-10795-2024-04-19.yaml
- .changes/unreleased/alloy-TINY-10795-2024-04-19_2.yaml
- .changes/unreleased/tinymce-TINY-10795-2024-04-19.yaml
- .changes/unreleased/tinymce-TINY-10795-2024-04-19_2.yaml
- modules/alloy/src/main/ts/ephox/alloy/api/ui/SplitSlidingToolbar.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/schema/SplitSlidingToolbarSchema.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/ToolbarDrawerToggleTest.ts
Related Ticket: TINY-10795
* It was discovered that the More button in sliding toolbar mode was using `aria-pressed` instead of `aria-expanded` when pressed.
* Focus should also be maintained on the current More button instead of shifting to the first control in the expanded toolbar row.
Pre-checks:
Review:
> TINY-10795: Accessibility improvements for More toolbar button in sliding toolbar mode

- .changes/unreleased/alloy-TINY-10806-2024-04-19.yaml
- .changes/unreleased/tinymce-TINY-10806-2024-04-12.yaml
- modules/alloy/src/main/ts/ephox/alloy/ui/schema/MenuSchema.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/single/MenuSpec.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/types/MenuTypes.ts
- modules/tinymce/src/themes/silver/main/ts/ui/menus/item/build/ColorSwatchItem.ts
- modules/tinymce/src/themes/silver/test/ts/browser/skin/OxideColorSwatchMenuTest.ts
Related Ticket: TINY-10806
* Added the `menuRole` boolean field to Alloy Menu Schema defaulted to true. Set it to false for the Color  Swatch  menu item.
Pre-checks:
Review:
> TINY-10806: Remove `role` attribute from Color Swatch menu item.

- .changes/unreleased/tinymce-TINY-10718-2024-04-19.yaml
- modules/tinymce/src/core/main/ts/init/InitIframe.ts
- modules/tinymce/src/core/test/ts/browser/init/InitIframeAriaTextTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/window/SilverInlineDialogTest.ts
Related Ticket: TINY-10718
* I've checked on NVDA, JAWS and VoiceOver
<table>
<tr>
<td></td>
<td>Chrome/Edge</td>
<td>Firefox</td>
<td>Safari </td>
</tr>
<tr>
<td> NVDA</td>
<td> `Rich Text Area` frame, `Rich Text Area. Press ALT-0 for help.` ` or `iframe_aria_text` option,  Edit </td>
<td> `Rich Text Area. Press ALT-0 for help.` or `iframe_aria_text` option. Edit </td>
<td> -  </td>
</tr>
</tr>
<tr>
<td> JAWS </td>
<td> Frame, `Rich Text Area` frame, document, `Rich Text Area. Press ALT-0 for help.` or `iframe_aria_text` option </td>
<td> `Rich Text Area. Press ALT-0 for help.` or `iframe_aria_text` option frame,  `Rich Text Area. Press ALT-0 for help.` or `iframe_aria_text` option document </td>
<td> - </td>
</tr>
<tr>
<td> VoiceOver </td>
<td> `Rich Text Area. …
> TINY-10718: Fixed firefox not announcing the iframe title when `iframe_aria_text` option was set

- .changes/unreleased/tinymce-TINY-9811-2024-04-19.yaml
- modules/oxide/src/less/theme/content/placeholder/placeholder.less
- modules/tinymce/src/plugins/autoresize/demo/html/demo.html
TINY-9811
- Added `z-index` to unblock caret in windows high contrast mode
- Changed colour of the placeholder text to be visible in windows high contrast mode
Pre-checks:
Review:
> TINY-9811: Cursor is invisible in Windows High Contrast Mode when Autoresize plugin is active

- .changes/unreleased/tinymce-TINY-10837-2024-04-18.yaml
- modules/tinymce/src/plugins/lists/main/ts/core/TextBlock.ts
- modules/tinymce/src/plugins/lists/main/ts/listmodel/ListsIndendation.ts
- modules/tinymce/src/plugins/lists/test/ts/browser/RetainListItemStylesTest.ts
Related Ticket: TINY-10837
* Fixes so the `style` attribute gets applied from the LI model element to the block element only styles right now not sure if all attributes should be retained or not maybe we expand it later.
Pre-checks:
Review:
> TINY-10837: Fix for style attribute not being retained when toggling lists

- .changes/unreleased/alloy-TINY-10795-2024-04-19.yaml
- .changes/unreleased/tinymce-TINY-10795-2024-04-19_2.yaml
- modules/alloy/src/main/ts/ephox/alloy/api/ui/SplitSlidingToolbar.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/ToolbarDrawerToggleTest.ts
Related Ticket: TINY-10795
* Reverting changes made to focus not being sent to the expanded toolbar
Pre-checks:
Review:
> TINY-10795: Partial revert 6db5421c

- modules/oxide/src/less/theme/components/view/view.less
Related Ticket: TINY-10741
* Increased the padding of the view toolbar so the focus outline of the buttons are not obscured by the scrollbar
Pre-checks:
Review:
> TINY-10741: Improve the visibility of focus outline on the view toolbar buttons

- modules/oxide/src/less/theme/components/notification/notification.less
- modules/tinymce/src/core/main/ts/api/NotificationManager.ts
- modules/tinymce/src/core/test/ts/browser/NotificationManagerTest.ts
- modules/tinymce/src/themes/silver/main/ts/alien/NotificationManagerImpl.ts
- modules/tinymce/src/themes/silver/main/ts/ui/general/Notification.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/NotificationManagerImplTest.ts
Related Ticket: TINY-6925
* Little improvement to the previous PR, now notification is focusable, tabbing flow and shortcut still remains the same
Pre-checks:
Review:
> TINY-6925: Make notifications focusable

- .changes/unreleased/tinymce-TINY-10886-2024-04-25.yaml
- modules/tinymce/src/core/demo/html/full_demo.html
- modules/tinymce/src/themes/silver/main/ts/alien/NotificationManagerImpl.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/NotificationManagerImplTest.ts
Related Ticket: TINY-10886
* Added a function that sets the width of the component after it has been rendered to match the v4 behavior.
Pre-checks:
Review:
> TINY-10886: Clamp notification width to the editor width

- .changes/unreleased/tinymce-TINY-10781-2024-04-22.yaml
- modules/oxide/src/less/theme/components/checkbox/checkbox.less
- modules/oxide/src/less/theme/components/collection/collection.less
- modules/oxide/src/less/theme/components/color-picker/color-picker.less
- modules/oxide/src/less/theme/components/color-swatch/color-swatch.less
- modules/oxide/src/less/theme/components/dialog/dialog.less
- modules/oxide/src/less/theme/components/edit-area/edit-area.less
- modules/oxide/src/less/theme/components/form/color.less
- modules/oxide/src/less/theme/components/form/listbox.less
- modules/oxide/src/less/theme/components/insert-table-picker/insert-table-picker.less
- modules/oxide/src/less/theme/components/pop/pop.less
- modules/oxide/src/less/theme/components/statusbar/statusbar.less
- modules/oxide/src/less/theme/components/toolbar-button/toolbar-button.less
- modules/oxide/src/less/theme/components/toolbar-button/toolbar-number-input.less
- modules/oxide/src/less/theme/components/toolbar-button/toolbar-select-button.less
- modules/oxide/src/less/theme/components/toolbar-button/toolbar-split-button.less
- modules/oxide/src/less/theme/components/toolbar/toolbar.less
- modules/oxide/src/less/theme/components/tooltip/tooltip.less
- modules/oxide/src/less/theme/globals/global.less
TINY-10781
```
WHCM: Windows high contrast mode
```
- Apply high contrast colour in WHCM
- Apply reduced brightness property on `hover` and `active` to indicate `hover` and `active` action
- Retain colour swatch colour (although this will not show up when applying to editor content. adding `forced-colour-adjust:none` to coloured content will not undo the forced colour change from OS) 
Pre-checks:
* <s> Tests have been added (if applicable) </s>
Review:
> TINY-10781: Apply high contrast colour in WHCM, retain colour swatch

- .changes/unreleased/tinymce-TINY-10391-2024-04-26.yaml
- modules/tinymce/src/plugins/link/main/ts/core/Actions.ts
- modules/tinymce/src/plugins/link/test/ts/browser/LinkContextMenuTest.ts
- modules/tinymce/src/plugins/link/test/ts/browser/OpenLinkContextMenuTest.ts
- modules/tinymce/src/plugins/link/test/ts/module/Utils.ts
Related Ticket: TINY-10391
* Updated the logic of getting links so the open link menu can be enabled for image with embedded link
* Moved some common assertions into `Utils.ts`
Pre-checks:
Review:
> TINY-10391: Fix open link context menu not enabled for image with embedded link

- modules/oxide/src/less/theme/content/math/math.less
Related Ticket: TINY-10890
* Changes the CSS so that inline math equations becomes inline blocks. Should fix two things both the border issue and the selection issue of math elements with `display="block"` inside a `tiny-math-inline`.
Pre-checks:
Review:
> TINY-10890: Render inline math equations as inline-block

- .changes/unreleased/tinymce-TINY-10885-2024-04-30.yaml
- modules/tinymce/src/plugins/image/main/ts/ui/Dialog.ts
- modules/tinymce/src/plugins/image/test/ts/browser/UploadTabTest.ts
Related Ticket: TINY-10885
* Set focus on the image Source input field after image upload
Pre-checks:
Review:
> TINY-10885: Keep focus on Image Dialog after image upload.

- .changes/unreleased/tinymce-TINY-10605-2024-05-03.yaml
- modules/tinymce/src/core/main/ts/api/Editor.ts
- modules/tinymce/src/core/main/ts/api/EditorOptions.ts
- modules/tinymce/src/core/main/ts/options/NormalizeOptions.ts
- modules/tinymce/src/core/test/ts/browser/EditorOptionsDebugTest.ts
Related Ticket: TINY-10605
- Added a `debug` method to `EditorOptions`. It's functionally the same as what's described in the investigation ticket [TINY-10862](https://ephocks.atlassian.net/browse/TINY-10862).
- Added an extra optional parameter to `createOptions` to pass in the initial non-normalised options.
- `normalizeOptions` now doesn't modify its `options` param as a side effect.
Example:
```console
> tinymce.activeEditor.options.debug()
{
"selector": "textarea.tinymce",
"plugins": "table lists image accordion code",
"toolbar": "table | numlist bullist | image | accordion | code",
"menu": {
"insert": {
"title": "Insert",
"items": "table | image | accordion"
}
},
"details_initial_state": "inherited",
"details_serialize_state": "inherited",
"height": 500, …
```
> TINY-10605: Added EditorOptions debug API

- .changes/unreleased/tinymce-TINY-10374-2024-05-09.yaml
- modules/tinymce/src/core/main/ts/schema/SchemaLookupTable.ts
- modules/tinymce/src/plugins/media/main/ts/core/Nodes.ts
* Added `referrerpolicy` as a valid attribute for an iframe element TINY-10374
Pre-checks:
Review:
>  TINY-10374: add referrerpolicy atribute to the iframe

- .changes/unreleased/tinymce-TINY-10878-2024-05-13.yaml
- modules/tinymce/src/plugins/emoticons/main/ts/api/Options.ts
TINY-10878
- Original CDN no longer valid, changed to a new on
Pre-checks:
Review:
> TINY-10878: Update the cdn link for the twitter emoji database

- .changes/unreleased/tinymce-TINY-10942-2024-05-15.yaml
- modules/tinymce/src/core/main/ts/keyboard/Autocompleter.ts
Related Ticket: TINY-10942
Removed the `context.text.length - ac.matchLength >= 10` check.
Pre-checks:
Review:
> TINY-10942: Show autocompleter regardless of match length

- .changes/unreleased/tinymce-TINY-10901-2024-05-14.yaml
- modules/oxide/src/less/theme/components/dialog/dialog.less
Related Ticket: TINY-10901
* Fixes issue with rendering of rounded borders on iframes in dialogs.
Pre-checks:
Review:
> TINY-10901: Fixed rendering issue with rounded borders on iframes

- .changes/unreleased/tinymce-TINY-10840-2024-05-07.yaml
- modules/tinymce/src/core/main/ts/ForceBlocks.ts
- modules/tinymce/src/core/main/ts/bookmark/StructureBookmark.ts
- modules/tinymce/src/core/main/ts/delete/DeleteCommands.ts
- modules/tinymce/src/core/main/ts/delete/DivDelete.ts
- modules/tinymce/src/core/main/ts/keyboard/DeleteBackspaceKeys.ts
- modules/tinymce/src/core/test/ts/browser/ForceBlocksTest.ts
- modules/tinymce/src/core/test/ts/browser/bookmark/StructureBookmarkTest.ts
- modules/tinymce/src/core/test/ts/browser/delete/DivDeleteTest.ts
- modules/tinymce/src/core/test/ts/browser/delete/InlineFormatPostShortcutDeleteTest.ts
Related Ticket: TINY-10840
* Added a new way to store/restore selections when wrapping elements in the root so that it doesn't throw if the element indexes doesn't match after it's been wrapped.
* Had to add special code for Firefox that does strange things when the body is empty or filled.
Pre-checks:
Review:
> TINY-10840: Fixed errors thrown by ForceBlocks and element selections

- modules/tinymce/src/core/main/ts/api/util/EventDispatcher.ts
Related Ticket: TINY-10948
* Update `fire()` method deprecation version in [EventDispatcher.ts](https://github.com/tinymce/tinymce/blob/1b981f0db698f58ba791a647830b9dbdb99f9614/modules/tinymce/src/core/main/ts/api/util/EventDispatcher.ts#L124C32-L124C35)
Pre-checks:
Review:
> TINY-10948: Update fire() method deprecation version.

- .changes/unreleased/tinymce-TINY-10900-2024-05-10.yaml
- modules/bridge/src/main/ts/ephox/bridge/components/dialog/HtmlPanel.ts
- modules/oxide/src/less/theme/components/form/custom-preview.less
- modules/oxide/src/less/theme/theme.less
- modules/tinymce/src/themes/silver/main/ts/ui/general/HtmlPanel.ts
- modules/tinymce/src/themes/silver/test/ts/headless/components/htmlpanel/HtmlPanelTest.ts
Related Ticket: TINY-10900
Re-target for 7.2 of this PR: https://github.com/tinymce/tinymce/pull/9641
* Added `onInit` that gives you a raw DOM reference to the HtmlPanel
* Added `stretched` so that you can control how the panel stretches.
* Added `custom-preview` css used by the math plugin.
Pre-checks:
Review:
> TINY-10900: Added onInit and stretched and custom preview css to HtmlPanel dialog component

- .changes/unreleased/tinymce-TINY-10885-2024-04-30.yaml
- modules/tinymce/src/plugins/image/main/ts/ui/Dialog.ts
- modules/tinymce/src/plugins/image/test/ts/browser/UploadTabTest.ts
Related Ticket: TINY-10885
* Backport of https://github.com/tinymce/tinymce/pull/9605 for 7.1.1 release
Pre-checks:
Review:
> TINY-10885: Keep focus on Image Dialog after image upload. (#9605)

- .changes/unreleased/tinymce-TINY-10916-2024-05-15.yaml
- modules/acid/src/main/ts/ephox/acid/api/colour/RgbaColour.ts
- modules/acid/src/test/ts/browser/RgbaColourTest.ts
- modules/tinymce/src/core/main/ts/api/html/Styles.ts
- modules/tinymce/src/core/test/ts/browser/html/StylesTest.ts
TINY-10916
- Added a seperate if statement to cover the edge case of transparent
Pre-checks:
Review:
https://github.com/tinymce/tinymce/issues/9391
> TINY-10916: Transparent color is converted into #00000

- .changes/unreleased/tinymce-TINY-10428-2024-05-20.yaml
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/Slider.ts
- modules/tinymce/src/themes/silver/test/ts/browser/window/SilverDialogSliderApiTest.ts
Related Ticket: TINY-10428
Silver theme slider component emits onChange event now while using arrow keys 
Pre-checks:
Review:
> TINY-10428: emit slider onChange event while using arrow keys 

- .changes/unreleased/tinymce-TINY-10384-2024-05-21.yaml
- modules/tinymce/src/core/main/ts/newline/InsertBlock.ts
- modules/tinymce/src/core/test/ts/browser/keyboard/EnterKeyHrTest.ts
- modules/tinymce/src/core/test/ts/browser/newline/NewlineAroundBrTest.ts
Related Ticket: TINY-10384
- Added a check before the cursor is potentially moved by the `insertBefore` function, to make sure it moves to the next line.
- Added _NewlineAroundBrTest.ts_ and modified existing _EnterKeyHrTest.ts_
Pre-checks:
* [-] Branch prefixed with `feature/`, `hotfix/` or `spike/`
Review:
> TINY-10384: Make sure cursor moves to next line when around a <br>, <img>, or <table>

- modules/tinymce/src/themes/silver/test/ts/webdriver/dialogs/IFrameDialogTest.ts
Related Ticket: TINY-10974
Version 126 of Firefox fix [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1884870) so some special behaviors for Firefox in `IFrameDialogTest.ts` are no more needed if the version of Firefox is 126 or superior
Pre-checks:
Review:
> TINY-10974: fix tests for new Firefox version (126)

- .changes/unreleased/tinymce-TINY-10793-2024-05-13.yaml
- modules/tinymce/src/plugins/autoresize/main/ts/Plugin.ts
- modules/tinymce/src/plugins/autoresize/main/ts/api/Commands.ts
- modules/tinymce/src/plugins/autoresize/main/ts/core/Resize.ts
- modules/tinymce/src/plugins/autoresize/test/ts/browser/AutoresizePluginDocumentTest.ts
- modules/tinymce/src/plugins/autoresize/test/ts/browser/AutoresizePluginTest.ts
Related Ticket: https://ephocks.atlassian.net/browse/TINY-10793
`autoresize_bottom_margin` was not applied in some situations.
Pre-checks:
Review:
> TINY-10973: Resize bottom margin not always applied.

- .changes/unreleased/polaris-TINY-10904-2024-05-22.yaml
- modules/polaris/src/main/ts/ephox/polaris/words/Words.ts
- modules/robin/src/test/ts/atomic/words/IdentifyTest.ts
- modules/tinymce/src/themes/silver/test/ts/webdriver/dialogs/IFrameDialogTest.ts
Related Ticket: TINY-10904
to manage correctly the acronyms when we get the words via polaris, I changed the check inside `findWordsWithIndices` instead of inside `isWordBoundary`.
This is because `isWordBoundary` is based on single "characters" so to avoid performance and readability issues I create an external check that is triggered only at the end of a word and on dots at the end of the word or after it.
This is came from [this PR](https://github.com/tinymce/tinymce/pull/9663)
Pre-checks:
Review:
> TINY-10904: now polaris manage acronyms correctly

- .changes/unreleased/tinymce-TINY-10916-2024-05-15.yaml
- modules/acid/src/main/ts/ephox/acid/api/colour/RgbaColour.ts
- modules/acid/src/test/ts/browser/RgbaColourTest.ts
- modules/tinymce/src/core/main/ts/api/html/Styles.ts
- modules/tinymce/src/core/test/ts/browser/html/StylesTest.ts
* TINY-10916: Convert transparent to fully transparent black in Styles.ts
* TINY-10916: Add changelog
* TINY-10916: Prevent transparent from been converted
* TINY-10916: Add and refactor tests
* Update .changes/unreleased/tinymce-TINY-10916-2024-05-15.yaml
* TINY-10916: Add more test
* TINY-10916: Add more tests
* TINY-10916: Update rgba regex to do exact match.
* TINY-10916: Remove transparent string check (WIP)
* TINY-10916: Rever rgba regex to rgb regex
* TINY-10916: Lint fix
* TINY-10916: Remove global match in rgb regex
* TINY-10916: Refactor code, add support and test for new format
* Update tinymce-TINY-10916-2024-05-15.yaml
* TINY-10916: Update rgba regex
* TINY-10916: Add RgbaColour test
* TINY-10916: Update rgba regex and test
---------
* …
> TINY-10916: Transparent color is converted into #00000 (#9649)

- .changes/unreleased/alloy-TINY-10891-2024-05-30.yaml
- .changes/unreleased/alloy-TINY-10891-2024-05-30_2.yaml
- .changes/unreleased/tinymce-TINY-10891-2024-05-30.yaml
- modules/alloy/src/main/ts/ephox/alloy/api/Main.ts
- modules/alloy/src/main/ts/ephox/alloy/aria/AriaDescribe.ts
- modules/tinymce/src/themes/silver/main/ts/backstage/TooltipsBackstage.ts
- modules/tinymce/src/themes/silver/main/ts/ui/statusbar/ElementPath.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/tooltip/ElementPathTooltipTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/statusbar/StatusbarTest.ts
- modules/tinymce/src/themes/silver/test/ts/webdriver/tooltip/ElementPathTooltipTest.ts
Related Ticket: TINY-10891
* Add tooltips to element path, in the previous version, the label of the button is being announced but there's no additional description to describe what does the button do
* On mouse hover and keyboard focus, tooltip with label `Select the X element` will be shown, and when using screen reader this will also be announced
* Removal of incorrect `aria-level`
* Exposed `AriaDescribe` and added a `remove` function in that API
Pre-checks:
* [ x Tests have been added (if applicable)
Review:
> TINY-10891: Add tooltips to element path

- .changes/unreleased/bridge-TINY-10971-2024-06-04.yaml
- .changes/unreleased/tinymce-TINY-10971-2024-06-04.yaml
- modules/bridge/src/main/ts/ephox/bridge/components/dialog/Label.ts
- modules/tinymce/src/plugins/searchreplace/main/ts/ui/Dialog.ts
- modules/tinymce/src/themes/silver/main/ts/backstage/Backstage.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/BodyPanel.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/Label.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/TabPanel.ts
- modules/tinymce/src/themes/silver/main/ts/ui/general/UiFactory.ts
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialog.ts
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialogBody.ts
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialogInstanceApi.ts
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverInlineDialog.ts
- modules/tinymce/src/themes/silver/test/ts/headless/components/label/LabelTest.ts
- modules/tinymce/src/themes/silver/test/ts/headless/window/SilverDialogForLabelTest.ts
Related Ticket: TINY-10971
It is now possible to define for attribute in a label component. It accepts the name of a different element.
Pre-checks:
Review:
> TINY-10971: introduce optional label for property

- .changes/unreleased/tinymce-TINY-10871-2024-06-05.yaml
- modules/tinymce/src/plugins/searchreplace/main/ts/ui/Dialog.ts
- modules/tinymce/src/plugins/searchreplace/test/ts/browser/SearchReplaceDialogCyclingTest.ts
- modules/tinymce/src/plugins/searchreplace/test/ts/browser/SearchReplaceDialogTest.ts
- modules/tinymce/src/plugins/searchreplace/test/ts/browser/SearchReplaceKeyboardNavigationTest.ts
- modules/tinymce/src/plugins/searchreplace/test/ts/browser/SearchReplacePrevNextTest.ts
- modules/tinymce/src/plugins/searchreplace/test/ts/browser/UndoReplaceSpanTest.ts
- modules/tinymce/src/plugins/searchreplace/test/ts/module/test/Utils.ts
Related Ticket: TINY-10871
Replaced input placeholders with labels in Find & Replace dialog.
Pre-checks:
Review:
> TINY-10871: replace placeholders with labels in Find & Replace dialog

- .changes/unreleased/alloy-TINY-10806-2024-04-19.yaml
- .changes/unreleased/tinymce-TINY-10807-2024-05-23.yaml
- modules/alloy/src/main/ts/ephox/alloy/api/ui/Dropdown.ts
- modules/alloy/src/main/ts/ephox/alloy/dropdown/DropdownUtils.ts
- modules/alloy/src/main/ts/ephox/alloy/menu/build/ItemType.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/schema/DropdownSchema.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/schema/MenuSchema.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/schema/SplitDropdownSchema.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/schema/TypeaheadSchema.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/single/MenuSpec.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/types/DropdownTypes.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/types/ItemTypes.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/types/MenuTypes.ts
- modules/bridge/src/main/ts/ephox/bridge/components/menu/CommonMenuItem.ts
- modules/bridge/src/main/ts/ephox/bridge/core/ComponentSchema.ts
- modules/tinymce/src/plugins/table/test/ts/module/test/TableTestUtils.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/ListBox.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dropdown/CommonDropdown.ts
- modules/tinymce/src/themes/silver/main/ts/ui/menus/item/build/ColorSwatchItem.ts
- modules/tinymce/src/themes/silver/main/ts/ui/menus/item/build/ToggleMenuItem.ts
- modules/tinymce/src/themes/silver/test/ts/headless/components/listbox/ListBoxAriaTest.ts
Related Ticket: TINY-10807
* Added `role` and `listRole` fields in schemas where needed to pass necessary role values for ListBox components. So for a ListBox without nested menu items, the menu button should have `role="combobox"`, the list of items should have `listRole="listbox" `(instead of `"menu"`) and items should have `role="option"` (instead of `"menuitem"`)
* rename the `menuRole` field to `showMenuRole` since it is confusing to have `menuRole` and `role` fields
Pre-checks:
Review:
> TINY-10807: Use role="combobox" for flat ListBox components

- .changes/unreleased/tinymce-TINY-10590-2024-05-21.yaml
- modules/tinymce/src/core/main/ts/delete/BlockBoundaryDelete.ts
- modules/tinymce/src/core/main/ts/delete/BlockMergeBoundary.ts
- modules/tinymce/src/core/main/ts/delete/MergeBlocks.ts
- modules/tinymce/src/core/test/ts/browser/delete/BlockMergeBoundaryTest.ts
- modules/tinymce/src/core/test/ts/browser/delete/MergeBlocksTest.ts
Related Ticket: https://ephocks.atlassian.net/browse/TINY-10590
Merge block would not always consider nested elements correctly.
Pre-checks:
Review:
> TINY-10590: Merge blocks now no longer relying on browser behavior for edgecase.

- build.properties
Related Ticket: TINY-10127
Descriptions:
- In some cases, when a branch is branched off `main` and target for `release/7`, the CI fails because of merge conflicts
> TINY-10127: Correct the merge branch for CI

- .changes/unreleased/tinymce-TINY-10127-2024-06-12.yaml
- modules/darwin/src/main/ts/ephox/darwin/mouse/MouseSelection.ts
- modules/tinymce/src/models/dom/test/ts/browser/table/FakeSelectionTest.ts
Related Ticket: TINY-10127
* Keeping the selection on the offscreen element instead of selecting the content of the actual td cell
* Similar behaviour when selecting the non editable paragraph or other elements, preventing the cursor to be shifted when the editor is not focused, then focused by clicking on noneditable cell
Pre-checks:
Review:
> TINY-10127: Fix cursor would shift to the start of the editor body when focus was shifted to a noneditable cell of a table

- Jenkinsfile
Related Ticket: TINY-11046
* Switches all tests to lambdatest since something is wrong with the aws device farm
Pre-checks:
Review:
> TINY-11046: Switched from aws to lambdatest

- .changes/unreleased/tinymce-TINY-10961-2024-06-18.yaml
- modules/oxide/src/less/theme/components/statusbar/statusbar.less
Related Ticket: https://ephocks.atlassian.net/browse/TINY-10961
Minor css changes for improved design.
Pre-checks:
Review:
> TINY-10961: Long translations of the bottom helptext would overflow poorly.

- .changes/unreleased/tinymce-TINY-10994-2024-06-17.yaml
- modules/tinymce/src/core/main/ts/textpatterns/keyboard/Keyboard.ts
- modules/tinymce/src/core/test/ts/browser/textpatterns/TextPatternsUnsupportedCmdTest.ts
Related Ticket: TINY-10994
Text pattern commands do not execute now if the command is not available.
Pre-checks:
Review:
> TINY-10994: filter unsupported commands from text patterns

- .changes/unreleased/tinymce-TINY-10955-2024-06-24.yaml
- modules/tinymce/src/core/main/ts/api/html/DomParser.ts
- modules/tinymce/src/core/test/ts/browser/EditorTest.ts
Related Ticket: https://ephocks.atlassian.net/browse/TINY-10955
To prevent element generation we just remove the whitespaces.
Pre-checks:
Review:
> TINY-10955: Remove whitespaces between comment elements.

- modules/tinymce/src/core/test/ts/browser/EditorTest.ts
Related Ticket: https://ephocks.atlassian.net/browse/TINY-10955
This is just removing that accidental .only
Pre-checks:
* ~~[x] Changelog entry added~~
* ~~[x] Tests have been added (if applicable)~~
* ~~[x] Branch prefixed with `feature/`, `hotfix/` or `spike/`~~
Review:
> TINY-10955: Accidentally left a development .only on a test when merging in.

- .changes/unreleased/tinymce-TINY-10799-2024-06-13.yaml
- modules/acid/src/demo/ts/ephox/acid/demo/Demo.ts
- modules/acid/src/main/ts/ephox/acid/gui/ColourPicker.ts
- modules/acid/src/main/ts/ephox/acid/gui/components/RgbForm.ts
- modules/alloy/src/main/ts/ephox/alloy/behaviour/tooltipping/ActiveTooltipping.ts
- modules/alloy/src/main/ts/ephox/alloy/behaviour/tooltipping/TooltippingApis.ts
- modules/alloy/src/main/ts/ephox/alloy/behaviour/tooltipping/TooltippingSchema.ts
- modules/alloy/src/main/ts/ephox/alloy/behaviour/tooltipping/TooltippingState.ts
- modules/alloy/src/main/ts/ephox/alloy/behaviour/tooltipping/TooltippingTypes.ts
- modules/alloy/src/main/ts/ephox/alloy/construct/CustomDefinition.ts
- modules/oxide/src/less/theme/components/color-picker/color-picker.less
- modules/oxide/src/less/theme/globals/global-variables.less
- modules/tinymce/src/themes/silver/main/ts/backstage/TooltipsBackstage.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/ColorPicker.ts
- modules/tinymce/src/themes/silver/test/ts/module/TestProviders.ts
Related Ticket: https://ephocks.atlassian.net/browse/TINY-10799
Add an error tooltip and error icon when the text input is not valid.
Pre-checks:
Review:
> TINY-10799: Color picker input field error tooltip.

- .changes/unreleased/tinymce-TINY-10590-2024-05-21.yaml
- modules/tinymce/src/core/main/ts/delete/BlockBoundaryDelete.ts
- modules/tinymce/src/core/main/ts/delete/BlockMergeBoundary.ts
- modules/tinymce/src/core/main/ts/delete/MergeBlocks.ts
- modules/tinymce/src/core/test/ts/browser/delete/BlockMergeBoundaryTest.ts
- modules/tinymce/src/core/test/ts/browser/delete/MergeBlocksTest.ts
After an investigation, it was determined that the change in #9669 incorrectly modifies the DOM when pressing backspace on a `br`. The following image shows the result between before (left) and after (right) the change has been reverted.
> Revert "TINY-10590: Merge blocks now no longer relying on browser behavior for edgecase."

- .changes/unreleased/tinymce-TINY-11053-2024-07-04.yaml
- modules/tinymce/src/core/main/ts/api/html/DomParser.ts
- modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts
Related Ticket: https://ephocks.atlassian.net/browse/TINY-11057
Previously whole html-blocks were put into a body-tag and merging the head and body before we could do anything about them.
Pre-checks:
Review:
> TINY-11053: Now handling whole html documents in the text area.

- .changes/unreleased/katamari-TINY-11083-2024-07-11.yaml
- modules/katamari/src/main/ts/ephox/katamari/api/Type.ts
- modules/katamari/src/test/ts/atomic/api/type/TypeTest.ts
Related Ticket: TINY-11083
as title says: add `Type.isPromiseLike` to `Katamari`
Pre-checks:
Review:
> TINY-11083: add `Type.isPromiseLike` to `Katamari`

- .changes/unreleased/tinymce-TINY-10884-2024-07-09.yaml
- modules/tinymce/src/themes/silver/main/ts/ui/dropdown/CommonDropdown.ts
Related Ticket: TINY-10884
Removed setting fixed width for listbox dropdown.
Pre-checks:
Review:
> TINY-10884: remove fixed width for listbox

- .changes/unreleased/tinymce-TINY-10638-2024-07-12.yaml
- modules/tinymce/src/themes/silver/main/ts/ui/general/Button.ts
Related Ticket: TINY-10638
Removed prevent default for mousedown in Button as it was causing bugs.
Pre-checks:
Review:
> TINY-10638: remove prevent default for mousedown from button

- .changes/unreleased/mcagar-TINY-11093-2024-07-10.yaml
- .changes/unreleased/sugar-TINY-11093-2024-07-10.yaml
- modules/agar/src/test/ts/browser/FocusToolsTest.ts
- modules/alloy/src/main/ts/ephox/alloy/api/testhelpers/GuiSetup.ts
- modules/mcagar/src/main/ts/ephox/mcagar/api/bdd/TinyHooks.ts
- modules/mcagar/src/main/ts/ephox/mcagar/api/pipeline/TinyLoader.ts
- modules/mcagar/src/test/ts/browser/api/TinyLoaderTest.ts
- modules/sand/src/main/ts/ephox/sand/api/PlatformDetection.ts
- modules/sugar/src/main/ts/ephox/sugar/api/events/Viewable.ts
- modules/sugar/src/main/ts/ephox/sugar/api/node/SugarShadowDom.ts
- modules/sugar/src/main/ts/ephox/sugar/api/view/Platform.ts
- modules/sugar/src/main/ts/ephox/sugar/selection/query/CaretRange.ts
- modules/sugar/src/test/ts/browser/BodyTest.ts
- modules/sugar/src/test/ts/browser/ShadowDomTest.ts
- modules/sugar/src/test/ts/module/ephox/sugar/test/WithHelpers.ts
- modules/tinymce/src/core/main/ts/api/Env.ts
- modules/tinymce/src/core/test/ts/browser/dom/StyleSheetLoaderRegistryTest.ts
- modules/tinymce/src/core/test/ts/browser/init/ShadowDomEditorTest.ts
Related Ticket: TINY-11093
* Remove IE11 and Edge Legacy poll fallback for mutation observer.
* Remove IE11 and Edge Legacy shadow DOM fallback.
* Avoid caching `PlatformDetection.detect()` as it's already cached.
* Remove on-load feature detection of caret position, it doesn't cost much to do at runtime and this simplifies the code.
This should have no user-facing impact. The bulk of the changes are unwinding test code that handled the case where ShadowDom was unavailable; I simply set the value to `true` and let my IDE refactoring remove the dead code.
Pre-checks:
* [] Changelog entry added
Review:
> TINY-11093: Reduce code running on script load

- modules/oxide/src/less/theme/components/revisionhistory/revisionhistory.less
Related Ticket: TINY-11045
* Updated the styling of revision sidebar according to the design
* Removed unused variables
* Added background and border colors for dark mode
**Attached pictures of revision history in normal and dark modes**:
Pre-checks:
Review:
> TINY-11045: Update the styles of Revision History sidebar

- .changes/unreleased/tinymce-TINY-11043-2024-07-12.yaml
- modules/tinymce/src/core/main/ts/focus/EditorFocus.ts
- modules/tinymce/src/core/test/ts/browser/focus/EditorFocusTest.ts
Related Ticket: TINY-11085
Giving focus to a CET which was not placed inside a CEF would cause some issues if we didn't also focus on the body first.
Pre-checks:
Review:
> TINY-11085: CET-marked elements outside of a CEF-element would not always gain focus as expected.

- modules/oxide/src/less/theme/components/revisionhistory/revisionhistory.less
Related Ticket: TINY-11090
* Updated the stylings of focused, hovered and selected revisions as per design
* Added a class for revision card check icon
Pre-checks:
Review:
> TINY-11090: Update stylings of focused, hovered and selected revisions

- modules/oxide/src/less/theme/components/revisionhistory/revisionhistory.less
Related Ticket:  TINY-11079
* Removed extra padding under revision card date
* Fixed label and date being rendered on the same line
* Removed an unused class
Pre-checks:
Review:
> TINY-11079: Fix styling of revision card when not displaying author

- modules/oxide/src/less/theme/components/revisionhistory/revisionhistory.less
Related Ticket: TINY-11128
* Fixed Revision History avatar not circular
* Applied the common height in other places
Pre-checks:
Review:
> TINY-11128: Fix Revision History avatar not circular

- .changes/unreleased/tinymce-TINY-11115-2024-07-23.yaml
- modules/acid/src/main/ts/ephox/acid/gui/components/RgbForm.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/ColorPicker.ts
Related Ticket: TINY-11115
Wrong text, 
Pre-checks:
Review:
> TINY-11115: Changed hex input field validation error text.

- modules/tinymce/src/core/main/ts/mode/Readonly.ts
- modules/tinymce/src/core/test/ts/browser/SelectionEnabledModeTest.ts
- modules/tinymce/src/core/test/ts/browser/UiEnabledModeTest.ts
- modules/tinymce/src/themes/silver/main/ts/ui/toolbar/button/ToolbarButtons.ts
Related Ticket: TINY-10890
* Follow up PR, the button part of a split button was incorrectly disabled.
* Tests have been added, but only asserting the menu part of button and only when it's enabled, when it's disabled the whole div (button) structure gets disabled but the menu part and the arrow are missing those attributes (but they are still disabled) 
* Missed out re-enabling `contenteditable="true"` when switching from readonly -> selectionEnabled mode.
Pre-checks:
Review:
> TINY-10890: Fix menu part of split button to be wrongly disabled

- modules/oxide/src/less/theme/components/color-picker/color-picker.less
Related Ticket: TINY-11138
Changed the colors on the validation error tooltip to be more user friendly.
Validation error tooltips not yet released, no changelog.
Pre-checks:
Review:
> TINY-11138: Change of error colors.

- .changes/unreleased/tinymce-TINY-9915-2024-07-24.yaml
- modules/oxide/src/less/theme/components/collection/collection.less
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/Collection.ts
Related Ticket: TINY-9915
Removed jumpy scroll when hovering on partially visible collection element. 
Pre-checks:
Review:
> TINY-9915: remove scroll on mouseover of collection dialog elements

- .changes/unreleased/tinymce-TINY-11077-2024-07-26.yaml
- modules/tinymce/src/core/main/ts/caret/CaretUtils.ts
- modules/tinymce/src/core/test/ts/browser/caret/TableRowNonEditable.ts
Related Ticket: TINY-11077
Fixed an issue with caret going unexpectedly to a not editable table row above when user pressed enter.
Pre-checks:
Review:
> TINY-11077: add table row to a block like list

- .changes/unreleased/tinymce-TINY-11082-2024-07-30.yaml
- modules/tinymce/src/core/main/ts/content/InsertContentImpl.ts
- modules/tinymce/src/core/test/ts/browser/content/insert/InsertContentCommandTest.ts
- modules/tinymce/src/core/test/ts/browser/content/insert/InsertContentTest.ts
- modules/tinymce/src/models/dom/test/ts/browser/table/ResizeTableTest.ts
- modules/tinymce/src/plugins/table/test/ts/browser/ClipboardTest.ts
- modules/tinymce/src/plugins/table/test/ts/browser/TableRemoveTrailingBrTest.ts
Related Ticket: TINY-11082
Caret would be placed inside the last cell of the pasted table. Now is placed after the table.
Pre-checks:
Review:
> TINY-11082: place the caret after the table when pasting 

- build.properties
- modules/tinymce/src/core/main/ts/api/commands/FormatCommands.ts
- modules/tinymce/src/core/main/ts/api/commands/LinkCommands.ts
- modules/tinymce/src/core/main/ts/api/dom/Selection.ts
- modules/tinymce/src/core/main/ts/commands/IndentOutdent.ts
- modules/tinymce/src/core/main/ts/keyboard/TableNavigation.ts
- modules/tinymce/src/core/main/ts/newline/InsertNewLine.ts
- modules/tinymce/src/core/main/ts/newline/NewBlock.ts
- modules/tinymce/src/core/test/ts/browser/FormattingCommandsTest.ts
- modules/tinymce/src/core/test/ts/browser/SelectionEnabledModeTest.ts
- modules/tinymce/src/core/test/ts/browser/api/commands/NewBlockCommandsTest.ts
- modules/tinymce/src/core/test/ts/browser/delete/OutdentTest.ts
- modules/tinymce/src/core/test/ts/browser/newline/InsertNewLineTest.ts
- modules/tinymce/src/models/dom/main/ts/table/api/TableResizeHandler.ts
- modules/tinymce/src/plugins/accordion/main/ts/core/Actions.ts
- modules/tinymce/src/plugins/autolink/main/ts/core/Keys.ts
- modules/tinymce/src/plugins/lists/main/ts/core/Util.ts
Related Ticket: TINY-10981
* Follow up ticket to address issues such as:
* Formatter still working with keyboard shortcuts
* Tabbing to indent list
* Tabbing to create new row when selection is at the last cell of a table
* Various commands that still work, example: `InsertNewBlockBefore`, `InsertLineBreak`
* Added readonly check to `selection.isEditable`
* They should be blocked anyway in readonly mode, but since the cursor cannot be placed in the editor with full readonly mode (`contenteditable="false"`) so they weren't.
Pre-checks:
Review:
> TINY-10981: Address issues with selectionEnabled

- .changes/unreleased/tinymce-TINY-11100-2024-08-05.yaml
- modules/tinymce/src/plugins/lists/main/ts/core/Delete.ts
- modules/tinymce/src/plugins/lists/test/ts/browser/BackspaceDeleteTest.ts
Related Ticket: TINY-11100
The list plugin will fire an input event if none is fired by the delete command.
Pre-checks:
Review:
> TINY-11100: Fire input event during delete if one is not already fired.

- .changes/unreleased/tinymce-TINY-11131-2024-07-31.yaml
- modules/bridge/src/main/ts/ephox/bridge/components/dialog/Tree.ts
- modules/oxide/src/less/theme/components/tree/tree-button.less
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/Tree.ts
- modules/tinymce/src/themes/silver/test/ts/headless/components/tree/TreeTest.ts
Related Ticket: TINY-11131
To display some sort of locked/readonly icon for locked/readonly templates and categories we needed to add the ability to add these.
Pre-checks:
Review:
> TINY-11131: Added custom state to tree structure

- modules/mcagar/src/main/ts/ephox/mcagar/api/McEditor.ts
- modules/mcagar/src/main/ts/ephox/mcagar/loader/Loader.ts
- modules/tinymce/src/core/test/ts/browser/EditorOptionsDebugTest.ts
- modules/tinymce/src/core/test/ts/browser/content/EditorResetContentTest.ts
- modules/tinymce/src/core/test/ts/browser/init/LicenseKeyValidationTest.ts
Related Ticket: n/a
* Suppress the license key warning in our own tests
* The reset content test created a bunch of editors but didn't shut them down, resulting in `textarea` elements left in the page that might impact subsequent tests.
Pre-checks:
Review:
> Properly shut down the editors created by the reset content test

- modules/bridge/src/main/ts/ephox/bridge/api/Registry.ts
- modules/bridge/src/main/ts/ephox/bridge/components/toolbar/ToolbarButton.ts
- modules/tinymce/src/core/main/ts/api/ui/Registry.ts
- modules/tinymce/src/themes/silver/main/ts/ButtonState.ts
- modules/tinymce/src/themes/silver/main/ts/backstage/Backstage.ts
- modules/tinymce/src/themes/silver/main/ts/modes/Iframe.ts
- modules/tinymce/src/themes/silver/main/ts/modes/Inline.ts
- modules/tinymce/src/themes/silver/main/ts/ui/core/Context.ts
- modules/tinymce/src/themes/silver/main/ts/ui/core/FormatControls.ts
- modules/tinymce/src/themes/silver/main/ts/ui/toolbar/button/ToolbarButtons.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/contexttoolbar/ContextToolbarLookupPrioritisationTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/ToolbarButtonContextTest.ts
- modules/tinymce/src/themes/silver/test/ts/headless/toolbar/ToolbarButtonsTest.ts
- modules/tinymce/src/themes/silver/test/ts/headless/window/SilverDialogEventTest.ts
- modules/tinymce/src/themes/silver/test/ts/module/TestProviders.ts
Related Ticket:  TINY-11211
* First phase, adding the base for `addContext` to the registry and using them in the backstage.
* Added the `context` spec to the Toolbar buttons for now, will be expanding to other type of buttons in the upcoming PRs.
Pre-checks:
Review:
> TINY-11211: Add context for UI components

- modules/oxide/src/less/theme/components/comments/comment.less
- modules/oxide/src/less/theme/content/comments/comments.less
- modules/tinymce/src/core/test/ts/browser/annotate/AnnotationStylingTest.ts
Related Ticket: TINY-11228
* Adds blue box shadow border and yellow background to active comment span elements according to new design.
* Sneaking in a fix for the CSS on scrolling the card into view. The extra margin make it off by a few pixels.
Pre-checks:
Review:
> TINY-11228: Changed styling for active comments

- .changes/unreleased/tinymce-TINY-11123-2024-08-26.yaml
- modules/alloy/src/main/ts/ephox/alloy/dropdown/DropdownUtils.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dropdown/CommonDropdown.ts
Related Ticket: TINY-11123
Dropdown would not close or adjust its width while resizing the window. We decided to close the dropdown to solve that issue.
Pre-checks:
Review:
> TINY-11123: close dropdowns while resizing window

- .changes/unreleased/tinymce-TINY-11166-2024-09-06.yaml
- modules/tinymce/src/core/main/ts/api/Options.ts
- modules/tinymce/src/core/main/ts/api/html/DomParser.ts
- modules/tinymce/src/core/main/ts/html/Sanitization.ts
- modules/tinymce/src/core/main/ts/init/InitContentBody.ts
- modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts
Related Ticket: TINY-11166
* Added new option to keep specific annotation encodings.
Pre-checks:
Review:
> TINY-11166: Added new option to allow specific math annotation elements

- Gruntfile.js
- Jenkinsfile
- yarn.lock
~Reduce the headless testing list to zero, so it never runs and those projects are included in normal browser testing (which does push up the browser test count, but not by a lot).~
[edit: this didn't help because some of the headless tests fail on safari and firefox. Downgraded the test run to Chrome 127 instead.]
Also:
* Bedrock was never upgraded to the version that reduces test log output in CI. So this should finally resolve those 20 megabyte log outputs we've been getting.
* Fix running headless-auto tests on dev machines.
* Increase default chunk size, which is used for headless testing.
* ~This didn't help headless tests pass, so I just disabled headless testing.~
> Stop headless tests failing the build

- modules/tinymce/src/core/main/ts/api/Options.ts
- modules/tinymce/src/core/test/ts/browser/content/EditorContentTest.ts
Related Ticket: TINY-11166
* Follow up to TINY-11166 since I messed up the option it would return `true` instead of the expected value.
* Added a proper integration test than just the unit test I had for DomParser this would have been caught if I had done that in the first place.
Pre-checks:
Review:
> TINY-11166: Fixed issue with editor config option

- .changes/unreleased/tinymce-TINY-10847-2024-09-09.yaml
- modules/tinymce/src/core/test/ts/browser/paste/InternalClipboardTest.ts
- modules/tinymce/src/models/dom/main/ts/table/actions/Clipboard.ts
- modules/tinymce/src/plugins/table/test/ts/browser/ClipboardTest.ts
Related Ticket: TINY-10847
* Update the table clipboard handler so that the replicated table is added to the DOM. We can use the browser to give us the `innerText` of the table element which separates cells with a `\t` character and rows with a `\n` character
Pre-checks:
Review:
> TINY-10847: Fix clipboard text content when copying tables

- .changes/unreleased/tinymce-TINY-11257-2024-09-16.yaml
- modules/oxide/src/less/theme/components/statusbar/statusbar.less
Related Ticket: TINY-11257
Resize handle would be incorrectly located in the right corner when no other components were added to status bar.
Pre-checks:
Review:
> TINY-11257: fix resize handle placing

- modules/oxide/src/less/theme/components/toolbar/toolbar.less
TINY-11194
- Added the pixel unit to a css value
Pre-checks:
Review:
> TINY-11194: A CSS Calc function with a unitless number causes Sass compilation error

- .changes/unreleased/tinymce-TINY-11266-2024-09-18.yaml
- modules/oxide/src/less/skins/ui/dark/skin.less
- modules/oxide/src/less/theme/components/comments/comment.less
- modules/oxide/src/less/theme/components/sidebar/sidebar.less
- modules/oxide/src/less/theme/content/comments/comments.less
- modules/oxide/src/less/theme/globals/global-variables.less
- modules/tinymce/src/core/test/ts/browser/annotate/AnnotationStylingTest.ts
Related Ticket: TINY-11266
Moved all styles from comments to oxide and adjusted them to dark mode. Added `@color-active` to global variables as a way to configure selected comment colors.
Default and dark mode after changes: 
Pre-checks:
Review:
> TINY-11266: move comments styles to oxide and adjust to skins

- modules/oxide/src/less/theme/components/comments/comment.less
Related Ticket: TINY-11258 TINY-11277
* Remove shadow by default on comment cards
* apply shadow on hover instead
Pre-checks:
Review:
> TINY-11258 TINY-11277: Remove shadow by default on comment cards

- modules/oxide/src/less/theme/components/comments/comment.less
Related Ticket: TINY-11294
* Fixes an issue where the after element would block clicks on anything below it like the kebab menu
Pre-checks:
Review:
> TINY-11294: Fixed CSS click through issue

- modules/oxide/src/less/theme/components/collection/collection.less
Related Ticket: TINY-11301
Added `:not(.tox-collection__item--state-disabled)` to enabled and active collection items to not apply styles on readonly mode.
Pre-checks:
Review:
> TINY-11301: add not state disabled to collection items styles

- modules/tinymce/src/plugins/autosave/main/ts/ui/Buttons.ts
Related Ticket: TINY-11326
* Follow up PR for ticket TINY-11264
* Disabling the `Restore last draft `button which was enabled in readonly mode
Pre-checks:
Review:
> TINY-11326: Disable restore last draft button in readonly mode

- modules/tinymce/src/core/test/ts/module/test/PasteEventUtils.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/ToolbarButtonContextTest.ts
Related Ticket: TINY-11024
* Fix test failure in CopyAndPasteTest.ts: e.data for input insertFromPaste with plain text is no longer null
Pre-checks:
Review:
> TINY-11024: Fix test failures for CopyAndPasteTest.ts

- .changes/unreleased/tinymce-TINY-11153-2024-10-03.yaml
- modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialogEvents.ts
Related Ticket: TINY-11153
We automatically blurred the ui when removing any modal dialog to prevent an issue with scrolling focus on safari if the focused dialog was removed. This fix will only blur the UI if the dialog has focus, preventing unneeded blurring and loss of UI in inline mode.
Manual test only, as the automated ones I made were highly unreliable and would succeed or fail randomly.
Pre-checks:
Review:
> TINY-11153: Only blur if the dialog has focus to start with.

- .changes/unreleased/tinymce-TINY-11313-2024-10-01.yaml
- modules/oxide/src/less/theme/components/toolbar-button/toolbar-split-button.less
Related Ticket: TINY-11313
Buttons like "Background Color" and "Text Color" were not fully greyed out in readonly mode.
Pre-checks:
Review:
> TINY-11313: apply opacity to color toolbar buttons in readonly mode

- .changes/unreleased/tinymce-TINY-11137-2024-10-01.yaml
- modules/tinymce/src/themes/silver/main/ts/modes/ScrollingContext.ts
- modules/tinymce/src/themes/silver/main/ts/ui/header/StickyHeader.ts
Related Ticket: TINY-11137
Added isFullscreen function to StickyHeader. Now, we don't apply offset if the editor is in fullscreen mode.
Pre-checks:
Review:
> TINY-11137: dont apply toolbar offset while in fullscreen

- .changes/unreleased/tinymce-TINY-11273-2024-09-24.yaml
- modules/tinymce/src/core/main/ts/autocomplete/AutocompleteUtils.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/autocomplete/AutocompleteTest.ts
Related Ticket: TINY-11273
When formatting is being applied a span with `zero width no-break space (ufeff)` is added to the editor. This character was not considered a whitespace and because of that the autocompleter was not triggering properly. To fix this bug I added the character to the `isWhitespace` function. 
Pre-checks:
Review:
> TINY-11273: add zero width nobreak space to isWhitespace function

- .changes/unreleased/tinymce-TINY-11395-2024-10-17.yaml
- modules/tinymce/src/core/main/ts/api/NotificationManager.ts
- modules/tinymce/src/core/test/ts/browser/NotificationManagerTest.ts
TINY-11395
- Changed the keyboard shortcut to a custom keyboard handler
Pre-checks:
Review:
> TINY-11395: Fix inability to type '{' character on German keyboard layouts

- .changes/unreleased/tinymce-GH-9599-2024-07-25.yaml
- modules/tinymce/src/themes/silver/main/ts/ui/core/color/Options.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/color/ColorSettingsTest.ts
Related Ticket: TINY-11385
Add support for CSS Variables in colour maps
https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties
Pre-checks:
Review:
- GH-9788
> Support the use of CSS variables in `color_map` (#9788)

- .changes/unreleased/tinymce-TINY-11344-2024-10-18.yaml
- modules/bridge/src/main/ts/ephox/bridge/components/content/ContextForm.ts
- modules/tinymce/src/themes/silver/main/ts/ui/context/ContextFormApi.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/contextform/ContextSizeInputFormTest.ts
Related Ticket: TINY-11344
implemented `contextForm.back` to restore the previous toolbar, to go back to the previous toolbar when we press back in the toolbar I added a function `contextForm.back` that use the event `backSlideEvent`.
since when we go in the context form we use [forwardSlideEvent](https://github.com/tinymce/tinymce/blob/main/modules/tinymce/src/themes/silver/main/ts/ui/context/ContextToolbar.ts#L139) so to go to the previous toolbar we need `backSlideEvent`
Pre-checks:
Review:
> TINY-11344: implement `contextForm.back` to restore the previous toolbar

- .changes/unreleased/tinymce-TINY-11437-2024-10-23.yaml
- modules/tinymce/src/core/main/ts/api/dom/ControlSelection.ts
- modules/tinymce/src/core/test/ts/browser/dom/ControlSelectionTest.ts
Related Ticket: TINY-11437
* Control selection on images was removed when calling nodeChange while the editor UI was focused
Pre-checks:
Review:
> TINY-11437: Fixed bug with nodeChanged while having UI focus

- modules/alloy/src/main/ts/ephox/alloy/ui/common/InputBase.ts
- modules/alloy/src/main/ts/ephox/alloy/ui/types/InputTypes.ts
- modules/tinymce/src/themes/silver/main/ts/ui/context/ContextFormSlider.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/contextform/ContextSliderFormTest.ts
Related Ticket: TINY-11428
* Fixes a type error where slider forms doesn't produce a number but a string
Pre-checks:
Review:
> TINY-11428: Fixed issue with slider not returning numbers

- .changes/unreleased/tinymce-TINY-11391-2024-10-28.yaml
- modules/tinymce/src/themes/silver/main/ts/ui/toolbar/button/ToolbarButtons.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/buttons/GroupToolbarButtonTest.ts
Related Ticket: TINY-11391
Add missing tooltipping for group toolbar buttons.
Pre-checks:
Review:
GitHub issues (if applicable): #9908
> TINY-11391: add tooltipping for group toolbar buttons

- Jenkinsfile
Related Ticket: TINY-11478
* Lock `lts` version to `node:20` in CI environments
Pre-checks:
Review:
> TINY-11478: Lock lts to node-20

- .changes/unreleased/tinymce-TINY-11390-2024-10-30.yaml
- modules/tinymce/src/core/main/ts/fmt/DefaultFormats.ts
- modules/tinymce/src/core/test/ts/browser/fmt/DefaultFormatsWithSchemaTest.ts
Related Ticket: [TINY-11390](https://ephocks.atlassian.net/browse/TINY-11390)
Removed `samp` from the list of elements being registered in `block` format as well as explicitly defining it as `inline`.
Pre-checks:
Review:
* ~[x] Docs ticket created (if applicable)~
GitHub issues (if applicable): [#7577
](https://github.com/tinymce/tinymce/issues/7577)
[TINY-11390]: https://ephocks.atlassian.net/browse/TINY-11390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TINY-11390: Avoid `samp` being registered as block format

- .changes/unreleased/tinymce-TINY-11470-2024-11-01.yaml
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/Tree.ts
Related Ticket: TINY-11470
Previously we set the title, which the browser will show as a tooltip in addition to our own tooltip. Removing the title will stop this double-tooltip from appearing.
Pre-checks:
Review:
> TINY-11470: Removed title attribute to prevent double tooltip.

- .changes/unreleased/katamari-TINY-7494-2024-11-08.yaml
- modules/katamari/src/test/ts/atomic/api/fun/FunTest.ts
Related Ticket: [TINY-7494](https://ephocks.atlassian.net/browse/TINY-7494)
Improve test clarity by splitting `FunTest` function tests into separate `it` blocks. 
Pre-checks:
Review:
* ~[x] Docs ticket created (if applicable)~
[TINY-7494]: https://ephocks.atlassian.net/browse/TINY-7494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TINY-7494: Split `FunTest` tests into separate `it` blocks for clarity

- .changes/unreleased/tinymce-TINY-9548-2024-11-08.yaml
- modules/tinymce/src/core/main/ts/file/Conversions.ts
- modules/tinymce/src/core/test/ts/browser/file/ConversionsTest.ts
Related Ticket: [TINY-9548](https://ephocks.atlassian.net/browse/TINY-9548)
Updated the way we are handling URL-encoded characters in base64 data by decoding them before processing.
Pre-checks:
Review:
* ~[x] Docs ticket created (if applicable)~
GitHub issues (if applicable): [#8400](https://github.com/tinymce/tinymce/issues/8400)
[TINY-9548]: https://ephocks.atlassian.net/browse/TINY-9548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TINY-9548: Handle URL-encoded characters in base64 data decoding

- .changes/unreleased/tinymce-TINY-11494-2024-11-07.yaml
- modules/bridge/src/main/ts/ephox/bridge/components/content/ContextForm.ts
- modules/tinymce/src/core/demo/ts/demo/ContextFormDemo.ts
- modules/tinymce/src/themes/silver/main/ts/ui/context/ContextFormSizeInput.ts
- modules/tinymce/src/themes/silver/main/ts/ui/context/ContextFormSlider.ts
- modules/tinymce/src/themes/silver/main/ts/ui/context/ContextFormTextInput.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/SizeInput.ts
- modules/tinymce/src/themes/silver/main/ts/ui/sizeinput/SizeInput.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/contextform/ContextFormTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/contextform/ContextSizeInputFormTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/contextform/ContextSliderFormTest.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/contexttoolbar/ContextToolbarLookupPrioritisationTest.ts
Related Ticket: TINY-11494
Added onSetup function to the context forms.
Pre-checks:
Review:
> TINY-11494: add onSetup function to context forms

- .changes/unreleased/tinymce-TINY-11515-2024-11-13.yaml
- modules/tinymce/src/plugins/advlist/main/ts/ui/Buttons.ts
- modules/tinymce/src/plugins/advlist/test/ts/browser/ListStyleAliasTest.ts
Related Ticket: TINY-11515
* When a list is either `lower-latin` or `upper-latin`, the "Lower Alpha" or "Upper Alpha" buttons will be highlighted in the split button dropdown
Pre-checks:
Review:
> TINY-11515: Update `advlist` plugin to recognise the `latin` list style type as an alias for the `alpha` list style type.

- modules/oxide/src/less/theme/components/comments/comment.less
Related Ticket: TINY-11510
* Adjust font size in the Comment input field to match the comment body font size
Pre-checks:
Review:
> TINY-11510:  Adjust font size in the Comment input field

- .changes/unreleased/tinymce-TINY-11498-2025-01-06.yaml
- modules/tinymce/src/themes/silver/main/ts/alien/NotificationManagerImpl.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/NotificationManagerImplTest.ts
Related Ticket:  TINY-11498
* Fixed condition to apply docking and call Docking.refresh when not using a sticky toolbar or when the toolbar is at the bottom
* When using a sticky toolbar that's located at the top, since we are attaching it to the anchor bar, there's no need to apply docking. It will stay attached as we scroll.
* When not using a sticky toolbar or when the toolbar is located at the bottom, we need the notification to be docked at the top of the window
Pre-checks:
Review:
> TINY-11498: Fix error with notifications when toolbar is at the bottom

- .changes/unreleased/tinymce-TINY-11446-2024-12-17.yaml
- modules/tinymce/src/core/main/ts/keyboard/PreventNoneditableInput.ts
Related Ticket: TINY-11446
* Checks if the `getTargetRanges` return ranges that have startContainer or endContainer not being in the body element.
* Didn't add at test since it pretty hard to simulate a internal browser shadowRoot element in theory we could try to use webdriver to type in a textbox inside a iframe but since we can barely type using webdriver in a regular textarea without flaking I opted to not do that.
Pre-checks:
Review:
> TINY-11446: Fixed issue with input in form elements

- modules/tinymce/src/core/test/ts/browser/FormatterRemoveTest.ts
- modules/tinymce/src/core/test/ts/browser/dom/SelectionTest.ts
Related Ticket: TINY-11837
* This fixes some tests that are broken on latest Safari
Pre-checks:
Review:
> TINY-11837: Fixed issue with Safari tests

- .changes/unreleased/tinymce-TINY-11368-2024-12-06.yaml
- modules/tinymce/src/themes/silver/main/ts/ui/button/MenuButton.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dialog/Tree.ts
- modules/tinymce/src/themes/silver/main/ts/ui/dropdown/CommonDropdown.ts
- modules/tinymce/src/themes/silver/main/ts/ui/general/Button.ts
- modules/tinymce/src/themes/silver/main/ts/ui/menus/menubar/SilverMenubar.ts
- modules/tinymce/src/themes/silver/main/ts/ui/toolbar/Integration.ts
- modules/tinymce/src/themes/silver/test/ts/headless/toolbar/SearchableMenuButtonPlaceholderTest.ts
- modules/tinymce/src/themes/silver/test/ts/headless/toolbar/SearchableMenuButtonTest.ts
- modules/tinymce/src/themes/silver/test/ts/headless/toolbar/ToolbarButtonsTest.ts
- modules/tinymce/src/themes/silver/test/ts/webdriver/toolbar/SearchableMenuTypingTest.ts
This reverts commit 5f4049f3045f4a8cf751a3dbb68a017738e119d6.
Related Ticket: TINY-11368
Reverting changes because of the bug reported here: https://ephocks.atlassian.net/browse/TINY-11368?focusedCommentId=144793
Pre-checks:
Review:
> TINY-11368: revert close dropdowns on window scroll (#10037)

- modules/tinymce/src/core/test/ts/browser/FormatterRemoveTest.ts
- modules/tinymce/src/core/test/ts/browser/dom/SelectionTest.ts
Related Ticket: TINY-11837
* So this will branch based on the minor version since it seems that LambdaTest has some machines running on 18.3 and some on older versions so if you get unlucky you get the older version.
Pre-checks:
Review:
> TINY-11837: Restored Safari test branching but with minor browser version testing

- .changes/unreleased/tinymce-TINY-11875-2025-02-25.yaml
- modules/oxide/src/less/theme/content/comments/comments.less
- modules/oxide/tasks/js-skins.js
Related Ticket: TINY-11875
* Added validation step in `gruntfile` to ensure that the minified CSS satisfy the condition or else it will fail
* Fixed error in the `comments.less` file
<details><summary>Sample message when build step fails:</summary>
<p>
<pre>
Running "cssmin:target" (cssmin) task
>> 22 sourcemaps created.
>> 22 files created. 724 kB → 627 kB
Running "generateJsSkins" task
Fatal error: Failed to create JS resource for ./build/skins/ui/dark/content.inline.min.css. Expected minified CSS contains 4 lines instead of the expected 2 or fewer.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "oxide-ci" exited with 1.
error Command failed with exit code 1.
info Visit …
> TINY-11875: Fix content css truncated when bundling, add validation to build step

- modules/oxide/package.json
- package.json
- yarn.lock
TINY-11878
- Recent dependency upgrade cased an import error, downgrade should fix it
Pre-checks:
Review:
> TINY-11878: Downgrade `chalk` version

- modules/tinymce/package.json
- modules/tinymce/src/core/main/ts/html/Sanitization.ts
- package.json
- patches/dompurify+3.2.4.patch
- yarn.lock
Related Ticket: TINY-11838
* A cherry pick of #10191 so we can include the dompurify update in the unscheduled 7.7.1 patch release
Pre-checks:
Review:
> TINY-11838: Update dompurify to 3.2.4

- .changes/unreleased/tinymce-TINY-11890-2025-02-26.yaml
- modules/tinymce/src/themes/silver/main/ts/ui/context/ContextFormTextInput.ts
- modules/tinymce/src/themes/silver/test/ts/browser/editor/contextform/ContextFormTest.ts
Related Ticket: TINY-11890
now the selection is moved to the first not-disabled button that make the toolbar not disapear
Pre-checks:
Review:
> TINY-11890: fix behavior when a context form has `setInputEnabled(false)` on init

- .github/CODEOWNERS
Related Ticket: TINY-11843
* Cherry-picking this commit to add functionality in release branch
Pre-checks:
Review:
> TINY-11843: Make docs team owner of changes (#10180)

- .changes/unreleased/tinymce-TINY-12021-2025-04-09.yaml
- modules/katamari/src/main/ts/ephox/katamari/api/Id.ts
- modules/katamari/src/main/ts/ephox/katamari/util/IdUtilts.ts
- modules/katamari/src/test/ts/atomic/api/data/IdTest.ts
- modules/tinymce/src/core/main/ts/api/Editor.ts
- modules/tinymce/src/core/main/ts/api/EditorManager.ts
- modules/tinymce/src/core/test/ts/browser/EditorManagerTest.ts
Related Ticket: TINY-12021
* Add `uuidV4` generator to katamari `Id` module
* Add `pageUid` to tinymce global (more specifically the EditorManager)
* Add `editorUId` to editor instance object
Pre-checks:
Review:
* ~~[X] Docs ticket created (if applicable)~~
> TINY-12021: Add pageUid and editorUid properties

- modules/tinymce/src/core/main/ts/SelectionOverrides.ts
- modules/tinymce/src/core/test/ts/browser/caret/FakeCaretImageCaptionTest.ts
Related Ticket: TINY-11997
I fixed the bug with the selection overrides in Firefox but I couldn't test it since the tests for this override aren't working for Firefox (the `TinySelections.setRawSelection` used to simulate the `tab` doesn't work in Firefox), so I just improved a little bit the one for Chrome
EDIT: I removed the check for Firefox since the check `editor.selection.getNode() === editor.getBody()` doesn't need any additional check
Pre-checks:
Review:
> TINY-11997: fix caret position on Firefox

- .changes/unreleased/tinymce-TINY-12131-2025-05-13.yaml
- modules/oxide/src/less/theme/components/form/select.less
Related Ticket: TINY-12131
Fixed select styles overwitten by css reset for chrome version 136
Pre-checks:
Review:
> TINY-12131: fix select styles overwitten by css reset

- .changes/unreleased/tinymce-TINY-12092-2025-05-13.yaml
- modules/tinymce/src/core/main/ts/api/html/Schema.ts
- modules/tinymce/src/core/test/ts/browser/html/DomParserTest.ts
- modules/tinymce/src/core/test/ts/browser/html/SchemaTest.ts
- modules/tinymce/src/models/dom/test/ts/browser/table/PasteTableTest.ts
Related Ticket: TINY-12092
* Adding to `blockElementsMap` so the whitespaces around `colgroup` and `col` elements
Pre-checks:
Review:
> TINY-12092: DomParser not removing whitespace around `colgroup` and `col` elements

- modules/tinymce/src/themes/silver/main/ts/Deprecations.ts
Related Ticket: TINY-12087
* Added migration URL for ToggleToolbarDrawer deprecation message
* Created a constant for the migration guide URL
* Updated the skipFocus deprecation message to use the new URL constant
Pre-checks:
Review:
> TINY-12087: add migration guide URL

- modules/tinymce/src/core/main/ts/api/OptionTypes.ts
- modules/tinymce/src/core/main/ts/api/Options.ts
- modules/tinymce/src/core/main/ts/api/PublicApi.ts
- modules/tinymce/src/core/main/ts/lookup/UserLookup.ts
- modules/tinymce/src/core/test/ts/browser/lookup/UserLookupTest.ts
Related Ticket: [TINY-11974](https://ephocks.atlassian.net/browse/TINY-11974)
* Upon using the `UserLookup` API we discovered that knowing which promise in the `Promise<User>[]` belonged to which user was difficult as we would need to wait for a promise to resolve before knowing its `id`. We've revised the return type to be a `Record<UserId, Promise<User>>` such that even if the promise hasn't been resolved, we will always know which promise is associated with a specific user. The tests were also updated accordingly to work with this new expected return type.
* We also added centralized avatar generation logic, removing the need for a custom implementation across various plugins.
Pre-checks:
Review:
[TINY-11974]: …
> TINY-11974: Update return type of `fetchUsers` and add avatar generation logic

- modules/oxide/src/less/theme/components/suggestededits/suggestededits.less
- modules/oxide/src/less/theme/content-ui.less
- modules/oxide/src/less/theme/content/suggestededits/suggestededits.less
Related Ticket: TINY-12210, TINY-12063
* Moving content css of suggested edits to oxide content css
* Should only be visible in suggested edits view, but would be visible with the right classes
* No support for dark mode due to limitations in global variable usage and contrast calculation
* Using a darker color for dark mode will result in that color being used in light mode as it is higher contrast
* There is no workaround for this and the design is impossible to fully implement
* For now we will only support light mode, but integrators can customize this with their own CSS
* Fixed issue with videos missing highlighting
Pre-checks:
Review:
> TINY-12210: Move Suggested Edits content CSS to oxide

- modules/tinymce/src/core/test/ts/browser/content/EditorContentTest.ts
Related Ticket: TINY-12379
A quick story of this problem:
1. During `setContent` we encode attribute values. `<` is replaced by `&lt;` and `>` is replaced by `&gt;`
2. During `getContent({ type: 'raw' })` we return `innerHTML` from editor's `body`
3. Different browsers return different results in this case
4. The recent firefox update on CI from 139 to 140 had to change this behavior. Also `chrome-headless` and `chrome` handle those differently.
Proof:
Run this line on Firefox, Safari, Chrome, compare results.
```
new DOMParser().parseFromString('<div data-some-attribute="title=&lt;br/&gt;"></div>', 'text/html').body.innerHTML;
```
Fix explained:
1. In the test case I removed `{ type: 'raw' }`
2. This is causing the editor to use our own serializer instead of …
> TINY-12379: fix broken preserve attributes with self closed HTML tags test on Firefox

- .changes/unreleased/tinymce-TINY-12462-2025-07-07.yaml
- modules/tinymce/src/plugins/pagebreak/main/ts/api/Options.ts
Related Ticket: TINY-12462
* Change default value of `pagebreak_split_block`  to true
Pre-checks:
Review:
> TINY-12462: Change default value of `pagebreak_split_block`  to true

- .changes/unreleased/tinymce-TINY-12289-2025-07-15.yaml
- modules/oxide/src/less/theme/components/revisionhistory/revisionhistory.less
- modules/oxide/src/less/theme/components/suggestededits/suggestededits.less
- modules/oxide/src/less/theme/components/view/view.less
- modules/oxide/src/less/theme/globals/global-variables.less
Related Ticket: TINY-12289
* Added `z-index` to work around issues where tooltips show on top of a view. The proper fix, to make them hide correctly, will come later.
* Swapped from `margin-top` on view content to `padding-bottom` on the view toolbar (which just means using a single `padding` value)
* Applied those changes to suggested edits manually, since it doesn't leverage the tox view classes
Pre-checks:
Review:
> TINY-12289: Add a z-index to views, moving them above sink elements

- modules/oxide/src/less/theme/content/suggestededits/suggestededits.less
Related Ticket: TINY-12257
* Improve contrast of `<hr>` in review edits view for better visibility 
Pre-checks:
Review:
> TINY-12257:  Improve contrast of <hr> in review edits view for better visibility 

- modules/oxide/src/less/theme/content/suggestededits/suggestededits.less
Related Ticket: TINY-12257
* Fix styling issues of `mce-pagebreak` in Review Edits view 
<details>
<summary>Screenshot</summary>
Not selected: 
Selected:
</details>
Pre-checks:
Review:
> TINY-12257: Fix `pagebreak` image styles in Review Edits view

- tsconfig.shared.json
Related Ticket: TINY-12807
- Removing `useVerbatimModuleSyntax`​ for now as need to do more investigation to make sure it is not negatively effecting bundle size
Pre-checks:
Review:
> TINY-12807: Remove useVerbatimModuleSyntax from tsconfig

- modules/tinymce/src/themes/silver/main/ts/ui/menus/menubar/Integration.ts
Related Ticket: TINY-12880
add video in `insert` menu
Pre-checks:
Review:
> TINY-12880: add `video` item in `Insert` menu
